force-app/main/default/objects/Trade_Event__c/Trade_Event__c.object-meta.xml
<CustomObject>
    <label>Trade Event</label>
    <nameField>
        <label>Trade Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade_Event_Attendee__c/Trade_Event_Attendee__c.object-meta.xml
<CustomObject>
    <description>Junction Object</description>
    <label>Trade Event Attendee</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Trade Event Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade_Event_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tourism Contact</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tourism Contact</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Leasing Contact</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand Contact</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>HNW Event Attendee</value>
        </filterItems>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>VIP Guest</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trade Events Attended</relationshipLabel>
    <relationshipName>Trade_Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Trade_Event_Attendee__c/fields/Followed_Up__c.field-meta.xml
<CustomField>
    <fullName>Followed_Up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Followed Up</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trade_Event_Attendee__c/fields/Invite_Status__c.field-meta.xml
<CustomField>
    <fullName>Invite_Status__c</fullName>
    <defaultValue>&quot;Invited&quot;</defaultValue>
    <label>Invite Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Added</fullName>
            </value>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade_Event_Attendee__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <formula>Contact__r.Title</formula>
    <label>Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trade_Event_Attendee__c/fields/Trade_Event__c.field-meta.xml
<CustomField>
    <fullName>Trade_Event__c</fullName>
    <label>Trade Event</label>
    <referenceTo>Trade_Event__c</referenceTo>
    <relationshipLabel>Trade Event Attendees</relationshipLabel>
    <relationshipName>Trade_Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Trade_Event_Attendee__c/fields/Trade_Event_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Trade_Event_Attendee__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; Id,  Contact__r.FirstName + &quot; &quot; +  Contact__r.LastName  ,&quot;_self&quot;)</formula>
    <label>Trade Event Attendee</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MassEditTradeEventAttendees.cls
public with sharing class MassEditTradeEventAttendees {

    //test
    public id recordId {get;set;}
    Public list<Trade_Event_Attendee__c> registeredAttendees {get;set;}
    Public List<cTradeAttendee> attendeesToEdit {get;set;}
    public Trade_Event_Attendee__c selectOptions {get;set;}

    public MassEditTradeEventAttendees(ApexPages.StandardController standardController) {
        selectOptions = new Trade_Event_Attendee__c();
        recordId = standardController.getId();
        attendeesToEdit = new list<cTradeAttendee>();
        registeredAttendees = [SELECT ID, Name,Contact__c,Invite_Status__c,Followed_Up__c,Title__c  FROM Trade_Event_Attendee__c WHERE Trade_Event__c =:recordId ORDER BY Name ASC ];
        system.debug('registeredAttendees' + registeredAttendees);
            for (Trade_Event_Attendee__c TEA : registeredAttendees ){
                system.debug('test');
                attendeesToEdit.add(new cTradeAttendee(TEA));
            }
    }


    Public Pagereference Cancel() {
    PageReference pageRef = new PageReference('/'+recordId);
        return pageRef;
    }



    Public Pagereference saveSelected() {
        list<Trade_Event_Attendee__c> TEAUpdates = new List<Trade_Event_Attendee__c>();
            for(cTradeAttendee cTEA: attendeesToEdit) {
                    if(cTEA.selected == true) {
                        TEAUpdates.add(cTEA.attendee); 
                    }
            }        
        update TEAUpdates;        
        PageReference pageRef = new PageReference('/'+recordId);
        return pageRef;
    }


    Public Pagereference selectAll() {
        for(cTradeAttendee cTEA : attendeesToEdit){
            cTEA.selected = true;
        }
     
    //PageReference pageRef = new PageReference('/'+recordId);
        return null;
    }

    Public Pagereference deselectAll() {
        for(cTradeAttendee cTEA : attendeesToEdit){
            cTEA.selected = false;
        }
     
    //PageReference pageRef = new PageReference('/'+recordId);
        return null;
    }

    Public Pagereference setAllStatus() {
        for(cTradeAttendee cTEA : attendeesToEdit){
            cTEA.attendee.Invite_Status__c = selectOptions.Invite_Status__c;
        }
     
    //PageReference pageRef = new PageReference('/'+recordId);
        return null;
    }


    Public Pagereference setAllFollowUps() {
        for(cTradeAttendee cTEA : attendeesToEdit){
            cTEA.attendee.Followed_Up__c = selectOptions.Followed_Up__c;
        }
     
    //PageReference pageRef = new PageReference('/'+recordId);
        return null;
    }





    public class cTradeAttendee{
        public Trade_Event_Attendee__c attendee {get; set;}
        public Boolean selected {get; set;}

        public cTradeAttendee(Trade_Event_Attendee__c tea) {
            attendee = tea;
            selected = false;

        }
    }
}