force-app/main/default/objects/Competitor_Visit__c/Competitor_Visit__c.object-meta.xml
<CustomObject>
    <label>Competitor Visit</label>
    <nameField>
        <displayFormat>CV-{0000000}</displayFormat>
        <label>Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Visit__c/fields/Share_Site_Visit_Info__c.field-meta.xml
<CustomField>
    <fullName>Share_Site_Visit_Info__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When Checked this Site Visit Report will be shared across the business.</inlineHelpText>
    <label>Share Site Visit Info</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/competitorSiteVisitTriggerHandler.cls
public class competitorSiteVisitTriggerHandler{


    public static void handleBeforeInsert(){
    
    }
    
    
    public static void handleAfterInsert(){
    
    }
    
    
    public static void handleBeforeUpdate(){
    
    }
    
    
    public static void handleAfterUpdate(map<id, Competitor_Visit__c> oldVisitMap, map<id,Competitor_Visit__c> newVisitMap){
    
        list<id> sharedCompSiteVisits = new list<id>();
    
        for(Id id : newVisitMap.keyset()){
            if(newVisitmap.get(id).Share_Site_Visit_Info__c == true){
                if(newVisitmap.get(id).Share_Site_Visit_Info__c != oldVisitmap.get(id).Share_Site_Visit_Info__c){
                    sharedCompSiteVisits.add(newVisitmap.get(id).id);
                }
            }
        }
    
        if(sharedCompSiteVisits.size() > 0 && sharedCompSiteVisits != null){
             compSiteVisitEmailHandler.sendEmails(sharedCompSiteVisits);
        }
         
    }

}