force-app/main/default/objects/Campaign/fields/Communication_Channel__c.field-meta.xml
<CustomField>
    <fullName>Communication_Channel__c</fullName>
    <inlineHelpText>Select which channels the Campaign will be distributed</inlineHelpText>
    <label>Communication Channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Publication</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Postal</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Leaflet/Coupon</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Face-to-face</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Other Media (TV/Radio)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Contact_Details_Required__c.field-meta.xml
<CustomField>
    <fullName>Contact_Details_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select this option if contact details are required for a redemption</inlineHelpText>
    <label>Contact Details Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Multi_Channel_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Multi_Channel_Campaign__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Select this option if the same campaign barcode will be used across all channels</inlineHelpText>
    <label>Multi-Channel Campaign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Multi_Village_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Multi_Village_Campaign__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select this option if the same campaign barcode will be valid across multiple Villages</inlineHelpText>
    <label>Multi-Village Campaign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Parent_Campaign_ID__c.field-meta.xml
<CustomField>
    <fullName>Parent_Campaign_ID__c</fullName>
    <description>Value is entered when a Redeemable Campaign is created using the Wizard.</description>
    <inlineHelpText>Only populated if the group (parent) campaign is a multi-village campaign</inlineHelpText>
    <label>Parent Campaign ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>only valid for redeemable campaigns</description>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Villages__c.field-meta.xml
<CustomField>
    <fullName>Villages__c</fullName>
    <inlineHelpText>Select the Village(s) in which this Campaign will be valid for</inlineHelpText>
    <label>Villages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RedeemableCampaignWizardControllerTest.cls
@isTest
public class RedeemableCampaignWizardControllerTest{

//properties
Private Static Campaign multiChannelCampaign = new Campaign(); 
Private Static Campaign singleChannelCampaign = new Campaign();
Private Static Campaign DuplicateRedeemableCampaign = new Campaign();
    
private static string village = 'Test Village'; 
private static village__c testvillage = new village__c();
private static id GroupCampRecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Group Campaign').getRecordTypeId();
private static id RedeemableCampRecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Redeemable Campaign').getRecordTypeId();    
private static integer countOfPromotions;
  
    
    public static testMethod void multiChannelCampaignTest()
    {
        //setup test data
        setupdata(false);
        
        PageReference pg = new PageReference('Page.RedeemableCampaignWizard');
            pg.getParameters().put('id', multiChannelCampaign.Id);
            test.setCurrentPageReference(pg);

        test.startTest();
            RedeemableCampaignWizardController controller = new RedeemableCampaignWizardController();
            controller.SubmitCampaigns();
        test.stopTest();
        
        //Asserts
        //There should be just one campaign inserted as there 
        //is one village and it's a multi-channel campaign
         list<campaign> insertedCampaigns = [SELECT id, Contact_Details_Required__c, parent_campaign_id__c
                                            FROM Campaign 
                                            WHERE RecordTypeId = :RedeemableCampRecordTypeId];
        system.assertEquals(1, insertedCampaigns.size() );
        
        //contact details should NOT be required for this multi channel campaign
        system.assertEquals(false , insertedCampaigns[0].Contact_Details_Required__c);
        
    }
    
    public static testMethod void singleChannelCampaignTest()
    {
        //setup test data
        setupdata(false);
        
        PageReference pg = new PageReference('Page.RedeemableCampaignWizard');
            pg.getParameters().put('id', singleChannelCampaign.Id);
            test.setCurrentPageReference(pg);

        test.startTest();
            RedeemableCampaignWizardController controller = new RedeemableCampaignWizardController();
        
            controller.getGroupCampaignName();
            controller.SubmitCampaigns();
            controller.getCampaigns();

        test.stopTest();
        //Asserts
        //There should be two campaigns inserted as there 
        //is one village but it's a single-channel campaign
        list<campaign> insertedCampaigns = [SELECT id, Contact_Details_Required__c, parent_campaign_id__c
                                            FROM Campaign 
                                            WHERE RecordTypeId = :RedeemableCampRecordTypeId];
        system.assertEquals(2, insertedCampaigns.size() );
        
        //contact details should be required
         system.assertEquals(true , insertedCampaigns[0].Contact_Details_Required__c);
        
        //it's also a multi-village campaign so make sure the parent Id is populated
        //so that it is SOSL searchable.
        system.assertEquals(singleChannelCampaign.Id , insertedCampaigns[0].parent_campaign_id__c ); 
        
        //tack on this additional test
        controller.Cancel2();
    }
    
 
     public static testMethod void singleChannelCampaignTest2() // non UI context
    {
        //setup test data
        setupdata(false);

        test.startTest();
            RedeemableCampaignWizardController controller = new RedeemableCampaignWizardController(singleChannelCampaign.Id);
        
            controller.getGroupCampaignName();
            controller.SubmitCampaigns();
            controller.getCampaigns();

        test.stopTest();
        //Asserts
        //There should be two campaigns inserted as there 
        //is one village but it's a single-channel campaign
        list<campaign> insertedCampaigns = [SELECT id, Contact_Details_Required__c, parent_campaign_id__c
                                            FROM Campaign 
                                            WHERE RecordTypeId = :RedeemableCampRecordTypeId];
        system.assertEquals(2, insertedCampaigns.size() );
        
        //contact details should be required
         system.assertEquals(true , insertedCampaigns[0].Contact_Details_Required__c);
        
        //it's also a multi-village campaign so make sure the parent Id is populated
        //so that it is SOSL searchable.
        system.assertEquals(singleChannelCampaign.Id , insertedCampaigns[0].parent_campaign_id__c ); 
        
        //tack on this additional test
        controller.Cancel2();
    }
       
    
    
    
 ////////////////////////data setup/////////////////////////////   
        static void setupdata(boolean createduplicate)
    {
        //Setup new test Village
        testvillage.Name = village;
        testvillage.Village_Code__c = 'TV';
		testvillage.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		testvillage.CertSales_Report_Sales_Grace_Period_Days__c = 1; 
        insert testvillage;
                      
        //new multi channel Group campaign  
        multiChannelCampaign.Contact_Details_Required__c = false;
        multiChannelCampaign.Name = 'My Test Group Campaign';
        multiChannelCampaign.Communication_Channel__c = 'Email;SMS';
        multiChannelCampaign.Status = 'In Progress' ;
        multiChannelCampaign.isActive = true;
        multiChannelCampaign.Villages__c = village;
        multiChannelCampaign.description = 'This is my test Group campaign description';
        multiChannelCampaign.startdate = Date.today();
        multiChannelCampaign.enddate = Date.today()+3;
        multiChannelCampaign.RecordTypeId = GroupCampRecordTypeId;
        multiChannelCampaign.Multi_Channel_Campaign__c = true;
        multiChannelCampaign.Multi_Village_Campaign__c = false;
        insert multiChannelCampaign;
        
        //new single channel Group campaign   
        singleChannelCampaign.Contact_Details_Required__c = true;
        singleChannelCampaign.Name = 'My Test Group Campaign';
        singleChannelCampaign.Communication_Channel__c = 'Email;SMS';
        singleChannelCampaign.Status = 'In Progress' ;
        singleChannelCampaign.isActive = true;
        singleChannelCampaign.Villages__c = village;
        singleChannelCampaign.description = 'This is my test Group campaign description';
        singleChannelCampaign.startdate = Date.today();
        singleChannelCampaign.enddate = Date.today()+3;
        singleChannelCampaign.RecordTypeId = GroupCampRecordTypeId;
        singleChannelCampaign.Multi_Channel_Campaign__c = false;
        singleChannelCampaign.Multi_Village_Campaign__c = true;
        insert singleChannelCampaign;
        
         if (createduplicate)
        {
            DuplicateRedeemableCampaign.Contact_Details_Required__c = true;
            DuplicateRedeemableCampaign.Name = 'My Test RedeemableCampaign';
            DuplicateRedeemableCampaign.Communication_Channel__c = 'Email';
            //DuplicateRedeemableCampaign.Status = 'In Progress' ;
            //DuplicateRedeemableCampaign.isActive = true;
            DuplicateRedeemableCampaign.Village__c = testvillage.id;
            DuplicateRedeemableCampaign.description = 'This is my test Group campaign description';
            DuplicateRedeemableCampaign.startdate = Date.today();
            DuplicateRedeemableCampaign.enddate = Date.today()+3;
            DuplicateRedeemableCampaign.RecordTypeId = RedeemableCampRecordTypeId;
            DuplicateRedeemableCampaign.ParentID = singleChannelCampaign.id;
            
            insert DuplicateRedeemableCampaign;
        
        }
        
    }
    
    
    
}