force-app/main/default/objects/Campaign/fields/Communication_Channel__c.field-meta.xml
<CustomField>
    <fullName>Communication_Channel__c</fullName>
    <inlineHelpText>Select which channels the Campaign will be distributed</inlineHelpText>
    <label>Communication Channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Publication</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Postal</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Leaflet/Coupon</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Face-to-face</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Other Media (TV/Radio)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>only valid for redeemable campaigns</description>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/Promotion_Redemption__c.object-meta.xml
<CustomObject>
    <description>A new record is created when a tourism redemption is claimed. the numbers role up in to Tourism Promotion</description>
    <label>Promotion Redemption</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Redemption ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Redemptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotion_Redemption__c/fields/Redeem_Date__c.field-meta.xml
<CustomField>
    <fullName>Redeem_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Redeem Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/fields/Redeemable_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Redeemable_Campaign__c</fullName>
    <label>Redeemable Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Redemptions</relationshipLabel>
    <relationshipName>Redemptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/fields/Voucher_Code__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Code__c</fullName>
    <description>This is the &quot;scan out&quot; code of the voucher (VIP card)</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter the VIP card code</inlineHelpText>
    <label>Voucher Code</label>
    <length>55</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PromotionRedemptionTriggerHelperTest.cls
@isTest
public class PromotionRedemptionTriggerHelperTest{

//properties
Private Static Campaign multiChannelCampaign = new Campaign(); 
private static string village = 'Test Village'; 
private static village__c testvillage = new village__c();
private static id RedeemableCampRecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Redeemable Campaign').getRecordTypeId();
private static integer countOfPromotions;
 
    
    public static testMethod void duplicateRedemptionTest()
    {
    	setupdata();
        Promotion_Redemption__c  firstPromoRedemption = new Promotion_Redemption__c(
                                                            voucher_code__c = '14xxxxxxxxxxxx',
                                                            redeem_date__c = date.today(),
                                                            Redeemable_Campaign__c = multiChannelCampaign.Id);
        
        Promotion_Redemption__c  secondPromoRedemption = new Promotion_Redemption__c(
                                                            voucher_code__c = '14xxxxxxxxxxxx',
                                                            redeem_date__c = date.today(),
                                                            Redeemable_Campaign__c = multiChannelCampaign.Id);
        test.startTest();
            insert firstPromoRedemption;
            
        	//ensure the insert went in
            countOfPromotions = [SELECT count() FROM Promotion_Redemption__c 
                                 WHERE voucher_code__c = :firstPromoRedemption.voucher_code__c];
            system.assertEquals(1, countOfPromotions);
            
        	//insert a duplicate
        	insert 	secondPromoRedemption;
       		test.stopTest();
        
        	//ensure there is still only one record with the '14xxxxxxxxxxxx' voucher code
            countOfPromotions = [SELECT count() FROM Promotion_Redemption__c 
                                WHERE voucher_code__c = :firstPromoRedemption.voucher_code__c];
            system.assertEquals(1, countOfPromotions);
    }


	static void setupdata()
    {
        //Setup new test Village
        testvillage.Name = village;
        testvillage.Village_Code__c = 'TV';
		testvillage.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		testvillage.CertSales_Report_Sales_Grace_Period_Days__c = 1; 
        insert testvillage;
                      
        //new redeemable campaign    
        multiChannelCampaign.Name = 'My Test Group Campaign';
        multiChannelCampaign.Communication_Channel__c = 'Email';
        multiChannelCampaign.Status = 'In Progress' ;
        multiChannelCampaign.isActive = true ;
        multiChannelCampaign.Village__c = testvillage.id;
        multiChannelCampaign.description = 'This is my test campaign';
        multiChannelCampaign.startdate = Date.today();
        multiChannelCampaign.enddate = Date.today()+3;
        multiChannelCampaign.RecordTypeId = RedeemableCampRecordTypeId;
        
        insert multiChannelCampaign;
    }

    
}