force-app/main/default/objects/Campaign/fields/Group_Booking__c.field-meta.xml
<CustomField>
    <fullName>Group_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group Booking</label>
    <referenceTo>Group_Booking__c</referenceTo>
    <relationshipLabel>Redemption Campaign</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/Group_Booking__c.object-meta.xml
<CustomObject>
    <description>Tourism (B2T) Object :: Used for recording MICE group bookings</description>
    <label>Booking/Partnership</label>
    <nameField>
        <displayFormat>GBI{0000000000}</displayFormat>
        <label>Group Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings/Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Booking__c/fields/Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Activity</label>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipName>Group_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Old_Redemption_Campaign_ID__c.field-meta.xml
<CustomField>
    <fullName>Old_Redemption_Campaign_ID__c</fullName>
    <inlineHelpText>If the Booking/Partnership was migrated over from an old campaign record, enter the ID here (starts with 701...)</inlineHelpText>
    <label>Old Redemption Campaign ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/Old_Redemption_Campaign_ID__c.field-meta.xml
<CustomField>
    <fullName>Old_Redemption_Campaign_ID__c</fullName>
    <label>Old Redemption Campaign ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/Promotion_Redemption__c.object-meta.xml
<CustomObject>
    <description>A new record is created when a tourism redemption is claimed. the numbers role up in to Tourism Promotion</description>
    <label>Promotion Redemption</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Redemption ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Redemptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotion_Redemption__c/fields/Country_of_Origin__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Origin__c</fullName>
    <label>Country of Residence</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>British Indian Ocean Territory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/fields/customer__c.field-meta.xml
<CustomField>
    <fullName>customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>b2c_customer__c</referenceTo>
    <relationshipLabel>Redeemed Promotions</relationshipLabel>
    <relationshipName>Promotion_Redemptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/fields/Redeem_Date__c.field-meta.xml
<CustomField>
    <fullName>Redeem_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Redeem Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/fields/Redeemable_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Redeemable_Campaign__c</fullName>
    <label>Redeemable Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Redemptions</relationshipLabel>
    <relationshipName>Redemptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <label>Visit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Leisure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/fields/Voucher_Code__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Code__c</fullName>
    <description>This is the &quot;scan out&quot; code of the voucher (VIP card)</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter the VIP card code</inlineHelpText>
    <label>Voucher Code</label>
    <length>55</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>v-{00000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Country_of_Origin__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Origin__c</fullName>
    <label>Country of Residence</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Republic of Ireland</fullName>
            </value>
            <value>
                <fullName>Russian Federation</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
            </value>
            <value>
                <fullName>Refuse to Answer</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Group_Booking__c.field-meta.xml
<CustomField>
    <fullName>Group_Booking__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Booking/Partnership</label>
    <referenceTo>Group_Booking__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter name of Marketing Promotion that resulted in this VIP Account being created.</inlineHelpText>
    <label>Marketing Activity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Marketing_Activity__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partnership Promotion</value>
        </filterItems>
        <filterItems>
            <field>Marketing_Activity__c.Is_Live__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Marketing_Activity__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipLabel>Visits (Marketing Activity)</relationshipLabel>
    <relationshipName>Visits1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Leisure</fullName>
            </value>
            <value>
                <fullName>MICE</fullName>
            </value>
            <value>
                <fullName>Drop-In</fullName>
            </value>
            <value>
                <fullName>Invite by VR chairman</fullName>
            </value>
            <value>
                <fullName>Invite by VR Management</fullName>
            </value>
            <value>
                <fullName>Invite by brand</fullName>
            </value>
            <value>
                <fullName>VIP Shopping Day</fullName>
            </value>
            <value>
                <fullName>Tourism</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Action / Charity</fullName>
            </value>
            <value>
                <fullName>1 to 1 Personal Shopping Appointment</fullName>
            </value>
            <value>
                <fullName>Group Personal Shopping Appointment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RememptionMigrationHandler.cls
global class RememptionMigrationHandler implements Database.Batchable<sObject>, Database.Stateful{

    global String query;
    global map<id,id> batchcampaignid2newActivityidMap = new map<id,id> ();
    global string batchObjectType = '';
    global list<string> batchidSet;
    
    global RememptionMigrationHandler(id maId){
        batchidSet = new list<string>();
        batchidSet.add(maId);
    }
            
    global Database.QueryLocator start(Database.BatchableContext BC)
    {

        system.debug('MigrateRedemptions Fired. List to process: ' + batchidSet);

        list<group_booking__c> GroupBookingList= new list<group_booking__c> ();
        list<Marketing_Activity__c> MarketingActivityList= new list<Marketing_Activity__c> ();
        //id1 = redeemablecampaignid, id2 = newobjectid

//******discover object type and setup campaignid2newActivityidMap which maps the Redemtion_Campaign_id to groupbBooking/markActy********
        If (batchidSet.get(0).left(3) == 'a0U'){
            batchobjectType = 'GroupBooking';
            GroupBookingList = [SELECT id, Old_Redemption_Campaign_ID__c
                                FROM group_booking__c
                                WHERE id in :batchidSet];
            for(group_booking__c gb : GroupBookingList)
            {
                batchcampaignid2newActivityidMap.put(gb.Old_Redemption_Campaign_ID__c, gb.id );
                
            }
           
        }
        else if (batchidSet[0].left(3) == 'a0y') {
            batchobjectType = 'MarketingActivity';
            MarketingActivityList = [SELECT id, Old_Redemption_Campaign_ID__c 
                                    FROM Marketing_Activity__c
                                    WHERE id in :batchidSet];
            for(Marketing_Activity__c ma : MarketingActivityList)
            {
                batchcampaignid2newActivityidMap.put(ma.Old_Redemption_Campaign_ID__c, ma.id );
            }   
        }
        else{
            batchobjectType = '';
        }
                                                         
                                                                
        set<Id> idList = batchcampaignid2newActivityidMap.keySet(); 
        query = 'SELECT id, Voucher_Code__c, Redeem_Date__c,Visit_Type__c,';
        query += 'Redeemable_Campaign__c,CreatedDate,';       
        query += 'Country_of_Origin__c, customer__r.email__c,Location__c,';
        query += 'Mode_of_Transport__c, Redeemable_Campaign__r.Transfer_Code__c,';
        query += 'Redeemable_Campaign__r.Village__c, Redeemable_Campaign__r.VIP_2_0_Activity_ID__c';
        query += ' FROM Promotion_Redemption__c';
        query += ' WHERE Redeemable_Campaign__r.VIP_2_0_Activity_ID__c = null';
        query += ' AND Redeemable_Campaign__r.Transfer_Code__c in : idList';
                                                        
system.debug('@@@@ query ... ' + query); 
system.debug('@@@@ batchcampaignid2newActivityidMap ... ' + batchcampaignid2newActivityidMap);
                                                       
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC,List<Sobject> scope)
    {

 
  //********End of campaignid2newActivityidMap mapping setup******************
 

            map<id, Sobject> Promoid2fullrecordMap = new Map<Id, Sobject>(scope);  


system.debug('@@@ scope ... ' + scope);
system.debug('@@@@ Promoid2fullrecordMap ' + Promoid2fullrecordMap );

system.debug('@@@@ batchcampaignid2newActivityidMap ... 2 .. ' + batchcampaignid2newActivityidMap);
   
            map<string, list<string>> vouchercodeMap = new map<string, list<string>>();
            //loop through all the promo redemptions
            for ( Sobject cpr : Promoid2fullrecordMap.values()){

system.debug('@@@ cpr ... ' + cpr);
system.debug('@@@ vip activity 1 .. ' + string.valueOf(cpr.getSobject('Redeemable_Campaign__r').get('Transfer_Code__c')));
                
                //id newVIPActivity = campaignid2newActivityidMap.get(cpr.Redeemable_Campaign__c);//gets the new VIP activity object ID
                id newVIPActivity = batchcampaignid2newActivityidMap.get(string.valueOf(cpr.getSobject('Redeemable_Campaign__r').get('Transfer_Code__c')));//gets the new VIP activity object ID

                system.debug('newVIPActivity: ' + newVIPActivity);
                
                string key =  string.valueOf(cpr.getSobject('Redeemable_Campaign__r').get('Transfer_Code__c')) + '~' +  string.valueOf(cpr.get('CreatedDate'))  + '~' +  string.valueOf(cpr.get('Mode_of_Transport__c'));
                       key += '~' + string.valueOf(cpr.get('Country_of_Origin__c'));
                       key += '~' + string.valueOf(cpr.getSobject('Redeemable_Campaign__r').get('Village__c')) + '~' + newVIPActivity + '~' + string.valueOf(cpr.get('Location__c')) ;
                
                list<string> voucherCodes =  vouchercodeMap.get(key);
                
                if (voucherCodes==null)
                {
                    voucherCodes = new list<string>();
                }
                
                voucherCodes.add(string.valueOf(cpr.get('Voucher_Code__c')));
                vouchercodeMap.put(key, voucherCodes);  
            }
            
           list<visit__c> NewVisitList = new  list<visit__c>();
           
            for(string cVisit:vouchercodeMap.keyset()){
              
                list<string> visitFields = cVisit.split('~');
            
                visit__c newVisit = new visit__c();
                //visitFields[1] is 2015-08-13 00:00:00
                list<string> dateandtimecomponents = visitFields[1].split(' ');
                list<string> datecomponents = dateandtimecomponents[0].split('-');
                list<string> timecomponents = dateandtimecomponents[1].split(':');
                
                system.debug('unformatted date: ' + visitFields[1]);
                DateTime formateddatetime = DateTime.newInstanceGMT(integer.valueOf(datecomponents[0]), integer.valueOf(datecomponents[1]), integer.valueOf(datecomponents[2]), 
                                                                    integer.valueOf(timecomponents[0]), integer.valueOf(timecomponents[1]), integer.valueOf(timecomponents[2]));
                system.debug('Check in date/time: ' + formateddatetime);
                
                
                newVisit.Visit_Date_Time__c = formateddatetime;
               
                if (visitFields[2] != 'null')
                                            newVisit.Mode_of_Transport__c = visitFields[2];
                if (visitFields[3] != 'null')
                                            newVisit.Country_of_Origin__c  = visitFields[3];
                
                newVisit.Village__c = visitFields[4];
                
                if (batchobjectType == 'GroupBooking'){
                    newVisit.Group_Booking__c = visitFields[5];
                }
                else if (batchobjectType == 'MarketingActivity'){
                    newVisit.Partnership_Promotion__c = visitFields[5];
                }
               newVisit.Migration_Key__c = cvisit; 
               newVisit.type__c = 'Leisure';
               
                if (visitFields[6] != 'null') 
                                 newVisit.Location__c = visitFields[6];
                
               NewVisitList.add(newVisit);
            
            }//end of loop through  vouchercodeMap.keyset 
        insert NewVisitList;
system.debug('@@@ NewVisitList ... ' + NewVisitList);        
                    
      list<visit__c> InsertedVisits = [SELECT id, Migration_Key__c from visit__c where  Migration_Key__c in :vouchercodeMap.keyset() ] ; 
            
            list<VIP_Card_Exchange__c> exchangeList = new list<VIP_Card_Exchange__c>();
                
                for(visit__c v : InsertedVisits ){
                   list<string> VIPcodes = vouchercodeMap.get(v.Migration_Key__c);
                       for (string VIPcode :VIPcodes ){
                           VIP_Card_Exchange__c iVIP = new VIP_Card_Exchange__c();
                           iVIP.Offer_Type__c = 'VIP Card';
                           iVIP.VIP_Card_Code__c = VIPcode;
                           iVIP.Visit__c = v.id;   
                       
                           exchangeList.add(iVIP); 
                       }    
                }
             insert exchangeList;
system.debug('@@@ exchangeList ... ' + exchangeList);        
            //Lock old campaigns (mark them as transfered)
            list<campaign> transferedcampaigns = [SELECT id, Transfer_Code__c, VIP_2_0_Activity_ID__c  FROM campaign
                                                  WHERE Transfer_Code__c in : batchcampaignid2newActivityidMap.keySet()];
            
            for(campaign c: transferedcampaigns){
                c.VIP_2_0_Activity_ID__c = batchcampaignid2newActivityidMap.get(c.Transfer_Code__c);
            }
            update transferedcampaigns;
            



          
    }

    global void finish(Database.BatchableContext BC)
    {
    
    }
                
    @future
    public static void MigrateRedemptions(list<string> idSet)
    {
        system.debug('MigrateRedemptions Fired. List to process: ' + idSet);
        string ObjectType; 
        list<group_booking__c> GroupBookingList= new list<group_booking__c> ();
        list<Marketing_Activity__c> MarketingActivityList= new list<Marketing_Activity__c> ();
        //id1 = redeemablecampaignid, id2 = newobjectid
        map<id,id> campaignid2newActivityidMap = new map<id,id> ();

//******discover object type and setup campaignid2newActivityidMap which maps the Redemtion_Campaign_id to groupbBooking/markActy********
        If (idSet.get(0).left(3) == 'a0U'){
            ObjectType = 'GroupBooking';
            GroupBookingList = [SELECT id, Old_Redemption_Campaign_ID__c
                                FROM group_booking__c
                                WHERE id in :idSet];
            for(group_booking__c gb : GroupBookingList)
            {
                campaignid2newActivityidMap.put(gb.Old_Redemption_Campaign_ID__c, gb.id );
                
            }
           
        }
        else if (idSet[0].left(3) == 'a0y') {
            ObjectType = 'MarketingActivity';
            MarketingActivityList = [SELECT id, Old_Redemption_Campaign_ID__c 
                                    FROM Marketing_Activity__c
                                    WHERE id in :idSet];
            for(Marketing_Activity__c ma : MarketingActivityList)
            {
                campaignid2newActivityidMap.put(ma.Old_Redemption_Campaign_ID__c, ma.id );
            }   
        }
        else{
            ObjectType = '';
        }
  //********End of campaignid2newActivityidMap mapping setup******************
 
        if (string.isNotBlank(ObjectType))
        {
      
            
        //map of promo redemptions. The id part can translate to booking/activity using the campaignid2newActivityidMap     
        map<id, Promotion_Redemption__c> Promoid2fullrecordMap =  new map<Id,Promotion_Redemption__c>( [
                                                        SELECT id, Voucher_Code__c, Redeem_Date__c,Visit_Type__c,
                                                        Redeemable_Campaign__c,CreatedDate,
                                                        Country_of_Origin__c, customer__r.email__c,Location__c,
                                                        Mode_of_Transport__c, Redeemable_Campaign__r.Transfer_Code__c,
                                                        Redeemable_Campaign__r.Village__c, Redeemable_Campaign__r.VIP_2_0_Activity_ID__c
                                                        FROM Promotion_Redemption__c
                                                        WHERE Redeemable_Campaign__r.VIP_2_0_Activity_ID__c = null
                                                        AND Redeemable_Campaign__r.Transfer_Code__c in :campaignid2newActivityidMap.keyset()]);
   
            map<string, list<string>> vouchercodeMap = new map<string, list<string>>();
            //loop through all the promo redemptions
            for ( Promotion_Redemption__c cpr : Promoid2fullrecordMap.values()){
                
                //id newVIPActivity = campaignid2newActivityidMap.get(cpr.Redeemable_Campaign__c);//gets the new VIP activity object ID
                id newVIPActivity = campaignid2newActivityidMap.get(cpr.Redeemable_Campaign__r.Transfer_Code__c);//gets the new VIP activity object ID
                system.debug('looking up cpr.Redeemable_Campaign__c in map: ' + cpr.Redeemable_Campaign__c);
                system.debug('cprID: ' + cpr.Id);
                system.debug('newVIPActivity: ' + newVIPActivity);
                
                string key =  cpr.Redeemable_Campaign__r.Transfer_Code__c + '~' +  cpr.CreatedDate  + '~' +  cpr.Mode_of_Transport__c + '~' + cpr.Country_of_Origin__c;
                       key += '~' + cpr.Redeemable_Campaign__r.Village__c + '~' + newVIPActivity + '~' + cpr.Location__c ;
                
                list<string> voucherCodes =  vouchercodeMap.get(key);
                
                if (voucherCodes==null)
                {
                    voucherCodes = new list<string>();
                }
                
                voucherCodes.add(cpr.Voucher_Code__c);
                vouchercodeMap.put(key, voucherCodes);  
            }
            
           list<visit__c> NewVisitList = new  list<visit__c>();
           
            for(string cVisit:vouchercodeMap.keyset()){
              
                list<string> visitFields = cVisit.split('~');
            
                visit__c newVisit = new visit__c();
                //visitFields[1] is 2015-08-13 00:00:00
                list<string> dateandtimecomponents = visitFields[1].split(' ');
                list<string> datecomponents = dateandtimecomponents[0].split('-');
                list<string> timecomponents = dateandtimecomponents[1].split(':');
                
                system.debug('unformatted date: ' + visitFields[1]);
                DateTime formateddatetime = DateTime.newInstanceGMT(integer.valueOf(datecomponents[0]), integer.valueOf(datecomponents[1]), integer.valueOf(datecomponents[2]), 
                                                                    integer.valueOf(timecomponents[0]), integer.valueOf(timecomponents[1]), integer.valueOf(timecomponents[2]));
                system.debug('Check in date/time: ' + formateddatetime);
                
                
                newVisit.Visit_Date_Time__c = formateddatetime;
               
                if (visitFields[2] != 'null')
                                            newVisit.Mode_of_Transport__c = visitFields[2];
                if (visitFields[3] != 'null')
                                            newVisit.Country_of_Origin__c  = visitFields[3];
                
                newVisit.Village__c = visitFields[4];
                
                if (ObjectType == 'GroupBooking'){
                    newVisit.Group_Booking__c = visitFields[5];
                }
                else if (ObjectType == 'MarketingActivity'){
                    newVisit.Partnership_Promotion__c = visitFields[5];
                }
               newVisit.Migration_Key__c = cvisit; 
               newVisit.type__c = 'Leisure';
               
                if (visitFields[6] != 'null') 
                                 newVisit.Location__c = visitFields[6];
                
               NewVisitList.add(newVisit);
            
            }//end of loop through  vouchercodeMap.keyset 
        insert NewVisitList;
            
      list<visit__c> InsertedVisits = [SELECT id, Migration_Key__c from visit__c where  Migration_Key__c in :vouchercodeMap.keyset() ] ; 
            
            list<VIP_Card_Exchange__c> exchangeList = new list<VIP_Card_Exchange__c>();
                
                for(visit__c v : InsertedVisits ){
                   list<string> VIPcodes = vouchercodeMap.get(v.Migration_Key__c);
                       for (string VIPcode :VIPcodes ){
                           VIP_Card_Exchange__c iVIP = new VIP_Card_Exchange__c();
                           iVIP.Offer_Type__c = 'VIP Card';
                           iVIP.VIP_Card_Code__c = VIPcode;
                           iVIP.Visit__c = v.id;   
                       
                           exchangeList.add(iVIP); 
                       }    
                }
             insert exchangeList;
        
            //Lock old campaigns (mark them as transfered)
            list<campaign> transferedcampaigns = [SELECT id, Transfer_Code__c, VIP_2_0_Activity_ID__c  FROM campaign
                                                  WHERE Transfer_Code__c in : campaignid2newActivityidMap.keySet()];
            
            for(campaign c: transferedcampaigns){
                c.VIP_2_0_Activity_ID__c = campaignid2newActivityidMap.get(c.Transfer_Code__c);
            }
            update transferedcampaigns;
            
        }//end of isNotBlank(ObjectType) IF
        
            
        
    }
    
}