force-app/main/default/objects/Campaign/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>only valid for redeemable campaigns</description>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/Promotion_Redemption__c.object-meta.xml
<CustomObject>
    <description>A new record is created when a tourism redemption is claimed. the numbers role up in to Tourism Promotion</description>
    <label>Promotion Redemption</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Redemption ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Redemptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotion_Redemption__c/fields/Country_of_Origin__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Origin__c</fullName>
    <label>Country of Residence</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>British Indian Ocean Territory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TIC</fullName>
                <default>true</default>
                <label>TIC</label>
            </value>
            <value>
                <fullName>Train Station</fullName>
            </value>
            <value>
                <fullName>Coach Pod</fullName>
            </value>
            <value>
                <fullName>VIP Lounge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <label>Mode of Transport</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Train</fullName>
            </value>
            <value>
                <fullName>Car</fullName>
            </value>
            <value>
                <fullName>Large Coach</fullName>
            </value>
            <value>
                <fullName>Small Coach</fullName>
            </value>
            <value>
                <fullName>Taxi</fullName>
            </value>
            <value>
                <fullName>Private Hire</fullName>
            </value>
            <value>
                <fullName>Public Bus</fullName>
            </value>
            <value>
                <fullName>Shopping Express</fullName>
            </value>
            <value>
                <fullName>Refuse to Answer</fullName>
            </value>
            <value>
                <fullName>Walking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/fields/Redeem_Date__c.field-meta.xml
<CustomField>
    <fullName>Redeem_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Redeem Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/fields/Redeemable_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Redeemable_Campaign__c</fullName>
    <label>Redeemable Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Redemptions</relationshipLabel>
    <relationshipName>Redemptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <label>Visit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Leisure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/fields/Voucher_Code__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Code__c</fullName>
    <description>This is the &quot;scan out&quot; code of the voucher (VIP card)</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter the VIP card code</inlineHelpText>
    <label>Voucher Code</label>
    <length>55</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <description>Mode of Transport</description>
    <inlineHelpText>Mode of Transport</inlineHelpText>
    <label>Mode of Transport</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>v-{00000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Country_of_Origin__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Origin__c</fullName>
    <label>Country of Residence</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Republic of Ireland</fullName>
            </value>
            <value>
                <fullName>Russian Federation</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
            </value>
            <value>
                <fullName>Refuse to Answer</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TIC</fullName>
            </value>
            <value>
                <fullName>TIC Satellite</fullName>
            </value>
            <value>
                <fullName>Train Station</fullName>
            </value>
            <value>
                <fullName>Coach Pod</fullName>
            </value>
            <value>
                <fullName>VIP Lounge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <label>Mode of Transport</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Train</fullName>
            </value>
            <value>
                <fullName>Car</fullName>
            </value>
            <value>
                <fullName>Large Coach</fullName>
            </value>
            <value>
                <fullName>Small Coach</fullName>
            </value>
            <value>
                <fullName>Taxi</fullName>
            </value>
            <value>
                <fullName>Private Hire</fullName>
            </value>
            <value>
                <fullName>Public Bus</fullName>
            </value>
            <value>
                <fullName>Shopping Express</fullName>
            </value>
            <value>
                <fullName>Refuse to Answer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Leisure</fullName>
            </value>
            <value>
                <fullName>MICE</fullName>
            </value>
            <value>
                <fullName>Drop-In</fullName>
            </value>
            <value>
                <fullName>Invite by VR chairman</fullName>
            </value>
            <value>
                <fullName>Invite by VR Management</fullName>
            </value>
            <value>
                <fullName>Invite by brand</fullName>
            </value>
            <value>
                <fullName>VIP Shopping Day</fullName>
            </value>
            <value>
                <fullName>Tourism</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Action / Charity</fullName>
            </value>
            <value>
                <fullName>1 to 1 Personal Shopping Appointment</fullName>
            </value>
            <value>
                <fullName>Group Personal Shopping Appointment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <label>Standard</label>
</RecordType>

force-app/main/default/classes/transferRedemptionsBatchable.cls
/*
-----How to Call this batchable Class from Dev Console-------
DateTime startDate = Datetime.newInstance(2015,6,12,0,0,0); 
DateTime endDate = Datetime.newInstance(2016,6,30,0,0,0);
transferRedemptionsBatchable myBatchObject = new transferRedemptionsBatchable('701b0000000YSFH',startDate,endDate);     WHERE Arg1 = Campaign Id
Id batchId = Database.executeBatch(myBatchObject);  
*/

global class transferRedemptionsBatchable implements Database.Batchable<sObject> {

    global Integer recordsProcessed = 0;

    private string campaignid;
    private Datetime thisStartDate;
    private Datetime thisEndDate;
    
    

    global transferRedemptionsBatchable(string campid, Datetime startDate, Datetime endDate){
        campaignid = campid;
        thisStartDate = startDate;
        thisEndDate = endDate;
        //System.debug('Start Date = ' + String.valueOf(startDate));
        //System.debug('End Date = ' + String.valueOf(endDate));
        
    }


    global Database.QueryLocator start(Database.BatchableContext bc) {
      String sql = 'SELECT Id,visit_type__c,mode_of_transport__c,Country_of_Origin__c, ' +
                 
                 'Voucher_Code__c,Redeem_Date__c,Location__c,Redeemable_Campaign__r.Village__c,Redeemable_Campaign__r.VIP_2_0_Activity_ID__c FROM Promotion_Redemption__c ' +
                 
                 'Where Redeemable_Campaign__c =\'' + campaignid + '\' AND Has_Been_Transfered__c = False AND Redeem_Date__c >= ' + thisStartDate.format('yyyy-MM-dd')  + ' AND Redeem_date__c <= ' + thisEndDate.format('yyyy-MM-dd') + ' ' ;
                 System.debug('This SQL = ' + sql);
            return Database.getQueryLocator(sql); 
        }
        
    
    global void execute(Database.BatchableContext bc, List<Promotion_Redemption__c> records){
    
    boolean error = FALSE;
    system.debug('class records '+records);
    
    LIST<Visit__c> visits = new LIST<Visit__c>();
    LIST<Visit__c> newVisits = new LIST<Visit__c>();
    LIST<Promotion_Redemption__c> updatedReds = new LIST<Promotion_Redemption__c>();
    LIST<VIP_Card_Exchange__c> newVIPCards = new LIST<VIP_Card_Exchange__c>();
    

    recordtype recordtypeid = [SELECT id from Recordtype WHERE name = 'Standard' AND sobjectType = 'Visit__c'];  
           for(Promotion_Redemption__c oldReds : records){             
               
               visit__c v = new Visit__c();
               v.recordtypeid= recordtypeid.id;
               v.Partnership_Promotion__c = oldReds.Redeemable_Campaign__r.VIP_2_0_Activity_ID__c;
               v.village__c = oldReds.Redeemable_Campaign__r.Village__c;
               v.type__c = 'Leisure';   
               v.Visit_Date_Time__c = oldReds.Redeem_Date__c;  
               v.mode_of_transport__c = oldReds.mode_of_transport__c;
               v.country_of_origin__c = oldReds.Country_of_Origin__c;  
               v.location__c = oldReds.location__c; 
               v.number_of_guests__c = 1;
               v.Visit_Notes__c = oldReds.Voucher_Code__c;
               visits.add(v);
               
               oldReds.Has_Been_Transfered__c = TRUE;
               updatedREDS.add(oldReds);
       
           }
       Try{
       system.debug('class visits ' + visits);
       system.debug('class reds ' + updatedReds);
       insert visits;
       update updatedReds;
       }catch(exception ex){
       error = true;
       throw ex;
       }
       //-----------------------------------------
       if(!error){
       LIST<Campaign> updatedcamp = [SELECT id, VIP_2_0_Activity_ID__c,Redemptions_Transfered__c,village__c FROM Campaign WHERE id =:campaignid];
       updatedcamp[0].Redemptions_Transfered__c = updatedcamp[0].Redemptions_Transfered__c + updatedreds.size();
       update updatedcamp[0];
   
           for(Visit__c vis :visits){
           
           VIP_Card_Exchange__c VIP = new VIP_Card_Exchange__c();
           VIP.Visit__c = vis.id;
           VIP.VIP_Card_Code__c = vis.Visit_Notes__c;
           newVIPCards.add(VIP);
                     
           }
           
           insert newVIPCards;
           recordsProcessed = recordsProcessed + 1;
           
        }
    }
    
    global void finish(Database.BatchableContext bc){
   System.debug(recordsProcessed + ' records processed. Shazam!');

   
   }
    
    
}