force-app/main/default/objects/Campaign/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>only valid for redeemable campaigns</description>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Tourism.recordType-meta.xml
<RecordType>
    <fullName>Tourism</fullName>
    <active>true</active>
    <description>All Tourism Responsys campaigns</description>
    <label>Tourism</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Primary_Relationship_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Relationship_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box if the Contact is the one that should recieve account emails</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/Group_Booking__c.object-meta.xml
<CustomObject>
    <description>Tourism (B2T) Object :: Used for recording MICE group bookings</description>
    <label>Booking/Partnership</label>
    <nameField>
        <displayFormat>GBI{0000000000}</displayFormat>
        <label>Group Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings/Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Booking__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the name of the company or agency responsible for organising this event</inlineHelpText>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Please select a Tourism or Marketing Partner.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Tourism</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Marketing_Partner</value>
        </filterItems>
        <infoMessage>Please select a Tourism or Marketing Partner.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings/Partnerships</relationshipLabel>
    <relationshipName>Group_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Please indicate the Status of the booking</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Proposed</fullName>
                <default>true</default>
                <label>Proposed</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipName>Bookings_Partnerships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/recordTypes/Group_Booking.recordType-meta.xml
<RecordType>
    <fullName>Group_Booking</fullName>
    <active>true</active>
    <description>A booking for a fixed date/time that a group of guests are scheduled to arrive</description>
    <label>Group Booking</label>
</RecordType>

force-app/main/default/objects/Group_Source__c/Group_Source__c.object-meta.xml
<CustomObject>
    <label>Group Source</label>
    <nameField>
        <label>Group Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group Sources</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Source__c/fields/Revenue_per_Visitor__c.field-meta.xml
<CustomField>
    <fullName>Revenue_per_Visitor__c</fullName>
    <label>Revenue per Visitor</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Group_Source__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Group</fullName>
            </value>
            <value>
                <fullName>European Cross Border Group</fullName>
            </value>
            <value>
                <fullName>Long Haul</fullName>
            </value>
            <value>
                <fullName>Meetings</fullName>
            </value>
            <value>
                <fullName>Special Events</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Group_Source__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Group Sources</relationshipLabel>
    <relationshipName>Group_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/recordTypes/Partnership_Promotion.recordType-meta.xml
<RecordType>
    <fullName>Partnership_Promotion</fullName>
    <active>true</active>
    <description>QR Code...</description>
    <label>Partnership Promotion</label>
</RecordType>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>...</description>
    <inlineHelpText>Select the Village is this campaign related to</inlineHelpText>
    <label>Village</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>notEqual</operation>
            <value>Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Village Campaign</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/recordTypes/Village_Campaign.recordType-meta.xml
<RecordType>
    <fullName>Village_Campaign</fullName>
    <active>true</active>
    <description>A Marketing Brief for a Village&apos;s Campaign..</description>
    <label>Village Campaign</label>
</RecordType>

force-app/main/default/objects/Tourism_Partner_Projection__c/Tourism_Partner_Projection__c.object-meta.xml
<CustomObject>
    <description>Projected Tourism partner visit contributions</description>
    <label>Tourism Partner Projection</label>
    <nameField>
        <displayFormat>TPP-{000000}</displayFormat>
        <label>Tourism Partner Projection Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tourism Partner Projections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/Partnership_Account__c.field-meta.xml
<CustomField>
    <fullName>Partnership_Account__c</fullName>
    <description>The Tourism partner</description>
    <inlineHelpText>The Tourism partner</inlineHelpText>
    <label>Partnership Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Tourism accounts can have projections</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tourism</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tourism Partner Projections</relationshipLabel>
    <relationshipName>Tourism_Partner_Projections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/Projected_Year__c.field-meta.xml
<CustomField>
    <fullName>Projected_Year__c</fullName>
    <description>The year for which the projections are</description>
    <inlineHelpText>The year for which the projections are</inlineHelpText>
    <label>Projected Year</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
                <default>true</default>
                <label>2020</label>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
                <isActive>false</isActive>
                <label>2017</label>
            </value>
            <value>
                <fullName>2018</fullName>
                <isActive>false</isActive>
                <label>2018</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>The village that this projection is for</description>
    <inlineHelpText>The village that this projection is for</inlineHelpText>
    <label>Village</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Village</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Organisation__c</fullName>
    <description>The business unit within oracle</description>
    <inlineHelpText>The business unit within oracle</inlineHelpText>
    <label>Oracle Organisation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Source_Template_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Source_Template_Number__c</fullName>
    <description>The value used to map to an oracle template when sent to Oracle Fusion</description>
    <inlineHelpText>The value used to map to an oracle template when sent to Oracle Fusion</inlineHelpText>
    <label>Oracle Source Template Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>v-{00000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Village.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bicester</fullName>
    </customValue>
    <customValue>
        <fullName>Fidenza</fullName>
    </customValue>
    <customValue>
        <fullName>Ingolstadt</fullName>
    </customValue>
    <customValue>
        <fullName>Kildare</fullName>
    </customValue>
    <customValue>
        <fullName>La Roca</fullName>
    </customValue>
    <customValue>
        <fullName>Las Rozas</fullName>
    </customValue>
    <customValue>
        <fullName>La Vallée</fullName>
    </customValue>
    <customValue>
        <fullName>Maasmechelen</fullName>
    </customValue>
    <customValue>
        <fullName>Shanghai</fullName>
    </customValue>
    <customValue>
        <fullName>Suzhou</fullName>
    </customValue>
    <customValue>
        <fullName>Wertheim</fullName>
    </customValue>
    <description>A list of all the villages</description>
    <masterLabel>Village</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TourismPartnerProjectionsTest.cls
@isTest
private class TourismPartnerProjectionsTest
{
    @TestSetup
    public static void SetupData(){
        
        // first create a village
        Village__c vill = TestDataGenerator.setupVillage(false);
        vill.Oracle_Source_Template_Number__c = '123456';
        vill.Oracle_Organisation__c = 'SourceOrg';
        vill.Name = 'Bicester';
		vill.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		vill.CertSales_Report_Sales_Grace_Period_Days__c = 1; 
        insert vill;

    
          Account testAccount = new Account(name = 'Test Account' , RecordTypeId =  Schema.SObjectType.Account.RecordTypeInfosByDeveloperName.get('Tourism').RecordTypeId);
          insert testAccount;

            Contact con1 = new contact(AccountId = testAccount.id, FirstName = 'Test1', LastName = 'Test1', email = 'test1@valueretail.com',Primary_Relationship_Contact__c = true);
            insert con1;
            
            String ThisYear = String.valueOf(date.today().year());

            Group_Source__c grpsrc = new Group_Source__c();
            grpsrc.Revenue_per_Visitor__c = 120.00;
            grpsrc.Source__c = 'Domestic Group';
            grpsrc.Village__c = vill.Id;
            insert grpsrc;

          // then we also need to add the Tourism Partner Projection
          Tourism_Partner_Projection__c TPP = new Tourism_Partner_Projection__c();
          TPP.Partnership_Account__c = testAccount.Id;
          TPP.Village__c = vill.Name;
          TPP.Projected_Year__c = ThisYear;
          TPP.Status__c = 'New';
          TPP.Group_or_Village_Projection__c = 'Group Projection';
          TPP.Visitor_Source__c = grpsrc.ID;
          insert TPP;

        id grpBookingRecordTypeId = Schema.SObjectType.Group_Booking__c.RecordTypeInfosByDeveloperName.get('Group_Booking').RecordTypeId;
        id promoRecordTypeId = Schema.SObjectType.Marketing_Activity__c.RecordTypeInfosByDeveloperName.get('Partnership_Promotion').RecordTypeId;
        
        //id promoRecordTypeId = Schema.SObjectType.Marketing_Activity__c.RecordTypeInfosByName.get('Village Partnership Promotion').RecordTypeId; 
        Map <String,Schema.RecordTypeInfo> recordTypesadjustment = Marketing_Campaign__c.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName();
        //System.assertEquals(1,2,recordTypesadjustment);
        Id RecTypeIdinadj = recordTypesadjustment.get('Village_Campaign').getRecordTypeId();
        
        
        Marketing_Activity__c partnerPromo = null;
        Marketing_Campaign__c marketingCampaign = null;
        Group_Booking__c oneOffBooking = null;    
        Group_Booking__c individualsPartnership = null; 
        
        
        marketingCampaign = new Marketing_Campaign__c();
        marketingCampaign.Start_Date__c = system.today();
        marketingCampaign.End_Date__c = system.today().addDays(30);
        marketingCampaign.Name = 'Test Campaign';
        marketingCampaign.RecordTypeId = RecTypeIdinadj;
        marketingCampaign.Village__c = vill.Id;
		marketingCampaign.Campaign_Level__c = 'Theme';
        insert marketingCampaign;
        
        partnerPromo = new Marketing_Activity__c();
        partnerPromo.Start_Date__c = system.today();
        partnerPromo.End_Date__c = system.today().addDays(10);
        partnerPromo.Name = 'Test Village promo';
        partnerPromo.Marketing_Campaign__c = marketingCampaign.Id;
        partnerPromo.Partner__c = testAccount.Id;
        
        partnerPromo.recordTypeId = promoRecordTypeId;
        insert partnerPromo;          
        
        oneOffBooking = new Group_Booking__c();
        oneOffBooking.Name_of_Event__c= 'Test one off booking for TPP';
        oneOffBooking.recordTypeId = grpBookingRecordTypeId;
        oneOffBooking.Status__c = 'Confirmed';
        oneOffBooking.Village__c = vill.Id;
        oneOffBooking.Expected_Arrival__c = system.today();
        oneOffBooking.Expected_Departure__c = system.now();
        oneOffBooking.visitors_country_of_origin__c = 'China';
        oneOffBooking.expected_mode_of_transport__c = 'Train';
        oneOffBooking.group_type__c  ='Leisure';
        oneOffBooking.Organisation__c = testAccount.Id;
        insert oneOffBooking;
        
        // setup complete
    }
    
    @isTest
    static void checkVisitAppearsInTPP()
    {
        List<Group_Booking__c> groupBookings = [Select ID, Name FROM Group_Booking__c WHERE Name_of_Event__c = 'Test one off booking for TPP'];
        System.assert(groupBookings != null, 'groupBooking is null');
        System.assertEquals(groupBookings.Size(),1, 'groupBooking count is not 1');
        
        Group_Booking__c groupBooking = groupBookings[0];
        Test.StartTest();
        //  we should have a visit, we can edit it to make it 'check in', and this should calculate the Tourism Partner Projection
        Visit__c visit = [select Id from Visit__c where Group_Booking__c = :groupBooking.Id];
        System.assert(visit != null, 'Visit is null');
        
        // lets edit the visit to say that the people arrived
        DateTime CheckoutOn = System.Now().addHours(4);
        
        visit.Visit_Date_Time__c = System.Now();
        visit.Check_Out_Date_Time__c = CheckoutOn;
        visit.Number_of_Guests__c = 25;
        
        update visit;
        Test.StopTest();
        // this should trigger the updating process, and roll up the numbers
        // lets re-get the TPP and see if the number of guests have been updated...
        String ThisYear = String.valueOf(date.today().year());
        //String TPPName = 'Test Account' + ' for ' + ThisYear + ' for Bicester';
        Account act = [select id, name from Account WHERE name = 'Test Account'];
        
        //List<Tourism_Partner_Projection__c> TPProjections = [Select ID, Name,Total_Actual_Pax__c FROM Tourism_Partner_Projection__c WHERE Name = :TPPName] ;
        List<Tourism_Partner_Projection__c> TPProjections = [Select ID, Name,Total_Actual_Pax__c FROM Tourism_Partner_Projection__c WHERE Partnership_Account__c =:act.id] ;
        System.assert(TPProjections != null, 'TPProjections is null');
        System.assertEquals(1,TPProjections.Size(), 'TPProjections count is not 1');
        
        // now we need to see that the 'month' number has been incremented.....
        System.assertEquals(TPProjections[0].Total_Actual_Pax__c,25,'Total_Actual_Pax__c must be 25');
    }
    
}