force-app/main/default/objects/Campaign/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>only valid for redeemable campaigns</description>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <inlineHelpText>The budget for the Marketing Activity</inlineHelpText>
    <label>Marketing Activity Budget</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter a End date where you expect the activity to stop impacting footfall/Sales in the Village.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Marketing_Activity_Ref__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity_Ref__c</fullName>
    <displayFormat>MA-{000000}</displayFormat>
    <externalId>true</externalId>
    <label>Marketing Activity Ref</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <description>....</description>
    <label>Marketing Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You cannot link an activity to a &apos;Cancelled&apos;  Campaign.</errorMessage>
        <filterItems>
            <field>Marketing_Campaign__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Activities</relationshipLabel>
    <relationshipName>Marketing_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter a date where you expect the activity to impact footfall/Sales in the Village. This is not necessarily the date the email is being sent</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Transfer_To_Oracle__c.field-meta.xml
<CustomField>
    <fullName>Transfer_To_Oracle__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Allows the activity to be transferred to Oracle Projects</description>
    <inlineHelpText>Allow the activity to be transferred to Oracle Projects</inlineHelpText>
    <label>Transfer To Oracle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/Campaign_Level__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Level__c</fullName>
    <description>Tactical is the norm.

Add &quot;Theme&quot; or &quot;BAU&quot; when required - keep it off so users can only choose Tactical and no validations are required.</description>
    <inlineHelpText>The Campaing Level...</inlineHelpText>
    <label>Campaign Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Theme</fullName>
            </value>
            <value>
                <fullName>BAU Campaign</fullName>
            </value>
            <value>
                <fullName>Non-Campaign</fullName>
            </value>
            <value>
                <fullName>Lead Moment</fullName>
            </value>
            <value>
                <fullName>Local Moment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter the End Date of the Campaign</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Marketing_Campaign_Ref__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign_Ref__c</fullName>
    <displayFormat>MC-{00000}</displayFormat>
    <externalId>true</externalId>
    <label>Marketing Campaign Ref</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Parent_Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Parent_Marketing_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a Parent Marketing Campaign</inlineHelpText>
    <label>Parent Marketing Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Parent Campaigns must be TBVSC Brand Campaigns</errorMessage>
        <filterItems>
            <field>Marketing_Campaign__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <infoMessage>Please select a TBVSC Brand Campaign</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <inlineHelpText>Enter a short description about the Campaign</inlineHelpText>
    <label>Short Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter the Start Date of the Campaign</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Transfer_To_Oracle__c.field-meta.xml
<CustomField>
    <fullName>Transfer_To_Oracle__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Allows the Campaign data to be sent to Oracle Projects</description>
    <inlineHelpText>Allow the Campaign data to be sent to Oracle Projects</inlineHelpText>
    <label>Transfer To Oracle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>...</description>
    <inlineHelpText>Select the Village is this campaign related to</inlineHelpText>
    <label>Village</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>notEqual</operation>
            <value>Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Village Campaign</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Village_Marketing_Budget__c.field-meta.xml
<CustomField>
    <fullName>Village_Marketing_Budget__c</fullName>
    <label>Village Campaign Budget</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/Oracle_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Organisation__c</fullName>
    <description>The business unit within oracle</description>
    <inlineHelpText>The business unit within oracle</inlineHelpText>
    <label>Oracle Organisation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Source_Template_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Source_Template_Number__c</fullName>
    <description>The value used to map to an oracle template when sent to Oracle Fusion</description>
    <inlineHelpText>The value used to map to an oracle template when sent to Oracle Fusion</inlineHelpText>
    <label>Oracle Source Template Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/marketingCampaignActionsControllerExt.cls
public with sharing class marketingCampaignActionsControllerExt {


    //edit Campaign Level on marketing Campaign Object
    private ApexPages.StandardController stdController;
    public String Option { get; set; }
    public marketing_Campaign__c MC { get; set; }
    public List<SelectOption> Options { get;set;}
    public String selectedOption { get; set; }
    public boolean shouldredirect {get;set;}
    public string redirectURL {get;set;}
    public boolean showLevelButton {get;set;}
   
    // Oracle Sync Section
    // private final Marketing_Campaign__c mysObject;
    public Boolean displayError {public get; private set;}
    public String errorMessage {public get; public set;}
    public Boolean displayWarning {public get; private set;}
    public String warningMessage {public get; public set;}
    public Boolean displayMessage {public get; private set;}
    public String pageMessage {public get; public set;}
    public Boolean showCSVButton {public get; private set;}
    public Boolean showCSVProjButton {public get; private set;}

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public marketingCampaignActionsControllerExt(ApexPages.StandardController stdController) {
    
        showLevelButton = False;
        showCSVButton = false;
        showCSVProjButton = false;
        // set all messages as default false
        displayError = false;
        displayWarning = false;
        displayMessage = false;
    
        List<PermissionSetAssignment> usersPerms = [SELECT ID,PermissionSet.Name FROM PermissionSetAssignment WHERE AssigneeId = :Userinfo.getUserId()];
        for(PermissionSetAssignment perm :usersPerms){
            if(perm.PermissionSet.Name == 'Edit_Marketing_Campaign_Level_Themes_Lead_Group_Tactical'){
                showLevelButton = true;
            }
            if(perm.PermissionSet.Name == 'Sync_Marketing_Campaigns'){
                showCSVButton = true;
                showCSVProjButton = true;
            }
            //System.debug('perm ==== ' + perm + '------' + perm.PermissionSet.Name);
        }

        this.MC = (marketing_Campaign__c)stdController.getRecord();

        if(showLevelButton){
            this.stdController = stdController; 
          //  stdController.addFields(new List<String>{'Campaign_Level__c'});
          Marketing_Campaign__c Camp = [Select ID, Name, Campaign_Level__c FROM Marketing_Campaign__c WHERE ID = :this.MC.ID ];
            Id recordId = stdController.getId();
           
            Options = new LIST<SelectOption>();
            Options.add(new SelectOption('','--None--'));
            Options.add(new SelectOption('Theme','Theme'));
            Options.add(new SelectOption('Lead Group Campaign','Lead Group Campaign', true));
            Options.add(new SelectOption('Tactical Campaign','Tactical Campaign',true));
            Options.add(new SelectOption('Lead Moment','Lead Moment'));
            Options.add(new SelectOption('Local Moment','Local Moment'));
            Options.add(new SelectOption('BAU Campaign','BAU Campaign'));

            selectedOption = Camp.Campaign_Level__c;
        }     

    }

    public PageReference generateCSVprojections(){
         try{
            List<Marketing_Campaign__c> campaigns = getAllCampaignsForCSV(this.MC.ID, 3);
            List<Marketing_Activity__c> activities = [Select Id, Name, CurrencyIsoCode, Marketing_Activity_Ref__c,Start_Date__c,End_Date__c,Marketing_Campaign__c, Budget__c, Transfer_To_Oracle__c FROM Marketing_Activity__c WHERE Marketing_Campaign__c in :campaigns AND Status__c in ('Approved','To be Approved') ];

            System.debug('campaigns ===== ' + campaigns);

            Map<Marketing_Campaign__c,List<Marketing_Activity__c>> CampaignData = CSVFileUtils.ProcessData(campaigns, activities);

            System.debug('CampaignData ===== ' + CampaignData);

            String filedata = '';
            // do a different loop here        

            for(Marketing_Campaign__c campaign :CampaignData.keyset()){

                System.debug('campaign Item adding to Data ===== ' + campaign);
               // filedata = CSVFileUtils.AddData(campaign,CampaignData.get(campaign),filedata);
               filedata = CSVFileUtils.AddProjectionData(campaign,CampaignData.get(campaign),filedata);
            }

        // we need to get the Marketing Ref number to use as the file title
        String CampaignReference = '';
        for(Marketing_Campaign__c camp :campaigns)
        {
          if(camp.Id == this.MC.Id){
            CampaignReference = camp.Marketing_Campaign_Ref__c;
          }

        }

             Zippex outputZip = new Zippex();
             outputZip = CSVFileUtils.ProduceProjectionZipFile(filedata,CampaignReference );

             String docName = 'Campaign-Budget-' + CampaignReference + '.zip'; // Document's name

                  Attachment attach = new Attachment();     
                  attach.parentId = this.MC.Id;
                  attach.Name =  docName;
                  attach.body = outputZip.getZipArchive();
                  attach.ContentType = 'text';
                //insert attach;
                displayMessage = true;
                pageMessage = 'Marketing Campaign successfully syncronised';
                showCSVButton = false;
                showCSVProjButton = false;

             ContentVersion contentVersion = new ContentVersion();
             contentVersion.VersionData = outputZip.getZipArchive();
             contentVersion.Title = docName;
             contentVersion.PathOnClient = docName + '.zip';
             contentVersion.ContentLocation = 'S';
             contentVersion.FirstPublishLocationId = this.MC.Id;

             Database.insert(contentVersion, true);

            return new PageReference('/' + this.MC.Id);
            
         }
         catch(Exception ex){
            System.debug('Exception ====== ' + ex.getMessage() + '========' + ex.getStackTraceString());
         }
            return null;
     }

     private List<Marketing_Campaign__c> getAllCampaignsForCSV(Id CampID, Integer levels){

 // at risk of blowing more queries, im going to get all 'grandchildren' too, in the form of another query
            if(Levels == 0){
                // if the level is 0 then we will only return this campaign, and no others
                List<Marketing_Campaign__c> thiscampaign = [Select Id, Name, Marketing_Campaign_Ref__c, Short_Description__c, Start_Date__c, End_Date__c,Village__r.Oracle_Source_Template_Number__c, Village__r.Oracle_Organisation__c, RecordType.Name,Owner.Name, Owner.email, Parent_Marketing_Campaign__r.Name, Village_Marketing_Budget__c, Transfer_To_Oracle__c  FROM Marketing_Campaign__c WHERE Status__c in ('Approved','To be Approved') AND ID = :CampID ];
                return thiscampaign;
            }
            else{
                System.debug('CampID ' + CampID);
                List<Marketing_Campaign__c> campaigns = [Select Id, Name, Marketing_Campaign_Ref__c, Short_Description__c, Start_Date__c, End_Date__c,Village__r.Oracle_Source_Template_Number__c, Village__r.Oracle_Organisation__c, RecordType.Name,Owner.Name, Owner.email, Parent_Marketing_Campaign__r.Name, Village_Marketing_Budget__c,Transfer_To_Oracle__c, CurrencyIsoCode FROM Marketing_Campaign__c WHERE Status__c in ('Approved','To be Approved') AND (ID = :CampID OR Parent_Marketing_Campaign__c = :CampID) ];
                List<Marketing_Campaign__c> grandchildcampaigns;
                if(Levels > 1){
                    grandchildcampaigns = [Select Id, Name, Marketing_Campaign_Ref__c, Short_Description__c, Start_Date__c, End_Date__c,Village__r.Oracle_Source_Template_Number__c, Village__r.Oracle_Organisation__c, RecordType.Name,Owner.Name, Owner.email, Parent_Marketing_Campaign__r.Name, Village_Marketing_Budget__c,Transfer_To_Oracle__c FROM Marketing_Campaign__c WHERE Parent_Marketing_Campaign__c in :campaigns AND Status__c in ('Approved','To be Approved') ];
                     campaigns.addAll(grandchildcampaigns);
                }
                if(Levels > 2){
                    // adding ANOTHER level (this could blow the query limit)
                    List<Marketing_Campaign__c> greatgrandchildcampaigns = [Select Id, Name, Marketing_Campaign_Ref__c, Short_Description__c, Start_Date__c, End_Date__c,Village__r.Oracle_Source_Template_Number__c, Village__r.Oracle_Organisation__c, RecordType.Name,Owner.Name, Owner.email, Parent_Marketing_Campaign__r.Name, Village_Marketing_Budget__c,Transfer_To_Oracle__c FROM Marketing_Campaign__c WHERE Parent_Marketing_Campaign__c in :grandchildcampaigns AND Status__c in ('Approved','To be Approved') ];
                    // then combine the lists into one
                    campaigns.addAll(greatgrandchildcampaigns);
                }

                return campaigns;
            }
            return null;
     }

    public PageReference generateCSV(){
         try{
            // lets get the data from the object:
/*
            // at risk of blowing more queries, im going to get all 'grandchildren' too, in the form of another query
            //Marketing_Campaign__c campaign = [Select Id, Name, Marketing_Campaign_Ref__c, Short_Description__c, Start_Date__c, End_Date__c,Village__r.Oracle_Source_Template_Number__c, Village__r.Oracle_Organisation__c, RecordType.Name,Owner.Name, Owner.email, Parent_Marketing_Campaign__r.Name FROM Marketing_Campaign__c WHERE ID = :this.mysObject.ID];
            List<Marketing_Campaign__c> campaigns = [Select Id, Name, Marketing_Campaign_Ref__c, Short_Description__c, Start_Date__c, End_Date__c,Village__r.Oracle_Source_Template_Number__c, Village__r.Oracle_Organisation__c, RecordType.Name,Owner.Name, Owner.email, Parent_Marketing_Campaign__r.Name FROM Marketing_Campaign__c WHERE Status__c in ('Approved','To be Approved') AND (ID = :this.MC.ID OR Parent_Marketing_Campaign__c = :this.MC.ID )];
            List<Marketing_Campaign__c> grandchildcampaigns = [Select Id, Name, Marketing_Campaign_Ref__c, Short_Description__c, Start_Date__c, End_Date__c,Village__r.Oracle_Source_Template_Number__c, Village__r.Oracle_Organisation__c, RecordType.Name,Owner.Name, Owner.email, Parent_Marketing_Campaign__r.Name FROM Marketing_Campaign__c WHERE Parent_Marketing_Campaign__c in :campaigns AND Status__c in ('Approved','To be Approved')];
            // adding ANOTHER level (this could blow the query limit)
            List<Marketing_Campaign__c> greatgrandchildcampaigns = [Select Id, Name, Marketing_Campaign_Ref__c, Short_Description__c, Start_Date__c, End_Date__c,Village__r.Oracle_Source_Template_Number__c, Village__r.Oracle_Organisation__c, RecordType.Name,Owner.Name, Owner.email, Parent_Marketing_Campaign__r.Name FROM Marketing_Campaign__c WHERE Parent_Marketing_Campaign__c in :grandchildcampaigns AND Status__c in ('Approved','To be Approved')];
            // then combine the lists into one
            campaigns.addAll(grandchildcampaigns);
            campaigns.addAll(greatgrandchildcampaigns);
            */
            List<Marketing_Campaign__c> campaigns = getAllCampaignsForCSV(this.MC.ID, 3);

            List<Marketing_Activity__c> activities = [Select Id, Name,Marketing_Activity_Ref__c,Start_Date__c,End_Date__c,Marketing_Campaign__c,Budget__c,Transfer_To_Oracle__c FROM Marketing_Activity__c WHERE Marketing_Campaign__c in :campaigns AND Status__c in ('Approved','To be Approved')];

            System.debug('campaigns ===== ' + campaigns);

            Map<Marketing_Campaign__c,List<Marketing_Activity__c>> CampaignData = CSVFileUtils.ProcessData(campaigns, activities);

            System.debug('CampaignData ===== ' + CampaignData);

            CSVFileUtils.OracleMarketingCSVFilesData filedata = new CSVFileUtils.OracleMarketingCSVFilesData();
            // do a different loop here        

            for(Marketing_Campaign__c campaign :CampaignData.keyset()){

                System.debug('campaign Item adding to Data ===== ' + campaign);
                filedata = CSVFileUtils.AddData(campaign,CampaignData.get(campaign),filedata);
            }

        // we need to get the Marketing Ref number to use as the file title
        String CampaignReference = '';
        for(Marketing_Campaign__c camp :campaigns)
        {
          if(camp.Id == this.MC.Id){
            CampaignReference = camp.Marketing_Campaign_Ref__c;
          }

        }
            Zippex outputZip = new Zippex();
            outputZip = CSVFileUtils.ProduceZipFile(filedata);

            String docName = 'Campaign-Export-' + CampaignReference + '.zip'; // Document's name

                  Attachment attach = new Attachment();     
                  attach.parentId = this.MC.Id;
                  attach.Name =  docName;
                  attach.body = outputZip.getZipArchive();
                  attach.ContentType = 'text';
                //insert attach;
                displayMessage = true;
                pageMessage = 'Marketing Campaign successfully syncronised';
                showCSVButton = false;
                showCSVProjButton = false;

             ContentVersion contentVersion = new ContentVersion();
             contentVersion.VersionData = outputZip.getZipArchive();
             contentVersion.Title = docName;
             contentVersion.PathOnClient = docName + '.zip';
             contentVersion.ContentLocation = 'S';
             contentVersion.FirstPublishLocationId = this.MC.Id;

             Database.insert(contentVersion, true);

            return new PageReference('/' + this.MC.Id);
       
        } catch ( Exception ex ) {
            displayError = true;
            showCSVButton = false;
            showCSVProjButton = false;
            errorMessage = 'There was an error producing your data \r\n' + ex.getMessage();
            System.debug('>>> ERROR ' + ex);
        }
        return null;
  
    }

    public pagereference EditCampaignLevel(){
        pagereference ref = new PageReference('/apex/EditCampaignLevel');
        return ref;
    }


    public pagereference Save(){

        try{
            shouldRedirect = true;
            redirectUrl = stdController.view().getUrl();

            this.MC.Campaign_Level__c = selectedOption;
            update this.MC;
        
        } catch ( Exception ex ) {
            system.debug('error message @@@@@@ ' + ex);
            this.MC.addError('There was a problem updating the record, Salesforce errorMessage : ' + ex + ', Please contact your System Administrator');
        }
        return null;
    }


    
    public PageReference cancel(){
        PageReference ref = new PageReference('/apex/Marketing_Campaign_Actions');
        return ref;
    }

}