force-app/main/default/objects/Case/fields/Client_QR_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_QR_Code__c</fullName>
    <description>This is the codification of the QR Code previously associated to the client.</description>
    <externalId>true</externalId>
    <label>Client QR Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Guest_ID_Number_Part__c.field-meta.xml
<CustomField>
    <fullName>Guest_ID_Number_Part__c</fullName>
    <description>the number portion of the guest ID. for use with getting an increment</description>
    <inlineHelpText>the number portion of the guest ID. for use with getting an increment</inlineHelpText>
    <label>Guest ID Number Part</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>the status of payment for the service</description>
    <inlineHelpText>the status of payment for the service</inlineHelpText>
    <label>Payment Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Payment on Collection</fullName>
            </value>
            <value>
                <fullName>Free of charge (Valet)</fullName>
            </value>
            <value>
                <fullName>Free of charge (VIP)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Guest_ID__c.field-meta.xml
<CustomField>
    <fullName>Service_Guest_ID__c</fullName>
    <description>a unique generated ID to identify the guest, and the date</description>
    <inlineHelpText>a unique generated ID to identify the guest, and the date</inlineHelpText>
    <label>Service Guest ID</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Guest_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Guest_Number__c</fullName>
    <description>The generated number assigned to the guest for the service for the day</description>
    <inlineHelpText>The generated number assigned to the guest for the service for the day</inlineHelpText>
    <label>Service Guest Number</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The village that this HFS service will be at</description>
    <inlineHelpText>The village that this HFS service will be at</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Shopping_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/Case_Item__c.object-meta.xml
<CustomObject>
    <description>a specific sub item under the case object</description>
    <label>HFS Purchase</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>HFS Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Purchases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Item__c/fields/Service_Guest_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Guest_Number__c</fullName>
    <formula>Case__r.Service_Guest_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Guest Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>the status of the item....</description>
    <inlineHelpText>the status of the item</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Pick-up from Brand</fullName>
            </value>
            <value>
                <fullName>In transit</fullName>
            </value>
            <value>
                <fullName>Ready for Guest Collection</fullName>
            </value>
            <value>
                <fullName>Guest Collected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>the brand from which the case item relates to</description>
    <inlineHelpText>The shop that this item relates to</inlineHelpText>
    <label>Brand</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipName>Case_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/HFS_Bag__c.object-meta.xml
<CustomObject>
    <description>This object save the information of the Bags</description>
    <label>HFS Bag</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Bag Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Bags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Bag__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/HFS_Runner__c.field-meta.xml
<CustomField>
    <fullName>HFS_Runner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFS Runner</label>
    <referenceTo>HFS_Runner__c</referenceTo>
    <relationshipLabel>HFS Bags</relationshipLabel>
    <relationshipName>HFS_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Pick-up</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Putaway</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Bag Dropped</fullName>
            </value>
            <value>
                <fullName>Bag with GSA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HFS_Job__c/HFS_Job__c.object-meta.xml
<CustomObject>
    <description>A junction object between User and Case_Item__c that will record all of the jobs of HFS Experiences.</description>
    <label>HFS Job</label>
    <nameField>
        <displayFormat>J-{00000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Job__c/fields/HFS_Runner__c.field-meta.xml
<CustomField>
    <fullName>HFS_Runner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFS Runner</label>
    <referenceTo>HFS_Runner__c</referenceTo>
    <relationshipLabel>HFS Jobs</relationshipLabel>
    <relationshipName>HFS_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Runner__c/HFS_Runner__c.object-meta.xml
<CustomObject>
    <label>HFS Runner</label>
    <nameField>
        <label>HFS Runner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HFS Runners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Runner__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Organisation__c</fullName>
    <description>The business unit within oracle</description>
    <inlineHelpText>The business unit within oracle</inlineHelpText>
    <label>Oracle Organisation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Source_Template_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Source_Template_Number__c</fullName>
    <description>The value used to map to an oracle template when sent to Oracle Fusion</description>
    <inlineHelpText>The value used to map to an oracle template when sent to Oracle Fusion</inlineHelpText>
    <label>Oracle Source Template Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Village Presence records must be linked to Brand accounts. Please ensure you are not linking the Deal/Village Presence to a Group</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deal Pending</fullName>
            </value>
            <value>
                <fullName>Trading</fullName>
            </value>
            <value>
                <fullName>in Refit</fullName>
            </value>
            <value>
                <fullName>Exited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/CaseItemTriggerHandlerTest.cls
@isTest
private class CaseItemTriggerHandlerTest {

    static void setupData(){

        Profile profileRunner = [SELECT ID, Name FROM Profile WHERE Name = 'HFS Runner'];
        Profile profileCoordinator = [SELECT ID, Name FROM Profile WHERE Name = 'HFS Co-ordinator'];

        UserRole runnerRole = new UserRole();
        runnerRole.DeveloperName = 'CustomRole';
        runnerRole.Name = 'Custom Role';
        insert runnerRole;

        User runner = new User();
        runner.LastName = 'John';
        runner.Alias = 'jhn';
        runner.Email = 'john@valueretai.com';
        runner.Username = 'john@valueretai.com';
        runner.CommunityNickname = 'johnvr';
        runner.UserRoleId = runnerRole.Id;
        runner.ProfileId = profileRunner.Id;
        runner.Village__c = 'Bicester';
        runner.TimeZoneSidKey = 'GMT';
        runner.LocaleSidKey = 'en_GB';
        runner.EmailEncodingKey = 'ISO-8859-1';
        runner.LanguageLocaleKey = 'en_US';
        insert runner;

        User coordinator = new User();
        coordinator.LastName = 'Paul';
        coordinator.Alias = 'pal';
        coordinator.Email = 'paul@valueretai.com';
        coordinator.Username = 'paul@valueretai.com';
        coordinator.CommunityNickname = 'paulas';
        coordinator.UserRoleId = runnerRole.Id;
        coordinator.ProfileId = profileCoordinator.Id;
        coordinator.Village__c = 'Bicester';
        coordinator.TimeZoneSidKey = 'GMT';
        coordinator.LocaleSidKey = 'en_GB';
        coordinator.EmailEncodingKey = 'ISO-8859-1';
        coordinator.LanguageLocaleKey = 'en_US';
        insert coordinator;

        system.runAs(runner){
            // first create a village
            Village__c vill = TestDataGenerator.setupVillage(false);
            vill.Oracle_Source_Template_Number__c = '123456';
            vill.Oracle_Organisation__c = 'SourceOrg';
            vill.Name = 'Bicester';
            vill.CertSales_CertPeriod_Cut_Off_Days__c = 1;
            vill.CertSales_Report_Sales_Grace_Period_Days__c = 1;
            insert vill;

            RecordType brandRecordType = [SELECT Id, Name FROM RecordType WHERE Name = 'Brand'];
            RecordType guestRecordType = [SELECT Id, Name FROM RecordType WHERE Name = 'Guest'];

            Account brand = new Account();
            brand.RecordTypeId = brandRecordType.Id;
            brand.Name = 'Brand 1';
            insert brand;

            Village_Presence__c presentBrand = new Village_Presence__c();
            presentBrand.Name = 'Brand1 in village';
            presentBrand.Brand__c = brand.Id;
            presentBrand.Village__c = vill.Id;
            insert presentBrand;

            Case guestCase = new Case();
            guestCase.Village__c = vill.Id;
            guestCase.Service_Guest_ID__c = '123456789';
            guestCase.Service_Guest_Number__c = 'XA1';
            guestCase.Guest_ID_Number_Part__c = 12;
            guestCase.Payment_Status__c = 'Paid';
            guestCase.Client_QR_Code__c = '123456789';
            guestCase.Status = 'New';
            guestCase.Origin = 'Email';
            insert guestCase;

            RecordType newJobRecordType = [SELECT Id, Name FROM RecordType WHERE Name = 'New Job General'];

            HFS_Runner__c newRunner = new HFS_Runner__c();
            newRunner.Name = 'John';
            newRunner.User__c = runner.Id;
            newRunner.Village__c = 'Bicester';
            insert newRunner;
        }
    }

    static testMethod void createNewJobandBagsTestN1(){
        setupData();
        User runner = [SELECT ID FROM User WHERE Alias = 'jhn'];

        system.runAs(runner){
            Case newGuest = [SELECT ID, Service_Guest_ID__c, Village__c FROM Case WHERE Service_Guest_ID__c = '123456789'];
            Village_Presence__c brand = [SELECT Id, Village__c FROM Village_Presence__c WHERE Village__c = :newGuest.Village__c];

            Case_Item__c hfsPurchaseWithoutRunner = new Case_Item__c();
            hfsPurchaseWithoutRunner.Case__c = newGuest.Id;
            hfsPurchaseWithoutRunner.Status__c = 'Awaiting Pick-up from Brand';
            hfsPurchaseWithoutRunner.Start_Time__c = system.now();
            hfsPurchaseWithoutRunner.Item_Count__c = 5;
            hfsPurchaseWithoutRunner.Bag_Barcodes_Manual__c = '0123456,false,0123457,true,0152635,false,01201201,false,023232,false';
            hfsPurchaseWithoutRunner.Require_a_Runner__c = false;
            hfsPurchaseWithoutRunner.Village_Presence__c = brand.Id;
            hfsPurchaseWithoutRunner.HFS_Bag_Drop__c = false;
            hfsPurchaseWithoutRunner.HFS_Bag_Transfer__c = false;

            Test.startTest();
            insert hfsPurchaseWithoutRunner;
            Test.stopTest();

            Case_Item__c hfsPurchase = [SELECT ID, Item_Count__c FROM Case_Item__c WHERE Require_a_Runner__c = false];
            List<HFS_Bag__c> hfsBag = [SELECT ID, HFS_Runner__c FROM HFS_Bag__c WHERE HFS_Purchase__c = :hfsPurchase.Id];
            HFS_Runner__c runnerId = [SELECT ID FROM HFS_Runner__c WHERE User__c = :runner.Id];
            HFS_Job__c theJob = [SELECT ID, Job_Type__c, HFS_Runner__c FROM HFS_Job__c WHERE HFS_Purchase__c = :hfsPurchase.Id];

            system.assertEquals(hfsBag.size(), hfsPurchase.Item_Count__c);
            system.assertEquals(hfsBag[0].HFS_Runner__c, runnerId.Id);
            system.assertEquals(theJob.Job_Type__c, 'Original Pick-up Request');
        }
    }
    
    static testMethod void createNewJobandBagsTestN2(){
        setupData();
        User runner = [SELECT ID FROM User WHERE Alias = 'jhn'];

        system.runAs(runner){
            Case newGuest = [SELECT ID, Service_Guest_ID__c, Village__c FROM Case WHERE Service_Guest_ID__c = '123456789'];
            Village_Presence__c brand = [SELECT Id, Village__c FROM Village_Presence__c WHERE Village__c = :newGuest.Village__c];

            Case_Item__c hfsPurchaseWithoutRunner = new Case_Item__c();
            hfsPurchaseWithoutRunner.Case__c = newGuest.Id;
            hfsPurchaseWithoutRunner.Status__c = 'Awaiting Pick-up from Brand';
            hfsPurchaseWithoutRunner.Start_Time__c = system.now();
            hfsPurchaseWithoutRunner.Item_Count__c = 5;
            hfsPurchaseWithoutRunner.Bag_Barcodes_Manual__c = '0123456,false,0123457,true,0152635,false,01201201,false,023232,false';
            hfsPurchaseWithoutRunner.Require_a_Runner__c = false;
            hfsPurchaseWithoutRunner.Village_Presence__c = brand.Id;
            hfsPurchaseWithoutRunner.HFS_Bag_Drop__c = true;
            hfsPurchaseWithoutRunner.HFS_Bag_Transfer__c = false;

            Test.startTest();
            insert hfsPurchaseWithoutRunner;
            Test.stopTest();

            Case_Item__c hfsPurchase = [SELECT ID, Item_Count__c FROM Case_Item__c WHERE Require_a_Runner__c = false];
            List<HFS_Bag__c> hfsBag = [SELECT ID, HFS_Runner__c FROM HFS_Bag__c WHERE HFS_Purchase__c = :hfsPurchase.Id];
            HFS_Runner__c runnerId = [SELECT ID FROM HFS_Runner__c WHERE User__c = :runner.Id];
            HFS_Job__c theJob = [SELECT ID, Job_Type__c, HFS_Runner__c FROM HFS_Job__c WHERE HFS_Purchase__c = :hfsPurchase.Id];

            system.assertEquals(hfsBag.size(), hfsPurchase.Item_Count__c);
            system.assertEquals(hfsBag[0].HFS_Runner__c, runnerId.Id);
            system.assertEquals(theJob.Job_Type__c, 'Bag Drop');
            system.assertEquals(theJob.HFS_Runner__c, runnerId.Id);
        }
    }

    static testMethod void createNewJobandBagsTestN3(){
        setupData();
        User runner = [SELECT ID FROM User WHERE Alias = 'jhn'];

        system.runAs(runner){
            Case newGuest = [SELECT ID, Service_Guest_ID__c, Village__c FROM Case WHERE Service_Guest_ID__c = '123456789'];
            Village_Presence__c brand = [SELECT Id, Village__c FROM Village_Presence__c WHERE Village__c = :newGuest.Village__c];

            Case_Item__c hfsPurchaseWithoutRunner = new Case_Item__c();
            hfsPurchaseWithoutRunner.Case__c = newGuest.Id;
            hfsPurchaseWithoutRunner.Status__c = 'Awaiting Pick-up from Brand';
            hfsPurchaseWithoutRunner.Start_Time__c = system.now();
            hfsPurchaseWithoutRunner.Item_Count__c = 5;
            hfsPurchaseWithoutRunner.Bag_Barcodes_Manual__c = '0123456,false,0123457,true,0152635,false,01201201,false,023232,false';
            hfsPurchaseWithoutRunner.Require_a_Runner__c = true;
            hfsPurchaseWithoutRunner.Village_Presence__c = brand.Id;
            hfsPurchaseWithoutRunner.HFS_Bag_Drop__c = true;
            hfsPurchaseWithoutRunner.HFS_Bag_Transfer__c = false;

            Test.startTest();
            insert hfsPurchaseWithoutRunner;
            Test.stopTest();

            Case_Item__c hfsPurchase = [SELECT ID, Item_Count__c FROM Case_Item__c WHERE Require_a_Runner__c = true];
            List<HFS_Bag__c> hfsBag = [SELECT ID, HFS_Runner__c FROM HFS_Bag__c WHERE HFS_Purchase__c = :hfsPurchase.Id];
            HFS_Runner__c runnerId = [SELECT ID FROM HFS_Runner__c WHERE User__c = :runner.Id];
            HFS_Job__c theJob = [SELECT ID, Job_Type__c, HFS_Runner__c FROM HFS_Job__c WHERE HFS_Purchase__c = :hfsPurchase.Id];

            system.assertEquals(hfsBag.size(), hfsPurchase.Item_Count__c);
            system.assertEquals(hfsBag[0].HFS_Runner__c, null);
            system.assertEquals(theJob.Job_Type__c, 'Bag Drop');
            system.assertEquals(theJob.HFS_Runner__c, null);
        }
    }

    static testMethod void createNewJobandBagsTestN4(){
        setupData();
        User runner = [SELECT ID FROM User WHERE Alias = 'jhn'];

        system.runAs(runner){
            Case newGuest = [SELECT ID, Service_Guest_ID__c, Village__c FROM Case WHERE Service_Guest_ID__c = '123456789'];
            Village_Presence__c brand = [SELECT Id, Village__c FROM Village_Presence__c WHERE Village__c = :newGuest.Village__c];

            Case_Item__c hfsPurchaseWithoutRunner = new Case_Item__c();
            hfsPurchaseWithoutRunner.Case__c = newGuest.Id;
            hfsPurchaseWithoutRunner.Status__c = 'Awaiting Pick-up from Brand';
            hfsPurchaseWithoutRunner.Start_Time__c = system.now();
            hfsPurchaseWithoutRunner.Require_a_Runner__c = true;
            hfsPurchaseWithoutRunner.Village_Presence__c = brand.Id;
            hfsPurchaseWithoutRunner.HFS_Bag_Drop__c = false;
            hfsPurchaseWithoutRunner.HFS_Bag_Transfer__c = true;

            Test.startTest();
            insert hfsPurchaseWithoutRunner;
            Test.stopTest();

            Case_Item__c hfsPurchase = [SELECT ID, Item_Count__c FROM Case_Item__c WHERE Require_a_Runner__c = true];
            List<HFS_Bag__c> hfsBag = [SELECT ID, HFS_Runner__c FROM HFS_Bag__c WHERE HFS_Purchase__c = :hfsPurchase.Id];
            HFS_Runner__c runnerId = [SELECT ID FROM HFS_Runner__c WHERE User__c = :runner.Id];
            HFS_Job__c theJob = [SELECT ID, Job_Type__c, HFS_Runner__c FROM HFS_Job__c WHERE HFS_Purchase__c = :hfsPurchase.Id];

            system.assertEquals(hfsBag.size(), 0);
            system.assertEquals(theJob.Job_Type__c, 'Bag Transfer');
            system.assertEquals(theJob.HFS_Runner__c, null);
        }
    }
}