force-app/main/default/objects/Case/fields/Client_QR_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_QR_Code__c</fullName>
    <description>This is the codification of the QR Code previously associated to the client.</description>
    <externalId>true</externalId>
    <label>Client QR Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Guest_ID_Number_Part__c.field-meta.xml
<CustomField>
    <fullName>Guest_ID_Number_Part__c</fullName>
    <description>the number portion of the guest ID. for use with getting an increment</description>
    <inlineHelpText>the number portion of the guest ID. for use with getting an increment</inlineHelpText>
    <label>Guest ID Number Part</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>the status of payment for the service</description>
    <inlineHelpText>the status of payment for the service</inlineHelpText>
    <label>Payment Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Payment on Collection</fullName>
            </value>
            <value>
                <fullName>Free of charge (Valet)</fullName>
            </value>
            <value>
                <fullName>Free of charge (VIP)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Date__c</fullName>
    <description>The date the service is to be for (could be in the future for prebookings)</description>
    <inlineHelpText>The date the service is to be for (could be in the future for prebookings)</inlineHelpText>
    <label>Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Guest_ID__c.field-meta.xml
<CustomField>
    <fullName>Service_Guest_ID__c</fullName>
    <description>a unique generated ID to identify the guest, and the date</description>
    <inlineHelpText>a unique generated ID to identify the guest, and the date</inlineHelpText>
    <label>Service Guest ID</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Guest_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Guest_Number__c</fullName>
    <description>The generated number assigned to the guest for the service for the day</description>
    <inlineHelpText>The generated number assigned to the guest for the service for the day</inlineHelpText>
    <label>Service Guest Number</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The village that this HFS service will be at</description>
    <inlineHelpText>The village that this HFS service will be at</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Shopping_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/Case_Item__c.object-meta.xml
<CustomObject>
    <description>a specific sub item under the case object</description>
    <label>HFS Purchase</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>HFS Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Purchases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Item__c/fields/Service_Guest_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Guest_Number__c</fullName>
    <formula>Case__r.Service_Guest_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Guest Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>the status of the item....</description>
    <inlineHelpText>the status of the item</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Pick-up from Brand</fullName>
            </value>
            <value>
                <fullName>In transit</fullName>
            </value>
            <value>
                <fullName>Ready for Guest Collection</fullName>
            </value>
            <value>
                <fullName>Guest Collected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>the brand from which the case item relates to</description>
    <inlineHelpText>The shop that this item relates to</inlineHelpText>
    <label>Brand</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipName>Case_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/HFS_Bag__c.object-meta.xml
<CustomObject>
    <description>This object save the information of the Bags</description>
    <label>HFS Bag</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Bag Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Bags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Bag__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Pick-up</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Putaway</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Bag Dropped</fullName>
            </value>
            <value>
                <fullName>Bag with GSA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tracked_Bag__e/Tracked_Bag__e.object-meta.xml
<CustomObject>
    <description>Platform Event to get interaction with CONIQ in way to track all purchase and bags from the Brand.</description>
    <label>Tracked Bag</label>
    <pluralLabel>Tracked Bags</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tracked_Bag__e/fields/lease_id__c.field-meta.xml
<CustomField>
    <fullName>lease_id__c</fullName>
    <label>Brande Lease ID</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Organisation__c</fullName>
    <description>The business unit within oracle</description>
    <inlineHelpText>The business unit within oracle</inlineHelpText>
    <label>Oracle Organisation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Source_Template_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Source_Template_Number__c</fullName>
    <description>The value used to map to an oracle template when sent to Oracle Fusion</description>
    <inlineHelpText>The value used to map to an oracle template when sent to Oracle Fusion</inlineHelpText>
    <label>Oracle Source Template Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Village Presence records must be linked to Brand accounts. Please ensure you are not linking the Deal/Village Presence to a Group</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Lease_ID__c.field-meta.xml
<CustomField>
    <fullName>Lease_ID__c</fullName>
    <externalId>true</externalId>
    <label>Lease ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deal Pending</fullName>
            </value>
            <value>
                <fullName>Trading</fullName>
            </value>
            <value>
                <fullName>in Refit</fullName>
            </value>
            <value>
                <fullName>Exited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/PETrackedBagTriggerHandlerTest.cls
@isTest
public class PETrackedBagTriggerHandlerTest {

  public static void setupData(){

        Profile profileRunner = [SELECT ID, Name FROM Profile WHERE Name = 'HFS Runner'];

        UserRole runnerRole = new UserRole();
        runnerRole.DeveloperName = 'CustomRole';
        runnerRole.Name = 'Custom Role';
        insert runnerRole;

        User runner = new User();
        runner.LastName = 'John';
        runner.Alias = 'jhn';
        runner.Email = 'john@valueretai.com';
        runner.Username = 'john@valueretai.com';
        runner.CommunityNickname = 'johnvr';
        runner.UserRoleId = runnerRole.Id;
        runner.ProfileId = profileRunner.Id;
        runner.Village__c = 'Bicester';
        runner.TimeZoneSidKey = 'GMT';
        runner.LocaleSidKey = 'en_GB';
        runner.EmailEncodingKey = 'ISO-8859-1';
        runner.LanguageLocaleKey = 'en_US';
        insert runner;

        system.runAs(runner){
        // first create a village

          Logging_Enabled__c test = new Logging_Enabled__c();
          test.Name = 'PETrackedBagTriggerHandler';
          insert test;

          Village__c vill = TestDataGenerator.setupVillage(false);
          vill.Oracle_Source_Template_Number__c = '123456';
          vill.Oracle_Organisation__c = 'SourceOrg';
          vill.Name = 'Bicester';
          vill.village_code__c = 'BV';
		  vill.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		  vill.CertSales_Report_Sales_Grace_Period_Days__c = 1; 
          insert vill;

          RecordType brandRecordType = [SELECT Id, Name FROM RecordType WHERE Name = 'Brand'];
          RecordType guestRecordType = [SELECT Id, Name FROM RecordType WHERE Name = 'Guest'];

          Account brand = new Account();
          brand.RecordTypeId = brandRecordType.Id;
          brand.Name = 'Brand 1';
          insert brand;

          Village_Presence__c presentBrand = new Village_Presence__c();
          presentBrand.Name = 'Brand1 in village';
          presentBrand.Brand__c = brand.Id;
          presentBrand.Village__c = vill.Id;
          presentBrand.Lease_ID__c = 'BRAND1BIC';
          insert presentBrand;

          Case guestCase = new Case();
          guestCase.Village__c = vill.Id;
          guestCase.Service_Guest_ID__c = '11111';
          guestCase.Service_Guest_Number__c = 'XA1';
          guestCase.Guest_ID_Number_Part__c = 12;
          guestCase.Payment_Status__c = 'Paid';
          guestCase.Client_QR_Code__c = '22222';
          guestCase.Status = 'New';
          guestCase.Origin = 'Email';
          guestCase.Service_Date__c = system.today();
          insert guestCase;
      }
    }

    static testMethod void PETrackedBagCreatePurchase(){
        setupData();

        String json = '[{\"barcode__c\": 1772664829,\"oversize__c\": false},{\"barcode__c\": 1772664828,\"oversize__c\": true},{\"barcode__c\": 1772664827,\"oversize__c\": false }]';
        //JSON2Apex obj = JSON2Apex.parse(json);
        
        Tracked_Bag__e newTrackedBag = new Tracked_Bag__e(lease_id__c = 'BRAND1BIC',
                                                          brand_location_name__c = 'Brand1 in village',
                                                          txn_datetime_utc__c = system.now(),
                                                          estimated_spend__c = 510.50,
                                                          guest_barcode__c = '22222',
                                                          hfsbags_list__c = json,
                                                          numberofbags__c = 3);

        Test.startTest();
        // Publish test event
        Database.SaveResult sr = EventBus.publish(newTrackedBag);
        
        Test.stopTest();
        
        Case theCase = [SELECT Id FROM Case WHERE Client_QR_Code__c = '22222'];
        List<Case_Item__c> purchases = [SELECT Id, Case__c FROM Case_Item__c];
        List<HFS_Bag__c> theBags = [SELECT Id FROM HFS_Bag__c];
        
        system.assertEquals(1, purchases.size());
        system.assertEquals(theCase.Id, purchases[0].Case__c);
        system.assertEquals(newTrackedBag.numberofbags__c, theBags.size());
    }

    static testMethod void PETrackedBagHandlingErros(){
        setupData();

        String json = '[{\"barcode__c\": 1772664829,\"oversize__c\": false},{\"barcode__c\": 1772664828,\"oversize__c\": true},{\"barcode__c\": 1772664827,\"oversize__c\": false }]';
        //JSON2Apex obj = JSON2Apex.parse(json);
        
        Tracked_Bag__e newTrackedBag = new Tracked_Bag__e(lease_id__c = '0000000',
                                                          brand_location_name__c = 'Brand1 in village',
                                                          txn_datetime_utc__c = system.now(),
                                                          estimated_spend__c = 510.50,
                                                          guest_barcode__c = '22000',
                                                          hfsbags_list__c = json,
                                                          numberofbags__c = 3);

        Test.startTest();
        // Publish test event
        Database.SaveResult sr = EventBus.publish(newTrackedBag);
        
        Test.stopTest();

        List<Case_Item__c> purchases = [SELECT Id, Case__c FROM Case_Item__c];
        List<HFS_Bag__c> theBags = [SELECT Id FROM HFS_Bag__c];
        
        system.assertEquals(0, purchases.size());
        system.assertEquals(0, theBags.size());
    }

    static testMethod void PETrackedBagHandlingBagsErros(){
        setupData();

        String json = '[{\"barcode__c\": 123456,\"oversize__c\": false},{\"barcode__c\": 1000,\"oversize__c\": true},{\"barcode__c\": 10120,\"oversize__c\": false }]';
        //JSON2Apex obj = JSON2Apex.parse(json);
        User john = [SELECT Id FROM User WHERE Alias='jhn'];
        Village_Presence__c brand = [SELECT Id FROM Village_Presence__c];
        Case caseItem = [SELECT Id FROM Case];

        system.runAs(john){
          Case_Item__c hfsPurchase = new Case_Item__c();
          hfsPurchase.Case__c = caseItem.Id;
          hfsPurchase.Village_Presence__c = brand.Id;
          hfsPurchase.Status__c = 'Awaiting Pick-up from Brand';
          hfsPurchase.Start_Time__c = system.now();
          hfsPurchase.Item_Count__c = 3;
          hfsPurchase.Bag_Barcodes_Manual__c = '123456,false,123457,true,152635,false';
          hfsPurchase.Require_a_Runner__c = TRUE;
          hfsPurchase.HFS_Bag_Transfer__c = FALSE;
          insert hfsPurchase;
        }

        Tracked_Bag__e newTrackedBag = new Tracked_Bag__e(lease_id__c = 'BRAND1BIC',
                                                          brand_location_name__c = 'Brand1 in village',
                                                          txn_datetime_utc__c = system.now(),
                                                          estimated_spend__c = 510.50,
                                                          guest_barcode__c = '22222',
                                                          hfsbags_list__c = json,
                                                          numberofbags__c = 3);

        Test.startTest();
        // Publish test event
        Database.SaveResult sr = EventBus.publish(newTrackedBag);
        
        Test.stopTest();

        Case theCase = [SELECT Id FROM Case WHERE Client_QR_Code__c = '22222'];
        List<Case_Item__c> purchases = [SELECT Id, Case__c FROM Case_Item__c];
        List<HFS_Bag__c> theBags = [SELECT Id FROM HFS_Bag__c];
        
        system.assertEquals(1, purchases.size());
        system.assertEquals(3, theBags.size());
    }
}