force-app/main/default/objects/Case/fields/Client_QR_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_QR_Code__c</fullName>
    <description>This is the codification of the QR Code previously associated to the client.</description>
    <externalId>true</externalId>
    <label>Client QR Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Guest_ID_Number_Part__c.field-meta.xml
<CustomField>
    <fullName>Guest_ID_Number_Part__c</fullName>
    <description>the number portion of the guest ID. for use with getting an increment</description>
    <inlineHelpText>the number portion of the guest ID. for use with getting an increment</inlineHelpText>
    <label>Guest ID Number Part</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>the status of payment for the service</description>
    <inlineHelpText>the status of payment for the service</inlineHelpText>
    <label>Payment Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Payment on Collection</fullName>
            </value>
            <value>
                <fullName>Free of charge (Valet)</fullName>
            </value>
            <value>
                <fullName>Free of charge (VIP)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Date__c</fullName>
    <description>The date the service is to be for (could be in the future for prebookings)</description>
    <inlineHelpText>The date the service is to be for (could be in the future for prebookings)</inlineHelpText>
    <label>Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Guest_ID__c.field-meta.xml
<CustomField>
    <fullName>Service_Guest_ID__c</fullName>
    <description>a unique generated ID to identify the guest, and the date</description>
    <inlineHelpText>a unique generated ID to identify the guest, and the date</inlineHelpText>
    <label>Service Guest ID</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Guest_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Guest_Number__c</fullName>
    <description>The generated number assigned to the guest for the service for the day</description>
    <inlineHelpText>The generated number assigned to the guest for the service for the day</inlineHelpText>
    <label>Service Guest Number</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The village that this HFS service will be at</description>
    <inlineHelpText>The village that this HFS service will be at</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Shopping_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/Case_Item__c.object-meta.xml
<CustomObject>
    <description>a specific sub item under the case object</description>
    <label>HFS Purchase</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>HFS Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Purchases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Item__c/fields/Estimated_Spend__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Spend__c</fullName>
    <description>The estimated spend for the collection item</description>
    <inlineHelpText>The estimated spend for the collection item</inlineHelpText>
    <label>Estimated Spend</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Service_Guest_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Guest_Number__c</fullName>
    <formula>Case__r.Service_Guest_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Guest Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>the status of the item....</description>
    <inlineHelpText>the status of the item</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Pick-up from Brand</fullName>
            </value>
            <value>
                <fullName>In transit</fullName>
            </value>
            <value>
                <fullName>Ready for Guest Collection</fullName>
            </value>
            <value>
                <fullName>Guest Collected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>the brand from which the case item relates to</description>
    <inlineHelpText>The shop that this item relates to</inlineHelpText>
    <label>Brand</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipName>Case_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/HFS_Bag__c.object-meta.xml
<CustomObject>
    <description>This object save the information of the Bags</description>
    <label>HFS Bag</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Bag Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Bags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Bag__c/fields/Barcode__c.field-meta.xml
<CustomField>
    <fullName>Barcode__c</fullName>
    <description>This is the visible numbers present on the Barcode</description>
    <inlineHelpText>Visible Barcode numbers</inlineHelpText>
    <label>Barcode</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Pick-up</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Putaway</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Bag Dropped</fullName>
            </value>
            <value>
                <fullName>Bag with GSA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HFS_IntegrationErrorTrackedBag__c/HFS_IntegrationErrorTrackedBag__c.object-meta.xml
<CustomObject>
    <label>HFS IntegrationError TrackedBag</label>
    <nameField>
        <displayFormat>IntegrationError-{0000}</displayFormat>
        <label>HFS IntegrationErrorTrackedBag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS IntegrationError TrackedBags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_IntegrationErrorTrackedBag__c/fields/Brand_Lease_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Lease_Id__c</fullName>
    <label>Brand Lease Id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_IntegrationErrorTrackedBag__c/fields/Brand_Location_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Location_Name__c</fullName>
    <label>Brand Location Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_IntegrationErrorTrackedBag__c/fields/Estimated_Spend__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Spend__c</fullName>
    <label>Estimated Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HFS_IntegrationErrorTrackedBag__c/fields/Guest_Code__c.field-meta.xml
<CustomField>
    <fullName>Guest_Code__c</fullName>
    <label>Guest Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_IntegrationErrorTrackedBag__c/fields/Is_Resolved__c.field-meta.xml
<CustomField>
    <fullName>Is_Resolved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resolved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HFS_IntegrationErrorTrackedBag__c/fields/List_of_Bags__c.field-meta.xml
<CustomField>
    <fullName>List_of_Bags__c</fullName>
    <label>List of Bags</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HFS_IntegrationErrorTrackedBag__c/fields/Number_of_Bags__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Bags__c</fullName>
    <label>Number of Bags</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Organisation__c</fullName>
    <description>The business unit within oracle</description>
    <inlineHelpText>The business unit within oracle</inlineHelpText>
    <label>Oracle Organisation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Source_Template_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Source_Template_Number__c</fullName>
    <description>The value used to map to an oracle template when sent to Oracle Fusion</description>
    <inlineHelpText>The value used to map to an oracle template when sent to Oracle Fusion</inlineHelpText>
    <label>Oracle Source Template Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Lease_ID__c.field-meta.xml
<CustomField>
    <fullName>Lease_ID__c</fullName>
    <externalId>true</externalId>
    <label>Lease ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deal Pending</fullName>
            </value>
            <value>
                <fullName>Trading</fullName>
            </value>
            <value>
                <fullName>in Refit</fullName>
            </value>
            <value>
                <fullName>Exited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/CreateConiqPurchaseExtensionTest.cls
@isTest
private class CreateConiqPurchaseExtensionTest {


    private static HFS_IntegrationErrorTrackedBag__c integrationErrorTrackedBag = null;
    private static HFS_IntegrationErrorTrackedBag__c integrationErrorTrackedBagWrong = null;
    private static HFS_IntegrationErrorTrackedBag__c integrationErrorTrackedBagWrong2 = null;

    static void setupData(){
		
		RecordType brandRecordType = [SELECT Id, Name FROM RecordType WHERE Name = 'Brand'];

		integrationErrorTrackedBag = new HFS_IntegrationErrorTrackedBag__c(
			Brand_Lease_Id__c = 'ID0105',
			Brand_Location_Name__c = 'Somewhere',
			DateTime__c = system.today(), 
			Estimated_Spend__c = 25,
			Guest_Code__c = '123456789',
			List_of_Bags__c = '[{"barcode__c": "321121","oversize__c": false},{"barcode__c": "7423432","oversize__c": true},{"barcode__c": "2324212","oversize__c": false}]',
			Number_of_Bags__c = 3,
			Is_Resolved__c = false);
		insert integrationErrorTrackedBag;
		
		integrationErrorTrackedBagWrong = new HFS_IntegrationErrorTrackedBag__c(
			Brand_Lease_Id__c = 'ID01056',
			Brand_Location_Name__c = 'Somewhere',
			DateTime__c = system.today(), 
			Estimated_Spend__c = 25,
			Guest_Code__c = '12345678',
			List_of_Bags__c = '[{"barcode__c": "321121","oversize__c": false},{"barcode__c": "7423432","oversize__c": true},{"barcode__c": "2324212","oversize__c": false},{"barcode__c": "9999999","oversize__c": false},{"barcode__c": "9999999","oversize__c": false}]',
			Number_of_Bags__c = 5,
			Is_Resolved__c = false);
		insert integrationErrorTrackedBagWrong;

		integrationErrorTrackedBagWrong2 = new HFS_IntegrationErrorTrackedBag__c(
			Brand_Lease_Id__c = 'ID0105',
			Brand_Location_Name__c = 'Somewhere',
			DateTime__c = system.today(), 
			Estimated_Spend__c = 25,
			Guest_Code__c = '123456789',
			List_of_Bags__c = '[{"barcode__c": "321121","oversize__c": false},{"barcode__c": "2312","oversize__c": false}]',
			Number_of_Bags__c = 5,
			Is_Resolved__c = false);
		insert integrationErrorTrackedBagWrong2;

		Logging_Enabled__c logEnabled = new Logging_Enabled__c(
			Name = 'PETrackedBagTriggerHandler');
		insert logEnabled;

		Village__c vill = TestDataGenerator.setupVillage(false);
        vill.Oracle_Source_Template_Number__c = '123456';
        vill.Oracle_Organisation__c = 'SourceOrg';
        vill.Name = 'Bicester';
		vill.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		vill.CertSales_Report_Sales_Grace_Period_Days__c = 1;
        insert vill;

		Case guestCase = new Case();
        guestCase.Village__c = vill.Id;
        guestCase.Service_Guest_ID__c = '123456789';
        guestCase.Service_Guest_Number__c = 'XA1';
        guestCase.Guest_ID_Number_Part__c = 12;
        guestCase.Payment_Status__c = 'Paid';
        guestCase.Client_QR_Code__c = '123456789';
        guestCase.Status = 'New';
        guestCase.Origin = 'Email';
        guestCase.Service_Date__c = system.today();
        insert guestCase;

        Account brand = new Account();
        brand.RecordTypeId = brandRecordType.Id;
        brand.Name = 'Brand 1';
        insert brand;

        Village_Presence__c presentBrand = new Village_Presence__c();
        presentBrand.Name = 'Brand1 in village';
        presentBrand.Brand__c = brand.Id;
        presentBrand.Village__c = vill.Id;
        presentBrand.Lease_Id__c = 'ID0105';
        insert presentBrand;

        Case_Item__c purchaseNew = new Case_Item__c();
        purchaseNew.Case__c = guestCase.Id;
        purchaseNew.Status__c = 'Awaiting Pick-up from Brand';
        purchaseNew.Start_Time__c = system.now();
        purchaseNew.Item_Count__c = 3;
        purchaseNew.Bag_Barcodes_Manual__c = '2312,false,123457,true,152635,false';
        purchaseNew.Require_a_Runner__c = true;
        purchaseNew.HFS_Bag_Transfer__c = false;
        purchaseNew.Village_Presence__c = presentBrand.Id;
        insert purchaseNew;

        HFS_Bag__c newBag = new HFS_Bag__c();
        newBag.Barcode__c = '2312';
        newBag.HFS_Bag_Active__c = true;
        newBag.HFS_Purchase__c = purchaseNew.Id;
        insert newBag;
	}

	static testMethod void verifyIfRunsCorrectly() {

		setupData();

		test.startTest();
			//Page reference to the VF page
			PageReference pageRef = Page.CreateConiqPurchasePage;
            Test.setCurrentPage(pageRef);
            //Pass the object to controller
            ApexPages.StandardController stdController = new ApexPages.StandardController(integrationErrorTrackedBag);
            //Call the controller
            CreateConiqPurchaseExtension controller = new CreateConiqPurchaseExtension(stdController);
            //Call method using controller ref
            controller.createConiqPurchase();
		test.stopTest();

		HFS_IntegrationErrorTrackedBag__c checkVar = [SELECT Id, Is_Resolved__c FROM HFS_IntegrationErrorTrackedBag__c WHERE Id =: integrationErrorTrackedBag.Id];
		System.assertEquals(true, checkVar.Is_Resolved__c);
	}

	static testMethod void verifyIfBagIsRepeated(){

		setupData();

		test.startTest();
		//Page reference to the VF page
			PageReference pageRef = Page.CreateConiqPurchasePage;
            Test.setCurrentPage(pageRef);
            //Pass the object to controller
            ApexPages.StandardController stdController = new ApexPages.StandardController(integrationErrorTrackedBagWrong);
            //Call the controller
            CreateConiqPurchaseExtension controller = new CreateConiqPurchaseExtension(stdController);
            //Call method using controller ref
            controller.createConiqPurchase();
		test.stopTest();

		List<LogFile__c> checkLogs = [SELECT Name FROM LogFile__c];
		System.assertEquals(false, checkLogs.isEmpty());	
	}

	static testMethod void verifyIfBarCodeAlreadyExists(){

		setupData();

		test.startTest();
		//Page reference to the VF page
			PageReference pageRef = Page.CreateConiqPurchasePage;
            Test.setCurrentPage(pageRef);
            //Pass the object to controller
            ApexPages.StandardController stdController = new ApexPages.StandardController(integrationErrorTrackedBagWrong2);
            //Call the controller
            CreateConiqPurchaseExtension controller = new CreateConiqPurchaseExtension(stdController);
            //Call method using controller ref
            controller.createConiqPurchase();
		test.stopTest();

		List<LogFile__c> checkLogs = [SELECT Name FROM LogFile__c];
		System.assertEquals(false, checkLogs.isEmpty());			
	}
}