force-app/main/default/objects/Case/fields/Client_QR_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_QR_Code__c</fullName>
    <description>This is the codification of the QR Code previously associated to the client.</description>
    <externalId>true</externalId>
    <label>Client QR Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Date__c</fullName>
    <description>The date the service is to be for (could be in the future for prebookings)</description>
    <inlineHelpText>The date the service is to be for (could be in the future for prebookings)</inlineHelpText>
    <label>Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Guest_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Guest_Number__c</fullName>
    <description>The generated number assigned to the guest for the service for the day</description>
    <inlineHelpText>The generated number assigned to the guest for the service for the day</inlineHelpText>
    <label>Service Guest Number</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/Case_Item__c.object-meta.xml
<CustomObject>
    <description>a specific sub item under the case object</description>
    <label>HFS Purchase</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>HFS Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Purchases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Item__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>HFS Purchases</relationshipLabel>
    <relationshipName>Case_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Estimated_Spend__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Spend__c</fullName>
    <description>The estimated spend for the collection item</description>
    <inlineHelpText>The estimated spend for the collection item</inlineHelpText>
    <label>Estimated Spend</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Item_Count__c.field-meta.xml
<CustomField>
    <fullName>Item_Count__c</fullName>
    <description>The number of items in the record</description>
    <inlineHelpText>The number of items in the record</inlineHelpText>
    <label>Item Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Require_a_Runner__c.field-meta.xml
<CustomField>
    <fullName>Require_a_Runner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Require a Runner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Service_Guest_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Guest_Number__c</fullName>
    <formula>Case__r.Service_Guest_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Guest Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>the start time</description>
    <inlineHelpText>the start time</inlineHelpText>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>the status of the item....</description>
    <inlineHelpText>the status of the item</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Pick-up from Brand</fullName>
            </value>
            <value>
                <fullName>In transit</fullName>
            </value>
            <value>
                <fullName>Ready for Guest Collection</fullName>
            </value>
            <value>
                <fullName>Guest Collected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>the brand from which the case item relates to</description>
    <inlineHelpText>The shop that this item relates to</inlineHelpText>
    <label>Brand</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipName>Case_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/HFS_Bag__c.object-meta.xml
<CustomObject>
    <description>This object save the information of the Bags</description>
    <label>HFS Bag</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Bag Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Bags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Bag__c/fields/Barcode__c.field-meta.xml
<CustomField>
    <fullName>Barcode__c</fullName>
    <description>This is the visible numbers present on the Barcode</description>
    <inlineHelpText>Visible Barcode numbers</inlineHelpText>
    <label>Barcode</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/HFS_Bag_Active__c.field-meta.xml
<CustomField>
    <fullName>HFS_Bag_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Bag Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/HFS_Purchase__c.field-meta.xml
<CustomField>
    <fullName>HFS_Purchase__c</fullName>
    <description>This field is a master detail relationship with the purpose of getting the information of the corresponding HFS Case Item.</description>
    <label>HFS Purchase</label>
    <referenceTo>Case_Item__c</referenceTo>
    <relationshipLabel>HFS Bags</relationshipLabel>
    <relationshipName>HFS_Bags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Pick-up</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Putaway</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Bag Dropped</fullName>
            </value>
            <value>
                <fullName>Bag with GSA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HFS_IntegrationErrorTrackedBag__c/HFS_IntegrationErrorTrackedBag__c.object-meta.xml
<CustomObject>
    <label>HFS IntegrationError TrackedBag</label>
    <nameField>
        <displayFormat>IntegrationError-{0000}</displayFormat>
        <label>HFS IntegrationErrorTrackedBag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS IntegrationError TrackedBags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_IntegrationErrorTrackedBag__c/fields/Brand_Lease_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Lease_Id__c</fullName>
    <label>Brand Lease Id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_IntegrationErrorTrackedBag__c/fields/Brand_Location_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Location_Name__c</fullName>
    <label>Brand Location Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_IntegrationErrorTrackedBag__c/fields/Estimated_Spend__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Spend__c</fullName>
    <label>Estimated Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HFS_IntegrationErrorTrackedBag__c/fields/Guest_Code__c.field-meta.xml
<CustomField>
    <fullName>Guest_Code__c</fullName>
    <label>Guest Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_IntegrationErrorTrackedBag__c/fields/Is_Resolved__c.field-meta.xml
<CustomField>
    <fullName>Is_Resolved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resolved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HFS_IntegrationErrorTrackedBag__c/fields/List_of_Bags__c.field-meta.xml
<CustomField>
    <fullName>List_of_Bags__c</fullName>
    <label>List of Bags</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HFS_IntegrationErrorTrackedBag__c/fields/Number_of_Bags__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Bags__c</fullName>
    <label>Number of Bags</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogFile__c/LogFile__c.object-meta.xml
<CustomObject>
    <label>LogFile</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>LogFile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LogFiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogFile__c/fields/Body4__c.field-meta.xml
<CustomField>
    <fullName>Body4__c</fullName>
    <label>Body4</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogFile__c/fields/Integration_Record__c.field-meta.xml
<CustomField>
    <fullName>Integration_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Integration Record</label>
    <referenceTo>HFS_IntegrationErrorTrackedBag__c</referenceTo>
    <relationshipLabel>LogFiles</relationshipLabel>
    <relationshipName>LogFiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogFile__c/fields/LogFile_From_Resubmitted_Purchase__c.field-meta.xml
<CustomField>
    <fullName>LogFile_From_Resubmitted_Purchase__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LogFile From Resubmitted Purchase</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LogFile__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B2B Report Emails</fullName>
            </value>
            <value>
                <fullName>ETLWebService</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Logging_Enabled__c/Logging_Enabled__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Add classes to enable logging for those classes</description>
    <label>Logging Enabled</label>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Lease_ID__c.field-meta.xml
<CustomField>
    <fullName>Lease_ID__c</fullName>
    <externalId>true</externalId>
    <label>Lease ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deal Pending</fullName>
            </value>
            <value>
                <fullName>Trading</fullName>
            </value>
            <value>
                <fullName>in Refit</fullName>
            </value>
            <value>
                <fullName>Exited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateConiqPurchaseExtension.cls
public with sharing class CreateConiqPurchaseExtension {

	public static HFS_IntegrationErrorTrackedBag__c integrationError {get;set;}
    public TrackebBag newTrackedBag;
    public List<TrackebBag> listToResend;
    public Id recordId;

    public CreateConiqPurchaseExtension(ApexPages.StandardController stdController) {
        integrationError = (HFS_IntegrationErrorTrackedBag__c)stdController.getRecord();
        newTrackedBag = new TrackebBag();
        listToResend = new List<TrackebBag>();
        recordId = integrationError.Id;
    }

    public PageReference createConiqPurchase() {
        integrationError = [SELECT Id, Name, Brand_Lease_Id__c, Brand_Location_Name__c, DateTime__c, Estimated_Spend__c, Guest_Code__c, List_of_Bags__c, Number_of_Bags__c, Is_Resolved__c
                            FROM HFS_IntegrationErrorTrackedBag__c
                            WHERE Id =: recordId];
        newTrackedBag.lease_id = integrationError.Brand_Lease_Id__c;
        newTrackedBag.brand_location_name = integrationError.Brand_Location_Name__c;
        newTrackedBag.txn_datetime_utc = integrationError.DateTime__c;
        newTrackedBag.estimated_spend = integrationError.Estimated_Spend__c;
        newTrackedBag.guest_barcode = integrationError.Guest_Code__c;
        newTrackedBag.hfsbags_list = integrationError.List_of_Bags__c;
        newTrackedBag.numberofbags = integrationError.Number_of_Bags__c;
        listToResend.add(newTrackedBag);
        if(!integrationError.Is_Resolved__c){
            createPurchase(listToResend);
        }
        PageReference pageRef = new PageReference('/' + integrationError.Id);
        return pageRef;
    }

    public static void createPurchase(List<TrackebBag> newTrackedBags){
        Boolean logging = false;
        try{
            // Custom Setting object
            List<Logging_Enabled__c> loggingEnabled = [SELECT Id FROM Logging_Enabled__c WHERE Name = 'PETrackedBagTriggerHandler'];
            if(!loggingEnabled.isEmpty()){
                logging = true;
            }

        } catch (exception e){
            logging = false;
        }
        
        system.debug(logging);

        LogFile__c logCreatePurchase = new LogFile__c();

        Set<String> caseQRCodes = new Set<String>();
        Set<String> existingVillagePresence = new Set<String>();

        List<String> listExistingBags = new List<String>();
        Set<String> setExistingBags = new Set<String>();

        Map<String, TrackebBag> tbMapByGuest = new Map<String, TrackebBag>();
        Map<String, TrackebBag> tbMapByVillagePresence = new Map<String, TrackebBag>();
        Map<String, TrackebBag> tbMapByBags = new Map<String, TrackebBag>();

        Date today = system.today();

        for(TrackebBag bag : newTrackedBags){
            caseQRCodes.add(bag.guest_barcode);
            existingVillagePresence.add(bag.lease_id);
            tbMapByGuest.put(bag.guest_barcode, bag);
            tbMapByVillagePresence.put(bag.lease_id, bag);

            List<HFS_Bag__c> baglist = (List<HFS_Bag__c>)JSON.deserialize(bag.hfsbags_List, List<HFS_Bag__c>.Class); 
            
            for(HFS_Bag__c aBag : baglist){
                setExistingBags.add(aBag.Barcode__c);
                listExistingBags.add(aBag.Barcode__c);
                tbMapByBags.put(aBag.Barcode__c, bag);
            }
        }
        List<Case> theGuestCase = [SELECT Id, Client_QR_Code__c, Service_Guest_Number__c FROM Case WHERE Client_QR_Code__c IN :caseQRCodes AND Service_Date__c = :TODAY AND Status != 'Closed'];
        Map<String,Id> guestCaseMap = new Map<String,Id>();
        for(Case aCase : theGuestCase){
            guestCaseMap.put(aCase.Client_QR_Code__c,aCase.Id);
        }

        List<Village_Presence__c> theBrand = [SELECT Id, Lease_ID__c FROM Village_Presence__c WHERE Lease_ID__c IN :existingVillagePresence];
        Map<String,Id> brandMap = new Map<String,Id>();
        for(Village_Presence__c aBrand : theBrand){
            brandMap.put(aBrand.Lease_ID__c,aBrand.Id);
        }

        catchErrors(caseQRCodes, existingVillagePresence, theGuestCase, theBrand, tbMapByGuest, tbMapByVillagePresence);
        
        Boolean getResultAlreadyExist;
        String allBags = '';
        
        if(listExistingBags.size() == setExistingBags.size()){
            getResultAlreadyExist = verifyEquals(setExistingBags, tbMapByBags);
        } else {
            getResultAlreadyExist = true;
            logCreatePurchase.Type__c = 'Hands Free Shopping';
            logCreatePurchase.Body__c = 'PETrackedBagTriggerHandler - Errors related to repeated barcodes';
            logCreatePurchase.Body2__c = 'Bags Error - The information of Bags is repeated: ' + listExistingBags + '\n' + '\n';
            logCreatePurchase.Integration_Record__c = integrationError.Id;
            logCreatePurchase.LogFile_From_Resubmitted_Purchase__c = true;
            insert logCreatePurchase;
        }

        List<Case_Item__c> thePurchases = new List<Case_Item__c>();
        Case_Item__c purchase = new Case_Item__c();
        
        if(getResultAlreadyExist == false && theGuestCase.size() != 0){
            for(TrackebBag actualTrackedBag : newTrackedBags){
                    purchase.Case__c = guestCaseMap.get(actualTrackedBag.guest_barcode);
                    purchase.Village_Presence__c = brandMap.get(actualTrackedBag.lease_id);
                    purchase.Estimated_Spend__c = actualTrackedBag.estimated_spend;
                    purchase.Item_Count__c = actualTrackedBag.numberofbags;
                    purchase.Start_Time__c = actualTrackedBag.txn_datetime_utc;
                    purchase.Status__c = 'Awaiting Pick-up from Brand';
                    purchase.Require_a_Runner__c = true;
                    purchase.CurrencyIsoCode = 'GBP';
                    thePurchases.add(purchase);

                    if(logging == true){
                        logCreatePurchase.Type__c = 'Hands Free Shopping';
                        logCreatePurchase.Body__c = 'PETrackedBagTriggerHandler';
                        logCreatePurchase.Body2__c += 'The Purchase: ' + JSON.serialize(purchase);
                        logCreatePurchase.Body4__c += 'Request Body: ' + actualTrackedBag;
                    }
            //  }
            }

            insert thePurchases;

            Map<String,Id> allPurchases = new Map<String,Id>();
            for(Case_Item__c onePurchase : thePurchases){
                allPurchases.put(onePurchase.Case__c, onePurchase.Id);
            }

            List<HFS_Bag__c> allInsertedBags = new List<HFS_Bag__c>();
            String listOfBags = ' ';
            for(TrackebBag actualTrackedBag : newTrackedBags){
                
                List<HFS_Bag__c> baglist = (List<HFS_Bag__c>)JSON.deserialize(actualTrackedBag.hfsbags_List, List<HFS_Bag__c>.Class);    
                
                for(HFS_Bag__c aBag : baglist){
                    if(guestCaseMap.get(actualTrackedBag.guest_barcode) != null){
                        aBag.HFS_Purchase__c = allPurchases.get(guestCaseMap.get(actualTrackedBag.guest_barcode));
                        aBag.Status__c = 'Awaiting Pick-up';
                        allInsertedBags.add(aBag);

                        if(logging == true){
                            listOfBags += 'Bag: ' + aBag;
                            logCreatePurchase.Body3__c = 'The List of Bags: ' + listOfBags;
                        }
                    }
                }
            }

            insert allInsertedBags;

            if(logging == true){
                logCreatePurchase.LogFile_From_Resubmitted_Purchase__c = true;
                logCreatePurchase.Integration_Record__c = integrationError.Id;
                integrationError.Is_Resolved__c = true;
                upsert integrationError;
                insert logCreatePurchase;
            }
        }
    }

    public static void catchErrors(Set<String> caseQRCodes, Set<String> existingVillagePresence,
                                    List<Case> theGuestCase, List<Village_Presence__c> theBrand,
                                    Map<String, TrackebBag> tbMapByGuest, Map<String, TrackebBag> tbMapByVillagePresence){

        String fieldName = 'Client_QR_Code__c';
        Set<String> errorsQRCodes = new Set<String>();

        if(theGuestCase.size() != caseQRCodes.size()){
            Set<String> guestCasesSet = new Set<String>();
            for(Case c : theGuestCase){
                guestCasesSet.add((String)c.get(fieldName));
            }
            for(String qr : caseQRCodes){
                if(!guestCasesSet.contains(qr)){
                    errorsQRCodes.add(qr);
                }
            }
        }

        fieldName = 'Lease_ID__c';
        Set<String> errorsVillagePresenceCodes = new Set<String>();

        if(theBrand.size() != existingVillagePresence.size()){
            Set<String> villagePresenceSet = new Set<String>();
            for(Village_Presence__c vp : theBrand){
                villagePresenceSet.add((String)vp.get(fieldName)); 
            }
            for(String vpcode : existingVillagePresence){
                if(!villagePresenceSet.contains(vpcode)){
                    errorsVillagePresenceCodes.add(vpcode);
                }
            }
        }

        LogFile__c logCatchErrors = new LogFile__c();
        logCatchErrors.Type__c = 'Hands Free Shopping';
        logCatchErrors.Body__c = 'PETrackedBagTriggerHandler - Errors related to Lookups';

        String getErrorsQRCodes = ' ';
        String getErrorsVillagePresence = ' ';

        for(String q : errorsQRCodes){
            getErrorsQRCodes += 'Invalid QR Codes: ' + q + '| From Message: ' + tbMapByGuest.get(q)  + '\n' + '\n';
            logCatchErrors.Body3__c = getErrorsQRCodes;
        }

        for(String vp : errorsVillagePresenceCodes){
            getErrorsVillagePresence += 'Invalid Lease ID for existing Village Presence: ' + vp + '| From Message: ' + tbMapByVillagePresence.get(vp) + '\n' + '\n';
            logCatchErrors.Body4__c = getErrorsVillagePresence;
        }

        if(!errorsQRCodes.isEmpty() || !errorsVillagePresenceCodes.isEmpty()){
            logCatchErrors.Integration_Record__c = integrationError.Id;
            logCatchErrors.LogFile_From_Resubmitted_Purchase__c = true;
            insert logCatchErrors;
        }
    }

    public static Boolean verifyEquals(Set<String> existingBags, Map<String, TrackebBag> mapCurrentBags){
        Boolean isEqual = false;
        
        List<HFS_Bag__c> allHFSBags = [SELECT Id, Barcode__c FROM HFS_Bag__c WHERE HFS_Bag_Active__c = true AND Barcode__c IN :existingBags];

        String fieldName = 'Barcode__c';
        Set<String> repeatedHFSBags = new Set<String>();

        if(!allHFSBags.isEmpty()){
            isEqual = true;
            
            for (HFS_Bag__c b : allHFSBags){
                repeatedHFSBags.add((String)b.get(fieldName)); 
            }

            LogFile__c logCatchErrors = new LogFile__c();
            logCatchErrors.Type__c = 'Hands Free Shopping';
            logCatchErrors.Body__c = 'PETrackedBagTriggerHandler - Errors related to repeated barcodes';

            String getErrorsHFSBags = ' ';
            for (String b : repeatedHFSBags){
                getErrorsHFSBags += 'This HFS Bag is already inserted in the system: ' + b + '| From Message: ' + mapCurrentBags.get(b) + '\n' + '\n';
                logCatchErrors.Body2__c = getErrorsHFSBags;
                // System.debug('Notification: ' + 'Invalid Invalid Lease ID for existing Village Presence: ' + b + '| From Message: ' + tbMapByBags.get(vp));
            }
            if(!repeatedHFSBags.isEmpty()){
                logCatchErrors.Integration_Record__c = integrationError.Id;
                logCatchErrors.LogFile_From_Resubmitted_Purchase__c = true;
                insert logCatchErrors;
            }
        }
        return isEqual;
    }

    private class TrackebBag{
        String lease_id;
        String brand_location_name;
        Datetime txn_datetime_utc;
        Decimal estimated_spend;
        String guest_barcode;
        String hfsbags_list;
        Decimal numberofbags;
    }
}