force-app/main/default/objects/Case/fields/Guest_ID_Number_Part__c.field-meta.xml
<CustomField>
    <fullName>Guest_ID_Number_Part__c</fullName>
    <description>the number portion of the guest ID. for use with getting an increment</description>
    <inlineHelpText>the number portion of the guest ID. for use with getting an increment</inlineHelpText>
    <label>Guest ID Number Part</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>the status of payment for the service</description>
    <inlineHelpText>the status of payment for the service</inlineHelpText>
    <label>Payment Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Payment on Collection</fullName>
            </value>
            <value>
                <fullName>Free of charge (Valet)</fullName>
            </value>
            <value>
                <fullName>Free of charge (VIP)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Guest_ID__c.field-meta.xml
<CustomField>
    <fullName>Service_Guest_ID__c</fullName>
    <description>a unique generated ID to identify the guest, and the date</description>
    <inlineHelpText>a unique generated ID to identify the guest, and the date</inlineHelpText>
    <label>Service Guest ID</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Guest_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Guest_Number__c</fullName>
    <description>The generated number assigned to the guest for the service for the day</description>
    <inlineHelpText>The generated number assigned to the guest for the service for the day</inlineHelpText>
    <label>Service Guest Number</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The village that this HFS service will be at</description>
    <inlineHelpText>The village that this HFS service will be at</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Shopping_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/Case_Item__c.object-meta.xml
<CustomObject>
    <description>a specific sub item under the case object</description>
    <label>HFS Purchase</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>HFS Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Purchases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Item__c/fields/Service_Guest_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Guest_Number__c</fullName>
    <formula>Case__r.Service_Guest_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Guest Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>the status of the item....</description>
    <inlineHelpText>the status of the item</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Pick-up from Brand</fullName>
            </value>
            <value>
                <fullName>In transit</fullName>
            </value>
            <value>
                <fullName>Ready for Guest Collection</fullName>
            </value>
            <value>
                <fullName>Guest Collected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>the brand from which the case item relates to</description>
    <inlineHelpText>The shop that this item relates to</inlineHelpText>
    <label>Brand</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipName>Case_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/HFS_Bag__c.object-meta.xml
<CustomObject>
    <description>This object save the information of the Bags</description>
    <label>HFS Bag</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Bag Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Bags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Bag__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/HFS_Runner__c.field-meta.xml
<CustomField>
    <fullName>HFS_Runner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFS Runner</label>
    <referenceTo>HFS_Runner__c</referenceTo>
    <relationshipLabel>HFS Bags</relationshipLabel>
    <relationshipName>HFS_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Pick-up</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Putaway</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Bag Dropped</fullName>
            </value>
            <value>
                <fullName>Bag with GSA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HFS_Job__c/HFS_Job__c.object-meta.xml
<CustomObject>
    <description>A junction object between User and Case_Item__c that will record all of the jobs of HFS Experiences.</description>
    <label>HFS Job</label>
    <nameField>
        <displayFormat>J-{00000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Job__c/fields/HFS_Runner__c.field-meta.xml
<CustomField>
    <fullName>HFS_Runner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFS Runner</label>
    <referenceTo>HFS_Runner__c</referenceTo>
    <relationshipLabel>HFS Jobs</relationshipLabel>
    <relationshipName>HFS_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Runner__c/HFS_Runner__c.object-meta.xml
<CustomObject>
    <label>HFS Runner</label>
    <nameField>
        <label>HFS Runner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HFS Runners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Runner__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>It should be a a HFS Runner</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>HFS Runner</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>HFS VR Assistant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>HFS_Runners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Runner__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Organisation__c</fullName>
    <description>The business unit within oracle</description>
    <inlineHelpText>The business unit within oracle</inlineHelpText>
    <label>Oracle Organisation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Source_Template_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Source_Template_Number__c</fullName>
    <description>The value used to map to an oracle template when sent to Oracle Fusion</description>
    <inlineHelpText>The value used to map to an oracle template when sent to Oracle Fusion</inlineHelpText>
    <label>Oracle Source Template Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Village Presence records must be linked to Brand accounts. Please ensure you are not linking the Deal/Village Presence to a Group</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deal Pending</fullName>
            </value>
            <value>
                <fullName>Trading</fullName>
            </value>
            <value>
                <fullName>in Refit</fullName>
            </value>
            <value>
                <fullName>Exited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/HFSDisplayBagsControllerTest.cls
@isTest
public class HFSDisplayBagsControllerTest {

    static void setupData(){

        Profile profileRunner = [SELECT ID, Name FROM Profile WHERE Name = 'HFS Runner'];

        UserRole runnerRole = new UserRole();
        runnerRole.DeveloperName = 'CustomRole';
        runnerRole.Name = 'Custom Role';
        insert runnerRole;


        User runner = new User();
        runner.LastName = 'John';
        runner.Alias = 'jhn';
        runner.Email = 'john@valueretai.com';
        runner.Username = 'john@valueretai.com';
        runner.CommunityNickname = 'johnvr';
        runner.UserRoleId = runnerRole.Id;
        runner.ProfileId = profileRunner.Id;
        runner.Village__c = 'Bicester';
        runner.TimeZoneSidKey = 'GMT';
        runner.LocaleSidKey = 'en_GB';
        runner.EmailEncodingKey = 'ISO-8859-1';
        runner.LanguageLocaleKey = 'en_US';
        insert runner;

        system.runAs(runner){
            // first create a village
            Village__c vill = TestDataGenerator.setupVillage(false);
            vill.Oracle_Source_Template_Number__c = '123456';
            vill.Oracle_Organisation__c = 'SourceOrg';
            vill.Name = 'Bicester';
            vill.CertSales_CertPeriod_Cut_Off_Days__c = 1;
            vill.CertSales_Report_Sales_Grace_Period_Days__c = 1;
            insert vill;

            RecordType brandRecordType = [SELECT Id, Name FROM RecordType WHERE Name = 'Brand'];
            RecordType guestRecordType = [SELECT Id, Name FROM RecordType WHERE Name = 'Guest'];

            Account brand = new Account();
            brand.RecordTypeId = brandRecordType.Id;
            brand.Name = 'Brand 1';
            insert brand;

            Village_Presence__c presentBrand = new Village_Presence__c();
            presentBrand.Name = 'Brand1 in village';
            presentBrand.Brand__c = brand.Id;
            presentBrand.Village__c = vill.Id;
            insert presentBrand;

            HFS_Runner__c runnerRecord = new HFS_Runner__c();
            runnerRecord.Name = 'John';
            runnerRecord.Village__c = 'Bicester';
            runnerRecord.User__c = runner.Id;
            insert runnerRecord;

            Case guestCase = new Case();
            guestCase.Village__c = vill.Id;
            guestCase.Service_Guest_ID__c = '123456789';
            guestCase.Service_Guest_Number__c = 'XA1';
            guestCase.Guest_ID_Number_Part__c = 12;
            guestCase.Payment_Status__c = 'Paid';
            guestCase.Client_QR_Code__c = '123456789';
            guestCase.Status = 'New';
            guestCase.Origin = 'Email';
            guestCase.Service_Date__c = system.today();
            insert guestCase;

            Case newGuest = [SELECT ID, Service_Guest_ID__c, Village__c FROM Case WHERE Service_Guest_ID__c = '123456789'];

            Case_Item__c hfsPurchase = new Case_Item__c();
            hfsPurchase.Case__c = guestCase.Id;
            hfsPurchase.Status__c = 'Awaiting Pick-up from Brand';
            hfsPurchase.Start_Time__c = system.now();
            hfsPurchase.Item_Count__c = 3;
            hfsPurchase.Bag_Barcodes_Manual__c = '123456,false,123457,true,152635,false';
            hfsPurchase.Require_a_Runner__c = true;
            hfsPurchase.HFS_Bag_Transfer__c = false;
            hfsPurchase.Village_Presence__c = presentBrand.Id;
            insert hfsPurchase;

            HFS_Job__c jobAssigned = [SELECT Id, HFS_Runner__c, HFS_Purchase__c FROM HFS_Job__c WHERE HFS_Purchase__c =: hfsPurchase.Id];
            jobAssigned.HFS_Runner__c = runnerRecord.Id;
            jobAssigned.Take_job_for_me__c = true;
            update jobAssigned;
        }
    }

    static testMethod void getBagsMethodTestN1(){
        setupData();

        HFS_Job__c purchaseJob = [SELECT Id FROM HFS_Job__c WHERE HFS_Purchase__r.Item_Count__c = 3];
        User userRunner = [SELECT Id FROM User WHERE Name = 'John'];

        System.runAs(userRunner){
            Test.startTest();
                PageReference pageRef = Page.HFSDisplayBags;
                Test.setCurrentPage(pageRef);
                
                pageRef.getParameters().put('id', purchaseJob.Id);
                pageRef.getParameters().put('barcodeBag', '123000');
                ApexPages.StandardController sc = new ApexPages.StandardController(purchaseJob);
                HFSDisplayBagsController controller = new HFSDisplayBagsController(sc);
                controller.updateBags();
                controller.finishJob();
            Test.stopTest();

            System.assertEquals(null, controller.finishJob());
        }
    }

    static testMethod void getBagsMethodTestN2(){
        setupData();

        
        User userRunner = [SELECT Id FROM User WHERE Name = 'John'];

        System.runAs(userRunner){
            HFS_Job__c purchaseJob = [SELECT Id, Total_Bags__c, HFS_Runner__c, Assigned_to_me__c, Take_job_for_me__c, Bags_collected__c FROM HFS_Job__c WHERE HFS_Purchase__r.Item_Count__c = 3];
            Test.startTest();
                PageReference pageRef = Page.HFSDisplayBags;
                Test.setCurrentPage(pageRef);
                
                pageRef.getParameters().put('id', purchaseJob.Id);
                pageRef.getParameters().put('barcodeBag', '123456');
                ApexPages.StandardController sc = new ApexPages.StandardController(purchaseJob);
                HFSDisplayBagsController controller = new HFSDisplayBagsController(sc);
                system.debug('pep ' + purchaseJob);
                controller.updateBags();
                controller.scanBag();
                controller.finishJob();
            Test.stopTest();

            List<HFS_Job__c> thePurchaseJob = [SELECT Id, Job_Status__c, Job_Type__c FROM HFS_Job__c WHERE HFS_Purchase__r.Item_Count__c = 3];
            HFS_Bag__c theBag = [SELECT Id, Status__c, Scanned__c, HFS_Runner__c, HFS_Job__c FROM HFS_Bag__c WHERE Barcode__c = '123456'];
            HFS_Runner__c theRunner = [SELECT Id FROM HFS_Runner__c WHERE User__c = :userRunner.Id];

            System.assertNotEquals(null, controller.scanBag());
            System.assertEquals('In Transit', theBag.Status__c);
            System.assertEquals(true, theBag.Scanned__c);
            System.assertEquals(theRunner.Id, theBag.HFS_Runner__c);
            System.assertEquals(2, thePurchaseJob.size());
            System.assertNotEquals(purchaseJob.Total_Bags__c, purchaseJob.Bags_collected__c);
        }
    }

    static testMethod void getBagsMethodTestN3(){
        setupData();

        Case_Item__c purchaseId = [SELECT Id FROM Case_Item__c WHERE Item_Count__c = 3];
        HFS_Job__c purchaseJob = [SELECT Id, Total_Bags__c, Bags_collected__c FROM HFS_Job__c WHERE HFS_Purchase__c = :purchaseId.Id];
        User userRunner = [SELECT Id FROM User WHERE Name = 'John'];

        System.runAs(userRunner){
            HFS_Bag__c newTBCBag = new HFS_Bag__c();
            newTBCBag.Barcode__c = 'TBC';
            newTBCBag.HFS_Purchase__c = purchaseId.Id;
            insert newTBCBag;

            Test.startTest();
                PageReference pageRef = Page.HFSDisplayBags;
                Test.setCurrentPage(pageRef);
                
                pageRef.getParameters().put('id', purchaseJob.Id);
                pageRef.getParameters().put('barcodeBag', '0120302');
                ApexPages.StandardController sc = new ApexPages.StandardController(purchaseJob);
                HFSDisplayBagsController controller = new HFSDisplayBagsController(sc);
                controller.updateBags();
                controller.scanBag();
                controller.finishJob();
            Test.stopTest();

            List<HFS_Job__c> thePurchaseJob = [SELECT Id, Job_Status__c, Job_Type__c FROM HFS_Job__c WHERE HFS_Purchase__c = :purchaseId.Id];
            HFS_Bag__c theBag = [SELECT Id, Status__c, Scanned__c, HFS_Runner__c, HFS_Job__c FROM HFS_Bag__c WHERE Barcode__c = '0120302'];
            HFS_Runner__c theRunner = [SELECT Id FROM HFS_Runner__c WHERE User__c = :userRunner.Id];

            System.assertNotEquals(null, controller.scanBag());
            System.assertEquals('In Transit', theBag.Status__c);
            System.assertEquals(true, theBag.Scanned__c);
            System.assertEquals(theRunner.Id, theBag.HFS_Runner__c);
            System.assertEquals(2, thePurchaseJob.size());
            System.assertNotEquals(purchaseJob.Total_Bags__c, purchaseJob.Bags_collected__c);
        }
    }
}