force-app/main/default/objects/Case/fields/Language_on_Registration__c.field-meta.xml
<CustomField>
    <fullName>Language_on_Registration__c</fullName>
    <label>Language on Registration</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The village that this HFS service will be at</description>
    <inlineHelpText>The village that this HFS service will be at</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Shopping_Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Label__c/Custom_Label__c.object-meta.xml
<CustomObject>
    <description>Overridden custom labels, to be used for translations where the translation workbench wont  work</description>
    <label>Custom Label</label>
    <nameField>
        <label>Custom Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Labels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Label__c/fields/Custom_Label_Value__c.field-meta.xml
<CustomField>
    <fullName>Custom_Label_Value__c</fullName>
    <description>The label value to be displayed on screen</description>
    <inlineHelpText>The label value to be displayed on screen</inlineHelpText>
    <label>Custom Label Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Label__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>The language that the label is displayed in</description>
    <inlineHelpText>The language that the label is displayed in</inlineHelpText>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en</fullName>
            </value>
            <value>
                <fullName>es</fullName>
            </value>
            <value>
                <fullName>de</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
            </value>
            <value>
                <fullName>ca</fullName>
            </value>
            <value>
                <fullName>nl</fullName>
            </value>
            <value>
                <fullName>it</fullName>
            </value>
            <value>
                <fullName>ru</fullName>
            </value>
            <value>
                <fullName>cn</fullName>
            </value>
            <value>
                <fullName>ar</fullName>
            </value>
            <value>
                <fullName>ae</fullName>
            </value>
            <value>
                <fullName>kr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Privacy_Policy_URLs__c/Village_Privacy_Policy_URLs__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used in HFS app for multilanguage Ts&amp;Cs and Privacy Policies</description>
    <label>Village Privacy Policy URLs</label>
</CustomObject>

force-app/main/default/objects/Village_Privacy_Policy_URLs__c/fields/Village_Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Village_Terms_and_Conditions__c</fullName>
    <description>.</description>
    <label>Village Terms and Conditions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village_Privacy_Policy_URLs__c/fields/VillageLink__c.field-meta.xml
<CustomField>
    <fullName>VillageLink__c</fullName>
    <description>village-privacy-notice.</description>
    <label>VillageLink</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/getVillageLanguageURL.cls
Global class getVillageLanguageURL{

    public Id caseId {get;set;}   
    public returnobject theURls {get {
        returnobject ret = new returnobject();
       
        case thecase = [select id,Village__r.name, Language_on_Registration__c from Case where id =:caseId ];
        list<Custom_Label__c> labels = [SELECT id, Name, Custom_Label_Value__c,Language__c FROM Custom_Label__c where
                                        (Name = 'VillagePrivacyNotice' OR Name = 'TermsConditions') AND Language__c =:thecase.Language_on_Registration__c ];
        system.debug('labels -- ' + labels);
        for(Custom_Label__c label : labels){
            if(label.name == 'VillagePrivacyNotice'){
                ret.theVillagePrivacyPolicy = label.Custom_Label_Value__c;
            }
            if (label.name == 'TermsConditions'){
                 ret.theVillageTermsandConditions = label.Custom_Label_Value__c;
            }

        }   
        
        string thequery = thecase.Village__r.name + '-' + thecase.Language_on_Registration__c;
        Village_Privacy_Policy_URLs__c villageURL = [SELECT id, Name,VillageLink__c,Village_Terms_and_Conditions__c FROM Village_Privacy_Policy_URLs__c WHERE name =: thequery LIMIT 1 ];
        ret.theVillageTermsandConditionsURL = villageURL.Village_Terms_and_Conditions__c;
        ret.theVillagePrivacyPolicyURL = villageURL.VillageLink__c;
        
        return ret;
                                       }  
    	set; }
    
    
      
    	global class returnobject{
            public string theVillageTermsandConditions {get;set;}
            public string theVillageTermsandConditionsURL {get;set;}
            public string theVillagePrivacyPolicy {get;set;}
            public string theVillagePrivacyPolicyURL {get;set;}
        
        
    	}
   
}