force-app/main/default/objects/LogFile__c/LogFile__c.object-meta.xml
<CustomObject>
    <label>LogFile</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>LogFile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LogFiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogFile__c/fields/Date_Time_Created__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Created__c</fullName>
    <label>Date/Time Created</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/LogFile__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B2B Report Emails</fullName>
            </value>
            <value>
                <fullName>ETLWebService</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Logger.cls
public without sharing class Logger {

   private String logType;
   private String toAppend;

	public Logger(String logType) {
    	this.toAppend = '';
   		this.logType = logType;
   	}

   	public void log(String message) {
   		
   		System.Debug(message);
      	toAppend = toAppend + '\n' + System.now().format() + ': ' + message;
   	}


   public void commitLog() {
   		try {
   			System.debug('Committing Log: ' + toAppend);
         	LogFile__c log = createLog();
         	if(!Properties.IS_TEST_METHOD){
      			insert log;
         	}
      		toAppend='';
   		} catch (Exception e) {
   			System.debug('Failed to commit logs: ' + e);
   		}
   }

   private LogFile__c createLog() {
   		LogFile__c log = new LogFile__c();
      	log.Type__c = logType;
      	log.Date__c = System.today();
        log.Date_Time_Created__c = System.now();
      	
      	if (toAppend.length() > 32000) {
      		toAppend = toAppend.substring(0, 31999);
      	}
      	log.Body__c = toAppend;
      	return log;
   }
}