force-app/main/default/objects/Adbuilder__c/Adbuilder__c.object-meta.xml
<CustomObject>
    <label>Adbuilder</label>
    <nameField>
        <label>Adbuilder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adbuilders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adbuilder__c/fields/Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Activity</label>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipLabel>Adbuilders</relationshipLabel>
    <relationshipName>Adbuilders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Adbuilder__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Campaign</label>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Adbuilders</relationshipLabel>
    <relationshipName>Adbuilders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <description>....</description>
    <label>Marketing Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You cannot link an activity to a &apos;Cancelled&apos;  Campaign.</errorMessage>
        <filterItems>
            <field>Marketing_Campaign__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Activities</relationshipLabel>
    <relationshipName>Marketing_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AdbuilderTriggerHandler.cls
public class AdbuilderTriggerHandler {
    
    public static void AdbuilderInsert(List<Adbuilder__c> AdbuilderList ){
        
        List<Adbuilder__c> adList = new List<Adbuilder__c>();
        
        for (Adbuilder__c orderAdbuilderList : AdbuilderList){
            adList.add(orderAdbuilderList);
        }
        
        
        if(adList != null && !adList.isEmpty()){
            getMarketingCampa(adList);
        }
    }
    
    public static void dbuilderBeforeInsert(Map<Id, Adbuilder__c> oldADMap, Map<Id, Adbuilder__c> newADMap){
        List<Adbuilder__c> adList = new List<Adbuilder__c>();
        
        for(Adbuilder__c orderAdbuilderList : newADMap.values()){
            if(orderAdbuilderList.Marketing_Campaign__c == null && orderAdbuilderList.Marketing_Activity__c != null){
                adList.add(orderAdbuilderList);
            }
        }
        
        if(adList != null && !adList.isEmpty()){
            getMarketingCampa(adList);
        }
    }
    
    
    public static void getMarketingCampa(List<Adbuilder__c> AdUpdate){
        Map<Id, Id> campaigmmAP = new Map<Id, Id>();
        List<Marketing_Activity__c> actList = new List<Marketing_Activity__c>();
        
        for(Adbuilder__c orderAdbuilderList : AdUpdate){
            campaigmmAP.put(orderAdbuilderList.Marketing_Activity__c, null);
        }
        
        actList = [SELECT Id, Marketing_Campaign__c 
                   FROM Marketing_Activity__c 
                   WHERE Id IN :campaigmmAP.keySet()];
        
        if(actList != null && !actList.isEmpty()){
            for(Marketing_Activity__c act : actList){
                if(act.Marketing_Campaign__c != null){
                    campaigmmAP.put(act.Id, act.Marketing_Campaign__c);
                }
            }
        }
        
        for(Adbuilder__c orderAdbuilderList : AdUpdate){
            if(campaigmmAP.keySet().contains(orderAdbuilderList.Marketing_Activity__c)){
                orderAdbuilderList.Marketing_Campaign__c = campaigmmAP.get(orderAdbuilderList.Marketing_Activity__c);
                
            }
        }
    }
}