force-app/main/default/objects/Adbuilder__c/Adbuilder__c.object-meta.xml
<CustomObject>
    <label>Adbuilder</label>
    <nameField>
        <label>Adbuilder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adbuilders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adbuilder__c/fields/Format__c.field-meta.xml
<CustomField>
    <fullName>Format__c</fullName>
    <defaultValue>$RecordType.Name</defaultValue>
    <description>..</description>
    <label>Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Adbuilder_Record_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adbuilder__c/recordTypes/Canvas.recordType-meta.xml
<RecordType>
    <fullName>Canvas</fullName>
    <active>true</active>
    <label>Facebook Canvas</label>
</RecordType>

force-app/main/default/globalValueSets/Adbuilder_Record_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Facebook Image Link Ad</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram Story</fullName>
    </customValue>
    <customValue>
        <fullName>Video Link Ad</fullName>
    </customValue>
    <customValue>
        <fullName>Video Post Page</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook Carousel</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook Canvas</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram Carousel</fullName>
    </customValue>
    <customValue>
        <fullName>Mixed Placement Paid Social</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook Story</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram Link Image Ad</fullName>
    </customValue>
    <customValue>
        <fullName>Canvas</fullName>
        <isActive>false</isActive>
        <label>Canvas</label>
    </customValue>
    <customValue>
        <fullName>Carousel</fullName>
        <isActive>false</isActive>
        <label>Carousel</label>
    </customValue>
    <customValue>
        <fullName>Image Post Page</fullName>
        <isActive>false</isActive>
        <label>Image Post Page</label>
    </customValue>
    <description>....</description>
    <masterLabel>Adbuilder Record Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DownloadAdbuilderController.cls
public class DownloadAdbuilderController {
    
        public String xlsHeader {
        get {
            String strHeader = '';
            strHeader += '<?xml version="2.0"?>';
            strHeader += '<?mso-application progid="Excel.Sheet"?>';
            return strHeader;
        }
    }
    
    public DownloadAdbuilderController(ApexPages.StandardController controller) {

    }
    
    @AuraEnabled
    public static String getLink(String recordId){
        Adbuilder__c rec = [SELECT Id, Format__c FROM Adbuilder__c WHERE Id = :recordId];
        
        String vfPage = null;
        
        if(rec.Format__c == 'Facebook Canvas'){
            vfPage = 'DownloadAdbuilderCanvasPage';
        }
        else if(rec.Format__c == 'Facebook Carousel' || rec.Format__c == 'Instagram Carousel'){
            vfPage = 'DownloadAdbuilderCarouselPage';
        }
        else if(rec.Format__c == 'Instagram Story'){
            vfPage = 'DownloadAdbuilderInstagramStoryPage';
        }
        else if(rec.Format__c == 'Facebook Image Link Ad'){
            vfPage = 'DownloadAdbuilderImageLinkAdPage';
        }
        else if(rec.Format__c == 'Image Post Page'){
            vfPage = 'DownloadAdbuilderImagePostPage';
        }
        else if(rec.Format__c == 'Video Link Ad'){
            vfPage = 'DownloadAdbuilderVideoLinkAdPage';
        }
        else if(rec.Format__c == 'Video Post Page'){
            vfPage = 'DownloadAdbuilderVideoPostPage';
        }
        
        if(vfPage == null) return null;
        
        return '/apex/' + vfPage + '?id=' + rec.Id;
    }
    
}