force-app/main/default/objects/Adbuilder__c/Adbuilder__c.object-meta.xml
<CustomObject>
    <label>Adbuilder</label>
    <nameField>
        <label>Adbuilder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adbuilders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adbuilder__c/fields/Format__c.field-meta.xml
<CustomField>
    <fullName>Format__c</fullName>
    <defaultValue>$RecordType.Name</defaultValue>
    <description>..</description>
    <label>Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Adbuilder_Record_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adbuilder__c/recordTypes/Canvas.recordType-meta.xml
<RecordType>
    <fullName>Canvas</fullName>
    <active>true</active>
    <label>Facebook Canvas</label>
</RecordType>

force-app/main/default/globalValueSets/Adbuilder_Record_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Facebook Image Link Ad</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram Story</fullName>
    </customValue>
    <customValue>
        <fullName>Video Link Ad</fullName>
    </customValue>
    <customValue>
        <fullName>Video Post Page</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook Carousel</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook Canvas</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram Carousel</fullName>
    </customValue>
    <customValue>
        <fullName>Mixed Placement Paid Social</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook Story</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram Link Image Ad</fullName>
    </customValue>
    <customValue>
        <fullName>Canvas</fullName>
        <isActive>false</isActive>
        <label>Canvas</label>
    </customValue>
    <customValue>
        <fullName>Carousel</fullName>
        <isActive>false</isActive>
        <label>Carousel</label>
    </customValue>
    <customValue>
        <fullName>Image Post Page</fullName>
        <isActive>false</isActive>
        <label>Image Post Page</label>
    </customValue>
    <description>....</description>
    <masterLabel>Adbuilder Record Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DownloadAdbuilderTest.cls
@isTest
public class DownloadAdbuilderTest {
    
    @isTest
    static   void TestDownloadAdbuilder(){
        Adbuilder__c adb = new Adbuilder__c (Name ='Test');
        insert adb;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(adb);
        DownloadAdbuilderController con = new DownloadAdbuilderController(sc);
        
        system.debug('*******con.xlsHeader********'+con.xlsHeader);
        
    }

    @isTest
    static void testgetLink1(){
        Adbuilder__c adb = new Adbuilder__c (Name ='Test', Format__c = null);
        insert adb;
        
        String url = DownloadAdbuilderController.getLink(adb.Id);
        system.assertEquals(null, url);
    }
    
    @isTest
    static void testgetLink2(){
        Id recordypeId = Schema.getGlobalDescribe().get('Adbuilder__c').getDescribe().getRecordTypeInfosByName().get('Instagram Story').getRecordTypeId();
        Adbuilder__c adb = new Adbuilder__c (Name ='Test', RecordTypeID = recordypeId, Format__c = 'Instagram Story');
        insert adb;
        
        String url = DownloadAdbuilderController.getLink(adb.Id);
        system.assert(url != null);
    }
    
    @isTest
    static void testgetLinkAll(){
        Map<String,Schema.RecordTypeInfo> recordypeInfoByName = Schema.getGlobalDescribe().get('Adbuilder__c').getDescribe().getRecordTypeInfosByName();
        Map<String, String> recTypeNameToFormat = new Map<String, String>();
        recTypeNameToFormat.put('Facebook Canvas', 'Facebook Canvas');
        recTypeNameToFormat.put('Facebook Carousel', 'Facebook Carousel');
     	recTypeNameToFormat.put('Instagram Carousel', 'Instagram Carousel');
        recTypeNameToFormat.put('Instagram Story', 'Instagram Story');
        recTypeNameToFormat.put('Facebook Image Link Ad', 'Facebook Image Link Ad');
        recTypeNameToFormat.put('Video Link Ad', 'Video Link Ad');
        recTypeNameToFormat.put('Video Post Page', 'Video Post Page');
                    
        List<Adbuilder__c> adBuilderList = new List<Adbuilder__c>(); 
        for(String recTypeName: recTypeNameToFormat.keySet()){
            Id recTypeID = recordypeInfoByName.get(recTypeName).getRecordTypeId();
            String format = recTypeNameToFormat.get(recTypeName);
            adBuilderList.add(new Adbuilder__c (Name ='Test', RecordTypeID = recTypeID, Format__c = format));
        }
        insert adBuilderList;
        
        for(Adbuilder__c adb: adBuilderList){
            String url = DownloadAdbuilderController.getLink(adb.Id);
            system.assert(url != null);
        }
    }
    
}