force-app/main/default/objects/Daily_Sale__c/Daily_Sale__c.object-meta.xml
<CustomObject>
    <label>Daily Sale</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>Daily Sale Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Sale__c/fields/Auxiliar_Variance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Auxiliar_Variance_Amount__c</fullName>
    <formula>IF(Variance_Amount__c == NULL,NULL,ABS( Variance_Amount__c ))</formula>
    <label>Auxiliar Variance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Brand_Reported_Amount__c.field-meta.xml
<CustomField>
    <fullName>Brand_Reported_Amount__c</fullName>
    <description>This field is looks at in the INT_Reported_Amount formula field and passed through to MRI via that field if the OVERRIDE RPT AMOUNT field is NULL</description>
    <inlineHelpText>This is the Total Net Sales and the total Net Value of Discounts for the day added together.</inlineHelpText>
    <label>Brand Reported Amount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Certification_Batch__c.field-meta.xml
<CustomField>
    <fullName>Certification_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certification Batch</label>
    <referenceTo>Daily_Sales_Certification_Batch__c</referenceTo>
    <relationshipLabel>Daily Sales</relationshipLabel>
    <relationshipName>Daily_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Certification_Comment__c.field-meta.xml
<CustomField>
    <fullName>Certification_Comment__c</fullName>
    <inlineHelpText>Any Sales Certification comments for this date added by the Brand Head Office user</inlineHelpText>
    <label>Certification Comment</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Certified_Amount__c.field-meta.xml
<CustomField>
    <fullName>Certified_Amount__c</fullName>
    <description>Maps to MRI: CERAMOUNT</description>
    <inlineHelpText>The total Certified Sales Amount for this date that is submitted by the Brand Head Office.  Once Approved by VR Finance this will integrate across to MRI.</inlineHelpText>
    <label>Certified Amount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Certified_Amount_Discount_Input__c.field-meta.xml
<CustomField>
    <fullName>Certified_Amount_Discount_Input__c</fullName>
    <description>This field appear on the Brand Portal front-end view (Certification table). It will be editable there and do not integrate with MRI.</description>
    <inlineHelpText>The total Certified Discount Amount for this date that is submitted by the Brand Head Office.  Once Approved by VR Finance this will integrate across to MRI.</inlineHelpText>
    <label>Certified Amount Discount Input</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Certified_Amount_NetTotal_Input__c.field-meta.xml
<CustomField>
    <fullName>Certified_Amount_NetTotal_Input__c</fullName>
    <description>This field appear on the Brand Portal front-end view (Certification table). It will be editable there and do not integrate with MRI.</description>
    <inlineHelpText>The total Certified Net Sales Amount for this date that is submitted by the Brand Head Office</inlineHelpText>
    <label>Certified Amount NetTotal Input</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/MRI_Suite_Id__c.field-meta.xml
<CustomField>
    <fullName>MRI_Suite_Id__c</fullName>
    <label>Unit</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/NET_Value_of_Discounts__c.field-meta.xml
<CustomField>
    <fullName>NET_Value_of_Discounts__c</fullName>
    <inlineHelpText>NET Value of Discounts</inlineHelpText>
    <label>NET Value of Discounts</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_End_Date__c</fullName>
    <description>MRI: Daily Sales Certification Batch Start Period</description>
    <formula>Certification_Batch__r.Period_End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CertBatchEndDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <description>MRI: Daily Sales Certification Batch Start Period</description>
    <formula>Certification_Batch__r.Period_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CertBatchStartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <color>#FF0000</color>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Reported Incomplete</fullName>
                <color>#FF9900</color>
                <label>Reported Incomplete</label>
            </value>
            <value>
                <fullName>Reported Confirmed</fullName>
                <color>#33CC00</color>
                <label>Reported Confirmed</label>
            </value>
            <value>
                <fullName>TOR</fullName>
            </value>
            <value>
                <fullName>Certified Pending</fullName>
            </value>
            <value>
                <fullName>Certified Approved</fullName>
            </value>
            <value>
                <fullName>Certified Complete</fullName>
            </value>
            <value>
                <fullName>Certified Re-opened</fullName>
            </value>
            <value>
                <fullName>Audited</fullName>
                <isActive>false</isActive>
                <label>Audited</label>
            </value>
            <value>
                <fullName>Certified</fullName>
                <isActive>false</isActive>
                <label>Certified</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
                <isActive>false</isActive>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Not Confirmed</fullName>
                <isActive>false</isActive>
                <label>Not Confirmed</label>
            </value>
            <value>
                <fullName>Reported Complete</fullName>
                <isActive>false</isActive>
                <label>Reported Complete</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Store_Closed__c.field-meta.xml
<CustomField>
    <fullName>Store_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Maps to MRI:TRADEOVER</description>
    <inlineHelpText>Select to indicate the store was closed on the trading date.</inlineHelpText>
    <label>Store Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Total_NET_SALES__c.field-meta.xml
<CustomField>
    <fullName>Total_NET_SALES__c</fullName>
    <inlineHelpText>This is the total sales for the day including all types of sales (e.g. Special Curated Selection Sales, Current Season Bestsellers Sales)</inlineHelpText>
    <label>Total NET SALES</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Trading_Date__c.field-meta.xml
<CustomField>
    <fullName>Trading_Date__c</fullName>
    <description>maps to MRI: TRADEDATE</description>
    <label>Trading Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Trading_Day_with_date__c.field-meta.xml
<CustomField>
    <fullName>Trading_Day_with_date__c</fullName>
    <formula>TEXT(YEAR(Trading_Date__c)) &amp;  &quot;-&quot; &amp; LPAD(TEXT(MONTH(Trading_Date__c)),2,&quot;0&quot;) &amp; &quot;-&quot; &amp; LPAD(TEXT(DAY(Trading_Date__c)),2,&quot;0&quot;) &amp; &quot; (&quot; &amp;
CASE( MOD(  Trading_Date__c - DATE(1900, 1, 7), 7), 0, $Label.DoW_Sunday , 1, $Label.DoW_Monday, 2, $Label.DoW_Tuesday, 3,
$Label.DoW_Wednesday, 4, $Label.DoW_Thursday, 5, $Label.DoW_Friday, 6, $Label.DoW_Saturday,&quot;Error&quot;) 

&amp; &quot;)&quot;</formula>
    <label>Trading Day</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Variance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Variance_Amount__c</fullName>
    <formula>IF(Store_Closed__c = FALSE, Certified_Amount__c - Brand_Reported_Amount__c, Brand_Reported_Amount__c*-1)</formula>
    <label>Variance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/Daily_Sales_Certification_Batch__c.object-meta.xml
<CustomObject>
    <description>Brand Portal object that will save all records related to the certifications</description>
    <label>Daily Sales Certification Batch</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Sales Certification Batches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_End_Date__c</fullName>
    <inlineHelpText>The end date for this Certification Batch</inlineHelpText>
    <label>Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <inlineHelpText>The start date for this Certification Batch</inlineHelpText>
    <label>Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status of this Certification Batch</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Being Prepared</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Batch Complete</fullName>
            </value>
            <value>
                <fullName>Re-opened</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Total_Brand_Reported_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Brand_Reported_Amount__c</fullName>
    <inlineHelpText>The total brand reported amount for this Certification Batch</inlineHelpText>
    <label>Total Brand Reported Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Total_Certified_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Certified_Amount__c</fullName>
    <inlineHelpText>The total certified amount for this Certification Batch</inlineHelpText>
    <label>Total Certified Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Total_Variance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Variance_Amount__c</fullName>
    <formula>Total_Certified_Amount__c - Total_Brand_Reported_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The variance amount between the total brand reported amount and the total certified amount for the Certification Batch</inlineHelpText>
    <label>Total Variance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deal Pending</fullName>
            </value>
            <value>
                <fullName>Trading</fullName>
            </value>
            <value>
                <fullName>in Refit</fullName>
            </value>
            <value>
                <fullName>Exited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BP_Certification_SCert_Controller.cls
public with sharing class BP_Certification_SCert_Controller {
    
    @AuraEnabled
    public static List<Daily_Sale__c> getDalySales(Id certId, String sortField, boolean isAsc){
        
        String sSoql = 'SELECT Id, Trading_Date__c, Trading_Day_with_date__c, Total_NET_SALES__c, NET_Value_of_Discounts__c, Store_Closed__c, Brand_Reported_Amount__c, Certified_Amount_NetTotal_Input__c, ';
        sSoql += 'Certified_Amount_Discount_Input__c, Certified_Amount__c, Variance_Amount__c, Certification_Comment__c, MRI_Suite_Id__c ';
        
        sSoql += 'FROM Daily_Sale__c ';
        sSoql += 'WHERE Certification_Batch__c =: certId ';
        
        if(sortField != null){
            if(sortField == 'Variance_Amount__c'){
                sSoql += 'ORDER BY Auxiliar_Variance_Amount__c';
                if (isAsc) {
                    sSoql += ' ASC';
                } else {
                    sSoql += ' DESC';
                }
            } else {
                sSoql += 'ORDER BY ' + sortField;        
                if (isAsc) {
                    sSoql += ' ASC';
                } else {
                    sSoql += ' DESC';
                }
            }
        }
        
        sSoql += ' NULLS LAST';
        
        system.debug('The query is' + sSoql);
        
        List<Daily_Sale__c> allRelatedDailySales = Database.query(sSoql);
        system.debug(allRelatedDailySales);
        return allRelatedDailySales;
    }
    
    @AuraEnabled
    public static Daily_Sales_Certification_Batch__c getCertification(Id certId){
        
        Daily_Sales_Certification_Batch__c theCert = [SELECT Name, Status__c, Total_Brand_Reported_Amount__c, Total_Certified_Amount__c, Total_Variance_Amount__c FROM Daily_Sales_Certification_Batch__c WHERE Id =:certId];
        
        system.debug(theCert);
        return theCert;
    }
    
    @AuraEnabled
    public static String getCertificationName(Id certId){
        
        Daily_Sales_Certification_Batch__c certName = [SELECT Id, Name FROM Daily_Sales_Certification_Batch__c WHERE Id = :certId];
        
        system.debug(certName.Name);
        return certName.Name;
    }
    
    @AuraEnabled
    public static String getCertificationRG(Id certId){
        
        Daily_Sales_Certification_Batch__c certRange = [SELECT Id, Period_Start_Date__c, Period_End_Date__c FROM Daily_Sales_Certification_Batch__c WHERE Id = :certId];
        
        system.debug(certRange.Period_Start_Date__c.format() + ' - ' + certRange.Period_End_Date__c.format());
        return certRange.Period_Start_Date__c.format() + ' - ' + certRange.Period_End_Date__c.format();
    }
    
    @AuraEnabled
    public static String getCertificationComm(Id certId){
        
        Daily_Sales_Certification_Batch__c certComment = [SELECT Id, Overall_Comment__c FROM Daily_Sales_Certification_Batch__c WHERE Id = :certId];
        
        system.debug(certComment.Overall_Comment__c);
        return certComment.Overall_Comment__c;
    }
    
    @AuraEnabled
    public static String getCurrenCode(Id certId){
        
        Daily_Sales_Certification_Batch__c cerrCurrency = [SELECT Id, CurrencyIsoCode FROM Daily_Sales_Certification_Batch__c WHERE Id = :certId];
        
        system.debug(cerrCurrency.CurrencyIsoCode);
        return cerrCurrency.CurrencyIsoCode;
    }
    
    @AuraEnabled
    public static void submitCertification(Id certId, String overallComment, Boolean isToSubmit){
        
        List<Daily_Sale__c> allUpdatedDS = new List<Daily_Sale__c>();
        List<Daily_Sale__c> allDS = [SELECT Id, Status__c, Certified_Amount__c, Store_Closed__c
                                     FROM Daily_Sale__c
                                     WHERE Certification_Batch__c = :certId]; 
        
        //Certified amount cannot be blank unless store close is true. This works together with Process builder "Set Brand Reported Amount"
        for(Daily_Sale__c ds : allDS){
            if((ds.Certified_Amount__c == null ) && (ds.Store_Closed__c == false)){
                throw new AuraHandledException ('Certified Amount must not be empty');                
            }                   
        }
        
        Daily_Sales_Certification_Batch__c certToSubmit = [SELECT Id, Variance_percentage_out_of_limits__c, Overall_Comment__c, Status__c, BP_Validation_Context_Override__c, Brand_Must_Edit_Before_Submission__c
                                                           FROM Daily_Sales_Certification_Batch__c
                                                           WHERE Id = :certId];
        
        String userFirstName = UserInfo.getFirstName();
        String userLastName = UserInfo.getLastName();
        
        if (certToSubmit.Brand_Must_Edit_Before_Submission__c == true && certToSubmit.Overall_Comment__c == overallComment){
            throw new AuraHandledException ('Please edit a field');
            
        } else if((certToSubmit.Variance_percentage_out_of_limits__c == true && (certToSubmit.Overall_Comment__c == null || String.isBlank(certToSubmit.Overall_Comment__c))) 
                  && (certToSubmit.Variance_percentage_out_of_limits__c == true && (overallComment == null || String.isBlank(overallComment)))){
                      throw new AuraHandledException ('Please add a Comment to the Certification');
                  } else {
                      if(isToSubmit == true){
                          certToSubmit.BP_Validation_Context_Override__c = true;
                          
                          try{
                              update certToSubmit;
                          } catch (Exception e){
                              throw new AuraHandledException ('Error on Submit Update');
                          }
                          
                          certToSubmit.Overall_Comment__c = overallComment;
                          certToSubmit.Certified_Date_Time__c = system.now();
                          certToSubmit.Certified_by__c = userFirstName + ' ' + userLastName;
                          certToSubmit.Status__c = 'Pending Approval';
                          for(Daily_Sale__c ds : allDS){
                              ds.Status__c = 'Certified Pending';
                              allUpdatedDS.add(ds);
                          }
                          try{
                              update allUpdatedDS;
                              
                              certToSubmit.BP_Validation_Context_Override__c = false;
                              update certToSubmit;
                              
                              sendEmailToVRFinance(certId);
                              
                          } catch(Exception e){
                              system.debug('Error: ' + e);
                              throw new AuraHandledException ('Error on Submit Update');
                          }
                      }
                  }
    }
    
    @AuraEnabled
    public static List <Daily_Sale__c> saveDaily(List<Daily_Sale__c> lstDaily, Id certId, String overallComment){
        
        Daily_Sales_Certification_Batch__c certValidOverride = [SELECT Id, BP_Validation_Context_Override__c, Brand_Must_Edit_Before_Submission__c, Status__c, Overall_Comment__c
                                                                FROM Daily_Sales_Certification_Batch__c
                                                                WHERE Id = :certId];
        
        system.debug(certValidOverride);
        
        try{
            
            certValidOverride.BP_Validation_Context_Override__c = true;
            if(certValidOverride.Status__c != 'Being Prepared'){
                certValidOverride.Status__c = 'Being Prepared';
            }
            certValidOverride.Overall_Comment__c = overallComment;
            
            if(certValidOverride.Brand_Must_Edit_Before_Submission__c == true){
                certValidOverride.Brand_Must_Edit_Before_Submission__c = false;
            }
            
            update certValidOverride;
            
            update lstDaily;
            
            certValidOverride.BP_Validation_Context_Override__c = false;
            update certValidOverride;
            
            return lstDaily;
            
        } catch(Exception e){
            String error = '' + e;
            Integer start = error.indexOf(':');
            Integer ennd = error.indexOf(',');
            
            if(ennd < 0){
                ennd = error.length();
            }
            if(start < 0){
                start = 0;
            }
            
            system.debug('Error: ' + error + ' e' + e + ' s '+start + ' e ' + ennd);
            throw new AuraHandledException ( error.substring(start, ennd) );
        }
    }
    
    @AuraEnabled
    public static void sendEmailToVRFinance(Id certId){
        
        Daily_Sales_Certification_Batch__c certToSubmit = [SELECT Id, Name, Village_Presence__r.Village__c, Village_Presence__r.Brand__c, Certified_by__c, Period_Start_Date__c, Period_End_Date__c
                                                           FROM Daily_Sales_Certification_Batch__c
                                                           WHERE Id = :certId];
        Village__c theDSCBVillage = [SELECT Name, VR_Finance_Email__c FROM Village__c WHERE Id = :certToSubmit.Village_Presence__r.Village__c];
        if(theDSCBVillage.VR_Finance_Email__c != null){
            Account brandName = [SELECT Name FROM Account WHERE Id = :certToSubmit.Village_Presence__r.Brand__c];
            
            EmailTemplate emailToVR = [SELECT Id, Name, HtmlValue, Subject FROM EmailTemplate WHERE Name = 'Submit Certification Template'];
            
            String pageURL = System.URL.getOrgDomainUrl().toExternalForm() + '/apex/DSCBDashboardFinance?id=' + certToSubmit.Id;
            
            String htmlBody;
            String subject;
            Id tempId;
            
            htmlBody = emailToVR.HtmlValue;
            subject = emailToVR.Subject;
            tempId = emailToVR.Id;
            subject = subject.replace('certificationBatchName', certToSubmit.Name);
            htmlBody = htmlBody.replace('website_here', pageURL);
            htmlBody = htmlBody.replace('certificationPeriodFrom', certToSubmit.Period_Start_Date__c.format());
            htmlBody = htmlBody.replace('certificationPeriodTo', certToSubmit.Period_End_Date__c.format());
            htmlBody = htmlBody.replace('certificationBatchName', certToSubmit.Name);
            
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            message.setSubject(subject);
            message.setHtmlBody(htmlBody);
            message.setTemplateId(tempId);
            message.setSaveAsActivity(false);
            message.setUseSignature(false);
            message.toAddresses = new String[] {theDSCBVillage.VR_Finance_Email__c};
                
            Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
            Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
            
            if (results[0].success) {
                System.debug('The email was sent successfully.');
            } else {
                logFile__c log = new logFile__c();
                log.Body__c = 'The certification submit email failed to send on class BP_Certification_SCert_Controller: ' + results[0].errors[0].message + ' for Village: ' + theDSCBVillage.Name;
                log.Type__c = 'Error on send email after certification submit';
                insert log;
            }
        }    
    }
}