force-app/main/default/objects/Daily_Sale__c/Daily_Sale__c.object-meta.xml
<CustomObject>
    <label>Daily Sale</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>Daily Sale Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Sale__c/fields/Certification_Batch__c.field-meta.xml
<CustomField>
    <fullName>Certification_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certification Batch</label>
    <referenceTo>Daily_Sales_Certification_Batch__c</referenceTo>
    <relationshipLabel>Daily Sales</relationshipLabel>
    <relationshipName>Daily_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Certified_Amount__c.field-meta.xml
<CustomField>
    <fullName>Certified_Amount__c</fullName>
    <description>Maps to MRI: CERAMOUNT</description>
    <inlineHelpText>The total Certified Sales Amount for this date that is submitted by the Brand Head Office.  Once Approved by VR Finance this will integrate across to MRI.</inlineHelpText>
    <label>Certified Amount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Certified_Amount_Discount__c.field-meta.xml
<CustomField>
    <fullName>Certified_Amount_Discount__c</fullName>
    <description>This is the field that should be integrated with MRI. The main goal is to avoid that this formula field never is blank. However it is utilized on the calculation of Certified Amount.</description>
    <formula>IF(ISBLANK(Certified_Amount_Discount_Input__c),IF(NOT(ISBLANK(NET_Value_of_Discounts__c)),NET_Value_of_Discounts__c,0),Certified_Amount_Discount_Input__c)</formula>
    <label>Certified Amount Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Certified_Amount_Discount_Input__c.field-meta.xml
<CustomField>
    <fullName>Certified_Amount_Discount_Input__c</fullName>
    <description>This field appear on the Brand Portal front-end view (Certification table). It will be editable there and do not integrate with MRI.</description>
    <inlineHelpText>The total Certified Discount Amount for this date that is submitted by the Brand Head Office.  Once Approved by VR Finance this will integrate across to MRI.</inlineHelpText>
    <label>Certified Amount Discount Input</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Certified_Amount_NetTotal__c.field-meta.xml
<CustomField>
    <fullName>Certified_Amount_NetTotal__c</fullName>
    <description>This is the field that should be integrated with MRI. The main goal is to avoid that this formula field never is blank. However it is utilized on the calculation of Certified Amount.</description>
    <formula>IF(ISBLANK(Certified_Amount_NetTotal_Input__c),IF(NOT(ISBLANK(Total_NET_SALES__c)),Total_NET_SALES__c ,0),Certified_Amount_NetTotal_Input__c)</formula>
    <label>Certified Amount NetTotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Certified_Amount_NetTotal_Input__c.field-meta.xml
<CustomField>
    <fullName>Certified_Amount_NetTotal_Input__c</fullName>
    <description>This field appear on the Brand Portal front-end view (Certification table). It will be editable there and do not integrate with MRI.</description>
    <inlineHelpText>The total Certified Net Sales Amount for this date that is submitted by the Brand Head Office</inlineHelpText>
    <label>Certified Amount NetTotal Input</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/MRI_Suite_Id__c.field-meta.xml
<CustomField>
    <fullName>MRI_Suite_Id__c</fullName>
    <label>Unit</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_End_Date__c</fullName>
    <description>MRI: Daily Sales Certification Batch Start Period</description>
    <formula>Certification_Batch__r.Period_End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CertBatchEndDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <description>MRI: Daily Sales Certification Batch Start Period</description>
    <formula>Certification_Batch__r.Period_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CertBatchStartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Store_Closed__c.field-meta.xml
<CustomField>
    <fullName>Store_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Maps to MRI:TRADEOVER</description>
    <inlineHelpText>Select to indicate the store was closed on the trading date.</inlineHelpText>
    <label>Store Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Trading_Date__c.field-meta.xml
<CustomField>
    <fullName>Trading_Date__c</fullName>
    <description>maps to MRI: TRADEDATE</description>
    <label>Trading Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Trading_Day_with_date__c.field-meta.xml
<CustomField>
    <fullName>Trading_Day_with_date__c</fullName>
    <formula>TEXT(YEAR(Trading_Date__c)) &amp;  &quot;-&quot; &amp; LPAD(TEXT(MONTH(Trading_Date__c)),2,&quot;0&quot;) &amp; &quot;-&quot; &amp; LPAD(TEXT(DAY(Trading_Date__c)),2,&quot;0&quot;) &amp; &quot; (&quot; &amp;
CASE( MOD(  Trading_Date__c - DATE(1900, 1, 7), 7), 0, $Label.DoW_Sunday , 1, $Label.DoW_Monday, 2, $Label.DoW_Tuesday, 3,
$Label.DoW_Wednesday, 4, $Label.DoW_Thursday, 5, $Label.DoW_Friday, 6, $Label.DoW_Saturday,&quot;Error&quot;) 

&amp; &quot;)&quot;</formula>
    <label>Trading Day</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <formula>Store__r.Village__r.Village_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Village Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/Daily_Sales_Certification_Batch__c.object-meta.xml
<CustomObject>
    <description>Brand Portal object that will save all records related to the certifications</description>
    <label>Daily Sales Certification Batch</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Sales Certification Batches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Certified_by__c.field-meta.xml
<CustomField>
    <fullName>Certified_by__c</fullName>
    <inlineHelpText>The name of the Brand Head Office user that submitted the Certification Batch</inlineHelpText>
    <label>Certified by</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Certified_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Certified_Date_Time__c</fullName>
    <inlineHelpText>The date and time when the Certification Batch was submitted by the Brand Head Office</inlineHelpText>
    <label>Certified Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_End_Date__c</fullName>
    <inlineHelpText>The end date for this Certification Batch</inlineHelpText>
    <label>Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <inlineHelpText>The start date for this Certification Batch</inlineHelpText>
    <label>Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Total_Certified_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Certified_Amount__c</fullName>
    <inlineHelpText>The total certified amount for this Certification Batch</inlineHelpText>
    <label>Total Certified Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Village Presence</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertS_Brand_Turnover_Cert_Decl_Statement__c.field-meta.xml
<CustomField>
    <fullName>CertS_Brand_Turnover_Cert_Decl_Statement__c</fullName>
    <description>The declaration statement that is displayed on the Sales Certification PDF Report for this village</description>
    <inlineHelpText>The declaration statement that is displayed on the Sales Certification PDF Report for this village</inlineHelpText>
    <label>CertS Brand Turnover Cert Decl Statement</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Integration_Language_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Language_Name__c</fullName>
    <description>Default language for the village used by integration layer when language has not been specified on guest creation</description>
    <inlineHelpText>Default language for the village used by integration layer when language has not been specified on guest creation</inlineHelpText>
    <label>Integration Language Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Integration_Village_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Village_Name__c</fullName>
    <description>Name used by Microservice API&apos;s to identify village.</description>
    <inlineHelpText>Name used by Microservice API&apos;s to identify village.</inlineHelpText>
    <label>Integration Village Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Village Presence records must be linked to Brand accounts. Please ensure you are not linking the Deal/Village Presence to a Group</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/BP_PDF_Render_Controller.cls
public class BP_PDF_Render_Controller {

    public Id recordId { get; set; }
    public List <Daily_Sale__c> theCert {get; set;}

    public Daily_Sales_Certification_Batch__c dscbFields {get; set;}
    public Account brandAccount {get; set;} 
    
    public Decimal spaceTotal {get; set;} 
    public Boolean renderValue {get; set;}

    public Decimal totalNet {get; set;} 
    public Decimal totalVip {get; set;} 
    public String startDate {get; set;}
    public String finalDate {get; set;} 
    public String villagePresenceName {get; set;} 
    public String certifiedBy {get; set;}
    public String brandName {get; set;}
    public String currencyCode {get; set;}
    public String currencySeparator {get; set;}
    
    public Date certifiedDate {get; set;}
    public String certifiedDateWithoutTime {get;set;}
    
    
    public String villageName {get; set;}
    public String villageCode {get; set;}
    public String villageLanguage {get; set;}
    public String printLanguage {get; set;}
    public Village__c theVillage {get; set;} 
    public String logo {get; set;} 
    
    public BP_PDF_Render_Controller() {
    
        // get record id from query parameters        
        recordId = ApexPages.currentPage().getParameters().get('id');        
        theCert = [SELECT Id, Trading_Day_with_date__c, Trading_Date__c, MRI_Suite_Id__c, Store_Closed__c, Certified_Amount_NetTotal__c, Certified_Amount_Discount__c,
                   Certified_Amount_NetTotal_Input__c, Certified_Amount_Discount_Input__c, Certified_Amount__c
                   FROM Daily_Sale__c
                   WHERE Certification_Batch__c = :recordId 
                   ORDER BY Trading_Day_with_date__c ASC];
        
        dscbFields = [SELECT Id, Total_Certified_Amount__c, Period_Start_Date__c, Period_End_Date__c, Village_Presence__r.Name, Certified_by__c, Village_Presence__r.Brand__c,
                      Certified_Date_Time__c, Village_Presence__r.Village__c, CurrencyIsoCode
                      FROM Daily_Sales_Certification_Batch__c
                      WHERE Id = :recordId];
        
        brandAccount = [SELECT Name FROM Account WHERE Id = :dscbFields.Village_Presence__r.Brand__c];
        
        theVillage = [SELECT Id, Integration_Village_Name__c, Integration_Language_Name__c, CertS_Brand_Turnover_Cert_Decl_Statement__c, Village_Code__c
                   FROM Village__c
                   WHERE Id = : dscbFields.Village_Presence__r.Village__c]; 
         
        currencyCode = String.valueOf(dscbFields.CurrencyIsoCode);
        
        villageName = theVillage.Integration_Village_Name__c;
        villageCode = theVillage.Village_Code__c;
        villageLanguage = theVillage.Integration_Language_Name__c;
        system.debug(villageLanguage);
        
        switch on villageLanguage{
            
            when 'English' {
                printLanguage = 'en_US';
            }
            when 'French' {
                printLanguage = 'fr';
            }
            when 'Spanish'{
                printLanguage = 'es';
            }
            when 'German'{
                printLanguage = 'de'; 
            }
            when 'Italian'{
                printLanguage = 'it';
            }
            when else{
                printLanguage = 'en_US';
            }                          
        }
        
        if (villageCode == 'MV'){
            printLanguage = 'en_US'; 
        }
        
        if (villageCode == 'BV' || villageCode == 'KV'){
            currencySeparator = 'CT'; 
        }else{
            currencySeparator = 'DT';            
        }  

        logo = theVillage.Village_Code__c + '.jpg';
        system.debug('Logo de agora '+logo);
        
        brandName = brandAccount.Name;
        certifiedBy = dscbFields.Certified_by__c;
                
        Datetime certifiedDateTime = dscbFields.Certified_Date_Time__c;
        certifiedDate = date.newInstance(certifiedDateTime.year(), certifiedDateTime.month(), certifiedDateTime.day());
        certifiedDateWithoutTime = certifiedDate.format();
        villagePresenceName = dscbFields.Village_Presence__r.Name;
                
        startDate = dscbFields.Period_Start_Date__c.format();
        finalDate = dscbFields.Period_End_Date__c.format();
       
        totalNet = 0;
        totalVip = 0;
        renderValue = false;        
               
        for(Daily_Sale__c ds : theCert ){
            if (ds.Store_Closed__c == false ){
                totalNet = totalNet + ds.Certified_Amount_NetTotal__c;
                totalVip = totalVip + ds.Certified_Amount_Discount__c;                
            }else{
                renderValue = true;
            }
        }
       
       spaceTotal = theCert.size();
       system.debug(spaceTotal);

       //setup a default file name
       string fileName = 'PDF Certificate'+'.pdf';
       Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename=' + fileName );

    }
    
}