force-app/main/default/objects/Daily_Sale__c/Daily_Sale__c.object-meta.xml
<CustomObject>
    <label>Daily Sale</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>Daily Sale Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Sale__c/fields/Current_Season_Bestsellers_Active__c.field-meta.xml
<CustomField>
    <fullName>Current_Season_Bestsellers_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When this check box is selected the Daily Sales record will include CSB Sales and Unit data fields.  This is full price product from current season collection.</inlineHelpText>
    <label>Current Season Bestsellers Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/F_B_Covers_Active__c.field-meta.xml
<CustomField>
    <fullName>F_B_Covers_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When F&amp;B Covers Active is selected the Daily Sales record will include the covers data field and will not include the tax free data fields.</inlineHelpText>
    <label>F &amp; B Covers Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/MRI_Unit_Id__c.field-meta.xml
<CustomField>
    <fullName>MRI_Unit_Id__c</fullName>
    <description>Concatenation of the Phase Id and Suite Id returned by MRI during the Daily Sale record creation</description>
    <formula>MRI_Phase_Id__c  &amp;  MRI_Suite_Id__c</formula>
    <inlineHelpText>Concatenation of the Phase Id and Suite Id returned by MRI during the Daily Sale record creation</inlineHelpText>
    <label>MRI_Unit_Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Special_Curated_Selection_Active__c.field-meta.xml
<CustomField>
    <fullName>Special_Curated_Selection_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When this check box is selected the Daily Sales record will include SCS Sales and Unit data fields.  This is product recently discontinued at full price but not yet available at off-price. Product for TBVSC at a 10% discount off RRP.</inlineHelpText>
    <label>Special Curated Selection Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <formula>Store__r.Village__r.Village_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Village Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/recordTypes/Current.recordType-meta.xml
<RecordType>
    <fullName>Current</fullName>
    <active>true</active>
    <description>Record Type replacing EDITABLE</description>
    <label>Current</label>
</RecordType>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the detail of all units in VR Villages</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/MRI_Unit_ID__c.field-meta.xml
<CustomField>
    <fullName>MRI_Unit_ID__c</fullName>
    <description>Populated by a workflow 
Phase_ID__c &amp; Suite_ID__c
which makes up the uniqueness of MRI, and is a unique field</description>
    <externalId>true</externalId>
    <inlineHelpText>Set automatically</inlineHelpText>
    <label>MRI Unit ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>...</description>
    <inlineHelpText>Select the Village where this unit lives</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>custom currency field</description>
    <inlineHelpText>Enter the currency to be used for all financial leasing values to be used in this village (custom currency)</inlineHelpText>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>RMB</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/fields/Default_Daily_Sales_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Default_Daily_Sales_Record_Type__c</fullName>
    <description>Select the default Daily Sales record type</description>
    <inlineHelpText>Select the default Daily Sales record type</inlineHelpText>
    <label>Default Daily Sales Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Daily_Sale_Record_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village_Closed_Period__c/Village_Closed_Period__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold periods when the village is closed</description>
    <label>Village Closed Period</label>
    <nameField>
        <label>Village Closed Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Closed Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Closed_Period__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This box will automatocally be checked if the closed period starts in the current year</inlineHelpText>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Closed_Period__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <inlineHelpText>The village</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Closed Periods</relationshipLabel>
    <relationshipName>Village_Closed_Periods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Village Presence records must be linked to Brand accounts. Please ensure you are not linking the Deal/Village Presence to a Group</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Brand_Event_Active__c.field-meta.xml
<CustomField>
    <fullName>Brand_Event_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Brand events of less than two months duration, in a unit or Village private space.  Sales recorded as a subset of an existing Village Presence Lease. Events by invitation only and/or open to the public, either physical or virtual.</inlineHelpText>
    <label>Is Brand Event Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/CertSales_Active__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When CertSales Active is selected then when the next Daily Sales record is created a Sales Certification Batch will also be created</inlineHelpText>
    <label>CertSales Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Current_Season_Bestsellers_Active__c.field-meta.xml
<CustomField>
    <fullName>Current_Season_Bestsellers_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When this check box is selected the Daily Sales record will include CSB Sales and Unit data fields.  This is full price product from current season collection.</inlineHelpText>
    <label>Current Season Bestsellers Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Daily_Sale_Active_Date__c.field-meta.xml
<CustomField>
    <fullName>Daily_Sale_Active_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Specify a future date if the store should not be made active for Daily Sales immediately. Daily Sale records will be created from midday (GMT) of the date specified. If value is left blank, it is assumed the store is immediately active.</description>
    <inlineHelpText>Specify a future date if the store should not be made active for Daily Sales immediately. Daily Sale records will be created from midday (GMT) of the date specified. If value is left blank, it is assumed the store is immediately active.</inlineHelpText>
    <label>Daily Sale Active Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Daily_Sale_Record_Type_Override__c.field-meta.xml
<CustomField>
    <fullName>Daily_Sale_Record_Type_Override__c</fullName>
    <label>Daily Sale Record Type Override</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Daily_Sale_Record_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/F_B_Covers_Active__c.field-meta.xml
<CustomField>
    <fullName>F_B_Covers_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When F&amp;B Covers Active is selected the Daily Sales record will include the covers data field and will not include the tax free data fields.</inlineHelpText>
    <label>F &amp; B Covers Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Pop_Up_Boutique_Active__c.field-meta.xml
<CustomField>
    <fullName>Pop_Up_Boutique_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Short-term boutiques of two to twenty-four months’ duration.  Sales recorded as a subset of an existing Village Presence Lease.</inlineHelpText>
    <label>Is Pop-Up Boutique Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Special_Curated_Selection_Active__c.field-meta.xml
<CustomField>
    <fullName>Special_Curated_Selection_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When this check box is selected the Daily Sales record will include SCS Sales and Unit data fields.  This is product recently discontinued at full price but not yet available at off-price. Product for TBVSC at a 10% discount off RRP.</inlineHelpText>
    <label>Special Curated Selection Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/globalValueSets/Daily_Sale_Record_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Net</fullName>
        <default>true</default>
        <label>Net</label>
    </customValue>
    <customValue>
        <fullName>F &amp; B Covers</fullName>
    </customValue>
    <customValue>
        <fullName>Full Price</fullName>
        <label>Current Season Bestsellers</label>
    </customValue>
    <customValue>
        <fullName>Discretionary Discount</fullName>
        <label>Special Curated Selection</label>
    </customValue>
    <customValue>
        <fullName>Full Price &amp; Discretionary Discount</fullName>
        <label>Current Season Bestsellers &amp; Special Curated Selection</label>
    </customValue>
    <customValue>
        <fullName>Gross</fullName>
        <isActive>false</isActive>
        <label>Gross</label>
    </customValue>
    <description>....</description>
    <masterLabel>Daily Sale Record Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DailySalesBatchProcessor.cls
global class DailySalesBatchProcessor implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    private static final id defaultRecordTypeID = Schema.SObjectType.Daily_Sale__c.RecordTypeInfosByDeveloperName.get('Current').RecordTypeId;
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {     
        
        Datetime dt = System.now(); 
        string theDay = dt.format('EEEE'); 
        System.debug('@@@  the day is .. ' +  dt.format('EEEE'));
        
        string query = 'select Id, Name, Unit__c, Village__c, Brand__c, Daily_Sale_Record_Type_Override__c,Brand_Event_Active__c, Pop_Up_Boutique_Active__c, ';
        query += ' Village__r.Village_Code__c, Village__r.Currency__c, Village__r.CurrencyISOCode, Village__r.Default_Daily_Sales_Record_Type__c, ';
        query += ' Unit__r.Name, Unit__r.MRI_Unit_Id__c,';
        query += ' Daily_Sale_Active_Date__c,';
        // ----- START LIS DEV Team @Hugo
        query += ' CertSales_Active__c, Village__r.CertSales_Report_Sales_Grace_Period_Days__c,';
        // ----- END LIS DEV Team @Hugo
        query += ' F_B_Covers_Active__c, Current_Season_Bestsellers_Active__c, Special_Curated_Selection_Active__c, Brand_Remote_Sales_Active__c, Brand_Private_Appointment_Active__c ';
        query += ' from Village_Presence__c';
        query += ' where Daily_Sales_Active__c = true and Status__c = ' + '\'Trading\'';
        query += ' and (Daily_Sale_Active_Date__c = null or Daily_Sale_Active_Date__c <= TODAY)';
        query += ' order by Village__c';
        System.debug('@@@  query is .. ' +  query);            
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC,List<Sobject> scope)
    {
        
        Map <String, String> valueToLabelMap = new Map <String, String> ();
        for (PicklistEntry pEntry : Village_Presence__c.Daily_Sale_Record_Type_Override__c.getDescribe().getPicklistValues()) {
            valueToLabelMap.put(pEntry.getValue(), pEntry.getLabel());
        }
        
        list<Daily_Sale__c> dsList = new list<Daily_Sale__c>();
        integer currentYear = system.today().year();
        
        // retrieve closed periods for each village
        list<Village_Closed_Period__c> villageCloseDatesList = [select From__c, To__c, Village_Days_Closed__c, village__c from Village_Closed_Period__c 
                                                                where Current_Year__c = :currentYear
                                                                and (from__c >= :system.today() or To__c >= :system.today())
                                                                and active__c = true  
                                                                order by From__c ];
        // create map of village closed periods
        map<Id, list<date>> villageClosedMap = new map<Id, list<date>>();
        for (Village_Closed_Period__c vcp :villageCloseDatesList){
            list<date> closedDates = villageClosedMap.get(vcp.village__c);
            if (closedDates == null)
                closedDates = new list<date>();
            integer daysClosed = vcp.from__c.daysBetween(vcp.To__c); //retrieve number of days covered by closed period
            while(daysClosed >= 0){ 
                Date dt = vcp.from__c.addDays(daysClosed); 
                closedDates.add(dt); // add each closed date to a list
                daysClosed--;
            }
            villageClosedMap.put(vcp.Village__c, closedDates);
            
        }
        
        // ----- START LIS DEV Team @Hugo
        List<Daily_Sales_Certification_Batch__c> allCertifications = [SELECT Id, Period_Start_Date__c, Period_End_Date__c, Village_Presence__c FROM Daily_Sales_Certification_Batch__c
                                                    WHERE Period_Start_Date__c <= :system.today()
                                                    AND Period_End_Date__c >= :system.today()];

        Map<String, Id> mapCertifications = new Map<String, Id>();
        Map<String, Date> mapCertDate = new Map<String, Date>();
        for(Daily_Sales_Certification_Batch__c theCertification : allCertifications){
            mapCertifications.put(theCertification.Village_Presence__c, theCertification.Id);
            mapCertDate.put(theCertification.Village_Presence__c, theCertification.Period_End_Date__c);
        }
        // ----- END LIS DEV Team @Hugo
        
        if (!scope.isEmpty()){
            
            map<string, string> closedVillages = new map<string, string>();
            
            for (Sobject vp :scope){
                string vpId = string.valueOf(vp.get('Id'));
                string brandId = string.valueOf(vp.get('Brand__c'));
                //string vpRecType = valueToLabelMap.get(string.valueOf(vp.get('Daily_Sale_Record_Type_Override__c')));
                String FBCoversActive = string.valueOf(vp.get('F_B_Covers_Active__c'));
                String CurrentSeasonBestsellersActive = string.valueOf(vp.get('Current_Season_Bestsellers_Active__c'));
                String SpecialCuratedSelectionActive = string.valueOf(vp.get('Special_Curated_Selection_Active__c'));
                String BrandRemoteSalesActive = string.valueOf(vp.get('Brand_Remote_Sales_Active__c'));
                String BrandPrivateAppointmentActive = string.valueOf(vp.get('Brand_Private_Appointment_Active__c'));
                string currencyCode = string.valueOf(vp.getSobject('Village__r').get('Currency__c'));
                string villageCode = string.valueOf(vp.getSobject('Village__r').get('Village_Code__c'));
                string villageId = string.valueOf(vp.getSobject('Village__r').get('Id'));
                string villageRecType = string.valueOf(vp.getSobject('Village__r').get('Default_Daily_Sales_Record_Type__c'));
                // Start LIS DEV Team @Hugo
                String PopUpBoutiqueActive = string.valueOf(vp.get('Pop_Up_Boutique_Active__c'));
                String BrandEventActive = string.valueOf(vp.get('Brand_Event_Active__c'));
                boolean certificationActive = Boolean.valueOf(string.valueOf(vp.get('CertSales_Active__c')));
                Id certificationId;
                if(certificationActive == true){
                    if(mapCertifications.get(vpId) != null){
                        certificationId = mapCertifications.get(vpId);
                    } else {
                        certificationId = CertificationProcessor.createCertification(vpId);
                    }
                }
                Id getCertification = certificationId;
                // End LIS DEV Team @Hugo
                
                Boolean isPopUpBoutiqueActive = False;
                IF(PopUpBoutiqueActive == 'True'){
                    isPopUpBoutiqueActive = True;
                }
                
                Boolean isBrandEventActive = False;
                 IF(BrandEventActive == 'True'){
                    isBrandEventActive = True;
                }
                
                Boolean FBCoversActiveFlag = FALSE;
                Boolean CurrentSeasonBestsellersActiveFlag = FALSE;
                Boolean SpecialCuratedSelectionActiveFlag = FALSE;
                Boolean BrandRemoteSalesActiveFlag = FALSE;
                Boolean BrandPrivateAppointmentActiveFlag = FALSE;
                System.debug('CurrentSeasonBestsellersActiveFlag: ' +  CurrentSeasonBestsellersActiveFlag);
                System.debug('SpecialCuratedSelectionActiveFlag: ' +  SpecialCuratedSelectionActiveFlag);
                if (FBCoversActive == 'true') {
                    FBCoversActiveFlag = TRUE;
                } if (CurrentSeasonBestsellersActive == 'true') {
                    CurrentSeasonBestsellersActiveFlag = TRUE;
                    System.debug('CurrentSeasonBestsellersActiveFlag: ' +  CurrentSeasonBestsellersActiveFlag);
                } if (SpecialCuratedSelectionActive == 'true') {
                    SpecialCuratedSelectionActiveFlag = TRUE;
                    System.debug('SpecialCuratedSelectionActiveFlag: ' +  SpecialCuratedSelectionActiveFlag);
                } if (BrandRemoteSalesActive == 'true') {
                    BrandRemoteSalesActiveFlag = TRUE;
                } if (BrandPrivateAppointmentActive == 'true') {
                    BrandPrivateAppointmentActiveFlag = TRUE;
                }


                /*string recType = '';
                if (string.isNotBlank(vpRecType)){
                    recType = Schema.SObjectType.Daily_Sale__c.RecordTypeInfosByName.get(vpRecType).RecordTypeId;
                } else if (string.isnotBlank(villageRecType)){
                    recType = Schema.SObjectType.Daily_Sale__c.RecordTypeInfosByName.get(villageRecType).RecordTypeId;
                } else {
                    recType = defaultRecordTypeID;
                }
                
                if (string.isBlank(recType)){
                    recType = defaultRecordTypeID;
                }*/
                
                if(test.isRunningTest()){
                    brandId = 'SF_TEST';
                }
                // check if village closed
                if (!closedVillages.containsKey(villageId)){
                    list<date> villageClosedDates = villageClosedMap.get(villageId);
                    boolean villageClosed = false;
                    if (villageClosedDates != null){
                        for (Date dt :villageClosedDates){
                            if (dt == system.today()){
                                villageClosed = true;
                                closedVillages.put(villageId, villageId);
                                break;
                            }
                        }
                    }
                    
                    // Start LIS DEV Team @Hugo - added the Certification lookup on Daily Sales (getCertification)
                    // create Daily sale record if village not closed - set currency to be the same as defined on village record
                    if (!villageClosed){
                        dsList.add (new Daily_Sale__c(Trading_Date__c = system.today(), Store__c = vpId, 
                                                      F_B_Covers_Active__c = FBCoversActiveFlag, 
                                                      Is_Pop_Up_Boutique_Active__c = isPopUpBoutiqueActive  ,
                                                      Is_Brand_Event_Active__c = isBrandEventActive,
                                                      Current_Season_Bestsellers_Active__c = CurrentSeasonBestsellersActiveFlag,
                                                      Special_Curated_Selection_Active__c = SpecialCuratedSelectionActiveFlag,
                                                      Brand_Remote_Sales_Active__c = BrandRemoteSalesActiveFlag,
                                                      Brand_Private_Appointment_Active__c = BrandPrivateAppointmentActiveFlag,
                                                      RecordTypeId = defaultRecordTypeID, CurrencyIsoCode = currencyCode,
                                                      Certification_Batch__c = getCertification));
                    }
                    // End LIS DEV Team @Hugo
                }
            }
        }
        if (!dsList.isEmpty()){
            
            try{
                
                Database.SaveResult[] resultList = Database.insert(dsList, false);
                
                for (Database.SaveResult r : resultList){  // Examine DML errors
                    if (!r.isSuccess()){  
                        for (Database.Error e : r.getErrors()){  
                            // errors here
                            StatusCode status = e.getStatusCode();
                            string errMsg = e.getMessage();
                            
                            system.debug('ERROR creating Daily Sales Record .. ' + status + ' : ' + errMsg );
                            
                        }
                    }
                    
                }
                
            } catch (exception e){
                system.debug('ERROR ...ERROR ... ERROR ' + e.getMessage() + ' : ' + e.getStackTraceString());
            }
            
            
            
        }
        
    }
    
    global void finish(Database.BatchableContext BC)
    {
        
    }
    
    
    
}