force-app/main/default/objects/Daily_Sale__c/Daily_Sale__c.object-meta.xml
<CustomObject>
    <label>Daily Sale</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>Daily Sale Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Sale__c/fields/Brand_Reported_Amount__c.field-meta.xml
<CustomField>
    <fullName>Brand_Reported_Amount__c</fullName>
    <description>This field is looks at in the INT_Reported_Amount formula field and passed through to MRI via that field if the OVERRIDE RPT AMOUNT field is NULL</description>
    <inlineHelpText>This is the Total Net Sales and the total Net Value of Discounts for the day added together.</inlineHelpText>
    <label>Brand Reported Amount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Certification_Batch__c.field-meta.xml
<CustomField>
    <fullName>Certification_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certification Batch</label>
    <referenceTo>Daily_Sales_Certification_Batch__c</referenceTo>
    <relationshipLabel>Daily Sales</relationshipLabel>
    <relationshipName>Daily_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Certified_Amount__c.field-meta.xml
<CustomField>
    <fullName>Certified_Amount__c</fullName>
    <description>Maps to MRI: CERAMOUNT</description>
    <inlineHelpText>The total Certified Sales Amount for this date that is submitted by the Brand Head Office.  Once Approved by VR Finance this will integrate across to MRI.</inlineHelpText>
    <label>Certified Amount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Certified_Amount_Discount__c.field-meta.xml
<CustomField>
    <fullName>Certified_Amount_Discount__c</fullName>
    <description>This is the field that should be integrated with MRI. The main goal is to avoid that this formula field never is blank. However it is utilized on the calculation of Certified Amount.</description>
    <formula>IF(ISBLANK(Certified_Amount_Discount_Input__c),IF(NOT(ISBLANK(NET_Value_of_Discounts__c)),NET_Value_of_Discounts__c,0),Certified_Amount_Discount_Input__c)</formula>
    <label>Certified Amount Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Certified_Amount_NetTotal__c.field-meta.xml
<CustomField>
    <fullName>Certified_Amount_NetTotal__c</fullName>
    <description>This is the field that should be integrated with MRI. The main goal is to avoid that this formula field never is blank. However it is utilized on the calculation of Certified Amount.</description>
    <formula>IF(ISBLANK(Certified_Amount_NetTotal_Input__c),IF(NOT(ISBLANK(Total_NET_SALES__c)),Total_NET_SALES__c ,0),Certified_Amount_NetTotal_Input__c)</formula>
    <label>Certified Amount NetTotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/Daily_Sales_Certification_Batch__c.object-meta.xml
<CustomObject>
    <description>Brand Portal object that will save all records related to the certifications</description>
    <label>Daily Sales Certification Batch</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Sales Certification Batches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Total_Brand_Reported_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Brand_Reported_Amount__c</fullName>
    <inlineHelpText>The total brand reported amount for this Certification Batch</inlineHelpText>
    <label>Total Brand Reported Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Total_Certified_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Certified_Amount__c</fullName>
    <inlineHelpText>The total certified amount for this Certification Batch</inlineHelpText>
    <label>Total Certified Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Total_Certified_Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Certified_Discount_Amount__c</fullName>
    <description>This field represents the total Certified Discount amount of the daily sales related to this certification batch.</description>
    <inlineHelpText>The total certified Discount Amount for the certification period</inlineHelpText>
    <label>Total Certified Discount Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Total_Certified_Net_Sales_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Certified_Net_Sales_Amount__c</fullName>
    <description>This field represents the total Certified Net Sales amount of the daily sales related to this certification batch.</description>
    <inlineHelpText>The total certified Net Sales amount for the certification period</inlineHelpText>
    <label>Total Certified Net Sales Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LogFile__c/LogFile__c.object-meta.xml
<CustomObject>
    <label>LogFile</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>LogFile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LogFiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogFile__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B2B Report Emails</fullName>
            </value>
            <value>
                <fullName>ETLWebService</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CalculationOfAmounts.cls
public class CalculationOfAmounts {

    @InvocableMethod
    public static void changesAmounts(List<Daily_Sale__c> allUpdatedDS){
        Set<Id> dsId = new Set<Id>();
        for(Daily_Sale__c ds : allUpdatedDS){
            if(ds.Certification_Batch__c != null){
                dsId.add(ds.Certification_Batch__c);
            }
        }
        
        if(!dsId.isEmpty()){
        	List<Daily_Sale__c> allDailySale = [SELECT Id, Certification_Batch__c, Brand_Reported_Amount__c, Certified_Amount__c, Certified_Amount_NetTotal__c, Certified_Amount_Discount__c FROM Daily_Sale__c WHERE Certification_Batch__c = :dsId];
            List<Daily_Sales_Certification_Batch__c> allCertification = [SELECT Id, Total_Brand_Reported_Amount__c, Total_Certified_Amount__c, Total_Certified_Net_Sales_Amount__c, Total_Certified_Discount_Amount__c FROM Daily_Sales_Certification_Batch__c WHERE Id = :dsId];
            List<Daily_Sales_Certification_Batch__c> updatedCertification = new List<Daily_Sales_Certification_Batch__c>();
            
            for(Daily_Sales_Certification_Batch__c cert : allCertification){
                cert.Total_Brand_Reported_Amount__c = 0;
                cert.Total_Certified_Amount__c = 0;
                cert.Total_Certified_Net_Sales_Amount__c = 0;
                cert.Total_Certified_Discount_Amount__c = 0;
                for(Daily_Sale__c ds : allDailySale){
                    if(cert.Id == ds.Certification_Batch__c){
                        
                        if(ds.Brand_Reported_Amount__c != null){
                            cert.Total_Brand_Reported_Amount__c = cert.Total_Brand_Reported_Amount__c + ds.Brand_Reported_Amount__c;
                        } else {
                            cert.Total_Brand_Reported_Amount__c = cert.Total_Brand_Reported_Amount__c + 0;
                        }
                        
                        if(ds.Certified_Amount__c != null){
                            cert.Total_Certified_Amount__c = cert.Total_Certified_Amount__c + ds.Certified_Amount__c;
                        } else {
                            cert.Total_Certified_Amount__c = cert.Total_Certified_Amount__c + 0;
                        }
						
						cert.Total_Certified_Net_Sales_Amount__c = cert.Total_Certified_Net_Sales_Amount__c + ds.Certified_Amount_NetTotal__c;
                        cert.Total_Certified_Discount_Amount__c = cert.Total_Certified_Discount_Amount__c + ds.Certified_Amount_Discount__c;
                    }
                }
                updatedCertification.add(cert);
            }
            try{
                update updatedCertification;
            } catch (Exception e){
                logFile__c log = new logFile__c();
                log.Body__c = 'Error on update certification in CalculationOfAmounts class. The update list: ' + updatedCertification + '. With the following mesage: ' + e.getMessage();
                log.Type__c = 'Calculation of Amounts of the certification';
                insert log;
                system.debug('Exist an error on update of CalculationOfAmounts class with the following mesage: ' + e.getMessage());
            }
        }
    }
}