force-app/main/default/objects/Daily_Sales_Status_Map__c/Daily_Sales_Status_Map__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Defines the share access for a Daily Sales record dependent on record status.</description>
    <label>Daily Sales Status Map</label>
</CustomObject>

force-app/main/default/objects/Daily_Sales_Status_Map__c/fields/Audited__c.field-meta.xml
<CustomField>
    <fullName>Audited__c</fullName>
    <description>Access level to apply when Daily Sales record has a Reported Audited status. Read or Edit.</description>
    <inlineHelpText>Access level to apply when Daily Sales record has a Reported Audited status. Read or Edit.</inlineHelpText>
    <label>Audited</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Status_Map__c/fields/Certified__c.field-meta.xml
<CustomField>
    <fullName>Certified__c</fullName>
    <description>Access level to apply when Daily Sales record has a Certified status. Read or Edit.</description>
    <inlineHelpText>Access level to apply when Daily Sales record has a Certified status. Read or Edit.</inlineHelpText>
    <label>Certified</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Status_Map__c/fields/Certified_Approved__c.field-meta.xml
<CustomField>
    <fullName>Certified_Approved__c</fullName>
    <description>Access level to apply when Daily Sales record has a Reported Audited status. Read or Edit.</description>
    <inlineHelpText>Access level to apply when Daily Sales record has a Reported Audited status. Read or Edit.</inlineHelpText>
    <label>Certified Approved</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Status_Map__c/fields/Certified_Complete__c.field-meta.xml
<CustomField>
    <fullName>Certified_Complete__c</fullName>
    <description>Access level to apply when Daily Sales record has a Reported Audited status. Read or Edit.</description>
    <inlineHelpText>Access level to apply when Daily Sales record has a Reported Audited status. Read or Edit.</inlineHelpText>
    <label>Certified Complete</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Status_Map__c/fields/Certified_Pending__c.field-meta.xml
<CustomField>
    <fullName>Certified_Pending__c</fullName>
    <description>Access level to apply when Daily Sales record has a Reported Audited status. Read or Edit.</description>
    <inlineHelpText>Access level to apply when Daily Sales record has a Reported Audited status. Read or Edit.</inlineHelpText>
    <label>Certified Pending</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Status_Map__c/fields/Certified_Re_opened__c.field-meta.xml
<CustomField>
    <fullName>Certified_Re_opened__c</fullName>
    <description>Access level to apply when Daily Sales record has a Reported Audited status. Read or Edit.</description>
    <inlineHelpText>Access level to apply when Daily Sales record has a Reported Audited status. Read or Edit.</inlineHelpText>
    <label>Certified Re-opened</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Status_Map__c/fields/Created__c.field-meta.xml
<CustomField>
    <fullName>Created__c</fullName>
    <description>Access level to apply when Daily Sales record has a &quot;created&quot; status. Read or Edit.</description>
    <inlineHelpText>Access level to apply when Daily Sales record has a created status. Read or Edit.</inlineHelpText>
    <label>Created</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Status_Map__c/fields/Reported_Complete__c.field-meta.xml
<CustomField>
    <fullName>Reported_Complete__c</fullName>
    <description>Access level to apply when Daily Sales record has a Reported Complete status. Read or Edit.</description>
    <inlineHelpText>Access level to apply when Daily Sales record has a Reported Complete status. Read or Edit.</inlineHelpText>
    <label>Reported Complete</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Status_Map__c/fields/Reported_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Reported_Confirmed__c</fullName>
    <description>Access level to apply when Daily Sales record has a Reported Confirmed status. Read or Edit.</description>
    <inlineHelpText>Access level to apply when Daily Sales record has a Reported Confirmed status. Read or Edit.</inlineHelpText>
    <label>Reported Confirmed</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Status_Map__c/fields/Reported_Incomplete__c.field-meta.xml
<CustomField>
    <fullName>Reported_Incomplete__c</fullName>
    <description>Access level to apply when Daily Sales record has a Reported Incomplete status. Read or Edit.</description>
    <inlineHelpText>Access level to apply when Daily Sales record has a Reported Incomplete status. Read or Edit.</inlineHelpText>
    <label>Reported Incomplete</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Status_Map__c/fields/TOR__c.field-meta.xml
<CustomField>
    <fullName>TOR__c</fullName>
    <description>Access level to apply when Daily Sales record has a TOR status. Read or Edit.</description>
    <inlineHelpText>Access level to apply when Daily Sales record has a TOR status. Read or Edit.</inlineHelpText>
    <label>TOR</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VR1_Configuration_Settings__c/VR1_Configuration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration settings for VR1</description>
    <label>VR1 Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/VR1_Configuration_Settings__c/fields/Default_Chatter_Roles__c.field-meta.xml
<CustomField>
    <fullName>Default_Chatter_Roles__c</fullName>
    <description>Comma separated list of role search string identifiers which should be included in logic to default chatter role memberships when a user&apos;s role is updated.</description>
    <inlineHelpText>Comma separated list of role search string identifiers which should be included in logic to default chatter role memberships when a user&apos;s role is updated.</inlineHelpText>
    <label>Default Chatter Roles</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DailySales_CustomSettings_Script_Test.cls
@isTest
public class DailySales_CustomSettings_Script_Test {
    
    static testMethod void CustomSettingsOptionsTest(){
        Daily_Sales_Status_Map__c newDSSM = Daily_Sales_Status_Map__c.getOrgDefaults();
        newDSSM.TOR__c = 'Read';
        insert newDSSM;
        
        VR1_Configuration_Settings__c newVR1CS = VR1_Configuration_Settings__c.getOrgDefaults();
        newVR1CS.Default_Chatter_Roles__c = 'Leasing,Legal,Retail,Finance';
        insert newVR1CS;
        
        Test.startTest();
        	DailySales_CustomSettings_Script.CustomSettingsOptions();
        Test.stopTest();
        
        Daily_Sales_Status_Map__c dssmR = [SELECT Id, Audited__c, Certified__c, Created__c, Reported_Complete__c, Reported_Confirmed__c, Reported_Incomplete__c,
                                           TOR__c, Certified_Approved__c, Certified_Complete__c, Certified_Pending__c, Certified_Re_opened__c
                                           FROM Daily_Sales_Status_Map__c];
        VR1_Configuration_Settings__c confSettingR = [SELECT id, Default_Chatter_Roles__c FROM VR1_Configuration_Settings__c];
        
        system.assertEquals('Read', dssmR.Certified_Approved__c);
        system.assertEquals('Edit', dssmR.TOR__c);
        system.assertEquals('Leasing,Legal,Retail', confSettingR.Default_Chatter_Roles__c);
    }
}