force-app/main/default/objects/PointsProvider__c/PointsProvider__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Third PartyCustom Settings</label>
</CustomObject>

force-app/main/default/objects/PointsProvider__c/fields/Alitalia_Partner_Code_Base__c.field-meta.xml
<CustomField>
    <fullName>Alitalia_Partner_Code_Base__c</fullName>
    <description>Partner Code for Base Points Transfer</description>
    <label>Alitalia Partner Code Base</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PointsProvider__c/fields/Alitalia_Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Alitalia_Partner_Type__c</fullName>
    <label>Alitalia Partner Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PointsProvider__c/fields/Alitalia_Points_Service_Password__c.field-meta.xml
<CustomField>
    <fullName>Alitalia_Points_Service_Password__c</fullName>
    <description>Alitalia Points Service  App User Password</description>
    <label>Alitalia Points Service Password</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PointsProvider__c/fields/Alitalia_Points_Service_User__c.field-meta.xml
<CustomField>
    <fullName>Alitalia_Points_Service_User__c</fullName>
    <description>Application Username for the Alitalia Service</description>
    <label>Alitalia Points Service User</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/tempuriOrgTest.cls
public with sharing class tempuriOrgTest {
    private static final String SOAP_HEADER_PWS='5c19ef5173889ef6019d26d619d54aa6';
    private static final String SOAP_HEADER_USER='webservice';
    
    private static String partnerUSER_ID;
    private static String partnerPASSWORD;
    
    static testMethod void testAlitaliatempuriOrg(){
        tempuriOrg.AlitaliaServiceSoap objPTServiceSoap = new tempuriOrg.AlitaliaServiceSoap();
        PointsProvider__c custPointsProvider = PointsProvider__c.getInstance();
        partnerUSER_ID = custPointsProvider.Alitalia_Points_Service_User__c;
        partnerPASSWORD = custPointsProvider.Alitalia_Points_Service_Password__c;
        
        String surname ='676702';
        String mmCode ='NEGRIN';
        String partnerType =custPointsProvider.Alitalia_Partner_Type__c;
        String partnerCode =custPointsProvider.Alitalia_Partner_Code_Base__c;
        Integer transPoints = 200;
        Date activityDate = DateTime.newInstance(System.currentTimeMillis()).date();
        String transReference ='BV01234567';
   
   // This causes a fake response to be generated
   
        Test.setMock(WebServiceMock.class, new tempuriOrgTestMockCallout());
             
        objPTServiceSoap.callLogin(SOAP_HEADER_USER,SOAP_HEADER_PWS,partnerUSER_ID,partnerPASSWORD);
        objPTServiceSoap.callVerifyCustomer(SOAP_HEADER_USER,SOAP_HEADER_PWS,partnerUSER_ID,partnerPASSWORD,mmCode,surname);
        objPTServiceSoap.creditPoints(SOAP_HEADER_USER,SOAP_HEADER_PWS,partnerUSER_ID,partnerPASSWORD,mmCode,surname,
                    partnerCode,partnerType,activityDate,transReference,transPoints);
                                       
        tempuriOrg.callLogin_element a = new tempuriOrg.callLogin_element();
        
        tempuriOrg.callVerifyCustomer_element b = new tempuriOrg.callVerifyCustomer_element();
        tempuriOrg.callVerifyCustomerResponse_element c = new tempuriOrg.callVerifyCustomerResponse_element();
                        
    }
   
}