force-app/main/default/objects/Product_Loan__c/Product_Loan__c.object-meta.xml
<CustomObject>
    <description>Denotes an agreement between a brand, and the marketing team, to facilitate the loaning of products for marketing purposes.</description>
    <label>Product Loan</label>
    <nameField>
        <label>Product Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Loan_Item__c/Product_Loan_Item__c.object-meta.xml
<CustomObject>
    <description>An individual item in the product loan</description>
    <label>Product Loan Item</label>
    <nameField>
        <label>Product Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Loan Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Loan_Item__c/fields/Colour_of_product__c.field-meta.xml
<CustomField>
    <fullName>Colour_of_product__c</fullName>
    <description>The colour of the product loaned</description>
    <inlineHelpText>The colour of the product loaned</inlineHelpText>
    <label>Colour of product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Loan_Item__c/fields/Damage_Description__c.field-meta.xml
<CustomField>
    <fullName>Damage_Description__c</fullName>
    <description>Describe the damage to the product</description>
    <inlineHelpText>Describe the damage to the product</inlineHelpText>
    <label>Damage Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product_Loan_Item__c/fields/Damaged_on_collection__c.field-meta.xml
<CustomField>
    <fullName>Damaged_on_collection__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Was the product damaged on collection?</description>
    <inlineHelpText>Was the product damaged on collection?</inlineHelpText>
    <label>Damaged on collection</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Loan_Item__c/fields/Damaged_on_return__c.field-meta.xml
<CustomField>
    <fullName>Damaged_on_return__c</fullName>
    <defaultValue>false</defaultValue>
    <description>was the product damaged on return?</description>
    <inlineHelpText>was the product damaged on return?</inlineHelpText>
    <label>Damaged on return</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Loan_Item__c/fields/Description_of_product__c.field-meta.xml
<CustomField>
    <fullName>Description_of_product__c</fullName>
    <description>The description of the product on loan</description>
    <inlineHelpText>The description of the product on loan</inlineHelpText>
    <label>Description of product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Loan_Item__c/fields/Outlet_Price__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Price__c</fullName>
    <description>The outlet price of the product</description>
    <inlineHelpText>The outlet price of the product</inlineHelpText>
    <label>Outlet Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Loan_Item__c/fields/Product_Loan__c.field-meta.xml
<CustomField>
    <fullName>Product_Loan__c</fullName>
    <description>The product loan that the item belongs to</description>
    <inlineHelpText>The product loan that the item belongs to</inlineHelpText>
    <label>Product Loan</label>
    <referenceTo>Product_Loan__c</referenceTo>
    <relationshipLabel>Product Loan Items</relationshipLabel>
    <relationshipName>Product_Loan_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Loan_Item__c/fields/Product_Reference_SKU__c.field-meta.xml
<CustomField>
    <fullName>Product_Reference_SKU__c</fullName>
    <description>The product reference number or SKU</description>
    <inlineHelpText>The product reference number or SKU</inlineHelpText>
    <label>Product Reference SKU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Loan_Item__c/fields/Quantity_of_product__c.field-meta.xml
<CustomField>
    <fullName>Quantity_of_product__c</fullName>
    <description>The quantity of products on loan</description>
    <inlineHelpText>The quantity of products on loan</inlineHelpText>
    <label>Quantity of product</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Loan_Item__c/fields/Retail_Price__c.field-meta.xml
<CustomField>
    <fullName>Retail_Price__c</fullName>
    <description>The retail price of the product</description>
    <inlineHelpText>The retail price of the product</inlineHelpText>
    <label>Retail Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Loan_Item__c/fields/Sample_Product__c.field-meta.xml
<CustomField>
    <fullName>Sample_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this a sample product?</description>
    <inlineHelpText>Is this a sample product?</inlineHelpText>
    <label>Sample Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Loan_Item__c/fields/Sample_Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Sample_Product_Price__c</fullName>
    <description>The price of the sample product</description>
    <inlineHelpText>The price of the sample product</inlineHelpText>
    <label>Sample Product Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/productLoanEmailController.cls
public  class productLoanEmailController
{
    public Id ProductLoanID {get;set;}
    public List<Product_Loan_Item__c> getPLitems()
    {
        List<Product_Loan_Item__c> plItems;
        plItems = [SELECT ID, Name, Colour_of_product__c, Damage_Description__c,Damaged_on_collection__c,Damaged_on_return__c,Description_of_product__c,Outlet_Price__c,Product_Loan__c             
,Product_Reference_SKU__c,Quantity_of_product__c,Retail_Price__c,Sample_Product__c,Sample_Product_Price__c FROM Product_Loan_Item__c WHERE Product_Loan__c =: ProductLoanID];
        return plItems;
    }
}