force-app/main/default/objects/Competitor_site__c/Competitor_site__c.object-meta.xml
<CustomObject>
    <description>Competitor outlet centers to replace VRNET

http://intranet.valueretail.com/remerchandising/New%20Schemes/Forms/AllItems.aspx</description>
    <label>Competitor Site</label>
    <nameField>
        <label>Competitor Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_site__c/fields/Days_Overdue__c.field-meta.xml
<CustomField>
    <fullName>Days_Overdue__c</fullName>
    <formula>IF(Next_On_Site_Visit__c -  TODAY() &gt;= 0, 0,Next_On_Site_Visit__c -  TODAY())</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Overdue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Competitor_site__c/fields/Days_Since_Last_Site_Visit__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Last_Site_Visit__c</fullName>
    <formula>Today() -  Last_On_Site_Visit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Since Last Site Visit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Competitor_site__c/fields/Last_On_Site_Visit__c.field-meta.xml
<CustomField>
    <fullName>Last_On_Site_Visit__c</fullName>
    <inlineHelpText>This field updates when a Competitor Visit record is created</inlineHelpText>
    <label>Last On-Site Visit</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Competitor_site__c/fields/Next_On_Site_Visit__c.field-meta.xml
<CustomField>
    <fullName>Next_On_Site_Visit__c</fullName>
    <inlineHelpText>This field updates when a Competitor Visit record is created</inlineHelpText>
    <label>Next On-Site Visit</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Competitor_site__c/fields/Priority_level__c.field-meta.xml
<CustomField>
    <fullName>Priority_level__c</fullName>
    <label>Priority level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CompSiteDashController.cls
Public Class CompSiteDashController{

    public list<Competitor_Site__c> compsites {get;set;}
      
    Public CompSiteDashController(){
        compsites = [Select id, Name, days_overdue__c, last_on_Site_visit__c,Next_On_site_visit__c,Priority_level__c,Days_Since_Last_Site_Visit__c FROM Competitor_Site__c WHERE Days_Since_Last_Site_Visit__c >= 0 ORDER BY Days_Since_Last_Site_Visit__c ASC ];  
    }

}