force-app/main/default/objects/Competitor_site__c/Competitor_site__c.object-meta.xml
<CustomObject>
    <description>Competitor outlet centers to replace VRNET

http://intranet.valueretail.com/remerchandising/New%20Schemes/Forms/AllItems.aspx</description>
    <label>Competitor Site</label>
    <nameField>
        <label>Competitor Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_site__c/fields/Competitor_to_Village__c.field-meta.xml
<CustomField>
    <fullName>Competitor_to_Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Competitor to Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Competitor Sites</relationshipLabel>
    <relationshipName>Competitor_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_site__c/fields/Distance_From_Village__c.field-meta.xml
<CustomField>
    <fullName>Distance_From_Village__c</fullName>
    <formula>IF( ISBLANK( Site_Coordinates__Latitude__s ) , &quot;No coordinates registered&quot;,   TEXT(ROUND(DISTANCE( Site_Coordinates__c , Competitor_to_Village__r.Village_GeoLocation__c , &quot;km&quot;),1)) &amp; &quot; Km&quot; )</formula>
    <label>Distance From Village</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Competitor_site__c/fields/Site_coordinates_Text__c.field-meta.xml
<CustomField>
    <fullName>Site_coordinates_Text__c</fullName>
    <formula>TEXT( Site_Coordinates__Latitude__s)&amp;&quot; &quot;&amp;TEXT( Site_Coordinates__Longitude__s )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site_coordinates_Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Competitor_site__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Developing Full Price</fullName>
            </value>
            <value>
                <fullName>Developing Outlet</fullName>
            </value>
            <value>
                <fullName>Existing Full Price</fullName>
            </value>
            <value>
                <fullName>Existing Outlet</fullName>
            </value>
            <value>
                <fullName>Closed Full Price</fullName>
            </value>
            <value>
                <fullName>Closed Outlet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/Village_GeoLocation_Text__c.field-meta.xml
<CustomField>
    <fullName>Village_GeoLocation_Text__c</fullName>
    <formula>TEXT(  Village_GeoLocation__Latitude__s )&amp;&quot; &quot;&amp;TEXT(  Village_GeoLocation__Longitude__s  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Village_GeoLocation_Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CompetitorSitesGeoController.cls
public with sharing class CompetitorSitesGeoController {


	public list<Competitor_Site__c> siteList {get; set;}
	public list<Village__c> villageList {get; set;}  
	
	
	// Extract all VR villages and Competitor Sites to display on global page
    public CompetitorSitesGeoController(ApexPages.StandardSetController controller) {
		
		siteList = new list<Competitor_Site__c>();
		villageList = new list<Village__c>();
		
		siteList = [select Id, Name, Site_coordinates_Text__c, Distance_From_Village__c, Type__c,
						Competitor_to_Village__r.Name from Competitor_Site__c];
						
		villageList = [select Id, Name, Village_GeoLocation_Text__c from Village__c];				
						
		if (!siteList.isEmpty()){
			controller.setPageSize(siteList.size());
		}
		
    }


}