force-app/main/default/objects/Competitor_site__c/Competitor_site__c.object-meta.xml
<CustomObject>
    <description>Competitor outlet centers to replace VRNET

http://intranet.valueretail.com/remerchandising/New%20Schemes/Forms/AllItems.aspx</description>
    <label>Competitor Site</label>
    <nameField>
        <label>Competitor Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Visit__c/Competitor_Visit__c.object-meta.xml
<CustomObject>
    <label>Competitor Visit</label>
    <nameField>
        <displayFormat>CV-{0000000}</displayFormat>
        <label>Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Visit__c/fields/Competitor_Site__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Site__c</fullName>
    <label>Competitor Site</label>
    <referenceTo>Competitor_site__c</referenceTo>
    <relationshipLabel>Competitor Visits / Intel</relationshipLabel>
    <relationshipName>Competitor_Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/fields/Customer_Service__c.field-meta.xml
<CustomField>
    <fullName>Customer_Service__c</fullName>
    <label>Customer Service</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Efficient</fullName>
            </value>
            <value>
                <fullName>Spoke Various Languages</fullName>
            </value>
            <value>
                <fullName>Understood My Concerns</fullName>
            </value>
            <value>
                <fullName>Resolved My Concerns</fullName>
            </value>
            <value>
                <fullName>Accessible</fullName>
            </value>
            <value>
                <fullName>Welcoming</fullName>
            </value>
            <value>
                <fullName>Helpful</fullName>
            </value>
            <value>
                <fullName>Encouraged To Purchase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/fields/Date_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Visit__c</fullName>
    <label>Date of Visit/Source</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/fields/Extra_Services__c.field-meta.xml
<CustomField>
    <fullName>Extra_Services__c</fullName>
    <description>..</description>
    <label>Extra Services</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tailoring</fullName>
            </value>
            <value>
                <fullName>personalization</fullName>
            </value>
            <value>
                <fullName>Information Hub (TIC)</fullName>
            </value>
            <value>
                <fullName>Hands-free Shopping</fullName>
            </value>
            <value>
                <fullName>Valet Parking</fullName>
            </value>
            <value>
                <fullName>Charging Stations</fullName>
            </value>
            <value>
                <fullName>Tax Free</fullName>
            </value>
            <value>
                <fullName>Loyalty Program</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>bag Storage Area</fullName>
            </value>
            <value>
                <fullName>Gift Wrapping</fullName>
            </value>
            <value>
                <fullName>Beauty Services</fullName>
            </value>
            <value>
                <fullName>Dog Allowance</fullName>
            </value>
            <value>
                <fullName>Personal Shopping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/fields/Food_Beverage_Options__c.field-meta.xml
<CustomField>
    <fullName>Food_Beverage_Options__c</fullName>
    <label>Food &amp; Beverage Options</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>1 - 5</fullName>
            </value>
            <value>
                <fullName>6 - 10</fullName>
            </value>
            <value>
                <fullName>10 +</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/fields/General_Presentation__c.field-meta.xml
<CustomField>
    <fullName>General_Presentation__c</fullName>
    <label>General Presentation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Clean Floors</fullName>
            </value>
            <value>
                <fullName>Free Parking</fullName>
            </value>
            <value>
                <fullName>Clean Windows</fullName>
            </value>
            <value>
                <fullName>Good Lighting</fullName>
            </value>
            <value>
                <fullName>Music</fullName>
            </value>
            <value>
                <fullName>Landscape Outside</fullName>
            </value>
            <value>
                <fullName>Parking Availability</fullName>
            </value>
            <value>
                <fullName>Brochures</fullName>
            </value>
            <value>
                <fullName>Good Acoustic</fullName>
            </value>
            <value>
                <fullName>Promotional Marketing</fullName>
            </value>
            <value>
                <fullName>Navigational Signage</fullName>
            </value>
            <value>
                <fullName>Directory/Map</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/fields/Overall_Experience__c.field-meta.xml
<CustomField>
    <fullName>Overall_Experience__c</fullName>
    <label>Overall Experience</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Poor</fullName>
            </value>
            <value>
                <fullName>Satisfactory</fullName>
            </value>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Extraordinary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/fields/Retail_Discount__c.field-meta.xml
<CustomField>
    <fullName>Retail_Discount__c</fullName>
    <label>Retail Discount</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>&lt;5%</fullName>
            </value>
            <value>
                <fullName>5 - 10%</fullName>
            </value>
            <value>
                <fullName>10 - 20%</fullName>
            </value>
            <value>
                <fullName>20 -30%</fullName>
            </value>
            <value>
                <fullName>30 - 40%</fullName>
            </value>
            <value>
                <fullName>40 - 50%</fullName>
            </value>
            <value>
                <fullName>50 - 75%</fullName>
            </value>
            <value>
                <fullName>&gt;75%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CompetitorSiteVisitController.cls
Global Class CompetitorSiteVisitController{

  public date startdate {get;set;}
  public List<Event> myevents {get;set;} 
  public transient List<ContentVersion> myattachments {get;set;}
  public string experience {get;set;}
  public transient Competitor_site__c compsite;
  public string compsiteid {get;set;}
  public string compsitename {get;set;}
  public string compsitevillage {get;set;}       
  public transient blob file { get; set; }
  public String fn { get; set; }  
  public String recType {get;set;}
  public Competitor_Site__c csv {get;set;}
  public Competitor_Visit__c cv {get;set;}
  public boolean isMobile {get;set;}
  public string compName {get;set;}
  public Date dateToday {get;set;}
  public id listViewId {get;set;}
  public string theURL {get;set;}
  


  public CompetitorSiteVisitController(ApexPages.StandardController controller) {     
  listViewId = [SELECT id FROM ListView WHERE SobjectType = 'Competitor_site__c' AND Name = 'All'].id;
  compsite = (Competitor_site__c)Controller.getRecord(); 
  compsiteid = compsite.id;
  system.debug('compsiteid :' + compsiteid);
  cv = new Competitor_Visit__c();
  cv.Retail_Discount__c = 'Select Retail Discount';
  cv.General_Presentation__c = 'Select General Presentation';
  cv.Customer_Service__c = 'Select Customer Services';
  cv.Extra_Services__c = 'Select Extra Services';
  cv.Food_Beverage_Options__c = 'Select Food & Beverages';
  cv.Overall_Experience__c = 'Select Overall Experience';
  string userisMobile = UserInfo.getUiTheme();
  isMobile = !userisMobile.contains('Theme4t');  
  dateToday = system.today();
  Competitor_site__c cs = [Select id, name FROM Competitor_site__c WHERE id =: compsiteid ];
  compName = cs.name;
  theuRL = URL.getSalesforceBaseUrl().toExternalForm();
  }



  public List<SelectOption> getOveralls() {
    List<SelectOption> options = new List<SelectOption>();
      Schema.DescribeFieldResult fieldResult = Competitor_Visit__c.Overall_Experience__c.getDescribe();
      List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
      SelectOption placeholder = new SelectOption('Select Overall Experience','Select Overall Experience',true);
      options.add(placeholder);
      for( Schema.PicklistEntry pickListVal : ple){
      options.add(new SelectOption(pickListVal.getLabel(),pickListVal.getLabel()));
      }      
    return options;
  }

  public List<SelectOption> getFoodBeverage() {
    List<SelectOption> options = new List<SelectOption>();
      Schema.DescribeFieldResult fieldResult = Competitor_Visit__c.Food_Beverage_Options__c.getDescribe();
      List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
      SelectOption placeholder = new SelectOption('Select Food & Beverages','Select Food & Beverages',true);
      options.add(placeholder);
      for( Schema.PicklistEntry pickListVal : ple){
      options.add(new SelectOption(pickListVal.getLabel(),pickListVal.getLabel()));
      }      
    return options;
  }


  public List<SelectOption> getExtras() {
    List<SelectOption> options = new List<SelectOption>();
      Schema.DescribeFieldResult fieldResult = Competitor_Visit__c.Extra_Services__c.getDescribe();
      List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
      SelectOption placeholder = new SelectOption('Select Extra Services','Select Extra Services',true);
      options.add(placeholder);
      for( Schema.PicklistEntry pickListVal : ple){
      options.add(new SelectOption(pickListVal.getLabel(),pickListVal.getLabel()));
      }      
    return options;
  }



  public List<SelectOption> getItems() {
    List<SelectOption> options = new List<SelectOption>();
      Schema.DescribeFieldResult fieldResult = Competitor_Visit__c.Retail_Discount__c.getDescribe();
      List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
      SelectOption placeholder = new SelectOption('Select Retail Discount','Select Retail Discount',true);
      options.add(placeholder);
      for( Schema.PicklistEntry pickListVal : ple){
      options.add(new SelectOption(pickListVal.getLabel(),pickListVal.getLabel()));
      }      
    return options;
  }

  public List<SelectOption> getPresentations() {
    List<SelectOption> options = new List<SelectOption>();
      Schema.DescribeFieldResult fieldResult = Competitor_Visit__c.General_Presentation__c.getDescribe();
      List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
      SelectOption placeholder = new SelectOption('Select General Presentation','Select General Presentation',true);
      options.add(placeholder);
      for( Schema.PicklistEntry pickListVal : ple){
      options.add(new SelectOption(pickListVal.getLabel(),pickListVal.getLabel()));
      }      
    return options;
  }

  public List<SelectOption> getServices() {
    List<SelectOption> options = new List<SelectOption>();
      Schema.DescribeFieldResult fieldResult = Competitor_Visit__c.Customer_Service__c.getDescribe();
      List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
      SelectOption placeholder = new SelectOption('Select Customer Services','Select Customer Services',true);
      options.add(placeholder);
      for( Schema.PicklistEntry pickListVal : ple){
      options.add(new SelectOption(pickListVal.getLabel(),pickListVal.getLabel()));
      }      
    return options;
  }

      
  public ContentVersion contentversion {
        get {
            if (contentversion == null)
            contentversion = new ContentVersion();
            return contentversion;
        }
        set;
  }
  
  
  public list<string> mylist{
      get{
      if(mylist == null)
      mylist = new List<string>();
      return mylist;
      }
      set;
      }
        
        
  public void startdate(date startdate){
  this.startdate = startdate;
  }
  
         
  public PageReference addAttachements() {  
            
      RecordType rt = [SELECT id,name FROM RecordType where sObjectType = 'Competitor_Visit__c' AND Name =:recType ];     

      if(cv.General_Presentation__c != NULL){
        string newStr = '';
          for (string str : cv.General_Presentation__c.split(',') ){
              if(str.contains('[')){
                str = str.right(str.length()-1);
              }
              if(str.contains(']')){
                str = str.left(str.length()-1);
              }
              newStr = newStr + str + ';';
        }
        cv.General_Presentation__c = newStr;
      }    


      if(cv.Customer_Service__c != NULL){
        string newStr = '';
          for (string str : cv.Customer_Service__c.split(',') ){
              if(str.contains('[')){
                str = str.right(str.length()-1);
              }
              if(str.contains(']')){
                str = str.left(str.length()-1);
              }
              newStr = newStr + str + ';';
        }
        cv.Customer_Service__c = newStr;
      } 

      if(cv.Extra_Services__c != NULL){
        string newStr = '';
          for (string str : cv.Extra_Services__c.split(',') ){
              if(str.contains('[')){
                str = str.right(str.length()-1);
              }
              if(str.contains(']')){
                str = str.left(str.length()-1);
              }
              newStr = newStr + str + ';';
        }
        cv.Extra_Services__c = newStr;
      } 
        
       CV.Recordtypeid = rt.id; 
       cv.Competitor_Site__c = compsiteid;
       CV.Date_of_Visit__c = startdate;
       insert cv; 
       
       ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Record created successfully'));  
       
       return Page.Competitor_Report_AttachmentsV2;
   }
     

   public PageReference go() {
  
          contentversion.versionData = file;
          contentversion.pathOnClient = fn;
          contentversion.FirstPublishLocationId = cv.id;
          system.debug('go called ');
          
      try {
            insert contentversion;
            mylist.add(contentversion.id);
            system.debug('mylist ' + mylist);
            
                            
          } catch (DMLException e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error uploading attachment'));
            return null;
          } finally 
          {
           contentversion = new ContentVersion(); 
          }
          system.debug('1st debug: ');
          myattachments = [SELECT id,description,ContentDocumentId,PathOnClient,FileType,title FROM ContentVersion WHERE id in :mylist];
          system.debug('2nd debug: ');
          ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Attachment uploaded successfully'));  
          return page.Competitor_Report_AttachmentsV2;    
  }


  public PageReference toNextPage() {
    PageReference pageRef = page.Competitor_Report_CreateV2; 
    system.debug('recType' + recType);
    return pageRef;
  }


  public PageReference finishUp() {
    PageReference pageRef = new PageReference('/'+cv.Id);
    return pageRef;
  }
  

@RemoteAction
public static String doUploadAttachment(String cvId, String attachmentBody, String attachmentName, String attachmentId) {
  if(cvId != null) {
      Competitor_Visit__c cvs = getVisits(cvId);
      if(cvs != null) {
          if(attachmentBody != null) {
          
              list<CollaborationGroup > siteGroup = [SELECT id, NAME FROM CollaborationGroup WHERE name = 'Competitor Site Visits' LIMIT 1 ];
          
              ContentVersion contVers = getContentVersion(attachmentId);
              String newBody = '';
              if(contVers.VersionData != null) {
                  newBody = EncodingUtil.base64Encode(contVers.VersionData);
              }
              newBody += attachmentBody;
              contVers.VersionData = EncodingUtil.base64Decode(newBody);
              list<string> listIds = new list<string>();
              if(attachmentId == null) {
                  contVers.Title = attachmentName;
                  contVers.PathOnClient = attachmentName + '.jpg';
                  contVers.FirstPublishLocationId = cvs.Id;
                  contVers.ContentLocation = 'S';
                  contVers.SharingPrivacy = 'N';
              }
              upsert contVers;
                    listIds.add(contVers.id);
                    
                    //--------------
                    list<ContentVersion> theAttachments = [SELECT id,description,ContentDocumentId,PathOnClient,FileType,title FROM ContentVersion WHERE id in :listIds];
                    list<string> contDocIds = new list<string>();
                    for(ContentVersion cv : theAttachments)
                    {
                        contDocIds.add(cv.ContentDocumentId);          
                    }
                    
                    list<ContentDocumentLink> links = new list<ContentDocumentLink>();
                    
                    for(string id : contDocIds){
                        ContentDocumentLink cdl = new ContentDocumentLink();
                        cdl.Visibility = 'AllUsers';
                        cdl.LinkedEntityId = siteGroup[0].id;
                        cdl.ShareType = 'V';
                        cdl.ContentDocumentId = id;
                        links.add(cdl);
                    }
                    insert links;
                  
                    //----------------
                    return contVers.Id;
          } else {
              return 'Attachment Body was null';
          }
      } else {
          return 'Account could not be found';
      }
  } else {
      return 'Account Id was null';
  }
}

private static ContentVersion getContentVersion(String cvId) {
  list<ContentVersion> contVers = [SELECT Id, VersionData 
                                  FROM ContentVersion 
                                  WHERE Id =: cvId];
  if(contVers.isEmpty()) {
      ContentVersion cv = new ContentVersion();
      return cv;
  } else {
      return contVers[0];
  }
}

private static Competitor_Visit__c getVisits(String acctId) {
  list<Competitor_Visit__c> cvs = [SELECT Id, Name
                            FROM Competitor_Visit__c
                            WHERE Id =: acctId];
  if(cvs.isEmpty()) {
      return null;
  } else {
      return cvs[0];
  }
}
    
}