force-app/main/default/objects/Competitor_site__c/Competitor_site__c.object-meta.xml
<CustomObject>
    <description>Competitor outlet centers to replace VRNET

http://intranet.valueretail.com/remerchandising/New%20Schemes/Forms/AllItems.aspx</description>
    <label>Competitor Site</label>
    <nameField>
        <label>Competitor Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_site__c/fields/Competitor_to_Village__c.field-meta.xml
<CustomField>
    <fullName>Competitor_to_Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Competitor to Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Competitor Sites</relationshipLabel>
    <relationshipName>Competitor_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/Competitor_Visit__c.object-meta.xml
<CustomObject>
    <label>Competitor Visit</label>
    <nameField>
        <displayFormat>CV-{0000000}</displayFormat>
        <label>Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Visit__c/fields/Announced_New_Arrivals__c.field-meta.xml
<CustomField>
    <fullName>Announced_New_Arrivals__c</fullName>
    <label>Announced New Arrivals</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/fields/Competitor_Site__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Site__c</fullName>
    <label>Competitor Site</label>
    <referenceTo>Competitor_site__c</referenceTo>
    <relationshipLabel>Competitor Visits / Intel</relationshipLabel>
    <relationshipName>Competitor_Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/fields/Date_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Visit__c</fullName>
    <label>Date of Visit/Source</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/fields/Number_of_Empty_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Empty_Units__c</fullName>
    <label>Number of Empty Units</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/CompetitorVisitImagesController_Test.cls
@IsTest
public class CompetitorVisitImagesController_Test {

    @testSetup
    public static void setupData(){
        
        Village__c village = TestDataGenerator.setupVillage(true);
        
        Competitor_Site__c compSite = new Competitor_Site__c(competitor_to_village__c = village.id);
        insert compSite;
        
        Competitor_Visit__c compVisit = new Competitor_Visit__c(Competitor_Site__c = compSite.id, Date_of_Visit__c = system.today(), Number_of_Empty_Units__c = 2, Announced_New_Arrivals__c = 3 );
        insert compVisit;
        
        ContentVersion contVers = new ContentVersion(Title = 'Test', PathOnClient = 'Test.jpg', FirstPublishLocationId = compVisit.Id, ContentLocation = 'S', VersionData = Blob.valueOf('Test'));
        insert contVers;
    }
    
    
    static testmethod void testConstructor(){
        Village__c village = [SELECT Id FROM Village__c LIMIT 1];
        Competitor_Visit__c compVisit = [SELECT Id FROM Competitor_Visit__c WHERE Competitor_Site__r.competitor_to_village__c = :village.Id LIMIT 1];
        
        Test.startTest();
        ApexPages.StandardController stdController = new ApexPages.StandardController(compVisit);
        CompetitorVisitImagesController ctrller = new CompetitorVisitImagesController(stdController);
        ContentVersion cv = ctrller.contentversion;
        Test.stopTest();
        system.assert(!ctrller.fileIdsLtg.isEmpty());
    } 
    
}