force-app/main/default/objects/Competitor_site__c/Competitor_site__c.object-meta.xml
<CustomObject>
    <description>Competitor outlet centers to replace VRNET

http://intranet.valueretail.com/remerchandising/New%20Schemes/Forms/AllItems.aspx</description>
    <label>Competitor Site</label>
    <nameField>
        <label>Competitor Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_site__c/fields/Competitor_to_Village__c.field-meta.xml
<CustomField>
    <fullName>Competitor_to_Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Competitor to Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Competitor Sites</relationshipLabel>
    <relationshipName>Competitor_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/Competitor_Visit__c.object-meta.xml
<CustomObject>
    <label>Competitor Visit</label>
    <nameField>
        <displayFormat>CV-{0000000}</displayFormat>
        <label>Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Visit__c/fields/Announced_New_Arrivals__c.field-meta.xml
<CustomField>
    <fullName>Announced_New_Arrivals__c</fullName>
    <label>Announced New Arrivals</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/fields/Competitor_Site__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Site__c</fullName>
    <label>Competitor Site</label>
    <referenceTo>Competitor_site__c</referenceTo>
    <relationshipLabel>Competitor Visits / Intel</relationshipLabel>
    <relationshipName>Competitor_Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/fields/Date_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Visit__c</fullName>
    <label>Date of Visit/Source</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/fields/Number_of_Empty_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Empty_Units__c</fullName>
    <label>Number of Empty Units</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/recordTypes/Intel.recordType-meta.xml
<RecordType>
    <fullName>Intel</fullName>
    <active>true</active>
    <description>Competitive intelligence gathered from contacts etc.</description>
    <label>Intel</label>
</RecordType>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/CompetitorSiteVisitController_Test.cls
@IsTest
public class CompetitorSiteVisitController_Test {

    @testSetup
    public static void setupData(){
        
        Village__c village = TestDataGenerator.setupVillage(true);
        
        Competitor_Site__c compSite = new Competitor_Site__c(competitor_to_village__c = village.id);
        insert compSite;
        
        insert new Competitor_Visit__c(Competitor_Site__c = compSite.id, Date_of_Visit__c = system.today(), Number_of_Empty_Units__c = 2, Announced_New_Arrivals__c = 3 );
        
    }
    
    static testmethod void testDoUploadAttachment_Success(){
        Village__c village = [SELECT Id FROM Village__c LIMIT 1];
        Competitor_Site__c compSite = [SELECT Id FROM Competitor_Site__c WHERE competitor_to_village__c = :village.Id LIMIT 1];
        Competitor_Visit__c compVisit = [SELECT Id FROM Competitor_Visit__c WHERE Competitor_Site__c = :compSite.Id LIMIT 1];

        Test.startTest();
        String bodyTest = 'This is a test';
        String result = CompetitorSiteVisitController.doUploadAttachment(compVisit.Id, bodyTest, 'ExampleTestContentVersion', null);
        Test.stopTest();
        
        system.assertEquals(String.valueOf(((Id)result).getSObjectType()), 'ContentVersion');
        List<ContentVersion> contVersList = [SELECT Id, Title, VersionData FROM ContentVersion WHERE Id = :result];
        system.assert(!contVersList.isEmpty());
    } 
    
    static testmethod void testDoUploadAttachment_Error1(){
        Village__c village = [SELECT Id FROM Village__c LIMIT 1];
        Competitor_Site__c compSite = [SELECT Id FROM Competitor_Site__c WHERE competitor_to_village__c = :village.Id LIMIT 1];
        Competitor_Visit__c compVisit = [SELECT Id FROM Competitor_Visit__c WHERE Competitor_Site__c = :compSite.Id LIMIT 1];

        Test.startTest();
        String bodyTest = null;
        String result = CompetitorSiteVisitController.doUploadAttachment(compVisit.Id, bodyTest, 'ExampleTestContentVersion', null);
        Test.stopTest();
        
        List<ContentVersion> contVersList = [SELECT Id, Title, VersionData FROM ContentVersion WHERE Id = :result];
        system.assert(contVersList.isEmpty());
    } 
    
    static testmethod void testDoUploadAttachment_Error2(){
        Village__c village = [SELECT Id FROM Village__c LIMIT 1];
        Competitor_Site__c compSite = [SELECT Id FROM Competitor_Site__c WHERE competitor_to_village__c = :village.Id LIMIT 1];
        Competitor_Visit__c compVisit = [SELECT Id FROM Competitor_Visit__c WHERE Competitor_Site__c = :compSite.Id LIMIT 1];

        Test.startTest();
        String bodyTest = 'This is a test';
        String result = CompetitorSiteVisitController.doUploadAttachment(null, bodyTest, 'ExampleTestContentVersion', null);
        Test.stopTest();
        
        List<ContentVersion> contVersList = [SELECT Id, Title, VersionData FROM ContentVersion WHERE Id = :result];
        system.assert(contVersList.isEmpty());
    } 
    
    static testmethod void testDoUploadAttachment_Error3(){
        Village__c village = [SELECT Id FROM Village__c LIMIT 1];
        Competitor_Site__c compSite = [SELECT Id FROM Competitor_Site__c WHERE competitor_to_village__c = :village.Id LIMIT 1];
        Competitor_Visit__c compVisit = [SELECT Id FROM Competitor_Visit__c WHERE Competitor_Site__c = :compSite.Id LIMIT 1];

        Test.startTest();
        String bodyTest = 'This is a test';
        String result = CompetitorSiteVisitController.doUploadAttachment('error', bodyTest, 'ExampleTestContentVersion', null);
        Test.stopTest();
        
        List<ContentVersion> contVersList = [SELECT Id, Title, VersionData FROM ContentVersion WHERE Id = :result];
        system.assert(contVersList.isEmpty());
    } 
    
    static testmethod void testGo_Success(){
        Village__c village = [SELECT Id FROM Village__c LIMIT 1];
        Competitor_Site__c compSite = [SELECT Id FROM Competitor_Site__c WHERE competitor_to_village__c = :village.Id LIMIT 1];
        Competitor_Visit__c compVisit = [SELECT Id FROM Competitor_Visit__c WHERE Competitor_Site__c = :compSite.Id LIMIT 1];

        Test.startTest();     
        ApexPages.StandardController stdController = new ApexPages.StandardController(compSite);
        CompetitorSiteVisitController ctrller = new CompetitorSiteVisitController(stdController);
        ctrller.fn = 'ExampleTest';
        ctrller.file = EncodingUtil.base64Decode('This is a test');
        ctrller.cv = compVisit;
        ctrller.go();
        Test.stopTest();
        
        List<ContentVersion> contVersList = [SELECT Id, Title, VersionData FROM ContentVersion WHERE FirstPublishLocationId = :compVisit.Id];
        system.assert(!contVersList.isEmpty());
    } 
    
    static testmethod void testPicklist(){
        Village__c village = [SELECT Id FROM Village__c LIMIT 1];
        Competitor_Site__c compSite = [SELECT Id FROM Competitor_Site__c WHERE competitor_to_village__c = :village.Id LIMIT 1];
        
        Test.startTest();     
        ApexPages.StandardController stdController = new ApexPages.StandardController(compSite);
        CompetitorSiteVisitController ctrller = new CompetitorSiteVisitController(stdController);
        
        List<SelectOption> overalls = ctrller.getOveralls();
        List<SelectOption> foods = ctrller.getFoodBeverage();
        List<SelectOption> extras = ctrller.getExtras();
        List<SelectOption> items = ctrller.getItems();
        List<SelectOption> presentations = ctrller.getPresentations();
        List<SelectOption> services = ctrller.getServices();
        
        Test.stopTest();
        
        system.assert(!overalls.isEmpty());
        system.assert(!foods.isEmpty());
        system.assert(!extras.isEmpty());
        system.assert(!items.isEmpty());
        system.assert(!presentations.isEmpty());
        system.assert(!services.isEmpty());
        
    }
    
    static testmethod void testAddAttachments(){
        Village__c village = [SELECT Id FROM Village__c LIMIT 1];
        Competitor_Site__c compSite = [SELECT Id FROM Competitor_Site__c WHERE competitor_to_village__c = :village.Id LIMIT 1];
        
        Test.startTest();     
        ApexPages.StandardController stdController = new ApexPages.StandardController(compSite);
        CompetitorSiteVisitController ctrller = new CompetitorSiteVisitController(stdController);
        ctrller.recType = 'Intel';
        ctrller.addAttachements();
        Test.stopTest();
    }
    
    static testmethod void testRedirects(){
        Village__c village = [SELECT Id FROM Village__c LIMIT 1];
        Competitor_Site__c compSite = [SELECT Id FROM Competitor_Site__c WHERE competitor_to_village__c = :village.Id LIMIT 1];
        Date today = system.today();
        
        Test.startTest();     
        ApexPages.StandardController stdController = new ApexPages.StandardController(compSite);
        CompetitorSiteVisitController ctrller = new CompetitorSiteVisitController(stdController);
        
        ctrller.startdate(today);
        PageReference nextPage = ctrller.toNextPage();
        PageReference finish = ctrller.finishUp();
        Test.stopTest();
        
        system.assertNotEquals(null,nextPage);
        system.assertNotEquals(null,finish);
        system.assertEquals(ctrller.startDate, today);
    }
    
}