force-app/main/default/objects/Competitor_site__c/Competitor_site__c.object-meta.xml
<CustomObject>
    <description>Competitor outlet centers to replace VRNET

http://intranet.valueretail.com/remerchandising/New%20Schemes/Forms/AllItems.aspx</description>
    <label>Competitor Site</label>
    <nameField>
        <label>Competitor Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_site__c/fields/Competitor_to_Village__c.field-meta.xml
<CustomField>
    <fullName>Competitor_to_Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Competitor to Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Competitor Sites</relationshipLabel>
    <relationshipName>Competitor_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Store__c/Competitor_Store__c.object-meta.xml
<CustomObject>
    <description>resolving Many-to-Many junction object</description>
    <label>Competitor Store</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Competitor Store ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Store</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Store__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitor Store</relationshipLabel>
    <relationshipName>Competitor_Store</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Competitor_Store__c/fields/Competitor_Site__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Site__c</fullName>
    <label>Competitor Site</label>
    <referenceTo>Competitor_site__c</referenceTo>
    <relationshipLabel>Competitor Store</relationshipLabel>
    <relationshipName>Competitor_Store</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Competitor_Store__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Village Presence</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>Competitor Stores</relationshipLabel>
    <relationshipName>Competitor_Store</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <inlineHelpText>Add a Village Presence Contact Role to add Villages to this field</inlineHelpText>
    <label>Village Presence</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Village Presence records must be linked to Brand accounts. Please ensure you are not linking the Deal/Village Presence to a Group</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/CompetitorStoreTriggerHelperTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seeAllData=true)
private class CompetitorStoreTriggerHelperTest {

	private static Account account = new Account();
	private static Contact contact = new Contact();
	private static Village__c village1 = new Village__c();
    private static Village_Presence__c villagePresence = new Village_Presence__c();
    private static Competitor_Site__c competitorSite = new Competitor_Site__c();    
    
    static void setupData(){
    
		account = TestData_Account.setupBrandAccount(1, true);
		contact = TestData_Contact.setupBrandContact('A',account, true);	
					
 		//create village 1
 		village1 = new Village__c();
 		village1.Name = 'TestVillage1'; 		
 		village1.Village_Code__c = 'AA';
 		village1.Village_GeoLocation__Latitude__s = 50.500;
 		village1.Village_GeoLocation__Longitude__s = -1.5;
		village1.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		village1.CertSales_Report_Sales_Grace_Period_Days__c = 1;
 		insert village1;
		village1 = [select name, id, Village_Code__c from Village__c where Village_Code__c = 'AA' LIMIT 1];   	

    	//create village presence
    	villagePresence = new Village_Presence__c();
    	villagePresence.Brand__c = account.Id;
    	villagePresence.Village__c = village1.Id;
    	insert villagePresence;
    	
    	competitorSite.Competitor_to_Village__c = village1.Id;
    	competitorSite.Site_Coordinates__Latitude__s = 50.100;
    	competitorSite.Site_Coordinates__Longitude__s = -1;
    	insert competitorSite;
    
    }

    static testMethod void testStoreUpsert() {
  		
  		setUpData();
  		
  		Competitor_Store__c store = new Competitor_Store__c();
  		store.Brand__c = account.Id;
  		store.Competitor_Site__c = competitorSite.Id;
  		
  		test.startTest();
  			insert store;
    	test.stopTest();
    	
    	store = [select Village_Presence__c from Competitor_Store__c where Id = :store.Id];
    	
    	system.assertEquals(store.Village_Presence__c, villagePresence.Id);
    
    }
}