force-app/main/default/objects/Competitor_site__c/Competitor_site__c.object-meta.xml
<CustomObject>
    <description>Competitor outlet centers to replace VRNET

http://intranet.valueretail.com/remerchandising/New%20Schemes/Forms/AllItems.aspx</description>
    <label>Competitor Site</label>
    <nameField>
        <label>Competitor Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_site__c/fields/Competitor_to_Village__c.field-meta.xml
<CustomField>
    <fullName>Competitor_to_Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Competitor to Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Competitor Sites</relationshipLabel>
    <relationshipName>Competitor_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/shareCompetitorVisitTest.cls
@isTest(SeeAllData=true)
global class shareCompetitorVisitTest{

private static testMethod void doTest() {

list <shareCompetitorVisit.myeventId> mycmpr = new list<shareCompetitorVisit.myeventId>();

shareCompetitorVisit.myeventId cmpr = new shareCompetitorVisit.myeventId();

        
        Village__c village = new Village__c();
        village.Name = 'TestVillage1';     
        village.Village_Code__c = 'AA';
		village.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		village.CertSales_Report_Sales_Grace_Period_Days__c = 1; 
        insert village;

        Competitor_Site__c cs = new Competitor_Site__c();
        cs.name = 'test Site';
        cs.Competitor_to_Village__c = village.id;
        
        event me = new event();
        me.Event_Department__c = 'Leasing/Commercialisation';
        me.Event_Status__c = 'Meeting Completed';
        me.StartDateTime = Date.Today();
        me.EndDateTime = Date.Today()+1;
        insert me;
        
        FeedItem post = new FeedItem();
            post.Title = 'Dan Childs created a competitor Site visit';
            post.body = 'Competitor Site Report' + '\n' +
            'Department :' + 'TESTS' + '\n' +
            'Village :' + 'Village' +  '\n' +
            'Meeting Notes :' + 'Motes';
             post.LinkUrl = '/'+ me.id ;
            post.ParentId = me.id;
            insert post;
        
        cmpr.eventIds = me.id;
        cmpr.eventName = 'TEST';
        cmpr.body = 'test body';
        cmpr.postid = post.id;
        system.debug(cmpr);
 
                
        mycmpr.add(cmpr);
        
        
    
        Test.startTest();
       
        shareCompetitorVisit.Id(mycmpr);
       
        
        Test.stopTest();

    }
}