force-app/main/default/objects/Competitor_site__c/Competitor_site__c.object-meta.xml
<CustomObject>
    <description>Competitor outlet centers to replace VRNET

http://intranet.valueretail.com/remerchandising/New%20Schemes/Forms/AllItems.aspx</description>
    <label>Competitor Site</label>
    <nameField>
        <label>Competitor Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Visit__c/Competitor_Visit__c.object-meta.xml
<CustomObject>
    <label>Competitor Visit</label>
    <nameField>
        <displayFormat>CV-{0000000}</displayFormat>
        <label>Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Visit__c/fields/BVSC_Employees_Name__c.field-meta.xml
<CustomField>
    <fullName>BVSC_Employees_Name__c</fullName>
    <label>BVSC Employees Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/fields/Competitor_Site__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Site__c</fullName>
    <label>Competitor Site</label>
    <referenceTo>Competitor_site__c</referenceTo>
    <relationshipLabel>Competitor Visits / Intel</relationshipLabel>
    <relationshipName>Competitor_Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Competitor_Visit__c/fields/Date_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Visit__c</fullName>
    <label>Date of Visit/Source</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/getCompetitorVisits.cls
Global class getCompetitorVisits{

    public Id compSiteId {get;set;}
    public string theURL {get;set;}


    public List<Competitor_Visit__c> getvisits(){
        
        theuRL = URL.getSalesforceBaseUrl().toExternalForm();
        system.debug('test');
        
        List<Competitor_Visit__c> visits ;
        visits = [select id,Name,Date_of_Visit__c,BVSC_Employees_Name__c, recordType.Name from Competitor_Visit__c where Competitor_Site__c =: compSiteId ORDER BY Date_of_Visit__c DESC LIMIT 10  ];
        return visits  ;
    }
    
    
}