force-app/main/default/objects/Gift__c/Gift__c.object-meta.xml
<CustomObject>
    <description>Record of any gifts given to brand representatives</description>
    <label>Gift</label>
    <nameField>
        <label>Gift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <inlineHelpText>The master deal for this gift</inlineHelpText>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Gifts</relationshipLabel>
    <relationshipName>Gifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Gift_Value__c.field-meta.xml
<CustomField>
    <fullName>Gift_Value__c</fullName>
    <inlineHelpText>Enter the value of the gift</inlineHelpText>
    <label>Gift Value</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Gift_Value__c.field-meta.xml
<CustomField>
    <fullName>Gift_Value__c</fullName>
    <inlineHelpText>Enter the value of the gift(s)</inlineHelpText>
    <label>Gift Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the actual village where this opportunity exists</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/deleteGiftsFromFlowSelectionTest.cls
@isTest(seeAllData=true)
global class  deleteGiftsFromFlowSelectionTest{

  private static Account account = new Account();
  private static Village__c village3 = new Village__c();
  private static Opportunity opp = new Opportunity();

        static void setupData(){
            
            account = TestData_Account.setupBrandAccount(1, true);
                  
             //create village 1
             village3 = new Village__c();
             village3.Name = 'TestVillage3';     
             village3.Village_Code__c = 'AA';
			 village3.CertSales_CertPeriod_Cut_Off_Days__c = 1;
			 village3.CertSales_Report_Sales_Grace_Period_Days__c = 1;
             insert village3;
             village3 = [select name, id, Village_Code__c from Village__c where Village_Code__c = 'AA' LIMIT 1];    
             
                
            
            }


        private static testMethod void doTest() {
        
        setupData();
        
        list <deleteGiftsFromFlowSelection.giftDeleteRequest> listofdgffs = new list<deleteGiftsFromFlowSelection.giftDeleteRequest>();
        
        deleteGiftsFromFlowSelection.giftDeleteRequest dgffs = new deleteGiftsFromFlowSelection.giftDeleteRequest();
                
                opp = new Opportunity(name = 'TestOpp', Village__c = village3.Id, AccountId = account.id, 
                CloseDate = system.today().addDays(1), StageName = 'Pipeline');
                insert opp;     
                
                gift__c gift1 = new gift__c();
                gift1.name = 'test';
                gift1.Gift_Value__c = 40.00;
                gift1.deal__c = opp.id;
                insert gift1;
                
                gift__c gift2 = new gift__c();
                gift2.name = 'test';
                gift2.Gift_Value__c = 40.00;
                gift2.deal__c = opp.id;
                insert gift2;
        
                dgffs.Ids = gift1.id;
                                
                listofdgffs.add(dgffs);

                Test.startTest();
                deleteGiftsFromFlowSelection.deleteGifts(listofdgffs);   
                Test.stopTest();
                
                list<Gift__c> finalgifts = [SELECT id FROM Gift__c WHERE deal__c =:opp.id];
                system.assert(finalgifts.size() == 1);
                
                
        
            }
}