force-app/main/default/objects/Master_Budget_Sheet__c/Master_Budget_Sheet__c.object-meta.xml
<CustomObject>
    <label>Master Budget Sheet</label>
    <nameField>
        <label>Master Budget Sheet  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Budget Sheets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Budget_Village__c.field-meta.xml
<CustomField>
    <fullName>Budget_Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Master Budget Sheets</relationshipLabel>
    <relationshipName>Master_Budget_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Creative_Agency_1__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Creative agent to be notified about this MBS</description>
    <inlineHelpText>The Creative agent to be notified about this MBS</inlineHelpText>
    <label>Creative Agency 1</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile_Name__c</field>
            <operation>contains</operation>
            <value>Third Party Community User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Budget_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Creative_Agency_2__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Creative agent to be notified about this MBS</description>
    <inlineHelpText>The Creative agent to be notified about this MBS</inlineHelpText>
    <label>Creative Agency 2</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile_Name__c</field>
            <operation>equals</operation>
            <value>Third Party Community User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Budget_Sheets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Creative_Agency_3__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Agency 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Budget_Sheets2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Creative_Agency_4__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Agency 4</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile_Name__c</field>
            <operation>equals</operation>
            <value>Third Party Community User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Budget_Sheets3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Creative_Agency_5__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Agency 5</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Budget_Sheets4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Creative_Agency_6__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_6__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Agency 6</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Budget_Sheets5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Creative_Agency_7__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_7__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Agency 7</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Budget_Sheets6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Creative_Agency_8__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_8__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Agency 8</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Budget_Sheets7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SubmitToAgencyMBSControllerTest.cls
@isTest(SeeAllData=true)
public class SubmitToAgencyMBSControllerTest {
    
    @isTest
    static void TestEmailMasterBudgetSheet(){
         
        SubmitToAgencyMBSControllerUtility.testSetup();

        Master_Budget_Sheet__c newMBS = [SELECT Id, Name, Creative_Agency_1__c, Creative_Agency_2__c, Creative_Agency_3__c, 
                                        Creative_Agency_4__c, Creative_Agency_5__c, Creative_Agency_6__c, 
                                        Creative_Agency_7__c, Creative_Agency_8__c, Budget_Village__c 
                                        FROM Master_Budget_Sheet__c WHERE Name = 'MBS Test' LIMIT 1];
        
        Test.startTest();
        PageReference pageRef = Page.SubmitToAgencyMasterBudgetSheet;
        Test.setCurrentPage(pageRef);
          
        String newMBSId = newMBS.id;
        Master_Budget_Sheet__c mbs = [SELECT Id, Name, Creative_Agency_1__c, Budget_Village__c FROM Master_Budget_Sheet__c where id=:newMBSId];
        
        ApexPages.currentPage().getParameters().put('id',newMBSId);
        ApexPages.StandardController con = new ApexPages.StandardController(mbs);
        SubmitToAgencyMBSController controller = new SubmitToAgencyMBSController(con);
       
        try{
            controller.sendEmailToUsers(newMBS);  
            controller.shareRecordWithUsers(newMBS); 
        }catch(Exception e){
            system.debug(e);
            System.assert(String.isBlank(String.valueOf(e)));
        }
        Test.stopTest();
    }
}