force-app/main/default/objects/Master_Budget_Sheet__c/Master_Budget_Sheet__c.object-meta.xml
<CustomObject>
    <label>Master Budget Sheet</label>
    <nameField>
        <label>Master Budget Sheet  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Budget Sheets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Budget_Village__c.field-meta.xml
<CustomField>
    <fullName>Budget_Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Master Budget Sheets</relationshipLabel>
    <relationshipName>Master_Budget_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Creative_Agency_1__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Creative agent to be notified about this MBS</description>
    <inlineHelpText>The Creative agent to be notified about this MBS</inlineHelpText>
    <label>Creative Agency 1</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile_Name__c</field>
            <operation>contains</operation>
            <value>Third Party Community User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Budget_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Creative_Agency_2__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Creative agent to be notified about this MBS</description>
    <inlineHelpText>The Creative agent to be notified about this MBS</inlineHelpText>
    <label>Creative Agency 2</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile_Name__c</field>
            <operation>equals</operation>
            <value>Third Party Community User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Budget_Sheets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Creative_Agency_3__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Agency 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Budget_Sheets2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Creative_Agency_4__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Agency 4</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile_Name__c</field>
            <operation>equals</operation>
            <value>Third Party Community User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Budget_Sheets3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Creative_Agency_5__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Agency 5</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Budget_Sheets4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Creative_Agency_6__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_6__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Agency 6</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Budget_Sheets5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Creative_Agency_7__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_7__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Agency 7</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Budget_Sheets6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Creative_Agency_8__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_8__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Agency 8</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Budget_Sheets7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/SubmitToAgencyMBSController.cls
public class SubmitToAgencyMBSController {

    Private Final Master_Budget_Sheet__c mbs;
    
    public SubmitToAgencyMBSController(ApexPages.StandardController stdController){
        
        this.mbs = (Master_Budget_Sheet__c)stdController.getRecord(); 
        
    }
    
    /**
     *  Submit to agency actions regarding the users that are on creative agency fields:
     * 1. Send email to that list of users
     * 2. Share the record with that list of the users
     */
    public pageReference SubmitToAgencyMBS(){
        String theId = ApexPages.currentPage().getParameters().get('id');
        Master_Budget_Sheet__c mbs = [select Id, Name, Creative_Agency_1__c,Creative_Agency_2__c,Creative_Agency_3__c, Creative_Agency_4__c,
                                      Creative_Agency_5__c, Creative_Agency_6__c, Creative_Agency_7__c, Creative_Agency_8__c, Budget_Village__c
                                      from Master_Budget_Sheet__c 
                                      where Id=:theId];
         
        sendEmailToUsers(mbs);
        
        shareRecordWithUsers(mbs);
           
        PageReference pageRef = new PageReference ('/' + theId);
        pageRef.setRedirect(true);
        
    
        return pageRef;        
    }   
    
    public void sendEmailToUsers(Master_Budget_Sheet__c mbs){
        List<Messaging.SingleEmailMessage> allMessag = new List<Messaging.SingleEmailMessage>();
        List<String> sendTo = new List<String>();
		Village__c bv;
        
        if(mbs.Budget_Village__c!=null){
        	bv = [select Id, Name from Village__c where Id =:mbs.Budget_Village__c];
    	}
        
        if(mbs.Creative_Agency_1__c != null){ 
            sendTo.add(mbs.Creative_Agency_1__c);  
        }

        if(mbs.Creative_Agency_2__c != null){ 
            sendTo.add(mbs.Creative_Agency_2__c);  
        }

        if(mbs.Creative_Agency_3__c != null){ 
            sendTo.add(mbs.Creative_Agency_3__c);  
        }

        if(mbs.Creative_Agency_4__c != null){ 
            sendTo.add(mbs.Creative_Agency_4__c);  
        }
        
        if(mbs.Creative_Agency_5__c != null){ 
            sendTo.add(mbs.Creative_Agency_5__c);  
        }
        
        if(mbs.Creative_Agency_6__c != null){ 
            sendTo.add(mbs.Creative_Agency_6__c);  
        }
        
        if(mbs.Creative_Agency_7__c != null){ 
            sendTo.add(mbs.Creative_Agency_7__c);  
        }
        
        if(mbs.Creative_Agency_8__c != null){ 
            sendTo.add(mbs.Creative_Agency_8__c);  
        }

        if(sendTo.size() != 0 && sendTo != NULL){
            
            Network myNetwork = [SELECT Id FROM Network WHERE Name = '3rdParty'];
            ConnectApi.Community  myCommunity = ConnectApi.Communities.getCommunity(myNetwork.id);

            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setBccAddresses(sendTo);

            mail.setSubject('Email Master Budget Sheet');
            
            
            String body = '<br/>';
                body +='Please go to the Salesforce third party portal for Value Retail.<br/>';
            if(bv != null){
                body +='A new Master Budget Sheet has been submitted by '  + bv.Name +  '<br/>';
            } else {
                body +='A new Master Budget Sheet has been submitted.<br/>';
            }
                body += mbs.Name +  '<br/>';
                body += myCommunity.siteUrl +'/s/master-budget-sheet/'+mbs.Id +'';
                


            mail.setHtmlBody(body);
            mail.setSaveAsActivity(false); 
            allMessag.add(mail);
        
        	Messaging.sendEmail(allMessag);
        	System.debug('user mail id '+allMessag);       
        }       
    }    
    
    public void shareRecordWithUsers(Master_Budget_Sheet__c mbs){

        List<Id> userIdList = new List<Id>();
    
        if(mbs.Creative_Agency_1__c != null){ 
			userIdList.add(mbs.Creative_Agency_1__c);
        }

        if(mbs.Creative_Agency_2__c != null){ 
            userIdList.add(mbs.Creative_Agency_2__c);  
        }

        if(mbs.Creative_Agency_3__c != null){ 
            userIdList.add(mbs.Creative_Agency_3__c);  
        }

        if(mbs.Creative_Agency_4__c != null){ 
            userIdList.add(mbs.Creative_Agency_4__c);  
        }
        
        if(mbs.Creative_Agency_5__c != null){ 
            userIdList.add(mbs.Creative_Agency_5__c);  
        }
        
        if(mbs.Creative_Agency_6__c != null){ 
            userIdList.add(mbs.Creative_Agency_6__c);  
        }
        
        if(mbs.Creative_Agency_7__c != null){ 
            userIdList.add(mbs.Creative_Agency_7__c);  
        }
        
        if(mbs.Creative_Agency_8__c != null){ 
            userIdList.add(mbs.Creative_Agency_8__c);  
        }  
                      

        for(integer i = 0; i<userIdList.size();i++){
            Master_Budget_Sheet__Share mbsShare = new Master_Budget_Sheet__Share(); 
  			mbsShare.ParentId= mbs.id;
            mbsShare.UserOrGroupId = userIdList.get(i);  
            mbsShare.AccessLevel = 'Edit';
            Database.SaveResult sr = Database.insert(mbsShare,false);
        }
         
    }
    
}