force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the opportunity that lead to the creation of this contract</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Size_GEA__c.field-meta.xml
<CustomField>
    <fullName>Size_GEA__c</fullName>
    <formula>IF( ISPICKVAL( Size_Metric__c , &quot;sq.m&quot;),  Unit_Size__c ,  Unit_Size_sqft__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Size_GEA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <formula>Opportunity__r.Unit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unit on the Opportunity</inlineHelpText>
    <label>Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <formula>TEXT( Opportunity__r.Unit__r.Unit_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If a Unit has been assigned to this contract the availability status of the unit is retrieved from the Unit record itself</inlineHelpText>
    <label>Unit Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the village for this lease</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <formula>Village__r.Village_Code__c</formula>
    <inlineHelpText>The 2 digit village code pulled from the Village object, this is used to select the appropriate contract approval process</inlineHelpText>
    <label>Village Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Auto_Sync_Stages__c/Deal_Auto_Sync_Stages__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Deal Auto Sync Stages</label>
</CustomObject>

force-app/main/default/objects/Deal_Auto_Sync_Stages__c/fields/Closed_Success__c.field-meta.xml
<CustomField>
    <fullName>Closed_Success__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether reaching this stage defines a positive outcome for the deal.</description>
    <inlineHelpText>Indicates whether reaching this stage defines a positive outcome for the deal.</inlineHelpText>
    <label>Closed Success</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Auto_Sync_Stages__c/fields/Default_Sync_Value__c.field-meta.xml
<CustomField>
    <fullName>Default_Sync_Value__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The default auto synch value to set on the deal when the deal is set to this stage. The auto synch value determines whether Deal data will be automatically copied to the associated village presence during the deal process.</description>
    <inlineHelpText>The default auto synch value to set on the deal when the deal is set to this stage. The auto synch value determines whether Deal data will be automatically copied to the associated village presence during the deal process.</inlineHelpText>
    <label>Default Sync Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Auto_Sync_Stages__c/fields/Stage_Name__c.field-meta.xml
<CustomField>
    <fullName>Stage_Name__c</fullName>
    <label>Stage Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Exit_Date__c.field-meta.xml
<CustomField>
    <fullName>Exit_Date__c</fullName>
    <inlineHelpText>Enter the date that the brand is expected to exit if budgetted or not</inlineHelpText>
    <label>Actual Exit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ideal_Size__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Size__c</fullName>
    <inlineHelpText>If a specific unit is not nominated then use this field to specify the ideal size this brand will be using in the size metric specific to the village</inlineHelpText>
    <label>Ideal Size</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Date__c</fullName>
    <inlineHelpText>Enter the Open date if this opportunity has been budgetted or not</inlineHelpText>
    <label>Actual Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Return_Local__c.field-meta.xml
<CustomField>
    <fullName>Projected_Return_Local__c</fullName>
    <inlineHelpText>The Projected Return based on the Sales and Income Projections in Local currency.</inlineHelpText>
    <label>1st Year Projected Income % (Local)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Sales_Yield_Local__c.field-meta.xml
<CustomField>
    <fullName>Projected_Sales_Yield_Local__c</fullName>
    <inlineHelpText>The Annualized Sales Yield in Village Currency (per Sq.ft for Bicester and per Sq. mtr for all other villages)</inlineHelpText>
    <label>1st Year Projected Sales Yield (Local)</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>Signed_Date__c</fullName>
    <inlineHelpText>Enter or select the date the deal was signed from the pop up calendar</inlineHelpText>
    <label>Actual Signed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Unit assigned to this opportunity, this is synchronized with the Unit on the Contract when the Unit is formally committed to the brand</inlineHelpText>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Village__c</field>
            <operation>equals</operation>
            <valueField>$Source.Village__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the actual village where this opportunity exists</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Exit.recordType-meta.xml
<RecordType>
    <fullName>Exit</fullName>
    <active>true</active>
    <businessProcess>Exit Process</businessProcess>
    <description>Deals for Brands that are exiting the village</description>
    <label>Exit</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Relocation.recordType-meta.xml
<RecordType>
    <fullName>Relocation</fullName>
    <active>true</active>
    <businessProcess>Relocate Deal Process</businessProcess>
    <description>A deal to relocate a trading brand to a new unit. Including a temporary relocation during shop refit</description>
    <label>Relocation</label>
</RecordType>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the detail of all units in VR Villages</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Size_GEA__c.field-meta.xml
<CustomField>
    <fullName>Size_GEA__c</fullName>
    <inlineHelpText>Enter the Gross External Area (GEA) of the unit in square meters</inlineHelpText>
    <label>Size (GEA)</label>
    <precision>13</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <inlineHelpText>Select the value that best describes the status of the Unit</inlineHelpText>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Suggested</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>Refit</fullName>
            </value>
            <value>
                <fullName>Do not use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>...</description>
    <inlineHelpText>Select the Village where this unit lives</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/B2B_Chatter_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>B2B_Chatter_Group_Name__c</fullName>
    <description>Defines the chatter group to post to when an event is created which mentions the village.</description>
    <inlineHelpText>Defines the chatter group to post to when an event is created which mentions the village.</inlineHelpText>
    <label>B2B Chatter Group Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Projected_Return_Local__c.field-meta.xml
<CustomField>
    <fullName>Projected_Return_Local__c</fullName>
    <label>Return (Local)</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Projected_Sales_Yield_Local__c.field-meta.xml
<CustomField>
    <fullName>Projected_Sales_Yield_Local__c</fullName>
    <label>Sales Yield (Local)</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/updateVillagePresenceControllerTest.cls
@isTest
private class updateVillagePresenceControllerTest {

	private static Account account = new Account();
	private static Opportunity opportunity1 = new Opportunity();
	private static Opportunity opportunity2 = new Opportunity();
	private static Opportunity opportunity3 = new Opportunity();
	private static Opportunity opportunity4 = new Opportunity();
	private static Village__c village = new Village__c();
	private static Unit__c unit = new Unit__c();
	private static Contract contract = new Contract();
	

	// Get Opportunity record type Ids
	private static final id exitedRecordTypeID = Schema.SObjectType.Opportunity.RecordTypeInfosByName.get('Exit').RecordTypeId;
	private static final id reviewRecordTypeID = Schema.SObjectType.Opportunity.RecordTypeInfosByName.get('Contract Change').RecordTypeId;
	private static final id relocationRecordTypeID = Schema.SObjectType.Opportunity.RecordTypeInfosByName.get('Relocation').RecordTypeId;
	private static final id newRecordTypeID = Schema.SObjectType.Opportunity.RecordTypeInfosByName.get('New Brand').RecordTypeId;
		
	static void setUpData(){

		account = TestData_Account.setupBrandAccount(1, true);
						
	 	village = new Village__c();
	 	village.Name = 'TestVillage';
	 	village.Village_Code__c = 'OO';
        village.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		village.CertSales_Report_Sales_Grace_Period_Days__c = 1; 
	 	insert village;
		village = [select name, id, B2B_Chatter_Group_Name__c, Village_Code__c from Village__c where Village_Code__c = 'OO' LIMIT 1];
		
		unit = new Unit__c(Name='TU1', Village__c = village.Id, size_GEA__c = 200,  Unit_Status__c = 'Available');
		insert unit;
		unit = 	[select Id, Name from Unit__c where name = 'TU1'];
		
		// New Deal
		opportunity1 = new Opportunity(name = 'TestOpp1', Village__c = village.Id, AccountId = account.id, RecordTypeId = newRecordTypeID,
										CloseDate = system.today().addDays(1), StageName = 'Pipeline', unit__c = unit.id,
										Projected_Sales_Yield_Local__c = 100000, Projected_Return_Local__c =12 , Ideal_Size__c = 100);
		insert opportunity1;			
		OpportunityTriggerHelper.hasRun = false;
		
	//	contract.StartDate = system.today();		
	//	contract.AccountId = account.Id;
	//	contract.Opportunity__c = opportunity1.Id;
	//	insert contract;
		
		// Review Deal
		opportunity2 = new Opportunity(name = 'TestOpp2', Village__c = village.Id, AccountId = account.id, RecordTypeId = reviewRecordTypeID,
										CloseDate = system.today().addDays(10), StageName = 'Pipeline', unit__c = unit.id,
										Projected_Sales_Yield_Local__c = 100000, Projected_Return_Local__c =12 , Ideal_Size__c = 100,
										Open_Date__c = system.today().addDays(-10), Signed_Date__c = system.today().addDays(-10));
		insert opportunity2;
		OpportunityTriggerHelper.hasRun = false;	
		
		//Terminated Deal
		opportunity3 = new Opportunity(name = 'TestOpp3', Village__c = village.Id, AccountId = account.id, RecordTypeId = exitedRecordTypeID,
										CloseDate = system.today().addDays(1), StageName = 'Pipeline', unit__c = unit.id,
										Projected_Sales_Yield_Local__c = 100000, Projected_Return_Local__c =12 , Ideal_Size__c = 100,
										Open_Date__c = system.today().addDays(-10), Exit_Date__c = system.today().addDays(+10));
		insert opportunity3;
		OpportunityTriggerHelper.hasRun = false;
		
		Deal_Auto_Sync_Stages__c defaultSettings = new Deal_Auto_Sync_Stages__c (Name = 'Pipeline', Stage_Name__c = 'Pipeline', Default_Sync_Value__c = false, Closed_Success__c = true);
		insert defaultSettings;
	}
	
    static testMethod void testFromController() {
    	
    	setupData();

    	// Test new deal
    	  
  		opportunity1 = [select Id, name, StageName,  Projected_Sales_Yield_Local__c, Projected_Return_Local__c,
    					Projected_Income_Yield__c, Sales_Rating__c, Income_Rating__c, village_presence__c
    					from Opportunity where Id = :opportunity1.Id]; 
    	
    	PageReference pg = new PageReference('/apex/updateVillagePresence');
    	pg.getParameters().put('stage', opportunity1.StageName);
    	pg.getParameters().put('Id', opportunity1.Id);
    	Test.setCurrentPage(pg);
    					    	
    	Apexpages.Standardcontroller stdController = new Apexpages.Standardcontroller(opportunity1);
		updateVillagePresenceController controller = new updateVillagePresenceController(stdController);
		
		test.startTest();
			
		controller = new updateVillagePresenceController();
		PageReference pg1 = controller.saveVillagePresence();

    	
    	Village_Presence__c vp1 = [select Id, Name, Projected_Sales_Yield_Local__c, Projected_Return_Local__c,
    									Projected_Income_Yield__c, Latest_Review_Deal__c, New_Deal__c, Exit_Deal__c, 
    									Sales_Rating__c, Income_Rating__c 
    									from Village_Presence__c
    									where id = :opportunity1.village_presence__c ];
		

		system.assertEquals(vp1.New_Deal__c, opportunity1.Id);
		system.assertEquals(vp1.Latest_Review_Deal__c, null);
		system.assertEquals(vp1.Exit_Deal__c, null);		

    	// Test review deal
    	
    	pg.getParameters().put('stage', opportunity2.StageName);
    	pg.getParameters().put('Id', opportunity2.Id);
    	
   		opportunity2 = [select Id, name, StageName, Projected_Sales_Yield_Local__c, Projected_Return_Local__c,
    					Projected_Income_Yield__c, Sales_Rating__c, Income_Rating__c, village_presence__r.Id
    					from Opportunity where Id = :opportunity2.Id];     	
    	
    	Apexpages.Standardcontroller stdController2 = new Apexpages.Standardcontroller(opportunity2);
		updateVillagePresenceController controller2 = new updateVillagePresenceController(stdController2);

    	pg = new PageReference('/apex/updateVillagePresence');
    	pg.getParameters().put('stage', opportunity2.StageName);
    	pg.getParameters().put('Id', opportunity2.Id);
    	Test.setCurrentPage(pg);

		controller2 = new updateVillagePresenceController();
		PageReference pg2 = controller2.saveVillagePresence();


    	Village_Presence__c vp2 = [select Id, Name, Projected_Sales_Yield_Local__c, Projected_Return_Local__c,
    									Projected_Income_Yield__c, Latest_Review_Deal__c, New_Deal__c, Exit_Deal__c, 
    									Sales_Rating__c, Income_Rating__c 
    									from Village_Presence__c
    									where id = :opportunity2.village_presence__c ];
		

		system.assertEquals(vp2.New_Deal__c, opportunity1.Id);
		system.assertEquals(vp2.Latest_Review_Deal__c, opportunity2.Id);
		system.assertEquals(vp2.Exit_Deal__c, null);


		
		// Test exit deal
		
		opportunity3 = [select Id, name,  Projected_Sales_Yield_Local__c, Projected_Return_Local__c,
    					Projected_Income_Yield__c, Sales_Rating__c, Income_Rating__c, village_presence__r.Id
    					from Opportunity where Id = :opportunity3.Id];      					    					    									    									     							
		
    	Apexpages.Standardcontroller stdController3 = new Apexpages.Standardcontroller(opportunity3);
		updateVillagePresenceController controller3 = new updateVillagePresenceController(stdController3);
		PageReference pg3 = controller3.saveVillagePresence();
		test.setCurrentPageReference(pg3);
    	
    	Village_Presence__c vp3 = [select Id, Name, Projected_Sales_Yield_Local__c, Projected_Return_Local__c,
    									Projected_Income_Yield__c, Latest_Review_Deal__c, New_Deal__c, Exit_Deal__c, 
    									Sales_Rating__c, Income_Rating__c 
    									from Village_Presence__c
    									where id = :opportunity3.village_presence__c ];
		

		system.assertEquals(vp3.New_Deal__c, opportunity1.Id);
		system.assertEquals(vp3.Latest_Review_Deal__c, opportunity2.Id);
		system.assertEquals(vp3.Exit_Deal__c, opportunity3.Id);

		pg3 = controller3.cancelUpdate();

		test.stopTest();
	
    }


	static testMethod void testBulkCall() {
    	
    	setupData();

		opportunity1 = [select Id, name,  Projected_Sales_Yield_Local__c, Projected_Return_Local__c,
    					Projected_Income_Yield__c, Sales_Rating__c, Income_Rating__c, village_presence__r.Id
    					from Opportunity where Id = :opportunity1.Id];    	   
   
   		opportunity2 = [select Id, name,  Projected_Sales_Yield_Local__c, Projected_Return_Local__c,
    					Projected_Income_Yield__c, Sales_Rating__c, Income_Rating__c, village_presence__r.Id
    					from Opportunity where Id = :opportunity2.Id];  
    					
		opportunity3 = [select Id, name,  Projected_Sales_Yield_Local__c, Projected_Return_Local__c,
    					Projected_Income_Yield__c, Sales_Rating__c, Income_Rating__c, village_presence__r.Id
    					from Opportunity where Id = :opportunity3.Id];  
    					    					
    	set<Id> oppIdList = new set<Id>();
    	oppIdList.add(opportunity1.Id);
    	oppIdList.add(opportunity2.Id);
    	oppIdList.add(opportunity3.Id);
    	
    	list<Id> vpIdList = new list<Id>();
    	vpIdList.add(opportunity1.village_presence__c);
    	vpIdList.add(opportunity2.village_presence__c);
    	vpIdList.add(opportunity3.village_presence__c);    	    									
		
		updateVillagePresenceController controller = new updateVillagePresenceController();
		
		string bulkCall = updateVillagePresenceController.updateVillagePresenceList(oppIdList);    									
 
     	map<Id, Village_Presence__c> vpMap = new Map<id, Village_Presence__c> ([select Id, Name, Projected_Sales_Yield_Local__c, Projected_Return_Local__c,
    									Projected_Income_Yield__c, Latest_Review_Deal__c, New_Deal__c, Exit_Deal__c, Sales_Rating__c,
    									Income_Rating__c 
    									from Village_Presence__c
    									where id in :vpIdList]);
 
 
		system.assertEquals(vpMap.get(opportunity1.village_presence__c).New_Deal__c, opportunity1.Id);
		system.assertEquals(vpMap.get(opportunity1.village_presence__c).Latest_Review_Deal__c, opportunity2.Id);
		system.assertEquals(vpMap.get(opportunity1.village_presence__c).Exit_Deal__c, opportunity3.Id);	
    
	}							

    
	static testMethod void  testErrors(){
		
		setupData();
		
        Test.startTest();
		// temporarily switch off validation rules to create invalid data
		Global_Object_Validation__c settings = Global_Object_Validation__c.getInstance(userinfo.getProfileId());
		if (settings != null) {
			settings.Deal_Validations_Active__c = false;
		} else {
			settings = new Global_Object_Validation__c();
			settings.Deal_Validations_Active__c = false;
		}
		upsert settings;
		
		opportunity1 = [select Id, name,  Projected_Sales_Yield_Local__c, Projected_Return_Local__c,
				Projected_Income_Yield__c, Sales_Rating__c, Income_Rating__c, village_presence__r.Id
				from Opportunity where Id = :opportunity1.Id];
				
		opportunity1.Projected_Sales_Yield_Local__c = null;
		update opportunity1;
		
		settings.Deal_Validations_Active__c = true;
		upsert settings;

        Apexpages.Standardcontroller stdController = new Apexpages.Standardcontroller(opportunity1);
        updateVillagePresenceController controller = new updateVillagePresenceController(stdController);	
        try {
            test.setCurrentPageReference(controller.saveVillagePresence());
        } catch (exception e){
            // do nothing 
        }

 		List<Apexpages.Message> msgs = ApexPages.getMessages();
	    boolean b = false;
		for(Apexpages.Message msg:msgs){
			if (msg.getDetail().contains('The Village presence could not be saved')) b = true;
	    }
	   // system.assert(b);    
		
    
    	// test error with bulk call

        opportunity1 = [select Id, name,  Projected_Sales_Yield_Local__c, Projected_Return_Local__c,
                        Projected_Income_Yield__c, Sales_Rating__c, Income_Rating__c, village_presence__r.Id
                        from Opportunity where Id = :opportunity1.Id];    	   
   
   		opportunity2 = [select Id, name,  Projected_Sales_Yield_Local__c, Projected_Return_Local__c,
    					Projected_Income_Yield__c, Sales_Rating__c, Income_Rating__c, village_presence__r.Id
    					from Opportunity where Id = :opportunity2.Id];  
    					
		opportunity3 = [select Id, name,  Projected_Sales_Yield_Local__c, Projected_Return_Local__c,
    					Projected_Income_Yield__c, Sales_Rating__c, Income_Rating__c, village_presence__r.Id
    					from Opportunity where Id = :opportunity3.Id];  
    					    					
    	set<Id> oppIdList = new set<Id>();
    	oppIdList.add(opportunity1.Id);
    	oppIdList.add(opportunity2.Id);
    	oppIdList.add(opportunity3.Id);
   											
		controller = new updateVillagePresenceController();
		
		string bulkCall = updateVillagePresenceController.updateVillagePresenceList(oppIdList);    			
        system.debug ( ' @@@@@@@@@@@@@@@  BULK CALL ..  ' + bulkCall);
    	system.debug(' @@@@@@@@@@@@@@@ END');
        Test.stopTest();
 //       system.assert(bulkCall.contains('Deal Update Error'));
        

	}    
}