force-app/main/default/objects/Contract/fields/Size_GEA__c.field-meta.xml
<CustomField>
    <fullName>Size_GEA__c</fullName>
    <formula>IF( ISPICKVAL( Size_Metric__c , &quot;sq.m&quot;),  Unit_Size__c ,  Unit_Size_sqft__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Size_GEA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <formula>Opportunity__r.Unit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unit on the Opportunity</inlineHelpText>
    <label>Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <formula>TEXT( Opportunity__r.Unit__r.Unit_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If a Unit has been assigned to this contract the availability status of the unit is retrieved from the Unit record itself</inlineHelpText>
    <label>Unit Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the village for this lease</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <formula>Village__r.Village_Code__c</formula>
    <inlineHelpText>The 2 digit village code pulled from the Village object, this is used to select the appropriate contract approval process</inlineHelpText>
    <label>Village Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Tenant_Break_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Tenant_Break_Date__c</fullName>
    <description>The first date in which the Tenant can break the contract.</description>
    <inlineHelpText>The first date in which the Tenant can break the contract.</inlineHelpText>
    <label>Tenant Break Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ideal_Size__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Size__c</fullName>
    <inlineHelpText>If a specific unit is not nominated then use this field to specify the ideal size this brand will be using in the size metric specific to the village</inlineHelpText>
    <label>Ideal Size</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Return_Local__c.field-meta.xml
<CustomField>
    <fullName>Projected_Return_Local__c</fullName>
    <inlineHelpText>The Projected Return based on the Sales and Income Projections in Local currency.</inlineHelpText>
    <label>1st Year Projected Income % (Local)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Sales_Yield_Local__c.field-meta.xml
<CustomField>
    <fullName>Projected_Sales_Yield_Local__c</fullName>
    <inlineHelpText>The Annualized Sales Yield in Village Currency (per Sq.ft for Bicester and per Sq. mtr for all other villages)</inlineHelpText>
    <label>1st Year Projected Sales Yield (Local)</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Unit assigned to this opportunity, this is synchronized with the Unit on the Contract when the Unit is formally committed to the brand</inlineHelpText>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Village__c</field>
            <operation>equals</operation>
            <valueField>$Source.Village__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the actual village where this opportunity exists</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the detail of all units in VR Villages</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Size_GEA__c.field-meta.xml
<CustomField>
    <fullName>Size_GEA__c</fullName>
    <inlineHelpText>Enter the Gross External Area (GEA) of the unit in square meters</inlineHelpText>
    <label>Size (GEA)</label>
    <precision>13</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <inlineHelpText>Select the value that best describes the status of the Unit</inlineHelpText>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Suggested</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>Refit</fullName>
            </value>
            <value>
                <fullName>Do not use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>...</description>
    <inlineHelpText>Select the Village where this unit lives</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AccountViewerTest.cls
@isTest
private class AccountViewerTest {

	private static Account account = new Account();
	private static Account childAccount = new Account();
	private static Village__c village = new Village__c();
	private static Unit__c unit = new Unit__c();
	private static Opportunity deal = new Opportunity();
    private static final id reviewRecordTypeID = Schema.SObjectType.Opportunity.RecordTypeInfosByName.get('Contract Change').RecordTypeId;
    	
    static void setupData(){
    
		account = TestData_Account.setupGroupAccount(1, true);	
		childAccount = 	TestData_Account.setupBrandAccount(2, false);
		childAccount.ParentId = account.Id;
		insert childAccount;
					
 		//create village 1
 		village = new Village__c();
 		village.Name = 'TestVillage1'; 		
 		village.Village_Code__c = 'AA';
		village.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		village.CertSales_Report_Sales_Grace_Period_Days__c = 1; 
 		insert village;
		village = [select name, id, Village_Code__c from Village__c where Village_Code__c = 'AA' LIMIT 1];   	

		unit = new Unit__c(Name='TU1', Village__c = village.Id, size_GEA__c = 200,  Unit_Status__c = 'Available');
		insert unit;
		unit = 	[select Id, Name from Unit__c where name = 'TU1'];
		
	// New Deal
		deal = new Opportunity(name = 'TestOpp1', Village__c = village.Id, AccountId = childAccount.id, RecordTypeId = reviewRecordTypeID,
										CloseDate = system.today().addDays(1), StageName = 'Pipeline', unit__c = unit.id, 
										Contract_Tenant_Break_Date__c = system.today().addDays(20), 
										Projected_Sales_Yield_Local__c = 100000, Projected_Return_Local__c =12 , Ideal_Size__c = 100);
		insert deal;
		
    
    }
	
	static testMethod void unitTest(){
		
		setupData();
		
    	PageReference pg = new PageReference('/apex/AccountTreeView');
    	pg.getParameters().put('Id', account.Id);
    	Test.setCurrentPage(pg);
    					    	
    			
		test.startTest();
		set<Id> oppIdList = new set<Id>();
    	oppIdList.add(deal.Id);

		string vpUpdate = updateVillagePresenceController.updateVillagePresenceList(oppIdList);	
		    	
    	Apexpages.Standardcontroller stdController = new Apexpages.Standardcontroller(account);
		AccountViewer controller = new AccountViewer(stdController);
		
					
		test.stopTest();
		
		string tree = controller.AccountTree;
		
		system.assert(tree.indexOf('"VillageName":"TestVillage1"') > -1);
		system.assert(tree.indexOf('"ProjectedSalesYieldLocalConverted":"100000.00"') > -1);
		system.assert(tree.indexOf('"Unit":"TU1"') > -1);
		
	}
}