force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <description>This object will save all information related to the Business Units...</description>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Unit__c/fields/Business_Unit_Code__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Code__c</fullName>
    <description>.</description>
    <label>Business Unit Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Unit__c/fields/OraclePrimaryBusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>OraclePrimaryBusinessUnit__c</fullName>
    <description>.</description>
    <label>OraclePrimaryBusinessUnit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>True</fullName>
            </value>
            <value>
                <fullName>False</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Unit__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>.</description>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Business Units</relationshipLabel>
    <relationshipName>Business_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/Business_Unit_Code1__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Code1__c</fullName>
    <label>Business Unit Code1</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Business_Unit_Code2__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Code2__c</fullName>
    <label>Business Unit Code2</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>...</description>
    <inlineHelpText>Select the Village is this campaign related to</inlineHelpText>
    <label>Village</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>notEqual</operation>
            <value>Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Village Campaign</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/BusinessUnitCodeUpdateHandler.cls
public class BusinessUnitCodeUpdateHandler {

    public static Map <Id, List<Business_Unit__c>> bUnitsMap;

    public static void updateBusinessUnitCode(Marketing_Campaign__c mCamp){

        if (bUnitsMap == null) {
            getBusinessUnits();
        }

        List <Business_Unit__c> villageBusinessUnits = bUnitsMap.get(mCamp.Village__c);
        
        if (villageBusinessUnits != null) {
            if(villageBusinessUnits.size()>0){
                mcamp.Business_Unit_Code1__c = villageBusinessUnits[0].Business_Unit_Code__c;
            }
            if(villageBusinessUnits.size()>1){
                mcamp.Business_Unit_Code2__c = villageBusinessUnits[1].Business_Unit_Code__c;
            }
        }
    }

    public static void getBusinessUnits () {
        Business_Unit__c[] bUnits = [Select id, Business_Unit_Code__c,OraclePrimaryBusinessUnit__c, Village__c from Business_Unit__c];
        bUnitsMap = new Map <Id, List <Business_Unit__c>> ();
        for (Business_Unit__c bUnit : bUnits) {
            if(bUnitsMap.containsKey(bUnit.Village__c)) {
                bUnitsMap.get(bUnit.Village__c).add(bUnit);
            } else {
                bUnitsMap.put(bUnit.Village__c, new List <Business_Unit__c> {bUnit});
            }
        }
    }
}