force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <description>This object will save all information related to the Business Units...</description>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Unit__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>.</description>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Business Units</relationshipLabel>
    <relationshipName>Business_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/Business_Function__c.field-meta.xml
<CustomField>
    <fullName>Business_Function__c</fullName>
    <description>The business area that this activity is aligned with.....</description>
    <inlineHelpText>The business area that this activity is aligned with</inlineHelpText>
    <label>Business Function</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Functions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <inlineHelpText>Marketing Channel</inlineHelpText>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Campaign Support</fullName>
            </value>
            <value>
                <fullName>Collateral</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Non-campaign</fullName>
            </value>
            <value>
                <fullName>Partnerships</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Village Services</fullName>
            </value>
            <value>
                <fullName>VIP</fullName>
            </value>
            <value>
                <fullName>Visual Merchandising</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter a End date where you expect the activity to stop impacting footfall/Sales in the Village.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Expenditure_Category__c.field-meta.xml
<CustomField>
    <fullName>Expenditure_Category__c</fullName>
    <formula>&apos;MKT&apos;+&apos;-&apos;+TEXT(Channel__c)</formula>
    <label>Expenditure Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Expenditure_Type__c.field-meta.xml
<CustomField>
    <fullName>Expenditure_Type__c</fullName>
    <formula>&apos;MKT&apos;+&apos;-&apos;+TEXT(Sub_Channel__c)</formula>
    <label>Expenditure Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Marketing_Activity_Ref__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity_Ref__c</fullName>
    <displayFormat>MA-{000000}</displayFormat>
    <externalId>true</externalId>
    <label>Marketing Activity Ref</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <description>....</description>
    <label>Marketing Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You cannot link an activity to a &apos;Cancelled&apos;  Campaign.</errorMessage>
        <filterItems>
            <field>Marketing_Campaign__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Activities</relationshipLabel>
    <relationshipName>Marketing_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Oracle_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Project_Id__c</fullName>
    <description>Text field created to store the project (Marketing Campaig) Id. This way, when the field is populated, the Marketing Activity will run and will send the objects to the Finance system (formula fields wouldn&apos;t trigger the execution of the Apex Trigger)</description>
    <label>Oracle Project Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Oracle_Secondary_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Secondary_Project_Id__c</fullName>
    <description>Text field created to store the project (Marketing Campaig) Id. This way, when the field is populated, the Marketing Activity will run and will send the objects to the Finance system (formula fields wouldn&apos;t trigger the execution of the Apex Trigger)</description>
    <label>Oracle Secondary Project Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Oracle_Secondary_Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Secondary_Task_Id__c</fullName>
    <label>Oracle Secondary Task Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Oracle_Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Task_Id__c</fullName>
    <label>Oracle Primary Task Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter a date where you expect the activity to impact footfall/Sales in the Village. This is not necessarily the date the email is being sent</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Transfer_To_Oracle__c.field-meta.xml
<CustomField>
    <fullName>Transfer_To_Oracle__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Allows the activity to be transferred to Oracle Projects</description>
    <inlineHelpText>Allow the activity to be transferred to Oracle Projects</inlineHelpText>
    <label>Transfer To Oracle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter the End Date of the Campaign</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Oracle_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Project_Id__c</fullName>
    <label>Oracle Primary Project Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Oracle_Secondary_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Secondary_Project_Id__c</fullName>
    <label>Oracle Secondary Project Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter the Start Date of the Campaign</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Transfer_To_Oracle__c.field-meta.xml
<CustomField>
    <fullName>Transfer_To_Oracle__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Allows the Campaign data to be sent to Oracle Projects</description>
    <inlineHelpText>Allow the Campaign data to be sent to Oracle Projects</inlineHelpText>
    <label>Transfer To Oracle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>...</description>
    <inlineHelpText>Select the Village is this campaign related to</inlineHelpText>
    <label>Village</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>notEqual</operation>
            <value>Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Village Campaign</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MarketingActivityUpdateBatchCallout.cls
global class MarketingActivityUpdateBatchCallout implements Database.Batchable<sObject>, Database.AllowsCallouts{

    Set<Id> maUpdateid = new Set<Id>();

    public MarketingActivityUpdateBatchCallout(Set<Id> maUpdateid){
        this.maUpdateid = maUpdateid;
    }

    public class MarketingActivityDetails
    {
        public List<Activity> Activities = new List <Activity> ();
    }

    public class Activity{
        public Id SalesforceId;
        public DateTime SalesforceDateTime;
        public String ActivityName;
        public String MarketingActivityNumber;
        public Date StartDate;
        public Date EndDate;
        public String ActivityStatus;
        public String BusinessFunction;
        public String Channel;
        public String SubChannel;
        public String ExpenditureCategory;
        public String ExpenditureType;
        public Village village ;
        public BusinessUnit[] BusinessUnit;
        public Activity(Id Sid, DateTime aSdateTime, String aName, String aNumber, Date sDate, Date eDate, String aStatus, String aBFunction, String aChannel, String aSubChannel,String ECategory, String EType, Village vlgRecords, BusinessUnit[] bulist){
            this.SalesforceId = Sid;
            this.SalesforceDateTime = aSdateTime;
            this.ActivityName = aName;
            this.MarketingActivityNumber = aNumber;
            this.StartDate = sDate;
            this.EndDate = eDate;
            this.ActivityStatus = aStatus;
            this.BusinessFunction = aBFunction;
            this.Channel = aChannel;
            this.SubChannel = aSubChannel;
            this.ExpenditureCategory = ECategory;
            this.ExpenditureType = EType;
            this.village = vlgRecords;
            this.BusinessUnit = bulist;
        }
    }
    public class Village{
        public String VillageCode;
        public String VillageName;
    }
    public class BusinessUnit{
        public String BusinessUnitCode;
        public String BusinessUnitName;
        public String OraclePrimaryBusinessUnit;
        public String OracleProjectId;
        public String OracleTaskId;

    }

    global List<Marketing_Activity__c> start(Database.BatchableContext BC){
        return [Select Oracle_Project_Id__c, Oracle_Secondary_Project_Id__c, id,Oracle_Task_Id__c, Oracle_Secondary_Task_Id__c,Transfer_To_Oracle__c,LastModifiedBy.Name, Expenditure_Category__c, Expenditure_Type__c, Marketing_Campaign__c, Marketing_Campaign__r.Village__c,Marketing_Campaign__r.Village__r.Name, CreatedDate, LastModifiedDate, Name, Marketing_Activity_Ref__c, Start_Date__c, End_Date__c, Status__c, Business_Function__c, Channel__c, Sub_Channel__c,MA_OracleSessionId__c,Error_Message__c  from Marketing_Activity__c where id IN : maUpdateid ORDER BY Marketing_Campaign__c];
    }

    global void execute(Database.BatchableContext BC, List<Marketing_Activity__c> maList){

        List<Marketing_Activity__c> matemplist = new  List<Marketing_Activity__c>();

        string endPointRequestURL = System.Label.MarketingActivityDIEndPoint;
        string apimkey = System.Label.MarketingFinanceIntegrationAPIMKey;
        MFIntegrationLogger logger = new MFIntegrationLogger ();
        logger.setMarketingActivityAsRelatedObject();

        Map <Id, Village__c> vRcrdMap = new Map <Id, Village__c>([select Id, Name, Village_Code__c from Village__c]);
        Map <Id, List <Business_Unit__c>> buByVillage = new Map <Id, List <Business_Unit__c>> ();

        for(Business_Unit__c bu : [select Village__c, Name, Business_Unit_Code__c, OraclePrimaryBusinessUnit__c, Oracle_Source_Template_Number__c from Business_Unit__c]) {
            if (buByVillage.containsKey(bu.Village__c)) {
                buByVillage.get(bu.Village__c).add(bu);
            } else {
                buByVillage.put(bu.Village__c, new List <Business_Unit__c> {bu});
            }
        }

        MarketingActivityDetails marketingActivitiesWrapper = new MarketingActivityDetails();


        try {
            for (Marketing_Activity__c maActivity : maList){
                id aId = maActivity.id;

                DateTime aCreateDate = maActivity.LastModifiedDate;
                String aName = maActivity.Name;
                String aMAref = maActivity.Marketing_Activity_Ref__c;
                Date aSdate = maActivity.Start_Date__c;
                Date aEdate = maActivity.End_Date__c;
                String aStatus = maActivity.Status__c;
                String aBFuntion = maActivity.Business_Function__c;
                String aChannel = maActivity.Channel__c;
                String aSubChannel = maActivity.Sub_Channel__c;
                String aECategory = maActivity.Expenditure_Category__c;
                String aEType = maActivity.Expenditure_Type__c;

                Village__c village = vRcrdMap.get(maActivity.Marketing_Campaign__r.Village__c);
                Village vlgwrap = new Village();
                vlgwrap.VillageCode = village.Village_Code__c;
                vlgwrap.VillageName = village.Name;

                List<BusinessUnit> tempbu = new List<BusinessUnit>();
                List<Business_Unit__c> bulist = buByVillage.get(village.Id);

                if(!bulist.isEmpty()) {
                    if(bulist.size()>0){
                        BusinessUnit bu1 = new BusinessUnit();
                        bu1.BusinessUnitCode = bulist[0].Business_Unit_Code__c;
                        bu1.BusinessUnitName = bulist[0].Name;
                        bu1.OraclePrimaryBusinessUnit = bulist[0].OraclePrimaryBusinessUnit__c;
                        bu1.OracleProjectId = maActivity.Oracle_Project_Id__c;
                        bu1.OracleTaskId = maActivity.Oracle_Task_Id__c;
                        if(!String.isBlank(maActivity.Oracle_Project_Id__c) && !String.isBlank(maActivity.Oracle_Task_Id__c) ) {
                            tempbu.add(bu1);
                        }
                    }
                    if(bulist.size()>1){
                        BusinessUnit bu2 = new BusinessUnit();
                        bu2.BusinessUnitCode = bulist[1].Business_Unit_Code__c;
                        bu2.BusinessUnitName = bulist[1].Name;
                        bu2.OraclePrimaryBusinessUnit = bulist[1].OraclePrimaryBusinessUnit__c;
                        bu2.OracleProjectId = maActivity.Oracle_Secondary_Project_Id__c;
                        //bu2.OracleTaskId = maActivity.Oracle_Secondary_Task_Id__c;

                        if(!String.isBlank(maActivity.Oracle_Secondary_Task_Id__c) ) {
                            bu2.OracleTaskId = maActivity.Oracle_Secondary_Task_Id__c;
                        }else{
                            bu2.OracleTaskId = maActivity.Oracle_Task_Id__c;
                        }
                        tempbu.add(bu2);
                    }
                }
                if(tempbu.size()>0){
                    Activity activityToSend = new Activity(aId,aCreateDate,aName,aMAref,aSdate,aEdate,aStatus,aBFuntion,aChannel,aSubChannel,aECategory,aEType,vlgwrap,tempbu);
                    marketingActivitiesWrapper.Activities.add(activityToSend);
                    logger.setOutboundRequest(activityToSend, aId);
                }
            }
            String jsonBody = JSON.serialize(marketingActivitiesWrapper);

            Http http =new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(endPointRequestURL);
            request.setMethod('POST');
            request.setHeader('Ocp-Apim-Subscription-Key', apimkey);
            request.setHeader('content-type', 'application/json');
            request.setHeader('Content-Length', '0');
            request.setBody(jsonBody);
            request.setTimeout(20000);

            HttpResponse response = http.send(request);

            system.debug('ResponseReceived$$$ : '+ response);
            logger.setResponseStatusCode(response.getStatusCode());

            if(response.getStatusCode()==202){
                system.debug('Successfull Response'+ response.getBody());
                Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                String SessionIdreceive = (String)results.get('SessionId');
                for (Marketing_Activity__c maActivity : maList) {
                    maActivity.MA_OracleSessionId__c = SessionIdreceive;
                    if(maActivity.Error_Message__c != ''){
                        maActivity.Error_Message__c = '';
                    }
                    matemplist.add(maActivity);
                }
                logger.setSessionId(SessionIdreceive);
            } else{
                logger.setErrorMessage(response.getStatus());
                for (Marketing_Activity__c maActivity : maList) {
                    maActivity.Error_Message__c = response.getStatusCode()+' '+ response.getStatus();
                    maActivity.Integration_Status__c = 'error';
                    matemplist.add(maActivity);
                }
            }

        }catch (Exception e) {
            for (Marketing_Activity__c maActivity : maList) {
                maActivity.Error_Message__c = e.getMessage()+'Issue at Line:'+e.getLineNumber();
                matemplist.add(maActivity);
            }
            logger.setErrorMessage(e.getMessage() + 'LN:' + e.getLineNumber());
            System.debug('Error:' + e.getMessage() + 'LN:' + e.getLineNumber() );
        } finally {
            for (Marketing_Activity__c ma : matemplist) {
                ma.Re_send_to_Oracle_for_NewActivity__c = false;
            } 
            update matemplist;            
            logger.saveRequests();
        }
    }

    global void finish(Database.BatchableContext BC){}
}