force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <description>This object will save all information related to the Business Units...</description>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Unit__c/fields/Business_Unit_Code__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Code__c</fullName>
    <description>.</description>
    <label>Business Unit Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Unit__c/fields/Oracle_Source_Template_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Source_Template_Number__c</fullName>
    <description>.</description>
    <label>Oracle Source Template Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Unit__c/fields/OraclePrimaryBusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>OraclePrimaryBusinessUnit__c</fullName>
    <description>.</description>
    <label>OraclePrimaryBusinessUnit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>True</fullName>
            </value>
            <value>
                <fullName>False</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Unit__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>.</description>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Business Units</relationshipLabel>
    <relationshipName>Business_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>only valid for redeemable campaigns</description>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter the End Date of the Campaign</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <description>Represents the status of the record as far as the Oracle Integration is concerned.</description>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>waiting</fullName>
                <default>true</default>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>sending</fullName>
                <label>Sending</label>
            </value>
            <value>
                <fullName>confirmed</fullName>
                <label>Success</label>
            </value>
            <value>
                <fullName>error</fullName>
                <label>Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Marketing_Campaign_Ref__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign_Ref__c</fullName>
    <displayFormat>MC-{00000}</displayFormat>
    <externalId>true</externalId>
    <label>Marketing Campaign Ref</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/NumberOfCampaigns__c.field-meta.xml
<CustomField>
    <fullName>NumberOfCampaigns__c</fullName>
    <label>NumberOfCampaigns</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/OracleSessionId__c.field-meta.xml
<CustomField>
    <fullName>OracleSessionId__c</fullName>
    <label>OracleSessionId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Re_send_to_Oracle__c.field-meta.xml
<CustomField>
    <fullName>Re_send_to_Oracle__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select this field and save the Record in order to resend this record&apos;s information to the Finance System</inlineHelpText>
    <label>Re-send to Oracle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter the Start Date of the Campaign</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>...</description>
    <inlineHelpText>Select the Village is this campaign related to</inlineHelpText>
    <label>Village</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>notEqual</operation>
            <value>Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Village Campaign</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/Oracle_Source_Template_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Source_Template_Number__c</fullName>
    <description>The value used to map to an oracle template when sent to Oracle Fusion</description>
    <inlineHelpText>The value used to map to an oracle template when sent to Oracle Fusion</inlineHelpText>
    <label>Oracle Source Template Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MarketingCampaignBatchCallout.cls
global class MarketingCampaignBatchCallout implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    Set <Id> insertedMarketingCampaignIds;

    public MarketingCampaignBatchCallout(Set <Id> insertedMarketingCampaignIds){
        this.insertedMarketingCampaignIds = insertedMarketingCampaignIds;
    }

    public class MarketingCampaignsDetails {
        public List<Campaign> Campaigns = new List <Campaign> ();
    }

    public class Campaign{
        public String SalesforceId;
        public DateTime SalesforceDateTime;
        public String CampaignName;
        public String MarketingCampaignRef;
        public Date StartDate;
        public Date EndDate;
        public String CampaignType;
        public String CampaignStatus;
        public Village Village;
        public List<BusinessUnit> BusinessUnit;
        
        public Campaign(String id, String cName, String mcref, Date sDate, Date eDate, String cType, String cStatus, Datetime cSDateTime,Village vlgRecords, List<BusinessUnit> BUnit){
            this.SalesforceId =id;
            this.CampaignName =cName;
            this.MarketingCampaignRef =mcref;
            this.StartDate =sDate;
            this.EndDate =eDate;
            this.CampaignType =cType;
            this.CampaignStatus =cStatus;
            this.SalesforceDateTime =cSDateTime;
            this.Village =vlgRecords;
            this.BusinessUnit =BUnit;
            
        }
    }    
    
    public class Village{
        public String VillageCode;
        public String VillageName;
    }

    public class BusinessUnit {
        public String BusinessUnitCode;
        public String BusinessUnitName;
        public String OraclePrimaryBusinessUnit;
        public String OracleSourceTemplateName;
    }
    
    
    global List <Marketing_Campaign__c> start(Database.BatchableContext BC){
        return [SELECT Name, Marketing_Campaign_Ref__c, Start_Date__c, End_Date__c, RecordTypeId, Status__c, CreatedDate, Village__c, Error_Message__c FROM Marketing_Campaign__c WHERE Id IN: this.insertedMarketingCampaignIds];
    }
    
    global void execute(Database.BatchableContext BC, List<Marketing_Campaign__c> mcList){    

        List<Marketing_Campaign__c> mctemplist = new  List<Marketing_Campaign__c>();
       
        String endPointRequestURL = System.Label.MarketingCampaignDIEndPoint;
        String apimkey = System.Label.MarketingFinanceIntegrationAPIMKey;
        MFIntegrationLogger logger = new MFIntegrationLogger ();
        logger.setMarketingCampaignAsRelatedObject();

        Map <Id, Village__c> vRcrdMap = new Map <Id, Village__c>([select Id, Name, Village_Code__c from Village__c]);
        
        List<Business_Unit__c> bulist = [select Name, Business_Unit_Code__c, OraclePrimaryBusinessUnit__c, Oracle_Source_Template_Number__c,Village__r.Name from Business_Unit__c];
        
        MarketingCampaignsDetails marketingCampaignsWrapper = new MarketingCampaignsDetails();
        
        
        try {
            for (Marketing_Campaign__c maCamp : mcList){
                Id mId = maCamp.id;
                system.debug('mId'+mId); 
                String mName= maCamp.Name;
                String mCRef= maCamp.Marketing_Campaign_Ref__c;
                Date mStartDate = maCamp.Start_Date__c;
                Date mEndDate = maCamp.End_Date__c;
                string mCtype = Schema.SObjectType.Marketing_Campaign__c.getRecordTypeInfosById().get(maCamp.recordtypeid).getname();
                String mCstatus = maCamp.Status__c;
                Datetime mCreateDate = maCamp.CreatedDate;
                
                maCamp.NumberOfCampaigns__c = mcList.size();
                System.debug('***Number of Campaigns send  :'+ maCamp.NumberOfCampaigns__c);
          
                Village vlgwrap = new Village();
                vlgwrap.VillageCode =  vRcrdMap.get(maCamp.Village__c).Village_Code__c;
                vlgwrap.VillageName = vRcrdMap.get(maCamp.Village__c).Name;  
                
                List<BusinessUnit>  businessUnitlist  = new List<BusinessUnit>();
                for(Business_Unit__c bu : bulist){
                    if(bu.Village__r.Name == vlgwrap.VillageName){ 
                        BusinessUnit tempbu = new BusinessUnit();
                        tempbu.BusinessUnitCode = bu.Business_Unit_Code__c;
                        tempbu.BusinessUnitName = bu.Name;
                        tempbu.OraclePrimaryBusinessUnit = bu.OraclePrimaryBusinessUnit__c;
                        tempbu.OracleSourceTemplateName = bu.Oracle_Source_Template_Number__c;
                        businessUnitlist.add(tempbu);
                    }
                } 

                Campaign campaignToSend = new Campaign(mId,mName,mCRef,mStartDate,mEndDate,mCtype,mCstatus,mCreateDate,vlgwrap,businessUnitlist);
                marketingCampaignsWrapper.Campaigns.add(campaignToSend);
                logger.setOutboundRequest(campaignToSend, mId);
            }
            String jsonBody = JSON.serialize(marketingCampaignsWrapper);   
            system.debug('json response :'+jsonBody); 
            
            Http http =new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(endPointRequestURL);
            request.setMethod('POST'); 
            request.setHeader('Ocp-Apim-Subscription-Key', apimkey);
            request.setHeader('content-type', 'application/json');
            request.setHeader('Content-Length', '0'); 
            request.setBody(jsonBody);
            request.setTimeout(20000);
            
            HttpResponse response = http.send(request); 
            system.debug('ResponseReceived$$$ : '+ response);
            logger.setResponseStatusCode(response.getStatusCode());
            
            if(response.getStatusCode()==202){
                system.debug('Successfull Response'+ response.getBody());  
                Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                String SessionIdreceive = (String)results.get('SessionId');
                Decimal numofcamp = (Decimal)results.get('NumberOfCampaigns');
                System.debug('&&& Number of Campaigns received :'+ numofcamp);
                for (Marketing_Campaign__c maCamp : mcList) {
                    maCamp.OracleSessionId__c = SessionIdreceive;
                    Decimal numofCampSalesforce = maCamp.NumberOfCampaigns__c;
                    if( numofCampSalesforce != numofcamp) {
                        maCamp.Error_Message__c = 'Mis-match in number of campaigns processed from Salesforce and Oracle';
                    }
                    if(maCamp.Error_Message__c != ''){
                        maCamp.Error_Message__c = '';
                    }
                    mctemplist.add(maCamp);
                }
                logger.setSessionId(SessionIdreceive);
            } else {
                for (Marketing_Campaign__c maCamp : mcList) {
                    maCamp.Error_Message__c = response.getStatusCode()+' '+ response.getStatus();
                    maCamp.Integration_Status__c = 'error';
                    maCamp.Re_send_to_Oracle__c = True;  
                    mctemplist.add(maCamp);
                }      
                logger.setErrorMessage(response.getStatus());
            }
        } catch (Exception e){ 
            for (Marketing_Campaign__c maCamp : mcList) {
                maCamp.Error_Message__c = e.getMessage() + 'LN:' + e.getLineNumber();                                
                maCamp.Integration_Status__c = 'error';
                maCamp.Re_send_to_Oracle__c = True;  
                mctemplist.add(maCamp);   
            }
            logger.setErrorMessage(e.getMessage() + 'LN:' + e.getLineNumber());
            System.debug('Error:' + e.getMessage() + 'LN:' + e.getLineNumber());           
        } finally {
            for (Marketing_Campaign__c mc : mctemplist) {
                mc.Re_send_to_Oracle__c = false;
            } 
            update mctemplist;        
            logger.saveRequests(); 
        }
    }

    global void finish(Database.BatchableContext BC){}
}