force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <inlineHelpText>Select the type of contract you wish to create</inlineHelpText>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lease</fullName>
                <default>true</default>
                <label>Lease</label>
            </value>
            <value>
                <fullName>Licence</fullName>
            </value>
            <value>
                <fullName>MSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Fitting_out_Period_days__c.field-meta.xml
<CustomField>
    <fullName>Fitting_out_Period_days__c</fullName>
    <defaultValue>60</defaultValue>
    <inlineHelpText>Enter the number of days agreed to perform the shop fit</inlineHelpText>
    <label>Fitting out Period (days)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Landlords_Break_Rights__c.field-meta.xml
<CustomField>
    <fullName>Landlords_Break_Rights__c</fullName>
    <inlineHelpText>Enter the details of the Landlords break rights if applicable</inlineHelpText>
    <label>Landlords Break Rights</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the opportunity that lead to the creation of this contract</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the village for this lease</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <formula>Village__r.Village_Code__c</formula>
    <inlineHelpText>The 2 digit village code pulled from the Village object, this is used to select the appropriate contract approval process</inlineHelpText>
    <label>Village Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the actual village where this opportunity exists</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Default_Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Default_Contract_Type__c</fullName>
    <inlineHelpText>Select the default contract type when creating new contracts</inlineHelpText>
    <label>Default Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>Licence</fullName>
            </value>
            <value>
                <fullName>MSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/fields/Std_Break_Clause__c.field-meta.xml
<CustomField>
    <fullName>Std_Break_Clause__c</fullName>
    <inlineHelpText>Enter the Standard Landlords Break Clause</inlineHelpText>
    <label>Std Break Clause</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Std_Fit_Out_days__c.field-meta.xml
<CustomField>
    <fullName>Std_Fit_Out_days__c</fullName>
    <inlineHelpText>Enter the standard fitting out period in days to be used in this village</inlineHelpText>
    <label>Std Fit Out (days)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Std_Lease_Term_months__c.field-meta.xml
<CustomField>
    <fullName>Std_Lease_Term_months__c</fullName>
    <defaultValue>120</defaultValue>
    <inlineHelpText>Enter the standard lease term in months for leases in this village</inlineHelpText>
    <label>Std Lease Term (months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Test_ContractPreDefaults.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Test_ContractPreDefaults {

    private static final id brandRecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Brand').RecordTypeId;
        
    static testMethod void testPreDefaultsOnInsert() {
    	
    	// Set up Account test data
    	Account account = new Account(Name='TestA', RecordTypeId = brandRecordTypeId);
    	insert account;
    	
    	// Set up Village test data
    	Village__c village = new Village__c(Name='TestV', Std_Break_Clause__c = 'Test_Std_Break_Clause__c',
    									Std_Fit_Out_days__c = 7, Default_Contract_Type__c = 'Lease',
    									Std_Lease_Term_months__c = 12, Village_Code__c = 'TT',CertSales_CertPeriod_Cut_Off_Days__c = 1, CertSales_Report_Sales_Grace_Period_Days__c = 1);
    	insert village;
    	
    	//Set up Opportunity test data
    	Opportunity opportunity = new Opportunity(Name='TestO', StageName = 'In discussion', 
    									AccountId = account.Id, CloseDate=system.today()+7,
    									Village__c = village.id);
    	insert opportunity;
    	
    	test.startTest();
    	Contract contract = new Contract(Name = 'TestC', AccountId = account.Id, Opportunity__c = opportunity.id);
    	insert contract;
    	contract = [select Landlords_Break_Rights__c, Fitting_out_Period_days__c, Contract_Type__c, ContractTerm 
    					from Contract where Name = 'TestC'];
    	/*
    	system.assertEquals(contract.Landlords_Break_Rights__c, village.Std_Break_Clause__c);
    	system.assertEquals(contract.Fitting_out_Period_days__c, village.Std_Fit_Out_days__c);
    	system.assertEquals(contract.Contract_Type__c, village.Default_Contract_Type__c);
    	system.assertEquals(contract.ContractTerm, village.Std_Lease_Term_months__c);
    	*/
    	test.stopTest();
    
    }
    
    
    static testMethod void testPreDefaultsOnBulkInsert() {
    	
    	// Set up Account test data
    	Account account = new Account(Name='TestA', RecordTypeId = brandRecordTypeId);
    	insert account;
    	
    	// Set up Village test data
    	Village__c village = new Village__c(Name='TestV', Std_Break_Clause__c = 'Test_Std_Break_Clause__c',
    									Std_Fit_Out_days__c = 7, Default_Contract_Type__c = 'Lease',
    									Std_Lease_Term_months__c = 12, Village_Code__c = 'TT',CertSales_CertPeriod_Cut_Off_Days__c = 1, CertSales_Report_Sales_Grace_Period_Days__c = 1);
    	insert village;
    	
    	//Set up Oportunity test data
    	Opportunity opportunity = new Opportunity(Name='TestO', StageName = 'In discussion', 
    									AccountId = account.Id, CloseDate=system.today()+7,
    									Village__c = village.id);
    	insert opportunity;
    	
    	test.startTest();
    	
    	// Create 200 Contract records
    	list<Contract> contractList = new list<Contract>();
    	for(integer i = 0; i < 200; i++){
    		Contract contract = new Contract(Name = 'TestC' + i, AccountId = account.Id, Opportunity__c = opportunity.id);
    		contractList.add(contract);
    	}
    	insert contractList;
    	
    	contractList = [select Landlords_Break_Rights__c, Fitting_out_Period_days__c, Contract_Type__c, ContractTerm 
    					from Contract where Name like 'TestC%'];
    	/*
    	for (Contract contract :contractList){
	    	system.assertEquals(contract.Landlords_Break_Rights__c, village.Std_Break_Clause__c);
	    	system.assertEquals(contract.Fitting_out_Period_days__c, village.Std_Fit_Out_days__c);
	    	system.assertEquals(contract.Contract_Type__c, village.Default_Contract_Type__c);
	    	system.assertEquals(contract.ContractTerm, village.Std_Lease_Term_months__c);
    	}
    	*/
    	test.stopTest();
    
    }
    
}