force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/BP_Brand_Term__c/BP_Brand_Term__c.object-meta.xml
<CustomObject>
    <label>T&amp;C</label>
    <nameField>
        <displayFormat>BT&amp;C-{0000}</displayFormat>
        <label>T&amp;C</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;Cs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BP_Brand_Term__c/fields/BP_terms_Language__c.field-meta.xml
<CustomField>
    <fullName>BP_terms_Language__c</fullName>
    <label>T&amp;C Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BP_terms_Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BP_Brand_Term__c/fields/Brand_Terms__c.field-meta.xml
<CustomField>
    <fullName>Brand_Terms__c</fullName>
    <label>Brand T&amp;Cs</label>
    <length>25000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <inlineHelpText>Add a Village Presence Contact Role to add Villages to this field</inlineHelpText>
    <label>Village Presence</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the detail of all units in VR Villages</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Phase_ID__c.field-meta.xml
<CustomField>
    <fullName>Phase_ID__c</fullName>
    <inlineHelpText>Enter the corresponding Phase ID</inlineHelpText>
    <label>Phase ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Size_GEA__c.field-meta.xml
<CustomField>
    <fullName>Size_GEA__c</fullName>
    <inlineHelpText>Enter the Gross External Area (GEA) of the unit in square meters</inlineHelpText>
    <label>Size (GEA)</label>
    <precision>13</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Suite_ID__c.field-meta.xml
<CustomField>
    <fullName>Suite_ID__c</fullName>
    <inlineHelpText>Enter the suite ID for this Unit in order to allow the data to be interfaced to a realted system such as MRI</inlineHelpText>
    <label>Suite ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>...</description>
    <inlineHelpText>Select the Village where this unit lives</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Organisation__c</fullName>
    <description>The business unit within oracle</description>
    <inlineHelpText>The business unit within oracle</inlineHelpText>
    <label>Oracle Organisation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Source_Template_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Source_Template_Number__c</fullName>
    <description>The value used to map to an oracle template when sent to Oracle Fusion</description>
    <inlineHelpText>The value used to map to an oracle template when sent to Oracle Fusion</inlineHelpText>
    <label>Oracle Source Template Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Village Presence records must be linked to Brand accounts. Please ensure you are not linking the Deal/Village Presence to a Group</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Daily_Sales_Active__c.field-meta.xml
<CustomField>
    <fullName>Daily_Sales_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Daily Sales Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deal Pending</fullName>
            </value>
            <value>
                <fullName>Trading</fullName>
            </value>
            <value>
                <fullName>in Refit</fullName>
            </value>
            <value>
                <fullName>Exited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/Village_Presence_Contact_Role__c.object-meta.xml
<CustomObject>
    <label>Village Presence Contact Role</label>
    <nameField>
        <displayFormat>VPC-{00000}</displayFormat>
        <label>Village Presence Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Village Presence Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/BP_HFS_Brand_TeC_Conf_Date__c.field-meta.xml
<CustomField>
    <fullName>BP_HFS_Brand_TeC_Conf_Date__c</fullName>
    <description>Timestamp for HFS Brand T&amp;Cs user´s confirmation</description>
    <label>HFS Brand T&amp;Cs Confirmation</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Confirm_Daily_Sales_Records__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Daily_Sales_Records__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Can the contact, for this store, confirm Daily Sales Records</inlineHelpText>
    <label>Confirm Daily Sales Records</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must be a Brand Contact</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Village Presence Contact Roles</relationshipLabel>
    <relationshipName>Village_Presence_Contact_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Daily_Sales_Active_From__c.field-meta.xml
<CustomField>
    <fullName>Daily_Sales_Active_From__c</fullName>
    <inlineHelpText>Enter the date for which the user should be able to see daily sales records</inlineHelpText>
    <label>Daily Sales Active From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Daily_Sales_Active_To__c.field-meta.xml
<CustomField>
    <fullName>Daily_Sales_Active_To__c</fullName>
    <inlineHelpText>Enter the date for which the user should no longer be able to see daily sales records.  If this field is left empty then the user will be able to see the daily sales records indefinitely unless the user is deactivated.</inlineHelpText>
    <label>Daily Sales Active To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Retail_Role__c.field-meta.xml
<CustomField>
    <fullName>Retail_Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Retail</fullName>
                <default>true</default>
                <label>Retail</label>
            </value>
            <value>
                <fullName>Remerchandising</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Village Presence</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>Village Presence Contact Roles</relationshipLabel>
    <relationshipName>Village_Presence_Contact_Roles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/BP_terms_Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>English</fullName>
        <default>true</default>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Deutsch</fullName>
    </customValue>
    <customValue>
        <fullName>Español</fullName>
    </customValue>
    <customValue>
        <fullName>Français</fullName>
    </customValue>
    <customValue>
        <fullName>Italiano</fullName>
    </customValue>
    <masterLabel>BP terms Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BP_Terms_Controller_Test.cls
@isTest
public class BP_Terms_Controller_Test {

    static void setupData(){

        Profile profileSysAdmin = [SELECT ID, Name FROM Profile WHERE Name = 'System Administrator'];

        UserRole adminRole = new UserRole();
        adminRole.DeveloperName = 'CustomRole';
        adminRole.Name = 'Custom Role';
        insert adminRole;

        User admin = new User();
        admin.LastName = 'AdministratorForTestingHere';
        admin.Alias = 'admin';
        admin.Email = 'adminFortests@valueretai.com';
        admin.Username = 'adminFortests@valueretai.com';
        admin.CommunityNickname = 'admin';
        admin.UserRoleId = adminRole.Id;
        admin.ProfileId = profileSysAdmin.Id;
        admin.Village__c = 'Bicester';
        admin.TimeZoneSidKey = 'GMT';
        admin.LocaleSidKey = 'en_GB';
        admin.EmailEncodingKey = 'ISO-8859-1';
        admin.LanguageLocaleKey = 'en_US';
        insert admin;

        system.runAs(admin){
            Village__c vill = TestDataGenerator.setupVillage(false);
            vill.Oracle_Source_Template_Number__c = '123456';
            vill.Oracle_Organisation__c = 'SourceOrg';
            vill.Name = 'Bicester';
			vill.CertSales_CertPeriod_Cut_Off_Days__c = 1;
			vill.CertSales_Report_Sales_Grace_Period_Days__c = 1;
            insert vill;
            
            Unit__c unit = new Unit__c();
            unit.Village__c = vill.Id;
            unit.Name = 'BIC1';
            unit.Size_GEA__c = 120;
            unit.Suite_ID__c = 'S1';
            unit.Phase_Id__c = 'P1';
            insert unit;
            
            RecordType brandRecordType = [SELECT Id, Name FROM RecordType WHERE Name = 'Brand'];
            
            Account brand = new Account();
            brand.RecordTypeId = brandRecordType.Id;
            brand.Name = 'Brand 1';
            insert brand;
            
            Village_Presence__c presentBrand = new Village_Presence__c();
            presentBrand.Name = 'Brand1 in village';
            presentBrand.Unit__c = unit.Id;
            presentBrand.Brand__c = brand.Id;
            presentBrand.Village__c = vill.Id;
            presentBRand.Daily_Sales_Active__c = true;
            presentBrand.Status__c = 'Trading';
            insert presentBrand;
            
            RecordType brandContactRecordType = [SELECT Id, Name FROM RecordType WHERE Name = 'Brand Contact'];
            
            Contact communityContact = new Contact();
            communityContact.RecordTypeId = brandContactRecordType.Id;
            communityContact.LastName = 'John';
            communityContact.AccountId = brand.Id;
            communityContact.Village_Presence__c = 'Bicester';
            communityContact.Email = 'testcommunity.contact@brand.com';
            insert communityContact;

            Village_Presence_Contact_Role__c communityContactRole = new Village_Presence_Contact_Role__c();
            communityContactRole.Contact__c = communityContact.Id;
            communityContactRole.Retail_Role__c = 'Retail';
            communityContactRole.Village_Presence__c = presentBrand.Id;
            communityContactRole.Daily_Sales_Active_From__c = Date.newInstance(2018, 10, 1);
            communityContactRole.Daily_Sales_Active_To__c = Date.newInstance(2025, 10, 1);
            communityContactRole.Confirm_Daily_Sales_Records__c = true;
            communityContactRole.BP_HFS_Brand_TeC_Conf_Date__c = Date.newInstance(2025, 10, 1);
            insert communityContactRole;

            UserRole communityRole = new UserRole();
            communityRole.DeveloperName = 'NewBalanceCustomerUser5';
            communityRole.Name = 'NewBalanceCustomerUser1';
            insert communityRole;
            
            Profile profileCommunity = [SELECT ID, Name FROM Profile WHERE Name = 'Brand Community Plus User (with Export)'];
            
            User communityUser = new User();
            communityUser.LastName = communityContact.LastName;
            communityUser.Alias = 'jhn';
            communityUser.Email = communityContact.Email;
            communityUser.Username = 'john@valueretai.com';
            communityUser.CommunityNickname = 'johnvr';
            communityUser.ProfileId = profileCommunity.Id;
            communityUser.Village__c = 'Bicester';
            communityUser.TimeZoneSidKey = 'GMT';
            communityUser.LocaleSidKey = 'en_GB';
            communityUser.EmailEncodingKey = 'ISO-8859-1';
            communityUser.LanguageLocaleKey = 'en_US';
            communityUser.ContactId = communityContact.Id;
            communityUser.PortalRole = 'Manager';
            insert communityUser;

            BP_Brand_Term__c terms = new BP_Brand_Term__c();
            terms.BP_terms_Language__c = 'English';
            terms.Brand_Terms__c = 'TeCs Text Example';
            terms.CurrencyIsoCode = 'EUR';
            insert terms;

        }
        
    }


    static testMethod void guestExtensionTestBPTC1(){

        setupData();
        String tR = '';

        Test.startTest();   

            tR = BP_Terms_Controller.getTerms();

        Test.stopTest();
        
        User user = [SELECT toLabel(LanguageLocaleKey) FROM User WHERE Alias = 'jhn'];
        String userLanguage = user.LanguageLocaleKey;
        BP_Brand_Term__c terms = [SELECT Brand_Terms__c, BP_terms_Language__c FROM BP_Brand_Term__c WHERE BP_terms_Language__c =: userLanguage ];

        System.assertEquals(tR, terms.Brand_Terms__c);
    }
    
    
    static testMethod void guestExtensionTestBPTC2(){

        setupData();
        User user = [SELECT Id, Email FROM User WHERE Alias = 'jhn' ];
        Date aDate;

        Test.startTest();   
            system.runAs(user){
               BP_Terms_Controller.getSubmit();  
               aDate = system.today();            
            }
        Test.stopTest();

        string email = user.Email;
        
        Contact contact = [SELECT id FROM CONTACT 
                           WHERE Email =: email                       
                           LIMIT 1];            
        
        Village_Presence_Contact_Role__c vpr = [SELECT Contact__c, id, BP_HFS_Brand_TeC_Conf_Date__c FROM Village_Presence_Contact_Role__c WHERE Contact__c =: contact.Id LIMIT 1];                       
         
        dateTime aDateTime = vpr.BP_HFS_Brand_TeC_Conf_Date__c;
        System.assertEquals(aDate, date.newinstance(aDateTime.year(), aDateTime.month(), aDateTime.day()));

    }
    
    static testMethod void guestExtensionTestBPTC3(){

        setupData();
        String tR = '';
        String tRuser = '';

        User user = [SELECT Email, Name, id FROM USER 
                     WHERE Alias = 'jhn'
                     LIMIT 1]; 

        Test.startTest();   
            system.runAs(user){
                tRuser = ' ' + System.Label.DAILY_SALE_TERMS_APPROVED_BY + ' ';
                tR = BP_Terms_Controller.getTermsUser();
            }
        Test.stopTest();

        string email = user.Email;
        
        Contact contact = [SELECT id FROM CONTACT 
                           WHERE Email =: email                       
                           LIMIT 1];            
        
        Village_Presence_Contact_Role__c vpr = [SELECT Contact__c, id, BP_HFS_Brand_TeC_Conf_Date__c FROM Village_Presence_Contact_Role__c WHERE Contact__c =: contact.Id LIMIT 1];                       
         
        String tUserDate = string.valueofGmt(vpr.BP_HFS_Brand_TeC_Conf_Date__c);
        tRuser = tRuser +  user.Name + '  ' + tUserDate;

        System.assertEquals(tR, tRuser);
    }


    
}