force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Trade_Event__c/Trade_Event__c.object-meta.xml
<CustomObject>
    <label>Trade Event</label>
    <nameField>
        <label>Trade Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade_Event__c/fields/Category_Specification__c.field-meta.xml
<CustomField>
    <fullName>Category_Specification__c</fullName>
    <label>Category Specification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trade Show</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Sport</fullName>
            </value>
            <value>
                <fullName>Dinner</fullName>
            </value>
            <value>
                <fullName>Fashion Show</fullName>
            </value>
            <value>
                <fullName>Music</fullName>
            </value>
            <value>
                <fullName>Theatre</fullName>
            </value>
            <value>
                <fullName>Awards Night</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade_Event__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade_Event__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade_Event_Attendee__c/Trade_Event_Attendee__c.object-meta.xml
<CustomObject>
    <description>Junction Object</description>
    <label>Trade Event Attendee</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Trade Event Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade_Event_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tourism Contact</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tourism Contact</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Leasing Contact</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand Contact</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>HNW Event Attendee</value>
        </filterItems>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>VIP Guest</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trade Events Attended</relationshipLabel>
    <relationshipName>Trade_Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Trade_Event_Attendee__c/fields/Invite_Status__c.field-meta.xml
<CustomField>
    <fullName>Invite_Status__c</fullName>
    <defaultValue>&quot;Invited&quot;</defaultValue>
    <label>Invite Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Added</fullName>
            </value>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade_Event_Attendee__c/fields/Trade_Event__c.field-meta.xml
<CustomField>
    <fullName>Trade_Event__c</fullName>
    <label>Trade Event</label>
    <referenceTo>Trade_Event__c</referenceTo>
    <relationshipLabel>Trade Event Attendees</relationshipLabel>
    <relationshipName>Trade_Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Trade_Event_Attendee__c/fields/Trade_Event_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Trade_Event_Attendee__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; Id,  Contact__r.FirstName + &quot; &quot; +  Contact__r.LastName  ,&quot;_self&quot;)</formula>
    <label>Trade Event Attendee</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/addtotradeEventControllertest.cls
@isTest
private class addtotradeEventControllertest{

  private static Village__c village = new Village__c();
  public static Trade_Event__c theEvent = new Trade_Event__c();
  public static Account testAccount = new Account();
  public static Contact contact1 = new Contact();
  public static Contact contact2 = new Contact();
  public static list <contact> contactList1 = new list <contact>();
  public static list <Trade_Event_Attendee__c> attendeelist2 = new list <Trade_Event_Attendee__c>();
  public static Trade_Event_Attendee__c Attendee1 = new Trade_Event_Attendee__c();
  public static Trade_Event_Attendee__c Attendee2 = new Trade_Event_Attendee__c();


  static void setupData1(){

  recordtype rt = [SELECT id FROM recordtype where sObjectType = 'contact' AND Name = 'Brand Contact' LIMIT 1];
   
  testAccount = TestData_Account.setupBrandAccount(1, true);   
               
  village.Name = 'TestVillage1';     
  village.Village_Code__c = 'AA';
  village.CertSales_CertPeriod_Cut_Off_Days__c = 1;
  village.CertSales_Report_Sales_Grace_Period_Days__c = 1;
  insert village;
  village = [select name, id, Village_Code__c from Village__c where Village_Code__c = 'AA' LIMIT 1];        
   
  contact1.FirstName = 'Firstname';   
  contact1.LastName = 'Surname';   
  contact1.phone = '123456789';   
  contact1.recordtypeid = rt.id;
  contact1.account = testAccount;  
  insert contact1; 
  
  contact2.FirstName = 'Firstname';   
  contact2.LastName = 'Surname';   
  contact2.phone = '123456789';   
  contact2.recordtypeid = rt.id;
  contact2.account = testAccount;  
  insert contact2; 
  
  theEvent.Name = 'test trade event';
  theEvent.Start_Time__c = system.now(); 
  theEvent.End_Time__c = system.now();
  theEvent.Category_Specification__c = 'Conference';
  insert theEvent;
                      
  }

    
    @isTest static void selectandProcessAccountandAttendees() {

      setupData1();
        
      test.startTest();
      Apexpages.Standardcontroller stdController = new Apexpages.Standardcontroller(theEvent);
      addtotradeEventController controller = new addtotradeEventController(stdController );
      PageReference pageRef = Page.MassAddTradeEventAttendees;
      Test.setCurrentPage(pageRef);
      controller.initMem.Accountid = testAccount.id;
      controller.AddSelectedAttendees();

      list<addtotradeEventController.cContact> cCons = new list<addtotradeEventController.cContact>();
      contactList1 = [SELECT Id, Name FROM Contact where id =:contact1.id or id=:contact2.id];
      for(contact cta : contactList1 ){
            cCons.add(new addtotradeEventController.cContact(cta, true));
          }
      controller.consToSelect = cCons;

      controller.processSelected();
      controller.cancel();
      controller.finished();
      test.stopTest();
      list<Trade_Event_Attendee__c> TEA = [SELECT Id, name FROM Trade_Event_Attendee__c where Trade_Event__c =:theEvent.id];
      system.assert(TEA.size() == 2);
      
    }


  static void setupData2(){
   
  testAccount = TestData_Account.setupBrandAccount(1, true);   
  recordtype conrt = [SELECT id FROM recordtype where sObjectType = 'contact' AND Name = 'Brand Contact' LIMIT 1];
  recordtype teart = [SELECT id FROM recordtype where sObjectType = 'Trade_Event_Attendee__c' AND Name = 'Leasing Contact' LIMIT 1];
               
  village.Name = 'TestVillage1';     
  village.Village_Code__c = 'AA';
  village.CertSales_CertPeriod_Cut_Off_Days__c = 1;
  village.CertSales_Report_Sales_Grace_Period_Days__c = 1;
  insert village;
  village = [select name, id, Village_Code__c from Village__c where Village_Code__c = 'AA' LIMIT 1];        
   
  contact1.FirstName = 'Firstname';   
  contact1.LastName = 'Surname';   
  contact1.phone = '123456789';   
  contact1.recordtypeid = conrt.id;
  contact1.account = testAccount;  
  insert contact1; 
  
  contact2.FirstName = 'Firstname';   
  contact2.LastName = 'Surname';   
  contact2.recordtypeid = conrt.id;
  contact2.phone = '123456789';   
  contact2.account = testAccount;  
  insert contact2; 
  
  theEvent.Name = 'test trade event';
  theEvent.Start_Time__c = system.now(); 
  theEvent.End_Time__c = system.now();
  theEvent.Category_Specification__c = 'Conference';
  insert theEvent;
  
  Attendee1.contact__c = contact1.id;
  Attendee1.Trade_Event__c = theEvent.id;
  Attendee1.Invite_Status__c = 'Not invited';
  Attendee1.recordtypeid = teart.id;
  insert Attendee1;
  
  Attendee2.contact__c = contact2.id;
  Attendee2.Trade_Event__c = theEvent.id;
  Attendee2.Invite_Status__c = 'Not invited';
  Attendee2.recordtypeid = teart.id;
  insert Attendee2;
                     
  }


  @isTest static void selectandEditAttendees() {

      setupData2();
        
      test.startTest();

      Apexpages.Standardcontroller stdController = new Apexpages.Standardcontroller(theEvent);
      MassEditTradeEventAttendees controller = new MassEditTradeEventAttendees(stdController );
      PageReference pageRef = Page.MassEditAttendees;
      Test.setCurrentPage(pageRef);

      list<MassEditTradeEventAttendees.cTradeAttendee> cAttendees = new list<MassEditTradeEventAttendees.cTradeAttendee>();
      MassEditTradeEventAttendees.cTradeAttendee cTEA1 = new MassEditTradeEventAttendees.cTradeAttendee(Attendee1);
      MassEditTradeEventAttendees.cTradeAttendee cTEA2 = new MassEditTradeEventAttendees.cTradeAttendee(Attendee2);
      cAttendees.add(cTEA1);
      cAttendees.add(cTEA2);
      controller.attendeesToEdit = cAttendees;
      controller.attendeesToEdit[0].selected = true;
      controller.attendeesToEdit[1].selected = true;

      controller.selectOptions.Invite_Status__c = 'Invited';
      controller.setAllStatus();
      controller.saveSelected();

      test.stopTest();

      list<Trade_Event_Attendee__c> TEAnonInvites = [SELECT Id, name FROM Trade_Event_Attendee__c where Trade_Event__c =:theEvent.id AND invite_status__c = 'Not Invited'];
      list<Trade_Event_Attendee__c> TEAinvites = [SELECT Id, name FROM Trade_Event_Attendee__c where Trade_Event__c =:theEvent.id AND invite_status__c = 'Invited'];
      system.assert(TEAinvites.size() == 2);
      system.assert(TEAinvites.size() > TEAnonInvites.size());
      
    }


     @isTest static void executeRemainingMethods() {

      setupData2();

      Apexpages.Standardcontroller stdController = new Apexpages.Standardcontroller(theEvent);
      MassEditTradeEventAttendees controller = new MassEditTradeEventAttendees(stdController );
      PageReference pageRef = Page.MassEditAttendees;
      Test.setCurrentPage(pageRef);

      test.startTest();

      controller.cancel();
      controller.selectAll();
      controller.deselectAll();
      controller.setAllFollowUps();

      test.stopTest();


     }

    
    

    
    
}