force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Village Presence records must be linked to Brand accounts. Please ensure you are not linking the Deal/Village Presence to a Group</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/VIP_Brand_Preference__c/VIP_Brand_Preference__c.object-meta.xml
<CustomObject>
    <description>Which brands does the VIP prefer</description>
    <label>VIP Brand Preference</label>
    <nameField>
        <label>VIP Brand Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VIP Brand Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIP_Brand_Preference__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The brand that the guest prefers</description>
    <inlineHelpText>The brand that the guest prefers</inlineHelpText>
    <label>Village Presence</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Village_Presence__c.Status__c</field>
            <operation>equals</operation>
            <value>Trading</value>
        </filterItems>
        <infoMessage>Only Trading brands should be selected</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>VIP Brand Preferences</relationshipLabel>
    <relationshipName>VIP_Brand_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VIPBrandPreferenceUtilities.cls
public without sharing class VIPBrandPreferenceUtilities{


 // Method to default village presence name after insert or update
  public static void defaultName(List<VIP_Brand_Preference__c> newMap){
  
  Set<Id> newValueUpdatedVP = new Set<Id>();
    for(VIP_Brand_Preference__c VBPID : newMap){
      newValueUpdatedVP.add(VBPID.Village_Presence__c);
    }
    if (!newValueUpdatedVP.isEmpty()){
      
      Map<ID, Village_Presence__c> villagePresenceList = new Map<ID, Village_Presence__c>([select Id, name, brand__r.name from Village_Presence__c where id in:newValueUpdatedVP]);
      if (!villagePresenceList.isEmpty()){
          for (VIP_Brand_Preference__c BrandPreference : newMap){
             BrandPreference.name = villagePresenceList.get(BrandPreference.Village_Presence__c).brand__r.name;
             
            }
     
      }
    }  
  }
  
    public static void defaultNameOnUpdate(List<VIP_Brand_Preference__c> oldMap, List<VIP_Brand_Preference__c> newMap){

    Set<Id> oldValueUpdatedVP = new Set<Id>();
    for(VIP_Brand_Preference__c oldValue : oldMap){
      oldValueUpdatedVP.add(oldValue.Id);
    }


    List<VIP_Brand_Preference__c> oldBrandPreferenceList = [SELECT Name, Village_Presence__r.Brand__r.Name FROM VIP_Brand_Preference__c WHERE Id IN:oldValueUpdatedVP];


    for(VIP_Brand_Preference__c theOldVBP : oldBrandPreferenceList){
      for (VIP_Brand_Preference__c BrandPreference : newMap){
        if(theOldVBP.Id == BrandPreference.Id){
       // System.AssertEquals(1,2,'-------' + theOldVBP.Village_Presence__r.Brand__r.Name);
          string brand = theOldVBP.Village_Presence__r.Brand__r.Name;
        
          BrandPreference.name = brand;
        }
      }
    }
  }
  
}