force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Risk_Factor__c/Risk_Factor__c.object-meta.xml
<CustomObject>
    <description>This is a temporary object used  to capture risk related information about brands presence in the village . The risk detail will be exported out and fed into Power BI to generate management dashboards.</description>
    <label>Risk Factor</label>
    <nameField>
        <displayFormat>RF-{0}</displayFormat>
        <label>Risk Factor #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Factor__c/fields/Brand_Risk_Description__c.field-meta.xml
<CustomField>
    <fullName>Brand_Risk_Description__c</fullName>
    <inlineHelpText>Add more detail as to why you think the brand is at risk.</inlineHelpText>
    <label>Brand Risk Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Risk_Factor__c/fields/Primary_Key__c.field-meta.xml
<CustomField>
    <fullName>Primary_Key__c</fullName>
    <label>Primary Key</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Risk_Factor__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the Village Presence to which this risk factor is associated to.</inlineHelpText>
    <label>Village Presence</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>Risk Factors</relationshipLabel>
    <relationshipName>Risk_Factors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Organisation__c</fullName>
    <description>The business unit within oracle</description>
    <inlineHelpText>The business unit within oracle</inlineHelpText>
    <label>Oracle Organisation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Source_Template_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Source_Template_Number__c</fullName>
    <description>The value used to map to an oracle template when sent to Oracle Fusion</description>
    <inlineHelpText>The value used to map to an oracle template when sent to Oracle Fusion</inlineHelpText>
    <label>Oracle Source Template Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Village Presence records must be linked to Brand accounts. Please ensure you are not linking the Deal/Village Presence to a Group</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Lease_ID__c.field-meta.xml
<CustomField>
    <fullName>Lease_ID__c</fullName>
    <externalId>true</externalId>
    <label>Lease ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/RiskFactorTriggerTest.cls
@isTest
public class RiskFactorTriggerTest{

      public static void setupData(){

        Profile riskProfile = [SELECT ID, Name FROM Profile WHERE Name = 'Leasing'];

        UserRole riskRole = new UserRole();
        riskRole.DeveloperName = 'CustomRole';
        riskRole.Name = 'Custom Role';
        insert riskRole;

        User riskUser = new User();
        riskUser.LastName = 'John';
        riskUser.Alias = 'jhnD';
        riskUser.Email = 'johnDoe@valueretai.com';
        riskUser.Username = 'johnDoe@valueretai.com';
        riskUser.CommunityNickname = 'johnvr';
        riskUser.UserRoleId = riskRole.Id;
        riskUser.ProfileId = riskProfile.Id;
        riskUser.Village__c = 'Bicester';
        riskUser.TimeZoneSidKey = 'GMT';
        riskUser.LocaleSidKey = 'en_GB';
        riskUser.EmailEncodingKey = 'ISO-8859-1';
        riskUser.LanguageLocaleKey = 'en_US';
        insert riskUser;

        system.runAs(riskUser){
        // Create a village
          Village__c vill = TestDataGenerator.setupVillage(false);
          vill.Oracle_Source_Template_Number__c = '123456';
          vill.Oracle_Organisation__c = 'SourceOrg';
          vill.Name = 'BicesterTestVillage';
          vill.village_code__c = 'BV';
          vill.CertSales_CertPeriod_Cut_Off_Days__c = 1;
          vill.CertSales_Report_Sales_Grace_Period_Days__c = 1; 
          insert vill;

          RecordType brandRecordType = [SELECT Id, Name FROM RecordType WHERE Name = 'Brand'];

          Account brand = new Account();
          brand.RecordTypeId = brandRecordType.Id;
          brand.Name = 'Brand 1';
          insert brand;

          Village_Presence__c presentBrand = new Village_Presence__c();
          presentBrand.Name = 'Brand1 in village';
          presentBrand.Brand__c = brand.Id;
          presentBrand.Village__c = vill.Id;
          presentBrand.Lease_ID__c = 'BRAND1BIC';
          insert presentBrand;
      }
    }
       
    @isTest static void TestRiskFactor() {
        
        setupData();
      	
        User john = [SELECT Id FROM User WHERE Alias='jhnD'];
        Risk_Factor__c risk = new Risk_Factor__c();
        system.runAs(john){
            Village_Presence__c vp = [SELECT Id FROM Village_Presence__c WHERE Lease_ID__c = 'BRAND1BIC'];
            
            // Create a risk factor record for a village presence
            risk.Village_Presence__c=vp.Id;
            risk.Brand_Risk_Description__c='VP_Risk_Factor_Test';
            insert risk;        
        }
        // Verify   
        Risk_Factor__c rf = [SELECT Id,Primary_Key__c,Village_Presence__c FROM Risk_Factor__c WHERE Id= :risk.Id];      
        //System.assertEquals(rf.Primary_Key__c, risk.Village_Presence__c);
    }    
}