force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Village Presence records must be linked to Brand accounts. Please ensure you are not linking the Deal/Village Presence to a Group</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deal Pending</fullName>
            </value>
            <value>
                <fullName>Trading</fullName>
            </value>
            <value>
                <fullName>in Refit</fullName>
            </value>
            <value>
                <fullName>Exited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/GenerateLeaseIdExtract.cls
// Utilitiy class for ad hoc calls to the GetLeaseList Microservice
// Can be invoked from Developer console, column selections should remain
// unchanged, but where clause can be modified as required
// Example:

/* string q = 'select Id, Name, Brand__r.Id, Brand__r.Name, Status__c, Village__r.Village_Code__c from Village_Presence__c ';
q += 'where Village__c in (select Id from Village__c where Name = \'La Roca\')';
q += 'order by Name';

Database.executeBatch(new generateLeaseIdExtract(q), 90);
*/

global class GenerateLeaseIdExtract implements Database.Batchable<sObject>, Database.AllowsCallouts {
  
    global final String query;
     
     
    //constructor
    global generateLeaseIdExtract (String q) {
        query = q;   
    }
     
    //start
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }
     
     
    //execute
    global void execute(Database.BatchableContext BC, List<sObject> scope) {

        string output = '';
        
        for (Sobject obj :scope){
        
            string status = string.valueOf(obj.get('Status__c'));
            string brandId = string.valueOf(obj.getSobject('Brand__r').get('Id'));
            string brand = string.valueOf(obj.getSobject('Brand__r').get('Name'));
            string vpId = string.valueOf(obj.get('Id'));
            string vpName = string.valueOf(obj.get('Name'));
            string villageCode = string.valueOf(obj.getSobject('Village__r').get('Village_Code__c'));
            string leaseId = '';
            string error = '';
            
            if (test.isRunningTest())
                    brandId = 'SF_TEST';
            
            string xmlLease = apiService.readLeaseList(brandId, villageCode, system.today());
            if (xmlLease.indexOf('Error') > -1){
                error = xmlLease;
            } else {
                list<apiLease.cls_LeaseItem> leaseList = apiLease.parseXML(xmlLease);
                if (leaseList.size() == 1){
                    leaseId = leaseList[0].leaseId;
                } else {
                    for (apiLease.cls_LeaseItem lease :leaseList){
                        leaseId += lease.leaseId + ',';
                    }
                }   
            
            }    
            output += brand + ',' + brandId + ',' + vpId + ',' + vpName + ',' + status + ',' + leaseId + ',' + error + '\r\n';        
            
        
        }

        system.debug(output);
    }
  
  
    //finish
    global void finish(Database.BatchableContext BC) {
    }
    
}