force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Product_Loan__c/Product_Loan__c.object-meta.xml
<CustomObject>
    <description>Denotes an agreement between a brand, and the marketing team, to facilitate the loaning of products for marketing purposes.</description>
    <label>Product Loan</label>
    <nameField>
        <label>Product Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Loan__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The brand that is loaning the items</description>
    <inlineHelpText>The brand that is loaning the items</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Brands can be related to the product loan</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Loans</relationshipLabel>
    <relationshipName>Product_Loans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Loan__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GBP</fullName>
                <label>GBP - British Pound</label>
            </value>
            <value>
                <fullName>EUR</fullName>
                <label>EUR - Euro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Loan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the product loan</description>
    <inlineHelpText>The status of the product loan</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request for collection</fullName>
                <default>true</default>
                <label>Request for collection</label>
            </value>
            <value>
                <fullName>Collected and signed for</fullName>
            </value>
            <value>
                <fullName>Returned but damaged</fullName>
            </value>
            <value>
                <fullName>Returned and signed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Loan_Item__c/Product_Loan_Item__c.object-meta.xml
<CustomObject>
    <description>An individual item in the product loan</description>
    <label>Product Loan Item</label>
    <nameField>
        <label>Product Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Loan Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Loan_Item__c/fields/Product_Loan__c.field-meta.xml
<CustomField>
    <fullName>Product_Loan__c</fullName>
    <description>The product loan that the item belongs to</description>
    <inlineHelpText>The product loan that the item belongs to</inlineHelpText>
    <label>Product Loan</label>
    <referenceTo>Product_Loan__c</referenceTo>
    <relationshipLabel>Product Loan Items</relationshipLabel>
    <relationshipName>Product_Loan_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProductLoanFormPDFExtensiontest.cls
@isTest
Public Class ProductLoanFormPDFExtensiontest{

	@isTest static void test_method_one() {

    Product_Loan__c pl = new Product_Loan__c();

    ApexPages.StandardController sc = new ApexPages.StandardController(pl);  
    ProductLoanFormPDFExtension plfcon = new ProductLoanFormPDFExtension(sc);

    system.assert(plfcon.html.startsWith('<table id="emptytable"'));

	}

	@isTest static void test_method_two() {

	Account testAccount = new Account(name = 'Test Account XYZ' , RecordTypeId =  Schema.SObjectType.Account.RecordTypeInfosByName.get('Brand').RecordTypeId);
    insert testAccount;

    Product_Loan__c pl = new Product_Loan__c();
    pl.brand__c = testAccount.id;
    pl.Name = 'Test';
    pl.status__c = 'Request for collection';
    pl.currency__c = 'GBP';
    insert pl;

    Product_Loan_Item__c pli = new Product_Loan_Item__c();
    pli.Name = 'test';
    pli.Product_Loan__c = pl.id;
    insert pli;


    ApexPages.StandardController sc = new ApexPages.StandardController(pl);  
    ProductLoanFormPDFExtension plfcon = new ProductLoanFormPDFExtension(sc);

    system.assert(plfcon.html.startsWith('<table id="productItemTable"'));

	}


}