force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Daily_Sale__c/Daily_Sale__c.object-meta.xml
<CustomObject>
    <label>Daily Sale</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>Daily Sale Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Sale__c/fields/Certification_Batch__c.field-meta.xml
<CustomField>
    <fullName>Certification_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certification Batch</label>
    <referenceTo>Daily_Sales_Certification_Batch__c</referenceTo>
    <relationshipLabel>Daily Sales</relationshipLabel>
    <relationshipName>Daily_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Certified_Amount__c.field-meta.xml
<CustomField>
    <fullName>Certified_Amount__c</fullName>
    <description>Maps to MRI: CERAMOUNT</description>
    <inlineHelpText>The total Certified Sales Amount for this date that is submitted by the Brand Head Office.  Once Approved by VR Finance this will integrate across to MRI.</inlineHelpText>
    <label>Certified Amount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Certified_Amount_Discount__c.field-meta.xml
<CustomField>
    <fullName>Certified_Amount_Discount__c</fullName>
    <description>This is the field that should be integrated with MRI. The main goal is to avoid that this formula field never is blank. However it is utilized on the calculation of Certified Amount.</description>
    <formula>IF(ISBLANK(Certified_Amount_Discount_Input__c),IF(NOT(ISBLANK(NET_Value_of_Discounts__c)),NET_Value_of_Discounts__c,0),Certified_Amount_Discount_Input__c)</formula>
    <label>Certified Amount Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Certified_Amount_NetTotal__c.field-meta.xml
<CustomField>
    <fullName>Certified_Amount_NetTotal__c</fullName>
    <description>This is the field that should be integrated with MRI. The main goal is to avoid that this formula field never is blank. However it is utilized on the calculation of Certified Amount.</description>
    <formula>IF(ISBLANK(Certified_Amount_NetTotal_Input__c),IF(NOT(ISBLANK(Total_NET_SALES__c)),Total_NET_SALES__c ,0),Certified_Amount_NetTotal_Input__c)</formula>
    <label>Certified Amount NetTotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/NET_Value_of_Discounts__c.field-meta.xml
<CustomField>
    <fullName>NET_Value_of_Discounts__c</fullName>
    <inlineHelpText>NET Value of Discounts</inlineHelpText>
    <label>NET Value of Discounts</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_End_Date__c</fullName>
    <description>MRI: Daily Sales Certification Batch Start Period</description>
    <formula>Certification_Batch__r.Period_End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CertBatchEndDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <description>MRI: Daily Sales Certification Batch Start Period</description>
    <formula>Certification_Batch__r.Period_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CertBatchStartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <color>#FF0000</color>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Reported Incomplete</fullName>
                <color>#FF9900</color>
                <label>Reported Incomplete</label>
            </value>
            <value>
                <fullName>Reported Confirmed</fullName>
                <color>#33CC00</color>
                <label>Reported Confirmed</label>
            </value>
            <value>
                <fullName>TOR</fullName>
            </value>
            <value>
                <fullName>Certified Pending</fullName>
            </value>
            <value>
                <fullName>Certified Approved</fullName>
            </value>
            <value>
                <fullName>Certified Complete</fullName>
            </value>
            <value>
                <fullName>Certified Re-opened</fullName>
            </value>
            <value>
                <fullName>Audited</fullName>
                <isActive>false</isActive>
                <label>Audited</label>
            </value>
            <value>
                <fullName>Certified</fullName>
                <isActive>false</isActive>
                <label>Certified</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
                <isActive>false</isActive>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Not Confirmed</fullName>
                <isActive>false</isActive>
                <label>Not Confirmed</label>
            </value>
            <value>
                <fullName>Reported Complete</fullName>
                <isActive>false</isActive>
                <label>Reported Complete</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>Daily Sales</relationshipLabel>
    <relationshipName>Daily_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Total_NET_SALES__c.field-meta.xml
<CustomField>
    <fullName>Total_NET_SALES__c</fullName>
    <inlineHelpText>This is the total sales for the day including all types of sales (e.g. Special Curated Selection Sales, Current Season Bestsellers Sales)</inlineHelpText>
    <label>Total NET SALES</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Trading_Date__c.field-meta.xml
<CustomField>
    <fullName>Trading_Date__c</fullName>
    <description>maps to MRI: TRADEDATE</description>
    <label>Trading Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/recordTypes/Current.recordType-meta.xml
<RecordType>
    <fullName>Current</fullName>
    <active>true</active>
    <description>Record Type replacing EDITABLE</description>
    <label>Current</label>
</RecordType>

force-app/main/default/objects/Daily_Sale__c/recordTypes/Full_Price.recordType-meta.xml
<RecordType>
    <fullName>Full_Price</fullName>
    <active>true</active>
    <label>Current Season Bestsellers</label>
</RecordType>

force-app/main/default/objects/Daily_Sale__c/recordTypes/Full_Price_NOT_Editable.recordType-meta.xml
<RecordType>
    <fullName>Full_Price_NOT_Editable</fullName>
    <active>true</active>
    <description>When dailySales record is not editable and no actions are available</description>
    <label>Current Season Bestsellers NOT Editable</label>
</RecordType>

force-app/main/default/objects/Daily_Sale__c/recordTypes/Gross.recordType-meta.xml
<RecordType>
    <fullName>Gross</fullName>
    <active>true</active>
    <description>Figures entered in Gross</description>
    <label>Gross</label>
</RecordType>

force-app/main/default/objects/Daily_Sale__c/recordTypes/Historical.recordType-meta.xml
<RecordType>
    <fullName>Historical</fullName>
    <active>true</active>
    <description>Record Type replacing NOT EDITABLE</description>
    <label>Historical</label>
</RecordType>

force-app/main/default/objects/Daily_Sale__c/recordTypes/Net.recordType-meta.xml
<RecordType>
    <fullName>Net</fullName>
    <active>true</active>
    <description>Figures are entered by the Brand in NET</description>
    <label>Net</label>
</RecordType>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/Daily_Sales_Certification_Batch__c.object-meta.xml
<CustomObject>
    <description>Brand Portal object that will save all records related to the certifications</description>
    <label>Daily Sales Certification Batch</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Sales Certification Batches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_End_Date__c</fullName>
    <inlineHelpText>The end date for this Certification Batch</inlineHelpText>
    <label>Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <inlineHelpText>The start date for this Certification Batch</inlineHelpText>
    <label>Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status of this Certification Batch</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Being Prepared</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Batch Complete</fullName>
            </value>
            <value>
                <fullName>Re-opened</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Village Presence</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/recordTypes/Finish.recordType-meta.xml
<RecordType>
    <fullName>Finish</fullName>
    <active>true</active>
    <label>Finish</label>
</RecordType>

force-app/main/default/objects/LogFile__c/LogFile__c.object-meta.xml
<CustomObject>
    <label>LogFile</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>LogFile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LogFiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogFile__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B2B Report Emails</fullName>
            </value>
            <value>
                <fullName>ETLWebService</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Village Presence records must be linked to Brand accounts. Please ensure you are not linking the Deal/Village Presence to a Group</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/CertSales_CertPeriod_Type__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Type__c</fullName>
    <inlineHelpText>The Sales Certification Batch period type will either be monthly or quarterly</inlineHelpText>
    <label>Sales Cert Period Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CertSales_Active__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deal Pending</fullName>
            </value>
            <value>
                <fullName>Trading</fullName>
            </value>
            <value>
                <fullName>in Refit</fullName>
            </value>
            <value>
                <fullName>Exited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/DailySales_Batch_Script.cls
/* Script to update TOR Records permissions, Change record types to Not Editable and for Certification Calculation on old records.
*/

global class DailySales_Batch_Script implements Database.Batchable<sObject>{
    
    /*private static final id dsNetRecordTypeId = Schema.SObjectType.Daily_Sale__c.RecordTypeInfosByName.get('Net').RecordTypeId;
    private static final id dsFullPriceRecordTypeId = Schema.SObjectType.Daily_Sale__c.RecordTypeInfosByDeveloperName.get('Full_Price').RecordTypeId;
    private static final id dsGrossRecordTypeId = Schema.SObjectType.Daily_Sale__c.RecordTypeInfosByName.get('Gross').RecordTypeId;
    private static final id dsFBCoversRecordTypeId = Schema.SObjectType.Daily_Sale__c.RecordTypeInfosByName.get('F & B Covers').RecordTypeId;
    private static final id dsNetNERecordTypeId = Schema.SObjectType.Daily_Sale__c.RecordTypeInfosByName.get('Net NOT Editable').RecordTypeId;
    private static final id dsFullPriceNERecordTypeId = Schema.SObjectType.Daily_Sale__c.RecordTypeInfosByDeveloperName.get('Full_Price_NOT_Editable').RecordTypeId;
    private static final id dsGrossNERecordTypeId = Schema.SObjectType.Daily_Sale__c.RecordTypeInfosByName.get('Gross NOT Editable').RecordTypeId;
    private static final id dsFBCoversNERecordTypeId = Schema.SObjectType.Daily_Sale__c.RecordTypeInfosByName.get('F & B Covers NOT Editable').RecordTypeId;*/
    
    private static final id dsCurrentRecordTypeId = Schema.SObjectType.Daily_Sale__c.RecordTypeInfosByDeveloperName.get('Current').RecordTypeId;
    private static final id dsHistoricalRecordTypeId = Schema.SObjectType.Daily_Sale__c.RecordTypeInfosByDeveloperName.get('Historical').RecordTypeId;
    
    private List<string> brandList {get;set;}
    private string village {get;set;}
    private string initialDateValue {get;set;}
    private string endDateValue {get;set;}
    
    global DailySales_Batch_Script(List<string> brandQuery, String villageQuery, String initialDate, String endDate) {
        brandList = brandQuery;
        village = villageQuery;
        initialDateValue = initialDate;
        endDateValue = endDate;
    }  
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        
        if(brandList.isEmpty() || village == null || initialDateValue == null || endDateValue == null){
            logFile__c log = new logFile__c();
            log.Body__c = 'Brand List size: ' + brandList.size()+ ' Village: ' + village;
            log.Type__c = 'DailySales UAT Script ' + village;
            insert log;
            system.debug('Empty List');
            return NULL;
        }else{ 
            String query = 'SELECT ID, Name, RecordTypeId, Status__c, Trading_Date__c, Certified_Amount__c, Total_NET_SALES__c,';
            query += ' NET_Value_of_Discounts__c, Certified_Amount_NetTotal__c, Store__c, Store__r.Brand__c, Store__r.Village__c, Store__r.Name,';
            query += ' Certified_Amount_Discount__c, Certification_Batch__c, Certification_Batch__r.Name,';
            query += ' Certification_Batch__r.Period_Start_Date__c, Certification_Batch__r.Period_End_Date__c';
            query += ' FROM Daily_Sale__c';
            query += ' WHERE (Store__r.Village__r.Name = \'' + village + '\' )';
            query += ' AND (';
            for(string brand : brandList){
                query +=  ' Store__r.Brand__r.Name =\'' + brand + '\' OR';
            }
            query = query.removeEnd('OR');
            query += ')';
            query += ' AND (Trading_Date__c >= ' + initialDateValue + ' AND Trading_Date__c <=' + endDateValue + ')';
            system.debug(query);
            return Database.getQueryLocator(query);
        }
    }
    
    public void execute(Database.BatchableContext BC, List<Daily_Sale__c> scope){
        Set<Id> setIdDS = new Set<Id>();
        Map<Id, Map<Date, Id>> dscbByVPStartDate = new Map<Id, Map<Date, Id>>();
        Map<Id, Map<Date, Id>> dscbByVPCloseDate = new Map<Id, Map<Date, Id>>();
        Map<Id, String> certPeriod = new Map<Id, String>();
        List<Village_Presence__c> theVPs = new List<Village_Presence__c>();
        List<Daily_Sales_Certification_Batch__c> allDSCB = new List<Daily_Sales_Certification_Batch__c>();

        String queryVillagePresence = 'SELECT Id, CertSales_CertPeriod_Type__c FROM Village_Presence__c WHERE (';
        for(string brand : brandList){
                queryVillagePresence +=  ' Brand__r.Name =\'' + brand + '\' OR';
            }
        queryVillagePresence = queryVillagePresence.removeEnd('OR');
        queryVillagePresence += ') AND Village__r.Name = \'' + village + '\'';
            system.debug(queryVillagePresence);
        try{
            theVPs = Database.query(queryVillagePresence);
        } catch (QueryException e){
            system.debug('No Village Presence return with the brandList and village variables informed');
        }

        try{
            allDSCB = [SELECT Id, Period_Start_Date__c, Period_End_Date__c, Village_Presence__c, Name
                                                    FROM Daily_Sales_Certification_Batch__c
                                                    WHERE Village_Presence__c = :theVPs];
                                                    system.debug(allDSCB);
        } catch (QueryException e){
            system.debug('No Daily Sales Certification Batch exists for the brandList and village variables informed');
        }
        
        for(Village_Presence__c vp : theVPs){
            certPeriod.put(vp.Id, vp.CertSales_CertPeriod_Type__c);
        }
        
        // Set the Start Date in the beggining of the month - It should only be utilised once (first time in production)
        if(!allDSCB.isEmpty()){
            for(Daily_Sales_Certification_Batch__c dscb : allDSCB){
                if(certPeriod.get(dscb.Village_Presence__c) == 'Monthly'){
                    if(!((dscb.Period_Start_Date__c.toStartOfMonth()).isSameDay(dscb.Period_Start_Date__c))){
                        dscb.Period_Start_Date__c = dscb.Period_Start_Date__c.toStartOfMonth();
                    }
                } else if (certPeriod.get(dscb.Village_Presence__c) == 'Quarterly'){
                    Integer month = dscb.Period_Start_Date__c.month();
                    Integer year = dscb.Period_Start_Date__c.year();
                    if(month == 1 || month == 2 || month == 3){
                        dscb.Period_Start_Date__c = Date.newInstance(year, 1, 1);
                    } else if(month == 4 || month == 5 || month == 6){
                        dscb.Period_Start_Date__c = Date.newInstance(year, 4, 1);
                    } else if(month == 7 || month == 8 || month == 9){
                        dscb.Period_Start_Date__c = Date.newInstance(year, 7, 1);
                    } else if(month == 10 || month == 11 || month == 12){
                        dscb.Period_Start_Date__c = Date.newInstance(year, 10, 1);
                    }
                }
            }

            try{
                update allDSCB;
            } catch (Exception e){
                LogFile__c log = new LogFile__c();
                log.Body__c = e.getMessage();
                log.Type__c = 'Error when try to update DSCB: ' + brandList;
                insert log;
            }
            
            for(Daily_Sales_Certification_Batch__c dscb : allDSCB){
                if(dscb.Period_Start_Date__c != NULL && dscb.Period_End_Date__c != NULL){
                    if(!dscbByVPStartDate.containsKey(dscb.Village_Presence__c) || !dscbByVPCloseDate.containsKey(dscb.Village_Presence__c)){
                        dscbByVPStartDate.put(dscb.Village_Presence__c, new Map<Date, Id>());
                        dscbByVPCloseDate.put(dscb.Village_Presence__c, new Map<Date, Id>());
                    }
                    dscbByVPStartDate.get(dscb.Village_Presence__c).put(dscb.Period_Start_Date__c, dscb.Id);
                    dscbByVPCloseDate.get(dscb.Village_Presence__c).put(dscb.Period_End_Date__c, dscb.Id);
                }
            }
        } else {
            LogFile__c log = new LogFile__c();
            log.Body__c = 'No Daily Sales Certification Batch exists for the brandList:' + brandList;
            log.Type__c = 'Batch Script error';
            insert log;
        }
        
        for(Daily_Sale__c sc : scope){
            if(sc.Status__c == 'TOR' || sc.Status__c == 'Certified Pending' || sc.Status__c == 'Certified Approved' ||
               sc.Status__c == 'Certified Complete' || sc.Status__c == 'Certified Re-opened'){
                   /*if(sc.RecordTypeId == dsNetRecordTypeId){
                       sc.RecordTypeId = dsNetNERecordTypeId;
                   } else if(sc.RecordTypeId == dsFullPriceRecordTypeId){
                       sc.RecordTypeId = dsFullPriceNERecordTypeId;
                   } else if(sc.RecordTypeId == dsGrossRecordTypeId){
                       sc.RecordTypeId = dsGrossNERecordTypeId;
                   } else if(sc.RecordTypeId == dsFBCoversRecordTypeId){
                       sc.RecordTypeId = dsFBCoversNERecordTypeId;
                   }*/
                   if (sc.RecordTypeId == dsCurrentRecordTypeId) {
                       sc.RecordTypeId = dsHistoricalRecordTypeId;
                   }
                   setIdDS.add(sc.Id);    
               }
            
            if(sc.Certified_Amount__c == NULL){
                if(sc.Total_NET_SALES__c != NULL && sc.NET_Value_of_Discounts__c != NULL){
                    sc.Certified_Amount__c = sc.Certified_Amount_NetTotal__c + sc.Certified_Amount_Discount__c;
                }
            }
            
            if(sc.Certification_Batch__c == NULL && !dscbByVPStartDate.isEmpty() && !dscbByVPCloseDate.isEmpty()){
                for(Date mapValueStart : dscbByVPStartDate.get(sc.Store__c).keySet()){
                    for(Date mapValueClose : dscbByVPCloseDate.get(sc.Store__c).keySet()){
                        if(sc.Trading_Date__c >= mapValueStart && sc.Trading_Date__c <= mapValueClose &&
                           dscbByVPStartDate.get(sc.Store__c).get(mapValueStart) == dscbByVPCloseDate.get(sc.Store__c).get(mapValueClose)){
                               sc.Certification_Batch__c = dscbByVPStartDate.get(sc.Store__c).get(mapValueStart);
                           }
                    }
                }
            }
        }
        
        update scope;
        
        CalculationOfAmounts.changesAmounts(scope);
        
        if(!setIdDS.isEmpty()){
            try{
                DailySaleTriggerHelper.ProcessShares(scope, setIdDS);   
            }catch(Exception e){
                logFile__c log = new logFile__c();
                log.Body__c = e.getMessage();
                log.Type__c = 'DailySales UAT Script ' + village;
                insert log;
            }
        }
    }
    
    public void finish(Database.BatchableContext BC){
        
    }
    
}