force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Unit assigned to this opportunity, this is synchronized with the Unit on the Contract when the Unit is formally committed to the brand</inlineHelpText>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Village__c</field>
            <operation>equals</operation>
            <valueField>$Source.Village__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the actual village where this opportunity exists</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Auto populated from Village and Brand</description>
    <label>Village Presence</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Exit.recordType-meta.xml
<RecordType>
    <fullName>Exit</fullName>
    <active>true</active>
    <businessProcess>Exit Process</businessProcess>
    <description>Deals for Brands that are exiting the village</description>
    <label>Exit</label>
</RecordType>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the detail of all units in VR Villages</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>...</description>
    <inlineHelpText>Select the Village where this unit lives</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHelper.cls
public with sharing class OpportunityTriggerHelper {

	// This method updates the Opportunity name with the format, <<Brand in Village, Unit (if applicable)>>
	// When called from trigger after insert, the second input argument oppList will be null.
	// When called from OpportunityProjectionYieldCalculator class as a result of an update, the first input
	// argument oppMap will be null and the oppList will already be populated.
	// This method also sets/creates a village presence reference for the opportunity. 
	public static boolean hasRun = false;
	
	public static list<Opportunity> updateOpportunityName(map<Id, Opportunity> oppMap, list<Opportunity> oppList){
		
		if (hasRun){
			return null;
		} else {
			hasRun = true;
		}

		
		list<Opportunity> returnList = new list<Opportunity>();
		
		if (oppList == null){	
			oppList = [select  Name, RecordType.Name, Account.Name, village__r.Name, unit__r.Name, village_presence__c 
										from Opportunity
										where Id in:oppMap.keySet()
										and IsWon = false];
		}								
		if (oppList != null){
			
			map<string, list<string>> oppVillageMap = new map<string, list<string>>();
			for (Opportunity opp :oppList){
				string recType = opp.RecordType.Name;
				string typeName = '';
				if (String.isnotBlank(recType)){
					typeName = recType.split(' ')[0]; //take first word of record type
				}
				string name = opp.Account.Name + ' in ' + opp.village__r.Name ;
				if (string.isnotBlank(opp.unit__r.name)){
					name += ' (' + opp.unit__r.name + ')';				
				}
				opp.Name = name + ' - ' + typeName;
				// prepare search parameters for village presence search
				list<string> villageList = oppVillageMap.get(opp.Account.Name);
				if (villageList == null){
					villageList = new list<string>();
				}
				villageList.add(opp.Village__r.name);
				if (!opp.IsWon)
				oppVillageMap.put(opp.Account.Name, villageList);				
			}
	
			if (!oppVillageMap.isEmpty()){
				// search for associated village presence records
				map<string, map<string,Village_Presence__c>> vpMap = VillagePresenceUtilities.getVillagePresence(oppVillageMap);

				if (vpMap != null){
					for (Opportunity opp :oppList){
						map<string, Village_Presence__c> oppVpMap = vpMap.get(opp.Account.Name);
					
						Village_Presence__c vp = null;
						if (oppVpMap != null){
							vp = oppVpMap.get(opp.Village__r.name);
							// set opportunity village presence reference
							if (vp != null){
								opp.Village_Presence__c = vp.Id;
								id RecId = [SELECT id from RecordType where name = 'Exit'].id;
								if(opp.RecordTypeid == RecId){
									opp.Unit__c = vp.Unit__c;
								}
							} else {
								// CC - 06/08/2014 - Need to Fix!! - causes too many soql statements governor limit error when bulk update to opps
								// and new VP is needed.
system.debug(' @@@ vp ... ' + opp.Account.Id + ' ---  ' +  opp.Village__r.name);	

								vp = villagePresenceUtilities.createVillagePresence(opp.Account.Id, opp.Village__r.name);	
								opp.Village_Presence__c = vp.Id;
								
								map<string,Village_Presence__c> newVPMap = new map<string, Village_Presence__c>();
								newVPMap = vpMap.get(opp.Account.Name);
								if (newVPMap == null){
									newVPMap = new map<string, Village_Presence__c>();
								}
								newVPMap.put(opp.Village__r.name, vp);
								
								vpMap.put(opp.Account.Name, newVPMap);
							}	
						}
						
						
					}
				}
			}
			if (oppMap != null && oppList != null){
				update oppList;			
			} else {
				returnList = oppList;
			}
		}										
		
		return returnList;	


	}


}