force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <description>A Group or Parent Account for Brand Accounts</description>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/Campaign/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>only valid for redeemable campaigns</description>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Local_Language__c.field-meta.xml
<CustomField>
    <fullName>Village_Local_Language__c</fullName>
    <inlineHelpText>Select the default language to be used for B2C communications</inlineHelpText>
    <label>Village Local Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataGenerator.cls
/**
 * This class contains static methods for creating test data for Unit Tests
 */
@isTest
public class TestDataGenerator {

	/**
	 * Setup Admin User for use in RunAs() method.
	 */
	public static User setupAdminUser(Boolean insertToDatabase){
		system.debug('Setting up Admin User');
		User adminUser = new User(alias='BOSS1',email= 'bossman@valueretail.com', emailencodingkey= 'UTF-8',
	                              lastname= 'bossman', firstname= 'the', languagelocalekey= 'en_US', localesidkey= 'en_GB',
	                              profileid = Properties.SYSTEM_ADMINISTRATOR_PROFILE, timezonesidkey= 'Europe/London',
	                              username= 'objSetUpUser1@valueretail.com', isActive = true );
	    if (insertToDatabase) {
	    	insert adminUser;
	    }
	    return adminUser;
	}
	 
	/**
	 * Setup Single User
	 */
	public static User setupUser(String userName, UserRole userRole, Profile userProfile, Boolean isActive, Boolean insertToDatabase) {
		system.debug('Setting up User: ' + userName);
		String truncUserName;
		if (userName.length() > 5) {
			truncUserName = userName.substring(0, 5);
		} else {
			truncUserName = userName;
		}

		User newUser = new User(LastName = userName,
			Alias = truncUserName.toUpperCase() + '123',
			Email = userName + '@valueretail.com',
			Username = userName + '@valueretail.com',
			Communitynickname = userName + 'Nickname',
			userroleId = userRole.Id,
			profileId = userProfile.Id,
			timezonesidkey = 'Europe/London',
			emailencodingkey = 'UTF-8',
			languagelocalekey = 'en_US',
			localesidkey = 'en_GB',
			isActive = isActive);

	    if (insertToDatabase) {
	    	insert newUser;
	    }
		return newUser;
	}

	/**
	 * Setup a Queue
	 */
	public static Group setUpQueue(String queueName, Boolean insertToDatabase){
		system.debug('Setting up Queue: ' + queueName);
    	Group newQueue = new Group(Name = 'ZZ' + queueName, Type = 'Queue');
	    if (insertToDatabase) {
	    	insert newQueue;
	    }
		return newQueue;
	}

	/**
	 * Setup Queue Members
	 */
	public static List<GroupMember> setUpQueueMembers(String queueId, List<User> userList, Boolean insertToDatabase){
		List<GroupMember> memberList = new List<GroupMember>();
		for (User u : userList) {
			GroupMember newQueueMember = new GroupMember(GroupId = queueId, UserOrGroupId = u.Id);
			memberList.add(newQueueMember);
		}
	    if (insertToDatabase) {
			insert memberList;
	    }
		return memberList;
	}

	/**
	 * Setup Person Account
	 */
    public static Account setupPersonAccount(Integer identifier, Boolean insertToDatabase) {
        Account testAccount = new Account(RecordTypeId = Properties.PERSON_ACCOUNT_RECORD_TYPE,
                                          LastName = 'Test111' + identifier,
                                          FirstName = 'John',
                                          Salutation = 'Mr',
                                          PersonEmail = 'testt2387@sdfh.com');
	    if (insertToDatabase) {
			insert testAccount;
	    }
        return testAccount;
    }
 
 	/**
	 * Setup B2B Account
	 */
    public static Account setupB2BAccount(Integer identifier, Boolean insertToDatabase) {
        Account testAccount = new Account(name = 'Test Account' + identifier,
                                          RecordTypeId =  Schema.SObjectType.Account.RecordTypeInfosByName.get('Brand').RecordTypeId);
	    if (insertToDatabase) {
			insert testAccount;
	    }
        return testAccount;
    }
    
    
	/**
	 * Setup Contact
	 */
	 /*
    public static Contact setupContact(Integer identifier, Id testAccountId, Boolean insertToDatabase) {
        Contact testContact = new Contact(AccountId = testAccountId,
                                          LastName = 'Test111' + identifier,
                                          FirstName = 'John',
                                          Salutation = 'Mr',
                                          Email = 'testt2387@sdfh.com',
                                          Mailing_Country_In_English__c = 'UNITED KINGDOM',
                                          High_Spender_Status__c = 'None',
                                          EmailReaderStatus__c = 'Unknown',
                                          LeadSource = 'Village Registration Card');
	    if (insertToDatabase) {
			insert testContact;
	    }
        return testContact;
    }
    */
    
    /**
     * Setup Campaign
     */
     /*
    public static Campaign setupCampaign(Integer identifier, Boolean insertToDatabase) {
    	Date startDate = system.today();
    	startDate = startDate.addDays(-5);
    	Date endDate = system.today();
    	endDate = endDate.addDays(5);
    	Campaign testCampaign = new Campaign(Name = 'TESTCAMPAIGN' + identifier,
    										 RecordTypeId = CampaignAfterSupport.DEFAULT_MEMBERS_B2C_CAMPAIGN_RT, 
                                             Type = CampaignAfterSupport.DEFAULT_MEMBERS_CAMPAIGN_TYPE,
                                             IsActive = true, StartDate = startDate, EndDate = endDate,
                                             Active_Redemption_Segments__c = true,
                                             Campaign_Member_Redemption_Count__c = 2);
	    if (insertToDatabase) {
			insert testCampaign;
	    }
        return testCampaign;
    }
    */

    /**
     * Setup Campaign Member
     */
    public static CampaignMember setupCampaignMember(Id contactId, Id campaignId, Boolean insertToDatabase) {
        CampaignMember testCM = new CampaignMember(ContactId = contactId, CampaignId = campaignId, Status = 'Sent');
	    if (insertToDatabase) {
			insert testCM;
	    }
        return testCM;
    }
    
    /**
     * Setup Village Record
     */
    
	public static Village__c setupVillage(Boolean insertToDatabase) {
    	Village__c testVillage = new Village__c(Village_Code__c = 'ZZ', Name = 'TESTVILLAGE', Village_Local_Language__c = 'English', CertSales_CertPeriod_Cut_Off_Days__c = 1, CertSales_Report_Sales_Grace_Period_Days__c = 1);
	    if (insertToDatabase) {
    		insert testVillage;
	    }
	    return testVillage;
	}
	
}