force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Product_Loan__c/Product_Loan__c.object-meta.xml
<CustomObject>
    <description>Denotes an agreement between a brand, and the marketing team, to facilitate the loaning of products for marketing purposes.</description>
    <label>Product Loan</label>
    <nameField>
        <label>Product Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Loan__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The brand that is loaning the items</description>
    <inlineHelpText>The brand that is loaning the items</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Brands can be related to the product loan</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Loans</relationshipLabel>
    <relationshipName>Product_Loans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Loan__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GBP</fullName>
                <label>GBP - British Pound</label>
            </value>
            <value>
                <fullName>EUR</fullName>
                <label>EUR - Euro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Loan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the product loan</description>
    <inlineHelpText>The status of the product loan</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request for collection</fullName>
                <default>true</default>
                <label>Request for collection</label>
            </value>
            <value>
                <fullName>Collected and signed for</fullName>
            </value>
            <value>
                <fullName>Returned but damaged</fullName>
            </value>
            <value>
                <fullName>Returned and signed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductLoanTriggerHandlertest.cls
@IsTest
Public Class ProductLoanTriggerHandlertest{

	@TestSetup
    public static void SetupData(){

          Account testAccount = new Account(name = 'Test Account XYZ' , RecordTypeId =  Schema.SObjectType.Account.RecordTypeInfosByName.get('Brand').RecordTypeId);
          insert testAccount;
    
    }

    @isTest
    static void inserttest(){

    	Account acct = [SELECT Id, Name from Account where Name = 'Test Account XYZ'];

    	Product_Loan__c pl = new Product_Loan__c();
    	pl.name = 'Test Loan 1';
    	pl.brand__c = acct.id;
    	pl.status__c = 'Request For Collection';
    	pl.currency__c = 'GBP';

        test.starttest();
    	Insert pl;
    	List<Product_Loan__c> plList = new List<Product_Loan__c>{pl};
        ProductLoanTriggerHandler.isBeforeisInsert(plList);
        test.stoptest();

        //Product_Loan__c pLoan = [SELECT ID, Name,CurrencyIsoCode FROM Product_Loan__c WHERE ID =:pl.id];
        Product_Loan__c pLoan = plList.get(0);
        system.assertEquals('GBP', pLoan.CurrencyIsoCode, 'Error');

    }

    @isTest
    static void updatetest(){

    	Account acct = [SELECT Id, Name from Account where Name = 'Test Account XYZ'];

    	Product_Loan__c pl = new Product_Loan__c();
    	pl.name = 'Test Loan 1';
    	pl.brand__c = acct.id;
    	pl.status__c = 'Request For Collection';
    	pl.currency__c = 'GBP';

        test.starttest();
    	Insert pl;

    	pl.currency__c = 'EUR ';
    	//update pl;
    	List<Product_Loan__c> plList = new List<Product_Loan__c>{pl};
        ProductLoanTriggerHandler.isBeforeUpdate(plList);
        test.stoptest();

        //Product_Loan__c pLoan = [SELECT ID, Name,CurrencyIsoCode FROM Product_Loan__c WHERE ID =:pl.id];
        Product_Loan__c pLoan = plList.get(0);
        system.assertEquals('EUR', pLoan.CurrencyIsoCode, 'Error');

    }


}