force-app/main/default/objects/Account/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <description>A Group or Parent Account for Brand Accounts</description>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/HFS_Item__c/HFS_Item__c.object-meta.xml
<CustomObject>
    <label>SCS Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SCS Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCS Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Item__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Village_Presence__c.Village__r.Name</field>
            <operation>equals</operation>
            <valueField>$User.Village__c</valueField>
        </filterItems>
        <filterItems>
            <field>Village_Presence__c.Status__c</field>
            <operation>equals</operation>
            <value>Trading</value>
        </filterItems>
        <infoMessage>Please select a Brand from within your village</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>SCS Items</relationshipLabel>
    <relationshipName>HFS_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Item__c/fields/Runner__c.field-meta.xml
<CustomField>
    <fullName>Runner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Runner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.TIC_Runner__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Village__c</field>
            <operation>equals</operation>
            <valueField>$User.Village__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>HFS_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Runner On Way</fullName>
            </value>
            <value>
                <fullName>With Runner</fullName>
            </value>
            <value>
                <fullName>In Storage</fullName>
            </value>
            <value>
                <fullName>With TIC</fullName>
            </value>
            <value>
                <fullName>Customer Collected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the detail of all units in VR Villages</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>...</description>
    <inlineHelpText>Select the Village where this unit lives</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Village Presence records must be linked to Brand accounts. Please ensure you are not linking the Deal/Village Presence to a Group</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deal Pending</fullName>
            </value>
            <value>
                <fullName>Trading</fullName>
            </value>
            <value>
                <fullName>in Refit</fullName>
            </value>
            <value>
                <fullName>Exited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/SCSItemMapController.cls
public with sharing class SCSItemMapController {

//////////to be deleted
 /*
    public SCSItemMapController (ApexPages.StandardController controller) {
    set<string> validStatuses = new set<string>{'Requested','Runner On Way', 'With Runner'};
    
    //extention####################################################
    //set of unique VPids
    set<id> VPIds = new set<id>();
    string MyVillageName = [SELECT Village__c FROM USER WHERE ID = :UserInfo.getUserId()].Village__c;
    
    for (AggregateResult results : [select  Brand__c from HFS_Item__c
                                        WHERE status__c in :validStatuses
                                        AND Brand__r.Village__r.name = :MyVillageName 
                                        GROUP BY Brand__c])  
    { 
       VPIds.add((ID)results.get('Brand__c')); 
    }
       
     list<Village_presence__c> SCSVPs = [SELECT id, Brand__r.Name, unit__r.Unit_GeoLocation__latitude__s, unit__r.Unit_GeoLocation__longitude__s,
                                                                          (SELECT id, name, Drop_Location__c, Runner__r.name, Brand__c, map_marker__c, status__c 
                                                                            FROM HFS_Items__r 
                                                                            WHERE status__c in :validStatuses
                                                                             )
                                         FROM Village_presence__c
                                         WHERE id in :VPIds];
                                         
       myMapPoints = new list<mapPoint>();
   
            for(Village_presence__c cVP : SCSVPs ){
                   
                boolean runnerallocated = false;
                decimal markerScore = 0;     
                   
                   mapPoint nMP = new mapPoint();
                   nMP.BrandName= cVP.Brand__r.Name ;
                   nMP.Lat= cVP.unit__r.Unit_GeoLocation__latitude__s;
                   nMP.Lng= cVP.unit__r.Unit_GeoLocation__longitude__s;
                   nMP.vpid = cVP.id;
                   nMP.scsrequests = new  list<SCSrequest> ();
                   
                  system.debug('Lat: ' + nMP.Lat + ',   Long: ' + nMP.Lng); 
                    
                    //now add remote request lists to each VPmarker
                    for(HFS_Item__c cRequest : cVP.HFS_Items__r){
                   
                            SCSrequest nRequest = new SCSrequest();
                            
                            nRequest.requestid = cRequest.id;
                            nRequest.status = cRequest.status__c;
                            
                            if(string.isnotblank(cRequest.Drop_Location__c) ){
                                nRequest.droplocation = cRequest.Drop_Location__c;
                            }
                            else{
                                nRequest.droplocation = 'Drop Location not set';
                            }
                            
                            if(string.isnotblank(cRequest.runner__r.name)){
                                nRequest.droplocation  += ' (' + cRequest.Runner__r.name + ')';
                                runnerallocated = true;
                            }
                            
                            
                            nRequest.droplocation  += ' - ' + cRequest.Status__c;
         
                            nMP.scsrequests.add(nRequest);
                            
                            //map marker based on location
                            if (cRequest.map_marker__c > markerScore)
                            {
                                markerScore = cRequest.map_marker__c;
                            }
                            
                                                  
                 }//end of adding requests to VP list
                 
                 
                 if(markerScore == 5){
                         nMP.marker = 'Crown-Map-Marker.png';
                 }
                 else if(markerScore == 4){
                         nMP.marker = 'trainstationmarker.png';
                 }
                 else if(markerScore == 3){
                         nMP.marker = 'infomapmarker.png';
                 }
                 else if(markerScore == 2){
                         nMP.marker = 'mapmarkergreen.png';
                 }
                 else if(markerScore == 1){
                         nMP.marker = 'mapmarkergreen.png';
                 }
                 else if(markerScore == 0){
                         nMP.marker = 'mapmarkergreen.png';
                 }
                 
            
 
                myMapPoints.add(nMP);
            }
            
       //set map default center point
       Village__c myVillage =  [select id, Village_GeoLocation__latitude__s, Village_GeoLocation__longitude__s FROM Village__c WHERE name = :MyVillageName LIMIT 1];
       homeVillageGeoLocation = '{latitude: ' +  myVillage.Village_GeoLocation__latitude__s + ', longitude: ' + myVillage.Village_GeoLocation__longitude__s + ' }';
     
    
     
    }//end of constructor


//Properties
//public list<SCS_Remote_Request__c> RemoteRequests {get;set;}
public list<mapPoint> myMapPoints{get;set;}
public string homeVillageGeoLocation {get;set;}

       
    public class mapPoint
    {
        public id vpid{get; set;}
        public id requestid {get; set;}
        public string BrandName{get; set;}
        public list<SCSrequest> scsrequests{get; set;}
        public decimal Lat{get; set;}
        public decimal Lng{get; set;}
        public string marker{get; set;}
    }

    public class SCSrequest
    {
        
        public id requestid{get; set;}
        //public id vpid{get; set;}
        public string status{get; set;}
        public string droplocation{get; set;}
    }

*/

}