force-app/main/default/objects/Account/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <description>A Group or Parent Account for Brand Accounts</description>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/Group_Booking__c/Group_Booking__c.object-meta.xml
<CustomObject>
    <description>Tourism (B2T) Object :: Used for recording MICE group bookings</description>
    <label>Booking/Partnership</label>
    <nameField>
        <displayFormat>GBI{0000000000}</displayFormat>
        <label>Group Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings/Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the name of the primary contact at the organising party</inlineHelpText>
    <label>Booking/Partnership Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tourism Contact</value>
        </filterItems>
        <infoMessage>Please Select a Tourism Contact</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Group_Booking_Information_del1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Expected_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Expected_Arrival__c</fullName>
    <inlineHelpText>Enter the expected date and time</inlineHelpText>
    <label>Expected Arrival</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Expected_Departure__c.field-meta.xml
<CustomField>
    <fullName>Expected_Departure__c</fullName>
    <inlineHelpText>Enter the expected departure date and time for the booking</inlineHelpText>
    <label>Expected Departure</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Group_Booking_Source__c.field-meta.xml
<CustomField>
    <fullName>Group_Booking_Source__c</fullName>
    <description>How did the booking get into the system --&gt; Mapped from Lead.Lead_Source__c</description>
    <label>Group Booking Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce Front End</fullName>
                <default>true</default>
                <label>Salesforce Front End</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Group_Type__c.field-meta.xml
<CustomField>
    <fullName>Group_Type__c</fullName>
    <inlineHelpText>Please enter the group type</inlineHelpText>
    <label>Group Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Leisure</fullName>
            </value>
            <value>
                <fullName>MICE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Name_of_Event__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Event__c</fullName>
    <inlineHelpText>Please enter the name of the event (If appropriate)</inlineHelpText>
    <label>Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Number_of_Visitors_Expected__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Visitors_Expected__c</fullName>
    <description>Maps from lead, the number of visitors</description>
    <inlineHelpText>Per Arrival (Visit)</inlineHelpText>
    <label>Number of Visitors Expected</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the name of the company or agency responsible for organising this event</inlineHelpText>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Please select a Tourism or Marketing Partner.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Tourism</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Marketing_Partner</value>
        </filterItems>
        <infoMessage>Please select a Tourism or Marketing Partner.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings/Partnerships</relationshipLabel>
    <relationshipName>Group_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Please indicate the Status of the booking</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Proposed</fullName>
                <default>true</default>
                <label>Proposed</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipName>Bookings_Partnerships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Visitors_Country_of_Origin__c.field-meta.xml
<CustomField>
    <fullName>Visitors_Country_of_Origin__c</fullName>
    <inlineHelpText>Please enter the country of origin of the tour group</inlineHelpText>
    <label>Visitors Country of Residence</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Russian Federation</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
            </value>
            <value>
                <fullName>------------------------------------</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Was_Quick_Converted__c.field-meta.xml
<CustomField>
    <fullName>Was_Quick_Converted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Was Quick Converted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the actual village where this opportunity exists</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/emailLeadQueuesAfterGBQuickConvertedTest.cls
@isTest
global class emailLeadQueuesAfterGBQuickConvertedTest{

        private static Account account = new Account();
        private static Village__c village3 = new Village__c();
        private static Opportunity opp = new Opportunity();
        private static Group grp = new Group();
        private static Contact con = new Contact();
        private static Group_Booking__c GB = new Group_Booking__c();

        static void setupData(){
        
        account = TestData_Account.setupTourismAccount(1, true);
        con = TestData_Contact.setupTourismContact('A',account,true);
                  
             //create village 1
             
             village3.Name = 'TestVillage1';     
             village3.Village_Code__c = 'AA';
			 village3.CertSales_CertPeriod_Cut_Off_Days__c = 1;
			 village3.CertSales_Report_Sales_Grace_Period_Days__c = 1;
             insert village3;
             village3 = [select name, id, Village_Code__c from Village__c where Village_Code__c = 'AA' LIMIT 1];  
             
             Recordtype myRec = [SELECT id FROM RecordType WHERE name = 'Group Booking' AND sobjectType = 'Group_Booking__c'];
                system.debug('myrec ' + myRec);
                               
                
                GB.recordtypeid = myRec.id;
                GB.village__c = village3.id;
                GB.Name_of_Event__c = 'TEST GB';
                GB.Organisation__c = account.id;
                GB.Group_Type__c = 'MICE';
                GB.Status__c = 'Proposed';
                GB.Group_Booking_Source__c = 'External MICE Form';
                GB.Expected_Arrival__c = system.now();
                GB.Visitors_Country_of_Origin__c = 'united Kingdom';
                GB.Expected_Departure__c = system.now()+1;
                GB.Contact__c = con.id;
                GB.Number_of_Visitors_Expected__c = 10;
                //GB.Was_Quick_Converted2__c = true;   
                system.debug('myGB1 ' + GB);        
            
                insert GB;     
                system.debug('myGB2 ' + GB);   
                
                Group_Booking__c GB2 = [SELECT Id,Was_Quick_Converted__c FROM Group_Booking__c WHERE Id =: GB.id];
                GB2.Was_Quick_Converted__c = true;
                update GB2;
                   
            }


        private static testMethod void Test1() {
 
        setupData();
        
        list <emailLeadQueuesAfterGBQuickConverted.sendEmailDetails> listofdetails = new list<emailLeadQueuesAfterGBQuickConverted.sendEmailDetails>();    
        emailLeadQueuesAfterGBQuickConverted.sendEmailDetails detail = new emailLeadQueuesAfterGBQuickConverted.sendEmailDetails();
                
                
                
                
                detail.GBId = GB.id;
                detail.PrimaryVillageofInterest = 'Bicester';
                system.debug('thisdetail ' + detail);
            
                listofdetails.add(detail);
                system.debug('thislistdetail ' + listofdetails);
 
                Test.startTest();
                emailLeadQueuesAfterGBQuickConverted.sendEmail(listofdetails);
                Test.stopTest();                
                
            }             
}