force-app/main/default/objects/Account/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <description>A Group or Parent Account for Brand Accounts</description>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the actual village where this opportunity exists</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FutureLeadContactUpdatesTest.cls
@isTest
private class FutureLeadContactUpdatesTest{

	private static Account account = new Account();
	private static Contact contact = new Contact();
	private static Village__c village = new Village__c();
	private static Opportunity opportunity = new Opportunity();
	private static Lead lead = new Lead();
	private static Lead lead2 = new Lead();
	
    
    static void setupData(){
    
		account = TestData_Account.setupTourismAccount(1, true);
					
 		village = new Village__c();
 		village.Name = 'TestVillage1'; 		
 		village.Village_Code__c = 'AA';
		village.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		village.CertSales_Report_Sales_Grace_Period_Days__c = 1;
 		insert village;

 		id LeadRTID = Schema.SObjectType.Lead.RecordTypeInfosByName.get('Group Booking Lead').RecordTypeId;
 		lead.firstName = 'John';
 		lead.lastName = 'Test';
 		lead.company = 'test';
 		lead.email = 'testA@valueretail.com';
 		lead.LeadSource = 'Village Registration Card';
 		lead.recordtypeid = LeadRTID;
 		lead.HasOptedOutOfEmail = true;

 		lead2.firstName = 'Paul';
 		lead2.lastName = 'Test2';
 		lead2.company = 'test2';
 		lead2.email = 'test2A@valueretail.com';
 		lead2.LeadSource = 'Village Registration Card';
 		lead2.recordtypeid = LeadRTID;
 		lead2.HasOptedOutOfEmail = false;

 		insert lead;
 		insert lead2;

    }


    static testMethod void unitTest() {
    	
    	setupData();

    	list<lead> leads = [SELECT id, Name FROM Lead];
	    // and add it to the list of lead conversions to be executed.
	    List<Database.LeadConvert> leadConversions = new List<Database.LeadConvert>();
	    LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1]; 
	        
	    FOR (Lead cLead : leads)
	    {
	        Database.LeadConvert lc = new database.LeadConvert();
	        lc.setConvertedStatus( convertStatus.MasterLabel );
	        lc.setLeadId(cLead.id);
	        lc.setDoNotCreateOpportunity(True);
	        leadConversions.add(lc);
	    }

	    // reset the limits
	    test.startTest();
	    // Convert the Lead records that cause the trigger to execute
	        Database.convertLead(leadConversions);   
	    // Stop the test, this changes limit context back to test from trigger.
	    test.stopTest();

	    list<contact> con1 = [select id,Name,email,HasOptedOutOfEmail FROM contact WHERE email = 'testA@valueretail.com'];
	    list<contact> con2 = [select id,Name,email,HasOptedOutOfEmail FROM contact WHERE email = 'test2A@valueretail.com'];

	    system.assert(con1[0].HasOptedOutOfEmail == false, 'error1');
	    system.assert(con2[0].HasOptedOutOfEmail == true, 'error2');




    }

}