force-app/main/default/objects/Account/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <description>A Group or Parent Account for Brand Accounts</description>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/b2c_customer__c/b2c_customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/b2c_customer__c/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <description>Customer email address</description>
    <inlineHelpText>Customer email address</inlineHelpText>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/b2c_customer__c/fields/firstName__c.field-meta.xml
<CustomField>
    <fullName>firstName__c</fullName>
    <description>Customer first name</description>
    <inlineHelpText>Customer first name</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/b2c_customer__c/fields/lastName__c.field-meta.xml
<CustomField>
    <fullName>lastName__c</fullName>
    <description>Customer last name</description>
    <inlineHelpText>Customer last name</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Communication_Channel__c.field-meta.xml
<CustomField>
    <fullName>Communication_Channel__c</fullName>
    <inlineHelpText>Select which channels the Campaign will be distributed</inlineHelpText>
    <label>Communication Channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Publication</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Postal</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Leaflet/Coupon</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Face-to-face</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Other Media (TV/Radio)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If this Group Campaign is linked to a Tourism Partner account the Select the Account</inlineHelpText>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Tourism</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>only valid for redeemable campaigns</description>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/Promotion_Redemption__c.object-meta.xml
<CustomObject>
    <description>A new record is created when a tourism redemption is claimed. the numbers role up in to Tourism Promotion</description>
    <label>Promotion Redemption</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Redemption ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Redemptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotion_Redemption__c/fields/customer__c.field-meta.xml
<CustomField>
    <fullName>customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>b2c_customer__c</referenceTo>
    <relationshipLabel>Redeemed Promotions</relationshipLabel>
    <relationshipName>Promotion_Redemptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/fields/Guest_Email__c.field-meta.xml
<CustomField>
    <fullName>Guest_Email__c</fullName>
    <description>The email address of the guest that the VIP card was handed out to. this will initiate a welcome process (if not already registered) or simply log the spend against the account</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter the Guests email address</inlineHelpText>
    <label>Guest Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/fields/Redeem_Date__c.field-meta.xml
<CustomField>
    <fullName>Redeem_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Redeem Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/fields/Redeemable_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Redeemable_Campaign__c</fullName>
    <label>Redeemable Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Redemptions</relationshipLabel>
    <relationshipName>Redemptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Promotion_Redemption__c/fields/Voucher_Code__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Code__c</fullName>
    <description>This is the &quot;scan out&quot; code of the voucher (VIP card)</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter the VIP card code</inlineHelpText>
    <label>Voucher Code</label>
    <length>55</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MultiAddRedemptionsControllerTest.cls
@isTest
public class MultiAddRedemptionsControllerTest{

Private Static Campaign multiChannelCampaign = new Campaign(); 
private static string village = 'Test Village'; 
private static village__c testvillage = new village__c();
private static Account TourismAccount = new Account();

//Private Static Account GuestContact = new Account();
Private Static b2c_customer__c GuestContact = new b2c_customer__c();
    
private static id RedeemableCampRecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Redeemable Campaign').getRecordTypeId();
//private static id GuestRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Guest').getRecordTypeId();
    
     public static testMethod void testReset() 
    { 
        setupdata();
        PageReference pg = new PageReference('Page.MultiAddRedemptions');
        pg.getParameters().put('id', multiChannelCampaign.id); 
        test.setCurrentPageReference(pg);
        
        test.startTest();
            MultiAddRedemptionsController controller = new MultiAddRedemptionsController();
        	//addsome records before the reset      
            controller.setmultiVouchers('14xxxxxxxxxxxx;14xxxxxxxxxxyy');
            controller.MultiAdd();
        	//check that where are two items in the TORlist
        	system.assertEquals(controller.TORList.size(), 2);
        	//this is what we are testing - after reset the list should be null(0)
        	controller.reset();
        test.stopTest();
        //After a reset the TORlist size should be 0
        system.assertEquals(controller.TORList.size(), 0);
    }
    
    public static testMethod void TestAddwithBadCode() 
    {
        setupdata();
        PageReference pg = new PageReference('Page.MultiAddRedemptions');
        pg.getParameters().put('id', multiChannelCampaign.id); 
        test.setCurrentPageReference(pg);
        
        test.startTest();   
            MultiAddRedemptionsController controller = new MultiAddRedemptionsController();
            //TODO
            controller.setmultiVouchers('14xxxxxxxxxxxx;14xxxxxxxxxxyy');
            controller.MultiAdd();
            //manually add a  bad code (replicating a user typing something directly in the list
            controller.TORList.add(New Promotion_Redemption__c(Redeemable_Campaign__c = multiChannelCampaign.Id, Redeem_Date__c = system.today() , Voucher_Code__c = 'invalid', customer__c = null));
            controller.add();
        	//check the TORlist has 3 records - 2 good, one bad
        	system.assertEquals(controller.TORList.size(), 3);
            //first quicksave (validate) should remove bogus code
        	controller.quicksave();
        	//After the first quicksave(validate) the TORlist size should now be 2
        	system.assertEquals(controller.TORList.size(), 2);
        	//and a user msg should be setup.
            List<Apexpages.Message> msgs = ApexPages.getMessages();
            boolean b = false;
            for(Apexpages.Message msg:msgs)
            {
                if (msg.getDetail().contains('Some codes were removed')) b = true;
            }
            system.assert(b);
        
            //second quicksave (validate) should all validate sucessfully.
            controller.quicksave();
        	//After the second quicksave(validate) the TORlist size should still be 2
        	system.assertEquals(controller.TORList.size(), 2);
        
        test.stopTest();
    }
    
    public static testMethod void testGuestPopulation() 
    {
        setupdata();
        PageReference pg = new PageReference('Page.MultiAddRedemptions');
        pg.getParameters().put('id', multiChannelCampaign.id); 
        test.setCurrentPageReference(pg);
        
        test.startTest();   
            MultiAddRedemptionsController controller = new MultiAddRedemptionsController();       
            //manually add a  bad code (replicating a user typing something directly in the list
            controller.TORList.add(New Promotion_Redemption__c(Redeemable_Campaign__c = multiChannelCampaign.Id, Redeem_Date__c = system.today() , Voucher_Code__c = 'invalid', customer__c = guestContact.Id));
            controller.rowIndex = 0;
            controller.updateContactFields();
        test.stopTest();
        
        //ensure the guest email address is populated from the person accoout lookup.
        system.assertEquals('guest@guest.com', controller.TORList[0].Guest_Email__c);
    }
    
    public static testMethod void testInValidCampaignIdinURL() 
    {
        PageReference pg = new PageReference('Page.MultiAddRedemptions');
        pg.getParameters().put('id', '701110000001bad'); 
        test.setCurrentPageReference(pg);
        
        test.startTest();   
            MultiAddRedemptionsController controller = new MultiAddRedemptionsController();
        test.stopTest();
        
        //there should not be an error and the redeemableCampaign should be null
        system.assertEquals(Null, controller.RedeemableCampaign);   
    }
    
    public static testMethod void Cancel() 
    {
        setupdata();
        PageReference pg = new PageReference('Page.MultiAddRedemptions');
        pg.getParameters().put('id', multiChannelCampaign.id); 
        test.setCurrentPageReference(pg);
        
        test.startTest();   
            MultiAddRedemptionsController controller = new MultiAddRedemptionsController();
            controller.cancel();
        test.stopTest(); 
        //no asserts - we're just cancelling the request and dedirecting the user 
    }
    
    public static testMethod void testredemptionWithBadCode() 
    {
        setupdata();
        PageReference pg = new PageReference('Page.MultiAddRedemptions');
        pg.getParameters().put('id', multiChannelCampaign.id); 
        test.setCurrentPageReference(pg);
        
        test.startTest();   
            MultiAddRedemptionsController controller = new MultiAddRedemptionsController();
    
            controller.setmultiVouchers('14xxxxxxxxxxxx;ddd');
        	//Ensure the getmultivouchers returns our entire input string
            system.assertEquals(controller.getmultiVouchers(),'14xxxxxxxxxxxx;ddd');
            
            controller.MultiAdd();
        	
            //ensure the multiadd function strips out the invalid ID and adds 
        	//just one record to the TROList
            system.assertEquals(controller.getTORs().size() ,1);
            
        	//We didn't set the contact details required on the campaign
        	//so  ensure they are indeed not required
            system.assertEquals(controller.getContactDetailsRequired(), false);
            
            //add a  bad vouchercode - inline
            controller.add();
           //controller.TORList.add(New Promotion_Redemption__c(Redeemable_Campaign__c = multiChannelCampaign.Id, Redeem_Date__c = system.today() , Voucher_Code__c = 'badcode'));         
            controller.save();
        test.stopTest();
        
        //ensure the badcodes string has captured the bad code (to display on screen)
        //badcode = 'badcode' Length = 7
        //n.b. Can't test the length of badcodes as it is reset after use. Assert == 0
        system.assertEquals(0, controller.badCodes.length());
    }
    
    
    public static testMethod void testRedemptionNoBadCodes() 
    {
        setupdata();

        PageReference pg = new PageReference('Page.MultiAddRedemptions');
        pg.getParameters().put('id', multiChannelCampaign.id); 
        
        test.setCurrentPageReference(pg);
        
        test.startTest();   
            MultiAddRedemptionsController controller = new MultiAddRedemptionsController();  
            controller.setmultiVouchers('14xxxxxxxxxxxx');
            controller.MultiAdd();
            system.assertEquals(controller.getTORs().size() ,1);         
            controller.save();
        test.stopTest();
        
        //ensure there are no bad codes reported
        system.assertEquals(0, controller.badCodes.length());
    }

	public static testMethod void testQuickRedemption() 
    {
        setupdata();

        PageReference pg = new PageReference('Page.MultiAddRedemptions');
        pg.getParameters().put('id', multiChannelCampaign.id); 
        pg.getParameters().put('redeemCode', '00000000000001');
        pg.getParameters().put('addCustomer', 'true');
         
        test.setCurrentPageReference(pg);
        
        test.startTest();   
            MultiAddRedemptionsController controller = new MultiAddRedemptionsController();  
            system.assertEquals(controller.getTORs().size() ,1);         
            controller.save();
        test.stopTest();
        
        //ensure there are no bad codes reported
        system.assertEquals(0, controller.badCodes.length());
    }


/////////////////////DATA setup///////////////////////
    static void setupdata()
    {
        
        //Setup new test Village
        //TO-DO - convert to generic object creation
        testvillage.Name = village;
        testvillage.Village_Code__c = 'TV';
		testvillage.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		testvillage.CertSales_Report_Sales_Grace_Period_Days__c = 1; 
        insert testvillage;
        
        //Setup Partner
       TourismAccount = TestData_Account.setupTourismAccount(1,true);
        
        //setup b2c customer Contact
        //GuestContact.RecordTypeId = GuestRecordTypeId;
        GuestContact.FirstName__c = 'GuestFN';
        guestContact.LastName__c = 'GuestLN';
        guestcontact.Email__c = 'guest@guest.com';
        
        insert guestContact;
        system.debug('@@@Test GUEST ID: ' + guestcontact.id);
               
        //new redeemable campaign    
        multiChannelCampaign.Name = 'My Test Group Campaign';
        multiChannelCampaign.Communication_Channel__c = 'Email';
        multiChannelCampaign.Status = 'In Progress' ;
        multiChannelCampaign.isActive = true ;
        multiChannelCampaign.Village__c = testvillage.id;
        multiChannelCampaign.Partner__c = TourismAccount.id;
        multiChannelCampaign.description = 'This is my test campaign';
        multiChannelCampaign.startdate = Date.today();
        multiChannelCampaign.enddate = Date.today()+3;
        multiChannelCampaign.RecordTypeId = RedeemableCampRecordTypeId;
        
        insert multiChannelCampaign;
    
    }
    
}