force-app/main/default/objects/Account/fields/Account_Email__c.field-meta.xml
<CustomField>
    <fullName>Account_Email__c</fullName>
    <inlineHelpText>This is a generic email address for the company as a whole. E.g. Reception@valueretail.com or Info@valueretail.com</inlineHelpText>
    <label>Account Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <description>A Group or Parent Account for Brand Accounts</description>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Secondary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Email_Address__c</fullName>
    <description>Used for genuine secondary address fields OR generic email addresses, like info@company.com, since the email address field is a unique field (Tourism only) but two separate contacts may share an email address.

This field will NOT be used by Responsys (only [Primary] email)</description>
    <inlineHelpText>If a Contact is using a group email address (e.g. info@company.com) then please enter it here instead of the Primary email address field.</inlineHelpText>
    <label>Secondary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/Group_Booking__c.object-meta.xml
<CustomObject>
    <description>Tourism (B2T) Object :: Used for recording MICE group bookings</description>
    <label>Booking/Partnership</label>
    <nameField>
        <displayFormat>GBI{0000000000}</displayFormat>
        <label>Group Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings/Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the name of the primary contact at the organising party</inlineHelpText>
    <label>Booking/Partnership Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tourism Contact</value>
        </filterItems>
        <infoMessage>Please Select a Tourism Contact</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Group_Booking_Information_del1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/No_Show_Email_Send_Date__c.field-meta.xml
<CustomField>
    <fullName>No_Show_Email_Send_Date__c</fullName>
    <description>Shows the date-time that the No-Show email was sent</description>
    <inlineHelpText>Shows the date-time that the No-Show email was sent</inlineHelpText>
    <label>No Show Email Send Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Notes_and_Additional_Comments__c.field-meta.xml
<CustomField>
    <fullName>Notes_and_Additional_Comments__c</fullName>
    <inlineHelpText>Enter any additional notes or comments relevant for this booking</inlineHelpText>
    <label>Notes and Additional Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the name of the company or agency responsible for organising this event</inlineHelpText>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Please select a Tourism or Marketing Partner.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Tourism</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Marketing_Partner</value>
        </filterItems>
        <infoMessage>Please select a Tourism or Marketing Partner.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings/Partnerships</relationshipLabel>
    <relationshipName>Group_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Secondary_MICE_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Secondary_MICE_Contact_Email__c</fullName>
    <label>Secondary Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Send_No_Show_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_No_Show_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sends an email to the booking parties to inform them that they were a &apos;No Show&apos;</description>
    <inlineHelpText>Sends an email to the booking parties to inform them that they were a &apos;No Show&apos; (Caution: this will send an email)</inlineHelpText>
    <label>Send No Show Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Please indicate the Status of the booking</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Proposed</fullName>
                <default>true</default>
                <label>Proposed</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>v-{00000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Group_Booking__c.field-meta.xml
<CustomField>
    <fullName>Group_Booking__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Booking/Partnership</label>
    <referenceTo>Group_Booking__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/No_Show__c.field-meta.xml
<CustomField>
    <fullName>No_Show__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select this option if the Group didn&apos;t turn up. This will remove any associated VIP cards, zero the guest count and remove the check-in date/time</inlineHelpText>
    <label>No Show</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GroupBookingTriggerHandler.cls
public with sharing class GroupBookingTriggerHandler{
    
    public static void updateRelatedAccount(List<Group_Booking__c> bookingList){
        List<Id> accIdList = new List<Id>();
        
        for(Group_Booking__c book : bookingList){
            accIdList.add(book.Organisation__c);
        }
        if(!accIdList.isEmpty()){
        	UpdateRelatedAccountSchedulable schedulable = new UpdateRelatedAccountSchedulable(accIdList, 'Group Booking');
            
            Datetime dt = Datetime.now().addMinutes(1);
   			String timeForScheduler = dt.format('s m H d M \'?\' yyyy');

            System.schedule('Schedule Account Update '+System.currentTimeMillis(), timeForScheduler , schedulable);
        }
    }

    public static void GroupBookingAfterUpdate(Map<Id, Group_Booking__c> oldBookingMap, Map<Id, Group_Booking__c> newBookingMap ){
        List<Id> noshowGBIds = new List<ID>();
        for(Group_Booking__c newGB :newBookingMap.values()){
            Group_Booking__c  oldGB = oldBookingMap.get(newGB.Id);
            if(oldGB.Status__c != newGB.Status__c ){
                // means the status has changed
                // lets check if the status has changed to 'No Show' 
                if(newGB.Status__c == 'No Show'){
                    // means we need to mark all this bookings visits as 'No Show'
                    noshowGBIds.add(newGB.Id);
                }
            }
        }
        
        // now that we have all the group bookings that we think are no shows, lets make sure all the visits are marked as no show too (but lets not mark the ones that are already marked)
        List<Visit__c> noShowVisits = [SELECT ID, No_Show__c FROM Visit__c WHERE No_Show__c = false AND Group_Booking__c in :noshowGBIds];
    
        for(Visit__c vst :noShowVisits){
            vst.No_Show__c = true;
        }
        update noShowVisits;
        // this should only update the visits that arent already marked as no-show
    }

     public static void GroupBookingBeforUpdate(Map<Id, Group_Booking__c> oldBookingMap, Map<Id, Group_Booking__c> newBookingMap ){

            System.debug('Checking bookings for no-show');
        // lets check if the 'send no show email' flag is set, so we can send the email
        List<Group_Booking__c> noShowEmailBookings = new List<Group_Booking__c>();
        for(Group_Booking__c newGB :newBookingMap.values()){
            Group_Booking__c  oldGB = oldBookingMap.get(newGB.Id);
  System.debug('old booking: ' + oldGB);
    System.debug('new booking: ' + newGB);
            if(oldGB.Send_No_Show_Email__c == false && newGB.Send_No_Show_Email__c == true){
                // then the user wants to send the no-show email
                // but lets make sure that the status is correct and all that.
                if(newGB.Status__c == 'No Show'){
                    noShowEmailBookings.add(newGB);
                }
            }

        }


        // now that we have the group bookings that need to send no show emails, lets send them

          emailUtils checkinmailUtils = new emailUtils('traveltrade@thebicestervillageshoppingcollection.com', 'Group_Booking_No_Show_Email');
         //Group_Booking__c GB = [SELECT Id,Contact__r.Secondary_Email_Address__c,Organisation__r.Account_Email__c ,contact__c,contact__r.email,Secondary_MICE_Contact_Email__c,status__c FROM Group_Booking__c where id = :vist.Group_Booking__c];
        for(Group_Booking__c GB :noShowEmailBookings) {
           if(GB != null){
                System.debug('GB Contact: ' + GB.contact__c);
                LIST<string> toaddress = New List<String>();
                IF(GB.contact__c!= null){
                    Contact cont = [SELECT ID,Secondary_Email_Address__c, email FROM Contact WHERE ID =:GB.contact__c];
                    IF( cont.email != NULL){
                        toaddress.add(cont.email);
                    }
                       
                    IF( cont.Secondary_Email_Address__c != NULL){
                        toaddress.add(cont.Secondary_Email_Address__c);
                    }
                
                }
                
                IF(GB.Secondary_MICE_Contact_Email__c != NULL){
                        toaddress.add(GB.Secondary_MICE_Contact_Email__c);
                }
                 IF(GB.Organisation__c != null ){
                    Account acc = [SELECT ID, Name,Account_Email__c FROM Account WHERE ID =:GB.Organisation__c ];
                    if(acc.Account_Email__c  != NULL){
                        toaddress.add(acc.Account_Email__c );
                    }
                }
                System.Debug('About to call SEND EMail == == ' + toaddress);
                if(toaddress.size() == 0 ){
                     GB.Notes_and_Additional_Comments__c += 'No Show Email send fail: No Email addresses to send to. ';
                 }
                 emailUtils.emailSendResponse emailResponse = checkinmailUtils.sendEmail(toaddress,null,GB.Id,null,null,null);
                
                // public emailSendResponse sendEmail( LIST<string> toaddresses,ID whatID, String htmlContent, String plainContent){ 
                    System.Debug('emailResponse == == ' + emailResponse);
                if(emailResponse.emailSendResult){
                    // only update the visits for the emails that suceeded.
                    if(emailResponse.emailSendResult){
                        GB.No_Show_Email_Send_Date__c = Datetime.now();
                       //return;
                    }  
                    else{
                        // need to surface an error if possible 
                        GB.Notes_and_Additional_Comments__c += 'No Show Email send fail: ' + emailResponse.emailResultMessage;
                    }           

                }
                else{
                        // need to surface an error if possible 
                        GB.Notes_and_Additional_Comments__c += 'No Show Email send fail: ' + emailResponse;
                    } 
            }
        }
     }

}