force-app/main/default/objects/Account/fields/Account_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Reference_Number__c</fullName>
    <displayFormat>{000000000}</displayFormat>
    <label>Account Reference Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <description>A Group or Parent Account for Brand Accounts</description>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Account_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Reference_Number__c</fullName>
    <description>Links the Lead to a specific Account Number</description>
    <label>Account Reference Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Create_Group_Booking__c.field-meta.xml
<CustomField>
    <fullName>Create_Group_Booking__c</fullName>
    <defaultValue>true</defaultValue>
    <description>(B2T) Controls whether a group booking record is created</description>
    <inlineHelpText>Uncheck this field if you do not want to create a Group booking when this lead is converted.</inlineHelpText>
    <label>Create Group Booking</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Quick_Convert__c.field-meta.xml
<CustomField>
    <fullName>Quick_Convert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quick Convert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LogFile__c/LogFile__c.object-meta.xml
<CustomObject>
    <label>LogFile</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>LogFile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LogFiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogFile__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B2B Report Emails</fullName>
            </value>
            <value>
                <fullName>ETLWebService</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadTriggerHandler.cls
Public Class LeadTriggerHandler{

    public static boolean isAfterInsert = false;

    public static void handlBeforeInsert(List<Lead> Leads){
     system.debug('before insert1');
            For (Lead cLead : Leads){ 
                IF(cLead.Account_Reference_Number__c != NULL){
                   LeadUtilities.setAccountReference(cLead);
                   system.debug('before insert2');

                }
            }
        }


    public static void handleafterInsert(List<Lead> Leads){

        list<logFile__c> logs = new list<logFile__c>();
        List<ID> lstLeadUpdate = new List<ID>();

        For (Lead cLead : Leads){ 
            try{
                //Checks if we can quickConvert the lead - Account & Contact info exists we can auto convert
                IF(LeadUtilities.canQuickConvert(cLead)){
                    system.debug('###Leads passed through### IN' + cLead );
                    //If True perform quickConvert
                    LeadUtilities.quickConvert(cLead);
                } else {
                    lstLeadUpdate.add(cLead.Id);
                }
            }
            catch (exception e){
                 
                    string leadConversionResults = '@@@@@@ lead Conversion failed ' + e + ' ------ ';
                    leadConversionResults += 'LeadData: ' + cLead;
                    logFile__c log = new logFile__c();
                    log.Body__c = leadConversionResults;
                    log.Type__c = 'Lead Conversion Error';
                    logs.add(log);
            }
        }
        
        if(lstLeadUpdate.Size() > 0){
            isAfterInsert = true;
            updateLead(lstLeadUpdate);
        }

        if(!logs.isempty()){
            insert logs;
        }
    }
    
   public static void updateLead(List<ID> Leads){
        List<Lead> lstLead = [Select Id from Lead Where Id IN :Leads];
        List<Lead> lstLeadUpdate = new List<Lead>();

        for(Lead leadUp : lstLead){
            leadUp.Quick_Convert__c = false;
            lstLeadUpdate.add(leadUp);
        }

        Update lstLeadUpdate;
    }

    public static void handleBeforeUpdate(List<Lead> Leads){
        For(Lead cLead :Leads){
            IF(cLead.Account_Reference_Number__c != NULL && cLead.Quick_Convert__c == True && cLead.Create_Group_Booking__c == False){
                LeadUtilities.setAccountReference(cLead); 
                }       
        }
    }        
    
    /*
    ##Name: LeadTrigger 
    ##Created by: Ian Womack
    ##Date: 14/01/2014
    ##Purpose: Upon Lead conversion, of a MICE lead, create a Group_Booking_Information__c record.
    */
    public static void handlAfterUpdate(Map<id,Lead> oldLeadMap, Map<id,lead> newLeadMap){
    
        //Stores a list of Lead records that will be sent over to the helper class
        List<Lead> leadsToCreateBookingInformationRecs = new List<Lead>();
        //record type of leads we are interested in
        Id RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Group Booking Lead').getRecordTypeId();
    
        //Loop through the leads and only filter out the leads that do not match the criteria
    
        For (Lead cLead : newLeadMap.values())
        {
            system.debug('Lead ID: '  +cLead.id);
            system.debug('nowConverted?: '  +cLead.isConverted);
            system.debug('was Converted?: ' + oldLeadMap.get(cLead.id).isConverted);
            system.debug('Recordtypeid: '   +cLead.recordtypeid );
            system.debug('Should GBI be created?: '   +cLead.Create_Group_Booking__c );
            
            //Criteria: Record Type = MICE && isConverted = true 
            IF (cLead.isConverted == true && oldLeadMap.get(cLead.id).isConverted == false && cLead.recordtypeid == RecordTypeId && cLead.Quick_Convert__c == false )
            {
            //add the lead to the list to send through for GBI creation
                leadsToCreateBookingInformationRecs.add(cLead);  
                system.debug('Lead added: ' + cLead);
            }
            else
            {
                system.debug('No leads converted');
            }
                 
        } //end for loop
        
        
        //display the list of leads for which will be sent for GBI creation
        system.debug('Leads converted: ' + leadsToCreateBookingInformationRecs );
      
        Lead2GroupBookingClass.CreateGroupBookings(leadsToCreateBookingInformationRecs);
      }
      

}