force-app/main/default/objects/Account/fields/Account_Email__c.field-meta.xml
<CustomField>
    <fullName>Account_Email__c</fullName>
    <inlineHelpText>This is a generic email address for the company as a whole. E.g. Reception@valueretail.com or Info@valueretail.com</inlineHelpText>
    <label>Account Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <description>(Tourism Field)</description>
    <inlineHelpText>The contact at Value Retail (inc. Sales reps), who is the main point of contact for this account</inlineHelpText>
    <label>Account Manager</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Advocate__c.field-meta.xml
<CustomField>
    <fullName>Brand_Advocate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Advocate</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Brands4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/China_Brand_Captain__c.field-meta.xml
<CustomField>
    <fullName>China_Brand_Captain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>China Brand Captain</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Brands2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/EU_Brand_Captain__c.field-meta.xml
<CustomField>
    <fullName>EU_Brand_Captain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EU Brand Captain</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Users setup as Brand Captains are shown. Please contact the System Administrator if the Brand Captain is not shown</errorMessage>
        <filterItems>
            <field>User.Brand_Captain__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Please Select a Brand Captain</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/GRS_Captain__c.field-meta.xml
<CustomField>
    <fullName>GRS_Captain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GRS Captain</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Brands3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Marketing_Captain__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Captain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Captain</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Marketing_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Phone_2__c.field-meta.xml
<CustomField>
    <fullName>Phone_2__c</fullName>
    <inlineHelpText>This is a secondary phone number for the company. Please use standard format 
[+][country code][subscriber number including area code] 
e.g. +44 20 7183 8750</inlineHelpText>
    <label>Phone (2)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Business__c</fullName>
    <description>...</description>
    <inlineHelpText>This field is for reference only</inlineHelpText>
    <label>OLD Type of Business</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Airline</fullName>
            </value>
            <value>
                <fullName>Diplomatic</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Travel Agent/OTA</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>MICE Organisation/DMC</fullName>
            </value>
            <value>
                <fullName>DMO/Tourism Board</fullName>
            </value>
            <value>
                <fullName>Tour Operator/Wholesaler</fullName>
            </value>
            <value>
                <fullName>Travel Agent</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Influencer/Blogger</fullName>
            </value>
            <value>
                <fullName>Media Agency</fullName>
            </value>
            <value>
                <fullName>Media House</fullName>
            </value>
            <value>
                <fullName>Photographer</fullName>
            </value>
            <value>
                <fullName>Corporate Partner</fullName>
            </value>
            <value>
                <fullName>Event Management Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <description>A Group or Parent Account for Brand Accounts</description>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Tourism.recordType-meta.xml
<RecordType>
    <fullName>Tourism</fullName>
    <active>true</active>
    <description>A Partner of the Business</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Group_Booking__c/Group_Booking__c.object-meta.xml
<CustomObject>
    <description>Tourism (B2T) Object :: Used for recording MICE group bookings</description>
    <label>Booking/Partnership</label>
    <nameField>
        <displayFormat>GBI{0000000000}</displayFormat>
        <label>Group Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings/Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Booking__c/fields/Coach_Tour_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Coach_Tour_Company_Name__c</fullName>
    <description>MICE web-2-lead capture field</description>
    <label>Coach Tour Company Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Coach_Tour_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Coach_Tour_Contact_Email__c</fullName>
    <label>Coach Tour Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Coach_Tour_Phone__c.field-meta.xml
<CustomField>
    <fullName>Coach_Tour_Phone__c</fullName>
    <label>Coach Tour Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the name of the primary contact at the organising party</inlineHelpText>
    <label>Booking/Partnership Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tourism Contact</value>
        </filterItems>
        <infoMessage>Please Select a Tourism Contact</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Group_Booking_Information_del1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <inlineHelpText>Enter a contact number for the Tour Leader or Driver whichever has been entered</inlineHelpText>
    <label>Contact Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Expected_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Expected_Arrival__c</fullName>
    <inlineHelpText>Enter the expected date and time</inlineHelpText>
    <label>Expected Arrival</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Primary_Contacts_Secondary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contacts_Secondary_Email__c</fullName>
    <label>Primary Contacts Secondary Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Secondary_MICE_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Secondary_MICE_Contact_Email__c</fullName>
    <label>Secondary Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Secondary_MICE_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Secondary_MICE_Contact_First_Name__c</fullName>
    <label>Secondary Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Secondary_MICE_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Secondary_MICE_Contact_Last_Name__c</fullName>
    <label>Secondary Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Secondary_MICE_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Secondary_MICE_Contact_Phone__c</fullName>
    <label>Secondary Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Tour_Leader_Driver_Contact__c.field-meta.xml
<CustomField>
    <fullName>Tour_Leader_Driver_Contact__c</fullName>
    <inlineHelpText>Enter the contact telephone number of the Tour Leader or Driver</inlineHelpText>
    <label>Tour Leader / Driver Contact</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Tour_Leader_or_Driver_Name__c.field-meta.xml
<CustomField>
    <fullName>Tour_Leader_or_Driver_Name__c</fullName>
    <inlineHelpText>Enter the name of the Tour Leader or Driver</inlineHelpText>
    <label>Tour Leader or Driver Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipName>Bookings_Partnerships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Visitors_Country_of_Origin__c.field-meta.xml
<CustomField>
    <fullName>Visitors_Country_of_Origin__c</fullName>
    <inlineHelpText>Please enter the country of origin of the tour group</inlineHelpText>
    <label>Visitors Country of Residence</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Russian Federation</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
            </value>
            <value>
                <fullName>------------------------------------</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/obfuscationClassTest.cls
@Istest
Public Class obfuscationClassTest{

	private static Account acnt = new Account();
	private static Contact cnt = new Contact();
	private static Group_Booking__c grp = new Group_Booking__c();
	private static emailmessage email = new emailmessage();

	static testMethod void testMethod1(){

		setupdata();
        
        Test.startTest();

            map<String, list<String>> theObjectFieldMap = new map<String, list<String>>();
			list<string> theGBFields = new list<string>{'Coach_Tour_Company_Name__c','Coach_Tour_Contact_Email__c','Coach_Tour_Phone__c','Contact_Number__c','Contact__c','Secondary_MICE_Contact_Email__c','Secondary_MICE_Contact_First_Name__c','Secondary_MICE_Contact_Last_Name__c','Secondary_MICE_Contact_Phone__c','Tour_Leader_Driver_Contact__c','Tour_Leader_or_Driver_Name__c','Primary_Contacts_Secondary_Email__c'};
			theObjectFieldMap.put('Group_Booking__c', theGBFields);
			obfuscationClass myBatchObject = new obfuscationClass(theObjectFieldMap, null); 
			Id batchId = Database.executeBatch(myBatchObject, 200);

        Test.stopTest();
    }


    static testMethod void testMethod2(){

		setupdata();
        
        Test.startTest();

        	list<Recordtype> RTIDs = [SELECT Id, Name from Recordtype where sobjecttype = 'account' AND (Name = 'guest' OR Name = 'VIP Guest')];
			list<string> ids = new list<string>();
			for(Recordtype rec : RTIDs){
			    ids.add(rec.id);    
			}
			map<String, list<String>> theObjectFieldMap = new map<String, list<String>>();
			list<string> theAccountFields = new list<string>{'LastName','FirstName','Phone','PersonMobilePhone','PersonAssistantPhone','PersonEmail','PersonAssistantName','PersonBirthdate','Account_Manager__c','Phone_2__c','Account_Email__c','Brand_Advocate__c','China_Brand_Captain__c','EU_Brand_Captain__c','GRS_Captain__c','Marketing_Captain__c'};
			theObjectFieldMap.put('Account', theAccountFields);
			obfuscationClass myBatchObject = new obfuscationClass(theObjectFieldMap, ids); 
			Id batchId = Database.executeBatch(myBatchObject, 200);
            
        Test.stopTest();
    }

    static testMethod void testMethod3(){

		setupdata();
        
        Test.startTest();

        	map<String, list<String>> theObjectFieldMap = new map<String, list<String>>();
			list<string> theEmailsFields = new list<string>{'BccAddress','CcAddress','FromAddress','FromName','ToAddress'};
			theObjectFieldMap.put('EmailMessage', theEmailsFields);
			obfuscationClass myBatchObject = new obfuscationClass(theObjectFieldMap, NULL); 
			Id batchId = Database.executeBatch(myBatchObject, 200);
     
        Test.stopTest();
    }





    static void setupdata(){

    	recordtype acntRecType = [SELECT id, name from Recordtype WHERE sObjectType = 'Account' AND DeveloperName = 'Tourism'];
    	recordtype conRecType = [SELECT id, name from Recordtype WHERE sObjectType = 'Contact' AND name = 'Tourism Contact'];

    	acnt = new account();
    	acnt.recordtypeid = acntRecType.id;
    	acnt.Name = 'TEST Partner';
    	acnt.Type_of_Business__c = 'Airline';
    	insert acnt;

    	cnt = new contact();
    	cnt.LastName = 'test';
    	cnt.AccountId = acnt.id;
    	cnt.Phone = '546456456';
        cnt.Email = 'testuser@valueretail.com';
    	insert cnt;	
   
		list<Village__c> VilsToInsert = new list<Village__c>();

		Village__c Bicestervillage = new Village__c();
		Bicestervillage.Name = 'Bicester Village';     
		Bicestervillage.Village_Code__c = 'BV';
		Bicestervillage.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		Bicestervillage.CertSales_Report_Sales_Grace_Period_Days__c = 1; 
		VilsToInsert.add(Bicestervillage);

		insert VilsToInsert;

		recordType rtid = [SELECT id, name FROM RecordType WHERE sobjecttype = 'Group_Booking__c' AND Name = 'Group Booking'];
		id villid = [SELECT Id, Name FROM Village__c WHERE NAME = 'Bicester Village'].id;

        List<Group_Booking__c> grpBookings= new List<Group_Booking__c>();
        for(Integer i=0 ;i <20;i++)
        {
            Group_Booking__c grp = new Group_Booking__c();
            grp.recordtypeid =rtid.id;
            grp.Village__c = villid;
            grp.Visitors_Country_of_Origin__c = 'Belgium';
            grp.Expected_Arrival__c = system.now();
            grp.Expected_Departure__c = system.now() + 10;
            grp.Number_of_Visitors_Expected__c = 20;
            grp.Group_Type__c = 'MICE';
            grp.Group_Booking_Source__c = 'Salesforce Front End';
            grp.Status__c = 'proposed';
            grp.Name_of_Event__c = 'test' + i;
            grp.Coach_Tour_Company_Name__c = 'The Coach Party';
            grp.Coach_Tour_Contact_Email__c = 'test@test.com';
            grp.Coach_Tour_Phone__c = '9876543210';
            grp.Contact_Number__c = '456789456789';
            grp.Secondary_MICE_Contact_Email__c = 'Secondary@test.com';
            grp.Secondary_MICE_Contact_First_Name__c = 'Luke';
            grp.Secondary_MICE_Contact_Last_Name__c = 'Skywalker';
            grp.Secondary_MICE_Contact_Phone__c = '0012384589';
            grp.Tour_Leader_Driver_Contact__c = 'Darth vader';
            grp.Tour_Leader_or_Driver_Name__c = 'Anakin Skywalker';
            grp.Primary_Contacts_Secondary_Email__c = 'Anny@takeovertheuniverse.com';
            grp.Contact__c = cnt.id;
            grp.Organisation__c = acnt.id;
            grpBookings.add(grp);
            i ++;
        }
        
        insert grpBookings;


        email = new emailmessage();
        email.FromAddress = 'traveltrade@chicoutletshopping.com';
        email.FromName = 'Chic Outlet Shopping';
        email.ToAddress = 'dmoirc@hotmail.com';
        email.Subject = 'test';
        email.TextBody = 'test';
        insert email;

  	}

}