force-app/main/default/objects/Account/fields/Account_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Reference_Number__c</fullName>
    <displayFormat>{000000000}</displayFormat>
    <label>Account Reference Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>...</description>
    <inlineHelpText>The primary Region this partner will bring guests from.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Tourism.recordType-meta.xml
<RecordType>
    <fullName>Tourism</fullName>
    <active>true</active>
    <description>A Partner of the Business</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Oceania</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Secondary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Email_Address__c</fullName>
    <description>Used for genuine secondary address fields OR generic email addresses, like info@company.com, since the email address field is a unique field (Tourism only) but two separate contacts may share an email address.

This field will NOT be used by Responsys (only [Primary] email)</description>
    <inlineHelpText>If a Contact is using a group email address (e.g. info@company.com) then please enter it here instead of the Primary email address field.</inlineHelpText>
    <label>Secondary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Account_Reference__c.field-meta.xml
<CustomField>
    <fullName>Account_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The reference to the account that the reference belongs to , calculated in trigger from Account Reference Number</description>
    <label>Account Reference</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tourism</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Account_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Reference_Number__c</fullName>
    <description>Links the Lead to a specific Account Number</description>
    <label>Account Reference Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Boutique_Private_Viewing__c.field-meta.xml
<CustomField>
    <fullName>Boutique_Private_Viewing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>B2T - MICE Capture Field</description>
    <label>Boutique Private Viewing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Create_Group_Booking__c.field-meta.xml
<CustomField>
    <fullName>Create_Group_Booking__c</fullName>
    <defaultValue>true</defaultValue>
    <description>(B2T) Controls whether a group booking record is created</description>
    <inlineHelpText>Uncheck this field if you do not want to create a Group booking when this lead is converted.</inlineHelpText>
    <label>Create Group Booking</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Expected_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Expected_Arrival__c</fullName>
    <description>(B2T) Will be transferred to the Group Booking Object</description>
    <inlineHelpText>This Time the booker entered on the web form</inlineHelpText>
    <label>Expected Arrival</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Expected_Departure__c.field-meta.xml
<CustomField>
    <fullName>Expected_Departure__c</fullName>
    <description>(B2T) MICE web capture field</description>
    <label>Expected Departure</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Food_Beverage__c.field-meta.xml
<CustomField>
    <fullName>Food_Beverage__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(B2T) MICE Capture Field</description>
    <label>Food &amp; Beverage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(B2T) MICE Capture Field</description>
    <label>Gift</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Gift_Card__c.field-meta.xml
<CustomField>
    <fullName>Gift_Card__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(B2T) MICE Capture Field</description>
    <label>Gift Card</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Group_Type__c.field-meta.xml
<CustomField>
    <fullName>Group_Type__c</fullName>
    <description>(B2T) will be transferred to the Group Booking object</description>
    <label>Group Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Leisure</fullName>
            </value>
            <value>
                <fullName>MICE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <description>(B2T) MICE Capture form field</description>
    <label>Mode of Transport</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Car</fullName>
            </value>
            <value>
                <fullName>Coach</fullName>
            </value>
            <value>
                <fullName>Limo</fullName>
            </value>
            <value>
                <fullName>Taxi</fullName>
            </value>
            <value>
                <fullName>Train</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Name_of_Event__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Event__c</fullName>
    <description>(B2T) The name of the event that will be transferred to the Group Booking</description>
    <label>Name of Event</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Notes_and_Additional_Comments__c.field-meta.xml
<CustomField>
    <fullName>Notes_and_Additional_Comments__c</fullName>
    <description>(B2T) MICE Capture Field</description>
    <label>Notes and Additional Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Number_of_Visitors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Visitors__c</fullName>
    <description>(B2T) MICE Capture field</description>
    <label>Expected Number of Visitors</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Quick_Convert__c.field-meta.xml
<CustomField>
    <fullName>Quick_Convert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quick Convert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>(B2T) MICE cature field</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Oceania</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Secondary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Email_Address__c</fullName>
    <description>If the booking is not converting because of duplication issues, move the email address into this field</description>
    <inlineHelpText>If the booking is not converting because of duplication issues, move the email address into this field</inlineHelpText>
    <label>Secondary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Transport_Required__c.field-meta.xml
<CustomField>
    <fullName>Transport_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(B2T) MICE Capture Field</description>
    <label>Transport Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Village_of_Visit_c__c.field-meta.xml
<CustomField>
    <fullName>Village_of_Visit_c__c</fullName>
    <description>(B2T) MICE Capture Field</description>
    <label>Primary Village of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/VIP_Lounge_Access__c.field-meta.xml
<CustomField>
    <fullName>VIP_Lounge_Access__c</fullName>
    <defaultValue>false</defaultValue>
    <description>B2T - Mice Capture Field</description>
    <label>VIP Lounge Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Visitors_Country_of_Origin__c.field-meta.xml
<CustomField>
    <fullName>Visitors_Country_of_Origin__c</fullName>
    <description>(B2T) captured from MICE web form</description>
    <label>Visitors Country of Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>ALAND ISLANDS</fullName>
            </value>
            <value>
                <fullName>ALBANIA</fullName>
            </value>
            <value>
                <fullName>ALGERIA</fullName>
            </value>
            <value>
                <fullName>AMERICAN SAMOA</fullName>
            </value>
            <value>
                <fullName>ANDORRA</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTARCTICA</fullName>
            </value>
            <value>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </value>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARMENIA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>AZERBAIJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BARBADOS</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDA</fullName>
            </value>
            <value>
                <fullName>BHUTAN</fullName>
            </value>
            <value>
                <fullName>BOLIVIA, PLURINATIONAL STATE OF</fullName>
            </value>
            <value>
                <fullName>BONAIRE, SAINT EUSTATIUS AND SABA</fullName>
            </value>
            <value>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Welcome_Pack__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Pack__c</fullName>
    <defaultValue>false</defaultValue>
    <description>MICE Capture Field</description>
    <label>Welcome Pack</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Greater China</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>Not Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Rest of World</fullName>
    </customValue>
    <customValue>
        <fullName>Russia &amp; CIS</fullName>
    </customValue>
    <customValue>
        <fullName>South East Asia</fullName>
    </customValue>
    <customValue>
        <fullName>US</fullName>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadActionsController.cls
//Actions for the lead page
//Daniel Childs & Ian Burton 06/04/2017
Public Class LeadActionsController {

    private ApexPages.StandardController standardController;
    public Boolean showbutton  { get; set; }
    public String redirectUrl {public get; private set;}
    public Boolean shouldRedirect {public get; private set;}
    public Boolean showerror {public get; private set;}
    public String errormessage {public get; public set;}
    public String displayEmailError {get; set;}
    public String displayAccountRefError {public get; public set;}
    public String displayvillageError {get; set;}
    public String displayEmailCompanyError {get; set;}
    
    

       
    
    public LeadActionsController(ApexPages.StandardController standardController){ 
    //Initialise the variables and get lead data
        this.standardController = standardController;   
        showbutton = False;
        shouldRedirect = False;
        //system.debug('shouldredirect1 :'+shouldredirect);
        Id recordId = standardController.getId();
        Lead record = [SELECT id,Village_of_Visit_c__c, Account_Reference__c,Account_Reference_Number__c,Create_Group_Booking__c,Quick_Convert__c,Email, Secondary_Email_Address__c,Account_Reference__r.id,company,Account_Reference__r.Name,Account_Reference__r.Account_Reference_Number__c from LEAD WHERE id =:recordId];
        displayEmailError = LeadUtilities.displayEmailError(record);
        displayAccountRefError = LeadUtilities.displayAccountRefError(record);
        //Only display the button if there is an account reference set from process builder workflow
        showbutton = (LeadUtilities.canQuickConvert(record) && record.Quick_Convert__c);
        displayvillageError = LeadUtilities.displayvillageError(record);
        displayEmailCompanyError = LeadUtilities.displayEmailCompanyError(record);
        
    }
    
    public PageReference QuickConvert(){
            //button press action from visualforce page
            Id record2Id = standardController.getId();
            Lead record2 = [SELECT id, 
            Account_Reference__c,Account_Reference_Number__c,Quick_Convert__c,Create_Group_Booking__c,FirstName,LastName,email,Secondary_Email_Address__c,
            phone,Leadsource,company,Account_Reference__r.name,Name_of_Event__c,account_reference__r.ownerid,Account_Reference__r.id,Account_Reference__r.Account_Reference_Number__c,Village_of_Visit_c__c,Boutique_Private_Viewing__c,Group_Type__c
            ,Expected_Arrival__c,Expected_Departure__c,Number_of_Visitors__c,Visitors_Country_of_Origin__c,Region__c
            ,Transport_Required__c,Mode_of_Transport__c,Food_Beverage__c,Gift_Card__c,Gift__c,Welcome_Pack__c,VIP_Lounge_Access__c,Notes_and_Additional_Comments__c,
            Secondary_MICE_Org_or_Agency_name__c,Secondary_MICE_Contact_Country__c,Secondary_MICE_Contact_Title__c,Secondary_MICE_Contact_First_Name__c,Secondary_MICE_Contact_Last_Name__c
            ,Secondary_MICE_Contact_Position__c,Secondary_MICE_Contact_Address_1__c,Secondary_MICE_Contact_Address_2__c,Secondary_MICE_Contact_Address_3__c,Secondary_MICE_Contact_Town_City__c,Secondary_MICE_Contact_State__c
            ,Secondary_MICE_Contact_ZIP_Postcode__c,Secondary_MICE_Contact_Phone__c,Secondary_MICE_Contact_Email__c from LEAD WHERE id =:record2Id ];
            RecordType RecordTypeid = [Select id from RecordType WHERE name = 'Tourism Contact' AND sObjectType = 'Contact'];
            
            //system.debug('cancquickconvert :'+LeadUtilities.canQuickConvert(record2));
            //displayAccountRefError = LeadUtilities.displayAccountRefError(record2);
         
            IF(LeadUtilities.canQuickConvert(record2)){ 
            try{
            boolean wasQuickConverted = LeadUtilities.quickConvert(record2);           
                        
            //create leadconversion object     
            //check lead conversion result
            if(!wasQuickConverted){
               errormessage = 'Failed to convert lead';
               throw new leadconvertException('Cannot convert lead');
            } 
            shouldRedirect = true;
            //system.debug('shouldredirect1.1 :'+shouldredirect);
            redirectUrl = standardController.view().getUrl();
            return null;
           }
            catch (DMLException e){
            if(e.getDmlType(0) == system.StatusCode.DUPLICATE_VALUE){
                errormessage = 'Duplicate value found, please check the data';
            }
             
            if(e.getDmlType(0) == system.StatusCode.REQUIRED_FIELD_MISSING){
                errormessage = 'A required field is missing, please check the data';
            }  
            
            if(e.getDmlType(0) == system.StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION){
                errormessage = 'At least one of Mobile, Phone or Email address must be entered before you can save the record';
            } 
            
            shouldredirect = false;
            //system.debug('shouldredirect2 :'+shouldredirect);
            showerror = true;
            return null;
            
            
            
        }
        catch (exception e){
            shouldredirect = false;
            errormessage = 'Please check the data';
            //system.debug('shouldredirect3 :'+shouldredirect);
            showerror = true;
            return null;
              
        }
            
            }
           
            else{
            errormessage = 'Cannot Quick convert, please check Company Name matches Account Reference Name';
            shouldredirect = false;
            //system.debug('shouldredirect4 :'+shouldredirect);
            showerror = true;
            return NUll;   
            }
    
        
            
        }
        public class leadconvertException extends Exception {}

}