force-app/main/default/objects/Account/fields/Assignment_Type__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Type__c</fullName>
    <description>The assignment type of the brand</description>
    <inlineHelpText>The assignment type of the brand</inlineHelpText>
    <label>Assignment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Local Village</fullName>
            </value>
            <value>
                <fullName>Group Retail</fullName>
            </value>
            <value>
                <fullName>Multi-Village</fullName>
            </value>
            <value>
                <fullName>No Village</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Competitor_site__c/Competitor_site__c.object-meta.xml
<CustomObject>
    <description>Competitor outlet centers to replace VRNET

http://intranet.valueretail.com/remerchandising/New%20Schemes/Forms/AllItems.aspx</description>
    <label>Competitor Site</label>
    <nameField>
        <label>Competitor Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_site__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Developing Full Price</fullName>
            </value>
            <value>
                <fullName>Developing Outlet</fullName>
            </value>
            <value>
                <fullName>Existing Full Price</fullName>
            </value>
            <value>
                <fullName>Existing Outlet</fullName>
            </value>
            <value>
                <fullName>Closed Full Price</fullName>
            </value>
            <value>
                <fullName>Closed Outlet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor_Store__c/Competitor_Store__c.object-meta.xml
<CustomObject>
    <description>resolving Many-to-Many junction object</description>
    <label>Competitor Store</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Competitor Store ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Store</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Store__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitor Store</relationshipLabel>
    <relationshipName>Competitor_Store</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Competitor_Store__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Village Presence</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>Competitor Stores</relationshipLabel>
    <relationshipName>Competitor_Store</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <inlineHelpText>Add a Village Presence Contact Role to add Villages to this field</inlineHelpText>
    <label>Village Presence</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/Daily_Sales_Certification_Batch__c.object-meta.xml
<CustomObject>
    <description>Brand Portal object that will save all records related to the certifications</description>
    <label>Daily Sales Certification Batch</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Sales Certification Batches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status of this Certification Batch</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Being Prepared</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Batch Complete</fullName>
            </value>
            <value>
                <fullName>Re-opened</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Village Presence</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogFile__c/LogFile__c.object-meta.xml
<CustomObject>
    <label>LogFile</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>LogFile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LogFiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogFile__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B2B Report Emails</fullName>
            </value>
            <value>
                <fullName>ETLWebService</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the detail of all units in VR Villages</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>...</description>
    <inlineHelpText>Select the Village where this unit lives</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Village Presence records must be linked to Brand accounts. Please ensure you are not linking the Deal/Village Presence to a Group</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deal Pending</fullName>
            </value>
            <value>
                <fullName>Trading</fullName>
            </value>
            <value>
                <fullName>in Refit</fullName>
            </value>
            <value>
                <fullName>Exited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/Village_Presence_Contact_Role__c.object-meta.xml
<CustomObject>
    <label>Village Presence Contact Role</label>
    <nameField>
        <displayFormat>VPC-{00000}</displayFormat>
        <label>Village Presence Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Village Presence Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must be a Brand Contact</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Village Presence Contact Roles</relationshipLabel>
    <relationshipName>Village_Presence_Contact_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Village Presence</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>Village Presence Contact Roles</relationshipLabel>
    <relationshipName>Village_Presence_Contact_Roles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VR1_Configuration_Settings__c/VR1_Configuration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration settings for VR1</description>
    <label>VR1 Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/VR1_Configuration_Settings__c/fields/Default_VP_Status__c.field-meta.xml
<CustomField>
    <fullName>Default_VP_Status__c</fullName>
    <description>Default status for newly created Village Presence record.</description>
    <inlineHelpText>Default status for newly created Village Presence record.</inlineHelpText>
    <label>Default VP Status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VR1_Configuration_Settings__c/fields/Salesforce_Instance_URL__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Instance_URL__c</fullName>
    <defaultValue>&quot;https://login.salesforce.com&quot;</defaultValue>
    <description>The base URL of the Salesforce instance. This can be referenced from external sites to provide links back the relevant Salesforce instance.</description>
    <inlineHelpText>The base URL of the Salesforce instance. This can be referenced from external sites to provide links back the relevant Salesforce instance.</inlineHelpText>
    <label>Salesforce Instance URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/VillagePresenceUtilities.cls
public without sharing class VillagePresenceUtilities {
	
	public static boolean updateProcessed = false;

	//send and return a single instance of a Village Presence record
	public static Village_Presence__c getVillagePresence(string village, string brand){
	
		Village_Presence__c villagePresence = null;
		try{
			villagePresence	= [SELECT id, name, village__r.name, village__r.Village_code__c, 
								Brand__r.name 
								FROM Village_Presence__c 
								WHERE (Village__r.Name = :village OR Village__r.Village_Code__c = :village)
								AND (Brand__r.Name = :brand) 								
								LIMIT 1];
		} catch (Exception e){
			villagePresence = null;	
		}	
							 
		return villagePresence;
	}//end method


	//[overload]send and return a map of village presence records given an account and list of villages
	public static map<string, map<string,Village_Presence__c>> getVillagePresence(map<string, list<string>> brandsVillages){
		
		//extract all the brands
		set<string> brandset = brandsVillages.keyset();
			system.debug('brandset: ' + brandset);
		
		set<string> villageset = new set<string>();
		
		//extract all the villages and put them in the set
		for (string brand : brandset) {
				
		 	list<string> villages =  brandsVillages.get(brand);
			
			for (string village : villages){
				villageset.add(village);
			}
				
		}

		//Get all possible village presences given all villages from all brands (OR) from above variables
		//This enables us to run just one SOQL call.
		list<Village_Presence__c> villagePresences = [SELECT id, name, unit__c, village__r.name, village__r.Village_code__c, brand__r.name
														 FROM Village_Presence__c WHERE (Village__r.Name in :villageset OR Village__r.Village_Code__c in :villageset) AND brand__r.Name in :brandset];
		
		//create a map that matches the return type of the method
		map<string, map<string,Village_Presence__c>> brandVillagePresences = new map<string, map<string,Village_Presence__c>>();
			
			
		//loop through all the unique brands sent through
		for (string brand: brandset){
						
			//create the village-->village presence map which is embedded into the brandVillagePresences map
			map<string ,Village_Presence__c> villagePresence = new map<string ,Village_Presence__c>();
			
			//now loop through the village presence records that were returned from our 1 x soql
			for (Village_Presence__c vp : villagePresences ) {	
				//if the brand we are looping through matches the brand on the village presence then add the record
				//details to the village-->village presence map 
				if(brand == vp.brand__r.name){					
					villagePresence.put(vp.village__r.name, vp);
				}
			}
			//add to brandVillageTenancies MAP here
			brandVillagePresences.put(brand, villagePresence);
		
		}//end loop. Go and fetch the next brand and go through the returned village presences again.
	
		
		return brandVillagePresences;
	}//close method


	// method to create a village presence
	public static Village_Presence__c createVillagePresence(Id brandId, string village){
		
		string defaultStatus = 'Open';
		
		VR1_Configuration_Settings__c profileSettings = VR1_Configuration_Settings__c.getInstance();
		string defaultVPStatus = profileSettings.Default_VP_Status__c;
		
		if (string.isNotBlank(defaultVPStatus)){
			defaultStatus = defaultVPStatus;
		} else {
			VR1_Configuration_Settings__c orgSettings = VR1_Configuration_Settings__c.getOrgDefaults();
			defaultVPStatus = orgSettings.Default_VP_Status__c;
			if (string.isnotblank(defaultVPStatus)){
				defaultStatus = defaultVPStatus;
			}			
		}
		
		Village_Presence__c villagePresence = null;

		Id villageId = [select Id from village__c where name=:village or village_code__c =:village].Id;

		villagePresence = new Village_Presence__c(village__c = villageId, 
														Brand__c = brandId, 
														Name = '<Blank>',
														Status__c = defaultStatus
														);


		insert villagePresence;
		
		
		return villagePresence;
	}
	
	// method to create a village presence
	// overloaded, to be able to accept villageID instead of querying all the time
	public static Village_Presence__c createVillagePresence(Id brandId, Id villageId, boolean insertObject){
		
		string defaultStatus = 'Open';
		
		VR1_Configuration_Settings__c profileSettings = VR1_Configuration_Settings__c.getInstance();
		string defaultVPStatus = profileSettings.Default_VP_Status__c;
		
		if (string.isNotBlank(defaultVPStatus)){
			defaultStatus = defaultVPStatus;
		} else {
			VR1_Configuration_Settings__c orgSettings = VR1_Configuration_Settings__c.getOrgDefaults();
			defaultVPStatus = orgSettings.Default_VP_Status__c;
			if (string.isnotblank(defaultVPStatus)){
				defaultStatus = defaultVPStatus;
			}			
		}
		
		Village_Presence__c villagePresence = null;

		//Id villageId = [select Id from village__c where name=:village or village_code__c =:village].Id;

		villagePresence = new Village_Presence__c(village__c = villageId, 
														Brand__c = brandId, 
														Name = '<Blank>',
														Status__c = defaultStatus
														);

		if(insertObject){
			insert villagePresence;
		}
		
		return villagePresence;
	}

	// Method to default village presence name after insert or update
	public static void defaultName(Set<Id> villagePresenceIds){
	
		if (!villagePresenceIds.isEmpty()){
			
			list<Village_Presence__c> villagePresenceList = [select name, brand__r.name, village__r.name from Village_Presence__c where id in:villagePresenceIds];
			if (!villagePresenceList.isEmpty()){
					for (Village_Presence__c villagePresence : villagePresenceList){
							string brand = villagePresence.brand__r.name;
							string village = villagePresence.village__r.name;
							
							string name = brand + ' in ' + village;
							villagePresence.name = name;
						}
				update villagePresenceList;
			}
		}	
	}


	// Method to check if duplicate village presence record already exists
	public static list<Village_Presence__c> checkDuplicate(list<Village_Presence__c> vpList){
	
		set<string> brandIds = new set <string>();
		set<string> villageIds = new set<string>();
		
		for (Village_Presence__c vp :vpList){
			brandIds.add(vp.brand__c);
			villageIds.add(vp.village__c);
		}
		
		if (!vpList.isEmpty()){
			map<Id, Village_presence__c> vpQueryMap = new map<Id, Village_Presence__c>([select id, brand__c, village__c,
																						brand__r.name, village__r.name 
																						from Village_Presence__c
								 														where brand__c in :brandIds and village__c in :villageIds]); 
			
			for (Village_Presence__c villagePresence :vpList){
				string brand = villagePresence.brand__c;
				string village = villagePresence.village__c;
				for (Village_Presence__c vpChk : vpQueryMap.values()) {				
					if (brand == vpChk.brand__c && village == vpChk.village__c){
	        			VR1_Configuration_Settings__c settings = VR1_Configuration_Settings__c.getOrgDefaults();
	        			string url = settings.Salesforce_Instance_URL__c;
	        			url += '/' + vpChk.Id;						  
						string msg = vpChk.brand__r.name +' already exists in ' + vpChk.village__r.name;
						villagePresence.addError(msg, false);
					
					}
				}
				
			}

		}	
		
		return vpList;
		
	}

	
	// Method to keep in sync the village presence list held at contact level with any village roles 
	// created for the contact
	//@future
	public static void refreshContactVillagePresence(list<string> contactIdList){
		
		// retrieve map of contacts for later update
		map<Id, Contact> contactMap = new map<Id, Contact>([select id, village_presence__c from contact where id in :contactIdList]);
		
		// create a map to store the contact village data 
		map <Id, set<string>> contactVillageMap = new map<Id, set<string>>();
		
		if (!contactMap.isEmpty()){
			// retrieve village contact roles for the contacts required
			list<Village_Presence_Contact_Role__c> contactRoleList = new list <Village_Presence_Contact_Role__c>();
			contactRoleList = [select Village_Presence__r.village__r.name, contact__r.Id
								from Village_Presence_Contact_Role__c
								where contact__r.Id in:contactIdList];
		
			// loop through village contact roles to populate contact village mapping
			for (Village_Presence_Contact_Role__c contactRole :contactRoleList){
				set<string> villageList = contactVillageMap.get(contactRole.contact__r.Id);
				if (villageList == null){
					villageList = new set<string>();
				}
				villageList.add(contactRole.Village_Presence__r.village__r.name);
				contactVillageMap.put(contactRole.Contact__r.Id, villageList);		
			}
			
			// loop through contact list to update village presence field with villages
			// identified for the contact
			for (Contact c :contactMap.values()){
				string contactVillages = '';
				set<string> villages = new set<string>();
				villages = contactVillageMap.get(c.Id);
				if (villages != null){
					if (!villages.isEmpty()){
						for(string village :villages){
							contactVillages += village + ';';
						}
					}
				}
								
				c.Village_Presence__c = contactVillages;
				
			}
			update contactMap.values();
		
		}	
		
		
	}
	
	public static void recalculateBrandAssignmentType(List<Village_Presence__c> newlist){
		// now we serialize this data, and hand it to the future method
		List<String> newlistJSON = new List<String>();

		for(Village_Presence__c VP : newlist){
			newlistJSON.add(JSON.serialize(VP));
		}

		recalculateBrandAssignmentType(newlistJSON);

	}

	@future
	private static void recalculateBrandAssignmentType(List<String> newlistJSON){
		// this is just to trigger the 'tickle' of the brand, so that the assignment type gets recalculated.
		Set<ID> VPIds = new Set<ID>();
		Village_Presence__c VP = null;
   		for (String ser : newlistJSON)
     	{
       		VP = (Village_Presence__c)JSON.deserialize(ser, Village_Presence__c.class);
       		if(!VPIds.contains(VP.Brand__c)){
				VPIds.add(VP.Brand__c);
			}
     	}

/*
		for(Village_Presence__c VP :newlist){
			if(!VIPIds.contains(VP.Brand__c)){
				VIPIds.add(VP.Brand__c);
			}
		}*/

		List<Account> accs = [Select ID, Assignment_Type__c FROM Account WHERE ID in :VPIds];

		for(Account ac :accs){
			// just blanking the assignment type. this will force the brand account trigger.
			ac.Assignment_Type__c = '';
		}
		update accs;
	}

	// Method to link any existing competitor stores with village presence when VP upserted
	//@future
	public static void linkCompetitorStores(set<Id> vpIdList){
		
		set<Id> brandList = new set<Id>();
		set<Id> villageList = new set<Id>();
		
		list<Village_Presence__c> vpList = [select Id, Brand__c, Village__c from Village_Presence__c where Id in:vpIdList];
		map<string, Id> vpMap = new map<string, Id>();
		
		for (Village_presence__c vp :vpList){
			string brand = vp.Brand__c;
			string village = vp.Village__c;
			brandList.add(brand);
			villageList.add(village);
			vpMap.put(brand + village, vp.Id);			
		}
		
		list<Competitor_Store__c> storeUpdateList = new list<Competitor_Store__c>();
		
		storeUpdateList = [select Id, Brand__c, Village_Presence__c, Competitor_Site__r.Competitor_to_Village__c
							from Competitor_Store__c 
							where 
							Brand__c in :brandList and  
							Competitor_Site__r.Competitor_to_Village__c in :villageList];
		
		if (!storeUpdateList.isEmpty()){
			for (Competitor_store__c store :storeUpdateList){
				string brand = store.Brand__c;
				string village = store.Competitor_Site__r.Competitor_to_Village__c;
				string vpId = vpMap.get(brand + village);
				if (!string.isBlank(vpId)){
					store.Village_Presence__c = vpId;
				}
			}
			update storeUpdateList;
		}					
		
		
	}

	public static void defaultNameOnUpdate(List<Village_Presence__c> oldMap, List<Village_Presence__c> newMap){

		Set<Id> oldValueUpdatedVP = new Set<Id>();
		for(Village_Presence__c oldValue : oldMap){
			oldValueUpdatedVP.add(oldValue.Id);
		}

		List<Village_Presence__c> oldVillagePresenceList = [SELECT Name, Brand__r.Name, Village__r.Name FROM Village_Presence__c WHERE Id IN:oldValueUpdatedVP];

		for(Village_Presence__c theOldVP : oldVillagePresenceList){
			for (Village_Presence__c villagePresence : newMap){
				if(theOldVP.Id == villagePresence.Id && theOldVP.Name != villagePresence.Name){
					string brand = theOldVP.Brand__r.Name;
					string village = theOldVP.village__r.name;
					
					string name = brand + ' in ' + village;
					villagePresence.name = name;
				}
			}
		}
	}

	public static void changeCertificationType(List<Village_Presence__c> oldMap, List<Village_Presence__c> newMap){
		
		Map<Id, String> newValuesMap = new Map<Id, String>();
		Map<Id, Boolean> newCheckboxMap = new Map<Id,Boolean>();
		Map<Id, String> newVCMap = new Map<Id, String>();
		Set<Id> setIds = new Set<Id>();

		for(Village_Presence__c newValue : newMap){
			newCheckboxMap.put(newValue.Id, newValue.CertSales_Active__c);
			newValuesMap.put(newValue.Id, newValue.CertSales_CertPeriod_Type__c);
			newVCMap.put(newValue.Id, newValue.Village__r.Village_Code__c);
		}

		for(Village_Presence__c oldValue : oldMap){
			if(oldValue.CertSales_Active__c == true && newCheckboxMap.get(oldValue.Id) == true){
				if(oldValue.CertSales_CertPeriod_Type__c != newValuesMap.get(oldValue.Id)){
                    setIds.add(oldValue.Id);
				}
			}
		}

		if(!setIds.isEmpty()){
			List<Daily_Sales_Certification_Batch__c> updDSCB = new List<Daily_Sales_Certification_Batch__c>();
			List<Daily_Sales_Certification_Batch__c> newDSCB = new List<Daily_Sales_Certification_Batch__c>();
			List<Daily_Sales_Certification_Batch__c> allActiveDSCB = [SELECT Id, Period_End_Date__c, Period_Start_Date__c, Village_Presence__c, Village_Presence__r.Name
																	FROM Daily_Sales_Certification_Batch__c
																	WHERE Village_Presence__c = :setIds
																	AND Period_Start_Date__c <= :system.today()
                                                    				AND Period_End_Date__c >= :system.today()];

	        Date todayDate = system.today();
        	Integer numberOfDays = Date.daysInMonth(todayDate.year(),todayDate.month());
        	Date lastDayOfMonth = Date.newInstance(todayDate.year(), todayDate.month(), numberOfDays);

			for(Daily_Sales_Certification_Batch__c theDSCB : allActiveDSCB){
				if(newValuesMap.get(theDSCB.Village_Presence__c) == 'Monthly'){
					theDSCB.Period_End_Date__c = lastDayOfMonth;
					updDSCB.add(theDSCB);
				} else if(newValuesMap.get(theDSCB.Village_Presence__c) == 'Quarterly'){
					if(todayDate.month() == 1 || todayDate.month() == 4 || todayDate.month() == 7 || todayDate.month() == 10){
				        
				        Daily_Sales_Certification_Batch__c firstCertification = new Daily_Sales_Certification_Batch__c();
					    firstCertification.Certification_Batch_Village_Code__c = newVCMap.get(theDSCB.Village_Presence__c);
					    firstCertification.Status__c = 'Generated';
					    firstCertification.Village_Presence__c = theDSCB.Village_Presence__c;
					    firstCertification.Certification_Period_Type__c = 'Monthly';
						firstCertification.Period_Start_Date__c = Date.newInstance(todayDate.year(), todayDate.month()+1, 1);
			            firstCertification.Name = theDSCB.Village_Presence__r.Name + ' - ' + Integer.valueOf(todayDate.month()+1) + '/' + todayDate.year();
			            Integer firstNumbDays = Date.daysInMonth(todayDate.year(),todayDate.month()+1);
			            firstCertification.Period_End_Date__c = Date.newInstance(todayDate.year(), todayDate.month()+1, firstNumbDays);
			            firstCertification.Period_Name__c = Integer.valueOf(todayDate.month()+1) + '/' + todayDate.year();
			            newDSCB.add(firstCertification);

						Daily_Sales_Certification_Batch__c secondCertification = new Daily_Sales_Certification_Batch__c();
					    secondCertification.Certification_Batch_Village_Code__c = newVCMap.get(theDSCB.Village_Presence__c);
					    secondCertification.Status__c = 'Generated';
					    secondCertification.Village_Presence__c = theDSCB.Village_Presence__c;
					    secondCertification.Certification_Period_Type__c = 'Monthly';
						secondCertification.Period_Start_Date__c = Date.newInstance(todayDate.year(), todayDate.month()+2, 1);
			            secondCertification.Name = theDSCB.Village_Presence__r.Name + ' - ' + Integer.valueOf(todayDate.month()+2) + '/' + todayDate.year();
			            Integer secondNumbDays = Date.daysInMonth(todayDate.year(),todayDate.month()+2);
			            secondCertification.Period_End_Date__c = Date.newInstance(todayDate.year(), todayDate.month()+2, secondNumbDays);
			            secondCertification.Period_Name__c = Integer.valueOf(todayDate.month()+2) + '/' + todayDate.year();
			            newDSCB.add(secondCertification);

					} else if(todayDate.month() == 2 || todayDate.month() == 5 || todayDate.month() == 8 || todayDate.month() == 11){

				        Daily_Sales_Certification_Batch__c firstCertification = new Daily_Sales_Certification_Batch__c();
					    firstCertification.Certification_Batch_Village_Code__c = newVCMap.get(theDSCB.Village_Presence__c);
					    firstCertification.Status__c = 'Generated';
					    firstCertification.Village_Presence__c = theDSCB.Village_Presence__c;
					    firstCertification.Certification_Period_Type__c = 'Monthly';
						firstCertification.Period_Start_Date__c = Date.newInstance(todayDate.year(), todayDate.month()+1, 1);
			            firstCertification.Name = theDSCB.Village_Presence__r.Name + ' - ' + Integer.valueOf(todayDate.month()+1) + '/' + todayDate.year();
			            Integer firstNumbDays = Date.daysInMonth(todayDate.year(),todayDate.month()+1);
			            firstCertification.Period_End_Date__c = Date.newInstance(todayDate.year(), todayDate.month()+1, firstNumbDays);
			            firstCertification.Period_Name__c = Integer.valueOf(todayDate.month()+1) + '/' + todayDate.year();
			            newDSCB.add(firstCertification);
					}
				}
			}

			try{
				insert newDSCB;
				update updDSCB;
	        } catch (Exception e){
	            logFile__c log = new logFile__c();
	            log.Body__c = 'Error on update or insert certifications on VillagePresenceUtilities class on changeCertificationType method. With the following mesage: ' + e.getMessage();
	            log.Type__c = 'Update/Insert a list of remaing/news Certification Batches on VP trigger';
	            insert log;
	            system.debug('Exist an error on update or insert certifications on VillagePresenceUtilities class on changeCertificationType method. With the following mesage: ' + e.getMessage());
        	}
		}
	}

	public static void avoidBlankCertification(List<Village_Presence__c> newMap){

		Set<Id> existedVP = new Set<Id>();

		for(Village_Presence__c vp : newMap){
			if(vp.Status__c == 'Exited'){
				existedVP.add(vp.Id);
			}
		}

		if(!existedVP.isEmpty()){
			// Get Certification Batch where start date is superior of todays date
			List<Daily_Sales_Certification_Batch__c> allActiveDSCB = [SELECT Id, Period_Start_Date__c, Village_Presence__c, Village_Presence__r.Name
																	FROM Daily_Sales_Certification_Batch__c
																	WHERE Village_Presence__c = :existedVP
																	AND Period_Start_Date__c >= :system.today()];

			if(!allActiveDSCB.isEmpty()){
				try{
					delete allActiveDSCB;
				} catch (Exception e){
		            logFile__c log = new logFile__c();
		            log.Body__c = 'Error on delete certifications on VillagePresenceUtilities class on avoidBlankCertification method. With the following mesage: ' + e.getMessage();
		            log.Type__c = 'Delete a list of empty Certification Batches on VP trigger when they aren\'t necessary';
		            insert log;
		            system.debug('Exist an error on delete certifications on VillagePresenceUtilities class on avoidBlankCertification method. With the following mesage: ' + e.getMessage());
				}
			}
		}
	}
}