force-app/main/default/objects/Account/fields/BarcodeNumber__c.field-meta.xml
<CustomField>
    <fullName>BarcodeNumber__c</fullName>
    <externalId>true</externalId>
    <label>BarcodeNumber</label>
    <length>38</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/b2c_customer__c/b2c_customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/b2c_customer__c/fields/currentMotherCode__c.field-meta.xml
<CustomField>
    <fullName>currentMotherCode__c</fullName>
    <description>Current mother code</description>
    <inlineHelpText>Current mother code</inlineHelpText>
    <label>Current Mother Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QRCodePrintController.cls
public without sharing class QRCodePrintController {
    public String cmid {get; private set;}
    public String objId {get; private set;}
    public String redirectUrl {get; private set;}
    public Boolean noBarcodeNumber { get; private set; }
    
    public QRCodePrintController(){
        cmid = ApexPages.currentPage().getParameters().get('cmid');
        objId = ApexPages.currentPage().getParameters().get('id');
        
        noBarcodeNumber = false;
        
        if(cmid == null){ 
            noBarcodeNumber = true;
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'This Customer has no barcode'));
            return;
        } 
        
        String objectType = ((Id)objId).getSObjectType().getDescribe().getName();
        if(objectType == 'Account'){
            Account acc = [SELECT Id, BarcodeNumber__c FROM Account WHERE Id = :objId];
            if(String.isBlank(acc.BarcodeNumber__c)){
                noBarcodeNumber = true;
            }
        }
        else if (objectType == 'b2c_customer__c'){
            b2c_customer__c b2cCust = [SELECT Id, currentMotherCode__c FROM b2c_customer__c WHERE Id = :objId];
            if(String.isBlank(b2cCust.currentMotherCode__c)){
                noBarcodeNumber = true;
            }
        }
        
        if(noBarcodeNumber){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'This Customer has no barcode'));
        }
        
    }
    
    public PageReference redirectToRecord(){
        PageReference pg = new PageReference('/' + objId);
        pg.setRedirect(true);
        return pg;  
    }
}