force-app/main/default/objects/Account/fields/Brand_Gender__c.field-meta.xml
<CustomField>
    <fullName>Brand_Gender__c</fullName>
    <description>The gender that the brand targets</description>
    <inlineHelpText>The gender that the brand targets</inlineHelpText>
    <label>Brand Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Women’s</fullName>
            </value>
            <value>
                <fullName>Men’s</fullName>
            </value>
            <value>
                <fullName>Children’s</fullName>
            </value>
            <value>
                <fullName>Mixed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Guest_Relevance__c.field-meta.xml
<CustomField>
    <fullName>Brand_Guest_Relevance__c</fullName>
    <description>The main geographic markets the brand resonates with</description>
    <inlineHelpText>The main geographic markets the brand resonates with. Select one or more</inlineHelpText>
    <label>Brand Guest Relevance</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Russia</fullName>
            </value>
            <value>
                <fullName>Central &amp; South America</fullName>
            </value>
            <value>
                <fullName>South East Asia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Segment__c.field-meta.xml
<CustomField>
    <fullName>Brand_Segment__c</fullName>
    <description>The main segmentation details for the brand</description>
    <inlineHelpText>The main segmentation details for the brand</inlineHelpText>
    <label>Brand Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apparel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>Brand_Subsegment__c</fullName>
    <description>The subsegmentation details for the brand</description>
    <inlineHelpText>The subsegmentation details for the brand</inlineHelpText>
    <label>Brand Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apparel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_VR_Positioning__c.field-meta.xml
<CustomField>
    <fullName>Brand_VR_Positioning__c</fullName>
    <description>The target market position for the brand.</description>
    <inlineHelpText>The target market position for the brand.</inlineHelpText>
    <label>Brand VR Positioning</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lifestyle</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Luxury</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Brand_Segmentation_Approval__c/Brand_Segmentation_Approval__c.object-meta.xml
<CustomObject>
    <description>Allows the user to change the segmentation details of a brand, and then submit it for approval.</description>
    <label>Brand Segmentation Approval</label>
    <nameField>
        <displayFormat>BSA-{00000}</displayFormat>
        <label>Brand Segmentation Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Segmentation Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Approval_Date__c</fullName>
    <description>The date that the record was approved</description>
    <inlineHelpText>The date that the record was approved</inlineHelpText>
    <label>Approval Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description>The brand that the segmentation approval belongs to.</description>
    <inlineHelpText>The brand that the segmentation approval belongs to</inlineHelpText>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only a Brand can be linked to a segmentation approval record</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <infoMessage>Please select a Brand account</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Segmentation Approvals</relationshipLabel>
    <relationshipName>Brand_Segmentation_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Brand_Gender__c.field-meta.xml
<CustomField>
    <fullName>Brand_Gender__c</fullName>
    <description>The gender that the brand markets for</description>
    <inlineHelpText>The gender that the brand markets for</inlineHelpText>
    <label>Brand Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Women’s</fullName>
            </value>
            <value>
                <fullName>Men’s</fullName>
            </value>
            <value>
                <fullName>Children’s</fullName>
            </value>
            <value>
                <fullName>Mixed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Brand_Guest_Relevance__c.field-meta.xml
<CustomField>
    <fullName>Brand_Guest_Relevance__c</fullName>
    <description>The target geographic markets for the brand</description>
    <inlineHelpText>The target geographic markets for the brand</inlineHelpText>
    <label>Brand Guest Relevance</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Central &amp; South America</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Russia</fullName>
            </value>
            <value>
                <fullName>South East Asia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Brand_Segment__c.field-meta.xml
<CustomField>
    <fullName>Brand_Segment__c</fullName>
    <description>The primary market segment</description>
    <inlineHelpText>The primary market segment</inlineHelpText>
    <label>Brand Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Beauty &amp; Skincare</fullName>
            </value>
            <value>
                <fullName>Eyewear</fullName>
            </value>
            <value>
                <fullName>Food &amp; Drink</fullName>
            </value>
            <value>
                <fullName>Footwear</fullName>
            </value>
            <value>
                <fullName>Homewares</fullName>
            </value>
            <value>
                <fullName>Innovative Concepts</fullName>
            </value>
            <value>
                <fullName>Intimates &amp; Hosiery</fullName>
            </value>
            <value>
                <fullName>Leather Goods</fullName>
            </value>
            <value>
                <fullName>Sports &amp; Active</fullName>
            </value>
            <value>
                <fullName>Swimwear</fullName>
            </value>
            <value>
                <fullName>Tech</fullName>
            </value>
            <value>
                <fullName>Travel &amp; Luggage</fullName>
            </value>
            <value>
                <fullName>Watches &amp; Jewellery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Brand_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>Brand_Subsegment__c</fullName>
    <description>The secondary market segment</description>
    <inlineHelpText>The secondary market segment</inlineHelpText>
    <label>Brand Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Brand_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Books &amp; Stationary</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Baby &amp; Toddler Apparel</fullName>
            </value>
            <value>
                <fullName>Beauty Services</fullName>
            </value>
            <value>
                <fullName>Glasses</fullName>
            </value>
            <value>
                <fullName>Fast Food</fullName>
            </value>
            <value>
                <fullName>Casual Footwear</fullName>
            </value>
            <value>
                <fullName>Books &amp; Stationery</fullName>
            </value>
            <value>
                <fullName>Classroom Space</fullName>
            </value>
            <value>
                <fullName>Pyjamas and Loungewear</fullName>
            </value>
            <value>
                <fullName>Leather Goods</fullName>
            </value>
            <value>
                <fullName>Sports Apparel</fullName>
            </value>
            <value>
                <fullName>Beachwear</fullName>
            </value>
            <value>
                <fullName>Home Tech</fullName>
            </value>
            <value>
                <fullName>Travel &amp; Luggage</fullName>
            </value>
            <value>
                <fullName>Jewellery</fullName>
            </value>
            <value>
                <fullName>Children&apos;s Apparel</fullName>
            </value>
            <value>
                <fullName>Colour Cosmetics</fullName>
            </value>
            <value>
                <fullName>Sunglasses</fullName>
            </value>
            <value>
                <fullName>Kiosk</fullName>
            </value>
            <value>
                <fullName>Children&apos;s Footwear</fullName>
            </value>
            <value>
                <fullName>Cookware</fullName>
            </value>
            <value>
                <fullName>Concept Store</fullName>
            </value>
            <value>
                <fullName>Socks and Hosiery</fullName>
            </value>
            <value>
                <fullName>Sports Footwear</fullName>
            </value>
            <value>
                <fullName>Swimsuits</fullName>
            </value>
            <value>
                <fullName>Personal Tech</fullName>
            </value>
            <value>
                <fullName>Watches</fullName>
            </value>
            <value>
                <fullName>Denim</fullName>
            </value>
            <value>
                <fullName>Fragrance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Brand_VR_Positioning__c.field-meta.xml
<CustomField>
    <fullName>Brand_VR_Positioning__c</fullName>
    <description>The market position for the brand</description>
    <inlineHelpText>The market position for the brand</inlineHelpText>
    <label>Brand VR Positioning</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accessible</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Luxury</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>the status of the approval</description>
    <inlineHelpText>the status of the approval</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Requesting Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SegmentationApprovalExtension.cls
public with sharing class SegmentationApprovalExtension {

	private final Brand_Segmentation_Approval__c segApproval;
    ApexPages.StandardSetController setCon;
    public Id Id { get; set; }
    public String errormessage { get; set;}
    private static final String PERMISSIONSET_APPROVED_BRAND_SEGMENTATION = 'Approve_Brand_Segmentation';
    private static final String APPROVED_STATUS = 'Approved';
  
    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public SegmentationApprovalExtension(ApexPages.StandardController stdController) {
        this.segApproval = (Brand_Segmentation_Approval__c)stdController.getRecord();
        Id = segApproval.Id;
        errormessage = '';
    }

    public SegmentationApprovalExtension(ApexPages.StandardSetController controller) {
        setCon = controller;
        errormessage = '';
    }

    public PageReference approveSegmentationRecord() {
        // we need to make sure that this user is permissioned to approve this record
        boolean hasPermissionForAction = false;

        try{
            List<PermissionSetAssignment> permissionSetAssignmentList = new List<PermissionSetAssignment>([SELECT ID FROM PermissionSetAssignment WHERE PermissionSet.Name = :PERMISSIONSET_APPROVED_BRAND_SEGMENTATION AND AssigneeId = :Userinfo.getUserId()]);

            if(!permissionSetAssignmentList.isEmpty()){
                Map<Id,Brand_Segmentation_Approval__c> brandSegmentationApprovalMap = new Map<Id,Brand_Segmentation_Approval__c>();

                // get brand record
                if(segApproval != null){
                    List<Account> accountBrandListSOQL = [Select Id FROM Account WHERE ID = : segApproval.Brand__c];
                    brandSegmentationApprovalMap.put(accountBrandListSOQL[0].Id, segApproval);
                    mappingBrandSegmentationToAccountBrand(brandSegmentationApprovalMap, accountBrandListSOQL);
                    
                    PageReference pageRef = new PageReference('/'+Id);
                    pageRef.setRedirect(true);
                    return pageRef; //Returns to the Segmentation Approval page

                } else if (setCon != null) {
                    // List View - Bulk
                    List<Brand_Segmentation_Approval__c> brandSegApprovalListGetSelect = (Brand_Segmentation_Approval__c[]) setCon.getSelected();

                    if (brandSegApprovalListGetSelect != null && !brandSegApprovalListGetSelect.isEmpty()) {
                        List<Id> brandIdList = new List<Id>();

                        // then its a list to all be approved
                        for (Brand_Segmentation_Approval__c outAccountBrand : brandSegApprovalListGetSelect) {
                            System.debug('Brand Seg Approval: ' + outAccountBrand);
                            brandSegmentationApprovalMap.put(outAccountBrand.Brand__c, outAccountBrand);
                            brandIdList.Add(outAccountBrand.Brand__c);
                        }

                        List<Account> accountBrandList = [Select Id FROM Account WHERE Id in :brandIdList];

                        mappingBrandSegmentationToAccountBrand(brandSegmentationApprovalMap, accountBrandList);

                    } else {
                        errormessage += 'No record was selected to process';
                    }
                }

            } else {
                 errormessage += 'You do not have the permission to perform this action';
            }

        } catch(Exception e){
            System.debug('The following error has occurred.');
            System.debug('Line: ' + e.getLineNumber());
            System.debug('Stack Trace: ' + e.getStackTraceString());
            errormessage += 'An error has occurred. Please contact Support, and quote the following error:\r\n';
            errormessage += ' Exception: ' + e.getMessage();
        }

        if(String.isNotBlank(errormessage)){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, errormessage));
        } else{
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, 'Records successfully approved'));
        }

        return null;
    }

    private void mappingBrandSegmentationToAccountBrand(Map<ID,Brand_Segmentation_Approval__c> inBrandSegApprovalMap, List<Account> inAccountBrandList){
        List<Brand_Segmentation_Approval__c> brandSegmentationApprovalList = new List<Brand_Segmentation_Approval__c>();

        System.debug('Mendes');
        for(Account outAccountBrand : inAccountBrandList){
            System.debug(outAccountBrand.Id);
            Brand_Segmentation_Approval__c brandSegApprovalGet = inBrandSegApprovalMap.get(outAccountBrand.Id);

            // now we can set the status to approved, and get the values over to the account
            outAccountBrand.Brand_Gender__c = brandSegApprovalGet.Brand_Gender__c;
            outAccountBrand.Brand_Guest_Relevance__c = brandSegApprovalGet.Brand_Guest_Relevance__c;
            outAccountBrand.Brand_Segment__c = brandSegApprovalGet.Brand_Segment__c;
            outAccountBrand.Brand_Subsegment__c = brandSegApprovalGet.Brand_Subsegment__c;
            outAccountBrand.Brand_VR_Positioning__c = brandSegApprovalGet.Brand_VR_Positioning__c;

            // now also update the approval data
            brandSegApprovalGet.Approval_Date__c = datetime.now();
            brandSegApprovalGet.Status__c = APPROVED_STATUS;

            brandSegmentationApprovalList.add(brandSegApprovalGet);
        }

        update brandSegmentationApprovalList;
        update inAccountBrandList;

        Approval.LockResult[] lockResultsList = Approval.lock(brandSegmentationApprovalList, false);
        // Iterate through each returned result
        for(Approval.LockResult outLockResult : lockResultsList) {
            if (outLockResult.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                System.debug('Successfully locked account with ID: ' + outLockResult.getId());

            } else {
                // Operation failed, so get all errors
                for(Database.Error err : outLockResult.getErrors()) {
                    System.debug('The following error has occurred.');
                    System.debug('LockResult: ' + err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Brand Segmentation Approval fields that affected this error: ' + err.getFields());
                }
            }
        }
    }

}