force-app/main/default/objects/Account/fields/Brand_Segment__c.field-meta.xml
<CustomField>
    <fullName>Brand_Segment__c</fullName>
    <description>The main segmentation details for the brand</description>
    <inlineHelpText>The main segmentation details for the brand</inlineHelpText>
    <label>Brand Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apparel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>Brand_Subsegment__c</fullName>
    <description>The subsegmentation details for the brand</description>
    <inlineHelpText>The subsegmentation details for the brand</inlineHelpText>
    <label>Brand Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apparel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_VR_Positioning__c.field-meta.xml
<CustomField>
    <fullName>Brand_VR_Positioning__c</fullName>
    <description>The target market position for the brand.</description>
    <inlineHelpText>The target market position for the brand.</inlineHelpText>
    <label>Brand VR Positioning</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lifestyle</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Luxury</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Secondary Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Department__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Formal</fullName>
            </value>
            <value>
                <fullName>Fashion</fullName>
            </value>
            <value>
                <fullName>Lifestyle</fullName>
            </value>
            <value>
                <fullName>Knitwear</fullName>
            </value>
            <value>
                <fullName>Outerwear</fullName>
            </value>
            <value>
                <fullName>Denim</fullName>
            </value>
            <value>
                <fullName>Baby &amp; Toddler</fullName>
            </value>
            <value>
                <fullName>Children&apos;s Apparel</fullName>
                <label>Children&apos;s</label>
            </value>
            <value>
                <fullName>Colour Cosmetics</fullName>
            </value>
            <value>
                <fullName>Skincare</fullName>
            </value>
            <value>
                <fullName>Fragrance</fullName>
            </value>
            <value>
                <fullName>Beauty Services</fullName>
            </value>
            <value>
                <fullName>Sunglasses</fullName>
            </value>
            <value>
                <fullName>Glasses</fullName>
            </value>
            <value>
                <fullName>Kiosk</fullName>
            </value>
            <value>
                <fullName>Fast Food</fullName>
            </value>
            <value>
                <fullName>Restaurant</fullName>
            </value>
            <value>
                <fullName>Packaged Products</fullName>
            </value>
            <value>
                <fullName>Classic</fullName>
            </value>
            <value>
                <fullName>Casual</fullName>
            </value>
            <value>
                <fullName>Childrens Footwear</fullName>
                <label>Childrens</label>
            </value>
            <value>
                <fullName>Linens &amp; Towels</fullName>
            </value>
            <value>
                <fullName>Home Décor</fullName>
            </value>
            <value>
                <fullName>Books &amp; Stationery</fullName>
            </value>
            <value>
                <fullName>Cookware</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Resale</fullName>
            </value>
            <value>
                <fullName>Concept Store</fullName>
            </value>
            <value>
                <fullName>Event/Experiential Space</fullName>
            </value>
            <value>
                <fullName>White Box Space (rotating pop ups)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <inlineHelpText>Segment for this deal</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Activewear</fullName>
            </value>
            <value>
                <fullName>Beauty</fullName>
            </value>
            <value>
                <fullName>Bed and Bath</fullName>
            </value>
            <value>
                <fullName>Books and Stationery</fullName>
            </value>
            <value>
                <fullName>Casualwear</fullName>
            </value>
            <value>
                <fullName>China and Glass</fullName>
            </value>
            <value>
                <fullName>Chocolatier</fullName>
            </value>
            <value>
                <fullName>Cookware</fullName>
            </value>
            <value>
                <fullName>Denim and Streetwear</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Evening Wear</fullName>
            </value>
            <value>
                <fullName>Eyewear</fullName>
            </value>
            <value>
                <fullName>Formal and Eveningwear</fullName>
            </value>
            <value>
                <fullName>General Fashion</fullName>
            </value>
            <value>
                <fullName>Handbags and Accessories</fullName>
            </value>
            <value>
                <fullName>Headwear</fullName>
            </value>
            <value>
                <fullName>Home and Gifts</fullName>
            </value>
            <value>
                <fullName>Intimates and Hosiery</fullName>
            </value>
            <value>
                <fullName>Jewellery and Watches</fullName>
            </value>
            <value>
                <fullName>Kids</fullName>
            </value>
            <value>
                <fullName>Restaurants</fullName>
            </value>
            <value>
                <fullName>Shirting</fullName>
            </value>
            <value>
                <fullName>Shoes</fullName>
            </value>
            <value>
                <fullName>Snack Bar</fullName>
            </value>
            <value>
                <fullName>Sports Shoes</fullName>
            </value>
            <value>
                <fullName>Sportswear</fullName>
            </value>
            <value>
                <fullName>Suiting</fullName>
            </value>
            <value>
                <fullName>Swimwear</fullName>
            </value>
            <value>
                <fullName>Toys</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Unit assigned to this opportunity, this is synchronized with the Unit on the Contract when the Unit is formally committed to the brand</inlineHelpText>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Village__c</field>
            <operation>equals</operation>
            <valueField>$Source.Village__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the actual village where this opportunity exists</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the detail of all units in VR Villages</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Size_GEA__c.field-meta.xml
<CustomField>
    <fullName>Size_GEA__c</fullName>
    <inlineHelpText>Enter the Gross External Area (GEA) of the unit in square meters</inlineHelpText>
    <label>Size (GEA)</label>
    <precision>13</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <inlineHelpText>Select the value that best describes the status of the Unit</inlineHelpText>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Suggested</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>Refit</fullName>
            </value>
            <value>
                <fullName>Do not use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>...</description>
    <inlineHelpText>Select the Village where this unit lives</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/B2B_Chatter_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>B2B_Chatter_Group_Name__c</fullName>
    <description>Defines the chatter group to post to when an event is created which mentions the village.</description>
    <inlineHelpText>Defines the chatter group to post to when an event is created which mentions the village.</inlineHelpText>
    <label>B2B Chatter Group Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OpportunitySegmentSynchButtonFlow_Test.cls
@isTest
private class OpportunitySegmentSynchButtonFlow_Test {

	private static Account account = new Account();
	private static Contact contact = new Contact();
	private static Opportunity opportunity = new Opportunity();
	private static Event event = new Event();
	private static Village__c village = new Village__c();
	private static Unit__c unit = new Unit__c();
	
	static void setUpData(){

		account = TestData_Account.setupBrandAccount(1, false);
		
		account.Brand_Segment__c = 'Department Test';
		account.Brand_Subsegment__c = 'Segment Test';
		account.Brand_VR_Positioning__c = 'Price Point Test';
		
		insert account;
		
		contact = TestData_Contact.setupContact('A',account, true);	
						
	 	village = new Village__c();
	 	village.Name = 'TestVillage';
	 	village.B2B_Chatter_Group_Name__c = 'B2BTestVillage';
	 	village.Village_Code__c = 'OO';
		village.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		village.CertSales_Report_Sales_Grace_Period_Days__c = 1; 
	 	insert village;
		village = [select name, id, B2B_Chatter_Group_Name__c, Village_Code__c from Village__c where Village_Code__c = 'OO' LIMIT 1];
		
		unit = new Unit__c(Name='TU1', Village__c = village.Id, size_GEA__c = 20,  Unit_Status__c = 'Available');
		insert unit;
		unit = 	[select Id, Name from Unit__c where name = 'TU1'];
		
		opportunity = new Opportunity(name = 'TestOpp', Village__c = village.Id, AccountId = account.id, CloseDate = system.today().addDays(1), StageName = 'Pipeline');
		insert opportunity;			
			
		
	}
    static testMethod void unitTest() {
        
        setupData();
        
        opportunity = [select Department__c, Segment__c, Price_point__c from Opportunity where id =:opportunity.Id];
        
        system.assertEquals(opportunity.Department__c, account.Brand_Segment__c);
        system.assertEquals(opportunity.Segment__c, account.Brand_Subsegment__c);
        system.assertEquals(opportunity.Price_point__c, account.Brand_VR_Positioning__c);
        
        opportunity.Department__c = 'Department updated';
        opportunity.Segment__c = null;
        opportunity.Price_Point__c = null;
        
        update opportunity;
        
        opportunity = [select Department__c, Segment__c, Price_point__c from Opportunity where id =:opportunity.Id];
        
        system.assertEquals(opportunity.Department__c, 'Department updated');
        system.assertEquals(opportunity.Segment__c, null);
        system.assertEquals(opportunity.Price_point__c, null);
        
        list<Id> idList = new list<Id>();
        idList.add(opportunity.Id);
        
        OpportunitySegmentSynchButtonFlow.syncSegmentationData(idList);
        
        opportunity = [select Department__c, Segment__c, Price_point__c from Opportunity where id =:opportunity.Id];
        
        system.assertEquals(opportunity.Department__c, account.Brand_Segment__c);
        system.assertEquals(opportunity.Segment__c, account.Brand_Subsegment__c);
        system.assertEquals(opportunity.Price_point__c, account.Brand_VR_Positioning__c);		
        
        
    }
}