force-app/main/default/objects/Account/fields/Brand_Referral__c.field-meta.xml
<CustomField>
    <fullName>Brand_Referral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter name of Brand Referral that resulted in this VIP Account being created.</inlineHelpText>
    <label>Brand Referral</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Car_Registration__c.field-meta.xml
<CustomField>
    <fullName>Car_Registration__c</fullName>
    <label>Car Registration</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>The company that the Guest works for</description>
    <inlineHelpText>The company the Private Client works for</inlineHelpText>
    <label>Company Name / Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country_of_Residence__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Residence__c</fullName>
    <description>Customer&apos;s Country of Residence</description>
    <inlineHelpText>Customer&apos;s Country of Residence</inlineHelpText>
    <label>Country of Residence</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Saint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Domestic_International_Partner__c.field-meta.xml
<CustomField>
    <fullName>Domestic_International_Partner__c</fullName>
    <inlineHelpText>Enter whether the partner is domestic or international.</inlineHelpText>
    <label>Domestic or International Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Guest_Source__c.field-meta.xml
<CustomField>
    <fullName>Guest_Source__c</fullName>
    <inlineHelpText>What is the reason for the VIP Account registration?</inlineHelpText>
    <label>Guest Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand_Event</fullName>
                <label>Brand Event</label>
            </value>
            <value>
                <fullName>Brand_Referral</fullName>
                <label>Brand Referral</label>
            </value>
            <value>
                <fullName>Brand Support</fullName>
            </value>
            <value>
                <fullName>Word_of_Mouth</fullName>
                <label>Guest Referral</label>
            </value>
            <value>
                <fullName>In_Village_Referral</fullName>
                <label>In Village Referral</label>
            </value>
            <value>
                <fullName>Marketing_Activity</fullName>
                <label>Marketing Activity</label>
            </value>
            <value>
                <fullName>Village_Specific</fullName>
                <label>Membership</label>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Personal_Shopper</fullName>
                <label>Personal Shopper</label>
            </value>
            <value>
                <fullName>PR/Influencer</fullName>
            </value>
            <value>
                <fullName>P/C - Apartment (BV Only)</fullName>
                <label>Private Clients Team - Apartment</label>
            </value>
            <value>
                <fullName>P/C - PR (BV Only)</fullName>
                <label>Private Clients Team - PR</label>
            </value>
            <value>
                <fullName>P/C - Tourism (BV Only)</fullName>
                <label>Private Clients Team - Tourism</label>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>WeChat</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
                <isActive>false</isActive>
                <label>Campaign</label>
            </value>
            <value>
                <fullName>Personal Shopping</fullName>
                <isActive>false</isActive>
                <label>Personal Shopping</label>
            </value>
            <value>
                <fullName>Private_Clients_Team</fullName>
                <isActive>false</isActive>
                <label>Private Clients Team</label>
            </value>
            <value>
                <fullName>Regular Guest</fullName>
                <isActive>false</isActive>
                <label>Regular Guest</label>
            </value>
            <value>
                <fullName>Special Event</fullName>
                <isActive>false</isActive>
                <label>Special Event</label>
            </value>
            <value>
                <fullName>VR Management Referral</fullName>
                <isActive>false</isActive>
                <label>VR Management Referral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Personal_Shopper__c.field-meta.xml
<CustomField>
    <fullName>Personal_Shopper__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter name of the Personal Shopper that resulted in this VIP Account being created.</inlineHelpText>
    <label>Personal Shopper</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile_Name__c</field>
            <operation>equals</operation>
            <value>Personal Shopper for Clientelling App</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts_Personal_Shopper</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <description>Customer&apos;s preferred language for communication</description>
    <inlineHelpText>Private Clients preferred language</inlineHelpText>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Brazilian-Portuguese</fullName>
            </value>
            <value>
                <fullName>Catalan</fullName>
            </value>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Turkish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Private_Client_Notes__c.field-meta.xml
<CustomField>
    <fullName>Private_Client_Notes__c</fullName>
    <inlineHelpText>Notes about your Private Client (this field is not reportable).</inlineHelpText>
    <label>Private Client Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Private_Client_Team__c.field-meta.xml
<CustomField>
    <fullName>Private_Client_Team__c</fullName>
    <inlineHelpText>Enter name of PCS Team Member or Ambassador that resulted in this VIP Account being created.</inlineHelpText>
    <label>Private Client Team</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Professional_Buyer__c.field-meta.xml
<CustomField>
    <fullName>Professional_Buyer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if guest is a Professional Buyer</description>
    <inlineHelpText>Is Private Client a Professional Buyer?</inlineHelpText>
    <label>Professional Buyer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Village_Specific__c.field-meta.xml
<CustomField>
    <fullName>Village_Specific__c</fullName>
    <inlineHelpText>Enter name of Village incentive that resulted in this VIP Account being created.</inlineHelpText>
    <label>Village Specific</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LVV Prestige</fullName>
            </value>
            <value>
                <fullName>FV Exclusive</fullName>
            </value>
            <value>
                <fullName>Membership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Label__c/Custom_Label__c.object-meta.xml
<CustomObject>
    <description>Overridden custom labels, to be used for translations where the translation workbench wont  work</description>
    <label>Custom Label</label>
    <nameField>
        <label>Custom Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Labels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Label__c/fields/Custom_Label_Value__c.field-meta.xml
<CustomField>
    <fullName>Custom_Label_Value__c</fullName>
    <description>The label value to be displayed on screen</description>
    <inlineHelpText>The label value to be displayed on screen</inlineHelpText>
    <label>Custom Label Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Label__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>The language that the label is displayed in</description>
    <inlineHelpText>The language that the label is displayed in</inlineHelpText>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en</fullName>
            </value>
            <value>
                <fullName>es</fullName>
            </value>
            <value>
                <fullName>de</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
            </value>
            <value>
                <fullName>ca</fullName>
            </value>
            <value>
                <fullName>nl</fullName>
            </value>
            <value>
                <fullName>it</fullName>
            </value>
            <value>
                <fullName>ru</fullName>
            </value>
            <value>
                <fullName>cn</fullName>
            </value>
            <value>
                <fullName>ar</fullName>
            </value>
            <value>
                <fullName>ae</fullName>
            </value>
            <value>
                <fullName>kr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VIPBBDeclineExtension.cls
global with sharing class VIPBBDeclineExtension {


    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public static String[] labelsonpage = new String[]{'OKButton', 'ThankyouTopHeader','ThankyouHeader','ThankYouContent','OKButton','DeclineContent','DeclineTopHeader','DeclineHeader','YesDeclineButton','NoDeclineButton','DeclineThankTopHeader','DeclineThankHeader','DeclineThankContent','ThankYouBelowContent'};
    public static String languagelabels {get;set;}
    public static String lang {get; set;}
     public String accId {get;set;}

    public VIPBBDeclineExtension(ApexPages.StandardController stdController) {
        lang = ApexPages.currentPage().getParameters().get('lang');
        languagelabels = getLanguageLabels(lang);
        accId = stdController.getId();
        getAccountInfo();
    }
    
    
    public Account accountRecordInfo ;
    public Account getaccountRecordInfo()
    {
        return accountRecordInfo;
    }
    public void setAccount(Account accountRecordInfo)
    {
        this.accountRecordInfo = accountRecordInfo;
    }
    
   
    
    @RemoteAction
    global static String deleteGuest(String accID){
        DeleteVIPGuest deleteguest = new DeleteVIPGuest((ID)accID);
        Account acc = [SELECT ID, Name FROM Account WHERE ID = :(ID)accID];
        try{
            System.debug('Aboun to call DeleteVIPGuestRecord');
            //deleteguest.DeleteVIPGuestRecord();
            String result = deleteguest.DeleteGuestAndCreateRecord(acc);
            return result;
          /*  if(result.startsWith('ERROR')){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, result));
            }
            else
            {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,result));
            }*/
        }
        catch(Exception ex){
            System.debug('EXCEPTION!!!=====' + ex.getMessage());
        }
        return '';
    }
    
    @RemoteAction
    global static string getLanguageLabels(String lang){
        // gets the labels for this page, for display by angular
        List<Custom_Label__c> custlabels = [SELECT ID, Name,Custom_Label_Value__c, Language__c FROM Custom_Label__c WHERE Language__c = :Lang AND Name IN :labelsonpage ];
        List<LabelValue> lblvals = new List<LabelValue>();
        for(Custom_Label__c cl :custlabels){
            LabelValue lval = new LabelValue();
            lval.LabelName = cl.Name;
            Lval.LabelValue = cl.Custom_Label_Value__c;
            lblvals.add(lval);
        }

        return JSON.serializePretty(lblvals);
    }

     private class LabelValue{
        String LabelName {get; set;}
        String LabelValue {get; set;}
     }
    
       

    global void getAccountInfo(){
        System.debug('>>> accId'+accId);
        
        List<Account>  Accounts	= [Select ID,Country_of_Residence__c, Preferred_Language__c, Company_Name__c, Car_Registration__c, Private_Client_Notes__c, Guest_Source__c ,Private_Client_Team__c, Professional_Buyer__c,Village_Specific__c,Domestic_International_Partner__c,
                                   Personal_Shopper__c,Brand_Referral__c,Brand_Event__c,Marketing_Activity__c,Partner_Program_Membership_1__c,Guest_Source_Notes__c FROM Account WHERE ID = :accId];
        
        accountRecordInfo = accounts.isEmpty() ? new Account():Accounts[0];
        System.debug('>>> accId'+ accountRecordInfo);
    }
    
    global PageReference saveAccountInfo()
    {
        SYstem.debug('Account**************'+JSON.serialize(accountRecordInfo));
        update accountRecordInfo;
        return null;
    }
    
}