force-app/main/default/objects/Account/fields/Brand_Gender__c.field-meta.xml
<CustomField>
    <fullName>Brand_Gender__c</fullName>
    <description>The gender that the brand targets</description>
    <inlineHelpText>The gender that the brand targets</inlineHelpText>
    <label>Brand Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Women’s</fullName>
            </value>
            <value>
                <fullName>Men’s</fullName>
            </value>
            <value>
                <fullName>Children’s</fullName>
            </value>
            <value>
                <fullName>Mixed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Guest_Relevance__c.field-meta.xml
<CustomField>
    <fullName>Brand_Guest_Relevance__c</fullName>
    <description>The main geographic markets the brand resonates with</description>
    <inlineHelpText>The main geographic markets the brand resonates with. Select one or more</inlineHelpText>
    <label>Brand Guest Relevance</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Russia</fullName>
            </value>
            <value>
                <fullName>Central &amp; South America</fullName>
            </value>
            <value>
                <fullName>South East Asia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Segment__c.field-meta.xml
<CustomField>
    <fullName>Brand_Segment__c</fullName>
    <description>The main segmentation details for the brand</description>
    <inlineHelpText>The main segmentation details for the brand</inlineHelpText>
    <label>Brand Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apparel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>Brand_Subsegment__c</fullName>
    <description>The subsegmentation details for the brand</description>
    <inlineHelpText>The subsegmentation details for the brand</inlineHelpText>
    <label>Brand Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apparel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_VR_Positioning__c.field-meta.xml
<CustomField>
    <fullName>Brand_VR_Positioning__c</fullName>
    <description>The target market position for the brand.</description>
    <inlineHelpText>The target market position for the brand.</inlineHelpText>
    <label>Brand VR Positioning</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lifestyle</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Luxury</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Brand_Segmentation_Approval__c/Brand_Segmentation_Approval__c.object-meta.xml
<CustomObject>
    <description>Allows the user to change the segmentation details of a brand, and then submit it for approval.</description>
    <label>Brand Segmentation Approval</label>
    <nameField>
        <displayFormat>BSA-{00000}</displayFormat>
        <label>Brand Segmentation Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Segmentation Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Approval_Date__c</fullName>
    <description>The date that the record was approved</description>
    <inlineHelpText>The date that the record was approved</inlineHelpText>
    <label>Approval Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user that this approval is assigned to</description>
    <inlineHelpText>The user that this approval is assigned to</inlineHelpText>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Brand_Segmentation_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description>The brand that the segmentation approval belongs to.</description>
    <inlineHelpText>The brand that the segmentation approval belongs to</inlineHelpText>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only a Brand can be linked to a segmentation approval record</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <infoMessage>Please select a Brand account</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Segmentation Approvals</relationshipLabel>
    <relationshipName>Brand_Segmentation_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Brand_Gender__c.field-meta.xml
<CustomField>
    <fullName>Brand_Gender__c</fullName>
    <description>The gender that the brand markets for</description>
    <inlineHelpText>The gender that the brand markets for</inlineHelpText>
    <label>Brand Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Women’s</fullName>
            </value>
            <value>
                <fullName>Men’s</fullName>
            </value>
            <value>
                <fullName>Children’s</fullName>
            </value>
            <value>
                <fullName>Mixed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Brand_Guest_Relevance__c.field-meta.xml
<CustomField>
    <fullName>Brand_Guest_Relevance__c</fullName>
    <description>The target geographic markets for the brand</description>
    <inlineHelpText>The target geographic markets for the brand</inlineHelpText>
    <label>Brand Guest Relevance</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Central &amp; South America</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Russia</fullName>
            </value>
            <value>
                <fullName>South East Asia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Brand_Segment__c.field-meta.xml
<CustomField>
    <fullName>Brand_Segment__c</fullName>
    <description>The primary market segment</description>
    <inlineHelpText>The primary market segment</inlineHelpText>
    <label>Brand Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Beauty &amp; Skincare</fullName>
            </value>
            <value>
                <fullName>Eyewear</fullName>
            </value>
            <value>
                <fullName>Food &amp; Drink</fullName>
            </value>
            <value>
                <fullName>Footwear</fullName>
            </value>
            <value>
                <fullName>Homewares</fullName>
            </value>
            <value>
                <fullName>Innovative Concepts</fullName>
            </value>
            <value>
                <fullName>Intimates &amp; Hosiery</fullName>
            </value>
            <value>
                <fullName>Leather Goods</fullName>
            </value>
            <value>
                <fullName>Sports &amp; Active</fullName>
            </value>
            <value>
                <fullName>Swimwear</fullName>
            </value>
            <value>
                <fullName>Tech</fullName>
            </value>
            <value>
                <fullName>Travel &amp; Luggage</fullName>
            </value>
            <value>
                <fullName>Watches &amp; Jewellery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Brand_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>Brand_Subsegment__c</fullName>
    <description>The secondary market segment</description>
    <inlineHelpText>The secondary market segment</inlineHelpText>
    <label>Brand Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Brand_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Books &amp; Stationary</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Baby &amp; Toddler Apparel</fullName>
            </value>
            <value>
                <fullName>Beauty Services</fullName>
            </value>
            <value>
                <fullName>Glasses</fullName>
            </value>
            <value>
                <fullName>Fast Food</fullName>
            </value>
            <value>
                <fullName>Casual Footwear</fullName>
            </value>
            <value>
                <fullName>Books &amp; Stationery</fullName>
            </value>
            <value>
                <fullName>Classroom Space</fullName>
            </value>
            <value>
                <fullName>Pyjamas and Loungewear</fullName>
            </value>
            <value>
                <fullName>Leather Goods</fullName>
            </value>
            <value>
                <fullName>Sports Apparel</fullName>
            </value>
            <value>
                <fullName>Beachwear</fullName>
            </value>
            <value>
                <fullName>Home Tech</fullName>
            </value>
            <value>
                <fullName>Travel &amp; Luggage</fullName>
            </value>
            <value>
                <fullName>Jewellery</fullName>
            </value>
            <value>
                <fullName>Children&apos;s Apparel</fullName>
            </value>
            <value>
                <fullName>Colour Cosmetics</fullName>
            </value>
            <value>
                <fullName>Sunglasses</fullName>
            </value>
            <value>
                <fullName>Kiosk</fullName>
            </value>
            <value>
                <fullName>Children&apos;s Footwear</fullName>
            </value>
            <value>
                <fullName>Cookware</fullName>
            </value>
            <value>
                <fullName>Concept Store</fullName>
            </value>
            <value>
                <fullName>Socks and Hosiery</fullName>
            </value>
            <value>
                <fullName>Sports Footwear</fullName>
            </value>
            <value>
                <fullName>Swimsuits</fullName>
            </value>
            <value>
                <fullName>Personal Tech</fullName>
            </value>
            <value>
                <fullName>Watches</fullName>
            </value>
            <value>
                <fullName>Denim</fullName>
            </value>
            <value>
                <fullName>Fragrance</fullName>
            </value>
            <value>
                <fullName>Formal Apparel</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Brand_VR_Positioning__c.field-meta.xml
<CustomField>
    <fullName>Brand_VR_Positioning__c</fullName>
    <description>The market position for the brand</description>
    <inlineHelpText>The market position for the brand</inlineHelpText>
    <label>Brand VR Positioning</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accessible</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Luxury</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Email_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Email_Notification_Date__c</fullName>
    <description>The date that the email notification was sent</description>
    <inlineHelpText>The date that the email notification was sent</inlineHelpText>
    <label>Email Notification Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Brand_Segmentation_Approval__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>the status of the approval</description>
    <inlineHelpText>the status of the approval</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Requesting Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SegmentationApprovalExtensionTest.cls
@isTest
private class SegmentationApprovalExtensionTest {
	
	private static Account account = new Account();
	private static Contact contact = new Contact();
	private static User usr = new User();
	
    
    static void setupData(){
    
    	System.runAs(new user(ID = UserInfo.getUserID())){
			usr = TestData_User.setupAdminUser(true);	
			TestData_User.addPermissionSetToUser(usr.Id, 'Approve_Brand_Segmentation');    	
		}		

		account = TestData_Account.setupBrandAccount(1, true);
		contact = TestData_Contact.setupBrandContact('A',account, true);	
	}

	@isTest 
	static void testSegmentationApproval() {
		setupData();
		// after creating a new brand account, it should trigger the creation of a segmentation approval record.
		List<Brand_Segmentation_Approval__c> bsas = [SELECT ID, Name,Approval_Date__c, Assigned_To__c, Assigned_To__r.Email, Assigned_To__r.Name, Brand__c, Brand__r.Name, Brand_Gender__c,  Brand_Guest_Relevance__c,  Brand_Segment__c,  Brand_Subsegment__c,  Brand_VR_Positioning__c,  Email_Notification_Date__c,  Status__c FROM Brand_Segmentation_Approval__c WHERE Brand__c = :account.Id];
		System.debug('account:===== ' + account.Id);
		System.debug('bsas: ' + bsas);
		System.assertEquals(bsas.size(),1,'There should be a segmentation record created' + bsas);

		// now we can test for approvals of this
		bsas[0].Brand_Gender__c = 'Mixed';
		bsas[0].Brand_Guest_Relevance__c = 'Europe';
		bsas[0].Brand_Segment__c = 'Apparel';
		bsas[0].Brand_Subsegment__c = 'Formal Apparel';
		bsas[0].Brand_VR_Positioning__c = 'Accessible';

		update bsas;
		//-----------------------------------------

		Test.startTest();
		String ErrorValue;
		system.runAs(usr) {
			
	        // Set test page passing initial parameters.
	        PageReference aPage = Page.ApproveSingleSegmentation;
	       // aPage.getParameters().put('AnyVariable', 'Test Value');
	        test.setCurrentPage(aPage);
	 
	        // Instantiate the standard controller
	        Apexpages.StandardController sc = new Apexpages.standardController(bsas[0]);
	 
	        // Instantiate the extension
	        SegmentationApprovalExtension ext = new SegmentationApprovalExtension(sc);

	        PageReference resultPage = ext.approveSegmentationRecord();
	        ErrorValue = ext.errormessage;
    	}
        Test.stopTest();

        //-----------------------------------------
		Brand_Segmentation_Approval__c resultBSA = [SELECT ID, Name,Approval_Date__c, Assigned_To__c, Assigned_To__r.Email, Assigned_To__r.Name, Brand__c, Brand__r.Name, Brand_Gender__c,  Brand_Guest_Relevance__c,  Brand_Segment__c,  Brand_Subsegment__c,  Brand_VR_Positioning__c,  Email_Notification_Date__c,  Status__c FROM Brand_Segmentation_Approval__c WHERE ID = :bsas[0].Id];

		System.assertEquals(resultBSA.Status__c, 'Approved', 'Status Should be approved.' + ErrorValue);

		// this is great, but we need to make sure that the same values are on the account.
		account = [SELECT ID, Name, Brand_Gender__c,  Brand_Guest_Relevance__c,  Brand_Segment__c,  Brand_Subsegment__c,  Brand_VR_Positioning__c FROM Account WHERE ID = :account.ID ];

		System.assertEquals(account.Brand_Gender__c, 'Mixed', 'Brand Gender should be Mixed');
		System.assertEquals(account.Brand_Guest_Relevance__c, 'Europe', 'Brand Guest Relevance should be Europe');
	}
	
	@isTest
 	static void testSegmentationApprovalExtension() {
		setupData();
		List<Brand_Segmentation_Approval__c> brandSegApprovalList = [SELECT ID, Name,Approval_Date__c, Assigned_To__c, Assigned_To__r.Email, Assigned_To__r.Name, Brand__c, Brand__r.Name, Brand_Gender__c,  Brand_Guest_Relevance__c,  Brand_Segment__c,  Brand_Subsegment__c,  Brand_VR_Positioning__c,  Email_Notification_Date__c,  Status__c FROM Brand_Segmentation_Approval__c];

		Test.startTest();
		System.runAs(usr){
			Test.setCurrentPage(Page.ApproveSegmentation);
			ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(brandSegApprovalList);
			stdSetController.setSelected(brandSegApprovalList);
			SegmentationApprovalExtension segApprovalExt = new SegmentationApprovalExtension(stdSetController);
			segApprovalExt.approveSegmentationRecord();
		}
		Test.stopTest();

	}

}