force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <inlineHelpText>Where is this partner based?</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Barbuda</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Duplicate_of_Account__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_of_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Set the Account of which this one is a duplicate of.</inlineHelpText>
    <label>Duplicate of Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select the Partner Account</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Tourism</value>
        </filterItems>
        <filterItems>
            <field>Account.Duplicate_of_Account__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Select a Partner account that this account duplicates.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Duplicates</relationshipLabel>
    <relationshipName>Duplicates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Business__c</fullName>
    <description>...</description>
    <inlineHelpText>This field is for reference only</inlineHelpText>
    <label>OLD Type of Business</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Airline</fullName>
            </value>
            <value>
                <fullName>Diplomatic</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Travel Agent/OTA</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>MICE Organisation/DMC</fullName>
            </value>
            <value>
                <fullName>DMO/Tourism Board</fullName>
            </value>
            <value>
                <fullName>Tour Operator/Wholesaler</fullName>
            </value>
            <value>
                <fullName>Travel Agent</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Influencer/Blogger</fullName>
            </value>
            <value>
                <fullName>Media Agency</fullName>
            </value>
            <value>
                <fullName>Media House</fullName>
            </value>
            <value>
                <fullName>Photographer</fullName>
            </value>
            <value>
                <fullName>Corporate Partner</fullName>
            </value>
            <value>
                <fullName>Event Management Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Tourism.recordType-meta.xml
<RecordType>
    <fullName>Tourism</fullName>
    <active>true</active>
    <description>A Partner of the Business</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Type_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Business__c</fullName>
    <label>Type of Business</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Airline</fullName>
            </value>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Attraction park</fullName>
            </value>
            <value>
                <fullName>Automobile Association</fullName>
            </value>
            <value>
                <fullName>Brochure Distribution</fullName>
            </value>
            <value>
                <fullName>Business Travel arranger</fullName>
            </value>
            <value>
                <fullName>Camping</fullName>
            </value>
            <value>
                <fullName>Car rental</fullName>
            </value>
            <value>
                <fullName>Coach operator</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Cruise company</fullName>
            </value>
            <value>
                <fullName>DMO</fullName>
            </value>
            <value>
                <fullName>Event Agency</fullName>
            </value>
            <value>
                <fullName>Excursionist</fullName>
            </value>
            <value>
                <fullName>Gay travel specialists</fullName>
            </value>
            <value>
                <fullName>General Sales Agent</fullName>
            </value>
            <value>
                <fullName>Golf &amp; Country Club</fullName>
            </value>
            <value>
                <fullName>Government body</fullName>
            </value>
            <value>
                <fullName>Hotel/Hotel Chain</fullName>
            </value>
            <value>
                <fullName>Hotel Association</fullName>
            </value>
            <value>
                <fullName>Incentive Travel Organiser</fullName>
            </value>
            <value>
                <fullName>Incoming Agency</fullName>
            </value>
            <value>
                <fullName>Incoming Operator</fullName>
            </value>
            <value>
                <fullName>Incoming specialist</fullName>
            </value>
            <value>
                <fullName>Limousine Cie</fullName>
            </value>
            <value>
                <fullName>MICE location</fullName>
            </value>
            <value>
                <fullName>MICE specialists</fullName>
            </value>
            <value>
                <fullName>National Tourist Board</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/duplicateAccountDeletetest.cls
@isTest
private class duplicateAccountDeletetest{

        private static List<Account> acts = new List<Account>();
        private static Account Act1 = new Account();  
        private static Account Act2 = new Account();
    
    
        @testSetup static void setupdata(){
          
              LIST<recordtype> actrtid = [SELECT id from Recordtype WHERE DeveloperName = 'Tourism' AND SobjectType = 'Account'];
              LIST<recordtype> conrtid = [SELECT id from Recordtype WHERE Name = 'Tourism Contact' AND SobjectType = 'Contact'];
              List<Lead> Leadstoadd = new List<lead>();
          
              //create account
              act1.name = 'ControllerTest1';
              act1.recordtypeid = actrtid[0].id;
              act1.country__c = 'Albania';
              act1.Type_of_Business__c = 'Airline';
              insert act1;
              
               //create account
              act2.name = 'ControllerTest2';
              act2.recordtypeid = actrtid[0].id;
              act2.country__c = 'Albania';
              act2.Type_of_Business__c = 'Airline';
              act2.Duplicate_of_Account__c = act1.id;
            Database.DMLOptions dmlOptions = new Database.DMLOptions();
            dmlOptions.DuplicateRuleHeader.AllowSave = true;
            Database.insert(act2, dmlOptions); 
          
         }

    
    
     
        static testmethod void mergeAccounts(){
        
            PageReference testPage = new pagereference('/apex/Duplicate_Act_Delete');
            
            Test.setCurrentPage(testPage);
            
            duplicateAccountDelete mycontroller = new duplicateAccountDelete();
            
            system.assertequals(1,mycontroller.acts.size(),'Expecting to find 1 acts' );
            
            mycontroller.deleteaccounts();
            
            List<account> deleted = [SELECT id from Account WHERE id =:Act2.id];
            system.assertequals(0,deleted.size(),'Acts is not zero');
                  
        }
         
         











}