force-app/main/default/objects/Account/fields/Customer_GUID__c.field-meta.xml
<CustomField>
    <fullName>Customer_GUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Customer GUID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Organisation__c</fullName>
    <description>The business unit within oracle</description>
    <inlineHelpText>The business unit within oracle</inlineHelpText>
    <label>Oracle Organisation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Source_Template_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Source_Template_Number__c</fullName>
    <description>The value used to map to an oracle template when sent to Oracle Fusion</description>
    <inlineHelpText>The value used to map to an oracle template when sent to Oracle Fusion</inlineHelpText>
    <label>Oracle Source Template Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/HFS_Utils_TEST.cls
@isTest
public without sharing class HFS_Utils_TEST {
	static testmethod void searchGuests_test(){
		
		Id guestRtId = Schema.SObjectType.Account.RecordTypeInfosByDeveloperName.get('Guest').RecordTypeId;
		Id vipGuestRtId = Schema.SObjectType.Account.RecordTypeInfosByDeveloperName.get('VIP_Guest').RecordTypeId;		

		Account guest1 = new Account();
		guest1.FirstName = 'Test';
		guest1.LastName = 'Test';
		guest1.RecordTypeId = guestRtId;
		guest1.PersonEmail = 'testing@mail.com';
		guest1.Customer_GUID__c = '12345';

		Account guest2 = new Account();
		guest2.FirstName = 'Tom';
		guest2.LastName = 'Tommy';
		guest2.RecordTypeId = guestRtId;
		guest2.PersonEmail = 'testing2@mail.com';
		guest2.Customer_GUID__c = '45678';

		Account vipGuest = new Account();
		vipGuest.FirstName = 'Tom';
		vipGuest.LastName = 'Tommy';
		vipGuest.RecordTypeId = vipGuestRtId;
		vipGuest.PersonEmail = 'testingvip@mail.com';
		vipGuest.Customer_GUID__c = '43338';

		insert new List <Account> {guest1, guest2, vipGuest};
		Test.setFixedSearchResults(new List <Id> {guest1.Id,guest2.Id,vipGuest.Id});
		Test.startTest();

		Map <String, List <Account>> guestsMap = HFS_Utils.searchGuests('testing');

		system.assertEquals(2, guestsMap.get('Guests').size());
		system.assertEquals(1, guestsMap.get('VIP_Guests').size());

		Test.stopTest();
		
	}

	static testmethod void getCurrencyLevelCalculator_test(){

		Village__c bv = TestDataGenerator.setupVillage(false);
		bv.Oracle_Source_Template_Number__c = '123456';
		bv.Oracle_Organisation__c = 'SourceOrg';
		bv.Name = 'Bicester';
		bv.Village_Code__c = 'BV';
		bv.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		bv.CertSales_Report_Sales_Grace_Period_Days__c = 1;

		Village__c lv = TestDataGenerator.setupVillage(false);
		lv.Oracle_Source_Template_Number__c = '123456';
		lv.Oracle_Organisation__c = 'SourceOrg';
		lv.Name = 'Bicester';
		lv.Village_Code__c = 'LV';
		lv.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		lv.CertSales_Report_Sales_Grace_Period_Days__c = 1;
		
		insert new List <Village__c> {bv, lv};

		HFSSpentLevelCalculator calculator = HFS_Utils.getCurrencyLevelCalculator('BV');

		system.assert(calculator instanceof HFSSpentLevelCalculatorBV);

		calculator = HFS_Utils.getCurrencyLevelCalculator('LV');

		system.assert(calculator instanceof HFSSpentLevelCalculatorGeneric);

	}

	static testmethod void searchVIPGuestByEmail ()  {

		Id guestRtId = Schema.SObjectType.Account.RecordTypeInfosByDeveloperName.get('VIP_Guest').RecordTypeId;

		Account guest2 = new Account();
		guest2.FirstName = 'Tom';
		guest2.LastName = 'Tommy';
		guest2.RecordTypeId = guestRtId;
		guest2.PersonEmail = 'testing2@mail.com';
		guest2.Customer_GUID__c = '45678';

		insert guest2;
		
		List<Account> vipRecords = HFS_Utils.searchVIPGuestByEmail('testing2@mail.com');
		system.assert(!vipRecords.isEmpty());

	}

	static testmethod void searchPrivilegeGuest_test ()  {

		Id guestRtId = Schema.SObjectType.Account.RecordTypeInfosByDeveloperName.get('Guest').RecordTypeId;

		Account guest2 = new Account();
		guest2.FirstName = 'Tom';
		guest2.LastName = 'Tommy';
		guest2.RecordTypeId = guestRtId;
		guest2.PersonEmail = 'testing2@mail.com';
		guest2.Customer_GUID__c = '45678';

		insert guest2;
		
		Account guestRecord = HFS_Utils.searchPrivilegeGuest('testing2@mail.com','Tom','Tommy');
		system.assert(guestRecord != null);

	}

}