force-app/main/default/objects/Account/fields/Customer_GUID__c.field-meta.xml
<CustomField>
    <fullName>Customer_GUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Customer GUID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/API_Configuration__c/API_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>API keys and parameters required for Microservice calls</description>
    <label>API Configuration</label>
</CustomObject>

force-app/main/default/objects/API_Configuration__c/fields/API_Host__c.field-meta.xml
<CustomField>
    <fullName>API_Host__c</fullName>
    <description>The base URL for all API calls</description>
    <inlineHelpText>The base URL for all API calls</inlineHelpText>
    <label>API Host</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>The API Key</description>
    <inlineHelpText>The API Key</inlineHelpText>
    <label>API Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Customer_Overview__c.field-meta.xml
<CustomField>
    <fullName>Customer_Overview__c</fullName>
    <description>Endpoint for read only customer overview items (from responsys and coniq..etc)</description>
    <inlineHelpText>Endpoint for read only customer overview items (from responsys and coniq..etc)</inlineHelpText>
    <label>Customer Overview</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Customer_Read_Items__c/API_Customer_Read_Items__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains API call definitiions for customer read-only items returned when searching/viewing an individual customer. Prefix Name field with number to determine display order.</description>
    <label>API Customer Read Items</label>
</CustomObject>

force-app/main/default/objects/API_Customer_Read_Items__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determines whether API call should be made for the item and data displayed.</description>
    <inlineHelpText>Determines whether API call should be made for the item and data displayed.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/API_Customer_Read_Items__c/fields/Display_as_Table__c.field-meta.xml
<CustomField>
    <fullName>Display_as_Table__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether data returned from api call is a list of one or more records and should therefore be displayed in a table. If not selected, it assumed that a single record form display is required.</description>
    <inlineHelpText>Indicates whether data returned from api call is a list of one or more records and should therefore be displayed in a table. If not selected, it assumed that a single record form display is required.</inlineHelpText>
    <label>Display as Table</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/API_Customer_Read_Items__c/fields/Item_Label__c.field-meta.xml
<CustomField>
    <fullName>Item_Label__c</fullName>
    <description>Label to appear as section title for the particular API call</description>
    <inlineHelpText>Label to appear as section title for the particular API call</inlineHelpText>
    <label>Item Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Customer_Read_Items__c/fields/Property_Items__c.field-meta.xml
<CustomField>
    <fullName>Property_Items__c</fullName>
    <description>Comma separated list of dynamic property items (xml tag names) to be included in read only display.</description>
    <inlineHelpText>Comma separated list of dynamic property items (xml tag names) to be included in read only display.</inlineHelpText>
    <label>Property Items</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/B2B_Chatter_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>B2B_Chatter_Group_Name__c</fullName>
    <description>Defines the chatter group to post to when an event is created which mentions the village.</description>
    <inlineHelpText>Defines the chatter group to post to when an event is created which mentions the village.</inlineHelpText>
    <label>B2B Chatter Group Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Integration_Language_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Language_Name__c</fullName>
    <description>Default language for the village used by integration layer when language has not been specified on guest creation</description>
    <inlineHelpText>Default language for the village used by integration layer when language has not been specified on guest creation</inlineHelpText>
    <label>Integration Language Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Integration_Village_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Village_Name__c</fullName>
    <description>Name used by Microservice API&apos;s to identify village.</description>
    <inlineHelpText>Name used by Microservice API&apos;s to identify village.</inlineHelpText>
    <label>Integration Village Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/apiCustomerViewControllerTest.cls
@isTest
private class apiCustomerViewControllerTest {

	
	private static API_Configuration__c settings = new API_Configuration__c();
	private static API_Customer_Read_Items__c readSettings = new API_Customer_Read_Items__c();
	private static User usr = new User();
	private static User usr2 = new User();
	private static Account a = new Account();
	private static MultiStaticResourceCalloutMock multimock = new MultiStaticResourceCalloutMock();

	static void setupCustomSettings(){
		
		list<API_Customer_Read_Items__c> readSettingsList = new list<API_Customer_Read_Items__c>();
		
		settings.name = 'API Config LIVE';
    	settings.Api_host__c = 'https://test.apiCustomer.com';
    	settings.Api_key__c = '123456';
    	settings.Customer_Overview__c = '/customerOverview';

    	insert settings;

    	readSettings = new API_Customer_Read_Items__c();
    	readSettings.Name = '05 Item';
    	readSettings.Active__c = true;
    	readSettings.Display_as_Table__c = false;
    	readSettings.Item_Label__c = 'Opt In Status';
		readSettings.Property_Items__c = 'OPTOUTEMAIL,OPTOUTMOBILE,OPTOUTPOSTAL';        
        
        readSettingsList.add(readSettings);
        
    	readSettings = new API_Customer_Read_Items__c();
    	readSettings.Name = '10 CustomerStatus';
    	readSettings.Active__c = true;
    	readSettings.Display_as_Table__c = true;
    	readSettings.Item_Label__c = 'Customer Status';
    	
    	readSettingsList.add(readSettings);
    	
    	readSettings = new API_Customer_Read_Items__c();
    	readSettings.Name = '20 Village';
    	readSettings.Active__c = true;
    	readSettings.Display_as_Table__c = true;
    	readSettings.Item_Label__c = 'Village Summary';
    	
    	readSettingsList.add(readSettings);
    	
    	readSettings = new API_Customer_Read_Items__c();
    	readSettings.Name = '30 Visit';
    	readSettings.Active__c = true;
    	readSettings.Display_as_Table__c = true;
    	readSettings.Item_Label__c = 'Visits';
    	
    	readSettingsList.add(readSettings);
    	
    	readSettings = new API_Customer_Read_Items__c();
    	readSettings.Name = '40 Brand';
    	readSettings.Active__c = true;
    	readSettings.Display_as_Table__c = true;
    	readSettings.Item_Label__c = 'Brands';
    	
    	readSettingsList.add(readSettings);
    	
    	readSettings = new API_Customer_Read_Items__c();
    	readSettings.Name = '50 OfferRedemption';
    	readSettings.Active__c = true;
    	readSettings.Display_as_Table__c = true;
    	readSettings.Item_Label__c = 'Redemptions';
    	
    	readSettingsList.add(readSettings);
    	
    	readSettings = new API_Customer_Read_Items__c();
    	readSettings.Name = '60 EmailEvent';
    	readSettings.Active__c = true;
    	readSettings.Display_as_Table__c = true;
    	readSettings.Item_Label__c = 'Email Events';
    	
    	readSettingsList.add(readSettings);
    	
    	readSettings = new API_Customer_Read_Items__c();
    	readSettings.Name = '70 CustomerPreference';
    	readSettings.Active__c = true;
    	readSettings.Display_as_Table__c = true;
    	readSettings.Item_Label__c = 'Preferences';
    	
    	readSettingsList.add(readSettings);
    	
    	insert readSettingsList;
	}
				

	static void setupData(){
		
   	// Create user
		usr = TestData_User.setupUser('BillyBones', null, 'System Administrator', true, true);
		usr = [select Id, Name, Village__c from User where Id =:usr.Id];

		
		system.runAs(usr){

			usr2 = TestData_User.setupUser('BarryBones', null, 'System Administrator', true, true);
			usr2 = [select Id, Name from User where Id =:usr.Id];

		 	Village__c village = new Village__c();
		 	village.Name = 'TestVillage';
		 	village.Village_Code__c = 'OO';
		 	village.Integration_Language_Name__c = 'English';
		 	village.Integration_Village_Name__c = 'TestVillage';
			village.CertSales_CertPeriod_Cut_Off_Days__c = 1;
			village.CertSales_Report_Sales_Grace_Period_Days__c = 1;
		 	insert village;
		 	
			village = [select name, id, B2B_Chatter_Group_Name__c, Village_Code__c from Village__c where Village_Code__c = 'OO' LIMIT 1];
			
			usr.Village__c = village.Name;
			update usr;

			a = new Account(PersonEmail='Jay@tee.com', Customer_GUID__c = '123456-7890-1234-1234-123456789012', FirstName = 'Jay', LastName = 'tee');
			insert a;
			
			a = [select Id, Customer_GUID__c, PersonMobilePhone from Account where PersonEmail = 'Jay@tee.com'];
								
	    	setupCustomSettings();
		}

	}
	
    static testMethod void unitTest() {
     	setupData();

		multimock.setStatusCode(200);
		multimock.setHeader('Content-Type', 'application/xml');
     	
     	// Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, multimock);
        
    	PageReference pg = new PageReference('/apex/apiCustomerMobile');
    	Test.setCurrentPage(pg);
    	
    	string msg = '';

		system.runAs(usr2){
			
	    	test.startTest();
		    	multimock.setStaticResource(settings.Api_Host__c + settings.Customer_Overview__c + '/123456-7890-1234-1234-123456789012', 'TestAPI_CustomerOverview');		    	
				    	
		    	
		    	Apexpages.StandardController stdController = new Apexpages.StandardController(a);
				apiCustomerViewController controller = new apiCustomerViewController(stdController);
				
				controller.getReadOnlyItems();
				system.debug(controller.readOnlyMap);
				system.assertEquals(controller.readOnlyMap.get('Brands'), '40 Brand');
				
				system.debug(controller.sortedReadOnlyList);
				system.assertEquals(controller.sortedReadOnlyList[0], 'Opt In Status');
				
				msg = apiCustomerViewController.callReadOnlyService(a.Customer_GUID__c);
		        
		        			
			test.stopTest();
			
			system.debug(msg);
			system.assert(msg.indexOf(a.Customer_GUID__c) > -1);


		}    	
        
    }

    static testMethod void unitTestError() {
     	setupData();

		multimock.setStatusCode(400);
		multimock.setHeader('Content-Type', 'application/xml');
     	
     	// Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, multimock);
        
    	PageReference pg = new PageReference('/apex/apiCustomerMobile');
    	Test.setCurrentPage(pg);
    	
    	string msg = '';

		system.runAs(usr2){
			
	    	test.startTest();
		    	multimock.setStaticResource(settings.Api_Host__c + settings.Customer_Overview__c + '/123456-7890-1234-1234-123456789012', 'TestAPI_CustomerOverview');		    	
				    	
		    	
		    	Apexpages.StandardController stdController = new Apexpages.StandardController(a);
				apiCustomerViewController controller = new apiCustomerViewController(stdController);
				
				controller.getReadOnlyItems();
				
				msg = apiCustomerViewController.callReadOnlyService(a.Customer_GUID__c);
		        
		        			
			test.stopTest();
			
			system.debug(msg);
			system.assert(msg.indexOf('ERROR') > -1);


		}    	
        
    }
}