force-app/main/default/objects/Account/fields/Last_action_type__c.field-meta.xml
<CustomField>
    <fullName>Last_action_type__c</fullName>
    <label>Last action type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <description>A Group or Parent Account for Brand Accounts</description>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Tourism.recordType-meta.xml
<RecordType>
    <fullName>Tourism</fullName>
    <active>true</active>
    <description>A Partner of the Business</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Travel_Trade_Meeting__c/Travel_Trade_Meeting__c.object-meta.xml
<CustomObject>
    <description>An Object for Avia reps to enter details of meetings they hold with Tourism Accounts</description>
    <label>Travel Trade Meeting</label>
    <nameField>
        <label>Meeting Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Trade Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Travel_Trade_Meeting__c/fields/Date_of_Meeting__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Meeting__c</fullName>
    <inlineHelpText>Please enter the date the meeting is planned or was held</inlineHelpText>
    <label>Date of Meeting</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Travel_Trade_Meeting__c/fields/Meeting_Location__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Location__c</fullName>
    <inlineHelpText>Where was the meeting held</inlineHelpText>
    <label>Meeting Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Travel_Trade_Meeting__c/fields/Meeting_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Minutes__c</fullName>
    <inlineHelpText>Enter all your meeting notes here</inlineHelpText>
    <label>Meeting Minutes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Travel_Trade_Meeting__c/fields/Share__c.field-meta.xml
<CustomField>
    <fullName>Share__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this checkbox is ticked it will be posted to a chatter group using a Trigger.

Default = Unchecked :: Manual Sharing
Default = Checked :: Automatic Sharing

This field will not be visible on the page layout, instead it will be driven by a custom action (or button?)</description>
    <label>Share</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Travel_Trade_Meeting__c/fields/Tourism_Account__c.field-meta.xml
<CustomField>
    <fullName>Tourism_Account__c</fullName>
    <inlineHelpText>lookup the Name of the Tourism Account for which the meeting was held</inlineHelpText>
    <label>Tourism Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <infoMessage>Search for the Tourism account associated with this meeting</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Travel Trade Meetings</relationshipLabel>
    <relationshipName>Travel_Trade_Meetings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Travel_Trade_Meeting__c/fields/Tourism_Contact__c.field-meta.xml
<CustomField>
    <fullName>Tourism_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup the name of the main Contact with which the meeting was held</inlineHelpText>
    <label>Tourism Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Tourism_Account__c</valueField>
        </filterItems>
        <infoMessage>Search for the Contact under the Tourism account you selected</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Travel Trade Meetings</relationshipLabel>
    <relationshipName>Travel_Trade_Meetings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Travel_Trade_Meeting__c/fields/VR_Representative__c.field-meta.xml
<CustomField>
    <fullName>VR_Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the name of the person that represented Value Retail</inlineHelpText>
    <label>VR Representative</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Travel_Trade_Meetings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TravelTradeMeetingHelper_TestClass.cls
@isTest(SeeAllData=true)
private class TravelTradeMeetingHelper_TestClass{
   
   static testMethod void createAndShareMeeting(){
    
    // Perform our data preparation.
	Account TourismAccount;
	Contact TourismContact;
	
    User u1 = TestData_User.setupAdminUser(false);
    u1.Username = 'vr_u1@test.com';
    u1.Email = 'vr_u1@test.com';
    insert u1;
	
	system.runAs(u1){
	    //Account
	    TourismAccount = TestData_Account.setupTourismAccount(1, true);    
	
	    //Contact
	    TourismContact = TestData_Contact.setupContact('1', TourismAccount, true);
	}
	  
    //User
    User adminUser = TestData_User.setupAdminUser(true);
           
   //Create a Chatter Group
   //List<CollaborationGroup> TTMgrps = [SELECT id, name FROM CollaborationGroup WHERE name = 'Travel Trade Meetings'];

    //the group does not exist, so create and add the admin as a user
    CollaborationGroup grp= new CollaborationGroup();
    grp.Name = 'Test Chatter Group'; 
    grp.CollaborationType = 'Public';                   
    insert grp;
    //Chatter Group Member
    CollaborationGroupMember grpMr = new CollaborationGroupMember();
    grpMr.memberid = adminUser.Id;
    grpMr.CollaborationGroupId = Grp.Id;
    insert grpMr; 
  

    
    //Travel Trade Meeting with immediate sharing
    Travel_Trade_Meeting__c TestTTMImmediate = new Travel_Trade_Meeting__c(Date_of_Meeting__c = system.today(), Meeting_Location__c = 'Test Location'
    ,Meeting_Minutes__c = 'Test Meeting Minutes', Tourism_Account__c = TourismAccount.id, Tourism_Contact__c = TourismContact.id, 
    VR_Representative__c = adminUser.id, share__c = true);

    //Travel Trade Meeting with Manual sharing
    Travel_Trade_Meeting__c TestTTMManual = new Travel_Trade_Meeting__c(Date_of_Meeting__c = system.today(), Meeting_Location__c = 'Test Location'
    ,Meeting_Minutes__c = 'Test Meeting Minutes', Tourism_Account__c = TourismAccount.id, Tourism_Contact__c = TourismContact.id, 
    VR_Representative__c = adminUser.id, share__c = false);
  
    // reset the limits
    test.startTest();
       
    //insert TTM with that should immediatly be shared   
    insert TestTTMImmediate;
    
     //Insert THEN update (to reflect the manual process) TTM with Share__c = true
    insert TestTTMManual;
    TestTTMManual.Share__c = true;
    update TestTTMManual;
     
    // Stop the test, this changes limit context back to test from trigger.
    test.stopTest();
    
    //Fetch and verify the results
    
    //Ensure there are two feeditems in the chatter feed
    integer countimmediateposts = [SELECT COUNT() FROM FeedItem WHERE ParentID = :TestTTMImmediate.Id];
    system.debug('countimmediateposts = ' + countimmediateposts);
    system.assertEquals(countimmediateposts, 1);  
    
    integer countManualposts = [SELECT COUNT() FROM FeedItem WHERE ParentID = :TestTTMManual.Id];
    system.debug('countManualposts = ' + countManualposts);
    system.assertEquals(countManualposts, 1);  
       
}
    static testMethod void updateRelatedAccountTest(){
        // Test Data
        List<Travel_Trade_Meeting__c> travelTradeMeetingList = new List <Travel_Trade_Meeting__c>();
        
		Id TourismRecordType = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Tourism').getRecordTypeId();
        Account acct = new Account(Name = 'TestAccountTest', RecordTypeId = TourismRecordType);
        
        INSERT acct;
        
		Contact con = new Contact(FirstName = 'Cristiano', LastName = 'Ronaldo', AccountId = acct.Id, email = 'CRonaldo@123emailtest123.com');
        
        INSERT con;
        
        Travel_Trade_Meeting__c travelTradeMeeting = new Travel_Trade_Meeting__c(Date_of_Meeting__c = system.today(), Meeting_Location__c = 'Test Location', 
                                                                                 Meeting_Minutes__c = 'Test Meeting Minutes', Tourism_Account__c = acct.Id, 
				                                                                 Tourism_Contact__c = con.Id);
		INSERT travelTradeMeeting;
        
        travelTradeMeetingList.add(travelTradeMeeting);
		       
        String lastActionBegin = [SELECT Last_action_type__c FROM Account WHERE Id = :acct.Id].Last_action_type__c;
        
        //Test
        
		test.startTest();
			TravelTradeMeetingTriggerHelper.updateRelatedAccount(travelTradeMeetingList);  
		test.stopTest();
        
        String lastActionEnd = [SELECT Last_action_type__c FROM Account WHERE Id = :acct.Id].Last_action_type__c;

        System.assertNotEquals(lastActionBegin, lastActionEnd, 'Wrong result');
        System.assertEquals('Travel Trade Meeting', lastActionEnd, 'Wrong result');
    } 
   
}