force-app/main/default/objects/Account/fields/Last_action_type__c.field-meta.xml
<CustomField>
    <fullName>Last_action_type__c</fullName>
    <label>Last action type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Retail_Live_Email__c/Retail_Live_Email__c.object-meta.xml
<CustomObject>
    <label>Retail LIVE</label>
    <nameField>
        <label>Retail LIVE Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail LIVE</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Live_Email__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Live_Email__c/fields/Reply_Count__c.field-meta.xml
<CustomField>
    <fullName>Reply_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>incremented by 1 when an EMAIL reply comes in. Will not count internal posts</description>
    <label>Reply Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Live_Email__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Retail_Live_Email__c/fields/Subject_Unique__c.field-meta.xml
<CustomField>
    <fullName>Subject_Unique__c</fullName>
    <label>Subject Unique</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Live_Email__c/fields/ToAddress__c.field-meta.xml
<CustomField>
    <fullName>ToAddress__c</fullName>
    <label>ToAddress</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Retail_Live_Email__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TaskTriggerHelperTest.cls
@isTest
private class TaskTriggerHelperTest {
	
	static Account account1;
	static Account account2;
	static Contact contact;
	static Retail_Live_Email__c retailLive;
	static Retail_Live_Email__c retailLive2;
	static Village__c testVillage;
	
	
	private static void setupData(){
	 	User u1 = TestData_User.setupAdminUser(false);
	    u1.Username = 'vr_u1@test.com';
	    u1.Email = 'vr_u1@test.com';
	    insert u1;
		system.runAs(u1){		
		 		testVillage = new Village__c();
		 		testVillage.Name = 'Test Test';
		 		testVillage.Village_Code__c = 'TT';
				testVillage.CertSales_CertPeriod_Cut_Off_Days__c = 1;
				testVillage.CertSales_Report_Sales_Grace_Period_Days__c = 1; 
		 		insert testVillage;
		
				id B2BAccountRecordTypeID = Schema.SObjectType.Account.RecordTypeInfosByName.get('Brand').RecordTypeId;
				account1 = new Account(Name='RLTestBrand', RecordTypeId = B2BAccountRecordTypeID);
				insert account1;
				account1 = [select Id, Name from Account where Id = :account1.Id];
				
				account2 = new Account(Name='Test BrandRL', RecordTypeId = B2BAccountRecordTypeID);
				insert account2;
				
				contact = new Contact(email='test1@sf.com', FirstName = 'Albert', LastName='Table', 
													AccountId = account1.id);
				insert contact;
				
				retailLive = new Retail_Live_Email__c(Subject__c = 'Unit Test Retail Live',
												Subject_Unique__c = 'Unit Test Retail Live',
												ToAddress__c = contact.email, 
												village__c = testVillage.Id,
												brand__c = account1.Id);
				insert retailLive;
				retailLive = [select Id, brand__c, subject__c, Subject_Unique__c, reply_count__c 
										from Retail_Live_Email__c where id = :retailLive.Id];

				retailLive2 = new Retail_Live_Email__c(Subject__c = 'Unit Test Retail Live2',
												Subject_Unique__c = 'Unit Test Retail Live2',
												ToAddress__c = contact.email, 
												village__c = testVillage.Id,
												brand__c = account1.Id);
				insert retailLive2;
				retailLive2 = [select Id, brand__c, subject__c, Subject_Unique__c, reply_count__c 
										from Retail_Live_Email__c where id = :retailLive.Id];				
		    }
	}

    static testMethod void unitTest() {
		
		setupData();

		// create task for brand (mimicing outlook task association)
		Task t1 = new Task(WhatId = account1.Id, Subject = retailLive.Subject__c, 
																ActivityDate = system.today());

		// create task for brand with different subject														
		Task t3 = new Task(WhatId = account1.Id, Subject = 'Unit Test Brand Subject', 
													ActivityDate = system.today());
		
		list<Task> taskList = new list<Task>();
		taskList.add(t1);													
		taskList.add(t3);
		
		test.startTest();
			insert taskList;
		test.stopTest();
		
		t1 = [select Id, RecordTypeId, WhoId, WhatId, Subject,  
                            	Retail_Live__c, Retail_Live_From__c,Retail_Live_Reply__c                                                         
                                from Task 
                                where id = :t1.Id ]; 
                                
                                
        // check task has reassigned to retail live record
        system.assertEquals(t1.whatId, retailLive.Id);         
 
 		t3 = [select Id, RecordTypeId, WhoId, WhatId, Subject,  
                            	Retail_Live__c, Retail_Live_From__c,Retail_Live_Reply__c                                                         
                                from Task 
                                where id = :t3.Id ]; 
                                
        // check task still assigned to brand
        system.assertEquals(t3.whatId, account1.Id);                                     
    }

	static testMethod void unitTest2() {
		
		setupData();
		
		// create task for retail live record directly														
		Task t2 = new Task(WhatId = retailLive2.Id, Subject = retailLive2.Subject__c + ' From Retail Live', 
													ActivityDate = system.today());

		// create task for brand with different subject														
		Task t3 = new Task(WhatId = account1.Id, Subject = 'Unit Test Brand Subject', 
													ActivityDate = system.today());
		
		list<Task> taskList = new list<Task>();													
		taskList.add(t2);
		taskList.add(t3);
		
		test.startTest();
			insert taskList;
		test.stopTest();
		

		t2 = [select Id, RecordTypeId, WhoId, WhatId, Subject,  
                            	Retail_Live__c, Retail_Live_From__c,Retail_Live_Reply__c                                                         
                                from Task 
                                where id = :t2.Id ]; 
                                
        // check task still assigned to retail live record
        system.assertEquals(t2.whatId, retailLive2.Id);         
 
 		t3 = [select Id, RecordTypeId, WhoId, WhatId, Subject,  
                            	Retail_Live__c, Retail_Live_From__c,Retail_Live_Reply__c                                                         
                                from Task 
                                where id = :t3.Id ]; 
                                
        // check task still assigned to brand
        system.assertEquals(t3.whatId, account1.Id);                                     
    }
	
    static testMethod void updateRelatedAccountTest(){
        setupData();
    
    	String lastActionBegin = [SELECT Last_action_type__c FROM Account WHERE Id = :account1.Id].Last_action_type__c;
        
        List<Task> taskList = new List<Task>();       
        Task t1 = new Task(WhatId = account1.Id, Subject = retailLive.Subject__c, 
													ActivityDate = system.today());
        INSERT t1;
        taskList.add(t1);
        
		test.startTest();
            TaskTriggerHelper.updateRelatedAccount(taskList);
        test.stopTest();
        
        String lastActionEnd = [SELECT Last_action_type__c FROM Account WHERE Id = :account1.Id].Last_action_type__c;
        
        System.assertNotEquals(lastActionBegin, lastActionEnd, 'Wrong result');
        System.assertEquals('Task', lastActionEnd, 'Wrong result');
    }

}