force-app/main/default/objects/Account/fields/Last_action_type__c.field-meta.xml
<CustomField>
    <fullName>Last_action_type__c</fullName>
    <label>Last action type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Primary_Relationship_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Relationship_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box if the Contact is the one that should recieve account emails</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/contactTriggerHelperTest.cls
@IsTest
Public Class contactTriggerHelperTest{

	@testSetup
	public static void setupData(){

		id accId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Brand').RecordTypeId;
		Account act = new account(Name = 'test Acc 1', Recordtypeid = accId);
		insert act;

		Contact con1 = new contact(AccountId = act.id, FirstName = 'Test1', LastName = 'Test1', email = 'test1@test.com',Primary_Relationship_Contact__c = true);
		Contact con2 = new contact(AccountId = act.id, FirstName = 'Test2', LastName = 'Test2', email = 'test2@test.com');

		list<Contact> obs = new list<Contact>();
		obs.add(con1);
		obs.add(con2);

		try{
		insert obs;
		}
		catch (exception e){
			system.debug('exception ' + e);
		}
	}

	@IsTest
	public static void testOne(){

		Contact con = [SELECT id,Primary_Relationship_Contact__c FROM Contact WHERE email = 'test2@test.com' ];
		con.Primary_Relationship_Contact__c = true;
		test.startTest();
		try{
			update con;
		}
		catch (exception e){
			system.debug('exception ' + e);
			System.Assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
		}
		
		test.stopTest();

	}

	@isTest
    public Static void updateRelatedAccountTest(){
        List<Contact> contactsList = [SELECT id, AccountId, email, RecordtypeId FROM Contact WHERE email = 'test1@test.com' OR email = 'test2@test.com'];
        
        Test.startTest();
        	contactTriggerHelper.updateRelatedAccount(contactsList);
        	contactTriggerHelper.checkDuplicate(contactsList);
        	contactTriggerHelper.populateUniqueKey(contactsList);
        Test.stopTest();
        
        Account acc = [SELECT Id, Last_action_type__c FROM Account WHERE Id = :contactsList[0].AccountId];
        System.assertNotEquals(null, acc.Last_action_type__c, 'Result not as expected.');
    } 
}