force-app/main/default/objects/Account/fields/Logo_Id__c.field-meta.xml
<CustomField>
    <fullName>Logo_Id__c</fullName>
    <label>Logo URL</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter name of Marketing Promotion that resulted in this VIP Account being created.</inlineHelpText>
    <label>Marketing Activity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Marketing_Activity__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partnership Promotion</value>
        </filterItems>
        <filterItems>
            <field>Marketing_Activity__c.Is_Live__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Marketing_Activity__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/API_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>API keys and parameters required for Microservice calls</description>
    <label>API Configuration</label>
</CustomObject>

force-app/main/default/objects/API_Configuration__c/fields/API_Host__c.field-meta.xml
<CustomField>
    <fullName>API_Host__c</fullName>
    <description>The base URL for all API calls</description>
    <inlineHelpText>The base URL for all API calls</inlineHelpText>
    <label>API Host</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>The API Key</description>
    <inlineHelpText>The API Key</inlineHelpText>
    <label>API Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Customer_Create__c.field-meta.xml
<CustomField>
    <fullName>Customer_Create__c</fullName>
    <description>The URL suffix for the User Create service</description>
    <inlineHelpText>The URL suffix for the User Create service</inlineHelpText>
    <label>Customer Create</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Customer_Read_GUID__c.field-meta.xml
<CustomField>
    <fullName>Customer_Read_GUID__c</fullName>
    <description>The URL suffix for the Customer Read using GUID service</description>
    <inlineHelpText>The URL suffix for the Customer Read using GUID service</inlineHelpText>
    <label>Customer Read GUID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Debug_Mode__c.field-meta.xml
<CustomField>
    <fullName>Debug_Mode__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate whether api calls should be logged.</description>
    <inlineHelpText>Flag to indicate whether api calls should be logged.</inlineHelpText>
    <label>Debug Mode</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Email_Change__c.field-meta.xml
<CustomField>
    <fullName>Email_Change__c</fullName>
    <description>End point suffix for Email Change service</description>
    <inlineHelpText>End point suffix for Email Change service</inlineHelpText>
    <label>Email Change</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Enum_Read__c.field-meta.xml
<CustomField>
    <fullName>Enum_Read__c</fullName>
    <description>The URL suffix for the Enumerator Read service</description>
    <inlineHelpText>The URL suffix for the Enumerator Read service</inlineHelpText>
    <label>Enum Read</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Lookup_Read__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Read__c</fullName>
    <description>The URL suffix for the Customer API Lookup Read services (genders, villages ..etc)</description>
    <inlineHelpText>The URL suffix for the Customer API Lookup Read services (genders, villages ..etc)</inlineHelpText>
    <label>Lookup Read</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Preference_Create__c.field-meta.xml
<CustomField>
    <fullName>Preference_Create__c</fullName>
    <label>Preference Create</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Preference_Read__c.field-meta.xml
<CustomField>
    <fullName>Preference_Read__c</fullName>
    <label>Preference Read</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Group_Booking__c.field-meta.xml
<CustomField>
    <fullName>Group_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group Booking</label>
    <referenceTo>Group_Booking__c</referenceTo>
    <relationshipLabel>Redemption Campaign</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>only valid for redeemable campaigns</description>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/Group_Booking__c.object-meta.xml
<CustomObject>
    <description>Tourism (B2T) Object :: Used for recording MICE group bookings</description>
    <label>Booking/Partnership</label>
    <nameField>
        <displayFormat>GBI{0000000000}</displayFormat>
        <label>Group Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings/Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Booking__c/fields/Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Activity</label>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipName>Group_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipName>Bookings_Partnerships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/recordTypes/Group_Booking.recordType-meta.xml
<RecordType>
    <fullName>Group_Booking</fullName>
    <active>true</active>
    <description>A booking for a fixed date/time that a group of guests are scheduled to arrive</description>
    <label>Group Booking</label>
</RecordType>

force-app/main/default/objects/Group_Booking__c/recordTypes/Groups_Partnership.recordType-meta.xml
<RecordType>
    <fullName>Groups_Partnership</fullName>
    <active>true</active>
    <description>An agreement with a partner who bring many groups of guests to a village, without the need to pre-book before each arrival</description>
    <label>Groups Partnership</label>
</RecordType>

force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter a End date where you expect the activity to stop impacting footfall/Sales in the Village.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <description>....</description>
    <label>Marketing Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You cannot link an activity to a &apos;Cancelled&apos;  Campaign.</errorMessage>
        <filterItems>
            <field>Marketing_Campaign__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Activities</relationshipLabel>
    <relationshipName>Marketing_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter a date where you expect the activity to impact footfall/Sales in the Village. This is not necessarily the date the email is being sent</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/recordTypes/Partnership_Promotion.recordType-meta.xml
<RecordType>
    <fullName>Partnership_Promotion</fullName>
    <active>true</active>
    <description>QR Code...</description>
    <label>Partnership Promotion</label>
</RecordType>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter the Start Date of the Campaign</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>...</description>
    <inlineHelpText>Select the Village is this campaign related to</inlineHelpText>
    <label>Village</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>notEqual</operation>
            <value>Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Village Campaign</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/recordTypes/Village_Campaign.recordType-meta.xml
<RecordType>
    <fullName>Village_Campaign</fullName>
    <active>true</active>
    <description>A Marketing Brief for a Village&apos;s Campaign..</description>
    <label>Village Campaign</label>
</RecordType>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/B2B_Chatter_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>B2B_Chatter_Group_Name__c</fullName>
    <description>Defines the chatter group to post to when an event is created which mentions the village.</description>
    <inlineHelpText>Defines the chatter group to post to when an event is created which mentions the village.</inlineHelpText>
    <label>B2B Chatter Group Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/VIPCardSchedule_Test.cls
@IsTest
public class VIPCardSchedule_Test {
    
//   private static final id promoRecordTypeId = Schema.SObjectType.Marketing_Activity__c.RecordTypeInfosByName.get('Partnership Promotion').RecordTypeId;
    private static final id promoRecordTypeId = Schema.SObjectType.Marketing_Activity__c.RecordTypeInfosByDeveloperName.get('Partnership_Promotion').RecordTypeId;
    private static final id grpsPartnershipRecordTypeId = Schema.SObjectType.Group_Booking__c.RecordTypeInfosByDeveloperName.get('Groups_Partnership').RecordTypeId;
    private static final id grpBookingRecordTypeId = Schema.SObjectType.Group_Booking__c.RecordTypeInfosByDeveloperName.get('Group_Booking').RecordTypeId;
    private static final id guestRecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByDeveloperName.get('Guest').RecordTypeId;
    private static final id VILLAGE_RECTYPE = Schema.SObjectType.Marketing_Campaign__c.RecordTypeInfosByDeveloperName.get('Village_Campaign').RecordTypeId;
    
    
    private static Account account = new Account();
    private static Account account2 = new Account();
    private static Village__c village = new Village__c();
    private static User usr = new User();
    private static User usr2 = new User();
    private static Marketing_Activity__c partnerPromo = null;
    private static Marketing_Campaign__c marketingCampaign = null;
    private static Group_Booking__c regularBooking = null;
    private static Group_Booking__c oneOffBooking = null;    
    private static Group_Booking__c individualsPartnership = null;
    
    private static API_Configuration__c settings = new API_Configuration__c();
    private static MultiStaticResourceCalloutMock multimock = new MultiStaticResourceCalloutMock();
    
    static void setupCustomSettings(){

    settings.name = 'API Config LIVE';
      settings.Api_host__c = 'https://test.apiCustomer.com';
      settings.Api_key__c = '123456';
      settings.Customer_create__c = '/createCustomer';
      settings.Customer_read_GUID__c = '/readCustomer';
      settings.Debug_mode__c = true;
      settings.Enum_read__c = '/enumRead';
      settings.Lookup_read__c = '/lookupRead';
      settings.Preference_create__c = '/prefCreate';
      settings.Preference_read__c = '/prefRead';
      settings.Email_Change__c = '/emailChange';

      insert settings;        
  }
  
  static void setupMessages(){
    
    multimock.setStaticResource(settings.Api_Host__c + settings.Lookup_Read__c + '/Villages', 'TestAPI_Villages');
    multimock.setStaticResource(settings.Api_Host__c + settings.Lookup_Read__c + '/Languages', 'TestAPI_Languages');
    multimock.setStaticResource(settings.Api_Host__c + settings.Lookup_Read__c + '/Genders', 'TestAPI_Genders');
    multimock.setStaticResource(settings.Api_Host__c + settings.Lookup_Read__c + '/Countries', 'TestAPI_Countries');
    multimock.setStaticResource(settings.Api_Host__c + settings.Customer_create__c, 'TestAPI_GoodGuest');
    
  }
    
    static void setupData(){
       // Create user
    usr = TestData_User.setupUser('BillyBones', null, 'System Administrator', true, true);
          
    system.runAs(usr){

      usr2 = TestData_User.setupUser('BarryBones', null, 'System Administrator', true, true);
      usr2 = [select Id, Name from User where Id =:usr.Id];
      
      account = TestData_Account.setupTourismAccount(1, true);
      account.logo_Id__c = 'http://www.google.com';
      Contact con = TestData_Contact.setupTourismContact('A',account,true); 

      update account;
      account2 = TestData_Account.setupTourismAccount(2, true);
      
      Document d = new Document(); 
      d.Name = 'Default'; 
      string myContent = 'text file text contents';      
      blob body = EncodingUtil.base64Decode(EncodingUtil.base64Encode(blob.valueOf(myContent)));  
      d.Body =  body;
      d.ContentType = 'text/plain';
      d.Type = 'txt';
      d.FolderId = UserInfo.getUserId();
      insert d;
              
       village = new Village__c();
       village.Name = 'TestVillage';
       village.Village_Code__c = 'OO';     
       village.CertSales_CertPeriod_Cut_Off_Days__c = 1;
       village.CertSales_Report_Sales_Grace_Period_Days__c = 1; 
       insert village;
       village = [select name, id, B2B_Chatter_Group_Name__c, Village_Code__c from Village__c where Village_Code__c = 'OO' LIMIT 1];      
          
          marketingCampaign = new Marketing_Campaign__c();
          marketingCampaign.Start_Date__c = system.today();
          marketingCampaign.End_Date__c = system.today().addDays(30);
          marketingCampaign.Name = 'Test Campaign';
          marketingCampaign.RecordTypeId = VILLAGE_RECTYPE;
          marketingCampaign.Village__c = village.Id;
          marketingCampaign.Campaign_Level__c = 'Theme';
          insert marketingCampaign;

          partnerPromo = new Marketing_Activity__c();
          partnerPromo.Start_Date__c = system.today();
          partnerPromo.End_Date__c = system.today().addDays(10);
          partnerPromo.Name = 'Test Village promo';
          partnerPromo.Marketing_Campaign__c = marketingCampaign.Id;
          partnerPromo.Partner__c = account.Id;
         
          partnerPromo.recordTypeId = promoRecordTypeId;
          insert partnerPromo; 
          
          regularBooking = new Group_Booking__c();
          regularBooking.Name_of_Event__c= 'Test regular booking';
          regularBooking.recordTypeId = grpsPartnershipRecordTypeId;
          regularBooking.Status__c = 'Confirmed';
          regularBooking.Village__c = village.Id;
          regularBooking.Valid_from__c = system.today();
          regularBooking.Valid_to__c = system.today().addDays(50);
          regularBooking.visitors_country_of_origin__c = 'China';
          regularBooking.expected_mode_of_transport__c = 'Train';
          regularBooking.group_type__c  ='Leisure';
          regularBooking.Organisation__c = account.Id;
          insert regularBooking;  

          oneOffBooking = new Group_Booking__c();
          oneOffBooking.Name_of_Event__c= 'Test one off booking';
          oneOffBooking.recordTypeId = grpBookingRecordTypeId;
          oneOffBooking.Status__c = 'Confirmed';
          oneOffBooking.Village__c = village.Id;
          oneOffBooking.Expected_Arrival__c = system.today();
          oneOffBooking.Expected_Departure__c = system.now();
          oneOffBooking.visitors_country_of_origin__c = 'China';
          oneOffBooking.expected_mode_of_transport__c = 'Train';
          oneOffBooking.group_type__c  ='Leisure';
          oneOffBooking.Organisation__c = account.Id;
          insert oneOffBooking;


      setupCustomSettings();
    }

    setupMessages();
    
    usr = [select Id, Name, Village__c from User where Id =:usr.Id];
    usr.Village__c = village.Name;
    update usr;
    }
    
    static testMethod void execute_test(){
        setupData();
        multimock.setStatusCode(200);
        multimock.setHeader('Content-Type', 'application/xml');
        
        // Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, multimock);     
        multimock.setStaticResource(settings.Api_Host__c + settings.Customer_read_GUID__c + '/123456-7890-1234-1234-123456789012' , 'TestAPI_GoodGuest');
        multimock.setStaticResource(settings.Api_Host__c + settings.Preference_read__c +  '/123456-7890-1234-1234-123456789012' , 'TestAPI_Preferences');
        multimock.setStaticResource(settings.Api_Host__c + settings.Preference_create__c + '/123456-7890-1234-1234-123456789012|contactmodes|email', 'TestAPI_Preferences');
        multimock.setStaticResource(settings.Api_Host__c + settings.Preference_create__c + '/123456-7890-1234-1234-123456789012|contactmodes|mobile', 'TestAPI_Preferences');
        multimock.setStaticResource(settings.Api_Host__c + settings.Preference_create__c , 'TestAPI_Preferences');
        system.runAs(usr){
          
            string guestId = VisitRedemptionsHelper.quickCreateGuest('jay@tee.com', '04444444444', 'Jay', 'Tee', 'United Kingdom', partnerPromo.Id, '0', '0', '0');
         
          string s1 = visitRedemptionsHelper.saveVisit('12345678901234',(String) partnerPromo.Id, guestId, 
                                        'TIC', 'Train', 'Leisure', 'Spain', 
                                        '', 'some notes','REG123' ,'01/01/2016 12:00','01/01/2016 14:00' , '1','1');
        }
        
        
        Test.startTest();
        
        VIPCardSchedule schClass = new VIPCardSchedule();
        String sch = '0 0 8 13 2 ?';
        System.schedule('One Time Pro', sch, schClass);
        
        Test.stopTest();
        
        
    }
}