force-app/main/default/objects/Account/fields/Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter name of Marketing Promotion that resulted in this VIP Account being created.</inlineHelpText>
    <label>Marketing Activity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Marketing_Activity__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partnership Promotion</value>
        </filterItems>
        <filterItems>
            <field>Marketing_Activity__c.Is_Live__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Marketing_Activity__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Tourism.recordType-meta.xml
<RecordType>
    <fullName>Tourism</fullName>
    <active>true</active>
    <description>A Partner of the Business</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Activity_Budget_Split__c/Activity_Budget_Split__c.object-meta.xml
<CustomObject>
    <label>Activity Budget Split</label>
    <nameField>
        <displayFormat>ABS-{0000000}</displayFormat>
        <label>Activity Budget Split Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Budget Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Budget_Split__c/fields/Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity__c</fullName>
    <label>Marketing Activity</label>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipLabel>Activity Budget Splits</relationshipLabel>
    <relationshipName>Activity_Budget_Splits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Associated_Account__c/Associated_Account__c.object-meta.xml
<CustomObject>
    <label>Associated Account</label>
    <nameField>
        <displayFormat>AA-{0000000}</displayFormat>
        <label>Associated Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Associated_Account__c/fields/Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity__c</fullName>
    <label>Marketing Activity</label>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipLabel>Associated Accounts (Brands/Partners)</relationshipLabel>
    <relationshipName>Associated_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Campaign/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>only valid for redeemable campaigns</description>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Tourism.recordType-meta.xml
<RecordType>
    <fullName>Tourism</fullName>
    <active>true</active>
    <description>All Tourism Responsys campaigns</description>
    <label>Tourism</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <inlineHelpText>Add a Village Presence Contact Role to add Villages to this field</inlineHelpText>
    <label>Village Presence</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field exists purely to provide a relationship between &quot;In_Village_Brand_Activity__c&quot; - Account - &quot;Marketing_Activity__c&quot;, this allows the related marketing Activty to be shown on the Account layout in a related list.
It is populated by a process builder workflow - &quot;In Village Brand Activity Set Brand__c&quot;, a process invoked by insert or update of an &quot;In_Village_Brand_Activity__c&quot; record.</description>
    <label>Brand</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing Activities (Brand)</relationshipLabel>
    <relationshipName>Marketing_Activities_Brand</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <description>....</description>
    <label>Marketing Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You cannot link an activity to a &apos;Cancelled&apos;  Campaign.</errorMessage>
        <filterItems>
            <field>Marketing_Campaign__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Activities</relationshipLabel>
    <relationshipName>Marketing_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/recordTypes/General_Activity.recordType-meta.xml
<RecordType>
    <fullName>General_Activity</fullName>
    <active>true</active>
    <description>No QR Code...</description>
    <label>General Activity</label>
</RecordType>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/Marketing_Campaign_Ref__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign_Ref__c</fullName>
    <displayFormat>MC-{00000}</displayFormat>
    <externalId>true</externalId>
    <label>Marketing Campaign Ref</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <inlineHelpText>Enter a short description about the Campaign</inlineHelpText>
    <label>Short Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>...</description>
    <inlineHelpText>Select the Village is this campaign related to</inlineHelpText>
    <label>Village</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>notEqual</operation>
            <value>Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Village Campaign</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Organisation__c</fullName>
    <description>The business unit within oracle</description>
    <inlineHelpText>The business unit within oracle</inlineHelpText>
    <label>Oracle Organisation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Oracle_Source_Template_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Source_Template_Number__c</fullName>
    <description>The value used to map to an oracle template when sent to Oracle Fusion</description>
    <inlineHelpText>The value used to map to an oracle template when sent to Oracle Fusion</inlineHelpText>
    <label>Oracle Source Template Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Village Presence records must be linked to Brand accounts. Please ensure you are not linking the Deal/Village Presence to a Group</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/ActivityBudgetSplitTriggerTest.cls
@isTest
Public Class ActivityBudgetSplitTriggerTest{   

private static Account account = new Account();
    private static Account account2 = new Account();
    public static Marketing_Campaign__c MC = new Marketing_Campaign__c();
    public static Marketing_Activity__c MA = new Marketing_Activity__c();
    public static Associated_Account__c AA = new Associated_Account__c();

    @testSetup 
    static void setUpData(){
    
     Profile profileSysAdmin = [SELECT ID, Name FROM Profile WHERE Name = 'System Administrator'];

        UserRole adminRole = new UserRole();
        adminRole.DeveloperName = 'CustomRole';
        adminRole.Name = 'Custom Role';
        insert adminRole;

        User admin = new User();
        admin.LastName = 'AdministratorForTestingHere';
        admin.Alias = 'admin';
        admin.Email = 'adminFortests@valueretai.com';
        admin.Username = 'adminFortests@valueretai.com';
        admin.CommunityNickname = 'admin';
        admin.UserRoleId = adminRole.Id;
        admin.ProfileId = profileSysAdmin.Id;
        admin.Village__c = 'Bicester';
        admin.TimeZoneSidKey = 'GMT';
        admin.LocaleSidKey = 'en_GB';
        admin.EmailEncodingKey = 'ISO-8859-1';
        admin.LanguageLocaleKey = 'en_US';
        insert admin;
    
        system.runAs(admin){
        
        RecordType brandRecordType = [SELECT Id, Name FROM RecordType WHERE Name = 'Brand'];
            
            Account brand = new Account();
            brand.RecordTypeId = brandRecordType.Id;
            brand.Name = 'Brand 1';
            insert brand;
        
            RecordType brandContactRecordType = [SELECT Id, Name FROM RecordType WHERE Name = 'Brand Contact'];
        
            Contact communityContact = new Contact();
            communityContact.RecordTypeId = brandContactRecordType.Id;
            communityContact.LastName = 'John';
            communityContact.AccountId = brand.Id;
            communityContact.Village_Presence__c = 'Bicester';
            communityContact.Email = 'testcommunity.contact@brand.com';
            insert communityContact;
            
            Profile profileCommunity = [SELECT ID, Name FROM Profile WHERE Name = 'Third Party Community User'];
                
            User communityUser = new User();
            communityUser.LastName = communityContact.LastName;
            communityUser.Alias = 'jhn';
            communityUser.Email = communityContact.Email;
            communityUser.Username = 'john@valueretai.com';
            communityUser.CommunityNickname = 'johnvr';
            communityUser.ProfileId = profileCommunity.Id;
            communityUser.Village__c = 'Bicester';
            communityUser.TimeZoneSidKey = 'GMT';
            communityUser.LocaleSidKey = 'en_GB';
            communityUser.EmailEncodingKey = 'ISO-8859-1';
            communityUser.LanguageLocaleKey = 'en_US';
            communityUser.ContactId = communityContact.Id;
            communityUser.PortalRole = 'Manager';
            insert communityUser;
            
        // first create a village
        Village__c vill = TestDataGenerator.setupVillage(false);
        vill.Oracle_Source_Template_Number__c = '123456';
        vill.Oracle_Organisation__c = 'SourceOrg';
		vill.CertSales_CertPeriod_Cut_Off_Days__c = 1;
        vill.CertSales_Report_Sales_Grace_Period_Days__c = 1;
        insert vill;

        account = TestData_Account.setupBrandAccount(1, true);
        account2 = TestData_Account.setupBrandAccount(2, true);
        Account testAccount = new Account(name = 'Test Account' , RecordTypeId =  Schema.SObjectType.Account.RecordTypeInfosByDeveloperName.get('Tourism').RecordTypeId);
        Database.DMLOptions dmlOptions = new Database.DMLOptions();
        dmlOptions.DuplicateRuleHeader.AllowSave = true;
        Database.insert(testAccount, dmlOptions);
          
        Village_Presence__c VP = new Village_Presence__c();
        VP.Name = 'test';
        VP.Brand__c = account2.id;
        VP.Village__c = vill.id;
        insert VP;

        Map <String,Schema.RecordTypeInfo> recordTypesadjustment = Marketing_Campaign__c.sObjectType.getDescribe().getRecordTypeInfosByName();
        Id RecTypeIdinadj = recordTypesadjustment.get('Village Campaign').getRecordTypeId();

        MC.Name = 'TestCampaignForTestingSync';
        //MC.Marketing_Campaign_Ref__c = 'MCREF001';
        MC.Short_Description__c = 'TestCampaign Description';
        MC.Start_Date__c = Date.newInstance(2020, 12, 12);
        MC.End_Date__c = Date.newInstance(2021, 12, 12);
        MC.Campaign_Level__c = 'Theme';
        MC.Village__c = vill.Id;
        MC.RecordTypeId = RecTypeIdinadj;
        insert MC;

        // and now insert an activity

    //    id theRecId =  Schema.SObjectType.Marketing_Activity__c.RecordTypeInfosByName.get('General Activity').RecordTypeId;
		id theRecId =  Schema.SObjectType.Marketing_Activity__c.RecordTypeInfosByDeveloperName.get('General_Activity').RecordTypeId;
        MA.Name = 'TestActivity for MAUtilites Test';
        //MA.Marketing_Activity_Ref__c = 'MA Ref';
        MA.recordtypeId = theRecId;
        MA.Start_Date__c = Date.newInstance(2020, 12, 12);
        MA.End_Date__c = Date.newInstance(2021, 12, 12);
        MA.Marketing_Campaign__c = MC.ID;
        MA.Partner__c = testAccount.Id;
        MA.Creative_Agency_Access_To_Salesforce__c = communityUser.id;
        MA.CurrencyIsoCode = 'GBP';
        insert MA;
        }
}
    
    
    @istest static void test1(){
    
        //setUpData();
        Marketing_Activity__c MA = [select id, name, Start_Date__c FROM Marketing_Activity__c WHERE NAME ='TestActivity for MAUtilites Test'];
    
        Activity_Budget_Split__c  ABS = new Activity_Budget_Split__c ();
        ABS.Marketing_Activity__c = MA.id;
        ABS.Year__c = String.valueOf(MA.Start_Date__c.year());
        ABS.X01_January__c = 100;
        ABS.CurrencyIsoCode = 'EUR';
        
        Test.startTest();
        try{
            insert ABS;
        }
        catch(Exception e){
            System.debug('ABS error ' + e.getMessage());
        }

        Test.stopTest();
        
        Activity_Budget_Split__c ABSplit = [SELECT ID, CurrencyIsoCode FROM Activity_Budget_Split__c WHERE id =: ABS.id];
        system.debug('ABS : ' +  ABS);
        System.Assert(ABSplit.CurrencyIsoCode == 'GBP' );
        //System.assertequals('GBP',ABSplit.CurrencyIsoCode, 'error');

        
        
    
    }
        
        
}