force-app/main/default/objects/Account/fields/Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter name of Marketing Promotion that resulted in this VIP Account being created.</inlineHelpText>
    <label>Marketing Activity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Marketing_Activity__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partnership Promotion</value>
        </filterItems>
        <filterItems>
            <field>Marketing_Activity__c.Is_Live__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Marketing_Activity__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Tourism.recordType-meta.xml
<RecordType>
    <fullName>Tourism</fullName>
    <active>true</active>
    <description>A Partner of the Business</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter a End date where you expect the activity to stop impacting footfall/Sales in the Village.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <description>....</description>
    <label>Marketing Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You cannot link an activity to a &apos;Cancelled&apos;  Campaign.</errorMessage>
        <filterItems>
            <field>Marketing_Campaign__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Activities</relationshipLabel>
    <relationshipName>Marketing_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Responsible_Person__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Marketing_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter a date where you expect the activity to impact footfall/Sales in the Village. This is not necessarily the date the email is being sent</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/recordTypes/General_Activity.recordType-meta.xml
<RecordType>
    <fullName>General_Activity</fullName>
    <active>true</active>
    <description>No QR Code...</description>
    <label>General Activity</label>
</RecordType>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/Campaign_Level__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Level__c</fullName>
    <description>Tactical is the norm.

Add &quot;Theme&quot; or &quot;BAU&quot; when required - keep it off so users can only choose Tactical and no validations are required.</description>
    <inlineHelpText>The Campaing Level...</inlineHelpText>
    <label>Campaign Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Theme</fullName>
            </value>
            <value>
                <fullName>BAU Campaign</fullName>
            </value>
            <value>
                <fullName>Non-Campaign</fullName>
            </value>
            <value>
                <fullName>Lead Moment</fullName>
            </value>
            <value>
                <fullName>Local Moment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter the End Date of the Campaign</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <inlineHelpText>Enter a short description about the Campaign</inlineHelpText>
    <label>Short Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter the Start Date of the Campaign</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>...</description>
    <inlineHelpText>Select the Village is this campaign related to</inlineHelpText>
    <label>Village</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>notEqual</operation>
            <value>Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Village Campaign</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trade_Event__c/Trade_Event__c.object-meta.xml
<CustomObject>
    <label>Trade Event</label>
    <nameField>
        <label>Trade Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade_Event__c/fields/Category_Specification__c.field-meta.xml
<CustomField>
    <fullName>Category_Specification__c</fullName>
    <label>Category Specification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trade Show</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Sport</fullName>
            </value>
            <value>
                <fullName>Dinner</fullName>
            </value>
            <value>
                <fullName>Fashion Show</fullName>
            </value>
            <value>
                <fullName>Music</fullName>
            </value>
            <value>
                <fullName>Theatre</fullName>
            </value>
            <value>
                <fullName>Awards Night</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade_Event__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade_Event__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade_Event_Attendee__c/Trade_Event_Attendee__c.object-meta.xml
<CustomObject>
    <description>Junction Object</description>
    <label>Trade Event Attendee</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Trade Event Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade_Event_Attendee__c/fields/Trade_Event__c.field-meta.xml
<CustomField>
    <fullName>Trade_Event__c</fullName>
    <label>Trade Event</label>
    <referenceTo>Trade_Event__c</referenceTo>
    <relationshipLabel>Trade Event Attendees</relationshipLabel>
    <relationshipName>Trade_Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Trade_Event_Attendee__c/fields/Trade_Event_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Trade_Event_Attendee__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; Id,  Contact__r.FirstName + &quot; &quot; +  Contact__r.LastName  ,&quot;_self&quot;)</formula>
    <label>Trade Event Attendee</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/reAssignMarketingActivitiesTest.cls
@isTest
Private Class reAssignMarketingActivitiesTest{

    private static Village__c village = new Village__c();
    public static Trade_Event__c theEvent = new Trade_Event__c();
    public static Account testAccount = new Account();
    public static Marketing_Campaign__c MC = new Marketing_Campaign__c();
    public static Marketing_Activity__c MA = new Marketing_Activity__c();
    public static Marketing_Activity__c MA2 = new Marketing_Activity__c();
    public static list <Marketing_Activity__c> MAList = new list <Marketing_Activity__c>();
    public static User usr1 = new User();

    public static list <contact> contactList1 = new list <contact>();
    public static list <Trade_Event_Attendee__c> attendeelist2 = new list <Trade_Event_Attendee__c>();


    @isTest static void test_method_one() {

      setupData();
        
    ApexPages.StandardSetController StdSetCon = new ApexPages.StandardSetController(MAList);
    reAssignMarketingActivities controller = new reAssignMarketingActivities(StdSetCon);    

      //Apexpages.StandardSetcontroller stdsetController = new Apexpages.StandardSetcontroller();  
      list<reAssignMarketingActivities.wrapper> cMAs = new list<reAssignMarketingActivities.wrapper>();
      MAList = [SELECT Id, Name, Status__c FROM Marketing_Activity__c where id =:MA.id or id=:MA2.id];
      for(Marketing_Activity__c MA : MAList ){
           cMAs.add(new reAssignMarketingActivities.wrapper(MA, true));
          }

      controller.wMAstoEdit = cMAs;

      test.startTest();
      Controller.saveSelected();
      controller.selectAll();
      controller.deselectAll();
      controller.Cancel();
      controller.setAllStatus();
      test.stopTest();

    }   


  static void setupData(){

  recordtype rt = [SELECT id FROM recordtype where sObjectType = 'contact' AND DeveloperName = 'Brand_Contact' LIMIT 1];

 // recordtype mart = [SELECT id FROM recordtype where sObjectType = 'Marketing_Activity__c' AND Name = 'General Activity' LIMIT 1];
  
  recordtype mart = [SELECT id FROM recordtype where sObjectType = 'Marketing_Activity__c' AND DeveloperName = 'General_Activity' LIMIT 1];
      
  testAccount = TestData_Account.setupBrandAccount(1, true);   
               
  village.Name = 'TestVillage1';     
  village.Village_Code__c = 'AA';
  village.CertSales_CertPeriod_Cut_Off_Days__c = 1;
  village.CertSales_Report_Sales_Grace_Period_Days__c = 1; 
  insert village;
  village = [select name, id, Village_Code__c from Village__c where Village_Code__c = 'AA' LIMIT 1];        
    
  
  theEvent.Name = 'test trade event';
  theEvent.Start_Time__c = system.now(); 
  theEvent.End_Time__c = system.now();
  theEvent.Category_Specification__c = 'Conference';
  insert theEvent;

    Profile pf = [select Id from Profile where name = 'Tourism'];
    usr1.LastName = 'myTestu1';
    usr1.Alias = 'myTestu2';
    usr1.Email = 'myTestu2@valueretail.com';
    usr1.Username = 'controllertest123456789@valueretail.com';
    usr1.Communitynickname = 'myTestu2' + 'Nickname';
    usr1.profileId = pf.Id;
    usr1.PortalRole = 'Manager';
    usr1.timezonesidkey = 'Europe/London';
    usr1.emailencodingkey = 'UTF-8';
    usr1.languagelocalekey = 'en_US';
    usr1.localesidkey = 'en_GB';
    usr1.isActive = true;   
    insert usr1;
    
    MC.Name = 'LGC 1';
    MC.Short_Description__c = 'TEST';
    //MC.status__c = 'Confirmed';
    MC.status__c = 'Approved';
    MC.Campaign_Level__c = 'Theme';
    MC.Start_Date__c = system.today();
    MC.End_Date__c = system.today() + 10;
    //MC.Responsible_Person__c = 'test';
    MC.Responsible__c = usr1.id;
    //MC.Accountable__c = 'test';
    MC.Accountable_Person__c = usr1.id;
    insert MC;

    MA.name = 'Test MA1';
    MA.business_Function__c = 'Local Tourism';
    //MA.Partner__c = testAccount.id;
    MA.channel__c = 'BAU';
    MA.Sub_channel__c = 'Agency Fee';
    MA.Marketing_Campaign__c = MC.id;
    MA.recordtypeid = mart.id;
    //MA.status__c = 'Confirmed';
    MA.status__c = 'Approved';
    MA.Start_Date__c = system.today();
    MA.End_Date__c = system.today() + 10;
    MA.objective__c = 'test';
    MA.Response_Description__c = 'test';
    MA.Measurement_Description__c = 'test';
    MA.Communication_Plan__c = 'test';
    MA.Message__c = 'test';
    //MA.Accountable__c = 'test';
    MA.Accountable1__c = usr1.id;
    MA.Responsible_Person__c = usr1.id;
    //MA.Creative_Agency_Access_To_Salesforce__c = usr1.id;
    insert MA;

    MA2.name = 'Test MA2';
    MA2.business_Function__c = 'Local Tourism';
    MA2.channel__c = 'BAU';
    MA2.Sub_channel__c = 'Agency Fee';
    MA2.recordtypeid = mart.id;
    //MA2.Partner__c = testAccount.id;
    MA2.Marketing_Campaign__c = MC.id;
    //MA2.status__c = 'Confirmed';
    MA2.status__c = 'Approved';
    MA2.Start_Date__c = system.today();
    MA2.End_Date__c = system.today() + 10;
    MA2.objective__c = 'test';
    MA2.Response_Description__c = 'test';
    MA2.Measurement_Description__c = 'test';
    MA2.Communication_Plan__c = 'test';
    MA2.Message__c = 'test';
    //MA2.Accountable__c = 'test';
    MA2.Accountable1__c = usr1.id;
    MA2.Responsible_Person__c = usr1.id;
    //MA2.Creative_Agency_Access_To_Salesforce__c = usr1.id;
    insert MA2;
                      
  }


}