force-app/main/default/objects/Account/fields/Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter name of Marketing Promotion that resulted in this VIP Account being created.</inlineHelpText>
    <label>Marketing Activity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Marketing_Activity__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partnership Promotion</value>
        </filterItems>
        <filterItems>
            <field>Marketing_Activity__c.Is_Live__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Marketing_Activity__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>only valid for redeemable campaigns</description>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <description>....</description>
    <label>Marketing Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You cannot link an activity to a &apos;Cancelled&apos;  Campaign.</errorMessage>
        <filterItems>
            <field>Marketing_Campaign__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Activities</relationshipLabel>
    <relationshipName>Marketing_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>...</description>
    <inlineHelpText>Select the Village is this campaign related to</inlineHelpText>
    <label>Village</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>notEqual</operation>
            <value>Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Village Campaign</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet__c/Master_Budget_Sheet__c.object-meta.xml
<CustomObject>
    <label>Master Budget Sheet</label>
    <nameField>
        <label>Master Budget Sheet  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Budget Sheets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Budget_Sheet__c/fields/Budget_Village__c.field-meta.xml
<CustomField>
    <fullName>Budget_Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Master Budget Sheets</relationshipLabel>
    <relationshipName>Master_Budget_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet_Item__c/Master_Budget_Sheet_Item__c.object-meta.xml
<CustomObject>
    <label>Master Budget Sheet Item</label>
    <nameField>
        <label>Master Budget Sheet Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Budget Sheet Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Budget_Sheet_Item__c/fields/Activity_Name__c.field-meta.xml
<CustomField>
    <fullName>Activity_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Activity Name</label>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipLabel>Master Budget Sheet Items</relationshipLabel>
    <relationshipName>Master_Budget_Sheet_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet_Item__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Name</label>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Master Budget Sheet Items</relationshipLabel>
    <relationshipName>Master_Budget_Sheet_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet_Item__c/fields/Creative_Name__c.field-meta.xml
<CustomField>
    <fullName>Creative_Name__c</fullName>
    <label>Creative Name</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet_Item__c/fields/Marketing_Partner__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Budget Sheet Items</relationshipLabel>
    <relationshipName>Master_Budget_Sheet_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Budget_Sheet_Item__c/fields/Master_Budget_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Master_Budget_Sheet__c</fullName>
    <label>Master Budget Sheet</label>
    <referenceTo>Master_Budget_Sheet__c</referenceTo>
    <relationshipLabel>Master Budget Sheet Items</relationshipLabel>
    <relationshipName>Master_Budget_Sheet_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AddMasterBudgetSheetItemController.cls
public with sharing class AddMasterBudgetSheetItemController {

    //Values of the Master Budget Sheet select list
    public List<MasterBudgetSheetItem> MasterBudgetSheetItemList {get; set;}
    public Boolean checkMBSI {get; set;}
    public Boolean disableSave {get; set;}
    public Id marketingActivityId {get; set;}
    public List<SelectOption> MBSSelections {get; set;}
    public Boolean renderMBSPicklist {get; set;}
    public Boolean renderTable {get; set;}
    
    //Get the picklist value
    public Id masterBudgetsheetValue {get; set;}
    public Boolean allSelected {get; set;}

    public AddMasterBudgetSheetItemController(){
        
        renderTable = false;
        renderMBSPicklist = true;
        marketingActivityId = ApexPages.currentPage().getParameters().get('Id');
        disableSave = true;

        //Get data from the current Marketing Campaign
        List<Marketing_Activity__c> mktActivityList = [SELECT Id, Name, Marketing_Campaign__r.Village__c FROM Marketing_Activity__c WHERE Id = :marketingActivityId LIMIT 1];

        List<Master_Budget_Sheet__c> masterBudgetSheetList = new List<Master_Budget_Sheet__c>();

        //Check if the Marketing Campaign is associated with a Village
        if(mktActivityList.get(0).Marketing_Campaign__r.Village__c != null){
            masterBudgetSheetList = [SELECT Id, Name FROM Master_Budget_Sheet__c WHERE Budget_Village__c = :mktActivityList.get(0).Marketing_Campaign__r.Village__c];
        }
        else{//Campaign with TBSC record type
            masterBudgetSheetList = [SELECT Id, Name FROM Master_Budget_Sheet__c];
        }
        
        //If there are master budget sheets, add the query results to the picklist options
        if (!masterBudgetSheetList.isEmpty()){

            MBSSelections = new List<SelectOption>{new SelectOption('--SelectValue--', '-- Select a value --')};
        
            for(Master_Budget_Sheet__c msb : masterBudgetSheetList){
                MBSSelections.add(new SelectOption(msb.Id, msb.Name));
            }
        }
        else{
            renderMBSPicklist = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO, Label.No_Master_Budget_Sheet));
        }
    }

    public void queryMasterBudgetSheetItems(){

        String MBSSelectionsId = String.valueOf(MBSSelections[0].getValue());
        String masterBudgetsheetValueId = String.valueOf(masterBudgetsheetValue);
        
        //Get the Master Budget Sheet Items related to the Master Budget Sheet Selected
        List<Master_Budget_Sheet_Item__c> mbsiList = new List<Master_Budget_Sheet_Item__c>();
        mbsiList = [SELECT Id, Name, Activity_Name__c, Creative_Name__c, Marketing_Partner__c, Campaign_Name__c, Marketing_Partner__r.Name, Campaign_Name__r.Name 
                    FROM Master_Budget_Sheet_Item__c 
                    WHERE Master_Budget_Sheet__c = :masterBudgetsheetValue AND Activity_Name__c = null]; 

        MasterBudgetSheetItemList = new List<MasterBudgetSheetItem>();

        //Create objects with the wrapper class to associate the checkboxes to the Master Budget Sheet Items
        if (mbsiList.size() > 0){
            for(Master_Budget_Sheet_Item__c mbsi : mbsiList){
                MasterBudgetSheetItem mbsiToAdd = new MasterBudgetSheetItem();
                mbsiToAdd.mbsiId = mbsi.Id;
                mbsiToAdd.itemName = mbsi.Name;
                mbsiToAdd.isSelected = false;
                mbsiToAdd.marketingPartnerId = mbsi.Marketing_Partner__c;
                mbsiToAdd.marketingPartner = mbsi.Marketing_Partner__r.Name;
                mbsiToAdd.campaignId = mbsi.Campaign_Name__c;
                mbsiToAdd.campaignName = mbsi.Campaign_Name__r.Name;
                mbsiToAdd.creativeName = mbsi.Creative_Name__c;
                
                MasterBudgetSheetItemList.add(mbsiToAdd);
            }
            renderTable = true;
        }
        else if (masterBudgetsheetValueId.contains(MBSSelectionsId)){
            renderTable = false;
            disableSave = false;
        }
        else {
            renderTable = false;
            disableSave = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO, Label.No_Master_Budget_Sheet));
        }
    }

    //Method for the check all Master Budget Sheet Items List
    public void checkAll(){

        if(allSelected == true){
            for(MasterBudgetSheetItem msbi : MasterBudgetSheetItemList){
                msbi.isSelected = true;
            }
        }
        else{
            for(MasterBudgetSheetItem msbi : MasterBudgetSheetItemList){
                msbi.isSelected = false;
            }
        }
    }

    public PageReference save(){
        if(disableSave == false && MasterBudgetSheetItemList.size() > 0){
            List<Id> listOfIds = new List<Id>();

            for(MasterBudgetSheetItem mbsiToUpdate : MasterBudgetSheetItemList){
                if(mbsiToUpdate.isSelected == true){
                    listOfIds.add(mbsiToUpdate.mbsiId);
                }
            }
            List<Master_Budget_Sheet_Item__c> listToUpdate = [SELECT Id,Campaign_Name__c FROM Master_Budget_Sheet_Item__c  WHERE Id IN :listOfIds];
            for(Master_Budget_Sheet_Item__c mbsiToUpdate : listToUpdate){
                mbsiToUpdate.Activity_Name__c = marketingActivityId;
            }
            if(listToUpdate.size() > 0){
                UPDATE listToUpdate;
                PageReference activitypage = new  PageReference('/' + marketingActivityId );
                activitypage.setRedirect(true);
                return activitypage ;
            }
            else {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, Label.Select_Master_Budget_Sheet_Item));
                return null;
            } 
        }
        else {
                renderTable = false;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, Label.No_Master_Budget_Sheet_items));
                return null;
        }
    }

    public PageReference returnToPage(){
        PageReference activitypage = new  PageReference('/' + marketingActivityId );
        activitypage.setRedirect(true);
        return activitypage;
    }
   
    public void checkSelected(){
        for(MasterBudgetSheetItem msbi : MasterBudgetSheetItemList){
            if(msbi.isSelected){
                disableSave = false;
                return;
            } 
        }
        disableSave = true;
    }

    //Wrapper to help the check box functionality
    public class MasterBudgetSheetItem{
        public Id mbsiId {get; set;}
        public String itemName {get; set;}
        public String creativeName {get; set;}
        public Id marketingPartnerId {get; set;}
        public String marketingPartner {get; set;}
        public Id campaignId {get; set;}
        public String campaignName {get; set;}
        public Id activityId {get; set;}
        public Boolean isSelected {get; set;}
        }
}