force-app/main/default/objects/Account/fields/Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter name of Marketing Promotion that resulted in this VIP Account being created.</inlineHelpText>
    <label>Marketing Activity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Marketing_Activity__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partnership Promotion</value>
        </filterItems>
        <filterItems>
            <field>Marketing_Activity__c.Is_Live__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Marketing_Activity__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <description>A Group or Parent Account for Brand Accounts</description>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Tourism.recordType-meta.xml
<RecordType>
    <fullName>Tourism</fullName>
    <active>true</active>
    <description>A Partner of the Business</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Campaign/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>only valid for redeemable campaigns</description>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Tourism.recordType-meta.xml
<RecordType>
    <fullName>Tourism</fullName>
    <active>true</active>
    <description>All Tourism Responsys campaigns</description>
    <label>Tourism</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <inlineHelpText>Add a Village Presence Contact Role to add Villages to this field</inlineHelpText>
    <label>Village Presence</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter a End date where you expect the activity to stop impacting footfall/Sales in the Village.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <description>....</description>
    <label>Marketing Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You cannot link an activity to a &apos;Cancelled&apos;  Campaign.</errorMessage>
        <filterItems>
            <field>Marketing_Campaign__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Activities</relationshipLabel>
    <relationshipName>Marketing_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter a date where you expect the activity to impact footfall/Sales in the Village. This is not necessarily the date the email is being sent</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/Campaign_Level__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Level__c</fullName>
    <description>Tactical is the norm.

Add &quot;Theme&quot; or &quot;BAU&quot; when required - keep it off so users can only choose Tactical and no validations are required.</description>
    <inlineHelpText>The Campaing Level...</inlineHelpText>
    <label>Campaign Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Theme</fullName>
            </value>
            <value>
                <fullName>BAU Campaign</fullName>
            </value>
            <value>
                <fullName>Non-Campaign</fullName>
            </value>
            <value>
                <fullName>Lead Moment</fullName>
            </value>
            <value>
                <fullName>Local Moment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter the End Date of the Campaign</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter the Start Date of the Campaign</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>...</description>
    <inlineHelpText>Select the Village is this campaign related to</inlineHelpText>
    <label>Village</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>notEqual</operation>
            <value>Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Village Campaign</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participating_Brand__c/Participating_Brand__c.object-meta.xml
<CustomObject>
    <label>Participating Brand</label>
    <nameField>
        <displayFormat>PB-{000000}</displayFormat>
        <label>Participating Brand ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participating Brands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participating_Brand__c/fields/Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity__c</fullName>
    <label>Activity Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Participating Brands can only be associated with Village Campaign Activities</errorMessage>
        <filterItems>
            <field>Marketing_Activity__c.Group_or_Village_Activity__c</field>
            <operation>equals</operation>
            <value>Village Activity</value>
        </filterItems>
        <infoMessage>Please select a Village Activity</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipLabel>Participating Brands (in Village)</relationshipLabel>
    <relationshipName>Participating_Brands</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Participating_Brand__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Campaign</label>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Participating Brands</relationshipLabel>
    <relationshipName>Participating_Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participating_Brand__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Please enter the Name of the Brand in Village</inlineHelpText>
    <label>Brand</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>Marketing Activities</relationshipLabel>
    <relationshipName>Participating_Brands</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the detail of all units in VR Villages</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>...</description>
    <inlineHelpText>Select the Village where this unit lives</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/bulkAddBrandParticipantsControllerTest.cls
@isTest
private class bulkAddBrandParticipantsControllerTest {

    
    static final id GROUP_RECTYPE = Schema.SObjectType.Marketing_Campaign__c.RecordTypeInfosByName.get('TBVSC Brand Campaign').RecordTypeId;
    
    static Marketing_Activity__c marketingActivity = null;
    static Marketing_Campaign__c marketingCampaignGroup = null;
    static Marketing_Campaign__c marketingCampaignVillage = null;
    static Village__c village = new Village__c();
    static Account accA = null;
    static Account accB = null;
    static Account accC = null;
    static Account accD = null;
    static Account account;
    
    static Village_Presence__c vpA = null;
    static Village_Presence__c vpB = null;
    static Village_Presence__c vpC = null;
    static Village_Presence__c vpD = null;
     
    static list<Participating_Brand__c> participatingBrandList = null;
    
    @testSetup static void setupData(){
    
    Profile profileSysAdmin = [SELECT ID, Name FROM Profile WHERE Name = 'System Administrator'];

        UserRole adminRole = new UserRole();
        adminRole.DeveloperName = 'CustomRole';
        adminRole.Name = 'Custom Role';
        insert adminRole;

        User admin = new User();
        admin.LastName = 'AdministratorForTestingHere';
        admin.Alias = 'admin';
        admin.Email = 'adminFortests@valueretai.com';
        admin.Username = 'adminFortests@valueretai.com';
        admin.CommunityNickname = 'admin';
        admin.UserRoleId = adminRole.Id;
        admin.ProfileId = profileSysAdmin.Id;
        admin.Village__c = 'Bicester';
        admin.TimeZoneSidKey = 'GMT';
        admin.LocaleSidKey = 'en_GB';
        admin.EmailEncodingKey = 'ISO-8859-1';
        admin.LanguageLocaleKey = 'en_US';
        insert admin;
    
        system.runAs(admin){
        
        account = TestData_Account.setupTourismAccount(1, true);
        
        Profile pf = [select Id from Profile where name = 'Tourism'];
        
        RecordType brandRecordType = [SELECT Id, Name FROM RecordType WHERE Name = 'Brand'];
            
            Account brand = new Account();
            brand.RecordTypeId = brandRecordType.Id;
            brand.Name = 'Brand 1';
            insert brand;
        
            RecordType brandContactRecordType = [SELECT Id, Name FROM RecordType WHERE Name = 'Brand Contact'];
        
            Contact communityContact = new Contact();
            communityContact.RecordTypeId = brandContactRecordType.Id;
            communityContact.LastName = 'John';
            communityContact.AccountId = brand.Id;
            communityContact.Village_Presence__c = 'Bicester';
            communityContact.Email = 'testcommunity.contact@brand.com';
            insert communityContact;
            
            Profile profileCommunity = [SELECT ID, Name FROM Profile WHERE Name = 'Third Party Community User'];
                
            User communityUser = new User();
            communityUser.LastName = communityContact.LastName;
            communityUser.Alias = 'jhn';
            communityUser.Email = communityContact.Email;
            communityUser.Username = 'john@valueretai.com';
            communityUser.CommunityNickname = 'johnvr';
            communityUser.ProfileId = profileCommunity.Id;
            communityUser.Village__c = 'Bicester';
            communityUser.TimeZoneSidKey = 'GMT';
            communityUser.LocaleSidKey = 'en_GB';
            communityUser.EmailEncodingKey = 'ISO-8859-1';
            communityUser.LanguageLocaleKey = 'en_US';
            communityUser.ContactId = communityContact.Id;
            communityUser.PortalRole = 'Manager';
            insert communityUser;

        accA = TestDataGenerator.setupB2BAccount(1, true);
        accB = TestDataGenerator.setupB2BAccount(2, true);
        accC = TestDataGenerator.setupB2BAccount(3, true);
        accD = TestDataGenerator.setupB2BAccount(4, true);
        
        marketingCampaignGroup = new Marketing_Campaign__c();
        marketingCampaignGroup.Campaign_Level__c = 'Theme';
        marketingCampaignGroup.Start_Date__c = system.today();
        marketingCampaignGroup.End_Date__c = system.today().addDays(30);
        marketingCampaignGroup.Name = 'Test Group Campaign';
        marketingCampaignGroup.RecordTypeId = GROUP_RECTYPE;
        insert marketingCampaignGroup;

        village = new Village__c();
        village.Name = 'TestVillage';
        village.Village_Code__c = 'TV';
		village.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		village.CertSales_Report_Sales_Grace_Period_Days__c = 1;
        insert village;
        
        Unit__c u = new Unit__c();
        u.name = 'Test';
        u.Suite_ID__c = '2';
        u.Phase_ID__c = 'BV1';
        u.village__c = village.Id;
        u.Size_GEA__c = 43;
        u.Unit_Status__c = 'Available';
        u.Unit_Designation__c = 'Retail';
        insert u;
        
        list<Village_Presence__c> vpList = new list<Village_Presence__c>();
        vpA = VillagePresenceUtilities.createVillagePresence(accA.Id, 'TV');
        //vpA.Status__c = 'Trading';
        vpA.Unit__c = u.id;
        vpList.add(vpA);
        vpB = VillagePresenceUtilities.createVillagePresence(accB.Id, 'TV');
        //vpB.Status__c = 'Trading';
        vpB.Unit__c = u.id;
        vpList.add(vpB);
        vpC = VillagePresenceUtilities.createVillagePresence(accC.Id, 'TV');
        //vpC.Status__c = 'Trading';
        vpC.Unit__c = u.id;
        vpList.add(vpC);
        vpD = VillagePresenceUtilities.createVillagePresence(accD.Id, 'TV');
        //vpD.Status__c = 'Trading';
        vpD.Unit__c = u.id;
        vpList.add(vpD);
        
        update vpList;
        
        for(Village_Presence__c vp : vpList){
            vp.status__c = 'Trading';
        }
        update vpList;
        
        
        marketingCampaignVillage = new Marketing_Campaign__c();
        marketingCampaignVillage.Start_Date__c = system.today();
        marketingCampaignVillage.End_Date__c = system.today().addDays(30);
        marketingCampaignVillage.Name = 'Test Village Campaign';
        marketingCampaignVillage.Parent_Marketing_Campaign__c = marketingCampaignGroup.Id;
        marketingCampaignVillage.Village__c = village.Id;
        insert marketingCampaignVillage;                


        marketingActivity = new Marketing_Activity__c();
        
        marketingActivity.name = 'Test Marketing Activity';
        marketingActivity.Start_Date__c = system.today().toStartOfWeek();
        marketingActivity.End_Date__c = system.today().toStartOfWeek().addDays(14); 
        marketingActivity.Marketing_Campaign__c = marketingCampaignVillage.Id;
        marketingActivity.Responsible_Person__c = system.userInfo.getUserId();
        marketingActivity.Partner__c = account.Id;
        marketingActivity.Creative_Agency_Access_To_Salesforce__c = communityUser.id;
        insert marketingActivity;
        }
    }
    
  
    static testMethod void unitTest() {
           
        //setupData();

        Marketing_Activity__c marketingActivity = [SELECT id, Name FROM Marketing_Activity__c Where Name = 'Test Marketing Activity'];  
    
        list< Participating_Brand__c> pbList = new list< Participating_Brand__c>();     
        PageReference pg = new PageReference('/apex/bulkAddBrandParticipants');
        pg.getParameters().put('Id', marketingActivity.Id);
        test.setCurrentPageReference(pg);               
        
        test.startTest();
            bulkAddBrandParticipantsController controller  = new bulkAddBrandParticipantsController();
            
            // check we have 4 records available for selection
            system.assertEquals(4, controller.ParticipantBrandList.size());
            
            // select first item in list
            controller.ParticipantBrandList[0].selected = true;                     
            pg = controller.save();
            
            //check 1 item selected
            system.assertEquals(1, controller.SelectedParticipantBrands.size());
            
            // Check against object record
            pbList = [select Village_Presence__c from Participating_Brand__c where Marketing_Activity__c = :marketingActivity.Id];
            system.assertEquals(1, pbList.size());
            system.assertEquals (pbList[0].Village_Presence__c, controller.SelectedParticipantBrands[0]. Village_Presence__c);
            
            controller  = new bulkAddBrandParticipantsController();
            // deselect 1st item
            controller.ParticipantBrandList[0].selected = false;
            controller.ParticipantBrandList[1].selected = true;
            controller.ParticipantBrandList[2].selected = true;
            controller.ParticipantBrandList[3].selected = true;                     
            pg = controller.save();

            //check 3 items selected
            system.assertEquals(3, controller.SelectedParticipantBrands.size());
            
            // Check against object record
            pbList = [select Village_Presence__c from Participating_Brand__c where Marketing_Activity__c = :marketingActivity.Id];
            system.assertEquals(4, pbList.size());
                        
            controller  = new bulkAddBrandParticipantsController();
            // deselect all items
            controller.allSelected = false;
            pg = controller.checkAll();
            pg = controller.save();
            
            //check 0 items selected
            system.assertEquals(0, controller.SelectedParticipantBrands.size());
            
            // Check against object record, 0 items selected
            pbList = [select Village_Presence__c from Participating_Brand__c where Marketing_Activity__c = :marketingActivity.Id];
            system.assertEquals(4, pbList.size());                      
            
            
            // for coverage, call methods to populate picklists and cancel
            
            list<selectoption> statusList = controller.getStatuses();
            system.assert(statusList != null);

            list<selectoption> discountList = controller.getDiscounts();
            system.assert(discountList != null);
            
            list<selectoption> minimumPurchaseList = controller.getMinimumPurchases();
            system.assert(minimumPurchaseList != null);

            list<selectoption> giftWithPurchaseList = controller.getGiftWithPurchases();
            system.assert(giftWithPurchaseList != null);
            
            pg = controller.cancel();           
            
        
        test.stopTest();
        
    }
    
    static testMethod void testDelete(){

        //setupData();

        Marketing_Activity__c marketingActivity = [SELECT id, Name FROM Marketing_Activity__c Where Name = 'Test Marketing Activity'];  
    
        list< Participating_Brand__c> pbList = new list< Participating_Brand__c>();     
        PageReference pg = new PageReference('/apex/bulkAddBrandParticipants');
        pg.getParameters().put('Id', marketingActivity.Id);
        test.setCurrentPageReference(pg);               
        
        test.startTest();

        bulkAddBrandParticipantsController controller  = new bulkAddBrandParticipantsController();

            controller.ParticipantBrandList[0].selected = true;
            controller.ParticipantBrandList[1].selected = true;                     
            pg = controller.save();

            
            //check 1 item selected
            system.assertEquals(2, controller.SelectedParticipantBrands.size());
            
            // Check against object record
            pbList = [select Village_Presence__c from Participating_Brand__c where Marketing_Activity__c = :marketingActivity.Id];
            system.assertEquals(2, pbList.size());

            controller = new bulkAddBrandParticipantsController();
            
            controller.ParticipantBrandList[0].selected = true;
            controller.ParticipantBrandList[1].selected = false;
            pg = controller.deleteRecord();
            // Check against object record
            pbList = [select Village_Presence__c from Participating_Brand__c where Marketing_Activity__c = :marketingActivity.Id];
            system.assertEquals(1, pbList.size());

            controller = new bulkAddBrandParticipantsController();
            // save all an then delete all

            controller.allSelected = true;
            pg = controller.checkAll();
            pg = controller.save();

            pbList = [select Village_Presence__c from Participating_Brand__c where Marketing_Activity__c = :marketingActivity.Id];
            system.assertEquals(4, pbList.size());

            controller = new bulkAddBrandParticipantsController();

            controller.allSelected = true;
            pg = controller.checkAll();
            pg = controller.deleteRecord();

            pbList = [select Village_Presence__c from Participating_Brand__c where Marketing_Activity__c = :marketingActivity.Id];
            system.assertEquals(0, pbList.size());

    }
    
}