force-app/main/default/objects/Account/fields/Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter name of Marketing Promotion that resulted in this VIP Account being created.</inlineHelpText>
    <label>Marketing Activity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Marketing_Activity__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partnership Promotion</value>
        </filterItems>
        <filterItems>
            <field>Marketing_Activity__c.Is_Live__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Marketing_Activity__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <description>A Group or Parent Account for Brand Accounts</description>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Tourism.recordType-meta.xml
<RecordType>
    <fullName>Tourism</fullName>
    <active>true</active>
    <description>A Partner of the Business</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Campaign/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If this Group Campaign is linked to a Tourism Partner account the Select the Account</inlineHelpText>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Tourism</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>only valid for redeemable campaigns</description>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Tourism.recordType-meta.xml
<RecordType>
    <fullName>Tourism</fullName>
    <active>true</active>
    <description>All Tourism Responsys campaigns</description>
    <label>Tourism</label>
</RecordType>

force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter a End date where you expect the activity to stop impacting footfall/Sales in the Village.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Expected_Footfall__c.field-meta.xml
<CustomField>
    <fullName>Expected_Footfall__c</fullName>
    <inlineHelpText>The expected footfall which will be generated as a result of this activity</inlineHelpText>
    <label>Expected Footfall</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <description>....</description>
    <label>Marketing Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You cannot link an activity to a &apos;Cancelled&apos;  Campaign.</errorMessage>
        <filterItems>
            <field>Marketing_Campaign__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Activities</relationshipLabel>
    <relationshipName>Marketing_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Responsible_Person__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Marketing_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Split_Type__c.field-meta.xml
<CustomField>
    <fullName>Split_Type__c</fullName>
    <label>Split Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter a date where you expect the activity to impact footfall/Sales in the Village. This is not necessarily the date the email is being sent</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity_Split__c/Marketing_Activity_Split__c.object-meta.xml
<CustomObject>
    <label>Marketing Activity Split</label>
    <nameField>
        <displayFormat>MAS-{00000000}</displayFormat>
        <label>Marketing Activity Split</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Activity Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity_Split__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>This is the start of the week</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity_Split__c/fields/Expected_Footfall__c.field-meta.xml
<CustomField>
    <fullName>Expected_Footfall__c</fullName>
    <label>Expected Footfall</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity_Split__c/fields/Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity__c</fullName>
    <label>Marketing Activity</label>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipLabel>Marketing Activity Splits</relationshipLabel>
    <relationshipName>Marketing_Activity_Splits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/Campaign_Level__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Level__c</fullName>
    <description>Tactical is the norm.

Add &quot;Theme&quot; or &quot;BAU&quot; when required - keep it off so users can only choose Tactical and no validations are required.</description>
    <inlineHelpText>The Campaing Level...</inlineHelpText>
    <label>Campaign Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Theme</fullName>
            </value>
            <value>
                <fullName>BAU Campaign</fullName>
            </value>
            <value>
                <fullName>Non-Campaign</fullName>
            </value>
            <value>
                <fullName>Lead Moment</fullName>
            </value>
            <value>
                <fullName>Local Moment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter the End Date of the Campaign</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Parent_Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Parent_Marketing_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a Parent Marketing Campaign</inlineHelpText>
    <label>Parent Marketing Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Parent Campaigns must be TBVSC Brand Campaigns</errorMessage>
        <filterItems>
            <field>Marketing_Campaign__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <infoMessage>Please select a TBVSC Brand Campaign</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Responsible_Person__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Person__c</fullName>
    <inlineHelpText>Enter the Names of the people that are responsible for the activities in this campaign</inlineHelpText>
    <label>Responsible</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter the Start Date of the Campaign</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>...</description>
    <inlineHelpText>Select the Village is this campaign related to</inlineHelpText>
    <label>Village</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>notEqual</operation>
            <value>Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Village Campaign</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MarketingSplitUtilitiesTest.cls
@isTest
private class MarketingSplitUtilitiesTest {

    static Marketing_Activity__c marketingActivity = null;
    static Marketing_Campaign__c marketingCampaignGroup = null;
    static Marketing_Campaign__c marketingCampaignVillage = null;
    static Village__c village = new Village__c(); 
    static final id GROUP_RECTYPE = Schema.SObjectType.Marketing_Campaign__c.RecordTypeInfosByName.get('TBVSC Brand Campaign').RecordTypeId;
    static Account account;
    
    static void setupData(){
        
        account = TestData_Account.setupTourismAccount(1, true);
        
        marketingCampaignGroup = new Marketing_Campaign__c();
        marketingCampaignGroup.Start_Date__c = system.today();
        marketingCampaignGroup.End_Date__c = system.today().addDays(30);
        marketingCampaignGroup.Name = 'Test Group Campaign';
        marketingCampaignGroup.Campaign_Level__c = 'Theme';
        marketingCampaignGroup.RecordTypeId = GROUP_RECTYPE;
        insert marketingCampaignGroup;

        village = new Village__c();
        village.Name = 'TestVillage';
        village.Village_Code__c = 'TV';
		village.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		village.CertSales_Report_Sales_Grace_Period_Days__c = 1; 
        insert village;
        
        marketingCampaignVillage = new Marketing_Campaign__c();
        marketingCampaignVillage.Start_Date__c = system.today();
        marketingCampaignVillage.End_Date__c = system.today().addDays(30);
        marketingCampaignVillage.Name = 'Test Village Campaign';
        marketingCampaignVillage.Campaign_Level__c = 'Theme';
        marketingCampaignVillage.Parent_Marketing_Campaign__c = marketingCampaignGroup.Id;
        marketingCampaignVillage.Village__c = village.Id;
        
        insert marketingCampaignVillage;               
        
    }
    

    static testMethod void unitTest() {
        
        setupData();
        
        Profile pf = [select Id from Profile where name = 'Tourism'];
        User usr1 = new User();
        usr1.LastName = 'myTestu1';
        usr1.Alias = 'myTestu2';
        usr1.Email = 'myTestu2@valueretail.com';
        usr1.Username = 'controllertest123456789@valueretail.com';
        usr1.Communitynickname = 'myTestu2' + 'Nickname';
        usr1.profileId = pf.Id;
        usr1.PortalRole = 'Manager';
        usr1.timezonesidkey = 'Europe/London';
        usr1.emailencodingkey = 'UTF-8';
        usr1.languagelocalekey = 'en_US';
        usr1.localesidkey = 'en_GB';
        usr1.isActive = true;   
        insert usr1;   
        
        marketingActivity = new Marketing_Activity__c();
        
        marketingActivity.name = 'Test Marketing Activity';
        marketingActivity.Start_Date__c = system.today().toStartOfWeek();
        marketingActivity.End_Date__c = system.today().toStartOfWeek().addDays(14); //15 days
        marketingActivity.Expected_Footfall__c = 1500; // therefore 100/day
        marketingActivity.Marketing_Campaign__c = marketingCampaignVillage.Id;
        marketingActivity.Responsible_Person__c = system.userInfo.getUserId();
        marketingActivity.Split_Type__c = 'Weekly';
        marketingActivity.Partner__c = account.Id;
        //marketingActivity.Creative_Agency_Access_To_Salesforce__c = usr1.id;
        insert marketingActivity;
        
        list<Marketing_Activity_Split__c> splitsList = [select Date__c, Expected_Footfall__c, Expected_Sales__c 
                                                        from Marketing_Activity_Split__c
                                                        where Marketing_Activity__r.Id = :marketingActivity.Id
                                                        order by Date__c asc];
        
        // check split records                                              
        system.assertEquals(splitsList.size(), 3);
        system.assertEquals(splitsList[0].Expected_Footfall__c, 700);
        system.assertEquals(splitsList[1].Expected_Footfall__c, 700);
        system.assertEquals(splitsList[2].Expected_Footfall__c, 100);
        system.assertEquals(splitsList[0].Expected_Sales__c, 0);
        system.assertEquals(splitsList[1].Expected_Sales__c, 0);
        system.assertEquals(splitsList[2].Expected_Sales__c, 0);
        system.assertEquals(splitsList[0].Date__c, system.today().toStartOfWeek());
        system.assertEquals(splitsList[1].Date__c, system.today().toStartOfWeek().addDays(7));
        system.assertEquals(splitsList[2].Date__c, system.today().toStartOfWeek().addDays(14));                                              
        
        // make amendment to marketing activity footfall figure
        marketingActivity.Expected_Footfall__c = 3000; // therefore 200/day
        update marketingActivity;

        splitsList = [select Date__c, Expected_Footfall__c, Expected_Sales__c 
                                                        from Marketing_Activity_Split__c
                                                        where Marketing_Activity__r.Id = :marketingActivity.Id
                                                        order by Date__c asc];
        
        // check split records                                              
        system.assertEquals(splitsList[0].Expected_Footfall__c, 1400);
        system.assertEquals(splitsList[1].Expected_Footfall__c, 1400);
        system.assertEquals(splitsList[2].Expected_Footfall__c, 200);       


        // make amendment to marketing activity date figures - so covers less than a week
        marketingActivity.Start_Date__c = system.today().toStartOfWeek();
        marketingActivity.End_Date__c = system.today().toStartOfWeek().addDays(3); 
        update marketingActivity;

        splitsList = [select Date__c, Expected_Footfall__c, Expected_Sales__c 
                                                        from Marketing_Activity_Split__c
                                                        where Marketing_Activity__r.Id = :marketingActivity.Id
                                                        order by Date__c asc];
        
         // check split records                                             
        system.assertEquals(splitsList.size(), 1);                                              
        system.assertEquals(splitsList[0].Expected_Footfall__c, 3000);
        system.assertEquals(splitsList[0].Date__c, marketingActivity.Start_Date__c);
        system.assertEquals(splitsList[0].Expected_sales__c, 0);            

    }
}