force-app/main/default/objects/Account/fields/Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter name of Marketing Promotion that resulted in this VIP Account being created.</inlineHelpText>
    <label>Marketing Activity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Marketing_Activity__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partnership Promotion</value>
        </filterItems>
        <filterItems>
            <field>Marketing_Activity__c.Is_Live__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Marketing_Activity__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field exists purely to provide a relationship between &quot;In_Village_Brand_Activity__c&quot; - Account - &quot;Marketing_Activity__c&quot;, this allows the related marketing Activty to be shown on the Account layout in a related list.
It is populated by a process builder workflow - &quot;In Village Brand Activity Set Brand__c&quot;, a process invoked by insert or update of an &quot;In_Village_Brand_Activity__c&quot; record.</description>
    <label>Brand</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing Activities (Brand)</relationshipLabel>
    <relationshipName>Marketing_Activities_Brand</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter a End date where you expect the activity to stop impacting footfall/Sales in the Village.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <description>....</description>
    <label>Marketing Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You cannot link an activity to a &apos;Cancelled&apos;  Campaign.</errorMessage>
        <filterItems>
            <field>Marketing_Campaign__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Activities</relationshipLabel>
    <relationshipName>Marketing_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter a date where you expect the activity to impact footfall/Sales in the Village. This is not necessarily the date the email is being sent</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/recordTypes/General_Activity.recordType-meta.xml
<RecordType>
    <fullName>General_Activity</fullName>
    <active>true</active>
    <description>No QR Code...</description>
    <label>General Activity</label>
</RecordType>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/Campaign_Level__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Level__c</fullName>
    <description>Tactical is the norm.

Add &quot;Theme&quot; or &quot;BAU&quot; when required - keep it off so users can only choose Tactical and no validations are required.</description>
    <inlineHelpText>The Campaing Level...</inlineHelpText>
    <label>Campaign Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Theme</fullName>
            </value>
            <value>
                <fullName>BAU Campaign</fullName>
            </value>
            <value>
                <fullName>Non-Campaign</fullName>
            </value>
            <value>
                <fullName>Lead Moment</fullName>
            </value>
            <value>
                <fullName>Local Moment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter the End Date of the Campaign</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter the Start Date of the Campaign</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>...</description>
    <inlineHelpText>Select the Village is this campaign related to</inlineHelpText>
    <label>Village</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>notEqual</operation>
            <value>Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Village Campaign</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/recordTypes/Village_Campaign.recordType-meta.xml
<RecordType>
    <fullName>Village_Campaign</fullName>
    <active>true</active>
    <description>A Marketing Brief for a Village&apos;s Campaign..</description>
    <label>Village Campaign</label>
</RecordType>

force-app/main/default/objects/Participating_Brand__c/Participating_Brand__c.object-meta.xml
<CustomObject>
    <label>Participating Brand</label>
    <nameField>
        <displayFormat>PB-{000000}</displayFormat>
        <label>Participating Brand ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participating Brands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participating_Brand__c/fields/Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity__c</fullName>
    <label>Activity Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Participating Brands can only be associated with Village Campaign Activities</errorMessage>
        <filterItems>
            <field>Marketing_Activity__c.Group_or_Village_Activity__c</field>
            <operation>equals</operation>
            <value>Village Activity</value>
        </filterItems>
        <infoMessage>Please select a Village Activity</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipLabel>Participating Brands (in Village)</relationshipLabel>
    <relationshipName>Participating_Brands</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Participating_Brand__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Campaign</label>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Participating Brands</relationshipLabel>
    <relationshipName>Participating_Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participating_Brand__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Please enter the Name of the Brand in Village</inlineHelpText>
    <label>Brand</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>Marketing Activities</relationshipLabel>
    <relationshipName>Participating_Brands</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Village Presence records must be linked to Brand accounts. Please ensure you are not linking the Deal/Village Presence to a Group</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/ParticipatingBrandTriggerTest.cls
@isTest
public class ParticipatingBrandTriggerTest{

	@testSetup
	static void testSetup(){
		Village__c village = TestDataGenerator.setupVillage(true);
		Account brand = TestData_Account.setupBrandAccount(6, true);

		Village_Presence__c vp = new Village_Presence__c(Village__c = village.Id, Brand__c = brand.Id);
		INSERT vp;

		Id campaignRecTypeId = Schema.SObjectType.Marketing_Campaign__c.getRecordTypeInfosByDeveloperName().get('Village_Campaign').getRecordTypeId();
		Marketing_Campaign__c marketCamp = new Marketing_Campaign__c();
		
		marketCamp.RecordTypeId = campaignRecTypeId;
        marketCamp.Start_Date__c = Date.today().addDays(-10);
        marketCamp.End_Date__c = Date.today().addDays(10);
        marketCamp.Campaign_Level__c = 'Theme';
        marketCamp.Village__c = village.Id;

        INSERT marketCamp;

  //    Id actRecTypeId = Schema.SObjectType.Marketing_Activity__c.getRecordTypeInfosByName().get('General Activity').getRecordTypeId();
		Id actRecTypeId = Schema.SObjectType.Marketing_Activity__c.getRecordTypeInfosByDeveloperName().get('General_Activity').getRecordTypeId();
        Marketing_Activity__c mAct = new Marketing_Activity__c(RecordTypeId = actRecTypeId,
																Start_Date__c = Date.today().addDays(-10), 
																End_Date__c = Date.today().addDays(10), 
																Marketing_Campaign__c = marketCamp.Id);
		INSERT mAct;
	}

	@isTest
	public static void testCreate(){
		List<Village_Presence__c> vpList = [SELECT Id FROM Village_Presence__c];
		List<Marketing_Activity__c> mActList = [SELECT Id FROM Marketing_Activity__c];

		Participating_Brand__c pBrand = new Participating_Brand__c(Village_Presence__c = vpList.get(0).Id, Marketing_Activity__c = mActList.get(0).Id);

		Test.startTest();
			INSERT pBrand;
		Test.stopTest();

		List<Participating_Brand__c> result = [SELECT Id FROM Participating_Brand__c];
		System.assertNotEquals(null, result, 'Result was not as expected.');
	}

	@isTest
	public static void testUpdate(){
		List<Village_Presence__c> vpList = [SELECT Id FROM Village_Presence__c];
		List<Marketing_Activity__c> mActList = [SELECT Id FROM Marketing_Activity__c];

		Participating_Brand__c pBrand = new Participating_Brand__c(Village_Presence__c = vpList.get(0).Id, Marketing_Activity__c = mActList.get(0).Id);
		INSERT pBrand;

		Test.startTest();
			UPDATE pBrand;
		Test.stopTest();

		List<Participating_Brand__c> result = [SELECT Id, Marketing_Campaign__c FROM Participating_Brand__c];
		System.assertNotEquals(null, result[0].Marketing_Campaign__c, 'Result was not as expected.');
	}
}