force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>...</description>
    <inlineHelpText>The primary Region this partner will bring guests from.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>A Retail Brand Account (Global)</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <description>A Group or Parent Account for Brand Accounts</description>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Oceania</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>(B2T) MICE cature field</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Oceania</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brand_Captain__c.field-meta.xml
<CustomField>
    <fullName>Brand_Captain__c</fullName>
    <description>This is an old field for EU Brand Captain that is no longer used.  This field cannot be easily removed from Salesforce as it is included in Apex Classes and various Report Types.</description>
    <label>EUBC</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Negotiator_Brand__c.field-meta.xml
<CustomField>
    <fullName>Lead_Negotiator_Brand__c</fullName>
    <label>Lead Negotiator Brand</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Negotiator_VR__c.field-meta.xml
<CustomField>
    <fullName>Lead_Negotiator_VR__c</fullName>
    <label>Lead Negotiator VR</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>Village__r.Region__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The region pulled from the Village for this opportunity</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the actual village where this opportunity exists</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <description>Defines the geography or region where the villages are situated</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Brand_Captain__c.field-meta.xml
<CustomField>
    <fullName>Brand_Captain__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for Brand Captain Report filtering only (at present)</description>
    <inlineHelpText>Is the User a Brand Captain (used for report filtering)</inlineHelpText>
    <label>Brand Captain</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Default_Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Default_Contract_Type__c</fullName>
    <inlineHelpText>Select the default contract type when creating new contracts</inlineHelpText>
    <label>Default Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>Licence</fullName>
            </value>
            <value>
                <fullName>MSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the region where this village is situated</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Villages</relationshipLabel>
    <relationshipName>Villages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Std_Break_Clause__c.field-meta.xml
<CustomField>
    <fullName>Std_Break_Clause__c</fullName>
    <inlineHelpText>Enter the Standard Landlords Break Clause</inlineHelpText>
    <label>Std Break Clause</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Std_Fit_Out_days__c.field-meta.xml
<CustomField>
    <fullName>Std_Fit_Out_days__c</fullName>
    <inlineHelpText>Enter the standard fitting out period in days to be used in this village</inlineHelpText>
    <label>Std Fit Out (days)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Std_Lease_Term_months__c.field-meta.xml
<CustomField>
    <fullName>Std_Lease_Term_months__c</fullName>
    <defaultValue>120</defaultValue>
    <inlineHelpText>Enter the standard lease term in months for leases in this village</inlineHelpText>
    <label>Std Lease Term (months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VR1_Configuration_Settings__c/VR1_Configuration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration settings for VR1</description>
    <label>VR1 Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/VR1_Configuration_Settings__c/fields/Brand_to_Deal_Role_Sync_Items__c.field-meta.xml
<CustomField>
    <fullName>Brand_to_Deal_Role_Sync_Items__c</fullName>
    <description>Comma separated list of Brand roles which should be synchronised with associated Deals when the &apos;Synchronise Deal Roles&apos; button is clicked on the Account detail page.</description>
    <inlineHelpText>Comma separated list of Brand roles which should be synchronised with associated Deals when the &apos;Synchronise Deal Roles&apos; button is clicked on the Account detail page.</inlineHelpText>
    <label>Brand to Deal Role Sync Items</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Greater China</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>Not Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Rest of World</fullName>
    </customValue>
    <customValue>
        <fullName>Russia &amp; CIS</fullName>
    </customValue>
    <customValue>
        <fullName>South East Asia</fullName>
    </customValue>
    <customValue>
        <fullName>US</fullName>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Test_OpportunityTeamMemberSync.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Test_OpportunityTeamMemberSync {
	
	private static final id brandRecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Brand').RecordTypeId;
	
    static testMethod void testOppTeam() {

        Opportunity opportunity = new Opportunity();
        
        //Set up Users
        //UserRole ur = [select id from UserRole where name = 'Group Value Retail'];
        UserRole ur = [select id from UserRole where name = 'Group Leasing'];
        Profile pf = [select Id from Profile where name = 'System Administrator'];
        
        // User u1 = TestDataGenerator.setupUser('Testu1', ur, pf, true, true);
        // User u2 = TestDataGenerator.setupUser('Testu2', ur, pf, true, true);
        // User u3 = TestDataGenerator.setupUser('Testu3', ur, pf, true, true);  
        
        User u1 = new User(LastName = 'Testu1',
            Alias = 'Testu1',
            Email = 'Testu1@valueretail.com',
            Username = 'Testu1@valueretail.com',
            Communitynickname = 'Testu1' + 'Nickname',
            userroleId = ur.Id,
            profileId = pf.Id,
            timezonesidkey = 'Europe/London',
            emailencodingkey = 'UTF-8',
            languagelocalekey = 'en_US',
            localesidkey = 'en_GB',
            isActive = true);
        insert u1;
            
        User u2 = new User(LastName = 'Testu2',
            Alias = 'Testu2',
            Email = 'Testu2@valueretail.com',
            Username = 'Testu2@valueretail.com',
            Communitynickname = 'Testu2' + 'Nickname',
            userroleId = ur.Id,
            profileId = pf.Id,
            timezonesidkey = 'Europe/London',
            emailencodingkey = 'UTF-8',
            languagelocalekey = 'en_US',
            localesidkey = 'en_GB',
            isActive = true);
        insert u2;

        User u3 = new User(LastName = 'Testu3',
            Alias = 'Testu3',
            Email = 'Testu3@valueretail.com',
            Username = 'Testu3@valueretail.com',
            Communitynickname = 'Testu3' + 'Nickname',
            userroleId = ur.Id,
            profileId = pf.Id,
            timezonesidkey = 'Europe/London',
            emailencodingkey = 'UTF-8',
            languagelocalekey = 'en_US',
            localesidkey = 'en_GB',
            isActive = true);
        insert u3;

// insert some custom settings



        system.runAs(u1){
            VR1_Configuration_Settings__c mycs = new VR1_Configuration_Settings__c(Brand_to_Deal_Role_Sync_Items__c= 'EU Brand Captain,Lead Negotiator,Legal Lead');
insert mycs;
            // Set up Account test data
            Account account = new Account(Name='TestA', RecordTypeId = brandRecordTypeId);
            insert account;
            
            // Set up Region        
            Region__c region1 = new Region__c(Name = 'China');
            insert region1;
            
            Region__c region2 = new Region__c(Name = 'GB');
            insert region2;
            
            
            // Set up Village test data
            Village__c village = new Village__c(Name='TestV', Std_Break_Clause__c = 'Test_Std_Break_Clause__c',
                                            Std_Fit_Out_days__c = 7, Default_Contract_Type__c = 'Lease',
                                            Std_Lease_Term_months__c = 12, Village_Code__c = 'TT', Region__c = region2.Id, CertSales_CertPeriod_Cut_Off_Days__c = 1, CertSales_Report_Sales_Grace_Period_Days__c = 1);
            insert village;
            
            //Set up Opportunity test data
            opportunity = new Opportunity(Name='TestO', StageName = 'In discussion', 
                                            AccountId = account.Id, CloseDate=system.today()+7,
                                            Village__c = village.id);
            insert opportunity;
        
        
            test.startTest();
            
            //Add team members to opportunity
            OpportunityTeamMember otm1 = new OpportunityTeamMember(UserId = u1.Id,TeamMemberRole = 'EU Brand Captain', OpportunityId = opportunity.Id);     
            insert otm1;
    
            OpportunityTeamMember otm2 = new OpportunityTeamMember(UserId = u2.Id,TeamMemberRole = 'Lead Negotiator', OpportunityId = opportunity.Id);      
            insert otm2;
    
            OpportunityTeamMember otm3 = new OpportunityTeamMember(UserId = u3.Id,TeamMemberRole = 'Legal Lead', OpportunityId = opportunity.Id);       
            insert otm3;
            
                    // lets try to add a team member
          AccountTeamMember atm1 = new AccountTeamMember(UserId = u1.Id,TeamMemberRole = 'EU Brand Captain', AccountId = account.Id);     
            insert atm1;
        
            AccountTeamMember atm2 = new AccountTeamMember(UserId = u2.Id,TeamMemberRole = 'Lead Negotiator', AccountId = account.Id);     
            insert atm2;

            AccountTeamMember atm3 = new AccountTeamMember(UserId = u3.Id,TeamMemberRole = 'Legal Lead', AccountId = account.Id);     
            insert atm3;

            test.stopTest();

             OpportunityTeamMemberSync.syncAccountRecordListPersonnel(new List<Id>{account.Id});

        }
        
        opportunity = [select Id, Lead_Negotiator_VR__c, Brand_Captain__c
                            from Opportunity where id = :opportunity.Id];
        
        u1 = [select Name from User where Id =:u1.Id];
        u2 = [select Name from User where Id =:u2.Id];
        
        system.assertEquals(opportunity.Brand_Captain__c, u1.Name);                 
        system.assertEquals(opportunity.Lead_Negotiator_VR__c, u2.Name);                    




    }
    
    static testMethod void testOppRole() {

  UserRole ur = [select id from UserRole where name = 'Group Leasing'];
        Profile pf = [select Id from Profile where name = 'System Administrator'];

        User u1 = new User(LastName = 'Testu1',
            Alias = 'Testu1',
            Email = 'Testu1@valueretail.com',
            Username = 'Testu1@valueretail.com',
            Communitynickname = 'Testu1' + 'Nickname',
            userroleId = ur.Id,
            profileId = pf.Id,
            timezonesidkey = 'Europe/London',
            emailencodingkey = 'UTF-8',
            languagelocalekey = 'en_US',
            localesidkey = 'en_GB',
            isActive = true);
        insert u1;
      system.runAs(u1){
        // Set up Account test data
        Account account = new Account(Name='TestA', RecordTypeId=brandRecordTypeId);
        insert account;
        
        // Set up Village test data
        Village__c village = new Village__c(Name='TestV', Std_Break_Clause__c = 'Test_Std_Break_Clause__c',
                                        Std_Fit_Out_days__c = 7, Default_Contract_Type__c = 'Lease',
                                        Std_Lease_Term_months__c = 12, Village_Code__c = 'TT', CertSales_CertPeriod_Cut_Off_Days__c = 1, CertSales_Report_Sales_Grace_Period_Days__c = 1 );
        insert village;
        
        //Set up Opportunity test data
        Opportunity opportunity = new Opportunity(Name='TestO', StageName = 'In discussion', 
                                        AccountId = account.Id, CloseDate=system.today()+7,
                                        Village__c = village.id);
        insert opportunity;                 
                                    
        // Set up Contact test data
        Contact contact = new Contact(FirstName = 'c1', LastName= 'Test', AccountId = account.id, email = 'test@contact.com');
        insert contact;
        
        OpportunityContactRole ocr = new OpportunityContactRole(isPrimary=true, ContactId=contact.id, OpportunityId=opportunity.Id);
        insert ocr;
        
        // lets try to add a team member
          AccountTeamMember atm1 = new AccountTeamMember(UserId = u1.Id,TeamMemberRole = 'EU Brand Captain', AccountId = account.Id);     
            insert atm1;
        
        test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(opportunity);

        OpportunityTeamMemberSync testController = new OpportunityTeamMemberSync(sc);
        
        testController.triggerUpdateOppBrandLeadNegotiator();

 OpportunityTeamMemberSync.syncAccountRecordListPersonnel(new List<Id>{account.Id});

        opportunity = [select Id, Lead_Negotiator_Brand__c
                            from Opportunity where id = :opportunity.Id];
        
        contact = [select Name from Contact where FirstName='c1' and LastName='Test'];
        
        system.assertEquals(opportunity.Lead_Negotiator_Brand__c, contact.Name);        
        
        string sUrl = testController.getPageURL();

        system.assert(sUrl.length() > 0);
        
        // Remove primary flag and check Lead_Negotiator_Brand__c value is cleared on opportunity
        ocr.IsPrimary = false;
        update ocr;
        testController.triggerUpdateOppBrandLeadNegotiator();

        opportunity = [select Id, Lead_Negotiator_Brand__c
                            from Opportunity where id = :opportunity.Id];       
        
        system.assert(string.isBlank(opportunity.Lead_Negotiator_Brand__c));
        
        // Test opportunity with no roles
        delete ocr;
        testController.triggerUpdateOppBrandLeadNegotiator();
        
        // lets also test from the accounts

        

        test.stopTest();        
        
        opportunity = [select Id, Lead_Negotiator_Brand__c
                            from Opportunity where id = :opportunity.Id];       
        
        system.assert(string.isBlank(opportunity.Lead_Negotiator_Brand__c));
        
                }

            
    }

/*
    static testMethod void testOppRole() {

  // Set up Account test data
        Account account = new Account(Name='TestA', RecordTypeId=brandRecordTypeId);
        insert account;
        
        // Set up Village test data
        Village__c village = new Village__c(Name='TestV', Std_Break_Clause__c = 'Test_Std_Break_Clause__c',
                                        Std_Fit_Out_days__c = 7, Default_Contract_Type__c = 'Lease',
                                        Std_Lease_Term_months__c = 12, Village_Code__c = 'TT');
        insert village;
        
        //Set up Opportunity test data
        Opportunity opportunity = new Opportunity(Name='TestO', StageName = 'In discussion', 
                                        AccountId = account.Id, CloseDate=system.today()+7,
                                        Village__c = village.id);
        insert opportunity;                 
                                    
        // Set up Contact test data
        Contact contact = new Contact(FirstName = 'c1', LastName= 'Test', AccountId = account.id, email = 'test@contact.com');
        insert contact;
        
        OpportunityContactRole ocr = new OpportunityContactRole(isPrimary=true, ContactId=contact.id, OpportunityId=opportunity.Id);
        insert ocr;


        syncAccountRecordPersonnel


        // sync account too
        OpportunityTeamMemberSync.syncAccountPersonnel(String.valueOf(account.Id),new List<Id>());
    }*/
}