force-app/main/default/objects/Daily_Sales_Certification_Batch__c/Daily_Sales_Certification_Batch__c.object-meta.xml
<CustomObject>
    <description>Brand Portal object that will save all records related to the certifications</description>
    <label>Daily Sales Certification Batch</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Sales Certification Batches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Certification_Batch_Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Certification_Batch_Village_Code__c</fullName>
    <description>Certification batch village code for Daily sales Certification sharing rule attribution implementation</description>
    <inlineHelpText>The village code for the village that the batch is associated to</inlineHelpText>
    <label>Certification Batch Village Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Certification_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Certification_Period_Type__c</fullName>
    <inlineHelpText>The Certification Batch period type will either be monthly or quarterly</inlineHelpText>
    <label>Certification Period Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_End_Date__c</fullName>
    <inlineHelpText>The end date for this Certification Batch</inlineHelpText>
    <label>Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Period_Name__c.field-meta.xml
<CustomField>
    <fullName>Period_Name__c</fullName>
    <inlineHelpText>The period name for the Certification Batch</inlineHelpText>
    <label>Period Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <inlineHelpText>The start date for this Certification Batch</inlineHelpText>
    <label>Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status of this Certification Batch</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Being Prepared</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Batch Complete</fullName>
            </value>
            <value>
                <fullName>Re-opened</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Village Presence</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogFile__c/LogFile__c.object-meta.xml
<CustomObject>
    <label>LogFile</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>LogFile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LogFiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogFile__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B2B Report Emails</fullName>
            </value>
            <value>
                <fullName>ETLWebService</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>custom currency field</description>
    <inlineHelpText>Enter the currency to be used for all financial leasing values to be used in this village (custom currency)</inlineHelpText>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>RMB</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/CertSales_CertPeriod_Type__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Type__c</fullName>
    <inlineHelpText>The Sales Certification Batch period type will either be monthly or quarterly</inlineHelpText>
    <label>Sales Cert Period Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CertSales_Active__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deal Pending</fullName>
            </value>
            <value>
                <fullName>Trading</fullName>
            </value>
            <value>
                <fullName>in Refit</fullName>
            </value>
            <value>
                <fullName>Exited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/CertificationProcessor.cls
public class CertificationProcessor{
    
    public static Id createCertification(String villagePresenceId){
        
        Village_Presence__c theVillagePresence = [SELECT Id, CertSales_CertPeriod_Type__c, Name, Village__r.Village_Code__c, Village__r.Currency__c
                                                  FROM Village_Presence__c
                                                  WHERE Id =: villagePresenceId];
        
        Date todayDate = system.today();
        Integer numberOfDays = Date.daysInMonth(todayDate.year(),todayDate.month());
        Date lastDayOfMonth = Date.newInstance(todayDate.year(), todayDate.month(), numberOfDays);

        Daily_Sales_Certification_Batch__c certification = new Daily_Sales_Certification_Batch__c();
        certification.Period_Start_Date__c = todayDate;
        certification.Certification_Batch_Village_Code__c = theVillagePresence.Village__r.Village_Code__c;
        certification.Status__c = 'Generated';
        certification.Village_Presence__c = theVillagePresence.Id;
        certification.CurrencyIsoCode = theVillagePresence.Village__r.Currency__c;

        if(theVillagePresence.CertSales_CertPeriod_Type__c == 'Monthly'){
            certification.Name = theVillagePresence.Name + ' - ' + todayDate.month() + '/' + todayDate.year();
            certification.Period_End_Date__c = lastDayOfMonth;
            certification.Period_Name__c = todayDate.month() + '/' + todayDate.year();
            certification.Certification_Period_Type__c = String.valueOf(theVillagePresence.CertSales_CertPeriod_Type__c);
            try{
                insert certification;
            } catch(Exception e){
                logFile__c log = new logFile__c();
                log.Body__c = 'Error on insert a new certification in CertificationProcessor class. It is related with VP Name: ' + theVillagePresence.Name + '. With the following mesage: ' + e.getMessage();
                log.Type__c = 'Insert of a new certification on the VP: ' + theVillagePresence.Name;
                insert log;
                system.debug('Exist an error on insert a new certification in CertificationProcessor class. with the following mesage: ' + e.getMessage());
            }
            return certification.Id;
        } else if (theVillagePresence.CertSales_CertPeriod_Type__c == 'Quarterly'){
            if(todayDate.month() == 1 || todayDate.month() == 2 || todayDate.month() == 3){
                certification.Name = theVillagePresence.Name + ' - Q1 - ' + todayDate.year();
                certification.Period_End_Date__c = Date.newInstance(todayDate.year(), 3, 31);
                certification.Period_Name__c = 'Q1 - ' + todayDate.year();
                certification.Certification_Period_Type__c = String.valueOf(theVillagePresence.CertSales_CertPeriod_Type__c);
                try{
                    insert certification;
                } catch(Exception e){
                    logFile__c log = new logFile__c();
                    log.Body__c = 'Error on insert a new certification in CertificationProcessor class. It is related with VP Name: ' + theVillagePresence.Name + '. With the following mesage: ' + e.getMessage();
                    log.Type__c = 'Insert of a new certification on the VP: ' + theVillagePresence.Name;
                    insert log;
                    system.debug('Exist an error on insert a new certification in CertificationProcessor class. with the following mesage: ' + e.getMessage());
                }
                return certification.Id;
            } else if (todayDate.month() == 4 || todayDate.month() == 5 || todayDate.month() == 6){
                certification.Name = theVillagePresence.Name + ' - Q2 - ' + todayDate.year();
                certification.Period_End_Date__c = Date.newInstance(todayDate.year(), 6, 30);
                certification.Period_Name__c = 'Q2 - ' + todayDate.year();
                certification.Certification_Period_Type__c = String.valueOf(theVillagePresence.CertSales_CertPeriod_Type__c);
                try{
                    insert certification;
                } catch(Exception e){
                    logFile__c log = new logFile__c();
                    log.Body__c = 'Error on insert a new certification in CertificationProcessor class. It is related with VP Name: ' + theVillagePresence.Name + '. With the following mesage: ' + e.getMessage();
                    log.Type__c = 'Insert of a new certification on the VP: ' + theVillagePresence.Name;
                    insert log;
                    system.debug('Exist an error on insert a new certification in CertificationProcessor class. with the following mesage: ' + e.getMessage());
                }
                return certification.Id;
            } else if(todayDate.month() == 7 || todayDate.month() == 8 || todayDate.month() == 9){
                certification.Name = theVillagePresence.Name + ' - Q3 - ' + todayDate.year();
                certification.Period_End_Date__c = Date.newInstance(todayDate.year(), 9, 30);
                certification.Period_Name__c = 'Q3 - ' + todayDate.year();
                certification.Certification_Period_Type__c = String.valueOf(theVillagePresence.CertSales_CertPeriod_Type__c);
                try{
                    insert certification;
                } catch(Exception e){
                    logFile__c log = new logFile__c();
                    log.Body__c = 'Error on insert a new certification in CertificationProcessor class. It is related with VP Name: ' + theVillagePresence.Name + '. With the following mesage: ' + e.getMessage();
                    log.Type__c = 'Insert of a new certification on the VP: ' + theVillagePresence.Name;
                    insert log;
                    system.debug('Exist an error on insert a new certification in CertificationProcessor class. with the following mesage: ' + e.getMessage());
                }
                return certification.Id;
            } else if(todayDate.month() == 10 || todayDate.month() == 11 || todayDate.month() == 12){
                certification.Name = theVillagePresence.Name + ' - Q4 - ' + todayDate.year();
                certification.Period_End_Date__c = Date.newInstance(todayDate.year(), 12, 31);
                certification.Period_Name__c  = 'Q4 - ' + todayDate.year();
                certification.Certification_Period_Type__c = String.valueOf(theVillagePresence.CertSales_CertPeriod_Type__c);
                try{
                    insert certification;
                } catch(Exception e){
                    logFile__c log = new logFile__c();
                    log.Body__c = 'Error on insert a new certification in CertificationProcessor class. It is related with VP Name: ' + theVillagePresence.Name + '. With the following mesage: ' + e.getMessage();
                    log.Type__c = 'Insert of a new certification on the VP: ' + theVillagePresence.Name;
                    insert log;
                    system.debug('Exist an error on insert a new certification in CertificationProcessor class. with the following mesage: ' + e.getMessage());
                }
                return certification.Id;
            }
        }
        return null;
    }
}