force-app/main/default/objects/Daily_Sales_Certification_Batch__c/Daily_Sales_Certification_Batch__c.object-meta.xml
<CustomObject>
    <description>Brand Portal object that will save all records related to the certifications</description>
    <label>Daily Sales Certification Batch</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Sales Certification Batches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_End_Date__c</fullName>
    <inlineHelpText>The end date for this Certification Batch</inlineHelpText>
    <label>Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <inlineHelpText>The start date for this Certification Batch</inlineHelpText>
    <label>Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status of this Certification Batch</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Being Prepared</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Batch Complete</fullName>
            </value>
            <value>
                <fullName>Re-opened</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Sales_Certification_Batch__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Village Presence</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deal Pending</fullName>
            </value>
            <value>
                <fullName>Trading</fullName>
            </value>
            <value>
                <fullName>in Refit</fullName>
            </value>
            <value>
                <fullName>Exited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/Village_Presence_Contact_Role__c.object-meta.xml
<CustomObject>
    <label>Village Presence Contact Role</label>
    <nameField>
        <displayFormat>VPC-{00000}</displayFormat>
        <label>Village Presence Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Village Presence Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Certification_Active__c.field-meta.xml
<CustomField>
    <fullName>Certification_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This is selected if the Village Presence Contact is authorised to certify sales within the Brand Portal</inlineHelpText>
    <label>Certification Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must be a Brand Contact</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Village Presence Contact Roles</relationshipLabel>
    <relationshipName>Village_Presence_Contact_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Village Presence</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>Village Presence Contact Roles</relationshipLabel>
    <relationshipName>Village_Presence_Contact_Roles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BP_Certification_Landing_History_Ct.cls
public class BP_Certification_Landing_History_Ct{

    @AuraEnabled
    public static List<Daily_Sales_Certification_Batch__c> getHistory(){ //Get History Certifications
        Id userID = UserInfo.getUserId();
        User theUser = [SELECT Id, ContactId FROM User WHERE ID = :userID];
        List<Village_Presence_Contact_Role__c> vpcrList = [SELECT Id, Village_Presence__c,Certification_Active__c
                                                           FROM Village_Presence_Contact_Role__c
                                                           WHERE Contact__c = :theUser.ContactId
                                                           AND Certification_Active__c= true];
        Set<Id> vpcrSet = new Set<Id>();
        
        for(Village_Presence_Contact_Role__c theVPCR : vpcrList){
            vpcrSet.add(theVPCR.Village_Presence__c);
        }
        
        List <Daily_Sales_Certification_Batch__c> outStandingList = [SELECT Period_Start_Date__c, Village_Presence__r.Name, Period_End_Date__c,Name
                                                                    FROM Daily_Sales_Certification_Batch__c
                                                                    WHERE Village_Presence__c = :vpcrSet
                                                                    AND (Status__c = 'Pending Approval' 
                                                                    OR Status__c = 'Approved'
                                                                    OR Status__c = 'Batch Complete')];
        
        return outStandingList;
    }
    
    
    
    
}