force-app/main/default/objects/Tourism_Partner_Projection__c/Tourism_Partner_Projection__c.object-meta.xml
<CustomObject>
    <description>Projected Tourism partner visit contributions</description>
    <label>Tourism Partner Projection</label>
    <nameField>
        <displayFormat>TPP-{000000}</displayFormat>
        <label>Tourism Partner Projection Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tourism Partner Projections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/Partnership_Account__c.field-meta.xml
<CustomField>
    <fullName>Partnership_Account__c</fullName>
    <description>The Tourism partner</description>
    <inlineHelpText>The Tourism partner</inlineHelpText>
    <label>Partnership Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Tourism accounts can have projections</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tourism</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tourism Partner Projections</relationshipLabel>
    <relationshipName>Tourism_Partner_Projections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/Projected_Year__c.field-meta.xml
<CustomField>
    <fullName>Projected_Year__c</fullName>
    <description>The year for which the projections are</description>
    <inlineHelpText>The year for which the projections are</inlineHelpText>
    <label>Projected Year</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
                <default>true</default>
                <label>2020</label>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
                <isActive>false</isActive>
                <label>2017</label>
            </value>
            <value>
                <fullName>2018</fullName>
                <isActive>false</isActive>
                <label>2018</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>The village that this projection is for</description>
    <inlineHelpText>The village that this projection is for</inlineHelpText>
    <label>Village</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Village</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Village.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bicester</fullName>
    </customValue>
    <customValue>
        <fullName>Fidenza</fullName>
    </customValue>
    <customValue>
        <fullName>Ingolstadt</fullName>
    </customValue>
    <customValue>
        <fullName>Kildare</fullName>
    </customValue>
    <customValue>
        <fullName>La Roca</fullName>
    </customValue>
    <customValue>
        <fullName>Las Rozas</fullName>
    </customValue>
    <customValue>
        <fullName>La Vallée</fullName>
    </customValue>
    <customValue>
        <fullName>Maasmechelen</fullName>
    </customValue>
    <customValue>
        <fullName>Shanghai</fullName>
    </customValue>
    <customValue>
        <fullName>Suzhou</fullName>
    </customValue>
    <customValue>
        <fullName>Wertheim</fullName>
    </customValue>
    <description>A list of all the villages</description>
    <masterLabel>Village</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TourismPartnerProjectionsTriggerHandler.cls
public class TourismPartnerProjectionsTriggerHandler 
{
   
     public static void processBeforeInsert( Map<Id,Tourism_Partner_Projection__c> newRecords){


        // now we can update the name from the supplied values
        // we need to build the name as "Account" + for + "Year" + for "Village"
        // eg. Kuoni International for 2017 for Bicester

        // lets get all the data..
        List<ID> acc = new List<ID>();
        System.debug('newRecords ===== '+newRecords);
          for (string key :newRecords.keySet()){
            acc.add(newRecords.get(key).Partnership_Account__c);
          }
        

        Map<ID,Account> tppaccs = new Map<ID,Account>([Select ID, Name FROM Account WHERE ID in :acc]);

        for(Tourism_Partner_Projection__c TPP :newRecords.values()){
            System.debug(TPP.Projected_Year__c);
            Account TPPAccount = tppaccs.get(TPP.Partnership_Account__c);
            String TPPName = TPPAccount.Name + ' for ' + TPP.Projected_Year__c + ' for ' + TPP.Village__c;
            //TPP.Name = TPPName;
        }

     } 

   
}