force-app/main/default/objects/b2c_customer__c/b2c_customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/b2c_customer__c/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <description>Customer email address</description>
    <inlineHelpText>Customer email address</inlineHelpText>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/b2c_customer__c/fields/firstName__c.field-meta.xml
<CustomField>
    <fullName>firstName__c</fullName>
    <description>Customer first name</description>
    <inlineHelpText>Customer first name</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/b2c_customer__c/fields/lastName__c.field-meta.xml
<CustomField>
    <fullName>lastName__c</fullName>
    <description>Customer last name</description>
    <inlineHelpText>Customer last name</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ODS_Delete_Log__c/ODS_Delete_Log__c.object-meta.xml
<CustomObject>
    <label>ODS Delete Log</label>
    <nameField>
        <displayFormat>L-{00000000}</displayFormat>
        <label>log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ODS Delete Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ODS_Delete_Log__c/fields/Deleted_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Deleted_Record_ID__c</fullName>
    <label>Deleted Record ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ODS_Delete_Log__c/fields/sObject__c.field-meta.xml
<CustomField>
    <fullName>sObject__c</fullName>
    <description>The sObject type that is being deleted</description>
    <label>sObject</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ODSDeleteHelperTest.cls
@isTest
private class ODSDeleteHelperTest {

    private static b2c_customer__c customer = new b2c_customer__c();

    private static void setupData(){
        
        User u1 = TestData_User.setupAdminUser(false);
	    u1.Username = 'vr_u1@test.com';
	    u1.Email = 'vr_u1@test.com';
	    insert u1;
	    
        system.runAs(u1){
	        customer.firstName__c = 'Eraser';
	        customer.lastName__c = 'Head';
	        customer.email__c = 'ee@head.com';
	        
	        insert customer;
        }
        
    }

    static testMethod void unitTest1() {

        setupData();
        
        string recId = customer.Id;
        
        test.startTest();
            delete customer;
        test.stopTest();
        
        list<ODS_Delete_Log__c> logList = [select Deleted_Record_ID__c, sObject__c from ODS_Delete_Log__c 
                                    where Deleted_Record_ID__c = :recId];
                                    
        system.assertEquals(logList.size(), 1);
        system.assertEquals(logList[0].Deleted_Record_ID__c, recId);
        system.assertEquals(logList[0].sObject__c, 'b2c_customer__c');                          

    }
    
    static testMethod void unitTest2() {

        setupData();
        
        string recId = customer.Id;
        // Create test admin user
        User usr = TestData_User.setupAdminUser(true);
        
        test.startTest();
            
            system.runAs(usr){
                ODSDeleteHelper.deleteCustomer(recId);
            }
            
        test.stopTest();
        
        list<ODS_Delete_Log__c> logList = [select Deleted_Record_ID__c, sObject__c from ODS_Delete_Log__c 
                                    where Deleted_Record_ID__c = :recId];
                                    
        system.assertEquals(logList.size(), 1);
        system.assertEquals(logList[0].Deleted_Record_ID__c, recId);
        system.assertEquals(logList[0].sObject__c, 'b2c_customer__c');                          

    }    
}