force-app/main/default/objects/b2c_customer__c/b2c_customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/b2c_customer__c/fields/leadSource__c.field-meta.xml
<CustomField>
    <fullName>leadSource__c</fullName>
    <description>Original touchpoint of registration</description>
    <inlineHelpText>Original touchpoint of registration</inlineHelpText>
    <label>Lead Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/b2c_customer__c/fields/primaryVillage__c.field-meta.xml
<CustomField>
    <fullName>primaryVillage__c</fullName>
    <description>Customer&apos;s primary village</description>
    <inlineHelpText>Customer&apos;s primary village</inlineHelpText>
    <label>Primary Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BV</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>FV</fullName>
            </value>
            <value>
                <fullName>IV</fullName>
            </value>
            <value>
                <fullName>KV</fullName>
            </value>
            <value>
                <fullName>LR</fullName>
            </value>
            <value>
                <fullName>LV</fullName>
            </value>
            <value>
                <fullName>LZ</fullName>
            </value>
            <value>
                <fullName>MV</fullName>
            </value>
            <value>
                <fullName>SH</fullName>
            </value>
            <value>
                <fullName>SV</fullName>
            </value>
            <value>
                <fullName>WV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>This fields is used for defaults when entering values in Custom Actions and for searching redeemable campaigns..</description>
    <inlineHelpText>Where is the user based.</inlineHelpText>
    <label>Village</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VR1_Configuration_Settings__c/VR1_Configuration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration settings for VR1</description>
    <label>VR1 Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/VR1_Configuration_Settings__c/fields/Salesforce_Instance_URL__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Instance_URL__c</fullName>
    <defaultValue>&quot;https://login.salesforce.com&quot;</defaultValue>
    <description>The base URL of the Salesforce instance. This can be referenced from external sites to provide links back the relevant Salesforce instance.</description>
    <inlineHelpText>The base URL of the Salesforce instance. This can be referenced from external sites to provide links back the relevant Salesforce instance.</inlineHelpText>
    <label>Salesforce Instance URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/B2CCustomerEntryController.cls
public with sharing class B2CCustomerEntryController {

	private b2c_customer__c customer {get; set;}
    private ApexPages.StandardController controller {get; set;}
    private boolean partnerInput = false;
    private string village;
    
    public B2CCustomerEntryController(ApexPages.StandardController controller) {

		this.controller = controller;
		initValues();

    }
	

	
	public PageReference initValues(){

		this.customer = (b2c_customer__c) controller.getRecord();

		string inputType = ApexPages.currentPage().getParameters().get('InputType'); 
		if (string.isnotBlank(inputType)){
			partnerInput = true;			
			customer.leadSource__c = inputType;					
		}
		
		if (string.isBlank(village)){
			string userId = userInfo.getUserId();
			User u = [select village__c from User where Id = :userId];
			village = u.Village__c;
			if (string.isnotBlank(village)){
				Village__c v = [select Village_Code__c from Village__c where Name = :village];
				string villageCode = v.Village_Code__c;
				customer.primaryVillage__c = villageCode;
			}
		}
		return null;		
		
	}
	
	public PageReference saveRecord(){
		
		PageReference pg = null;
		string prefix = '';
		this.customer = (b2c_customer__c) controller.getRecord();
		VR1_Configuration_Settings__c orgSettings = VR1_Configuration_Settings__c.getOrgDefaults();
		string homeUrl = orgSettings.Salesforce_Instance_URL__c;		
				
		try {
		
			//pg = controller.save();			
			insert customer;
 			Schema.DescribeSObjectResult objectSchema = Schema.getGlobalDescribe().get('b2c_customer__c').getDescribe();
        	prefix = objectSchema.getKeyPrefix();
        	pg = new PageReference(homeUrl + '/' + prefix + '/o');	
			
		} catch (exception e){
			
			string errMsg = e.getMessage();
			
			if (errMsg.indexOf('duplicate value found') > -1){				
				integer pos1 = errMsg.lastIndexOf('id:');
				integer pos2 = errMsg.lastIndexOf(':');				
				string dupeId = errMsg.substring(pos1 + 4 , pos2);
		
				errMsg = 'This email address is already registered. Please enter a different email address or <a href="' + homeUrl + '/' + dupeId +'">click here</a> to view the existing customer.';				
				pg = null;
			} else {
				
				errMsg = 'A technical error has occurred, record could not be saved. ' + e.getMessage();
				
			}
			
			ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, errMsg));
			
		}
		
		return pg;
		
	}

}