force-app/main/default/objects/HFS_Job__c/HFS_Job__c.object-meta.xml
<CustomObject>
    <description>A junction object between User and Case_Item__c that will record all of the jobs of HFS Experiences.</description>
    <label>HFS Job</label>
    <nameField>
        <displayFormat>J-{00000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Job__c/fields/Assigned_to_me__c.field-meta.xml
<CustomField>
    <fullName>Assigned_to_me__c</fullName>
    <formula>IF(HFS_Runner__r.User__c = $User.Id, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned to me</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HFS_Job__c/fields/HFS_Runner__c.field-meta.xml
<CustomField>
    <fullName>HFS_Runner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFS Runner</label>
    <referenceTo>HFS_Runner__c</referenceTo>
    <relationshipLabel>HFS Jobs</relationshipLabel>
    <relationshipName>HFS_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Job__c/fields/Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Status__c</fullName>
    <description>It is for collect the status of the job through the collection of bags, since the decisions taken by Runners and Co-ordinators.</description>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Not Accepted</label>
            </value>
            <value>
                <fullName>Delivering</fullName>
            </value>
            <value>
                <fullName>Bags Putaway</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HFS_Job__c/fields/Reject_Job__c.field-meta.xml
<CustomField>
    <fullName>Reject_Job__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reject Job</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HFS_Job__c/fields/Rejected_By__c.field-meta.xml
<CustomField>
    <fullName>Rejected_By__c</fullName>
    <label>Rejected By</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_Job__c/fields/Take_job_for_me__c.field-meta.xml
<CustomField>
    <fullName>Take_job_for_me__c</fullName>
    <defaultValue>false</defaultValue>
    <label>I want the Job</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HFS_Runner__c/HFS_Runner__c.object-meta.xml
<CustomObject>
    <label>HFS Runner</label>
    <nameField>
        <label>HFS Runner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HFS Runners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Runner__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>It should be a a HFS Runner</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>HFS Runner</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>HFS VR Assistant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>HFS_Runners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HFSJobTriggerHandler.cls
public with sharing class HFSJobTriggerHandler{
	
	public static void runnerChangeStatus(List<HFS_Job__c> oldEditedJobs, List<HFS_Job__c> newEditedJobs){

		Id runnerId = UserInfo.getUserId();
		Id profileId = UserInfo.getProfileId();
		Profile profile = [SELECT Id, Name FROM Profile WHERE Id =: profileId];
		List<HFS_Runner__c> allhfsRunner = [SELECT Id, Name, User__c FROM HFS_Runner__c];
		
		for(HFS_Runner__c hfsRunner : allhfsRunner){
			if(hfsRunner.User__c == runnerId){
				for(HFS_Job__c oneOldJob : oldEditedJobs){			
					for(HFS_Job__c oneNewJob : newEditedJobs){
						if(oneOldJob.Take_job_for_me__c == false && oneNewJob.Take_job_for_me__c == true){
							oneNewJob.HFS_Runner__c = hfsRunner.Id;
							oneNewJob.Job_Status__c = 'Accepted';
						} else if(oneOldJob.Assigned_to_me__c == false && profile.Name == 'HFS Runner'){
							oneNewJob.addError('This job is already assigned to another runner');
						}

						if(oneOldJob.Reject_Job__c == false && oneNewJob.Reject_Job__c == true){
							oneNewJob.Job_Status__c = 'Rejected';
							oneNewJob.Rejected_By__c = hfsRunner.Name;
							oneNewJob.HFS_Runner__c = null;
							oneNewJob.Take_job_for_me__c = false;
						}
					}
				}
			}
		}
	}
}