force-app/main/default/objects/Global_Properties__c/Global_Properties__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Global Properties Key Value pairs</description>
    <label>Global Properties</label>
</CustomObject>

force-app/main/default/objects/Global_Properties__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The value for this setting.</description>
    <inlineHelpText>The value for this configuration setting.</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/HFS_Bags_Left__c.field-meta.xml
<CustomField>
    <fullName>HFS_Bags_Left__c</fullName>
    <formula>HFS_Bags_Received__c -  HFS_Bags_Used__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>#HFS Bags Left</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/HFS_Bags_Received__c.field-meta.xml
<CustomField>
    <fullName>HFS_Bags_Received__c</fullName>
    <defaultValue>0</defaultValue>
    <label># HFS Bags Received</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/HFS_Bags_Used__c.field-meta.xml
<CustomField>
    <fullName>HFS_Bags_Used__c</fullName>
    <defaultValue>0</defaultValue>
    <label>#HFS Bags Used</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/HFS_Threshold__c.field-meta.xml
<CustomField>
    <fullName>HFS_Threshold__c</fullName>
    <defaultValue>0</defaultValue>
    <label>HFS Threshold</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Is_HFS_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_HFS_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in the HFSDash screen to select the correct VPs</description>
    <inlineHelpText>to Enable view on the HFSDash screen in the TIC</inlineHelpText>
    <label>Is HFS Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Replenish__c.field-meta.xml
<CustomField>
    <fullName>Replenish__c</fullName>
    <formula>HFS_Bags_Left__c &lt;=  HFS_Threshold__c</formula>
    <label>Replenish?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/HFSReplenishmentDailyJob.cls
Global Class HFSReplenishmentDailyJob implements Schedulable, Database.Batchable<sObject> {

    /*BATCH EXECUTION*/
    
    global List<Village_Presence__c> start (Database.BatchableContext BC) {
        return [SELECT id, Name,HFS_Bags_Left__c ,HFS_Bags_Received__c,HFS_Bags_Used__c,HFS_Threshold__c, Replenish__c FROM Village_Presence__c WHERE Is_HFS_Active__c = true ORDER BY Village__c];
    }

    global void execute (Database.BatchableContext BC, List<Village_Presence__c> vps) {
        
        for(Village_Presence__c vp : vps){
            vp.HFS_Bags_Received__c = vp.HFS_Bags_Left__c;
            vp.HFS_Bags_Used__c = 0;          
        }
        update vps;        
    }

    global void finish (Database.BatchableContext BC) {

    }

    /*SCHEDULABLE EXECUTION*/
    global void execute(SchedulableContext sch) {

 	    Database.executebatch(new HFSReplenishmentDailyJob(),Integer.valueOf(Global_Properties__c.getInstance('REPLENISHMENT_BAG_JOB_SIZE').Value__c));
       
   }
}