force-app/main/default/objects/Global_Properties__c/Global_Properties__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Global Properties Key Value pairs</description>
    <label>Global Properties</label>
</CustomObject>

force-app/main/default/objects/Global_Properties__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The value for this setting.</description>
    <inlineHelpText>The value for this configuration setting.</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Village Presence records must be linked to Brand accounts. Please ensure you are not linking the Deal/Village Presence to a Group</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/HFS_Bags_Received__c.field-meta.xml
<CustomField>
    <fullName>HFS_Bags_Received__c</fullName>
    <defaultValue>0</defaultValue>
    <label># HFS Bags Received</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/HFS_Bags_Used__c.field-meta.xml
<CustomField>
    <fullName>HFS_Bags_Used__c</fullName>
    <defaultValue>0</defaultValue>
    <label>#HFS Bags Used</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Is_HFS_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_HFS_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in the HFSDash screen to select the correct VPs</description>
    <inlineHelpText>to Enable view on the HFSDash screen in the TIC</inlineHelpText>
    <label>Is HFS Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/HFSReplenishmentDailyJobTest.cls
@isTest
public class HFSReplenishmentDailyJobTest {

    static testmethod void testBatchExecution() {
        
        Village__c village = new Village__c();
 		village.Name = 'TestVillage1'; 		
 		village.Village_Code__c = 'AA';
		village.CertSales_CertPeriod_Cut_Off_Days__c = 1;
        village.CertSales_Report_Sales_Grace_Period_Days__c = 1;
        insert village;
         
        Account brand1 = TestData_Account.setupBrandAccount(1, true);
        Account brand2 = TestData_Account.setupBrandAccount(2, true);

        Village_Presence__c vp1 = new Village_Presence__c (Brand__c = brand1.Id, Village__c = village.Id, HFS_Bags_Used__c = 5, HFS_Bags_Received__c = 15, Is_HFS_Active__c=true);
        Village_Presence__c vp2 = new Village_Presence__c (Brand__c = brand2.Id, Village__c = village.Id, HFS_Bags_Used__c = 2, HFS_Bags_Received__c = 20, Is_HFS_Active__c=true);

        insert new List <Village_Presence__c> {vp1, vp2};

        Map <Id, Decimal> vpMap = new Map <Id, Decimal> {vp1.Id => 10, vp2.Id => 18};
        
        Global_Properties__c gp = new Global_Properties__c (Name='REPLENISHMENT_BAG_JOB_SIZE', Value__c='30');
        insert gp;

        Test.startTest();

        HFSReplenishmentDailyJob scheduler = new HFSReplenishmentDailyJob();
        scheduler.execute(null);

        Test.stopTest();

        for (Village_Presence__c vp : [SELECT Id, HFS_Bags_Used__c, HFS_Bags_Received__c FROM Village_Presence__c]) {
            system.assertEquals(0, vp.HFS_Bags_Used__c);
            system.assertEquals(vpMap.get(vp.Id), vp.HFS_Bags_Received__c);
        }

        
    }

}