force-app/main/default/objects/Case_Item__c/Case_Item__c.object-meta.xml
<CustomObject>
    <description>a specific sub item under the case object</description>
    <label>HFS Purchase</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>HFS Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Purchases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Item__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>the start time</description>
    <inlineHelpText>the start time</inlineHelpText>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>the status of the item....</description>
    <inlineHelpText>the status of the item</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Pick-up from Brand</fullName>
            </value>
            <value>
                <fullName>In transit</fullName>
            </value>
            <value>
                <fullName>Ready for Guest Collection</fullName>
            </value>
            <value>
                <fullName>Guest Collected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/HFS_Bag__c.object-meta.xml
<CustomObject>
    <description>This object save the information of the Bags</description>
    <label>HFS Bag</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Bag Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Bags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Bag__c/fields/Barcode__c.field-meta.xml
<CustomField>
    <fullName>Barcode__c</fullName>
    <description>This is the visible numbers present on the Barcode</description>
    <inlineHelpText>Visible Barcode numbers</inlineHelpText>
    <label>Barcode</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/Guest_ID_Code__c.field-meta.xml
<CustomField>
    <fullName>Guest_ID_Code__c</fullName>
    <formula>HFS_Purchase__r.Case__r.Service_Guest_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Guest ID Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/HFS_Job__c.field-meta.xml
<CustomField>
    <fullName>HFS_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFS Job</label>
    <referenceTo>HFS_Job__c</referenceTo>
    <relationshipLabel>HFS Bags</relationshipLabel>
    <relationshipName>HFS_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/HFS_Purchase__c.field-meta.xml
<CustomField>
    <fullName>HFS_Purchase__c</fullName>
    <description>This field is a master detail relationship with the purpose of getting the information of the corresponding HFS Case Item.</description>
    <label>HFS Purchase</label>
    <referenceTo>Case_Item__c</referenceTo>
    <relationshipLabel>HFS Bags</relationshipLabel>
    <relationshipName>HFS_Bags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/HFS_Runner__c.field-meta.xml
<CustomField>
    <fullName>HFS_Runner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFS Runner</label>
    <referenceTo>HFS_Runner__c</referenceTo>
    <relationshipLabel>HFS Bags</relationshipLabel>
    <relationshipName>HFS_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/HFS_Storage_Location__c.field-meta.xml
<CustomField>
    <fullName>HFS_Storage_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFS Storage Location</label>
    <referenceTo>HFS_Storage_Location__c</referenceTo>
    <relationshipLabel>HFS Bags</relationshipLabel>
    <relationshipName>HFS_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/In_Storage_Point__c.field-meta.xml
<CustomField>
    <fullName>In_Storage_Point__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In Storage Point</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/Scanned__c.field-meta.xml
<CustomField>
    <fullName>Scanned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scanned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Pick-up</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Putaway</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Bag Dropped</fullName>
            </value>
            <value>
                <fullName>Bag with GSA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/Storage_Matches_Guest_Collection_Point__c.field-meta.xml
<CustomField>
    <fullName>Storage_Matches_Guest_Collection_Point__c</fullName>
    <description>Indicator to show if bag is in wrong storage location...</description>
    <formula>OR(CONTAINS( HFS_Storage_Location__r.HFS_Storage_Point__r.For_Collection_Point__c , HFS_Purchase__r.Case__r.HFS_Collection_Location__c) ,  ISPICKVAL(Status__c,&apos;Bag with GSA&apos;)) 

/*HFS_Storage_Location__r.HFS_Storage_Point__r.For_Collection_Point__c =  HFS_Purchase__r.Case__r.HFS_Collection_Location__c*/</formula>
    <label>Storage Matches Guest Collection Point</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HFS_Job__c/HFS_Job__c.object-meta.xml
<CustomObject>
    <description>A junction object between User and Case_Item__c that will record all of the jobs of HFS Experiences.</description>
    <label>HFS Job</label>
    <nameField>
        <displayFormat>J-{00000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Job__c/fields/Assigned_to_me__c.field-meta.xml
<CustomField>
    <fullName>Assigned_to_me__c</fullName>
    <formula>IF(HFS_Runner__r.User__c = $User.Id, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned to me</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HFS_Job__c/fields/HFS_Guest_Collection_Point__c.field-meta.xml
<CustomField>
    <fullName>HFS_Guest_Collection_Point__c</fullName>
    <formula>HFS_Purchase__r.Case__r.HFS_Collection_Location__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HFS Guest Collection Point</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_Job__c/fields/HFS_Purchase__c.field-meta.xml
<CustomField>
    <fullName>HFS_Purchase__c</fullName>
    <description>Master detail relationship to Case_Item__c</description>
    <label>HFS Purchase</label>
    <referenceTo>Case_Item__c</referenceTo>
    <relationshipLabel>HFS Jobs</relationshipLabel>
    <relationshipName>HFS_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/HFS_Job__c/fields/HFS_Runner__c.field-meta.xml
<CustomField>
    <fullName>HFS_Runner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFS Runner</label>
    <referenceTo>HFS_Runner__c</referenceTo>
    <relationshipLabel>HFS Jobs</relationshipLabel>
    <relationshipName>HFS_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Job__c/fields/Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Status__c</fullName>
    <description>It is for collect the status of the job through the collection of bags, since the decisions taken by Runners and Co-ordinators.</description>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Not Accepted</label>
            </value>
            <value>
                <fullName>Delivering</fullName>
            </value>
            <value>
                <fullName>Bags Putaway</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HFS_Runner__c/HFS_Runner__c.object-meta.xml
<CustomObject>
    <label>HFS Runner</label>
    <nameField>
        <label>HFS Runner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HFS Runners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Storage_Location__c/HFS_Storage_Location__c.object-meta.xml
<CustomObject>
    <description>This object will save all information related to the Storage Locations.</description>
    <label>HFS Storage Location</label>
    <nameField>
        <label>Storage Location Unique Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HFS Storage Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Storage_Location__c/fields/HFS_Storage_Point__c.field-meta.xml
<CustomField>
    <fullName>HFS_Storage_Point__c</fullName>
    <label>HFS Storage Point</label>
    <referenceTo>HFS_Storage_Point__c</referenceTo>
    <relationshipLabel>HFS Storage Locations</relationshipLabel>
    <relationshipName>HFS_Storage_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HFS_Storage_Location__c/fields/QR_Code_hidden__c.field-meta.xml
<CustomField>
    <fullName>QR_Code_hidden__c</fullName>
    <label>QR Code hidden</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_Storage_Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Empty</fullName>
                <default>true</default>
                <label>Empty</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HFS_Storage_Point__c/HFS_Storage_Point__c.object-meta.xml
<CustomObject>
    <label>HFS Storage Point</label>
    <nameField>
        <label>HFS Storage Point Unique Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HFS Storage Points</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/HFSQuickBagPutawayController.cls
public with sharing class HFSQuickBagPutawayController {

  public List<HFS_Bag__c> allJobBags { get; set; }
  public List<HFS_Bag__c> theBag { get; set; }
  public Map<String, Integer> allBagStorage { get; set; }
  public Id jobId { get; set; }
  public string bagId { get; set; }
  public String qrCodeLocation { get; set; }
  public String getLocationName { get; set; }
  public String getLocationId { get; set; }
  public String barcodeBag { get; set; }
  public Boolean stopLoopBags { get; set; }
  public Boolean displayPopUp { get; set; }
  public Boolean differentLocations{get;set;}
  public Integer countAllJobBagsInStorage { get; set; }
  public Integer count { get; set; }
  public HFS_Job__c CurrentJob {get;set;}
  public String currentStoragePoint{get;set;}
  public String guestCollectionPoint{get;set;}
  public Boolean VarConfPutaway {get;set;}
  public HFS_Job__c getAvailableJob;
    
    
  public HFSQuickBagPutawayController() {

    bagId = ApexPages.CurrentPage().getParameters().get('bagId');
    qrCodeLocation = ApexPages.CurrentPage().getParameters().get('qrCodeLocation');
    getLocationId = ApexPages.CurrentPage().getParameters().get('StorageLocation');
    barcodeBag = ApexPages.CurrentPage().getParameters().get('barcodeBag');
    system.debug('getLocationId cont ' + getLocationId );
    
    theBag = [SELECT id, name,HFS_Job__c,HFS_Runner__c FROM HFS_Bag__c WHERE Barcode__c =: bagId AND In_Storage_Point__c = false AND HFS_Purchase__r.Start_Time__c = TODAY];
    system.debug('theBag cont ' + theBag );
      if(theBag.size() > 0 && theBag != NULL){
        
        if(theBag[0].HFS_Runner__c == NULL){
          Apexpages.Message errorMessage = new Apexpages.Message(Apexpages.Severity.Error, 'This bag\'s Job needs to be assigned to a runner before it can be \"Quick Putaway\" ');
          Apexpages.addMessage(errorMessage);        
        }
        else{  
          CurrentJob = [SELECT Id,name,HFS_Guest_Collection_Point__c,Guest_ID_Code__c, Assigned_to_me__c FROM HFS_Job__c WHERE Id =: theBag[0].HFS_Job__c];
          system.debug('CurrentJob ' + CurrentJob );
          if(CurrentJob != NULL){
            
          jobId = theBag[0].HFS_Job__c;    
          system.debug('jobId ' + jobId );
        
          allBagStorage = getAllStorage(jobId);
        
          allJobBags = [SELECT Id, Name, In_Storage_Point__c, HFS_Runner__c, Barcode__c FROM HFS_Bag__c WHERE HFS_Job__c =: jobId AND Barcode__c =: bagId ];
          system.debug('alljobBags construcotr --- ' + alljobBags);
          
          List<HFS_Bag__c> allPurchaseBags = [SELECT Id, Guest_ID_Code__c, HFS_Storage_Location__c, HFS_Storage_Location__r.Name FROM HFS_Bag__c WHERE Guest_ID_Code__c =: CurrentJob.Guest_ID_Code__c AND HFS_Purchase__r.Start_Time__c = TODAY];
      
            if(qrCodeLocation == null && getLocationId == null){
              for(HFS_Bag__c eachBag : allPurchaseBags){
                if(eachBag.HFS_Storage_Location__c != null){
                  getLocationName = eachBag.HFS_Storage_Location__r.Name;
                  getLocationId = eachBag.HFS_Storage_Location__c;
                }
              }
            }
          
          initialActionStorageLocation();
            
          }
        }
  
      }
      else{
        Apexpages.Message errorMessage = new Apexpages.Message(Apexpages.Severity.Error, 'This bag is either already checked in or is not valid for todays experiences');
        Apexpages.addMessage(errorMessage);      
      }
    
    }

  public void initialActionStorageLocation(){
      List<HFS_Storage_Location__c> storageLocation = [SELECT Id, Name, QR_Code_hidden__c, HFS_Storage_Point__r.Name FROM HFS_Storage_Location__c];
      system.debug('storageLocation ' + storageLocation );
      //Apexpages.Message informAssignStorageLocation = new Apexpages.Message(Apexpages.Severity.Error, 'You need to Assign a Storage Location');

      system.debug(getLocationId);
    if(jobId != null && qrCodeLocation != null){
        for(HFS_Storage_Location__c correspondentSL : storageLocation){
          if(correspondentSL.QR_Code_hidden__c == qrCodeLocation){
            getLocationName = correspondentSL.Name;
            Apexpages.Message informLocation = new Apexpages.Message(Apexpages.Severity.Info, 'At this point you can put the bags on: ' + getLocationName + ' without scanning Storage Location. Now Scan the Bag');
          Apexpages.addMessage(informLocation);
            currentStoragePoint = correspondentSL.HFS_Storage_Point__r.Name;
            guestCollectionPoint = CurrentJob.HFS_Guest_Collection_Point__c;
            if(!currentStoragePoint.equals(guestCollectionPoint)){
              differentLocations = true;
          }
            getLocationId = correspondentSL.Id;
          }
        }
      } else if(getLocationId != null){
        for(HFS_Storage_Location__c correspondentSL : storageLocation){
          if(correspondentSL.Id == getLocationId){
            getLocationName = correspondentSL.Name;
          }
        }
      }
  }



    public PageReference scanLocationCode(){    
      PageReference goToBQrcodeScan = new PageReference('/apex/HFSQuickDeliveryPageScanStorage?Id=' + jobId + '&bagId=' + bagId);
        return goToBQrcodeScan;
    }

    public PageReference scanBagsCode(){
      PageReference goToBarcodeScan = new PageReference('/apex/HFSQuickDeliveryPageScanBags?Id=' + jobId + '&StorageLocation=' + getLocationId);
      return goToBarcodeScan;
    }


 //-----------------------------------------------------------------------

  public PageReference updateRecords(){
    Apexpages.Message informBagNotMatch = new Apexpages.Message(Apexpages.Severity.Error, 'This is bag ' + barcodeBag + ' does not correspond to this Job.');
    stopLoopBags = true;
    countAllJobBagsInStorage = 0;
    List<HFS_Bag__c> updatedBag = new List<HFS_Bag__c>();

    if(barcodeBag != null && getLocationId != null){
      system.debug('barcode & locationid -- ' + barcodeBag + ' ---- ' + getLocationId + ' ---- ' + allJobBags );
      for(HFS_Bag__c bag : allJobBags){
        if(stopLoopBags){
          if(bag.Barcode__c == barcodeBag){
            bag.In_Storage_Point__c = true;
            bag.HFS_Storage_Location__c = getLocationId;
            bag.Scanned__c = false;
            bag.Status__c = 'Putaway';
            updatedBag.add(bag);
            stopLoopBags = false;
          }
        }
        if(bag.In_Storage_Point__c == true){
          countAllJobBagsInStorage ++;
        }
      }
      update updatedBag;

      if(stopLoopBags == true){
        ApexPages.addMessage(informBagNotMatch);
      }
      
      
      list<HFS_Bag__c> alltheJobBags = [SELECT Id, Name, In_Storage_Point__c, HFS_Runner__c, Barcode__c FROM HFS_Bag__c WHERE HFS_Job__c =: jobId];
      list<HFS_Bag__c> BagsinStorage = new list<HFS_Bag__c>();
      for(HFS_Bag__c bag : alltheJobBags ){
        if(bag.In_Storage_Point__c){
          BagsinStorage.add(bag);
        }
      }
      
      if(alltheJobBags.size() == BagsinStorage.size()){
        HFS_Job__c getCurrentJob = [SELECT Id, HFS_Purchase__c, HFS_Purchase__r.Status__c, Job_Status__c, HFS_Guest_Collection_Point__c FROM HFS_Job__c WHERE Id=: jobId];
        RecordType Delivered_JobsRT = [SELECT Id, Name FROM RecordType WHERE sObjectType = 'HFS_Job__c' AND Name = 'Delivered Jobs' ];
        getCurrentJob.Job_Status__c = 'Bags Putaway';
        getCurrentJob.HFS_Purchase__r.Status__c = 'Ready for Guest Collection';
        getCurrentJob.recordtypeid = Delivered_JobsRT.id;  
        update getCurrentJob.HFS_Purchase__r;
        update getCurrentJob;
                VarConfPutaway = true;
        //return null;
         
        PageReference goToScan = new PageReference('/apex/QuickBagPutawayScan');
        return goToScan;
            
      }
      
      PageReference goToScan = new PageReference('/apex/QuickBagPutawayScan');
    return goToScan;   
      
    }

    //allBagStorage = getAllStorage(jobId);  
    return null;
  }


 //-----------------------------------------------------------------------


  public Map<String, Integer> getAllStorage(ID jobId){
    allBagStorage = new Map<String, Integer>();
    HFS_Job__c getCurrentJob = [SELECT Id, HFS_Purchase__c, Job_Status__c, HFS_Guest_Collection_Point__c, Guest_ID_Code__c FROM HFS_Job__c WHERE Id=: jobId];

    set<HFS_Bag__c> allstorage = new Set<HFS_Bag__c>([SELECT Id, HFS_Storage_Location__c, HFS_Storage_Location__r.Name FROM HFS_Bag__c WHERE Guest_ID_Code__c =: CurrentJob.Guest_ID_Code__c AND HFS_Purchase__r.Start_Time__c = TODAY AND HFS_Storage_Location__c != NULL AND Storage_Matches_Guest_Collection_Point__c = true ]);
    system.debug('all storage ' + allstorage );

    Map<String, Integer> storageLocationName = new Map<String, Integer>();

    count = 0;

    if(!allstorage.isEmpty()){
      for(HFS_Bag__c aBag : allstorage){
        if(storageLocationName.containsKey(aBag.HFS_Storage_Location__r.Name)){
          count = storageLocationName.get(aBag.HFS_Storage_Location__r.Name) + 1;
          storageLocationName.put(aBag.HFS_Storage_Location__r.Name, count);
        } else {
        storageLocationName.put(aBag.HFS_Storage_Location__r.Name,1);
        }
      }
    }
    
    return storageLocationName;
  }

  public PageReference resetLocation(){
   // PageReference detailPage = new PageReference('/' + getCurrentJob.Id);
    return null;
  }


  public PageReference CurrentJob(){      
        ListView currentList = [SELECT Id FROM ListView WHERE DeveloperName = 'My_Current_Jobs' AND SobjectType = 'HFS_Job__c'];   
        PageReference goToCurrentJob = new PageReference('/a1L?fcf=' + currentList.Id);
        return goToCurrentJob;
    }
}