force-app/main/default/objects/Case_Item__c/Case_Item__c.object-meta.xml
<CustomObject>
    <description>a specific sub item under the case object</description>
    <label>HFS Purchase</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>HFS Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Purchases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Item__c/fields/Service_Guest_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Guest_Number__c</fullName>
    <formula>Case__r.Service_Guest_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Guest Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/HFS_Bag__c.object-meta.xml
<CustomObject>
    <description>This object save the information of the Bags</description>
    <label>HFS Bag</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Bag Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Bags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Bag__c/fields/Barcode__c.field-meta.xml
<CustomField>
    <fullName>Barcode__c</fullName>
    <description>This is the visible numbers present on the Barcode</description>
    <inlineHelpText>Visible Barcode numbers</inlineHelpText>
    <label>Barcode</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/HFS_Bag_Active__c.field-meta.xml
<CustomField>
    <fullName>HFS_Bag_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Bag Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/HFS_Purchase__c.field-meta.xml
<CustomField>
    <fullName>HFS_Purchase__c</fullName>
    <description>This field is a master detail relationship with the purpose of getting the information of the corresponding HFS Case Item.</description>
    <label>HFS Purchase</label>
    <referenceTo>Case_Item__c</referenceTo>
    <relationshipLabel>HFS Bags</relationshipLabel>
    <relationshipName>HFS_Bags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/HFS_Remove_Reason__c.field-meta.xml
<CustomField>
    <fullName>HFS_Remove_Reason__c</fullName>
    <label>Remove Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Guest request</fullName>
            </value>
            <value>
                <fullName>Brand Error</fullName>
            </value>
            <value>
                <fullName>VR error</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HFSRemoveBagController.cls
public with sharing class HFSRemoveBagController {
    
    public ID purchaseId {get;set;}
    public List<Case_Item__c> allJobBags { get; set; }
    public String idName {get;set;}
    public String guestId {get;set;}
    public HFS_Bag__c aBag { get; set; }
    
    public List<SelectOption> categories {get;set;}
    public String selectedBag{get;set;}
    
    
    public HFSRemoveBagController(ApexPages.StandardSetController stdController){
        this.aBag = (HFS_Bag__c)stdController.getRecord();
        purchaseId = ApexPages.CurrentPage().getParameters().get('Id'); 
        getPurchase(purchaseId); 
        getBags();
        
    }
    
    public void getPurchase(Id pId){
        allJobBags = [SELECT Name, Service_Guest_Number__c FROM Case_Item__c WHERE Id= :pId];
        idName = allJobBags[0].Name;
        guestId = allJobBags[0].Service_Guest_Number__c;
        
    }
    
    
    public void getBags(){    	
        
        List <HFS_Bag__c>  bags= [SELECT Barcode__c,HFS_Bag_Active__c,HFS_Purchase__c FROM HFS_Bag__c WHERE HFS_Purchase__r.Name= :idName AND HFS_Bag_Active__c = true];
        
        categories = new List<SelectOption>();
        categories.add(new SelectOption('', '--None--'));
        
        for(HFS_Bag__c c :bags){
            categories.add(new SelectOption(c.Barcode__c, c.Barcode__c));
        }
        
    }
    
    
    public PageReference RemoveBag(){
        
        System.debug(' Mala ' + selectedBag);
        
        try{
            
            HFS_Bag__c  bag =  [SELECT Barcode__c,HFS_Bag_Active__c,HFS_Purchase__c FROM HFS_Bag__c WHERE HFS_Purchase__c= :purchaseId AND Barcode__c= :selectedBag AND HFS_Bag_Active__c = true];
            
            bag.HFS_Bag_Active__c = false;
            bag.HFS_Remove_Reason__c = aBag.HFS_Remove_Reason__c;
            update bag;
            
            System.debug(' Mala ' + selectedBag);
            PageReference purchasePage = new PageReference('/' + purchaseId);
            return purchasePage;
            
            
        }
        catch(Exception ex){
            Apexpages.Message informNotProceed = new Apexpages.Message(Apexpages.Severity.Error, 'Not able to remove, duplicated barcode');
            ApexPages.addMessage(informNotProceed);
            return null;
        }
        
        
    }
    
    
    
    public PageReference cancel(){
        PageReference purchasePage = new PageReference('/' + purchaseId);    
        return purchasePage;
    }
    
    
}