force-app/main/default/objects/Case_Item__c/Case_Item__c.object-meta.xml
<CustomObject>
    <description>a specific sub item under the case object</description>
    <label>HFS Purchase</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>HFS Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Purchases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Item__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>the start time</description>
    <inlineHelpText>the start time</inlineHelpText>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>the status of the item....</description>
    <inlineHelpText>the status of the item</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Pick-up from Brand</fullName>
            </value>
            <value>
                <fullName>In transit</fullName>
            </value>
            <value>
                <fullName>Ready for Guest Collection</fullName>
            </value>
            <value>
                <fullName>Guest Collected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/HFS_Bag__c.object-meta.xml
<CustomObject>
    <description>This object save the information of the Bags</description>
    <label>HFS Bag</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Bag Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Bags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Bag__c/fields/Barcode__c.field-meta.xml
<CustomField>
    <fullName>Barcode__c</fullName>
    <description>This is the visible numbers present on the Barcode</description>
    <inlineHelpText>Visible Barcode numbers</inlineHelpText>
    <label>Barcode</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/Guest_ID_Code__c.field-meta.xml
<CustomField>
    <fullName>Guest_ID_Code__c</fullName>
    <formula>HFS_Purchase__r.Case__r.Service_Guest_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Guest ID Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/HFS_Job__c.field-meta.xml
<CustomField>
    <fullName>HFS_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFS Job</label>
    <referenceTo>HFS_Job__c</referenceTo>
    <relationshipLabel>HFS Bags</relationshipLabel>
    <relationshipName>HFS_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/HFS_Purchase__c.field-meta.xml
<CustomField>
    <fullName>HFS_Purchase__c</fullName>
    <description>This field is a master detail relationship with the purpose of getting the information of the corresponding HFS Case Item.</description>
    <label>HFS Purchase</label>
    <referenceTo>Case_Item__c</referenceTo>
    <relationshipLabel>HFS Bags</relationshipLabel>
    <relationshipName>HFS_Bags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/HFS_Runner__c.field-meta.xml
<CustomField>
    <fullName>HFS_Runner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFS Runner</label>
    <referenceTo>HFS_Runner__c</referenceTo>
    <relationshipLabel>HFS Bags</relationshipLabel>
    <relationshipName>HFS_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/HFS_Storage_Location__c.field-meta.xml
<CustomField>
    <fullName>HFS_Storage_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFS Storage Location</label>
    <referenceTo>HFS_Storage_Location__c</referenceTo>
    <relationshipLabel>HFS Bags</relationshipLabel>
    <relationshipName>HFS_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/In_Storage_Point__c.field-meta.xml
<CustomField>
    <fullName>In_Storage_Point__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In Storage Point</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/Scanned__c.field-meta.xml
<CustomField>
    <fullName>Scanned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scanned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Pick-up</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Putaway</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Bag Dropped</fullName>
            </value>
            <value>
                <fullName>Bag with GSA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HFS_Bag__c/fields/Storage_Matches_Guest_Collection_Point__c.field-meta.xml
<CustomField>
    <fullName>Storage_Matches_Guest_Collection_Point__c</fullName>
    <description>Indicator to show if bag is in wrong storage location...</description>
    <formula>OR(CONTAINS( HFS_Storage_Location__r.HFS_Storage_Point__r.For_Collection_Point__c , HFS_Purchase__r.Case__r.HFS_Collection_Location__c) ,  ISPICKVAL(Status__c,&apos;Bag with GSA&apos;)) 

/*HFS_Storage_Location__r.HFS_Storage_Point__r.For_Collection_Point__c =  HFS_Purchase__r.Case__r.HFS_Collection_Location__c*/</formula>
    <label>Storage Matches Guest Collection Point</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HFS_Job__c/HFS_Job__c.object-meta.xml
<CustomObject>
    <description>A junction object between User and Case_Item__c that will record all of the jobs of HFS Experiences.</description>
    <label>HFS Job</label>
    <nameField>
        <displayFormat>J-{00000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HFS Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Job__c/fields/Assigned_to_me__c.field-meta.xml
<CustomField>
    <fullName>Assigned_to_me__c</fullName>
    <formula>IF(HFS_Runner__r.User__c = $User.Id, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned to me</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HFS_Job__c/fields/HFS_Guest_Collection_Point__c.field-meta.xml
<CustomField>
    <fullName>HFS_Guest_Collection_Point__c</fullName>
    <formula>HFS_Purchase__r.Case__r.HFS_Collection_Location__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HFS Guest Collection Point</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_Job__c/fields/HFS_Purchase__c.field-meta.xml
<CustomField>
    <fullName>HFS_Purchase__c</fullName>
    <description>Master detail relationship to Case_Item__c</description>
    <label>HFS Purchase</label>
    <referenceTo>Case_Item__c</referenceTo>
    <relationshipLabel>HFS Jobs</relationshipLabel>
    <relationshipName>HFS_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/HFS_Job__c/fields/HFS_Runner__c.field-meta.xml
<CustomField>
    <fullName>HFS_Runner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFS Runner</label>
    <referenceTo>HFS_Runner__c</referenceTo>
    <relationshipLabel>HFS Jobs</relationshipLabel>
    <relationshipName>HFS_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Job__c/fields/Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Status__c</fullName>
    <description>It is for collect the status of the job through the collection of bags, since the decisions taken by Runners and Co-ordinators.</description>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Not Accepted</label>
            </value>
            <value>
                <fullName>Delivering</fullName>
            </value>
            <value>
                <fullName>Bags Putaway</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HFS_Job__c/recordTypes/Assigned_Jobs.recordType-meta.xml
<RecordType>
    <fullName>Assigned_Jobs</fullName>
    <active>true</active>
    <label>Assigned Jobs</label>
</RecordType>

force-app/main/default/objects/HFS_Runner__c/HFS_Runner__c.object-meta.xml
<CustomObject>
    <label>HFS Runner</label>
    <nameField>
        <label>HFS Runner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HFS Runners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Runner__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>It should be a a HFS Runner</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>HFS Runner</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>HFS VR Assistant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>HFS_Runners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HFS_Storage_Location__c/HFS_Storage_Location__c.object-meta.xml
<CustomObject>
    <description>This object will save all information related to the Storage Locations.</description>
    <label>HFS Storage Location</label>
    <nameField>
        <label>Storage Location Unique Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HFS Storage Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Storage_Location__c/fields/HFS_Storage_Point__c.field-meta.xml
<CustomField>
    <fullName>HFS_Storage_Point__c</fullName>
    <label>HFS Storage Point</label>
    <referenceTo>HFS_Storage_Point__c</referenceTo>
    <relationshipLabel>HFS Storage Locations</relationshipLabel>
    <relationshipName>HFS_Storage_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HFS_Storage_Location__c/fields/QR_Code_hidden__c.field-meta.xml
<CustomField>
    <fullName>QR_Code_hidden__c</fullName>
    <label>QR Code hidden</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HFS_Storage_Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Empty</fullName>
                <default>true</default>
                <label>Empty</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HFS_Storage_Point__c/HFS_Storage_Point__c.object-meta.xml
<CustomObject>
    <label>HFS Storage Point</label>
    <nameField>
        <label>HFS Storage Point Unique Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HFS Storage Points</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/HFSDeliveryPageController.cls
public with sharing class HFSDeliveryPageController {

	public List<HFS_Bag__c> allJobBags { get; set; }
	public Map<String, Integer> allBagStorage { get; set; }
	public Id jobId { get; set; }
	public String qrCodeLocation { get; set; }
	public String getLocationName { get; set; }
	public String getLocationId { get; set; }
	public String barcodeBag { get; set; }
	public Boolean stopLoopBags { get; set; }
	public Boolean displayPopUp { get; set; }
	public Boolean differentLocations{get;set;}
    public Integer countAllJobBagsInStorage { get; set; }
    public Integer count { get; set; }
    public HFS_Job__c getCurrentJob;
    public String currentStoragePoint{get;set;}
    public String guestCollectionPoint{get;set;}
    public Boolean assignedJob {get;set;}
    public Boolean VarConfPutaway {get;set;}
    public HFS_Job__c getAssignedJob;
    public HFS_Job__c getAvailableJob;

	public HFSDeliveryPageController(ApexPages.StandardController stdController) {
		assignedJob = true;
		Id profileId = UserInfo.getProfileId();
        Profile profile = [SELECT Id, Name FROM Profile WHERE Id =: profileId];
		differentLocations = false;
		jobId = ApexPages.CurrentPage().getParameters().get('id');
        HFS_Job__c currenctJob = [SELECT Id, Assigned_to_me__c FROM HFS_Job__c WHERE Id =: jobId];
		qrCodeLocation = ApexPages.CurrentPage().getParameters().get('qrCodeLocation');
		getLocationId = ApexPages.CurrentPage().getParameters().get('StorageLocation');
        if(currenctJob.Assigned_to_me__c == false && profile.Name == 'HFS Runner'){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'This job is already assigned to another runner'));
            assignedJob = false;
            }else{
                if(getLocationId == ''){
                	getLocationId = null;
				}
				barcodeBag = ApexPages.CurrentPage().getParameters().get('barcodeBag');
				displayPopUp = true;
				getCurrentBags(jobId);
				initialActionStorageLocation();
            }
		
    }

	public void initialActionStorageLocation(){
    	List<HFS_Storage_Location__c> storageLocation = [SELECT Id, Name, QR_Code_hidden__c, HFS_Storage_Point__r.Name FROM HFS_Storage_Location__c];
    	//Apexpages.Message informAssignStorageLocation = new Apexpages.Message(Apexpages.Severity.Error, 'You need to Assign a Storage Location');

    	system.debug(getLocationId);
		if(jobId != null && qrCodeLocation != null){
    		for(HFS_Storage_Location__c correspondentSL : storageLocation){
    			if(correspondentSL.QR_Code_hidden__c == qrCodeLocation){
    				getLocationName = correspondentSL.Name;
    				Apexpages.Message informLocation = new Apexpages.Message(Apexpages.Severity.Info, 'At this point you can put the bags on: ' + getLocationName + ' without scanning Storage Location.');
					Apexpages.addMessage(informLocation);
    				currentStoragePoint = correspondentSL.HFS_Storage_Point__r.Name;
    				guestCollectionPoint = getCurrentJob.HFS_Guest_Collection_Point__c;
    				if(!currentStoragePoint.equals(guestCollectionPoint)){
    					differentLocations = true;
					}
    				getLocationId = correspondentSL.Id;
    			}
    		}
	    } else if(getLocationId != null){
	    	for(HFS_Storage_Location__c correspondentSL : storageLocation){
    			if(correspondentSL.Id == getLocationId){
    				getLocationName = correspondentSL.Name;
    			}
    		}
	    }
	}

    public List<HFS_Bag__c> getCurrentBags (Id jobId){
    	if(String.isEmpty(qrCodeLocation)){
    		Apexpages.Message informNewLocation = new Apexpages.Message(Apexpages.Severity.Info, 'Assign a Storage Location');
			Apexpages.addMessage(informNewLocation);
    	}

		Id userId = UserInfo.getUserId();
		User currentUser = [SELECT Profile.Name FROM User WHERE Id =: userId];
		String profileName = currentUser.Profile.Name;

    	HFS_Runner__c hfsRunnerId = [SELECT Id, Name, User__c FROM HFS_Runner__c WHERE User__c =: userId];

    	getCurrentJob = [SELECT Id, Name, HFS_Purchase__c, Job_Status__c, HFS_Guest_Collection_Point__c, Guest_ID_Code__c FROM HFS_Job__c WHERE Id=: jobId];

		if (profileName == 'HFS Runner') {
			allJobBags = [SELECT Id, Name, In_Storage_Point__c, HFS_Runner__c, Barcode__c FROM HFS_Bag__c WHERE HFS_Runner__c =: hfsRunnerId.Id AND HFS_Job__c =: getCurrentJob.Id];
		} else {	
			allJobBags = [SELECT Id, Name, In_Storage_Point__c, HFS_Runner__c, Barcode__c FROM HFS_Bag__c WHERE HFS_Job__c =: getCurrentJob.Id];
		}
		List<HFS_Bag__c> allPurchaseBags = [SELECT Id, Guest_ID_Code__c, HFS_Storage_Location__c, HFS_Storage_Location__r.Name FROM HFS_Bag__c WHERE Guest_ID_Code__c =: getCurrentJob.Guest_ID_Code__c AND HFS_Purchase__r.Start_Time__c = TODAY];
		
		if(qrCodeLocation == null && getLocationId == null){
			for(HFS_Bag__c eachBag : allPurchaseBags){
				if(eachBag.HFS_Storage_Location__c != null){
					getLocationName = eachBag.HFS_Storage_Location__r.Name;
					getLocationId = eachBag.HFS_Storage_Location__c;
				}
			}
		}

    	return allJobBags;
    }

    public PageReference scanLocationCode(){
    	
    	PageReference goToBQrcodeScan = new PageReference('/apex/HFSDeliveryPageScanStorage?Id=' + jobId);
        return goToBQrcodeScan;
    }

    public PageReference scanBagsCode(){
    	
    	PageReference goToBarcodeScan = new PageReference('/apex/HFSDeliveryPageScanBags?Id=' + jobId + '&StorageLocation=' + getLocationId);
        return goToBarcodeScan;
    }

	public PageReference updateRecords(){
		Apexpages.Message informBagNotMatch = new Apexpages.Message(Apexpages.Severity.Error, 'This is bag ' + barcodeBag + ' does not correspond to this Job.');
		stopLoopBags = true;
		countAllJobBagsInStorage = 0;
		List<HFS_Bag__c> updatedBag = new List<HFS_Bag__c>();

		if(barcodeBag != null && getLocationId != null){
			for(HFS_Bag__c bag : allJobBags){
				if(stopLoopBags){
					if(bag.Barcode__c == barcodeBag){
						bag.In_Storage_Point__c = true;
						bag.HFS_Storage_Location__c = getLocationId;
						bag.Scanned__c = false;
						bag.Status__c = 'Putaway';
						updatedBag.add(bag);
						stopLoopBags = false;
					}
				}
				if(bag.In_Storage_Point__c == true){
					countAllJobBagsInStorage ++;
				}
			}
			update updatedBag;

			if(stopLoopBags == true){
				ApexPages.addMessage(informBagNotMatch);
			}

			if(allJobBags.size() == countAllJobBagsInStorage){
				HFS_Job__c getCurrentJob = [SELECT Id, HFS_Purchase__c, HFS_Purchase__r.Status__c, Job_Status__c, HFS_Guest_Collection_Point__c FROM HFS_Job__c WHERE Id=: jobId];
				getCurrentJob.Job_Status__c = 'Bags Putaway';
				getCurrentJob.HFS_Purchase__r.Status__c = 'Ready for Guest Collection';
				update getCurrentJob.HFS_Purchase__r;
				update getCurrentJob;
                VarConfPutaway = true;
				return null;
				 /*
				PageReference goToRecord = new PageReference('/' + getCurrentJob.Id);
        		return goToRecord;
        		*/
			}
		}

		allBagStorage = getAllStorage(jobId);

		return null;
	}

	public Map<String, Integer> getAllStorage(ID jobId){
		allBagStorage = new Map<String, Integer>();
		HFS_Job__c getCurrentJob = [SELECT Id, HFS_Purchase__c, Job_Status__c, HFS_Guest_Collection_Point__c, Guest_ID_Code__c FROM HFS_Job__c WHERE Id=: jobId];

		set<HFS_Bag__c> allstorage = new Set<HFS_Bag__c>([SELECT Id, HFS_Storage_Location__c, HFS_Storage_Location__r.Name FROM HFS_Bag__c WHERE Guest_ID_Code__c =: getCurrentJob.Guest_ID_Code__c AND HFS_Purchase__r.Start_Time__c = TODAY AND HFS_Storage_Location__c != NULL AND Storage_Matches_Guest_Collection_Point__c = true ]);

		Map<String, Integer> storageLocationName = new Map<String, Integer>();



		count = 0;

		if(!allstorage.isEmpty()){
			for(HFS_Bag__c aBag : allstorage){
				if(storageLocationName.containsKey(aBag.HFS_Storage_Location__r.Name)){
					count = storageLocationName.get(aBag.HFS_Storage_Location__r.Name) + 1;
					storageLocationName.put(aBag.HFS_Storage_Location__r.Name, count);
				} else {
				storageLocationName.put(aBag.HFS_Storage_Location__r.Name,1);
				}
			}
		}
		
		return storageLocationName;
	}

	public PageReference resetLocation(){
		PageReference detailPage = new PageReference('/' + getCurrentJob.Id);
		return detailPage;
	}


	public PageReference CurrentJob(){   	 
        ListView currentList = [SELECT Id FROM ListView WHERE DeveloperName = 'My_Current_Jobs' AND SobjectType = 'HFS_Job__c'];	 
        PageReference goToCurrentJob = new PageReference('/a1L?fcf=' + currentList.Id);
        return goToCurrentJob;
    }

    public PageReference AssignedJob(){    
	ListView assignedList = [SELECT Id FROM ListView WHERE DeveloperName = 'Assigned_Jobs' AND SobjectType = 'HFS_Job__c'];	 
    PageReference goToAssignedJob = new PageReference('/a1L?fcf=' + assignedList.Id);
      return goToAssignedJob;
   }


     public PageReference AvailableJob(){
    	ListView availableList = [SELECT Id FROM ListView WHERE DeveloperName = 'Available_Jobs' AND SobjectType = 'HFS_Job__c'];	 
    	PageReference goToAvailableJob = new PageReference('/a1L?fcf=' + availableList.Id);
        return goToAvailableJob;
    }



}