force-app/main/default/objects/Personal_Shopping_Preference__c/Personal_Shopping_Preference__c.object-meta.xml
<CustomObject>
    <label>Personal Shopping Preference</label>
    <nameField>
        <displayFormat>PSP-{000000}</displayFormat>
        <label>Personal Shopping Preference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Shopping Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personal_Shopping_Preference__c/fields/Body_Shape__c.field-meta.xml
<CustomField>
    <fullName>Body_Shape__c</fullName>
    <description>The guest&apos;s body shape</description>
    <inlineHelpText>The guest&apos;s body shape</inlineHelpText>
    <label>Body Shape</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personal_Shopping_Preference__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <description>How the guest heard about Personal Shopping</description>
    <inlineHelpText>How did the guest hear about Personal Shopping?</inlineHelpText>
    <label>Lead Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Word of Mouth</fullName>
            </value>
            <value>
                <fullName>VR Website</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Press</fullName>
            </value>
            <value>
                <fullName>Recommendation</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Own Contact</fullName>
            </value>
            <value>
                <fullName>TIC/Hosts</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Personal_Shopping_Preference__c/fields/Style__c.field-meta.xml
<CustomField>
    <fullName>Style__c</fullName>
    <description>The guests fashion style</description>
    <inlineHelpText>The guests fashion style</inlineHelpText>
    <label>Style</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PI_PersonalPrefControllerTest.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* This Apex Test Class is to test the functionality of  PI_PersonalPrefController
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author        Barry White
* @created       01/07/2019
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/

@isTest 
public with sharing class PI_PersonalPrefControllerTest {
    
    /**
    * ───────────────────────────────────────────────────────────────────────────────────────────────┐
    * The Setup method is used to create common test data that is used by all other test methods in 
    * the class.
    * ───────────────────────────────────────────────────────────────────────────────────────────────┘
    */
    @testSetup 
    static void setup() {

        Account acc = new Account();
        acc.FirstName = 'Baker';
        acc.LastName = 'Mayfield';
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('VIP Guest').getRecordTypeId();
        insert acc;
    }

    /**
    * ───────────────────────────────────────────────────────────────────────────────────────────────┐
    * Test the save method and country code mapping
    * ───────────────────────────────────────────────────────────────────────────────────────────────┘
    */
    static testMethod void testSave(){
        
        
        Account customer = [SELECT Id, PersonContactId FROM ACCOUNT LIMIT 1][0];

        ApexPages.StandardController controller = new ApexPages.StandardController(customer);
        PI_PersonalPrefController extension = new PI_PersonalPrefController(controller);
        PageReference pageRef = Page.pi_personalPref;
        pageRef.getParameters().put('Id', String.valueOf(customer.Id));
        Test.setCurrentPage(pageRef);

        Test.startTest();
            // create a personal pref
            extension.personalPref.Lead_Source__c = 'Other';
            extension.personalPref.Body_Shape__c = 'small';
            extension.personalPref.Style__c = 'cool';
            // Save
            extension.save();

        Test.stopTest();

        list<Personal_Shopping_Preference__c> listPersonalprefs = [SELECT Id, Body_Shape__c FROM Personal_Shopping_Preference__c];
        system.assertEquals(1, listPersonalprefs.size(), 'Expected 1 preference, found ' + listPersonalprefs.size());
        system.assertEquals('small', listPersonalprefs[0].Body_Shape__c, 'Expected small as body shape, found ' + listPersonalprefs[0].Body_Shape__c);
    }
}