force-app/main/default/objects/Deal_Business_History__c/Deal_Business_History__c.object-meta.xml
<CustomObject>
    <description>This is an object to capture a snapshot of various deal approval fields during the negotiation process at user initiated intervals.</description>
    <label>Deal Business History</label>
    <nameField>
        <displayFormat>BDH-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Business Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Business_History__c/fields/Approved_By__c.field-meta.xml
<CustomField>
    <fullName>Approved_By__c</fullName>
    <inlineHelpText>Select signatories involved.</inlineHelpText>
    <label>Approved By</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adele Davey</fullName>
            </value>
            <value>
                <fullName>Adele Reast Duggan</fullName>
            </value>
            <value>
                <fullName>Alberto Caballe</fullName>
            </value>
            <value>
                <fullName>Aleksander Michalowski</fullName>
            </value>
            <value>
                <fullName>Andrew Marshall</fullName>
            </value>
            <value>
                <fullName>Anne Caroline Krenz</fullName>
            </value>
            <value>
                <fullName>Anne Marie Scichili</fullName>
            </value>
            <value>
                <fullName>Ann Marie Scichili</fullName>
            </value>
            <value>
                <fullName>Aonghus Wright</fullName>
            </value>
            <value>
                <fullName>Barbara de Magistris</fullName>
            </value>
            <value>
                <fullName>Carla Annunziato</fullName>
            </value>
            <value>
                <fullName>Carlos Santana</fullName>
            </value>
            <value>
                <fullName>Carme Bigata</fullName>
            </value>
            <value>
                <fullName>Chris Cabot</fullName>
            </value>
            <value>
                <fullName>Chris Rycroft</fullName>
            </value>
            <value>
                <fullName>Christof Fuchs</fullName>
            </value>
            <value>
                <fullName>Chris Warren</fullName>
            </value>
            <value>
                <fullName>Clare Dutton</fullName>
            </value>
            <value>
                <fullName>Clare Lecointe</fullName>
            </value>
            <value>
                <fullName>Desiree Bollier</fullName>
            </value>
            <value>
                <fullName>Eamonn Curry</fullName>
            </value>
            <value>
                <fullName>Edoardo Vittucci</fullName>
            </value>
            <value>
                <fullName>Elena Foguet</fullName>
            </value>
            <value>
                <fullName>Federica Barone</fullName>
            </value>
            <value>
                <fullName>Francois Poirel</fullName>
            </value>
            <value>
                <fullName>Frank Heydenreich</fullName>
            </value>
            <value>
                <fullName>Gaëlle Garnier</fullName>
            </value>
            <value>
                <fullName>Gary Rosen</fullName>
            </value>
            <value>
                <fullName>George Ross</fullName>
            </value>
            <value>
                <fullName>Helen Pask</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Business_History__c/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <description>Date of last and final approval</description>
    <inlineHelpText>Date of last and final approval</inlineHelpText>
    <label>Approved Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Deal_Business_History__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <description>Parent Deal record</description>
    <inlineHelpText>Parent Deal record</inlineHelpText>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Business Histories</relationshipLabel>
    <relationshipName>Deal_Business_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deal_Business_History__c/fields/Review_Comment__c.field-meta.xml
<CustomField>
    <fullName>Review_Comment__c</fullName>
    <description>Notes about the deal negotiation/approval process.</description>
    <inlineHelpText>Notes about the deal negotiation/approval process.</inlineHelpText>
    <label>Review Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Deal_Business_History__c/fields/Tier_Level__c.field-meta.xml
<CustomField>
    <fullName>Tier_Level__c</fullName>
    <description>Approval Tier Level</description>
    <inlineHelpText>Approval Tier Level</inlineHelpText>
    <label>Tier Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 2a</fullName>
            </value>
            <value>
                <fullName>Tier 2b</fullName>
            </value>
            <value>
                <fullName>Tier 2c</fullName>
            </value>
            <value>
                <fullName>Tier 3a</fullName>
            </value>
            <value>
                <fullName>Tier 3b</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
            <value>
                <fullName>Tier 4a</fullName>
            </value>
            <value>
                <fullName>Tier 4b</fullName>
            </value>
            <value>
                <fullName>Tier 4*</fullName>
            </value>
            <value>
                <fullName>Tier 5</fullName>
            </value>
            <value>
                <fullName>Tier 4L</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Business_History__c/fields/Tier_Level_Rationale__c.field-meta.xml
<CustomField>
    <fullName>Tier_Level_Rationale__c</fullName>
    <description>Enter some rationale for the Tier Level entered</description>
    <inlineHelpText>Enter some rationale for the Tier Level entered</inlineHelpText>
    <label>Tier Level Rationale</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <description>Date of last and final approval</description>
    <inlineHelpText>Date of last and final approval</inlineHelpText>
    <label>Approved Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tier_Level__c.field-meta.xml
<CustomField>
    <fullName>Tier_Level__c</fullName>
    <description>Approval Tier Level</description>
    <inlineHelpText>Approval Tier Level</inlineHelpText>
    <label>Tier Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 2a</fullName>
            </value>
            <value>
                <fullName>Tier 2b</fullName>
            </value>
            <value>
                <fullName>Tier 2c</fullName>
            </value>
            <value>
                <fullName>Tier 3a</fullName>
            </value>
            <value>
                <fullName>Tier 3b</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
            <value>
                <fullName>Tier 4a</fullName>
            </value>
            <value>
                <fullName>Tier 4b</fullName>
            </value>
            <value>
                <fullName>Tier 4*</fullName>
            </value>
            <value>
                <fullName>Tier 5</fullName>
            </value>
            <value>
                <fullName>Tier 4L</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tier_Level_Rationale__c.field-meta.xml
<CustomField>
    <fullName>Tier_Level_Rationale__c</fullName>
    <description>Enter some rationale for the Tier Level entered</description>
    <inlineHelpText>Enter some rationale for the Tier Level entered</inlineHelpText>
    <label>Tier Level Rationale</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the actual village where this opportunity exists</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/DealBusinessUtilitiesTest.cls
@isTest
private class DealBusinessUtilitiesTest {
    
    static Account testAccount;
    static Village__c testVillage;
    static Opportunity testOpp;
    
    static void setupData(){
        
        testAccount = TestDataGenerator.setupB2BAccount(1, true);
        testVillage = TestDataGenerator.setupVillage(true);

        testOpp = new Opportunity(Village__c = testVillage.Id, AccountId = testAccount.Id,
                                               Name = 'TESTOPP1', CloseDate = system.today(),
                                               StageName = 'Agreed in Principle');
        insert testOpp;
        
    }

    static testMethod void unitTest() {

        setupData();
        
        testOpp.Tier_Level__c = 'Yes- Tier 1';
        testOpp.Tier_Level_Rationale__c = 'All good';
        
        update testOpp;
        
        Deal_Business_History__c history = new Deal_Business_History__c();
        history.Deal__c = testOpp.Id;
        history.Approved_Date__c = system.now().addDays(-3);
        history.Review_Comment__c = 'abc';
        history.Approved_By__c = 'Mr Test';
        
        insert history;
        
        history = [select Id, Approved_Date__c, Tier_Level__c, Tier_Level_Rationale__c from Deal_Business_History__c
                            where Id = :history.Id];
        
        testOpp = [select Id,Approved_Date__c, Tier_Level__c, Tier_Level_Rationale__c from Opportunity 
                        where Id = :testOpp.Id];
        
        // check history tier fields have been populated with values from parent deal
        system.assertEquals(history.Tier_Level__c, testOpp.Tier_Level__c);
        system.assertEquals(history.Tier_Level_Rationale__c, testOpp.Tier_Level_Rationale__c);
        
        // check approval date updated on parent deal record
        system.assertEquals(testOpp.Approved_Date__c, history.Approved_Date__c);
                            
        

    }
}