force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/Business_Function__c.field-meta.xml
<CustomField>
    <fullName>Business_Function__c</fullName>
    <description>The business area that this activity is aligned with.....</description>
    <inlineHelpText>The business area that this activity is aligned with</inlineHelpText>
    <label>Business Function</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Functions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <inlineHelpText>Marketing Channel</inlineHelpText>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Campaign Support</fullName>
            </value>
            <value>
                <fullName>Collateral</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Non-campaign</fullName>
            </value>
            <value>
                <fullName>Partnerships</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Village Services</fullName>
            </value>
            <value>
                <fullName>VIP</fullName>
            </value>
            <value>
                <fullName>Visual Merchandising</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter a End date where you expect the activity to stop impacting footfall/Sales in the Village.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <description>....</description>
    <label>Marketing Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You cannot link an activity to a &apos;Cancelled&apos;  Campaign.</errorMessage>
        <filterItems>
            <field>Marketing_Campaign__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Activities</relationshipLabel>
    <relationshipName>Marketing_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <inlineHelpText>e.g. Footfall, Sales, Recruitment</inlineHelpText>
    <label>Objective</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Response_Description__c.field-meta.xml
<CustomField>
    <fullName>Response_Description__c</fullName>
    <inlineHelpText>How will the target audience respond?  Phone, website registration?  Do we need a data capture system or other response mechanism?</inlineHelpText>
    <label>Response Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter a date where you expect the activity to impact footfall/Sales in the Village. This is not necessarily the date the email is being sent</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Sub_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sub_Channel__c</fullName>
    <description>..</description>
    <label>Sub Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Channel__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accommodation</fullName>
            </value>
            <value>
                <fullName>Agency Fee</fullName>
            </value>
            <value>
                <fullName>App Innovations</fullName>
                <label>App Development</label>
            </value>
            <value>
                <fullName>Books/Magazines</fullName>
            </value>
            <value>
                <fullName>Brand Events</fullName>
            </value>
            <value>
                <fullName>Brochure</fullName>
                <label>Brochure/Leaflet</label>
            </value>
            <value>
                <fullName>Catering</fullName>
            </value>
            <value>
                <fullName>Christmas Lights</fullName>
            </value>
            <value>
                <fullName>Cinema/Theatre</fullName>
            </value>
            <value>
                <fullName>Community Marketing</fullName>
            </value>
            <value>
                <fullName>Contracts</fullName>
            </value>
            <value>
                <fullName>Copywriting</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Event</fullName>
            </value>
            <value>
                <fullName>Digital Travel Platforms</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Display</fullName>
            </value>
            <value>
                <fullName>Display: Biddable</fullName>
            </value>
            <value>
                <fullName>Display: Non - Biddable</fullName>
            </value>
            <value>
                <fullName>Donations - Not Tax-Deductible</fullName>
            </value>
            <value>
                <fullName>Donations - Tax Deductible</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Entertaining Staff Only</fullName>
            </value>
            <value>
                <fullName>Entertaining Third Parties/Mixed</fullName>
            </value>
            <value>
                <fullName>Expats</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Facebook &amp; Instagram (Organic)</fullName>
                <label>Facebook &amp; Instagram (Owned)</label>
            </value>
            <value>
                <fullName>Facebook &amp; Instagram (Paid Social)</fullName>
            </value>
            <value>
                <fullName>Familiarisation Trips</fullName>
            </value>
            <value>
                <fullName>Financial Partnerships</fullName>
            </value>
            <value>
                <fullName>Printed Survey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/recordTypes/General_Activity.recordType-meta.xml
<RecordType>
    <fullName>General_Activity</fullName>
    <active>true</active>
    <description>No QR Code...</description>
    <label>General Activity</label>
</RecordType>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/Accountable_Person__c.field-meta.xml
<CustomField>
    <fullName>Accountable_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accountable</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Campaign_Focus__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Focus__c</fullName>
    <inlineHelpText>...</inlineHelpText>
    <label>Campaign Focus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Theme</fullName>
            </value>
            <value>
                <fullName>Awareness and Positioning</fullName>
            </value>
            <value>
                <fullName>Promotional Moments</fullName>
            </value>
            <value>
                <fullName>Tactical Product Focus</fullName>
            </value>
            <value>
                <fullName>International Moments</fullName>
            </value>
            <value>
                <fullName>Retail Brand Moments</fullName>
            </value>
            <value>
                <fullName>Local Moments</fullName>
            </value>
            <value>
                <fullName>Destination Marketing Moments</fullName>
            </value>
            <value>
                <fullName>International Always On</fullName>
            </value>
            <value>
                <fullName>Non-Campaigns</fullName>
            </value>
            <value>
                <fullName>BAU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Campaign_Level__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Level__c</fullName>
    <description>Tactical is the norm.

Add &quot;Theme&quot; or &quot;BAU&quot; when required - keep it off so users can only choose Tactical and no validations are required.</description>
    <inlineHelpText>The Campaing Level...</inlineHelpText>
    <label>Campaign Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Theme</fullName>
            </value>
            <value>
                <fullName>BAU Campaign</fullName>
            </value>
            <value>
                <fullName>Non-Campaign</fullName>
            </value>
            <value>
                <fullName>Lead Moment</fullName>
            </value>
            <value>
                <fullName>Local Moment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter the End Date of the Campaign</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <description>e.g. Footfall, Sales, Recruitment</description>
    <inlineHelpText>e.g. Footfall, Sales, Recruitment</inlineHelpText>
    <label>Objective</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Parent_Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Parent_Marketing_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a Parent Marketing Campaign</inlineHelpText>
    <label>Parent Marketing Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Parent Campaigns must be TBVSC Brand Campaigns</errorMessage>
        <filterItems>
            <field>Marketing_Campaign__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <infoMessage>Please select a TBVSC Brand Campaign</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>.</description>
    <label>Responsible</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Marketing_Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter the Start Date of the Campaign</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/recordTypes/TBVSC_Brand_Campaign.recordType-meta.xml
<RecordType>
    <fullName>TBVSC_Brand_Campaign</fullName>
    <active>true</active>
    <description>TBVSC Brand Campaign: A Marketing Theme or Campaign set at TBVSC Brand level..</description>
    <label>TBVSC Brand Campaign</label>
</RecordType>

force-app/main/default/objects/Marketing_Campaign__c/recordTypes/Village_Campaign.recordType-meta.xml
<RecordType>
    <fullName>Village_Campaign</fullName>
    <active>true</active>
    <description>A Marketing Brief for a Village&apos;s Campaign..</description>
    <label>Village Campaign</label>
</RecordType>

force-app/main/default/classes/massEditReAssignCampaignsControllertest.cls
@IsTest
Public Class massEditReAssignCampaignsControllertest{

    Public Static Marketing_Campaign__c MC1 {get;set;}
    Public Static Marketing_Campaign__c MC2 {get;set;}
    static final id GROUP_RECTYPE = Schema.SObjectType.Marketing_Campaign__c.RecordTypeInfosByDeveloperName.get('TBVSC_Brand_Campaign').RecordTypeId;
    static final id VILLAGE_RECTYPE = Schema.SObjectType.Marketing_Campaign__c.RecordTypeInfosByDeveloperName.get('Village_Campaign').RecordTypeId;

    @testsetup
    static void setupData(){
       
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'userTest', Email='testuser@test.com', EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                        LocaleSidKey='en_US', ProfileId = p.Id, 
                        TimeZoneSidKey='America/Los_Angeles', 
                        UserName='testUser@test.com.SMP');

        insert u;

        list<Marketing_Campaign__c> mcToAdd = new list<Marketing_Campaign__c>();
        MC1 = new Marketing_Campaign__c(Name='Test Group Campaign', Campaign_Level__c = 'Theme',RecordTypeId = GROUP_RECTYPE,Campaign_Focus__c = 'Theme',Start_date__c = system.today(), end_date__c = system.today()+365, status__c = 'Approved', Responsible__c = u.Id , Accountable_Person__c = u.Id , CurrencyIsoCode = 'GBP');
        insert MC1;
        system.debug('MC1.id' + MC1.id);
        Marketing_Campaign__c MC2 = new Marketing_Campaign__c(Name='Test Village1 Campaign',Parent_Marketing_Campaign__c = MC1.id, Campaign_Level__c = 'Lead Moment',RecordTypeId = VILLAGE_RECTYPE,Campaign_Focus__c = 'Theme',Start_date__c = system.today(), end_date__c = system.today()+365, status__c = 'To be Approved', Responsible__c = u.Id , Accountable_Person__c = u.Id , CurrencyIsoCode = 'GBP');
        Marketing_Campaign__c MC3 = new Marketing_Campaign__c(Name='Test Village2 Campaign',Parent_Marketing_Campaign__c = MC1.id, Campaign_Level__c = 'Lead Moment',RecordTypeId = VILLAGE_RECTYPE,Campaign_Focus__c = 'Theme',Start_date__c = system.today(), end_date__c = system.today()+365, status__c = 'To be Approved', Responsible__c = u.Id , Accountable_Person__c = u.Id , CurrencyIsoCode = 'GBP');
        
        mcToAdd.add(MC2);
        mcToAdd.add(MC3);
        insert mcToAdd;

        
    }

    @isTest
    static void successTest() {
        
        Marketing_Campaign__c MC = [SELECT Name FROM Marketing_Campaign__c WHERE NAME = 'Test Group Campaign'];
        list<Marketing_Campaign__c> testMCs = [SELECT id, name FROM Marketing_Campaign__c WHERE Parent_Marketing_Campaign__c =: MC.id ];
        system.debug('testMCs ' + testMCs);

        list<massEditReAssignCampaignsController.Wrapper> wraps = new list<massEditReAssignCampaignsController.Wrapper>();
        for(Marketing_Campaign__c mark : testMCs){
            wraps.add(new massEditReAssignCampaignsController.Wrapper(mark));
        }

        ApexPages.StandardSetController StdSetCon = new ApexPages.StandardSetController(testMCs);
        massEditReAssignCampaignsController controller = new massEditReAssignCampaignsController(StdSetCon);   
        PageReference pageRef = Page.massEditReAssignCampaigns;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', MC.id);
        
        test.startTest();
        controller.wMCstoEdit = wraps;
        controller.selectOption.status__c = 'Approved';
        Controller.setAllStatus();
        controller.selectAll();
        controller.deselectAll();
        controller.selectAll();
        Controller.saveSelected();
        test.stopTest();

        list<Marketing_Campaign__c> checkMCs = [SELECT id, name,Status__c FROM Marketing_Campaign__c WHERE Parent_Marketing_Campaign__c =: MC.id ];
        system.assert(checkMCs[0].status__c == 'Approved');

    }

    @isTest
    static void cancelTest() {
        
        Marketing_Campaign__c MC = [SELECT Name FROM Marketing_Campaign__c WHERE NAME = 'Test Group Campaign'];
        list<Marketing_Campaign__c> testMCs = [SELECT id, name FROM Marketing_Campaign__c WHERE Parent_Marketing_Campaign__c =: MC.id ];
        system.debug('testMCs ' + testMCs);

        list<massEditReAssignCampaignsController.Wrapper> wraps = new list<massEditReAssignCampaignsController.Wrapper>();
        for(Marketing_Campaign__c Mark : testMCs){
            wraps.add(new massEditReAssignCampaignsController.Wrapper(mark));
        }
 
        ApexPages.StandardSetController StdSetCon = new ApexPages.StandardSetController(testMCs);
        massEditReAssignCampaignsController controller = new massEditReAssignCampaignsController(StdSetCon);   
        PageReference pageRef = Page.massEditReAssignCampaigns;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', MC.id);

        
        test.startTest();
        controller.wMCstoEdit = wraps;
        controller.selectOption.status__c = 'Cancelled';
        controller.Cancel();
        test.stopTest();

        list<Marketing_Campaign__c> checkMCs = [SELECT id, name,Status__c FROM Marketing_Campaign__c WHERE Parent_Marketing_Campaign__c =: MC.id ];
        system.debug('checkMCs ' + checkMCs);
        system.assert(checkMCs[0].status__c != 'Cancelled');

    }



    @isTest
    static void errorHandlingTest() {

        User usr = TestData_User.setupAdminUser(true);

        Marketing_Campaign__c VMC = [SELECT Name FROM Marketing_Campaign__c WHERE NAME = 'Test Village1 Campaign'];
      //  recordtype rectype = [SELECT id, Name FROM RecordType WHERE sObjectType = 'Marketing_Activity__c' AND Name = 'General Activity'];
        recordtype rectype = [SELECT id, Name FROM RecordType WHERE sObjectType = 'Marketing_Activity__c' AND DeveloperName = 'General_Activity'];
        Marketing_Activity__c MA1 = new Marketing_Activity__c(recordtypeid = rectype.id, name = 'TA1',  Business_function__c = 'Local PR', Channel__c = 'CRM',Sub_Channel__c = 'Printed Survey', Start_date__c = system.today(), end_date__c = system.today()+365, Status__c = 'Approved', Objective__c = 'test', Response_Description__c = 'test', Measurement_Description__c = 'test', Communication_Plan__c = 'test', Message__c = 'test', Marketing_Campaign__c = VMC.id  );
        insert MA1;

        Marketing_Campaign__c MC = [SELECT Name FROM Marketing_Campaign__c WHERE NAME = 'Test Group Campaign'];
        list<Marketing_Campaign__c> testMCs = [SELECT id, name FROM Marketing_Campaign__c WHERE Parent_Marketing_Campaign__c =: MC.id ];
        system.debug('testMCs ' + testMCs);

        list<massEditReAssignCampaignsController.Wrapper> wraps = new list<massEditReAssignCampaignsController.Wrapper>();
        for(Marketing_Campaign__c mark : testMCs){
            wraps.add(new massEditReAssignCampaignsController.Wrapper(mark));
        }


        ApexPages.StandardSetController StdSetCon = new ApexPages.StandardSetController(testMCs);
        massEditReAssignCampaignsController controller = new massEditReAssignCampaignsController(StdSetCon);   
        PageReference pageRef = Page.massEditReAssignCampaigns;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', MC.id);

        
        test.startTest();
        system.runAs(usr){
            controller.MCs = testMCs;
            controller.wMCstoEdit = wraps;
            controller.selectOption.status__c = 'Cancelled';
            Controller.setAllStatus();
            controller.selectAll();
            controller.saveSelected();
        }
        test.stopTest();


        list<Marketing_Campaign__c> checkMCs = [SELECT id, name,Status__c FROM Marketing_Campaign__c WHERE name =: 'Test Village1 Campaign' ];
        system.assert(checkMCs[0].Status__c != 'Cancelled');

    }
    





}