force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <description>Represents the status of the record as far as the Oracle Integration is concerned.</description>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>waiting</fullName>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>sending</fullName>
                <label>Sending</label>
            </value>
            <value>
                <fullName>confirmed</fullName>
                <label>Success</label>
            </value>
            <value>
                <fullName>error</fullName>
                <label>Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <description>....</description>
    <label>Marketing Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You cannot link an activity to a &apos;Cancelled&apos;  Campaign.</errorMessage>
        <filterItems>
            <field>Marketing_Campaign__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Activities</relationshipLabel>
    <relationshipName>Marketing_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Oracle_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Project_Id__c</fullName>
    <description>Text field created to store the project (Marketing Campaig) Id. This way, when the field is populated, the Marketing Activity will run and will send the objects to the Finance system (formula fields wouldn&apos;t trigger the execution of the Apex Trigger)</description>
    <label>Oracle Project Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Oracle_Secondary_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Secondary_Project_Id__c</fullName>
    <description>Text field created to store the project (Marketing Campaig) Id. This way, when the field is populated, the Marketing Activity will run and will send the objects to the Finance system (formula fields wouldn&apos;t trigger the execution of the Apex Trigger)</description>
    <label>Oracle Secondary Project Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Oracle_Secondary_Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Secondary_Task_Id__c</fullName>
    <label>Oracle Secondary Task Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Oracle_Secondary_Task_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Secondary_Task_Number__c</fullName>
    <label>[Oracle] Secondary Task Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Oracle_Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Task_Id__c</fullName>
    <label>Oracle Primary Task Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Oracle_Task_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Task_Number__c</fullName>
    <label>[Oracle] Primary Task Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <description>Represents the status of the record as far as the Oracle Integration is concerned.</description>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>waiting</fullName>
                <default>true</default>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>sending</fullName>
                <label>Sending</label>
            </value>
            <value>
                <fullName>confirmed</fullName>
                <label>Success</label>
            </value>
            <value>
                <fullName>error</fullName>
                <label>Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Oracle_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Project_Id__c</fullName>
    <label>Oracle Primary Project Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Oracle_Secondary_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Secondary_Project_Id__c</fullName>
    <label>Oracle Secondary Project Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>...</description>
    <inlineHelpText>Select the Village is this campaign related to</inlineHelpText>
    <label>Village</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>notEqual</operation>
            <value>Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Village Campaign</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MarketingActivityDataReceive.cls
@RestResource(urlMapping='/MarketingActivities')
global with sharing class MarketingActivityDataReceive{
    @HttpPUT
    global static string taskDetailsReceivedfromOracle(BusinessUnitWrapper activityResponseString){
        MFIntegrationLogger logger = new MFIntegrationLogger (activityResponseString.SessionId);
        try{
            logger.setInboundRequest(activityResponseString, activityResponseString.SalesforceId);
            logger.setResponseStatusCode(activityResponseString.ResponseStatus.Code);
            logger.setErrorMessage(activityResponseString.ResponseStatus.Message);

            Marketing_Activity__c ma = [select id, Name, Marketing_Campaign__c, Marketing_Campaign__r.Village__c, Error_Message__c, Integration_Status__c, Oracle_Project_Id__c, Oracle_Secondary_Project_Id__c from Marketing_Activity__c where id=:activityResponseString.SalesforceId];  


            if (activityResponseString.ResponseStatus.Code != '0') {
                /*
                    Because of DI retry system, it could happen that a Successfully created MA ends up being in Error status. This is why:
                        1-. Marketing Activity creation initially fails in Oracle --> DI enqueues a retry
                        2-. DI Calls back to Salesforce informing the error but, after trying to update the Marketing Activity to reflect the error,
                            Salesforce update fails because, for instance, UNABLE_TO_LOCK_ROWS error --> DI enqueus a retry FOR THE CALLBACK
                        3-. DI performs the retry of the creation of the MA in Oracle and now is successful. DI calls back immediately to Salesforce informing of the success.
                            Salesforce Marketing Activity gets updated to "confirmed"
                        4-. After a few seconds, the failed error callback (point 2) is retried and now it works in Salesforce, changing the MA to error status
                    To avoid this problem, we check that the status hasn't been changed to confirmed already      
                */
                if (ma.Integration_Status__c != 'confirmed') {
                    ma.Error_Message__c = activityResponseString.ResponseStatus.Message.length() > 250 ? activityResponseString.ResponseStatus.Message.subString(0,250) : activityResponseString.ResponseStatus.Message;
                    ma.Integration_Status__c = 'error';
                    update ma;
                }
                logger.saveRequests();
                return null;
            }
            
            Village__c vRcrd = [select Name, Village_Code__c from Village__c where id=:ma.Marketing_Campaign__r.Village__c];
            
            //if(activityResponseString.BusinessUnit.size()>0){
            if(ma.Oracle_Project_Id__c != null){
                ma.Oracle_Task_Id__c = activityResponseString.BusinessUnit[0].OracleTaskId;
                ma.Oracle_Task_Number__c = activityResponseString.BusinessUnit[0].OracleTaskNumber;
            }
            
            //if(activityResponseString.BusinessUnit.size()>1){ 
            if(ma.Oracle_Project_Id__c == null && ma.Oracle_Secondary_Project_Id__c != null ){  
                ma.Oracle_Secondary_Task_Id__c = activityResponseString.BusinessUnit[0].OracleTaskId;
                ma.Oracle_Secondary_Task_Number__c = activityResponseString.BusinessUnit[0].OracleTaskNumber;
            } else if( ma.Oracle_Secondary_Project_Id__c != null ) {
                ma.Oracle_Secondary_Task_Id__c = activityResponseString.BusinessUnit[1].OracleTaskId;
                ma.Oracle_Secondary_Task_Number__c = activityResponseString.BusinessUnit[1].OracleTaskNumber;            
            }

            ma.Integration_Status__c = 'confirmed';

            update ma;
            logger.saveRequests();
            return ''+activityResponseString.ResponseStatus;
 
        }catch (Exception e){         
            System.debug('Error:' + e.getMessage() + 'LN:' + e.getLineNumber());   
            logger.setErrorMessage(e.getMessage() + 'LN:' + e.getLineNumber());
            logger.saveRequests();
            RestContext.response.statusCode = 500;
            return e.getMessage();
        }  
    }
    global class BusinessUnitWrapper{
        public String SessionId;
        public Id SalesforceId;
        public BusinessUnit[] BusinessUnit;
        public ResponseStatus ResponseStatus;
    }
    global class BusinessUnit{
        public String BusinessUnitCode;
        public String OracleTaskId;
        public String OracleTaskNumber;
    } 
    global class ResponseStatus{
        public String Code;
        public String Message;
    } 
}