force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/Business_Function__c.field-meta.xml
<CustomField>
    <fullName>Business_Function__c</fullName>
    <description>The business area that this activity is aligned with.....</description>
    <inlineHelpText>The business area that this activity is aligned with</inlineHelpText>
    <label>Business Function</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Functions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <inlineHelpText>Marketing Channel</inlineHelpText>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Campaign Support</fullName>
            </value>
            <value>
                <fullName>Collateral</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Non-campaign</fullName>
            </value>
            <value>
                <fullName>Partnerships</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Village Services</fullName>
            </value>
            <value>
                <fullName>VIP</fullName>
            </value>
            <value>
                <fullName>Visual Merchandising</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter a End date where you expect the activity to stop impacting footfall/Sales in the Village.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Expenditure_Category__c.field-meta.xml
<CustomField>
    <fullName>Expenditure_Category__c</fullName>
    <formula>&apos;MKT&apos;+&apos;-&apos;+TEXT(Channel__c)</formula>
    <label>Expenditure Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Expenditure_Type__c.field-meta.xml
<CustomField>
    <fullName>Expenditure_Type__c</fullName>
    <formula>&apos;MKT&apos;+&apos;-&apos;+TEXT(Sub_Channel__c)</formula>
    <label>Expenditure Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <description>....</description>
    <label>Marketing Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You cannot link an activity to a &apos;Cancelled&apos;  Campaign.</errorMessage>
        <filterItems>
            <field>Marketing_Campaign__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Activities</relationshipLabel>
    <relationshipName>Marketing_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Oracle_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Project_Id__c</fullName>
    <description>Text field created to store the project (Marketing Campaig) Id. This way, when the field is populated, the Marketing Activity will run and will send the objects to the Finance system (formula fields wouldn&apos;t trigger the execution of the Apex Trigger)</description>
    <label>Oracle Project Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Re_send_to_Oracle_for_NewActivity__c.field-meta.xml
<CustomField>
    <fullName>Re_send_to_Oracle_for_NewActivity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Re-send to Oracle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter a date where you expect the activity to impact footfall/Sales in the Village. This is not necessarily the date the email is being sent</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Sub_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sub_Channel__c</fullName>
    <description>..</description>
    <label>Sub Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Channel__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accommodation</fullName>
            </value>
            <value>
                <fullName>Agency Fee</fullName>
            </value>
            <value>
                <fullName>App Innovations</fullName>
                <label>App Development</label>
            </value>
            <value>
                <fullName>Books/Magazines</fullName>
            </value>
            <value>
                <fullName>Brand Events</fullName>
            </value>
            <value>
                <fullName>Brochure</fullName>
                <label>Brochure/Leaflet</label>
            </value>
            <value>
                <fullName>Catering</fullName>
            </value>
            <value>
                <fullName>Christmas Lights</fullName>
            </value>
            <value>
                <fullName>Cinema/Theatre</fullName>
            </value>
            <value>
                <fullName>Community Marketing</fullName>
            </value>
            <value>
                <fullName>Contracts</fullName>
            </value>
            <value>
                <fullName>Copywriting</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Event</fullName>
            </value>
            <value>
                <fullName>Digital Travel Platforms</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Display</fullName>
            </value>
            <value>
                <fullName>Display: Biddable</fullName>
            </value>
            <value>
                <fullName>Display: Non - Biddable</fullName>
            </value>
            <value>
                <fullName>Donations - Not Tax-Deductible</fullName>
            </value>
            <value>
                <fullName>Donations - Tax Deductible</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Entertaining Staff Only</fullName>
            </value>
            <value>
                <fullName>Entertaining Third Parties/Mixed</fullName>
            </value>
            <value>
                <fullName>Expats</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Facebook &amp; Instagram (Organic)</fullName>
                <label>Facebook &amp; Instagram (Owned)</label>
            </value>
            <value>
                <fullName>Facebook &amp; Instagram (Paid Social)</fullName>
            </value>
            <value>
                <fullName>Familiarisation Trips</fullName>
            </value>
            <value>
                <fullName>Financial Partnerships</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Transfer_To_Oracle__c.field-meta.xml
<CustomField>
    <fullName>Transfer_To_Oracle__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Allows the activity to be transferred to Oracle Projects</description>
    <inlineHelpText>Allow the activity to be transferred to Oracle Projects</inlineHelpText>
    <label>Transfer To Oracle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter the End Date of the Campaign</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Oracle_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Project_Id__c</fullName>
    <label>Oracle Primary Project Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter the Start Date of the Campaign</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Transfer_To_Oracle__c.field-meta.xml
<CustomField>
    <fullName>Transfer_To_Oracle__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Allows the Campaign data to be sent to Oracle Projects</description>
    <inlineHelpText>Allow the Campaign data to be sent to Oracle Projects</inlineHelpText>
    <label>Transfer To Oracle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>...</description>
    <inlineHelpText>Select the Village is this campaign related to</inlineHelpText>
    <label>Village</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>notEqual</operation>
            <value>Group</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Village Campaign</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <filterItems>
            <field>Village__c.Name</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MarketingActivityTriggerHandler.cls
public class MarketingActivityTriggerHandler 
{
    private static List <String> fieldsToTriggerIntegration = new List <String> {'Re_send_to_Oracle_for_NewActivity__c','Transfer_to_Oracle__c','Name','Start_Date__c','End_Date__c','Status__c','CreatedDate','Business_Function__c','Channel__c','Sub_Channel__c','Expenditure_Category__c','Expenditure_Type__c','Oracle_Project_Id__c'};
    
    public static void beforeUpdateAndInsert(list<Marketing_Activity__c> maList) {
        
        List<Id> mcIdList = new List<Id>();
        
        for(Marketing_Activity__c ma : maList){
        	mcIdList.add(ma.Marketing_Campaign__c);
        }
    	     
		List<Marketing_Campaign__c> mcList = [SELECT Id, Village__r.name FROM Marketing_Campaign__c where Id = :mcIdList];
        Map<Id,Marketing_Campaign__c> mcMap = new Map<Id,Marketing_Campaign__c>();
        
        for(Marketing_Campaign__c mc: mcList){           
            mcMap.put(mc.id,mc);            
        }                     
        
    	for(Marketing_Activity__c ma : maList){
        	Marketing_Campaign__c mc = mcMap.get(ma.Marketing_Campaign__c);
            if( (ma.Market__c=='Belgium' && mc.Village__r.name=='Maasmechelen') || (ma.Market__c=='France' && mc.Village__r.name=='La Vallée') 
              || (ma.Market__c=='Germany' && (mc.Village__r.name=='Ingolstadt' || mc.Village__r.name=='Wertheim')) || (ma.Market__c=='Ireland' && mc.Village__r.name=='Kildare') 
              || (ma.Market__c=='Italy' && mc.Village__r.name=='Fidenza')  || (ma.Market__c=='Netherlands' && mc.Village__r.name=='Maasmechelen') 
              || (ma.Market__c=='Northern Ireland' && mc.Village__r.name=='Kildare')  || (ma.Market__c=='Spain' && (mc.Village__r.name=='La Roca' ||mc.Village__r.name=='Las Rozas')) 
              || (ma.Market__c=='United Kingdom' && mc.Village__r.name=='Bicester') ){
            	ma.Domestic__c=true;
        	} else {
                ma.Domestic__c=false;
            }
    	}
       
        lockCloneFields(maList);
    }

    public static void populateOracleProjectIds (List <Marketing_Activity__c> newMarketingActivities) {

        Set<Id> marketingCampaignIds = new Set <Id> ();

        for (Marketing_Activity__c marketingActivity : newMarketingActivities) {
            marketingCampaignIds.add(marketingActivity.Marketing_Campaign__c);
        }

        Map <Id, Marketing_Campaign__c> marketingCampaignsMap = new Map <Id, Marketing_Campaign__c> ([SELECT Oracle_Project_Id__c, Oracle_Secondary_Project_Id__c FROM Marketing_Campaign__c WHERE Id IN: marketingCampaignIds]);

        for (Marketing_Activity__c marketingActivity : newMarketingActivities) {
            marketingActivity.Oracle_Project_Id__c = marketingCampaignsMap.get(marketingActivity.Marketing_Campaign__c).Oracle_Project_Id__c;
            marketingActivity.Oracle_Secondary_Project_Id__c = marketingCampaignsMap.get(marketingActivity.Marketing_Campaign__c).Oracle_Secondary_Project_Id__c;
        }
    }


    //START ORACLE INTEGRATION METHODS

    public static void handleAfterInsert(Map <Id, Marketing_Activity__c> oldMap, List<Marketing_Activity__c> newMarketingActivities) {
        Set <Id> marketingActivitiesToSend = new Set<Id> ();
        for (Marketing_Activity__c marketingActivity : newMarketingActivities) {
            if (isReadyToSend(marketingActivity)) {
                marketingActivitiesToSend.add(marketingActivity.Id);
            }

        }
        if (!marketingActivitiesToSend.isEmpty()) {
            insertInOracle(marketingActivitiesToSend);
            changeToSendingState(marketingActivitiesToSend);
        }
    }

    public static void handleAfterUpdate (Map <Id, Marketing_Activity__c> oldMap, List<Marketing_Activity__c> updatedMarketingActivities) {
        Set <Id> newOracleActivities = new Set <Id>();
        Set <Id> existingOracleActivities = new Set <Id>();
        Map <Id, Marketing_Activity__c> lastModifiedByMap = new Map <Id, Marketing_Activity__c> ([SELECT LastModifiedBy.Name FROM Marketing_Activity__c WHERE Id IN: updatedMarketingActivities]); 
        if(!System.isBatch()){
            for (Marketing_Activity__c marketingActivity : updatedMarketingActivities) {
                //We check for two things:
                // 1. If we just changed the status to sending, we don't send it again because we have already changed that
                // 2. If the marketing activity is ready to send
                // 3. We check that if the LastModified user is the Integration User, we don't want to resend anything (recursivity) UNLESS that what has been updated is the Project Id
                // 4. Check that either a relevant field has changed and it's being resent
                if (marketingActivity.Integration_Status__c != 'sending' || isResending(oldMap.get(marketingActivity.Id), marketingActivity)) {
                    if (isReadyToSend(marketingActivity) && (lastModifiedByMap.get(marketingActivity.Id).LastModifiedBy.Name != Label.DataIntegrationUser || marketingActivity.Oracle_Project_Id__c != oldMap.get(marketingActivity.Id).Oracle_Project_Id__c)) {
                        if (hasChangedFields(oldMap.get(marketingActivity.Id), marketingActivity)) {
                            if (String.isNotBlank(marketingActivity.Oracle_Task_Id__c) || String.isNotBlank(marketingActivity.Oracle_Secondary_Task_Id__c)) {
                                existingOracleActivities.add(marketingActivity.Id);
                            } else {
                                newOracleActivities.add(marketingActivity.Id);
                            }
                        }
                    }
                }
            }
            
            if (!newOracleActivities.isEmpty()) {
                insertInOracle(newOracleActivities);
            }
            if (!existingOracleActivities.isEmpty()) {
                updateInOracle(existingOracleActivities);
            }
            
            Set <Id> allActivitiesToSend = new Set <Id> ();
            allActivitiesToSend.addAll(newOracleActivities);
            allActivitiesToSend.addAll(existingOracleActivities);
            changeToSendingState(allActivitiesToSend);

        }
    }

    public static Boolean isReadyToSend (Marketing_Activity__c marketingActivity) {
        return  (marketingActivity.Transfer_to_Oracle__c &&
                (String.isNotBlank(marketingActivity.Oracle_Project_Id__c) || String.isNotBlank(marketingActivity.Oracle_Secondary_Project_Id__c)));
    }

    public static void insertInOracle (Set <Id> newOracleActivities) {
        Database.executeBatch(new MarketingActivityBatchCallout(newOracleActivities),30);
    }

    public static void updateInOracle (Set <Id> existingOracleActivities) {
        Database.executeBatch(new MarketingActivityUpdateBatchCallout(existingOracleActivities),30);
    }

    public static void changeToSendingState(Set <Id> marketingActivityIds) {
        List <Marketing_Activity__c> marketingActivitiesUpdate = new List <Marketing_Activity__c> ();
        for (Id marketingActivityId : marketingActivityIds) {
            marketingActivitiesUpdate.add(new Marketing_Activity__c(Id=marketingActivityId, Integration_Status__c='sending'));
        }
        update marketingActivitiesUpdate;
    }

    public static Boolean hasChangedFields (Marketing_Activity__c oldActivity, Marketing_Activity__c newActivity) {
        
        for (String field : fieldsToTriggerIntegration) {
          if (isFieldChanged(oldActivity, newActivity, field)) {
            return true;
          }
        }
        return false;
    }
    
    public static Boolean isFieldChanged (Marketing_Activity__c oldRecord, Marketing_Activity__c newRecord, String fieldName) {
        return oldRecord.get(fieldName) != newRecord.get(fieldName);
    }

    public static Boolean isResending (Marketing_Activity__c oldRecord, Marketing_Activity__c newRecord) {
        return (oldRecord.Re_send_to_Oracle_for_NewActivity__c != newRecord.Re_send_to_Oracle_for_NewActivity__c) && newRecord.Re_send_to_Oracle_for_NewActivity__c;
    }

    public static void lockCloneFields (list<Marketing_Activity__c> markActList) {
        for(Marketing_Activity__c markAct : markActList) {
            if (markAct.isClone()) {
                markAct.Oracle_Task_Id__c = '';
                markAct.Oracle_Task_Number__c = '';

                markAct.Oracle_Secondary_Task_Id__c = '';
                markAct.Oracle_Secondary_Task_Number__c = '';
            }
        }
    }

    //END ORACLE INTEGRATION METHODS
    
}