force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/Creative_Agency_2__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Agency 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile_Name__c</field>
            <operation>equals</operation>
            <value>Third Party Community User</value>
        </filterItems>
        <infoMessage>Please choose a Customer Portal User</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Marketing_Activities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Creative_Agency_3__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Agency 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile_Name__c</field>
            <operation>equals</operation>
            <value>Third Party Community User</value>
        </filterItems>
        <infoMessage>Please choose a Customer Portal User</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Marketing_Activities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Creative_Agency_4__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Agency 4</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile_Name__c</field>
            <operation>equals</operation>
            <value>Third Party Community User</value>
        </filterItems>
        <infoMessage>Please choose a Customer Portal User</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Marketing_Activities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Creative_Agency_Access_To_Salesforce__c.field-meta.xml
<CustomField>
    <fullName>Creative_Agency_Access_To_Salesforce__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Agency 1</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please choose a Customer Portal User</errorMessage>
        <filterItems>
            <field>User.Profile_Name__c</field>
            <operation>equals</operation>
            <value>Third Party Community User</value>
        </filterItems>
        <infoMessage>Please choose a Customer Portal User</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Marketing_Activities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmailMarketingActivity.cls
public class EmailMarketingActivity {
    
    public Static void SendEmailMarketingActivity(List<Marketing_Activity__c> listMarketing){

        List<Messaging.SingleEmailMessage> allMessag = new List<Messaging.SingleEmailMessage>();
        List<String> sendTo = new List<String>();

        for(Marketing_Activity__c marck : listMarketing){

            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

            
            if(marck.Creative_Agency_Access_To_Salesforce__c != null){ 
                sendTo.add(marck.Creative_Agency_Access_To_Salesforce__c);  
            }

            if(marck.Creative_Agency_2__c != null){ 
                sendTo.add(marck.Creative_Agency_2__c);  
            }

            if(marck.Creative_Agency_3__c != null){ 
                sendTo.add(marck.Creative_Agency_3__c);  
            }

            if(marck.Creative_Agency_4__c != null){ 
                sendTo.add(marck.Creative_Agency_4__c);  
            }

            if(sendTo.size() != 0 && sendTo != NULL){
                
                mail.setToAddresses(sendTo);
                
                mail.setSubject('Email Marketing Activity');
                String body = '<br/>';
                       body +='Marketing Activity Name :   '  + marck.Name +  '<br/>';
                       body +='<br/>';
                       body += System.Url.getSalesforceBaseUrl().toExternalForm()
                    +'/'+marck.Id +'';
                
                mail.setHtmlBody(body);
                mail.setSaveAsActivity(false); 
                allMessag.add(mail);
            }
                    
        }

        Messaging.sendEmail(allMessag);
        System.debug('user mail id '+allMessag);
        
    }
    
}