force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/Re_send_to_Oracle_for_NewActivity__c.field-meta.xml
<CustomField>
    <fullName>Re_send_to_Oracle_for_NewActivity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Re-send to Oracle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/maCreatescheduledBatchable.cls
global class maCreatescheduledBatchable implements Schedulable {

   Map<Id, Marketing_Activity__c> maMap = new Map<Id, Marketing_Activity__c>([SELECT Id, Name FROM Marketing_Activity__c where Re_send_to_Oracle_for_NewActivity__c=True]);

   global void execute(SchedulableContext sc) {
   
   System.debug('ActivityId :'+maMap.keySet());
      MarketingActivityBatchCallout mabatch = new MarketingActivityBatchCallout(maMap.keySet()); 
      database.executebatch(mabatch);
   }
}