force-app/main/default/objects/Brand_Activity__c/Brand_Activity__c.object-meta.xml
<CustomObject>
    <label>Brand Activity</label>
    <nameField>
        <label>Brand Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Activity__c/fields/Approved_Villages__c.field-meta.xml
<CustomField>
    <fullName>Approved_Villages__c</fullName>
    <label>Approved Villages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Village</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only select Brand Accounts</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Activities</relationshipLabel>
    <relationshipName>Brand_Village_Activities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Brand_Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Brand_Activity_Type__c</fullName>
    <label>Brand Activity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>New Store</fullName>
            </value>
            <value>
                <fullName>Pop Up</fullName>
            </value>
            <value>
                <fullName>Refit</fullName>
            </value>
            <value>
                <fullName>Product Launch</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Expected_Average_Spend__c.field-meta.xml
<CustomField>
    <fullName>Expected_Average_Spend__c</fullName>
    <label>Expected Average Spend</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Expected_Footfall__c.field-meta.xml
<CustomField>
    <fullName>Expected_Footfall__c</fullName>
    <label>Expected Footfall</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Expected_New_Members__c.field-meta.xml
<CustomField>
    <fullName>Expected_New_Members__c</fullName>
    <label>Expected New Members</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Expected_Sales__c.field-meta.xml
<CustomField>
    <fullName>Expected_Sales__c</fullName>
    <label>Expected Sales</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Marketing_Activity_Budget__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity_Budget__c</fullName>
    <label>Marketing Activity Budget</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Marketing_Activity_Cost__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity_Cost__c</fullName>
    <label>Marketing Activity Cost</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Campaign</label>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Brand Activities</relationshipLabel>
    <relationshipName>Brand_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Reach__c.field-meta.xml
<CustomField>
    <fullName>Reach__c</fullName>
    <label>Reach</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Village.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bicester</fullName>
    </customValue>
    <customValue>
        <fullName>Fidenza</fullName>
    </customValue>
    <customValue>
        <fullName>Ingolstadt</fullName>
    </customValue>
    <customValue>
        <fullName>Kildare</fullName>
    </customValue>
    <customValue>
        <fullName>La Roca</fullName>
    </customValue>
    <customValue>
        <fullName>Las Rozas</fullName>
    </customValue>
    <customValue>
        <fullName>La Vallée</fullName>
    </customValue>
    <customValue>
        <fullName>Maasmechelen</fullName>
    </customValue>
    <customValue>
        <fullName>Shanghai</fullName>
    </customValue>
    <customValue>
        <fullName>Suzhou</fullName>
    </customValue>
    <customValue>
        <fullName>Wertheim</fullName>
    </customValue>
    <description>A list of all the villages</description>
    <masterLabel>Village</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/massEditBrandActivitiesController.cls
Public Class massEditBrandActivitiesController{

    public id recordId {get;set;}
    public list<Brand_Activity__c> BAs {get;set;}
    public list<Wrapper> wBAstoEdit {get;set;}
    public Brand_Activity__c selectOption {get;set;}
    public String selectedStatus {get;set;}
    public String objName {get;set;}


    Public massEditBrandActivitiesController(ApexPages.StandardController standardController){
    }


    Public massEditBrandActivitiesController(ApexPages.StandardSetController stdcontroller){

        selectedStatus = '';
        recordId = ApexPages.currentPage().getParameters().get('id');
        objName = recordId.getSObjectType().getDescribe().getName();

        selectOption = new Brand_Activity__c();
        wBAstoEdit = new list<Wrapper>();

        if(objName == 'Marketing_Campaign__c'){
            BAs = [SELECT ID, Name, Status__c, Brand__c,CurrencyIsoCode,Expected_Average_Spend__c,Expected_Sales__c,Marketing_Activity_Cost__c,Expected_New_Members__c,Reach__c,Expected_Footfall__c,Marketing_Activity_Budget__c,Marketing_Campaign__c,Brand_Activity_Type__c,Approved_Villages__c,Details__c  FROM Brand_Activity__c WHERE Marketing_Campaign__c =:recordId ];
        }
        else if (objName == 'Account'){
            BAs = [SELECT ID, Name, Status__c, Brand__c,CurrencyIsoCode,Expected_Average_Spend__c,Expected_Sales__c,Marketing_Activity_Cost__c,Expected_New_Members__c,Reach__c,Expected_Footfall__c,Marketing_Activity_Budget__c,Marketing_Campaign__c,Brand_Activity_Type__c,Approved_Villages__c,Details__c  FROM Brand_Activity__c WHERE Brand__c =:recordId ];
        }


        for(Brand_Activity__c BA : BAs){
            wBAstoEdit.add(new Wrapper(BA));
        }
        system.debug('wBAstoEdit' + wBAstoEdit);

    }


    Public Pagereference selectAll() {
        for(Wrapper wrapper : wBAstoEdit){
            wrapper.selected = true;
        }
     
    //PageReference pageRef = new PageReference('/'+recordId);
        return null;
    }


    Public Pagereference deselectAll() {
      for(Wrapper wrapper : wBAstoEdit){
            wrapper.selected = false;
        }
     
    //PageReference pageRef = new PageReference('/'+recordId);
        return null;
    }


    Public Pagereference saveSelected() {

      try{
        list<Brand_Activity__c> Updates = new List<Brand_Activity__c>();
            for(Wrapper wrapper : wBAstoEdit) {
                    if(wrapper.selected == true) {
                        Updates.add(wrapper.theBA); 
                    }
            }        
        update Updates;        
        PageReference pageRef = new PageReference('/'+recordId);
        return pageRef;}
        catch (exception e){
          return null;
        }
    }


    Public Pagereference Cancel() {
    PageReference pageRef = new PageReference('/'+recordId);
        return pageRef;
    }


    Public Pagereference setAllStatus() {
        for(Wrapper wrapper : wBAstoEdit){
            wrapper.theBA.Status__c = selectOption.Status__c;
        }
     
    //PageReference pageRef = new PageReference('/'+recordId);
        return null;
    }


    Public Pagereference setAllStatus2() {
        for(Wrapper wrapper : wBAstoEdit){
            wrapper.theBA.Status__c = selectedStatus;
        }
     
    //PageReference pageRef = new PageReference('/'+recordId);
        return null;
    }



    public class Wrapper{
        public Brand_Activity__c theBA {get; set;}
        public Boolean selected {get; set;}

        public Wrapper(Brand_Activity__c ba) {
            theBA = ba;
            selected = false;
        }

        public Wrapper(Brand_Activity__c ba, boolean bool) {
            theBA = ba;
            selected = bool;

        }
    }


    public class reassignmentException extends Exception {}

    
}