force-app/main/default/objects/Brand_Activity__c/Brand_Activity__c.object-meta.xml
<CustomObject>
    <label>Brand Activity</label>
    <nameField>
        <label>Brand Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Activity__c/fields/Expected_Average_Spend__c.field-meta.xml
<CustomField>
    <fullName>Expected_Average_Spend__c</fullName>
    <label>Expected Average Spend</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Expected_Footfall__c.field-meta.xml
<CustomField>
    <fullName>Expected_Footfall__c</fullName>
    <label>Expected Footfall</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Expected_New_Members__c.field-meta.xml
<CustomField>
    <fullName>Expected_New_Members__c</fullName>
    <label>Expected New Members</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Expected_Sales__c.field-meta.xml
<CustomField>
    <fullName>Expected_Sales__c</fullName>
    <label>Expected Sales</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Marketing_Activity_Budget__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity_Budget__c</fullName>
    <label>Marketing Activity Budget</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Marketing_Activity_Cost__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity_Cost__c</fullName>
    <label>Marketing Activity Cost</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Reach__c.field-meta.xml
<CustomField>
    <fullName>Reach__c</fullName>
    <label>Reach</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Split_Type__c.field-meta.xml
<CustomField>
    <fullName>Split_Type__c</fullName>
    <label>Split Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/In_Village_Brand_Activity__c/In_Village_Brand_Activity__c.object-meta.xml
<CustomObject>
    <label>In Village Brand Activity</label>
    <nameField>
        <label>In Village Brand Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>In Village Brand Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/In_Village_Brand_Activity__c/fields/Brand_Activity__c.field-meta.xml
<CustomField>
    <fullName>Brand_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Activity</label>
    <referenceTo>Brand_Activity__c</referenceTo>
    <relationshipLabel>In Village Brand Activities</relationshipLabel>
    <relationshipName>In_Village_Brand_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/In_Village_Brand_Activity__c/fields/Expected_Average_Spend__c.field-meta.xml
<CustomField>
    <fullName>Expected_Average_Spend__c</fullName>
    <label>Expected Average Spend</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/In_Village_Brand_Activity__c/fields/Expected_Footfall__c.field-meta.xml
<CustomField>
    <fullName>Expected_Footfall__c</fullName>
    <label>Expected Footfall</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/In_Village_Brand_Activity__c/fields/Expected_New_Members__c.field-meta.xml
<CustomField>
    <fullName>Expected_New_Members__c</fullName>
    <label>Expected New Members</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/In_Village_Brand_Activity__c/fields/Expected_Sales__c.field-meta.xml
<CustomField>
    <fullName>Expected_Sales__c</fullName>
    <label>Expected Sales</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/In_Village_Brand_Activity__c/fields/Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Activity</label>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipLabel>In Village Brand Activities</relationshipLabel>
    <relationshipName>In_Village_Brand_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/In_Village_Brand_Activity__c/fields/Marketing_Activity_Budget__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity_Budget__c</fullName>
    <label>Marketing Activity Budget</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/In_Village_Brand_Activity__c/fields/Marketing_Activity_Cost__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Activity_Cost__c</fullName>
    <label>Marketing Activity Cost</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/In_Village_Brand_Activity__c/fields/Reach__c.field-meta.xml
<CustomField>
    <fullName>Reach__c</fullName>
    <label>Reach</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/In_Village_Brand_Activity__c/fields/Split_Type__c.field-meta.xml
<CustomField>
    <fullName>Split_Type__c</fullName>
    <label>Split Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/In_Village_Brand_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>..</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/Expected_Average_Spend__c.field-meta.xml
<CustomField>
    <fullName>Expected_Average_Spend__c</fullName>
    <inlineHelpText>The expected average spend for each customer responding to this activity</inlineHelpText>
    <label>Expected Average Spend</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Expected_Footfall__c.field-meta.xml
<CustomField>
    <fullName>Expected_Footfall__c</fullName>
    <inlineHelpText>The expected footfall which will be generated as a result of this activity</inlineHelpText>
    <label>Expected Footfall</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Expected_New_Members__c.field-meta.xml
<CustomField>
    <fullName>Expected_New_Members__c</fullName>
    <inlineHelpText>The expected new members which will be recruited as a result of this activity</inlineHelpText>
    <label>Expected New Members</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Expected_Sales__c.field-meta.xml
<CustomField>
    <fullName>Expected_Sales__c</fullName>
    <inlineHelpText>The expected sales which will be generated as a result of this activity</inlineHelpText>
    <label>Expected Sales</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Reach__c.field-meta.xml
<CustomField>
    <fullName>Reach__c</fullName>
    <inlineHelpText>Actual potential customers that are reached by the activity</inlineHelpText>
    <label>Reach</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Split_Type__c.field-meta.xml
<CustomField>
    <fullName>Split_Type__c</fullName>
    <label>Split Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/massEditInVilBrandActsController.cls
Public Class massEditInVilBrandActsController{

    public id recordId {get;set;}
    public list<In_Village_Brand_Activity__c> inVilBAs {get;set;}
    public list<Wrapper> wBAstoEdit {get;set;}
    public In_Village_Brand_Activity__c selectOption {get;set;}
    //public list<SelectOption> options {get;set;}
    public String selectedStatus {get;set;}
    public String objName {get;set;}


    Public massEditInVilBrandActsController(ApexPages.StandardController standardController){
    }


    Public massEditInVilBrandActsController(ApexPages.StandardSetController stdcontroller){

    selectedStatus = '';
    selectOption = new In_Village_Brand_Activity__c();
    wBAstoEdit = new list<Wrapper>();
    recordId = ApexPages.currentPage().getParameters().get('id');
    objName = recordId.getSObjectType().getDescribe().getName();

    if(objName == 'Brand_Activity__c'){
       inVilBAs = [SELECT ID, Name, Status__c,Marketing_Activity_Budget__c,Expected_Footfall__c,Reach__c,Expected_New_Members__c,Marketing_Activity_Cost__c,Expected_Sales__c,Expected_Average_Spend__c,Split_Type__c FROM In_Village_Brand_Activity__c WHERE Brand_Activity__c =:recordId ]; 
    }
    else if (objName == 'Marketing_Activity__c'){
        inVilBAs = [SELECT ID, Name, Status__c,Marketing_Activity_Budget__c,Expected_Footfall__c,Reach__c,Expected_New_Members__c,Marketing_Activity_Cost__c,Expected_Sales__c,Expected_Average_Spend__c,Split_Type__c FROM In_Village_Brand_Activity__c WHERE Marketing_Activity__c =:recordId ]; 
    }
    system.debug('BAs' + inVIlBAs);

      for(In_Village_Brand_Activity__c BA : inVilBAs){
        wBAstoEdit.add(new Wrapper(BA));
      }
    system.debug('wBAstoEdit' + wBAstoEdit);
    }


    Public Pagereference selectAll() {
        for(Wrapper wrapper : wBAstoEdit){
            wrapper.selected = true;
        }
     
    //PageReference pageRef = new PageReference('/'+recordId);
        return null;
    }

    Public Pagereference deselectAll() {
      for(Wrapper wrapper : wBAstoEdit){
            wrapper.selected = false;
        }
     
    //PageReference pageRef = new PageReference('/'+recordId);
        return null;
    }

    Public Pagereference saveSelected() {

      try{
        list<In_Village_Brand_Activity__c> Updates = new List<In_Village_Brand_Activity__c>();
            for(Wrapper wrapper : wBAstoEdit) {
                    if(wrapper.selected == true) {
                        Updates.add(wrapper.theBA); 
                    }
            }        
        update Updates;        
        PageReference pageRef = new PageReference('/'+recordId);
        return pageRef;}
        catch (exception e){
          return null;
        }
    }

    Public Pagereference Cancel() {
    PageReference pageRef = new PageReference('/'+recordId);
        return pageRef;
    }

    Public Pagereference setAllStatus() {
        for(Wrapper wrapper : wBAstoEdit){
            wrapper.theBA.Status__c = selectOption.Status__c;
        }
     
    //PageReference pageRef = new PageReference('/'+recordId);
        return null;
    }

    Public Pagereference setAllStatus2() {
        for(Wrapper wrapper : wBAstoEdit){
            wrapper.theBA.Status__c = selectedStatus;
        }
     
    //PageReference pageRef = new PageReference('/'+recordId);
        return null;
    }


    public class Wrapper{
        public In_Village_Brand_Activity__c theBA {get; set;}
        public Boolean selected {get; set;}

        public Wrapper(In_Village_Brand_Activity__c ba) {
            theBA = ba;
            selected = false;
        }

        public Wrapper(In_Village_Brand_Activity__c ba, boolean bool) {
            theBA = ba;
            selected = bool;

        }
    }

    public List<SelectOption> getItems() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('US','US'));
        options.add(new SelectOption('CANADA','Canada'));
        options.add(new SelectOption('MEXICO','Mexico'));
        return options;
    }

    public class reassignmentException extends Exception {}
}