force-app/main/default/objects/Lead/fields/Expected_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Expected_Arrival__c</fullName>
    <description>(B2T) Will be transferred to the Group Booking Object</description>
    <inlineHelpText>This Time the booker entered on the web form</inlineHelpText>
    <label>Expected Arrival</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Expected_Departure__c.field-meta.xml
<CustomField>
    <fullName>Expected_Departure__c</fullName>
    <description>(B2T) MICE web capture field</description>
    <label>Expected Departure</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Group_Type__c.field-meta.xml
<CustomField>
    <fullName>Group_Type__c</fullName>
    <description>(B2T) will be transferred to the Group Booking object</description>
    <label>Group Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Leisure</fullName>
            </value>
            <value>
                <fullName>MICE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Name_of_Event__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Event__c</fullName>
    <description>(B2T) The name of the event that will be transferred to the Group Booking</description>
    <label>Name of Event</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Number_of_Visitors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Visitors__c</fullName>
    <description>(B2T) MICE Capture field</description>
    <label>Expected Number of Visitors</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Quick_Convert__c.field-meta.xml
<CustomField>
    <fullName>Quick_Convert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quick Convert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Village_of_Visit_c__c.field-meta.xml
<CustomField>
    <fullName>Village_of_Visit_c__c</fullName>
    <description>(B2T) MICE Capture Field</description>
    <label>Primary Village of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/reassignToQueueOwnerTest.cls
@isTest
global class reassignToQueueOwnerTest{

        private static testMethod void Test1() {
 
        
        list <reassignToQueueOwner.leadDetails> detailList = new list<reassignToQueueOwner.leadDetails>();    
        reassignToQueueOwner.leadDetails detail = new reassignToQueueOwner.leadDetails();
                
                Recordtype myRec = [SELECT id FROM RecordType WHERE name = 'Group Booking Lead' AND sobjectType = 'Lead'];
                               
                Lead L = new Lead();
                L.recordtypeid = myRec.id;
                L.company = 'test Lead';
                L.Group_Type__c = 'MICE';
                L.FirstName = 'test';
                L.LastName = 'user';
                L.email = 'dchilds@valueretail.com';
                L.phone = '0987654321';
                L.Name_Of_Event__c = 'Test Event';
                L.Village_of_Visit_c__c = 'Bicester';
                L.Expected_Arrival__c = system.now();
                L.Expected_Departure__c = system.now()+1;
                L.Number_of_Visitors__c = 10;
                L.Quick_Convert__c = true;
                insert L;
                
                detail.Leadid = L.id;
                detail.PrimaryVillageofInterest = L.Village_of_Visit_c__c;
                detail.leadGroupType = L.Group_Type__c;
            
                detailList.add(detail);
 
                Test.startTest();
                reassignToQueueOwner.reassignOwner(detailList);
                Test.stopTest();                
                
                Group Grp = [Select Id,Name from Group where type='Queue' and Name = 'MICE Lead Queue - Bicester' LIMIT 1];
                Lead lead = [SELECT id,name,ownerid FROM Lead WHERE Id =:L.id];
                
                system.assert(lead.ownerid == Grp.id, 'wrong');
            }             
}