force-app/main/default/objects/Lead/fields/Expected_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Expected_Arrival__c</fullName>
    <description>(B2T) Will be transferred to the Group Booking Object</description>
    <inlineHelpText>This Time the booker entered on the web form</inlineHelpText>
    <label>Expected Arrival</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Expected_Departure__c.field-meta.xml
<CustomField>
    <fullName>Expected_Departure__c</fullName>
    <description>(B2T) MICE web capture field</description>
    <label>Expected Departure</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Group_Type__c.field-meta.xml
<CustomField>
    <fullName>Group_Type__c</fullName>
    <description>(B2T) will be transferred to the Group Booking object</description>
    <label>Group Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Leisure</fullName>
            </value>
            <value>
                <fullName>MICE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Name_of_Event__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Event__c</fullName>
    <description>(B2T) The name of the event that will be transferred to the Group Booking</description>
    <label>Name of Event</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Number_of_Visitors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Visitors__c</fullName>
    <description>(B2T) MICE Capture field</description>
    <label>Expected Number of Visitors</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Quick_Convert__c.field-meta.xml
<CustomField>
    <fullName>Quick_Convert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quick Convert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Village_of_Visit_c__c.field-meta.xml
<CustomField>
    <fullName>Village_of_Visit_c__c</fullName>
    <description>(B2T) MICE Capture Field</description>
    <label>Primary Village of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Visitors_Country_of_Origin__c.field-meta.xml
<CustomField>
    <fullName>Visitors_Country_of_Origin__c</fullName>
    <description>(B2T) captured from MICE web form</description>
    <label>Visitors Country of Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>ALAND ISLANDS</fullName>
            </value>
            <value>
                <fullName>ALBANIA</fullName>
            </value>
            <value>
                <fullName>ALGERIA</fullName>
            </value>
            <value>
                <fullName>AMERICAN SAMOA</fullName>
            </value>
            <value>
                <fullName>ANDORRA</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTARCTICA</fullName>
            </value>
            <value>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </value>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARMENIA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>AZERBAIJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BARBADOS</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDA</fullName>
            </value>
            <value>
                <fullName>BHUTAN</fullName>
            </value>
            <value>
                <fullName>BOLIVIA, PLURINATIONAL STATE OF</fullName>
            </value>
            <value>
                <fullName>BONAIRE, SAINT EUSTATIUS AND SABA</fullName>
            </value>
            <value>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/emailLeadQueuesAfterFailedQuickCnvtTest.cls
@isTest
global class emailLeadQueuesAfterFailedQuickCnvtTest{

        private static testMethod void Test1() {
 
        
        list <emailLeadQueuesAfterFailedQuickConvert.sendEmailDetails> listofdetails = new list<emailLeadQueuesAfterFailedQuickConvert.sendEmailDetails>();    
        emailLeadQueuesAfterFailedQuickConvert.sendEmailDetails detail = new emailLeadQueuesAfterFailedQuickConvert.sendEmailDetails();
                
                Recordtype myRec = [SELECT id FROM RecordType WHERE name = 'Group Booking Lead' AND sobjectType = 'Lead'];
                               
                Lead L = new Lead();
                L.recordtypeid = myRec.id;
                L.company = 'test Lead';
                L.FirstName = 'test';
                L.LastName = 'user';
                L.email = 'dchilds@test.com';
                L.phone = '0987654321';
                L.Group_Type__c = 'MICE';
                L.Name_Of_Event__c = 'Test Event';
                L.Village_of_Visit_c__c = 'Bicester';
                L.Expected_Arrival__c = system.now();
                L.Expected_Departure__c = system.now()+1;
                L.Number_of_Visitors__c = 10;
                L.Visitors_Country_of_Origin__c = 'Visitors_Country_of_Origin__c';
                L.Quick_Convert__c = true;
                insert L;
            
                detail.Leadid = L.id;
                detail.PrimaryVillageofInterest = L.Village_of_Visit_c__c;
            
                listofdetails.add(detail);
 
                Test.startTest();
                emailLeadQueuesAfterFailedQuickConvert.id(listofdetails);
                Test.stopTest();                
                
            }             
}