force-app/main/default/objects/Opportunity/fields/EU_Brand_Captain__c.field-meta.xml
<CustomField>
    <fullName>EU_Brand_Captain__c</fullName>
    <description>This is the EU Brand Captain on the Brand Account</description>
    <formula>Account.EU_Brand_Captain__r.FirstName +&apos; &apos;+ Account.EU_Brand_Captain__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This is the EU Brand Captain on the Brand Account</inlineHelpText>
    <label>EU Brand Captain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Negotiator_for_VR__c.field-meta.xml
<CustomField>
    <fullName>Lead_Negotiator_for_VR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Negotiator for VR</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Negotiator_for_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Auto populated from Village and Brand</description>
    <label>Village Presence</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Village Presence records must be linked to Brand accounts. Please ensure you are not linking the Deal/Village Presence to a Group</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Village Presences</relationshipLabel>
    <relationshipName>Village_Presences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence__c/fields/EU_Brand_Captain__c.field-meta.xml
<CustomField>
    <fullName>EU_Brand_Captain__c</fullName>
    <label>EU Brand Captain</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DealUtilities.cls
public with sharing class DealUtilities {
	
	public static string ReassignDealOwnertoLeadNegotiator(string currentOwner){
		
		string returnValue = '';		
		
		try {		

			string soql = '';
			User u = null;
			string userId = '';
			DateTime lastModified = system.now().addSeconds(-1200);
			
			soql = 'Select Id, OwnerId, Lead_Negotiator_for_VR__c,' ;
			soql += 'Village_Presence__r.Brand__r.EU_Brand_Captain__c,';
			soql += 'Lead_Negotiator_for_VR__r.IsActive,';
			soql += 'Village_Presence__r.Brand__r.EU_Brand_Captain__r.IsActive';
			soql +=	' from Opportunity';									
			soql += ' where (Lead_Negotiator_for_VR__r.IsActive = true';										 
			soql += ' or Village_Presence__r.Brand__r.EU_Brand_Captain__r.IsActive = true)';							
			if (string.isnotBlank(currentOwner)){
				u = [Select Id from User where UserName = :currentOwner limit 1];
				
				if (u != null){
					userId = u.Id;
					soql += ' and OwnerId = :userId';
				} else {
					returnValue = 'User not found, no records processed';
				}		 
			}
			if (!test.isRunningTest())
				soql += ' and SystemModStamp < :lastModified';
            
            soql += ' limit 400';
            
			if (string.isBlank(returnValue)){
				
				list<Opportunity> dealList = database.query(soql);
				
				if (!dealList.isEmpty()){
					for (Opportunity deal :dealList){
system.debug('@@@ deal  - ' + deal);
						if(string.isnotBlank(deal.Lead_Negotiator_for_VR__c)){
							if (deal.Lead_Negotiator_for_VR__r.IsActive)
								deal.OwnerId =  deal.Lead_Negotiator_for_VR__c;
						} else if (string.isnotBlank(deal.Village_Presence__r.Brand__r.EU_Brand_Captain__c)){
							if(deal.Village_Presence__r.Brand__r.EU_Brand_Captain__r.IsActive)
								deal.OwnerId = deal.Village_Presence__r.Brand__r.EU_Brand_Captain__c;
						}															
					}
					
					update dealList;
					returnValue = dealList.size() + ' Processed.';
				}
			}
		} catch(exception e){
			
			system.debug('ERROR ...ERROR ... ERROR ' + e.getMessage() + ' : ' + e.getStackTraceString());			
			returnValue = 'ERROR ...ERROR ... ERROR ' + e.getMessage() + ' : ' + e.getStackTraceString();
		}		
		
		return returnvalue;
		
	}
	    
}