force-app/main/default/objects/Opportunity/fields/Expected_Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Open_Date__c</fullName>
    <inlineHelpText>The date that the brand is expected to open its doors and begin trading</inlineHelpText>
    <label>Expected Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ideal_Size__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Size__c</fullName>
    <inlineHelpText>If a specific unit is not nominated then use this field to specify the ideal size this brand will be using in the size metric specific to the village</inlineHelpText>
    <label>Ideal Size</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Income_Rating__c.field-meta.xml
<CustomField>
    <fullName>Income_Rating__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>This is normally calculated based on the ratings attached to the village if the Income yield is known otherwise enter the rating to be applied to this brand in this village</inlineHelpText>
    <label>Income Rating</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Income__c.field-meta.xml
<CustomField>
    <fullName>Projected_Income__c</fullName>
    <formula>Projected_Income_Local__c  *  FX_Rate__c</formula>
    <label>1st Year Projected Income</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Income_Local__c.field-meta.xml
<CustomField>
    <fullName>Projected_Income_Local__c</fullName>
    <formula>Projected_Sales_Local__c  *  Projected_Return_Local__c</formula>
    <label>1st Year Proj. Income TO/Royalty (Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Income_Yield_Local__c.field-meta.xml
<CustomField>
    <fullName>Projected_Income_Yield_Local__c</fullName>
    <formula>Projected_Income_Local__c  /  (Effective_Size__c *  SF__c)</formula>
    <label>1st Year Proj. TO/Royalty Yield (Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Return_Local__c.field-meta.xml
<CustomField>
    <fullName>Projected_Return_Local__c</fullName>
    <inlineHelpText>The Projected Return based on the Sales and Income Projections in Local currency.</inlineHelpText>
    <label>1st Year Projected Income % (Local)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Sales__c.field-meta.xml
<CustomField>
    <fullName>Projected_Sales__c</fullName>
    <formula>Projected_Sales_Local__c  *  FX_Rate__c</formula>
    <label>1st Year Projected Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Sales_Local__c.field-meta.xml
<CustomField>
    <fullName>Projected_Sales_Local__c</fullName>
    <formula>Projected_Sales_Yield_Local_Converted__c *  Effective_Size__c</formula>
    <label>1st Year Projected Sales (Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Sales_Yield_Local__c.field-meta.xml
<CustomField>
    <fullName>Projected_Sales_Yield_Local__c</fullName>
    <inlineHelpText>The Annualized Sales Yield in Village Currency (per Sq.ft for Bicester and per Sq. mtr for all other villages)</inlineHelpText>
    <label>1st Year Projected Sales Yield (Local)</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Rating__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rating__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>This is normally calculated based on the ratings attached to the village if the Sales yield is known otherwise enter the rating to be applied to this brand in this village</inlineHelpText>
    <label>Sales Rating</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the actual village where this opportunity exists</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village_Rating__c/Village_Rating__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold Village Rating League Tables used in the automatic calculation of Ratings as part of the Strategic Brand Mix</description>
    <label>Village Ratings</label>
    <nameField>
        <label>Village Rating Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Rating__c/fields/Range_Maximum__c.field-meta.xml
<CustomField>
    <fullName>Range_Maximum__c</fullName>
    <defaultValue>0.00</defaultValue>
    <inlineHelpText>Enter the maximum or upper value for this range</inlineHelpText>
    <label>Range Maximum</label>
    <precision>13</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village_Rating__c/fields/Range_Minimum__c.field-meta.xml
<CustomField>
    <fullName>Range_Minimum__c</fullName>
    <defaultValue>0.00</defaultValue>
    <inlineHelpText>Enter the minimum value or start value for this range</inlineHelpText>
    <label>Range Minimum</label>
    <precision>13</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village_Rating__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <inlineHelpText>Enter the rating if the yield falls into this range</inlineHelpText>
    <label>Rating</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village_Rating__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <inlineHelpText>Select the Village for this yield line item</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipName>Village_Yields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Village_Rating__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <inlineHelpText>Enter the year to which this yield item applies</inlineHelpText>
    <label>Year</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village_Rating__c/fields/Yield_Classification__c.field-meta.xml
<CustomField>
    <fullName>Yield_Classification__c</fullName>
    <inlineHelpText>Select  the classification for this yield item</inlineHelpText>
    <label>Yield Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Income</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Rating__c/fields/Yield_Type__c.field-meta.xml
<CustomField>
    <fullName>Yield_Type__c</fullName>
    <inlineHelpText>Enter the type of yield, either Income or Sales</inlineHelpText>
    <label>Yield Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Actual</fullName>
            </value>
            <value>
                <fullName>Budget</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityRatingCalculatorTest.cls
@isTest (seeAllData=true)
private class OpportunityRatingCalculatorTest {

    static testMethod void testRatingUpdate() {


        Account testAccount = TestDataGenerator.setupB2BAccount(1, true);
        Village__c ratedVillage = TestDataGenerator.setupVillage(true);
        Village__c unratedVillage = TestDataGenerator.setupVillage(false);
        unratedVillage.Village_Code__c = 'ZY';
        unratedVillage.Name = 'UNRATEDVILLAGE';
        insert unratedVillage;
        
        List<Village_Rating__c> ratingList = new List<Village_Rating__c>();
        for (Integer i = 1; i <= 5; i++) {
        	Village_Rating__c rating = setupVillageRating(i, 'Income', ratedVillage.Id);
        	ratingList.add(rating);
        }
        for (Integer i = 1; i <= 10; i++) {
        	Village_Rating__c rating = setupVillageRating(i, 'Sales', ratedVillage.Id);
        	ratingList.add(rating);
        }
        insert ratingList;
        
        Opportunity ratedOpp = new Opportunity(Village__c = ratedVillage.Id, AccountId = testAccount.Id,
        									   Name = 'TESTOPP1', CloseDate = system.today(), Expected_Open_Date__c = system.today().addDays(7),
        									   StageName = 'Pipeline');

        Opportunity unratedOpp = new Opportunity(Village__c = unratedVillage.Id, AccountId = testAccount.Id,
        									     Name = 'TESTOPP2', CloseDate = system.today(), Expected_Open_Date__c = system.today().addDays(7),
        									     StageName = 'Pipeline');

        List<Opportunity> oppInsertList = new List<Opportunity> {ratedOpp, unratedOpp};
        test.startTest();
        insert oppInsertList;
        test.stopTest();
        
        List<Opportunity> updatedOppList1 = [SELECT Id, Name, Income_Rating__c, Sales_Rating__c
        						   	   		 FROM Opportunity
        						   	   		 WHERE Id IN :oppInsertList ORDER BY Name LIMIT 2];
        

        system.assertEquals(0, updatedOppList1.get(0).Income_Rating__c);
        system.assertEquals(0, updatedOppList1.get(0).Sales_Rating__c);
        system.assertEquals(0, updatedOppList1.get(1).Income_Rating__c);
        system.assertEquals(0, updatedOppList1.get(1).Sales_Rating__c);
        
        ratedOpp.Projected_Sales_Yield_Local__c = 5000;
        ratedOpp.Projected_Return_Local__c = 30;
        ratedOpp.Ideal_Size__c = 1;  // therefore projected sales =5000 (5000 x 1), projected income = 1500 (5000 x 0.3)

        
        update oppInsertList;
        
        List<Opportunity> updatedOppList2 = [SELECT Id, Name, Income_Rating__c, Sales_Rating__c,
        									 projected_sales_local__c, projected_income_local__c,
        									 projected_income_yield_local__c,
        									 projected_sales__c, projected_income__c
        						   	   		 FROM Opportunity
        						   	   		 WHERE Id = :ratedOpp.Id];
        
        system.assertEquals(ratedOpp.Name, updatedOppList2.get(0).Name);
        system.assertEquals(2, updatedOppList2.get(0).Income_Rating__c);
        system.assertEquals(6, updatedOppList2.get(0).Sales_Rating__c);
     
    }
    
    private static Village_Rating__c setupVillageRating(Integer identifier, String ratingType, Id villageId) {
    	Integer rangeMin = (identifier - 1) * 1000;
    	Integer rangeMax = identifier * 1000;
    	Integer year = system.today().year();
    	Village_Rating__c rating = new Village_Rating__c(Village__c = villageId,
    													 Range_Minimum__c = rangeMin,
    													 Range_Maximum__c = rangeMax,
    													 Rating__c = identifier,
    													 Year__c = year,
    													 Yield_Classification__c = ratingType,
    													 Yield_Type__c = 'Budget');
    	return rating;
    }

}