force-app/main/default/objects/Opportunity/fields/Ideal_Size__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Size__c</fullName>
    <inlineHelpText>If a specific unit is not nominated then use this field to specify the ideal size this brand will be using in the size metric specific to the village</inlineHelpText>
    <label>Ideal Size</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Return_Local__c.field-meta.xml
<CustomField>
    <fullName>Projected_Return_Local__c</fullName>
    <inlineHelpText>The Projected Return based on the Sales and Income Projections in Local currency.</inlineHelpText>
    <label>1st Year Projected Income % (Local)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Sales_Yield_Local__c.field-meta.xml
<CustomField>
    <fullName>Projected_Sales_Yield_Local__c</fullName>
    <inlineHelpText>The Annualized Sales Yield in Village Currency (per Sq.ft for Bicester and per Sq. mtr for all other villages)</inlineHelpText>
    <label>1st Year Projected Sales Yield (Local)</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Unit assigned to this opportunity, this is synchronized with the Unit on the Contract when the Unit is formally committed to the brand</inlineHelpText>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Village__c</field>
            <operation>equals</operation>
            <valueField>$Source.Village__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the actual village where this opportunity exists</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the detail of all units in VR Villages</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Size_GEA__c.field-meta.xml
<CustomField>
    <fullName>Size_GEA__c</fullName>
    <inlineHelpText>Enter the Gross External Area (GEA) of the unit in square meters</inlineHelpText>
    <label>Size (GEA)</label>
    <precision>13</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <inlineHelpText>Select the value that best describes the status of the Unit</inlineHelpText>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Suggested</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>Refit</fullName>
            </value>
            <value>
                <fullName>Do not use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>...</description>
    <inlineHelpText>Select the Village where this unit lives</inlineHelpText>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/B2B_Chatter_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>B2B_Chatter_Group_Name__c</fullName>
    <description>Defines the chatter group to post to when an event is created which mentions the village.</description>
    <inlineHelpText>Defines the chatter group to post to when an event is created which mentions the village.</inlineHelpText>
    <label>B2B Chatter Group Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHelperTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seeAllData=true)
private class OpportunityTriggerHelperTest {

	private static Account account = new Account();
	private static Contact contact = new Contact();
	private static Opportunity opportunity = new Opportunity();
	private static Event event = new Event();
	private static Village__c village = new Village__c();
	private static Unit__c unit = new Unit__c();
	
	static void setUpData(){

		account = TestData_Account.setupBrandAccount(1, true);
		contact = TestData_Contact.setupContact('A',account, true);	
						
	 	village = new Village__c();
	 	village.Name = 'TestVillage';
	 	village.B2B_Chatter_Group_Name__c = 'B2BTestVillage';
	 	village.Village_Code__c = 'OO';
		village.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		village.CertSales_Report_Sales_Grace_Period_Days__c = 1; 
	 	insert village;
		village = [select name, id, B2B_Chatter_Group_Name__c, Village_Code__c from Village__c where Village_Code__c = 'OO' LIMIT 1];
		
		unit = new Unit__c(Name='TU1', Village__c = village.Id, size_GEA__c = 20,  Unit_Status__c = 'Available');
		insert unit;
		unit = 	[select Id, Name from Unit__c where name = 'TU1'];
		
		opportunity = new Opportunity(name = 'TestOpp', Village__c = village.Id, AccountId = account.id, 
										CloseDate = system.today().addDays(1), StageName = 'Pipeline',
										Projected_Sales_Yield_Local__c = 100000, Projected_Return_Local__c =12 , Ideal_Size__c = 100);
		insert opportunity;			
		
		
		
	}
	
    static testMethod void unitTest() {
        
    	test.startTest();
    	
    	setupData();
    	opportunity = [Select name, RecordType.Name, Unit__c, Unit__r.name from opportunity where id = :opportunity.Id];
    	system.assertEquals(opportunity.Name, account.Name + ' in ' + village.Name + ' - ' + opportunity.RecordType.Name.split(' ')[0]);    

		//OpportunityProjectionYieldCalculator.hasRun = false;	
    	opportunity.Unit__c = unit.Id;
    	OpportunityTriggerHelper.hasRun = false;
    	update opportunity;
    	
    	test.stopTest();
    	
    	opportunity = [Select name, RecordType.Name, Unit__c, Unit__r.name from opportunity where id = :opportunity.Id];
    	
    	system.assertEquals(opportunity.Name, account.Name + ' in ' + village.Name + ' (' + unit.Name + ')' +  ' - ' + opportunity.RecordType.Name.split(' ')[0] );
        
        
    }
}