force-app/main/default/objects/HFS_Item__c/HFS_Item__c.object-meta.xml
<CustomObject>
    <label>SCS Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SCS Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCS Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HFS_Item__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Village_Presence__c.Village__r.Name</field>
            <operation>equals</operation>
            <valueField>$User.Village__c</valueField>
        </filterItems>
        <filterItems>
            <field>Village_Presence__c.Status__c</field>
            <operation>equals</operation>
            <value>Trading</value>
        </filterItems>
        <infoMessage>Please select a Brand from within your village</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>SCS Items</relationshipLabel>
    <relationshipName>HFS_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateHFSItemController.cls
public with sharing class CreateHFSItemController {

    private string vpId ='';
    
    public HFS_Item__c hfsItem {
        get {
            if (hfsItem == null)
                hfsItem = new HFS_Item__c();
              return hfsItem;
        }
        set;
    }

    public CreateHFSItemController () {
        vpId = ApexPages.currentPage().getParameters().get('brandid');
    }

  
    public PageReference save() {

        try {
            if(String.isnotBlank(vpId)){
                hfsItem.Brand__c = vpId;
                insert hfsItem; 
            } else {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error creating new HFS Item. Invalid Brand Id'));
                return null;
            }
        } catch (DMLException e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error creating new HFS Item.'));
            return null;
        }
    
        // if successfully inserted new contact, then displays the thank you page.
        return Page.CreateHFSItem_Thankyou;


    }


    public PageReference addAnother() {
        hfsItem = new HFS_Item__c();
        return Page.CreateHFSItem;

    }

}