force-app/main/default/objects/Contact/fields/Latest_Trade_Events_Attended__c.field-meta.xml
<CustomField>
    <fullName>Latest_Trade_Events_Attended__c</fullName>
    <label>Latest Trade Events Attended</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trade_Event_Attendee__c/Trade_Event_Attendee__c.object-meta.xml
<CustomObject>
    <description>Junction Object</description>
    <label>Trade Event Attendee</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Trade Event Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade_Event_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tourism Contact</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tourism Contact</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Leasing Contact</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand Contact</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>HNW Event Attendee</value>
        </filterItems>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>VIP Guest</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trade Events Attended</relationshipLabel>
    <relationshipName>Trade_Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Trade_Event_Attendee__c/fields/Trade_Event_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Trade_Event_Attendee__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; Id,  Contact__r.FirstName + &quot; &quot; +  Contact__r.LastName  ,&quot;_self&quot;)</formula>
    <label>Trade Event Attendee</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trade_Event_Attendee__c/fields/Trade_Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Trade_Event_Date__c</fullName>
    <formula>Trade_Event__r.Event_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trade Event Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trade_Event_Attendee__c/fields/Trade_Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Trade_Event_Name__c</fullName>
    <formula>Trade_Event__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trade Event Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactTradeEventSync.cls
public without sharing class ContactTradeEventSync {
	
	// This method updates the contact Latest_Trade_Events_Attended__c field with most recent 3
	// trade events attended. The method accepts a list of Trade Event Attendance record Ids.
	public static void syncContactTradeEvents(set <Id> tradeEventAttendeeIds){
		
		final integer MAX = 3; //Constant value to identify how many most recent trade event records to retrieve 
		
		// Retrieve all associated contacts which have been passed into the method call
		map<Id, Contact> contactMap = new map<Id, Contact>([select Id, Latest_Trade_Events_Attended__c from contact
		                                                    where Id in (select Contact__c from Trade_Event_Attendee__c 
		                                                   					 where Id in :tradeEventAttendeeIds) ALL ROWS]);
		
		// Retrieve most recent Trade events attended for each contact
		list<Contact> contactList = [SELECT Id, Name, Latest_Trade_Events_Attended__c, 
											(SELECT Trade_Event_Name__c, Trade_Event_Date__c 
		                                        FROM Trade_Event_Attendees__r 
		                                        order by Trade_Event_Date__c desc limit :MAX) 
		                             			FROM Contact where Id in :contactMap.keySet()];
		
		//loop through contact records
		for (Contact c :contactList){
		    list<Trade_Event_Attendee__c> attendanceList = c.getSobjects('Trade_Event_Attendees__r');
		    string tradeEventNames = '';
		    integer icount = 0;
		    // loop through trade events for each contact
		    if (attendanceList == null){
		    	c.Latest_Trade_Events_Attended__c = ''; // no trade event attendances found
		    } else {
			    for (Trade_Event_Attendee__c attendance :attendanceList){
			        // concatenate semi-colon separated string of trade event names
			        tradeEventNames += attendance.Trade_Event_Name__c; 
			        icount ++;
			        if (icount < MAX){
			        	tradeEventNames += ';';
			        }
			    }
	system.debug('@@@@  Latest Trade Events for .. ' + c.Name + ' - ' + tradeEventNames);
			    // set field value on contact with concatenated string value
			    c.Latest_Trade_Events_Attended__c = tradeEventNames;
		    }
		}
		
		// update the contact list
		update contactList;
		
		
	}
	


}