force-app/main/default/objects/Contact/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <inlineHelpText>Add a Village Presence Contact Role to add Villages to this field</inlineHelpText>
    <label>Village Presence</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/Daily_Sale__c.object-meta.xml
<CustomObject>
    <label>Daily Sale</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>Daily Sale Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Sale__c/fields/Brand_Reported_Amount__c.field-meta.xml
<CustomField>
    <fullName>Brand_Reported_Amount__c</fullName>
    <description>This field is looks at in the INT_Reported_Amount formula field and passed through to MRI via that field if the OVERRIDE RPT AMOUNT field is NULL</description>
    <inlineHelpText>This is the Total Net Sales and the total Net Value of Discounts for the day added together.</inlineHelpText>
    <label>Brand Reported Amount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Brand_Status__c.field-meta.xml
<CustomField>
    <fullName>Brand_Status__c</fullName>
    <description>Maps to MRI: BRANDCONF</description>
    <inlineHelpText>Please set to Confirmed when all figures have been entered and verified. This will submit the record to VR to be processed</inlineHelpText>
    <label>Brand Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Confirmed</fullName>
                <default>true</default>
                <label>Not Confirmed</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>Daily Sales</relationshipLabel>
    <relationshipName>Daily_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Store_Closed__c.field-meta.xml
<CustomField>
    <fullName>Store_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Maps to MRI:TRADEOVER</description>
    <inlineHelpText>Select to indicate the store was closed on the trading date.</inlineHelpText>
    <label>Store Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Store_Formula__c.field-meta.xml
<CustomField>
    <fullName>Store_Formula__c</fullName>
    <formula>LEFT(Store__r.Brand__r.Name,FIND(&quot; in &quot;, Store__r.Name,0)) &amp; &quot; (&quot; &amp; Store__r.Village__r.Name &amp; &quot;)&quot;</formula>
    <label>Store</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Trading_Date__c.field-meta.xml
<CustomField>
    <fullName>Trading_Date__c</fullName>
    <description>maps to MRI: TRADEDATE</description>
    <label>Trading Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Trading_Day_with_date__c.field-meta.xml
<CustomField>
    <fullName>Trading_Day_with_date__c</fullName>
    <formula>TEXT(YEAR(Trading_Date__c)) &amp;  &quot;-&quot; &amp; LPAD(TEXT(MONTH(Trading_Date__c)),2,&quot;0&quot;) &amp; &quot;-&quot; &amp; LPAD(TEXT(DAY(Trading_Date__c)),2,&quot;0&quot;) &amp; &quot; (&quot; &amp;
CASE( MOD(  Trading_Date__c - DATE(1900, 1, 7), 7), 0, $Label.DoW_Sunday , 1, $Label.DoW_Monday, 2, $Label.DoW_Tuesday, 3,
$Label.DoW_Wednesday, 4, $Label.DoW_Thursday, 5, $Label.DoW_Friday, 6, $Label.DoW_Saturday,&quot;Error&quot;) 

&amp; &quot;)&quot;</formula>
    <label>Trading Day</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/fields/Valid_for_Confirmation__c.field-meta.xml
<CustomField>
    <fullName>Valid_for_Confirmation__c</fullName>
    <description>Flag to indicate record is in a state which can be confirmed.</description>
    <formula>IF(
OR( AND(Store_Closed__c = True, ISPICKVAL(Brand_Status__c, &apos;Not Confirmed&apos;)),
AND(
ISPICKVAL(Brand_Status__c, &apos;Not Confirmed&apos;),
NOT(ISPICKVAL(Status__c, &apos;TOR&apos;)),
IF( OR(RecordType.DeveloperName = &apos;Current&apos;, RecordType.DeveloperName = &apos;Net&apos;, RecordType.DeveloperName = &apos;F_B_Covers&apos;, RecordType.DeveloperName = &apos;Full_Price&apos;, RecordType.DeveloperName = &apos;Discretionary_Discount&apos;, RecordType.DeveloperName = &apos;Full_Price_Discretionary_Discount&apos;), NOT( ISNULL ( Total_NET_SALES__c )), NOT( ISNULL ( Total_GROSS_SALES__c ))),
IF( OR(RecordType.DeveloperName = &apos;Current&apos;, RecordType.DeveloperName = &apos;Net&apos;, RecordType.DeveloperName = &apos;F_B_Covers&apos;, RecordType.DeveloperName = &apos;Full_Price&apos;, RecordType.DeveloperName = &apos;Discretionary_Discount&apos;, RecordType.DeveloperName = &apos;Full_Price_Discretionary_Discount&apos;), NOT( ISNULL ( NET_Value_of_Discounts__c )), NOT( ISNULL ( GROSS_Value_of_Discounts__c))),
NOT( ISNULL( Brand_Reported_Amount__c ) ),
NOT ( ISNULL ( Number_of_Transactions__c )),
NOT ( ISNULL ( Units_Sold__c )),
NOT ( ISNULL ( VIP_Cards__c )),
IF( OR(RecordType.DeveloperName = &apos;Current&apos;, RecordType.DeveloperName = &apos;Net&apos;, RecordType.DeveloperName = &apos;Gross&apos;, RecordType.DeveloperName = &apos;Full_Price&apos;, RecordType.DeveloperName = &apos;Discretionary_Discount&apos;, RecordType.DeveloperName = &apos;Full_Price_Discretionary_Discount&apos;), NOT ( ISNULL ( Tax_Free_Sales_Amount__c )), NOT (ISNULL (Covers__c))),
IF( OR(RecordType.DeveloperName = &apos;Current&apos;, RecordType.DeveloperName = &apos;Net&apos;, RecordType.DeveloperName = &apos;Gross&apos;, RecordType.DeveloperName = &apos;Full_Price&apos;, RecordType.DeveloperName = &apos;Discretionary_Discount&apos;, RecordType.DeveloperName = &apos;Full_Price_Discretionary_Discount&apos;), NOT ( ISNULL ( Tax_Free_Transactions__c )), NOT (ISNULL (Covers__c))),
ISNULL( VR_Override_Reported_Amount__c )




),
AND(F_B_Covers_Active__c = True, RecordType.DeveloperName = &apos;Current&apos;, NOT (ISNULL(Number_of_Transactions__c)), NOT (ISNULL(Covers__c)), NOT (ISNULL(Units_Sold__c)), NOT (ISNULL(VIP_Cards__c)), NOT (ISNULL(NET_Value_of_Discounts__c)), NOT (ISNULL(Total_NET_SALES__c)), ISPICKVAL(Brand_Status__c, &apos;Not Confirmed&apos;),
NOT(ISPICKVAL(Status__c, &apos;TOR&apos;))
) )





, true, false)</formula>
    <inlineHelpText>Before a record can be confirmed it must have sales data completed and cannot be overridden by Value Retail.</inlineHelpText>
    <label>Valid for Confirmation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence__c/fields/Daily_Sales_Active__c.field-meta.xml
<CustomField>
    <fullName>Daily_Sales_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Daily Sales Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/Village_Presence_Contact_Role__c.object-meta.xml
<CustomObject>
    <label>Village Presence Contact Role</label>
    <nameField>
        <displayFormat>VPC-{00000}</displayFormat>
        <label>Village Presence Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Village Presence Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must be a Brand Contact</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Village Presence Contact Roles</relationshipLabel>
    <relationshipName>Village_Presence_Contact_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Daily_Sales_Active_From__c.field-meta.xml
<CustomField>
    <fullName>Daily_Sales_Active_From__c</fullName>
    <inlineHelpText>Enter the date for which the user should be able to see daily sales records</inlineHelpText>
    <label>Daily Sales Active From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Daily_Sales_Active_To__c.field-meta.xml
<CustomField>
    <fullName>Daily_Sales_Active_To__c</fullName>
    <inlineHelpText>Enter the date for which the user should no longer be able to see daily sales records.  If this field is left empty then the user will be able to see the daily sales records indefinitely unless the user is deactivated.</inlineHelpText>
    <label>Daily Sales Active To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Village Presence</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>Village Presence Contact Roles</relationshipLabel>
    <relationshipName>Village_Presence_Contact_Roles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StoreUnconfirmedDailySales.cls
// Used by Visualforce Component - Unconfirmed_Daily_Sales in construction of reminder email
// sent to brand contacts where a daily sale record has not been confirmed within a day
public class StoreUnconfirmedDailySales {

	//capture the user id
    public Id userId {get; set;}
    public string language {get; set;}
    public map<Id, Daily_Sale__c> unconfirmedList = new map<Id, Daily_Sale__c>();
    private static final string fieldSetName = 'Reminder_Email';
    
    public list<Daily_Sale__c> getUnconfirmedList() {
		
		try{		
			if (string.isnotBlank(userId)){
				// Retrieve user record language to be used on Visualforce component.
				// This ensures field labels on email appear in correct language
				User u = [select Id, Email, ContactId, LanguageLocaleKey from User where Id = :userId];
				
				if (string.isnotBlank(u.ContactId)){
					this.language = u.LanguageLocaleKey; // set language
					
					// Retrieve Village presence contact roles associated with user
					list<Village_Presence_Contact_Role__c> vpcrList = [select Village_Presence__c, Daily_Sales_Active_From__c,
																		Daily_Sales_Active_To__c
																		from Village_Presence_Contact_Role__c 
																		where Village_Presence__r.Daily_Sales_Active__c = true
																		and Daily_Sales_Active_From__c != null
																		and Contact__c = :u.ContactId];
					
					if (!vpcrList.isEmpty()){
						
						set<Id> vpIds = new set<Id>();
						for (Village_Presence_Contact_Role__c vpcr :vpcrList){
							vpIds.add(vpcr.Village_Presence__c);
							
						}
						
						// Retrieve unconfirmed Daily sale records associated with the user's village presence contact
						// roles.
						// Construct query using fields defined on Daily_Sale__c 'Reminder_Email' fieldset. 
						date thisDay = system.today();						
						string query = 'select Id, Name, Store__r.Name,  ';					
						List<DailySalesListController.FieldSetMember> fsFlds = DailySalesListController.getFields(fieldSetName);
				        for (DailySalesListController.FieldSetMember fm :fsFlds){
				            string fldName = fm.fieldPath;
				            if (fldName != 'Id' && fldName != 'Name'){
				                query = query + fldName + ',';
				            }            
				        }
				        query = query.subString(0,query.length() - 1);
				        query = query + ' from ';
				        query = query + ' Daily_Sale__c';
				        query = query + ' where Brand_Status__c = \'Not Confirmed\' ';
				        query = query + ' and Trading_Date__c < :thisDay';
				        query = query + ' and Trading_Date__c = LAST_N_DAYS:7';
				        query = query + ' and Store__c in :vpIds';
        				
        				list<Daily_Sale__c> dsList = Database.query(query);

        				/*		
						list<Daily_Sale__c> dsList = [select Id, Name, Trading_Date__c, Store__c, Store_Formula__c, 
														Brand_Reported_Amount__c, Store_Closed__c, Trading_Day_with_date__c,
														Valid_for_Confirmation__c
											from Daily_Sale__c
											where Brand_Status__c = 'Not Confirmed'
											and Trading_Date__c < :system.today()
											and Store__c in :vpIds];
						*/
						
						if (!dsList.isEmpty()){
							for (Village_Presence_Contact_Role__c vpcr :vpcrList){
								Date startDt = vpcr.Daily_Sales_Active_From__c;
								Date endDt = vpcr.Daily_Sales_Active_To__c;
								// Ensure that only records which are within the village presence contact role Daily sale
								// date boundaries appear on the email
								for (Daily_Sale__c ds :dsList){
									if (vpcr.Village_Presence__c == ds.Store__c
											&& ds.Trading_Date__c >= startDt
											&& (endDt == null || endDt >= system.today())){
												
										unconfirmedList.put(ds.Id, ds);			
									}
								}
							}
							
						}					
						
					}																	
																		
					
				}
				
				
				
			}
		} catch (exception e){
			system.debug('ERROR ...ERROR ... ERROR ' + e.getMessage() + ' : ' + e.getStackTraceString());			
		}
		return unconfirmedList.values();
        
    }
    
	
    
}