force-app/main/default/objects/Contact/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <inlineHelpText>Add a Village Presence Contact Role to add Villages to this field</inlineHelpText>
    <label>Village Presence</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Sale__c/Daily_Sale__c.object-meta.xml
<CustomObject>
    <label>Daily Sale</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>Daily Sale Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Sale__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>Daily Sales</relationshipLabel>
    <relationshipName>Daily_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Global_Object_Validation__c/Global_Object_Validation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Control whether validation rules for an individual object are active or not. For example, if object name is Account add the following line to each validation rule for the Account object: $Setup.Global_Object_Validation__c.Account_Active__c &amp;&amp; ......</description>
    <label>Global Object Validation</label>
</CustomObject>

force-app/main/default/objects/Global_Object_Validation__c/fields/Daily_Sales_Validations_Active__c.field-meta.xml
<CustomField>
    <fullName>Daily_Sales_Validations_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Daily Sales Validations Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence_Contact_Role__c/Village_Presence_Contact_Role__c.object-meta.xml
<CustomObject>
    <label>Village Presence Contact Role</label>
    <nameField>
        <displayFormat>VPC-{00000}</displayFormat>
        <label>Village Presence Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Village Presence Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Confirm_Daily_Sales_Records__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Daily_Sales_Records__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Can the contact, for this store, confirm Daily Sales Records</inlineHelpText>
    <label>Confirm Daily Sales Records</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must be a Brand Contact</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brand Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Village Presence Contact Roles</relationshipLabel>
    <relationshipName>Village_Presence_Contact_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Daily_Sales_Active_From__c.field-meta.xml
<CustomField>
    <fullName>Daily_Sales_Active_From__c</fullName>
    <inlineHelpText>Enter the date for which the user should be able to see daily sales records</inlineHelpText>
    <label>Daily Sales Active From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Daily_Sales_Active_To__c.field-meta.xml
<CustomField>
    <fullName>Daily_Sales_Active_To__c</fullName>
    <inlineHelpText>Enter the date for which the user should no longer be able to see daily sales records.  If this field is left empty then the user will be able to see the daily sales records indefinitely unless the user is deactivated.</inlineHelpText>
    <label>Daily Sales Active To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Village Presence</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>Village Presence Contact Roles</relationshipLabel>
    <relationshipName>Village_Presence_Contact_Roles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DailySalesValidations.cls
public class DailySalesValidations {
    
    private string errMsg = '';
    
    // Custom setting indicating whether validations on the Daily_Sale__c object should be performed
    private static final boolean validationsActive = boolean.valueOf(Global_Object_Validation__c.getInstance().get('Daily_Sales_Validations_Active__c'));
    
    // Validate whether user confirming record is authorised to do so.
    // This is defined by Confirm_Daily_Sales_Records__c flag on Village Presence Contact Role record
    public static void checkConfirmUser(list<Daily_Sale__c> DailySalesList){
        
        if (validationsActive){
            
            boolean valid = true;
           
            string userId =  system.userInfo.getUserId();
            
            string contactId = [select ContactId from User where Id = :userId].contactId; //Equivalent brand contact id for the running user 
            map<string, string> vpIdSet = new map<string, string>() ;
            
            for(Daily_Sale__c ds: DailySalesList)
            {
                vpIdSet.put(ds.Id, ds.Store__c);
            }
            
            map<Id, Village_Presence__c> vpcontactRoleMap = new map<Id, Village_Presence__c>([select Id, Name, (SELECT id, Village_presence__c, Contact__c,
                                                                 Daily_Sales_Active_From__c, Daily_Sales_Active_To__c,
                                                                 Confirm_Daily_Sales_Records__c
                                                                 from Village_Presence_Contact_roles__r
                                                                 where Daily_Sales_Active_From__c != null
                                                                 and Contact__c = :contactId)
                                                            From Village_Presence__c
                                                            where Id in :vpIdSet.values()]);
                

            for(Daily_Sale__c ds :DailySalesList){
                
                list<Village_Presence_Contact_Role__c> vpcontactRoleList = vpcontactRoleMap.get(ds.Store__c).Village_Presence_Contact_roles__r;
            
                if (vpcontactRoleList.size() == 1){
                    if (!vpcontactRoleList[0].Confirm_Daily_Sales_Records__c)
                        valid = false;
                } else {
                    valid = false;
                }

        
                if(!Valid){
                    ds.addError('Sorry! you do not have authority to confirm this record');
                }
            } 
        }

        
    }
    
    
}