force-app/main/default/objects/Contact/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <inlineHelpText>Add a Village Presence Contact Role to add Villages to this field</inlineHelpText>
    <label>Village Presence</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bicester</fullName>
            </value>
            <value>
                <fullName>Fidenza</fullName>
            </value>
            <value>
                <fullName>Ingolstadt</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>La Roca</fullName>
            </value>
            <value>
                <fullName>Las Rozas</fullName>
            </value>
            <value>
                <fullName>La Vallée</fullName>
            </value>
            <value>
                <fullName>Maasmechelen</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Suzhou</fullName>
            </value>
            <value>
                <fullName>Wertheim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Presence__c/Village_Presence__c.object-meta.xml
<CustomObject>
    <description>represents a Brand Account in a Village and stores all the properties in the record</description>
    <label>Village Presence</label>
    <nameField>
        <label>Village Presence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Village Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence_Contact_Role__c/Village_Presence_Contact_Role__c.object-meta.xml
<CustomObject>
    <label>Village Presence Contact Role</label>
    <nameField>
        <displayFormat>VPC-{00000}</displayFormat>
        <label>Village Presence Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Village Presence Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Primary_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Role__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Tick this box if the contact&apos;s role is the primary one for this Village Presence</inlineHelpText>
    <label>Primary Contact Role</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Retail_Role__c.field-meta.xml
<CustomField>
    <fullName>Retail_Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Retail</fullName>
                <default>true</default>
                <label>Retail</label>
            </value>
            <value>
                <fullName>Remerchandising</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>keeps the record unique</description>
    <label>UniqueKey</label>
    <length>55</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village_Presence_Contact_Role__c/fields/Village_Presence__c.field-meta.xml
<CustomField>
    <fullName>Village_Presence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Village Presence</label>
    <referenceTo>Village_Presence__c</referenceTo>
    <relationshipLabel>Village Presence Contact Roles</relationshipLabel>
    <relationshipName>Village_Presence_Contact_Roles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PrimaryVPCRCheck.cls
Global with sharing Class PrimaryVPCRCheck{   

public static void vpcrCheck(List<Village_Presence_Contact_Role__c> VPCRfromtrigger) {

            //Records coming from trigger have been filtered to Primary_Contact_Role__c = TRUE
            
            //Map to execute SOQL statement
            map<Id, Id> VPSet = new map<Id, Id>();
            
            //Map of (string,Village_Presence_Contact_Role__c) made up of a unique string of VP and Retail_Role eg. 'Barbour in BicesterRetail' 
            map<string, Village_Presence_Contact_Role__c> otherprimarystringmap  = new map<string, Village_Presence_Contact_Role__c>(); 
          
            //Add ids and VPids to map
            for (Village_Presence_Contact_Role__c vpcr : VPCRfromtrigger) {
            VPSet.put(vpcr.Id, vpcr.Village_presence__c);
            }
            
            //Only get the primaries from the VP, excludes trigger id's
            list<Village_Presence_Contact_Role__c> otherprimarylist = new list<Village_Presence_Contact_Role__c>
            ([select id, Village_Presence__c, Primary_Contact_Role__c,Retail_Role__c,Name FROM
             Village_Presence_Contact_Role__c WHERE village_presence__c in :VPSet.values() and Primary_Contact_Role__c = true 
             and id NOT IN:VPSet.keyset() ]);  
            
            //put string of VillagePresence+retail_role__c into Map for OTHER primary contacts at VP's
            for(Village_Presence_Contact_Role__c vpcr: otherprimarylist){
                   string vprole = vpcr.Village_Presence__c+vpcr.Retail_Role__c;
                   otherprimarystringmap.put(vprole, vpcr);
            }
    
    
        //compare trigger record string (village_presence+retail_role with same values in otherprimarymap
        for(Village_Presence_Contact_Role__c vpcr : VPCRfromtrigger ){
                 string vproles = vpcr.Village_Presence__c+vpcr.Retail_Role__c;
         if(!otherprimarystringmap.containsKey(vproles) && vpcr.UniqueKey__c != NULL){
         //reproduce uniquekey__c workflow field update that doesn't fire after the save operation
              otherprimarystringmap.put(vproles, vpcr);
              string uk = vpcr.UniqueKey__c;
              uk = uk.left(30);
              vpcr.UniqueKey__c = uk+vpcr.Retail_Role__c;
              }
              
              //to handle insert operation without creating second/seperate trigger variables 
              //and enable the UniqueKey__c field update 
             else if(!otherprimarystringmap.containsKey(vproles) && vpcr.UniqueKey__c == NULL){
              otherprimarystringmap.put(vproles, vpcr);
             
              }
              
                  
        else{
         vpcr.addError('This Village Presence already has a Primary '+vpcr.Retail_Role__c+
           ' Contact, please uncheck the Primary Contact Role on <a href=\'https://valueretail.my.salesforce.com/'+otherprimarystringmap.get(vproles).id +
            '\'  target="_blank">' + otherprimarystringmap.get(vproles).name + '</a> before saving this as the Primary '+vpcr.Retail_Role__c+
            ' Contact ',FALSE);
             }     
   }                                 
 }                              
}