force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/HFS_Country_of_Village__c.field-meta.xml
<CustomField>
    <fullName>HFS_Country_of_Village__c</fullName>
    <label>Country of Village</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/fields/HFS_High_Spend_Threshold__c.field-meta.xml
<CustomField>
    <fullName>HFS_High_Spend_Threshold__c</fullName>
    <description>Field used to stablish what a High spent amount by the guest is</description>
    <label>Local Guest High Spend Threshold</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/HFS_International_Guest_Spend_Threshold__c.field-meta.xml
<CustomField>
    <fullName>HFS_International_Guest_Spend_Threshold__c</fullName>
    <description>International threshold to determine when the spend amount  reaches a gift/treat level</description>
    <label>International Guest Spend Threshold</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/HFS_Medium_Spend_Threshold__c.field-meta.xml
<CustomField>
    <fullName>HFS_Medium_Spend_Threshold__c</fullName>
    <description>Indicates what a medium spent is for the village in the context of the HFS Project</description>
    <label>Local Guest Medium Spend Threshold</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/HFSSpentLevelCalculatorTest.cls
@isTest
public class HFSSpentLevelCalculatorTest {

	@testSetup
	static void setupData () {

		Village__c bicesterVillage = TestDataGenerator.setupVillage(false);
		bicesterVillage.Village_Code__c = 'BV';
		bicesterVillage.HFS_Medium_Spend_Threshold__c = 1500;
		bicesterVillage.HFS_High_Spend_Threshold__c = 3000;
		bicesterVillage.HFS_International_Guest_Spend_Threshold__c = 5000;
		bicesterVillage.HFS_Country_of_Village__c = 'United Kingdom';

		Village__c fidenzaVillage = TestDataGenerator.setupVillage(false);
		fidenzaVillage.Village_Code__c = 'FV';
		fidenzaVillage.HFS_Medium_Spend_Threshold__c = 1000;
		fidenzaVillage.HFS_High_Spend_Threshold__c = 2000;
		fidenzaVillage.HFS_International_Guest_Spend_Threshold__c = 4000;
		fidenzaVillage.HFS_Country_of_Village__c = 'Italy';

		Village__c laValleeVillage = TestDataGenerator.setupVillage(false);
		laValleeVillage.Village_Code__c = 'LV';
		laValleeVillage.HFS_Country_of_Village__c = 'France';

		insert new List<Village__c> {bicesterVillage, fidenzaVillage, laValleeVillage};	

	}

	static testmethod void mainTest() {
		
		HFSSpentLevelCalculator calculator1 = HFS_Utils.getCurrencyLevelCalculator('BV');

		system.assertEquals(HFS_SpentLevel.LOW, calculator1.getGuestLevel(null, 'United Kingdom'));
		system.assertEquals(HFS_SpentLevel.LOW, calculator1.getGuestLevel(1400, 'United Kingdom'));
		system.assertEquals(HFS_SpentLevel.MEDIUM, calculator1.getGuestLevel(2000, 'United Kingdom'));
		system.assertEquals(HFS_SpentLevel.LOW, calculator1.getGuestLevel(2900, 'Spain'));
		system.assertEquals(HFS_SpentLevel.LOW, calculator1.getGuestLevel(3100, 'Spain'));
		system.assertEquals(HFS_SpentLevel.HIGH, calculator1.getGuestLevel(3100, 'United Kingdom'));
		system.assertEquals(HFS_SpentLevel.LOW, calculator1.getGuestLevel(3100, 'Spain'));
		system.assertEquals(HFS_SpentLevel.HIGH, calculator1.getGuestLevel(6000, 'Spain'));

		system.assertEquals('',calculator1.getFormattedCurrency(null));
		system.assertEquals('£ 250.00',calculator1.getFormattedCurrency(250));

		calculator1 = HFS_Utils.getCurrencyLevelCalculator('FV');

		system.assertEquals(HFS_SpentLevel.LOW, calculator1.getGuestLevel(null, 'Italy'));
		system.assertEquals(HFS_SpentLevel.LOW, calculator1.getGuestLevel(900, 'Italy'));
		system.assertEquals(HFS_SpentLevel.MEDIUM, calculator1.getGuestLevel(1500, 'Italy'));
		system.assertEquals(HFS_SpentLevel.LOW, calculator1.getGuestLevel(1500, 'Spain'));
		system.assertEquals(HFS_SpentLevel.HIGH, calculator1.getGuestLevel(2100, 'Italy'));
		system.assertEquals(HFS_SpentLevel.HIGH, calculator1.getGuestLevel(4100, 'Italy'));
		system.assertEquals(HFS_SpentLevel.LOW, calculator1.getGuestLevel(3100, 'Spain'));
		system.assertEquals(HFS_SpentLevel.HIGH, calculator1.getGuestLevel(4100, 'Spain'));

		system.assertEquals('',calculator1.getFormattedCurrency(null));
		system.assertEquals('250.00 €',calculator1.getFormattedCurrency(250));

		calculator1 = HFS_Utils.getCurrencyLevelCalculator('LV');

		system.assertEquals(HFS_SpentLevel.LOW, calculator1.getGuestLevel(5000, 'France'));


	}

}