force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>custom currency field</description>
    <inlineHelpText>Enter the currency to be used for all financial leasing values to be used in this village (custom currency)</inlineHelpText>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>RMB</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Local_Language__c.field-meta.xml
<CustomField>
    <fullName>Village_Local_Language__c</fullName>
    <inlineHelpText>Select the default language to be used for B2C communications</inlineHelpText>
    <label>Village Local Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village_Reference_Data__c/Village_Reference_Data__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Village lookup data for code matching and transformations.</description>
    <label>Village Reference Data</label>
</CustomObject>

force-app/main/default/objects/Village_Reference_Data__c/fields/MRI_Code__c.field-meta.xml
<CustomField>
    <fullName>MRI_Code__c</fullName>
    <label>MRI Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VR1_Chatter_Groups__c/VR1_Chatter_Groups__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of Chatter Groups required for VR1.</description>
    <label>VR1 Chatter Groups</label>
</CustomObject>

force-app/main/default/classes/SandboxRefreshUtilitiesTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class SandboxRefreshUtilitiesTest {

    static testMethod void chatterGroupTest() {
        
        VR1_Chatter_Groups__c grp1 = new VR1_Chatter_Groups__c(name='Test1', Group_Name__c = 'Test1');
        insert grp1;
        
        VR1_Chatter_Groups__c grp2 = new VR1_Chatter_Groups__c(name='Test2', Group_Name__c = 'Test2');
        insert grp2;
        
        test.startTest();
        	
        	SandboxRefreshUtilities.loadChatterGroups();
        

        
	        list<CollaborationGroup> grpList = [select Id, Name from CollaborationGroup 
	        										where Name Like 'Test%'
	        										order by Name Asc];
	        
	        system.assertEquals(grpList.size(), 2);
	        system.assertEquals(grpList[0].Name, 'Test1');
	    
	        // test error
	        VR1_Chatter_Groups__c grp3 = new VR1_Chatter_Groups__c(name='Test3', Group_Name__c = 'Test1');
	        insert grp3;
	
			grpList = [select Id, Name from CollaborationGroup 
	        										where Name Like 'Test%'
	        										order by Name Asc];
	        
	        SandboxRefreshUtilities.loadChatterGroups();
	        
	        system.assertEquals(grpList.size(), 2);
        
		test.stopTest();    
        
    }
    
    static testMethod void villageDataTest(){
    	
    	Village__c village = new Village__c(Name = 'Test1', Village_Code__c = 'V1', Currency__c = 'EUR', Village_Local_Language__c = 'Italian',CertSales_CertPeriod_Cut_Off_Days__c = 1, CertSales_Report_Sales_Grace_Period_Days__c = 1);
    	insert village;
    	
    	test.startTest();
    		SandboxRefreshUtilities.refreshVillageRefData();
    	test.stopTest();
    	
    	list<Village_Reference_Data__c> dataList = Village_Reference_Data__c.getall().values();
    	system.assertEquals(dataList.size(), 1);
    	system.assertEquals(dataList[0].Name, village.Name);
    	system.assertEquals(dataList[0].MRI_Code__c, village.Village_Code__c);
    	
    }
}