force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/HFS_Country_of_Village__c.field-meta.xml
<CustomField>
    <fullName>HFS_Country_of_Village__c</fullName>
    <label>Country of Village</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/fields/HFS_High_Spend_Threshold__c.field-meta.xml
<CustomField>
    <fullName>HFS_High_Spend_Threshold__c</fullName>
    <description>Field used to stablish what a High spent amount by the guest is</description>
    <label>Local Guest High Spend Threshold</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/HFS_International_Guest_Spend_Threshold__c.field-meta.xml
<CustomField>
    <fullName>HFS_International_Guest_Spend_Threshold__c</fullName>
    <description>International threshold to determine when the spend amount  reaches a gift/treat level</description>
    <label>International Guest Spend Threshold</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/HFS_Medium_Spend_Threshold__c.field-meta.xml
<CustomField>
    <fullName>HFS_Medium_Spend_Threshold__c</fullName>
    <description>Indicates what a medium spent is for the village in the context of the HFS Project</description>
    <label>Local Guest Medium Spend Threshold</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/HFSSpentLevelCalculatorBV.cls
public without sharing class HFSSpentLevelCalculatorBV implements HFSSpentLevelCalculator{
	
	private final Decimal highLevelAmount;
	private final Decimal mediumLevelAmount;
	private final Decimal internationalLevelAmount;
	private final String villageCode = 'BV';
	private final String country;
	private final List<String> formattingArgs = new String[]{'0','number','###,###,###,###.00'};
	private final String currencySymbol = '£';


	public HFSSpentLevelCalculatorBV() {
		Village__c village = [SELECT Id, HFS_High_Spend_Threshold__c, HFS_Medium_Spend_Threshold__c, HFS_International_Guest_Spend_Threshold__c, HFS_Country_of_Village__c FROM Village__c WHERE Village_Code__c =: villageCode];
		this.highLevelAmount = village.HFS_High_Spend_Threshold__c;
		this.mediumLevelAmount = village.HFS_Medium_Spend_Threshold__c;
		this.internationalLevelAmount = village.HFS_International_Guest_Spend_Threshold__c;
		this.country = village.HFS_Country_of_Village__c;
	}
	
	public HFS_SpentLevel getGuestLevel(Decimal spentAmount, String country) {
	
		if (highLevelAmount != null && mediumLevelAmount != null && internationalLevelAmount != null) {
			if (spentAmount == null) {
				return HFS_SpentLevel.LOW;
			} else if (country == this.country) {
				if (spentAmount > this.highLevelAmount) {
					return HFS_SpentLevel.HIGH;
				} else if (spentAmount > this.mediumLevelAmount) {
					return HFS_SpentLevel.MEDIUM;
				} else {
					return HFS_SpentLevel.LOW;
				}
			} else {
				if (spentAmount > this.internationalLevelAmount) {
					return HFS_SpentLevel.HIGH;
				} else {
					return HFS_SpentLevel.LOW;
				}
			}
		} else {
			return HFS_SpentLevel.LOW;
		}
	}

	public String getFormattedCurrency(Decimal spentAmount) {

		String formattedCurrency = '';

		if (spentAmount != null) {
			formattedCurrency = currencySymbol + ' ' + String.format(String.valueOf(spentAmount.setScale(2)), formattingArgs);
		}

		return formattedCurrency;
	}
}