force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/calculateRatingsForVillageButtonFlowTest.cls
@isTest (seeAllData=true)
private class calculateRatingsForVillageButtonFlowTest {
    static testMethod void testRatingUpdate() {
        
        Account testAccount = TestDataGenerator.setupB2BAccount(1, true);
        Village__c ratedVillage = TestDataGenerator.setupVillage(true);
        Village__c unratedVillage = TestDataGenerator.setupVillage(false);
        unratedVillage.Village_Code__c = 'ZY';
        unratedVillage.Name = 'UNRATEDVILLAGE';
        
        Village__c villageIn = TestDataGenerator.setupVillage(false);
        villageIn.Village_Code__c = 'AB';
        villageIn.Name = 'TESTUNIT';
        List<Village__c> listvilla = new List<Village__c> {unratedVillage, villageIn};
            
            insert listvilla;
        
        list<Id> testId = new List<Id>();
        testId.add(listvilla[0].id);
     
        test.startTest();
         calculateRatingsForVillageButtonFlow.calculateRatingsForVillage(testId);   
        test.stopTest();
              
    }
}