force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/Campaign_Focus__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Focus__c</fullName>
    <inlineHelpText>...</inlineHelpText>
    <label>Campaign Focus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Theme</fullName>
            </value>
            <value>
                <fullName>Awareness and Positioning</fullName>
            </value>
            <value>
                <fullName>Promotional Moments</fullName>
            </value>
            <value>
                <fullName>Tactical Product Focus</fullName>
            </value>
            <value>
                <fullName>International Moments</fullName>
            </value>
            <value>
                <fullName>Retail Brand Moments</fullName>
            </value>
            <value>
                <fullName>Local Moments</fullName>
            </value>
            <value>
                <fullName>Destination Marketing Moments</fullName>
            </value>
            <value>
                <fullName>International Always On</fullName>
            </value>
            <value>
                <fullName>Non-Campaigns</fullName>
            </value>
            <value>
                <fullName>BAU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Campaign_Level__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Level__c</fullName>
    <description>Tactical is the norm.

Add &quot;Theme&quot; or &quot;BAU&quot; when required - keep it off so users can only choose Tactical and no validations are required.</description>
    <inlineHelpText>The Campaing Level...</inlineHelpText>
    <label>Campaign Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Theme</fullName>
            </value>
            <value>
                <fullName>BAU Campaign</fullName>
            </value>
            <value>
                <fullName>Non-Campaign</fullName>
            </value>
            <value>
                <fullName>Lead Moment</fullName>
            </value>
            <value>
                <fullName>Local Moment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Campaign_Marketing_Budget__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Marketing_Budget__c</fullName>
    <inlineHelpText>The budget that is planned to be spent on this marketing campaign</inlineHelpText>
    <label>TBVSC Brand Campaign Marketing Budget</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Enter the End Date of the Campaign</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Parent_Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Parent_Marketing_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a Parent Marketing Campaign</inlineHelpText>
    <label>Parent Marketing Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Parent Campaigns must be TBVSC Brand Campaigns</errorMessage>
        <filterItems>
            <field>Marketing_Campaign__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>TBVSC Brand Campaign</value>
        </filterItems>
        <infoMessage>Please select a TBVSC Brand Campaign</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Campaigns</relationshipLabel>
    <relationshipName>Marketing_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Re_send_to_Oracle__c.field-meta.xml
<CustomField>
    <fullName>Re_send_to_Oracle__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select this field and save the Record in order to resend this record&apos;s information to the Finance System</inlineHelpText>
    <label>Re-send to Oracle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Enter the Start Date of the Campaign</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/Transfer_To_Oracle__c.field-meta.xml
<CustomField>
    <fullName>Transfer_To_Oracle__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Allows the Campaign data to be sent to Oracle Projects</description>
    <inlineHelpText>Allow the Campaign data to be sent to Oracle Projects</inlineHelpText>
    <label>Transfer To Oracle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/massEditReAssignCampaignsController.cls
Public Class massEditReAssignCampaignsController{

    public id recordId {get;set;}
    public list<Marketing_Campaign__c> MCs {get;set;}
    public list<Wrapper> wMCstoEdit {get;set;}
    public Marketing_Campaign__c selectOption {get;set;}
    public Integer errorcount {get;set;}
    public string errormessage {get;set;}

    
    Public massEditReAssignCampaignsController(ApexPages.StandardSetController stdsetcontroller){
        
        selectOption = new Marketing_Campaign__c();
        wMCstoEdit = new list<Wrapper>();
        errorcount = 0;
        errormessage = '';
        recordId = ApexPages.currentPage().getParameters().get('theid');
        system.debug('recordId' + recordId);
        MCs = [SELECT ID, Name,CurrencyIsoCode,Campaign_Marketing_Budget__c,Campaign_Level__c,
               Campaign_Focus__c, Parent_Marketing_Campaign__c,Status__c,RecordTypeid, Start_Date__c,
               End_Date__c, Transfer_To_Oracle__c, Re_send_to_Oracle__c
            FROM
               marketing_campaign__c 
            WHERE 
                Parent_Marketing_Campaign__c =:recordId ];
        system.debug('MCs' + MCs);

            for(Marketing_Campaign__c MC : MCs){
                wMCstoEdit.add(new Wrapper(MC));
            }

    }


    Public Pagereference saveSelected() {

        try{
        list<Marketing_Campaign__c> Updates = new List<Marketing_Campaign__c>();
            for(Wrapper wrapper : wMCstoEdit) {
                    if(wrapper.selected == true) {
                        Updates.add(wrapper.theMC); 
                    }
            }   
        system.debug('updates :' + updates);     
        update Updates;        
        PageReference pageRef = new PageReference('/'+recordId);
        return pageRef;
        }

        catch (exception e){
            errorcount ++ ;
            system.debug('error mercc : ' + e);
            if (e.getmessage().contains('You cannot set the Status as "Cancelled" before you reassign all its associated "Live" Marketing activities')){       
                errormessage = 'There are open Marketing Activites on one or more of the Campaigns you are trying to update, please close them before proceeding.';
            }
            else {
                errormessage = 'An Error has occurred, please contact your System Administrator'; 
            }
            
            return null;   
        }
    }





    Public Pagereference selectAll() {
        for(Wrapper wrapper : wMCstoEdit){
            wrapper.selected = true;
        }
        return null;
    }

    Public Pagereference deselectAll() {
      for(Wrapper wrapper : wMCstoEdit){
            wrapper.selected = false;
        }
        return null;
    }

    Public Pagereference Cancel() {
    PageReference pageRef = new PageReference('/'+recordId);
        return pageRef;
    }

    Public Pagereference setAllStatus() {
        for(Wrapper wrapper : wMCstoEdit){
            wrapper.theMC.Status__c = selectOption.Status__c;
        }
     
        return null;
    }

    public class Wrapper{
        public Marketing_Campaign__c theMC {get; set;}
        public Boolean selected {get; set;}

        public Wrapper(Marketing_Campaign__c mc) {
            theMC = mc;
            selected = false;
        }
    }

}