force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <description>Marketing Campaigns........</description>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/Re_send_to_Oracle_Update__c.field-meta.xml
<CustomField>
    <fullName>Re_send_to_Oracle_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Re-send to Oracle Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/mcUpdatescheduledBatchable.cls
global class mcUpdatescheduledBatchable implements Schedulable{

   Map<Id, Marketing_Campaign__c> mcMap = new Map<Id, Marketing_Campaign__c>([SELECT Id, Name FROM Marketing_Campaign__c where Re_send_to_Oracle_Update__c=True]);

   global void execute(SchedulableContext sc) {
   
   System.debug('CampaignId :'+mcMap.keySet());
      MarketingCampaignUpdateBatchCallout mcbatch = new MarketingCampaignUpdateBatchCallout(mcMap.keySet()); 
      database.executebatch(mcbatch);
   }
}