force-app/main/default/objects/LGL_Service_Item__c/LGL_Service_Item__c.object-meta.xml
<CustomObject>
    <description>Represents a particular service request for an offered service</description>
    <label>Service Item</label>
    <nameField>
        <displayFormat>SI-{00000}</displayFormat>
        <label>Service Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LGL_Service_Item__c/fields/LGL_Checkout_Time__c.field-meta.xml
<CustomField>
    <fullName>LGL_Checkout_Time__c</fullName>
    <description>Represents the hour in when the service finished (because of Luggage collection, loan return, etc.)</description>
    <label>Checkout Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/LGL_Service_Item__c/fields/LGL_Status__c.field-meta.xml
<CustomField>
    <fullName>LGL_Status__c</fullName>
    <description>Represents the status of the Service Item</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>using</fullName>
                <label>In Use</label>
            </value>
            <value>
                <fullName>closed</fullName>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Service_Request_API.cls
public inherited sharing class Service_Request_API {

	public static String NEW_SERVICE_ITEM_STATUS = 'using';
	public static String CLOSED_SERVICE_ITEM_STATUS = 'closed';

	public static List<LGL_Service_Item__c> checkoutServiceItems (List <LGL_Service_Item__c> serviceItems) {

		if (serviceItems != null) {
			for (LGL_Service_Item__c serviceItem : serviceItems) {
				serviceItem.LGL_Status__c = CLOSED_SERVICE_ITEM_STATUS;
				serviceItem.LGL_Checkout_Time__c = system.now();
			}
		}
		update serviceItems;
		return serviceItems;
	}

	public static List <LGL_Service_Item__c> createServiceItems (List <LGL_Service_Item__c> serviceItems) {

		for (LGL_Service_Item__c serviceItem : serviceItems) {
			serviceItem.LGL_Status__c = NEW_SERVICE_ITEM_STATUS;
		}

		insert serviceItems;
		return serviceItems;
	}

}