force-app/main/default/objects/Integration_Callout_Body__c/Integration_Callout_Body__c.object-meta.xml
<CustomObject>
    <label>Integration Callout Body</label>
    <nameField>
        <displayFormat>IC-{00000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Callout Bodies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Callout_Body__c/fields/Marketing_Finance_Integration_Log__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Finance_Integration_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Finance Integration Log</label>
    <referenceTo>MF_Integration_Log__c</referenceTo>
    <relationshipLabel>Integration Callout Bodies</relationshipLabel>
    <relationshipName>Integration_Callout_Bodies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Callout_Body__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <description>Stores the value for a particular integration (inbound or outbound) request</description>
    <inlineHelpText>The maximum number of characters for the field is 10000. If the full value doesn&apos;t appear it&apos;s because has been reduced to fit the maximum number</inlineHelpText>
    <label>Request Body</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Callout_Body__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>inbound</fullName>
                <label>Inbound Request</label>
            </value>
            <value>
                <fullName>outbound</fullName>
                <label>Outbound Request</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Callout_Body__c/fields/Response_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Code__c</fullName>
    <description>Represents the response status code received for a particular request</description>
    <label>Response Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Callout_Body__c/fields/Response_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Response_Error_Message__c</fullName>
    <description>Error Message received in the response of the callout in case there has been a failure</description>
    <label>Response Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Callout_Body__c/fields/Salesforce_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Record_Id__c</fullName>
    <label>Salesforce_Record_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MF_Integration_Log__c/MF_Integration_Log__c.object-meta.xml
<CustomObject>
    <description>Stored all information about while perform integration with DI (Oracle).</description>
    <label>Marketing Finance Integration Log</label>
    <nameField>
        <displayFormat>ILOG-{00000}</displayFormat>
        <label>MF Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Finance Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MFIntegrationLogger.cls
public with sharing class MFIntegrationLogger {
	
	static final String INBOUND_REQUEST = 'inbound';
	static final String OUTBOUND_REQUEST = 'outbound';
	static final String MARKETING_ACTIVITY_REL_OBJECT = 'Marketing Activity';
	static final String MARKETING_CAMPAIGN_REL_OBJECT = 'Marketing Campaign';

	MF_Integration_Log__c integrationLog;
	String sessionId;
	String statusCode;
	String errorMessage;

	List <Integration_Callout_Body__c> calloutBodies = new List <Integration_Callout_Body__c> ();
	
	public MFIntegrationLogger(String sessionId) {
		this.sessionId = sessionId;
		this.getIntegrationLog();
	}

	public MFIntegrationLogger() {
		this.integrationLog = new MF_Integration_Log__c();
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
		this.integrationLog.Session_Id__c = sessionId;
	}

	public void setResponseStatusCode(Integer statusCode) {
		this.statusCode = String.valueOf(statusCode);
	}

	public void setResponseStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage.length() > 250 ? errorMessage.subString(0,250) : errorMessage;
	}

	public void setMarketingActivityAsRelatedObject() {
		this.setRelatedObject(MARKETING_ACTIVITY_REL_OBJECT);
	}

	public void setMarketingCampaignAsRelatedObject() {
		this.setRelatedObject(MARKETING_CAMPAIGN_REL_OBJECT);
	}

	public void setRelatedObject(String relatedObject) {
		this.integrationLog.Related_Object__c = relatedObject;
	}

	private MF_Integration_Log__c getIntegrationLog() {
		if (this.integrationLog == null) {
			if (String.isNotBlank(sessionId)) {
				//Query for a list to check for existency and avoid errors although the sessionId should be unique
				List <MF_Integration_Log__c> existingIntegrationLog = [SELECT Id, Session_Id__c FROM MF_Integration_Log__c WHERE Session_Id__c =: sessionId];
				if (!existingIntegrationLog.isEmpty()) {
					this.integrationLog = existingIntegrationLog[0];
				}
			}
		}

		//In case that we haven't found any existing integration Log, we instantiate a new one
		if (this.integrationLog == null) {
			this.integrationLog = new MF_Integration_Log__c ();
			this.integrationLog.Session_Id__c = this.sessionId;
		}

		return this.integrationLog;
	}

	public Integration_Callout_Body__c setInboundRequest(Object body, Id salesforceRecordId) {
		return this.setNewRequest(body, INBOUND_REQUEST, salesforceRecordId);
	}

	public Integration_Callout_Body__c setOutboundRequest(Object body, Id salesforceRecordId) {
		return this.setNewRequest(body, OUTBOUND_REQUEST, salesforceRecordId);
	}

	private Integration_Callout_Body__c setNewRequest(Object body, String type, Id salesforceRecordId) {
		Integration_Callout_Body__c newRequest = new Integration_Callout_Body__c ();
		String serializedBody = JSON.serializePretty(body, false);

		//In case that the serialized request exceed the total characters allowed for the body field, create a substring
		if (serializedBody.length() > 10000) {
			serializedBody = serializedBody.subString(0,10000);
		}

		newRequest.Request_Type__c = type;
		newRequest.Request_Body__c = serializedBody;
		newRequest.Salesforce_Record_Id__c = salesforceRecordId;
		this.calloutBodies.add(newRequest);
		return newRequest;
	}

	public void saveRequests() {

		upsert this.integrationLog;

		if (!this.calloutBodies.isEmpty()) {
			for (Integration_Callout_Body__c integrationBody : this.calloutBodies) {
				integrationBody.Marketing_Finance_Integration_Log__c = this.integrationLog.Id;
				integrationBody.Response_Code__c = this.statusCode;
				integrationBody.Response_Error_Message__c = this.errorMessage;
			}
			upsert calloutBodies;
		}
	}	

}