force-app/main/default/objects/API_Configuration__c/API_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>API keys and parameters required for Microservice calls</description>
    <label>API Configuration</label>
</CustomObject>

force-app/main/default/objects/API_Configuration__c/fields/API_Host__c.field-meta.xml
<CustomField>
    <fullName>API_Host__c</fullName>
    <description>The base URL for all API calls</description>
    <inlineHelpText>The base URL for all API calls</inlineHelpText>
    <label>API Host</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>The API Key</description>
    <inlineHelpText>The API Key</inlineHelpText>
    <label>API Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Customer_Create__c.field-meta.xml
<CustomField>
    <fullName>Customer_Create__c</fullName>
    <description>The URL suffix for the User Create service</description>
    <inlineHelpText>The URL suffix for the User Create service</inlineHelpText>
    <label>Customer Create</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Customer_Read_GUID__c.field-meta.xml
<CustomField>
    <fullName>Customer_Read_GUID__c</fullName>
    <description>The URL suffix for the Customer Read using GUID service</description>
    <inlineHelpText>The URL suffix for the Customer Read using GUID service</inlineHelpText>
    <label>Customer Read GUID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Debug_Mode__c.field-meta.xml
<CustomField>
    <fullName>Debug_Mode__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate whether api calls should be logged.</description>
    <inlineHelpText>Flag to indicate whether api calls should be logged.</inlineHelpText>
    <label>Debug Mode</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Email_Change__c.field-meta.xml
<CustomField>
    <fullName>Email_Change__c</fullName>
    <description>End point suffix for Email Change service</description>
    <inlineHelpText>End point suffix for Email Change service</inlineHelpText>
    <label>Email Change</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Enum_Read__c.field-meta.xml
<CustomField>
    <fullName>Enum_Read__c</fullName>
    <description>The URL suffix for the Enumerator Read service</description>
    <inlineHelpText>The URL suffix for the Enumerator Read service</inlineHelpText>
    <label>Enum Read</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Lease_List__c.field-meta.xml
<CustomField>
    <fullName>Lease_List__c</fullName>
    <description>End-point to return list of lease details for a given Brand/Village</description>
    <inlineHelpText>End-point to return list of lease details for a given Brand/Village</inlineHelpText>
    <label>Lease List</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Lookup_Read__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Read__c</fullName>
    <description>The URL suffix for the Customer API Lookup Read services (genders, villages ..etc)</description>
    <inlineHelpText>The URL suffix for the Customer API Lookup Read services (genders, villages ..etc)</inlineHelpText>
    <label>Lookup Read</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Preference_Create__c.field-meta.xml
<CustomField>
    <fullName>Preference_Create__c</fullName>
    <label>Preference Create</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Preference_Read__c.field-meta.xml
<CustomField>
    <fullName>Preference_Read__c</fullName>
    <label>Preference Read</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Village__c/fields/CertSales_CertPeriod_Cut_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_CertPeriod_Cut_Off_Days__c</fullName>
    <inlineHelpText>The number of days from the period end to the deadline for Brand Head Offices to submit the Sales Certification.</inlineHelpText>
    <label>CertSales CertPeriod Cut Off Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/CertSales_Report_Sales_Grace_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>CertSales_Report_Sales_Grace_Period_Days__c</fullName>
    <inlineHelpText>The number of days that brand stores have to enter Daily Sales after the period end before the Daily Sales are no longer editable.  (Note - Daily Sales records are also no longer editable by the brand stores after Sales Certification submission)</inlineHelpText>
    <label>CertSales Report Sales Grace Period Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Village__c/fields/Village_Code__c.field-meta.xml
<CustomField>
    <fullName>Village_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the 2 digit Village Code used to identify the Village</inlineHelpText>
    <label>Village Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/apiLeaseTest.cls
@isTest
public class apiLeaseTest {

    private static Account account = new Account();
    private static API_Configuration__c settings = new API_Configuration__c();
    private static MultiStaticResourceCalloutMock multimock = new MultiStaticResourceCalloutMock();
    private static Village__c village1 = new Village__c();
    private static string dateString = '';
    
    static void setupData(){

		account = TestData_Account.setupBrandAccount(1, true);
        
        //create village 1
        village1 = new Village__c();
        village1.Name = 'TestVillage1'; 		
        village1.Village_Code__c = 'AA';
		village1.CertSales_CertPeriod_Cut_Off_Days__c = 1;
		village1.CertSales_Report_Sales_Grace_Period_Days__c = 1;
        insert village1;
        village1 = [select name, id, Village_Code__c from Village__c where Village_Code__c = 'AA' LIMIT 1];   	
               
		dateString = string.valueOfGmt(system.today());
        dateString = dateString.split(' ')[0].replace('-', '');
        
        setupCustomSettings();
        
    }    
    
	static void setupCustomSettings(){

		settings.name = 'API Config LIVE';
    	settings.Api_host__c = 'https://test.apiCustomer.com';
    	settings.Api_key__c = '123456';
    	settings.Customer_create__c = '/createCustomer';
    	settings.Customer_read_GUID__c = '/readCustomer';
    	settings.Debug_mode__c = true;
    	settings.Enum_read__c = '/enumRead';
    	settings.Lookup_read__c = '/lookupRead';
    	settings.Preference_create__c = '/prefCreate';
    	settings.Preference_read__c = '/prefRead';
    	settings.Email_Change__c = '/emailChange';
        settings.Lease_List__c = '/leaseList';

    	insert settings;				
	}
    
    static testMethod void unitTest(){
        
        setupData();
        
		multimock.setStatusCode(200);
		multimock.setHeader('Content-Type', 'application/xml');
     	
     	// Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, multimock);
        
        test.startTest();

            multimock.setStaticResource(settings.Api_Host__c + settings.Lease_List__c + '/' + 'SF_TEST' + '|' + Village1.Village_Code__c + '|' + dateString, 'TestAPI_LeaseList1');        
        	
        	string xmlLease = apiService.readLeaseList('SF_TEST', Village1.Village_Code__c, system.today());
        	list<apiLease.cls_LeaseItem> leaseList = apiLease.parseXML(xmlLease);
system.debug('@@@@  ' + leaseList);        
        	
        	system.assertEquals(leaseList.size(), 1);
        
		test.stopTest();        
        
    }
    
}