force-app/main/default/objects/Group_Booking__c/Group_Booking__c.object-meta.xml
<CustomObject>
    <description>Tourism (B2T) Object :: Used for recording MICE group bookings</description>
    <label>Booking/Partnership</label>
    <nameField>
        <displayFormat>GBI{0000000000}</displayFormat>
        <label>Group Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings/Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Booking__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the name of the company or agency responsible for organising this event</inlineHelpText>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Please select a Tourism or Marketing Partner.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Tourism</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Marketing_Partner</value>
        </filterItems>
        <infoMessage>Please select a Tourism or Marketing Partner.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings/Partnerships</relationshipLabel>
    <relationshipName>Group_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Booking__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipName>Bookings_Partnerships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Activity__c/Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds all Marketing Activities.....</description>
    <label>Marketing Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Activity__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Please select a Tourism or Marketing Partner.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Tourism</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Marketing_Partner</value>
        </filterItems>
        <infoMessage>Please select a Tourism or Marketing Partner.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing Activities</relationshipLabel>
    <relationshipName>Marketing_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/Tourism_Partner_Projection__c.object-meta.xml
<CustomObject>
    <description>Projected Tourism partner visit contributions</description>
    <label>Tourism Partner Projection</label>
    <nameField>
        <displayFormat>TPP-{000000}</displayFormat>
        <label>Tourism Partner Projection Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tourism Partner Projections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/April_Actual__c.field-meta.xml
<CustomField>
    <fullName>April_Actual__c</fullName>
    <description>Actual numbers as calculated from visits</description>
    <inlineHelpText>Actual numbers as calculated from visits</inlineHelpText>
    <label>April Actual</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/August_Actual__c.field-meta.xml
<CustomField>
    <fullName>August_Actual__c</fullName>
    <description>Actual numbers as calculated from visits</description>
    <inlineHelpText>Actual numbers as calculated from visits</inlineHelpText>
    <label>August Actual</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/December_Actual__c.field-meta.xml
<CustomField>
    <fullName>December_Actual__c</fullName>
    <description>Actual numbers as calculated from visits</description>
    <inlineHelpText>Actual numbers as calculated from visits</inlineHelpText>
    <label>December Actual</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/February_Actual__c.field-meta.xml
<CustomField>
    <fullName>February_Actual__c</fullName>
    <description>Actual numbers as calculated from visits</description>
    <inlineHelpText>Actual numbers as calculated from visits</inlineHelpText>
    <label>February Actual</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/January_Actual__c.field-meta.xml
<CustomField>
    <fullName>January_Actual__c</fullName>
    <description>Actual numbers as calculated from visits</description>
    <inlineHelpText>Actual numbers as calculated from visits</inlineHelpText>
    <label>January Actual</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/July_Actual__c.field-meta.xml
<CustomField>
    <fullName>July_Actual__c</fullName>
    <description>Actual numbers as calculated from visits</description>
    <inlineHelpText>Actual numbers as calculated from visits</inlineHelpText>
    <label>July Actual</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/June_Actual__c.field-meta.xml
<CustomField>
    <fullName>June_Actual__c</fullName>
    <description>Actual numbers as calculated from visits</description>
    <inlineHelpText>Actual numbers as calculated from visits</inlineHelpText>
    <label>June Actual</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/March_Actual__c.field-meta.xml
<CustomField>
    <fullName>March_Actual__c</fullName>
    <description>Actual numbers as calculated from visits</description>
    <inlineHelpText>Actual numbers as calculated from visits</inlineHelpText>
    <label>March Actual</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/May_Actual__c.field-meta.xml
<CustomField>
    <fullName>May_Actual__c</fullName>
    <description>Actual numbers as calculated from visits</description>
    <inlineHelpText>Actual numbers as calculated from visits</inlineHelpText>
    <label>May Actual</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/November_Actual__c.field-meta.xml
<CustomField>
    <fullName>November_Actual__c</fullName>
    <description>Actual numbers as calculated from visits</description>
    <inlineHelpText>Actual numbers as calculated from visits</inlineHelpText>
    <label>November Actual</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/October_Actual__c.field-meta.xml
<CustomField>
    <fullName>October_Actual__c</fullName>
    <description>Actual numbers as calculated from visits</description>
    <inlineHelpText>Actual numbers as calculated from visits</inlineHelpText>
    <label>October Actual</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/Partnership_Account__c.field-meta.xml
<CustomField>
    <fullName>Partnership_Account__c</fullName>
    <description>The Tourism partner</description>
    <inlineHelpText>The Tourism partner</inlineHelpText>
    <label>Partnership Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Tourism accounts can have projections</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tourism</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tourism Partner Projections</relationshipLabel>
    <relationshipName>Tourism_Partner_Projections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/Projected_Year__c.field-meta.xml
<CustomField>
    <fullName>Projected_Year__c</fullName>
    <description>The year for which the projections are</description>
    <inlineHelpText>The year for which the projections are</inlineHelpText>
    <label>Projected Year</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
                <default>true</default>
                <label>2020</label>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
                <isActive>false</isActive>
                <label>2017</label>
            </value>
            <value>
                <fullName>2018</fullName>
                <isActive>false</isActive>
                <label>2018</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/September_Actual__c.field-meta.xml
<CustomField>
    <fullName>September_Actual__c</fullName>
    <description>Actual numbers as calculated from visits</description>
    <inlineHelpText>Actual numbers as calculated from visits</inlineHelpText>
    <label>September Actual</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tourism_Partner_Projection__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <description>The village that this projection is for</description>
    <inlineHelpText>The village that this projection is for</inlineHelpText>
    <label>Village</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Village</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Village__c/Village__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold the details specific to a village such as sales area, standard contract/lease terms, default brand performance targets, signatories etc.</description>
    <label>Village</label>
    <nameField>
        <label>Village Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Villages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>v-{00000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Group_Booking__c.field-meta.xml
<CustomField>
    <fullName>Group_Booking__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Booking/Partnership</label>
    <referenceTo>Group_Booking__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Number_of_Guests__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Guests__c</fullName>
    <description>Not all guests will receive a VIP card so this field is used to track qualified guests (with or without a VIP Card)</description>
    <inlineHelpText>Enter the total numbers of guests in visit</inlineHelpText>
    <label>Number of Adults</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Partnership_Promotion__c.field-meta.xml
<CustomField>
    <fullName>Partnership_Promotion__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partnership Promotion</label>
    <referenceTo>Marketing_Activity__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Village</label>
    <referenceTo>Village__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Visit_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date_Time__c</fullName>
    <label>Check In Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/globalValueSets/Village.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bicester</fullName>
    </customValue>
    <customValue>
        <fullName>Fidenza</fullName>
    </customValue>
    <customValue>
        <fullName>Ingolstadt</fullName>
    </customValue>
    <customValue>
        <fullName>Kildare</fullName>
    </customValue>
    <customValue>
        <fullName>La Roca</fullName>
    </customValue>
    <customValue>
        <fullName>Las Rozas</fullName>
    </customValue>
    <customValue>
        <fullName>La Vallée</fullName>
    </customValue>
    <customValue>
        <fullName>Maasmechelen</fullName>
    </customValue>
    <customValue>
        <fullName>Shanghai</fullName>
    </customValue>
    <customValue>
        <fullName>Suzhou</fullName>
    </customValue>
    <customValue>
        <fullName>Wertheim</fullName>
    </customValue>
    <description>A list of all the villages</description>
    <masterLabel>Village</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TourismPartnerProjectionUtils.cls
public with sharing class TourismPartnerProjectionUtils {

	public static void UpdatePartnerProjections(Set<Id> AccountIds, String year,Set<Integer> Months){

		// not particularly great code, but we are going to call the accounts, month by month
		for(Integer x = 1; x < 13; x++){
			if(Months.contains(x)){
			System.debug('About to call future method : AccountIds = ' + AccountIds);
			FutureUpdatePartnerProjections(AccountIds, x, year);
		}
		}

	}
	// goes through the list of all visits for an account, and updates the projections for that partner, to update the 'Actuals'
	// this will only calculate the current years numbers
	@future
	public static void FutureUpdatePartnerProjections(Set<Id> AccountIds, Integer Month, String year){
		// lets get todays date, and use the datepart year
		String ThisYear = year ; 
		Integer intYear = Integer.valueOf(year);
		// Select Id, Date__c from Object where CALENDAR_MONTH(Date__c) == MonthInVF

		System.debug('AccountIds === ' + AccountIds.size() + ' ----- ' + AccountIds);
		// lets get all the visits for the accounts in question
		List<Visit__c> allVisits = [SELECT ID, Partnership_Promotion__r.Partner__c , Group_Booking__r.Organisation__c,Number_of_Guests__c,Visit_Date_Time__c, Village__r.Name FROM Visit__c WHERE (Partnership_Promotion__r.Partner__c in :AccountIds OR Group_Booking__r.Organisation__c in :AccountIds) AND Number_Of_Guests__c > 0 AND CALENDAR_MONTH(Visit_Date_Time__c )  = :Month AND CALENDAR_YEAR(Visit_Date_Time__c) = :intYear];
 		System.debug('allVisits === ' + allVisits.size() + ' ----- ' + allVisits);
		// lets build a map of lists
		Map<ID, List<Visit__c>> partnerVisitMap = new Map<ID, List<Visit__c>>();
		for (Visit__c vst : allVisits) {
			// fist lets use a device to get the account ID
			ID accID = null;
			if(vst.Partnership_Promotion__r.Partner__c != null)
			{
				accID = vst.Partnership_Promotion__r.Partner__c;
			}
			else if(vst.Group_Booking__r.Organisation__c != null){
				accID = vst.Group_Booking__r.Organisation__c;
			}
			if(accID != null){
			    List<Visit__c> listSo = partnerVisitMap.get(accID);
			    if (listSo == null) {
			        listSo = new List<Visit__c>();
			        partnerVisitMap.put(accID, listSo);
			    }
			    System.debug('Adding Visit to acc === ' + vst);
			    listSo.add(vst);
			}
			// if it is null, then its a dud visit....
		}

		// now we have a nice map of visits by account.
		// next we will need to know what projections to update
		List<Tourism_Partner_Projection__c> projections = [SELECT ID, Name,Partnership_Account__c, Village__c FROM Tourism_Partner_Projection__c WHERE Projected_Year__c = :ThisYear AND Partnership_Account__c in :partnerVisitMap.keyset()];
		// we have to assume that there is only 1 projection per year, per partner (if there are more, then it will only update the first)
		List<Tourism_Partner_Projection__c> projectionsforupdate = new List<Tourism_Partner_Projection__c>();
		for(ID accID :partnerVisitMap.keyset()){
			// need to try to do it by village too
			Map<String,Map<String,Integer>> visitByVillageByMonth = new Map<String,Map<String,Integer>>();


		//	Map<String,Integer> visitGuestsByMonthMap = new Map<String,Integer>();
			// now we get the visits
			List<Visit__c> visits = partnerVisitMap.get(accID);
			// now loop the visits
			for(Visit__c vst :visits){

				// check if this village has been added yet
				if(visitByVillageByMonth.get(vst.Village__r.Name) != null){
					// then the village does exist, and we need to add to the guests
				}
				else
				{
					// means we need to add the village
					visitByVillageByMonth.put(vst.Village__r.Name,new Map<String,Integer>());
				}

				// now we need to count the number of guests by month
				Map<String,Integer> visitGuestsByMonthMap = visitByVillageByMonth.get(vst.Village__r.Name);
				Integer guestcount = visitGuestsByMonthMap.get(vst.Visit_Date_Time__c.format('MMMMM'));
			    if (guestcount == null) {				    	        
			        visitGuestsByMonthMap.put(vst.Visit_Date_Time__c.format('MMMMM'), Integer.Valueof(vst.Number_Of_Guests__c)); // just making the count 0 and will provide the actual value after
			    }
			    else
			    {
			    	guestcount += Integer.Valueof(vst.Number_Of_Guests__c);
			    	visitGuestsByMonthMap.put(vst.Visit_Date_Time__c.format('MMMMM'), guestcount); 
				}
				// then add the map to the village
				visitByVillageByMonth.put(vst.Village__r.Name,visitGuestsByMonthMap);
				System.debug('visitGuestsByMonthMap === ' + visitGuestsByMonthMap);
			}

			// now we have finished looping all the visits for that account, we can update the projections
			for(Tourism_Partner_Projection__c proj :projections){
				// lets get the projection for this account and village
				if(proj.Partnership_Account__c == accID){
					Map<String,Integer> visitGuestsByMonthMap = visitByVillageByMonth.get(proj.Village__c);
					System.debug('proj === ' + proj);
					// now we can update each field
					// need to get the value by village and month....
					if(Month == 1){
						proj.January_Actual__c  = visitGuestsByMonthMap.get('January');}
					if(Month == 2){
					proj.February_Actual__c = visitGuestsByMonthMap.get('February');}
					if(Month == 3){
					proj.March_Actual__c = visitGuestsByMonthMap.get('March');}
					if(Month == 4){
					proj.April_Actual__c = visitGuestsByMonthMap.get('April');}
					if(Month == 5){
					proj.May_Actual__c = visitGuestsByMonthMap.get('May');}
					if(Month == 6){
					proj.June_Actual__c = visitGuestsByMonthMap.get('June');}
					if(Month == 7){
					proj.July_Actual__c = visitGuestsByMonthMap.get('July');}
					if(Month == 8){
					proj.August_Actual__c = visitGuestsByMonthMap.get('August');}
					if(Month == 9){
					proj.September_Actual__c = visitGuestsByMonthMap.get('September');}
					if(Month == 10){
					proj.October_Actual__c = visitGuestsByMonthMap.get('October');}
					if(Month == 11){
					proj.November_Actual__c = visitGuestsByMonthMap.get('November');}
					if(Month == 12){
					proj.December_Actual__c = visitGuestsByMonthMap.get('December');}
					

					projectionsforupdate.add(proj);
				}
			}
		}
		update projectionsforupdate;
	}
}